### ISSUE TITLE
Service Fabric DownstreamHeaderTransform  "{DownstreamBaseUrl}, {BaseUrl}" config not working.

### ISSUE THREAD

**Issue by ovidiubuligan** [ThreeMammals/Ocelot#1003]
## Expected Behavior / New Feature
It should be possible to handle 302 redirects from within **Service Fabric** with the config taken from the documentation:

```json
"GlobalConfiguration": {
    "RequestIdKey": "OcRequestId",
    "ServiceDiscoveryProvider": {
      "Host": "localhost",
      "Port": 19081,
      "Type": "ServiceFabric"
    },
    "BaseUrl": "https://localhost:5000"
  },
  "ReRoutes": [
    {
      "DownstreamPathTemplate": "/{url}",
      "DownstreamScheme": "https",
      "ServiceName": "FrontendFabric/Frontend",
      "UpstreamHttpMethod": [
        "Get",
        "Post",
        "Put"
      ],
      "UpstreamPathTemplate": "/{url}",
      "DownstreamHeaderTransform": {
        "Location": "{DownstreamBaseUrl}, {BaseUrl}"
      },
      "HttpHandlerOptions": {
        "AllowAutoRedirect": false
      }
    }
```

Returning a Redirect from a service behind ocelot will give Location : `http://10.0.0.4/newLocation` . problem is that {DownstreamBaseUrl} is resolved with the naming service Url .

## Actual Behavior / Motivation for New Feature

Location header is not replaced with config "Location": "{DownstreamBaseUrl}, {BaseUrl}".

## Steps to Reproduce the Problem

  1. Create a service fabric app with 2 services  
  2. One service is ocelot configured with `DownstreamHeaderTransform`  and `HttpHandlerOptions`
  3. The other service is a simple http responder with http 302  and Location : "http://10.0.0.5/MyIndex" . This is what Asp net core RedirectToAction("MyIndex")  is returning .
## Specifications

  - Version: 13.5.2
  - Platform: windows  10
  - Subsystem:

**Comment by raman-m** [comment]
How did you solve this problem?
Our [Service Fabric](https://ocelot.readthedocs.io/en/latest/features/servicefabric.html) service discovery feature is not fancy!

Please, report the bug if exists for the latest versions 23.x
