### ISSUE TITLE
Merging configuration and multiple environments

### ISSUE THREAD

**Issue by hiredgunhouse** [ThreeMammals/Ocelot#1004]
What is the point of this line            
`string excludeConfigName = env?.EnvironmentName != null ? $"ocelot.{env.EnvironmentName}.json" : string.Empty;` ?  
Assuming I can have multiple configuration files for different environments  (i.e. Development, Staging, etc.) this means that the configuration for my current environment is ignored while configurations for other environments are actually loaded.
Isn't this the reverse of what should happen?

**Comment by ggoyal-Axum** [comment]
interesting, i recently came across the same. It may not answer your question but here is my take on it.
In order to support environment specific config via config merge, i think we will need 
ocelot.([a-zA-Z0-9]*).{env.EnvrionmentName}.json

**Comment by hiredgunhouse** [comment]
@ggoyal-Axum yes, I think your solution is actually what makes sense and what I need.

Are you, Ocelot guys, fine with that approach? Would like a PR?

**Comment by gboder** [comment]
@ggoyal-Axum I would suggest if you have already implemented the solution on your side please submit a PR with the change to allow Ocelot guys reviewing it and eventually merge into the codebase.

Thanks

**Comment by raman-m** [comment]
@hiredgunhouse 
>Are you, Ocelot guys, fine with that approach? Would like a PR?

A PR for what? Solving your local little problem?

-----
> What is the point of this line            
`string excludeConfigName = env?.EnvironmentName != null ? $"ocelot.{env.EnvironmentName}.json" : string.Empty;` ?  
>Isn't this the reverse of what should happen? 

It is reserved to skip/exclude environment config file during merging operation. But env file will be attached to the pipeline like this pseudo code:
```
ConfigureAppConfiguration((hostingContext, config) =>
{
    config
        .SetBasePath(hostingContext.HostingEnvironment.ContentRootPath)
        .AddJsonFile("appsettings.json", true, true)
        .AddJsonFile($"appsettings.{hostingContext.HostingEnvironment.EnvironmentName}.json", true, true)
        .AddJsonFile("ocelot.json")

        // this is excludeConfigName !!!
        .AddJsonFile($"configuration.{hostingContext.HostingEnvironment.EnvironmentName}.json")

        .AddEnvironmentVariables();
})
```
But the file will be attached and `IConfiguration` service will allow you dynamically apply env values by internal provider.

Have you read carefully the following sections of the [Configuration](https://ocelot.readthedocs.io/en/latest/features/configuration.html) feature docs?
- [Multiple Environments](https://ocelot.readthedocs.io/en/latest/features/configuration.html#multiple-environments)
- [Merging Configuration Files](https://ocelot.readthedocs.io/en/latest/features/configuration.html#merging-configuration-files)

Pay attention, in upcoming new version [23.2](https://github.com/ThreeMammals/Ocelot/releases/tag/23.2.0) we've upgraded merging feature but entire algorithm of merging the same.
See more in PR  #1227

**Comment by raman-m** [comment]
> @ggoyal-Axum commented [on Sep 6, 2019](https://github.com/ThreeMammals/Ocelot/issues/1004#issuecomment-528761343)

Sorry! But we won't do that! It will be massive breaking change.
All logic is much better now after merging #1227. We support static injection of main 3 files from any location! If you not sure in something you can save file to different folder and inject its location via optional parameters.

**Comment by raman-m** [comment]
@hiredgunhouse @ggoyal-Axum 
Please watch for [February'24](https://github.com/ThreeMammals/Ocelot/milestone/5) release. We will release it in a week or two.
New overloaded methods should help you, guys.
