### ISSUE TITLE
RegEx in ReRoutes

### ISSUE THREAD

**Issue by dnx231** [ThreeMammals/Ocelot#1005]
Hi,
is it possible to use RegEx in UpstreamPathTemplate?

```json
{
  "Routes": [
    {
      "DownstreamPathTemplate": "/api/report/get?reportid={reportId}",
      "DownstreamScheme": "http",
      "DownstreamHostAndPorts": [
        {
          "Host": "localhost",
          "Port": 5001
        }
      ],
      "UpstreamPathTemplate": "/get?reportid={reportId}" // all reportIds from 1-3
    },
    {
      "DownstreamPathTemplate": "/api/report/get?reportid={reportId}",
      "DownstreamScheme": "http",
      "DownstreamHostAndPorts": [
        {
          "Host": "localhost",
          "Port": 5002
        }
      ],
      "UpstreamPathTemplate": "/get?reportid={reportId}" // all reportIds from 4-5
    }
  ],

  "GlobalConfiguration": {
    "BaseUrl": "http://localhost:5000"
  }
}
```

The First Downstream Host only returns Reports from ID 1-3, the second from 4-5...

**Comment by szymonpiekny** [comment]
Something new?

**Comment by raman-m** [comment]
@dnx231 
> is it possible to use RegEx in UpstreamPathTemplate?

No, impossible! Ocelot will crash.
Consider to use [Catch-All](https://ocelot.readthedocs.io/en/latest/features/routing.html#catch-all) route definition.
Be very careful when experimenting with query string placeholders! We recommend to use [Catch All Query String](https://ocelot.readthedocs.io/en/latest/features/routing.html#catch-all-query-string) feature to have less pain with placeholders.
After that you may develop [Delegating Handler](https://ocelot.readthedocs.io/en/latest/features/delegatinghandlers.html) to do whatever you want with your requests, including URL and query string analysis by regular expressions.
But especially in your scenario, it's better to inject [custom middleware](https://ocelot.readthedocs.io/en/latest/features/middlewareinjection.html) and attach it as a `PreQueryStringBuilderMiddleware` overriding.
