### ISSUE TITLE
Missing claimsToDownstreamPath in releases code

### ISSUE THREAD

**Issue by Fabman08** [ThreeMammals/Ocelot#1010]
Hi guys,

I'm trying to use the "ChangeDownstreamPathTemplate" to forward some claims value to destination api following your instruction on your [Documentation](https://ocelot.readthedocs.io/en/latest/features/claimstransformation.html), but actually it doesn't work.
I've cloned the Development branch and it works; I've took a look in the code and I've found in ReRouteCreator class at the SetUpDownstreamReRoute method the following code
`
var claimsToDownstreamPath = _claimsToThingCreator.Create(fileReRoute.ChangeDownstreamPathTemplate);
`
but changing branch to release/13.5.2 or 13.6.0 or 13.7.0 this line is missing so the feature doesnt' work!

Are you aware of this missing code?

Thank you!
## Specifications

  - Version: 13.5.2 / 13.6.0 / 13.7.0
  - Platform: .net Core 2.2

**Comment by EngRajabi** [comment]
ChangeDownstreamPathTemplate not working
version 13.5.2

**Comment by JakubSlonka** [comment]
Any news on this issue? It seems like it could be easily fixed for next release? It would be really helpful to have this functionality.

**Comment by maradonasu** [comment]
Version13.8.0 is fixed
