### ISSUE TITLE
Can't get User requested host and port in Microservices

### ISSUE THREAD

**Issue by hamedmaleki1366** [ThreeMammals/Ocelot#1011]
hi all.

## How can i get user requested Url in Microservices?

i have ocelot in domain.com and also i set sub1.domain.com and sub2.domain.com to domain.com.

now i want get sub1.domain.com or sub2.domain.com in ASP.Net Core Microservice to know what data user wants.

what should i do ? 

how can i pass dynamic subdomain name to internal microservice throght Ocelot??

this is my ReRoutes : 
 `"DownstreamPathTemplate": "/api/authentication/signin",
      "DownstreamScheme": "http",
      "UpstreamPathTemplate": "/authentication/signin",
      "UpstreamHttpMethod": [ "Get", "POST" ],
      "DownstreamHostAndPorts": [
        {
          "Host": "localhost",
          "Port": 63981
        }
      ],
      "UpstreamHeaderTransform": {
        "X-Forwarded-For": "{RemoteIpAddress}"
      },      
      "HttpHandlerOptions": {
        "AllowAutoRedirect": false
      }`

and also i wrote this code for ocelot but didn't work

` var configuration = new OcelotPipelineConfiguration
                    {
                        PreQueryStringBuilderMiddleware = async (ctx, next) =>
                        {
                            ctx.DownstreamRequest.Headers.Host = ctx.HttpContext.Request.Host.Host;                            
                            await next.Invoke();
                        }
                    };

                    app.UseWebSockets();
                    app.UseAuthentication();
                    app.UseOcelot(configuration).Wait();
`

**Comment by Leandropintogit** [comment]
> hi all.
> 
> ## How can i get user requested Url in Microservices?
> i have ocelot in domain.com and also i set sub1.domain.com and sub2.domain.com to domain.com.
> 
> now i want get sub1.domain.com or sub2.domain.com in ASP.Net Core Microservice to know what data user wants.
> 
> what should i do ?
> 
> how can i pass dynamic subdomain name to internal microservice throght Ocelot??
> 
> this is my ReRoutes :
> `"DownstreamPathTemplate": "/api/authentication/signin", "DownstreamScheme": "http", "UpstreamPathTemplate": "/authentication/signin", "UpstreamHttpMethod": [ "Get", "POST" ], "DownstreamHostAndPorts": [ { "Host": "localhost", "Port": 63981 } ], "UpstreamHeaderTransform": { "X-Forwarded-For": "{RemoteIpAddress}" }, "HttpHandlerOptions": { "AllowAutoRedirect": false }`
> 
> and also i wrote this code for ocelot but didn't work
> 
> ` var configuration = new OcelotPipelineConfiguration
> {
> PreQueryStringBuilderMiddleware = async (ctx, next) =>
> {
> ctx.DownstreamRequest.Headers.Host = ctx.HttpContext.Request.Host.Host;
> await next.Invoke();
> }
> };
> 
> ```
>                 app.UseWebSockets();
>                 app.UseAuthentication();
>                 app.UseOcelot(configuration).Wait();
> ```
> 
> `

Hi

I solved it that way

var configuration = new OcelotPipelineConfiguration
            {
                PreQueryStringBuilderMiddleware = async (context, next) =>
                {
                    var host = $"{context.HttpContext.Request.Scheme}://{context.HttpContext.Request.Host.Value}";
                    context.DownstreamRequest.Headers.Add("OriginalHost", host);

                    await next.Invoke();
                }
            };

And int he MicroService

`
var originalHost = request.Headers["OriginalHost"].ToString();
                if (string.IsNullOrWhiteSpace(originalHost))
                    originalHost = $"{request.Scheme}://{request.Host.Value}";`
