### ISSUE TITLE
Can't use UseTracing in GlobalConfiguration

### ISSUE THREAD

**Issue by huanbd** [ThreeMammals/Ocelot#1013]
## Steps to Reproduce the Problem

  1. Set UseTracing in HttpHandlerOptions of GlobalConfiguration

   Have not log trace inserted to Butterfly

**Comment by raman-m** [comment]
Why not to contribute? We have no time for such implementations.

@huanbd Will you contribute?

Butterfly is popular in China only.
We have no final decision on Butterfly tracing but we will make a team decision during this year...

@ggnaegi @RaynaldM  FYI
