### ISSUE TITLE
Ocelot is not routing the request correctlym in Docker containers

### ISSUE THREAD

**Issue by rwin** [ThreeMammals/Ocelot#1016]
## Expected Behavior
I have a solution with two projects. One project is the WebApi and the  other one is the WebGateway (Ocelot). With the Docker-Compose file i start the services and also Consul. 

In the WebGateway project I have two Ocelot configuration files. One is working properly (configurationWorking.json) and the other one unfortunately not (configurationNOTworking.json). You can switch the configuration file to see the behavior.

The only difference between these two files is the configuration of the downstream. If I use the configuration with "DownstreamHostAndPorts" everything works as expected. If I use only "ServiceName" as mentioned in the documentation. The routing to the WebApi does not work. 

## Actual Behavior / Motivation for New Feature
Routing should work with Ocelot, Consul, WebApi and Docker-Containers.

## Steps to Reproduce the Problem

  1. Run Docker-Compose file and build the containers
  2. Open Browser 
       - http://localhost:8500 open Consul --> working
       - http://localhost:7005/api/v1/values starts the WebApi --> working
       - http://localhost:7000/api/service/values --> NOT working
  3. Stop container
  4. Change configuration file in WebGateway in Program.cs (line 24/25)
  5. Create and run Docker-Containers again and open same websites. Everything is working as expected.

## Specifications

  - Version: latest versions
  - Example: https://github.com/rwin/OcelotConsulDockerTest

**Comment by daisen** [comment]
#909

**Comment by raman-m** [comment]
> ## Steps to Reproduce the Problem
> 
>   1. Run Docker-Compose file and build the containers
>   2. Open Browser 
>        - http://localhost:8500 open Consul --> working
>        - http://localhost:7005/api/v1/values starts the WebApi --> working
>        - http://localhost:7000/api/service/values --> NOT working
>        

Were you seriously testing your docker compose hosts from the browser? :rofl: 
If your gateway app was added to docker compose network then you might use compose config **host names**!

------

> ## Specifications
>   - Example: https://github.com/rwin/OcelotConsulDockerTest
> 

Your repo was deleted! Link doesn't work! We can't review your code!
Sorry, we can't help you!
