### ISSUE TITLE
asp api controller post method from body

### ISSUE THREAD

**Issue by EngRajabi** [ThreeMammals/Ocelot#1021]
run ocelot 13.5.2
microservice 2.2
post method, from body parameter
error : {
    "type": "https://tools.ietf.org/html/rfc7231#section-6.5.13",
    "title": "Unsupported Media Type",
    "status": 415,
    "traceId": "0HLPUDC9Q7B3O:00000004"
}

**Comment by EngRajabi** [comment]
if used nuget package https://github.com/getsentry/sentry-dotnet, this bug will occur

**Comment by EngRajabi** [comment]
Using UseSentry next to Ocelot api gateway is problematic

**Comment by raman-m** [comment]
Interesting fairy tales!

**Comment by raman-m** [comment]
> Using UseSentry next to Ocelot api gateway is problematic

Ocelot team is not responsible for your third-party integrations with exotic protocols and libs.
We care and support only the following protocols aka schemes
- `http` and `https`
- `ws` and `wss` + SignalR `ws` over `http`

[Sentry SDK for .NET](https://github.com/getsentry/sentry-dotnet) is an interesting project, but we don't have any partnership with them, and don't understand why we should have to?

**Comment by EngRajabi** [comment]
This problem is due to the use of EnableBuffering(). I don't use sentry anymore. But using EnableBuffering() was causing problems.

**Comment by raman-m** [comment]
Please continue your ASP.NET experiments asking your development team...
Regarding buffering... in current Ocelot kernel we switched off this mode in favor of streaming mode.
