### ISSUE TITLE
System.Net.Sockets.SocketException: Connection refused

### ISSUE THREAD

**Issue by dalyl** [ThreeMammals/Ocelot#1023]
## Disaster tolerance and duplication

I have more than one machine, one of which is out of order, how to find the available machine automatically（Using static routing tables）

##  Next Service

For example: Nginx  => proxy_next_upstream

**Comment by raman-m** [comment]
If I understood you correctly, you meant Health Checks?
Use Health Checks! This is Microservices philosophy.  
But Ocelot has no implemented Health Checks feature...
These days we are discussing this feature with the team, see [the link to 1041](https://github.com/ThreeMammals/Ocelot/issues/1041#issuecomment-2002032363)

**Comment by raman-m** [comment]
Since your problem is not very well described, I'm going to close it...
Watch for related open issues plz!

**Comment by raman-m** [comment]
And it seems, you love [YARP](https://github.com/dalyl/reverse-proxy)...
Please, love it more! :angry:
