### ISSUE TITLE
Mark Issues With Meaningful Labels

### ISSUE THREAD

**Issue by catcherwong** [ThreeMammals/Ocelot#1024]
Hi all,

Maybe adding some labels for the issues can help people to find out what they need quickly.

Creating some new labels, such as `area-Routing`, `area-RequestAggregation`, `area-RateLimiting` . ect.   

After labeling the issues, people can know the main topic of an issue in the issues page.

Here is a sample of AspNetCore 

https://github.com/aspnet/AspNetCore/issues?q=is%3Aissue+is%3Aopen+label%3Aarea-mvc

**Comment by raman-m** [comment]
Hi Catcher!
How do you do?

Will you return to our repo back to [contribute more](https://github.com/ThreeMammals/Ocelot/commits?author=catcherwong)? :wink:

True fact is that after my joining the Ocelot team in May'23 we had started usage of labels: See [all labels](https://github.com/ThreeMammals/Ocelot/issues/labels)
And I mark Ocelot feature related issues/PR with appropriate label: see [Ocelot feature labels](https://github.com/ThreeMammals/Ocelot/labels?q=Ocelot+feature%3A)

Please, provide your feedback on new labels usage!
And thanks for your suggestion! I found it extremely useful for project management. But your recommendation was read too late.

I hope you will use Ocelot and will open interesting PRs soon. :smile_cat:

**Comment by raman-m** [comment]
Already implemented :rofl:

**Comment by raman-m** [comment]
1024 is magic number! :magic_wand: 
One kilobyte issue :rofl:
