### ISSUE TITLE
.net core 3.0  with ocelot loadtype error 

### ISSUE THREAD

**Issue by winlj** [ThreeMammals/Ocelot#1028]
.net core 3.0 last version

ocelot not run

error:
System.TypeLoadException:“Could not load type 'Microsoft.Extensions.DependencyInjection.MvcJsonMvcCoreBuilderExtensions' from assembly 'Microsoft.AspNetCore.Mvc.Formatters.Json, Version=3.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.”

startup.cs
services.AddControllers().AddNewtonsoftJson();
services.AddOcelot().AddConsul();

**Comment by pablopioli** [comment]
See 
https://github.com/ThreeMammals/Ocelot/issues/1001

this is a known problem caused by Net Core changing the default Json encoder

**Comment by winlj** [comment]
> See
> #1001
> 
> this is a known problem caused by Net Core changing the default Json encoder

I set it exactly the same way, but still prompted the same error.

Microsoft.AspNetCore.Mvc.NewtonsoftJson3.0.0
Ocelot13.8.0-alpha0019

**Comment by zhanghaiboshiwo** [comment]
I also have this problem, setting up NewtonsoftJson3.0.0 is also useless

**Comment by geffzhang** [comment]
Try tracking #1025 for updates.

**Comment by esofar** [comment]
> Try tracking #1025 for updates.
In other words, the .net core 3.0 still can't use ocelot now?

**Comment by letrung-it** [comment]
Hi, did we already fixed this issue yet? or do we have any plans to update to Net Core 3.0?

**Comment by jondmcelroy** [comment]
Currently Ocelot does not work with DotNet Core 3.0, look at #1025 for status.

**Comment by Hbib-drif** [comment]
Same problem

**Comment by winlj** [comment]
Does anyone know when the author can solve this problem?

**Comment by jmezach** [comment]
@winlj We have pull request #1025 ready to go which should fix this issue. We'll have to wait until one of the maintainers can merge it though.

**Comment by TomPallister** [comment]
Ocelot.13.8.0.nupkg
Ocelot.Administration.13.8.0.nupkg
Ocelot.Cache.CacheManager.13.8.0.nupkg
Ocelot.Provider.Consul.13.8.0.nupkg
Ocelot.Provider.Eureka.13.8.0.nupkg
Ocelot.Provider.Kubernetes.13.8.0.nupkg
Ocelot.Provider.Polly.13.8.0.nupkg
Ocelot.Provider.Rafty.13.8.0.nupkg
Ocelot.Tracing.Butterfly.13.8.0.nupkg

Have just released these to NuGet. Should be available in 30 minutes.
