### ISSUE TITLE
net   consul client Stopped maintenance

### ISSUE THREAD

**Issue by mingyangzhu** [ThreeMammals/Ocelot#1035]
now ,.net consul  client stopped maintenance :https://github.com/PlayFab/consuldotnet

ocelot  considered  switch .net consul client?
e.g: https://github.com/Drawaes/CondenserDotNet

**Comment by raman-m** [comment]
What are you talking about?


We use G-Search Consul.NET product: https://consuldot.net/
GitHub repo: https://github.com/G-Research/consuldotnet
NuGet package: https://www.nuget.org/packages/Consul 
`Consul` packages references in our projects: https://github.com/search?q=repo%3AThreeMammals%2FOcelot%20Include%3D%22Consul%22&type=code

Any other questions?
