### ISSUE TITLE
Which nuget package version support netcore3.0？

### ISSUE THREAD

**Issue by jiahengaa** [ThreeMammals/Ocelot#1039]
Which nuget package version support netcore3.0？

**Comment by IMJacky** [comment]
System.TypeLoadException:“Could not load type 'Microsoft.Extensions.DependencyInjection.MvcJsonMvcCoreBuilderExtensions' from assembly 'Microsoft.AspNetCore.Mvc.Formatters.Json, Version=3.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.”

**Comment by LGinC** [comment]
目测今天应该发个预览版出来，支持3.0的

**Comment by 690486439** [comment]
I am also waiting !!!

**Comment by winlj** [comment]
> 目测今天应该发个预览版出来，支持3.0的

除了预览版,依旧不好使

**Comment by LGinC** [comment]
>> 除了预览版,依旧不好使

最新的预览版也不好使啊

**Comment by winlj** [comment]
> > > 除了预览版,依旧不好使
> 
> 最新的预览版也不好使啊

我打错字了,是出了.

**Comment by Hbib-drif** [comment]
Also waiting !

**Comment by winlj** [comment]
> Also waiting !

Waiting in a hurry

**Comment by Jarvan333** [comment]
still not working

**Comment by allanhboy** [comment]
引用13.8.0-alpha0019,并重写OcelotBuilder中添加AddNewtonsoftJson()方法,并重写ServiceCollectionExtensions,使其引用刚重写的类,目前没有发现问题

**Comment by winlj** [comment]
> 引用13.8.0-alpha0019,并重写OcelotBuilder中添加AddNewtonsoftJson()方法,并重写ServiceCollectionExtensions,使其引用刚重写的类,目前没有发现问题

能贴下实现的代码吗?

**Comment by allanhboy** [comment]
在自己的Ocelot项目中添加将源码中OcelotBuilder类和ServiceCollectionExtensions类复制过来,并修改
OcelotBuilder类构造器方法中此段代码

this.MvcCoreBuilder = Services.AddMvcCore()
                  .AddApplicationPart(assembly)
                  .AddControllersAsServices()
                  .AddAuthorization()
                  .AddJsonFormatters();
替换成
this.MvcCoreBuilder = Services.AddMvcCore()
                  .AddApplicationPart(assembly)
                  .AddControllersAsServices()
                  .AddAuthorization()
                  .AddNewtonsoftJson();

这两个类在Ocelot.DependencyInjection命名空间下

**Comment by jiahengaa** [comment]
@allanhboy That's not good idea.

**Comment by sunahr** [comment]
when to expect this release?

**Comment by Mo-ha-mmed** [comment]
Still waiting guys

**Comment by Jarvan333** [comment]
> 在自己的Ocelot项目中添加将源码中OcelotBuilder类和ServiceCollectionExtensions类复制过来,并修改
> OcelotBuilder类构造器方法中此段代码
> 
> this.MvcCoreBuilder = Services.AddMvcCore()
> .AddApplicationPart(assembly)
> .AddControllersAsServices()
> .AddAuthorization()
> .AddJsonFormatters();
> 替换成
> this.MvcCoreBuilder = Services.AddMvcCore()
> .AddApplicationPart(assembly)
> .AddControllersAsServices()
> .AddAuthorization()
> .AddNewtonsoftJson();
> 
> 这两个类在Ocelot.DependencyInjection命名空间下

可行，先将就着用，等更新

**Comment by TomPallister** [comment]
Ocelot.13.8.0.nupkg
Ocelot.Administration.13.8.0.nupkg
Ocelot.Cache.CacheManager.13.8.0.nupkg
Ocelot.Provider.Consul.13.8.0.nupkg
Ocelot.Provider.Eureka.13.8.0.nupkg
Ocelot.Provider.Kubernetes.13.8.0.nupkg
Ocelot.Provider.Polly.13.8.0.nupkg
Ocelot.Provider.Rafty.13.8.0.nupkg
Ocelot.Tracing.Butterfly.13.8.0.nupkg

I have just released....will be available on NuGet in 30 minutes
