### ISSUE TITLE
Ocelot IHostBuilder and IWebHostBuilder issues

### ISSUE THREAD

**Issue by gurelsoycaner** [ThreeMammals/Ocelot#1047]
## Expected Behavior / New Feature
Hi,

I'm having this issue after updating my system to .Net Core 3.0

![image](https://user-images.githubusercontent.com/5128170/67872155-a10e6800-fb42-11e9-8d40-ca2c88a79baf.png)

I need to dynamically create ocelot.json base on my environment but I'm getting this error
**"cannot convert from Microsoft.Extension.Hosting.IHostEnvironment to Microsoft.AspNetCore.Host.IWebHostEnvironment"** 

I find out that ocelot is still using IWebHostBuilder which is for .Net core 2.x instead of IHostBuilder that comes with .Net cor 3.0.

Thanks in advance

**Comment by catcherwong** [comment]
You can use `ConfigureWebHostDefaults` to do that.

Here is a sample that you can take a look.

```cs
public static IHostBuilder CreateHostBuilder(string[] args) =>
              Host.CreateDefaultBuilder(args)
                 .ConfigureWebHostDefaults(webBuilder =>
                 {
                     webBuilder.UseUrls("http://*:9000")
                       .ConfigureAppConfiguration((hostingContext, config) =>
                       {
                           config
                               .SetBasePath(hostingContext.HostingEnvironment.ContentRootPath)
                               .AddJsonFile("ocelot.json")
                               .AddEnvironmentVariables();

                           config.AddOcelot("your folder", hostingContext.HostingEnvironment);

                       })
                      .ConfigureServices(services =>
                      {
                          services.AddOcelot();
                      })
                     .Configure(app =>
                     {
                         app.UseOcelot().Wait();
                     });
                 });            
```

**Comment by gurelsoycaner** [comment]
> You can use `ConfigureWebHostDefaults` to do that.
> 
> Here is a sample that you can take a look.
> 
> ```cs
> public static IHostBuilder CreateHostBuilder(string[] args) =>
>               Host.CreateDefaultBuilder(args)
>                  .ConfigureWebHostDefaults(webBuilder =>
>                  {
>                      webBuilder.UseUrls("http://*:9000")
>                        .ConfigureAppConfiguration((hostingContext, config) =>
>                        {
>                            config
>                                .SetBasePath(hostingContext.HostingEnvironment.ContentRootPath)
>                                .AddJsonFile("ocelot.json")
>                                .AddEnvironmentVariables();
> 
>                            config.AddOcelot("your folder", hostingContext.HostingEnvironment);
> 
>                        })
>                       .ConfigureServices(services =>
>                       {
>                           services.AddOcelot();
>                       })
>                      .Configure(app =>
>                      {
>                          app.UseOcelot().Wait();
>                      });
>                  });            
> ```

Thanks, you've saved my day.

**Comment by maiconheck** [comment]
I had this problem when I trying to split my ocelot config files per microservice, for merge configuration files.
The solution is similar as @gurelsoycaner, but in such case, I just needed this:

[https://stackoverflow.com/a/68415447/5219344](https://stackoverflow.com/a/68415447/5219344)

**Comment by raman-m** [comment]
@gurelsoycaner  Can we close the issue?

**Comment by raman-m** [comment]
> I'm having this issue after updating my system to **.Net Core 3.0**

## .NET Core 3 is not supported
### Outdated issue :exclamation:
