### ISSUE TITLE
Support of Unix Sockets in downstream uri

### ISSUE THREAD

**Issue by akritikos** [ThreeMammals/Ocelot#1052]
## Expected Behavior / New Feature

Support unix sockets as downstream connection uri

## Actual Behavior / Motivation for New Feature

Hassle free setup in unix-based systems, direct usage of existing sockets-based setup instead of having to assign ports

**Comment by raman-m** [comment]
## Oh, my gosh! :hear_no_evil:

**Comment by raman-m** [comment]
Hi Alexandros!
Are you expert in UNIX OS and systems?

What protocol did you mean exactly? A link to proto docs?
What's the problem with current `ws` protocol?
I can't get your concern about ports. Could you please explain us plz?

Add good description of the problem please!

**Comment by raman-m** [comment]
Did you mean this difference?
- [What is the difference between Unix sockets and TCP/IP sockets?](https://serverfault.com/questions/124517/what-is-the-difference-between-unix-sockets-and-tcp-ip-sockets)

This is different protocol and it requires to having stable .NET driver.

**Will you personally contribute to implement this feature in Ocelot?**

**Comment by raman-m** [comment]
@akritikos 
### You have the right to reopen this issue in the future if you come with a PR ready
