### ISSUE TITLE
Bad Request with Ocelot ReRoute using Eureka as Service Provider at LocalHost

### ISSUE THREAD

**Issue by JayChuah95** [ThreeMammals/Ocelot#1053]
## Expected Behavior
Reroute to /api/User/GetStuff

## Actual Behavior
Bad Request - Invalid Hostname
HTTP Error 400. The request hostname is invalid.

## Steps to Reproduce the Problem
Project Link: https://github.com/JayChuah95/AntyChatty/tree/master/AntyChatty
  1. Startup multiple project and go to url 'localhost:10000/Auth/GetStuff'

## My ocelot.json
```
{
  "ReRoutes": [
    {
      "DownstreamPathTemplate": "/api/User/GetStuff",
      "DownstreamScheme": "http",
      "UpstreamPathTemplate": "/Auth/GetStuff",
      "UseServiceDiscovery": true,
      "ServiceName": "AuthService",
      "UpstreamHttpMethod": [ "Get" ]
    },
    {
      "DownstreamPathTemplate": "/api/User/GetAuthorize",
      "DownstreamScheme": "http",
      "UpstreamPathTemplate": "/Auth/GetAuthorize",
      "UseServiceDiscovery": true,
      "ServiceName": "AuthService",
      "UpstreamHttpMethod": [ "Get" ],
      "AuthenticationOptions": {
        "AuthenticationProviderKey": "ApiSecurity",
        "AllowedScopes": []
      }
    }
  ],
  "GlobalConfiguration": {
    "RequestIdKey": "OcRequestId",
    "AdministrationPath": "/administration",
    "ServiceDiscoveryProvider": {
      "Type": "Eureka",
      "Host": "localhost",
      "Port": "8761"
    }
  }
}
```

## AuthService appsettings.json
```
{
  "spring": {
    "application": {
      "name": "AuthService"
    }
  },
  "eureka": {
    "client": {
      "serviceUrl": "http://localhost:8761/eureka",
      "shouldRegisterWithEureka": true,
      "shouldFetchRegistry": true,
      "validateCertificates": false
    },
    "instance": {
      "port": 20000
    }
  },
  "Logging": {
    "LogLevel": {
      "Default": "Warning"
    }
  },
  "AllowedHosts": "*",
  "AppSettings": {
    "Secret": "0265776e-b490-4253-9be4-7d73457700b1"
  }
}
```

## Specifications
  - NuGet: Ocelot 13.5.2, Ocelot.Provider.Eureka 13.5.2, Steeltoe.Discovery.ClientCore 2.3.0

**Comment by JayChuah95** [comment]
Output Message
```
ApiGateway>       Request starting HTTP/1.1 GET http://localhost:10000/Auth/GetStuff  
ApiGateway> info: Ocelot.RateLimit.Middleware.ClientRateLimitMiddleware[0]
ApiGateway>       requestId: 0HLR42UO95R3M:00000001, previousRequestId: no previous request id, message: EndpointRateLimiting is not enabled for /api/User/GetStuff
ApiGateway> info: Ocelot.Authentication.Middleware.AuthenticationMiddleware[0]
ApiGateway>       requestId: 0HLR42UO95R3M:00000001, previousRequestId: no previous request id, message: No authentication needed for /Auth/GetStuff
ApiGateway> info: Ocelot.Authorisation.Middleware.AuthorisationMiddleware[0]
ApiGateway>       requestId: 0HLR42UO95R3M:00000001, previousRequestId: no previous request id, message: /api/User/GetStuff route does not require user to be authorised
ApiGateway> info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
ApiGateway>       Request finished in 7.2071ms 400 text/html; charset=us-ascii
```

**Comment by JayChuah95** [comment]
@catcherwong 
May I know is there any issue on my configuration?
Thanks for the help

**Comment by catcherwong** [comment]
@JayChuah95 Based on your sample, it seems that all things run well.

![bb](https://user-images.githubusercontent.com/8394988/68555627-97053700-0469-11ea-95ee-7a4e07bbe180.png)

**Comment by JayChuah95** [comment]
It seem like there is some issue on my localhost networking routing.
Could you help with this?
As I check on my httperr.log, it doesn't route to my localhost > ::1%0 20000
![image](https://user-images.githubusercontent.com/57252943/68555928-029bd400-046b-11ea-97df-0c0169ee5878.png)

**Comment by JayChuah95** [comment]
It turn up is a networking issue in my pc.
I have solved it.
Thanks.

**Comment by catcherwong** [comment]
I am not quite sure what the cause of this problem, But based on your log message, I guess it may be a request for an IPV6 address.

https://stackoverflow.com/questions/19676265/using-ipv6-address-to-connect-to-a-server-using-httpclient-using-ipv6-address-t/19676640

Can you record the full URL address from API Gateway to downstream services?

**Comment by JayChuah95** [comment]
Hi @catcherwong 
It turn up is a networking issue.
The fe80::xxxx:xxxx:xxxx:xxxx%20 is my link-local ipv6 address.

It seem like the ipv6 address is not working.
May I know what is the means by "record the full URL address from API Gateway to downstream services"?

**Comment by catcherwong** [comment]
API Gateway will send HTTP requests to the downstream services, in your sample is `AuthService`.

And what is the request URL here?  `http://localhost:30000/api/User/GetStuff` or `http://fe80::xxxx:xxxx:xxxx:xxxx%20:30000/api/User/GetStuff` or others.

**Comment by JayChuah95** [comment]
@catcherwong 
It suppose to be like the following example:
Upstream > http://localhost:10000/Auth/GetStuff
Then route to > http://localhost:20000/api/User/GetStuff

The output when I call http://localhost:10000/Auth/GetStuff
![image](https://user-images.githubusercontent.com/57252943/68559057-8c9d6a00-0476-11ea-9d94-52b093984b83.png)

**Comment by catcherwong** [comment]
Maybe you can change the default Log Level to Debug, ocelot will show more information for the request.

![cc](https://user-images.githubusercontent.com/8394988/68559559-6b3d7d80-0478-11ea-97b5-a769f1b56b33.png)

```JSON
{
  "spring": {
    "application": {
      "name": "Api-Gateway"
    }
  },
  "eureka": {
    "client": {
      "serviceUrl": "http://localhost:8761/eureka",
      "shouldRegisterWithEureka": true,
      "shouldFetchRegistry": true,
      "validateCertificates": false
    },
    "instance": {
      "port": 10000
    }
  },
 //  add the following section.
  "Logging": {
    "LogLevel": {
      "Default": "Debug"
    }
  },
  "AppSettings": {
    "Secret": "0265776e-b490-4253-9be4-7d73457700b1"
  }
}
```

**Comment by JayChuah95** [comment]
@catcherwong 
![image](https://user-images.githubusercontent.com/57252943/68559970-f79c7000-0479-11ea-89ce-98196b7335af.png)
The Downstream url is http://obest157:20000/api/User/GetStuff

obest157 is my computer name

**Comment by catcherwong** [comment]
When you access `http://obest157:20000/api/User/GetStuff`, can you get the right result or `Bad Request `?

**Comment by JayChuah95** [comment]
@catcherwong 
![image](https://user-images.githubusercontent.com/57252943/68562481-cb3a2100-0484-11ea-88e7-a5fec8e4bce8.png)
Bad Result on the url

**Comment by catcherwong** [comment]
You should resolve this problem at first, why you can not access this url normally?

**Comment by JayChuah95** [comment]
@catcherwong 
I think this is a networking issue?
It can be access if I changed it to localhost:20000 instead of the computer name

**Comment by catcherwong** [comment]
I guess this could be a issue for some network settings as well.

**Comment by JayChuah95** [comment]
Temperary Solution
go to \.vs\config
and change the applicationhost.config
Modify from
`<binding protocol="http" bindingInformation="*:20000:localhost" />`
to
`<binding protocol="http" bindingInformation="*:20000:*" />`

**Comment by raman-m** [comment]
Hi @JayChuah95 !
Is it still the issue? 😄

**Comment by raman-m** [comment]
> It seem like there is some issue on my localhost networking routing.
> https://github.com/ThreeMammals/Ocelot/issues/1053#issuecomment-553183891

Seems it was the discussion of 2 DevOps engineers :rofl:

**Comment by raman-m** [comment]
Not Ocelot issue!
