### ISSUE TITLE
Kubernetes and Consul Integration question

### ISSUE THREAD

**Issue by csnance** [ThreeMammals/Ocelot#1057]
Hello,

I am using Ocelot as an API gateway in AKS with Consul deployed inside the cluster for service discovery. I am using connect sidecar injection with ACL tokens for my pods. So my question is how to best integrate Ocelot with Consul in this scenario. This [issue](https://github.com/ThreeMammals/Ocelot/issues/332) references what I am trying to do but doesn't lay out a preferred route. I see three potential solutions.
1) Annotate the ocelot pod for connect injection and provide the list of required services to the connect-service-upstreams. This would create localhost bindings for each service and then I would use Ocelots normal configuration (without consul integration)
```json
{
    "DownstreamPathTemplate": "/api/posts/{postId}",
    "DownstreamScheme": "https",
    "DownstreamHostAndPorts": [
            {
                "Host": "127.0.0.1",
                "Port": {servicePortConfiguredInUpstreams},
            }
        ],
    "UpstreamPathTemplate": "/posts/{postId}",
    "UpstreamHttpMethod": [ "Put", "Delete" ]
}
```

2) Don't use connect inject on the Ocelot pod, use the Consul integration as defined in the configuration
```json
"ServiceDiscoveryProvider": {
 "Host": "consul",
 "Port": 8500,
 "Token": "{aclToken}",
 "Namespace": "{consulns}"
}
```

3) Use connect inject and the consul integration. In this scenario connect-inject is setup, but the service being injected is the consul service.
```json
{
      "DownstreamPathTemplate": "/api/{everything}",
      "DownstreamScheme": "http",
      "ServiceName": "{requestedService}",
      "UpstreamPathTemplate": "/api/c/{everything}",
      "UpstreamHttpMethod": [],
      "AuthenticationOptions": {
        "AuthenticationProviderKey": "IdentityApiKey",
        "AllowedScopes": []
      }
```

```json
"ServiceDiscoveryProvider": {
      "Host": "127.0.0.1",
      "Port": 8500,
      "Token": "{aclToken}",
      "Type": "Consul"
    }
```
Of the three I think I prefer the first option as it allows consul to manage it's ACL tokens, but is there a recommended best practice for this scenario?

Thanks!

**Comment by raman-m** [comment]
Hi @csnance !
Thanks for your interest in Ocelot!

I know my feedback is a bit late after these long 4 yesrs of your waiting...
To understand the correctness of your Consul provider configurations you need to have Ocelot logs.
I hope attached PR 1366 will help you totake your solution to the next level.
Let me know if you have any further questions!

**Comment by raman-m** [comment]
@csnance Let me know if your question is still actual.
