### ISSUE TITLE
How to cover both http and https downstream schemes in a reroute?

### ISSUE THREAD

**Issue by tekbyts** [ThreeMammals/Ocelot#1060]
If i want to define reroutes for both http and https, how can i do that? 

Should i add two different sections for a reroute one for http and one for https as shown below? 

```
"ReRoutes": [
    {
      "DownstreamPathTemplate": "/api/v{version}/{everything}",
      "DownstreamScheme": "http",
      "DownstreamHostAndPorts": [
        {
          "Host": "apidns.local",
          "Port": 28642
        }
      ],
      "UpstreamPathTemplate": "/api/v{version}providers/microsoft/requests",
      "UpstreamHttpMethod": [
        "POST",
        "GET",
        "PUT",
        "DELETE"
      ]
    },
    {
      "DownstreamPathTemplate": "/api/v{version}/{everything}",
      "DownstreamScheme": "https",
      "DownstreamHostAndPorts": [
        {
          "Host": "apidns.local",
          "Port": 44321
        }
      ],
      "UpstreamPathTemplate": "/api/v{version}/providers/microsoft/requests",
      "UpstreamHttpMethod": [
        "POST",
        "GET",
        "PUT",
        "DELETE"
      ]
    }
  ]
```

**Comment by melvinduc** [comment]
It seems like this doesn't work. I get a duplicate error.

**Comment by nkovacic** [comment]
Also getting a duplicate error, this issue is preventing SignalR integration with both websocket and long polling support. They both have the same PathTemplate but different DownstreamScheme.

**Comment by zTheProgrammer** [comment]
any solution for this. I also need to use http and https for same upstream url like following:
![image](https://user-images.githubusercontent.com/75984925/102086780-6e086000-3e3a-11eb-848e-2812abc7578a.png)

**Comment by niroshank** [comment]
> Also getting a duplicate error, this issue is preventing SignalR integration with both websocket and long polling support. They both have the same PathTemplate but different DownstreamScheme.

Did you resolve this ws issue?

**Comment by raman-m** [comment]
But the ports are different! Very strange that we have duplication error here... Really strange!
Can anyone test this scenario with the latest version of Ocelot please?

**Comment by raman-m** [comment]
Some unit and acceptance tests are required to check this configuration samples.
I will really wonder if the duplication problem persists.

**Comment by raman-m** [comment]
@tekbyts 
You must define 2 different routes with diff upstream templates for example.
Hope it helps!
