### ISSUE TITLE
Ocelot using Ocelot.Provider.Consul Service Discovery uses port 80 over https

### ISSUE THREAD

**Issue by Alpheusms** [ThreeMammals/Ocelot#1061]
## Expected Behavior / New Feature
Hi There, I am new to Ocelot and Consul service discovery. So I use ocelot to get the service from consul and expect it to use port 443 over https

## Actual Behavior / Motivation for New Feature
Ocelot can locate the service but when calling the webapi via the discovered service it uses port 80 over https.

Completed GET request to 'https://1.1.1.1/api/v1/namespaces/mynamespace/services/mywebapi-service' (OK).
dbug: Ocelot.DownstreamUrlCreator.Middleware.DownstreamUrlCreatorMiddleware[0]
      requestId: 0HLRED7HJNFUL:00000001, previousRequestId: no previous request id, message: Downstream url is https://1.2.1.16:80/myapi/api/1.0/messaging
dbug: Ocelot.Requester.Middleware.HttpRequesterMiddleware[0]
      requestId: 0HLRED7HJNFUL:00000001, previousRequestId: no previous request id, message: IHttpRequester returned an error, setting pipeline error
warn: Ocelot.Requester.Middleware.HttpRequesterMiddleware[0]
      requestId: 0HLRED7HJNFUL:00000001, previousRequestId: no previous request id, message: Error making http request, exception: System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception. ---> System.IO.IOException: The handshake failed due to an unexpected packet format.

## Steps to Reproduce the Problem

  1.Installed consul on azure kubernetes, 
  1.Implement ocelot using Ocelot.Provider.Consul to reroute to the api
  1.Call the gateway service

## Specifications

  - Version:13.8.0
  - Platform:Azure,Kubernetes,Linux
  - Subsystem:DotnetCore

**Comment by raman-m** [comment]
@Alpheusms
Thanks for reporting!

Seems you didn't define the port in service entry of Consul config.
Try to define exactly 443 as a port.
We read the port from `ServiceEntry` object: https://github.com/ThreeMammals/Ocelot/blob/develop/src/Ocelot.Provider.Consul/Consul.cs#L61

But, could you reproduce the bug for the latest Ocelot version plz?
If the problem persists, reopen or report once again.
Thanks!

**Comment by raman-m** [comment]
@Alpheusms 
This doc will help you understand better Consul ports: [Consul ports reference](https://developer.hashicorp.com/consul/docs/install/ports)

**Comment by raman-m** [comment]
And pay attention https port is disabled by default ❗ 

HTTPS | The HTTPS API | TCP | 8501 | Disabled | 443 | Incoming
-- | -- | -- | -- | -- | -- | --
[HTTPS](https://developer.hashicorp.com/consul/docs/install/ports#https)	| The HTTPS API | TCP | `8501` | **Disabled** | `443` | Incoming
