### ISSUE TITLE
Multiple template URLs in UpstreamPathTemplate

### ISSUE THREAD

**Issue by linuxchata** [ThreeMammals/Ocelot#1063]
Is there a way to set multiple template URLs in UpstreamPathTemplate?

## New Feature
{
  "DownstreamPathTemplate": "/url/people/{everything}",
  "DownstreamScheme": "https",
  "DownstreamHostAndPorts": [
    {
      "Host": "host.name",
      "Port": 9000
    }
  ],
  "UpstreamPathTemplate": [ "/url/people/{everything}", "/url/{everything}" ],
  "UpstreamHttpMethod": [ "GET" ]
}

## Specifications

  - Version: 13.5.0
  - Platform: Windows / Linux
  - Subsystem: .NET Core

**Comment by catcherwong** [comment]
It don't support multiple template URLs in UpstreamPathTemplate now.

You can add another section with different UpstreamPathTemplate or use [Catch All](https://ocelot.readthedocs.io/en/latest/features/routing.html#catch-all) to do this job.

**Comment by LouieGuo** [comment]
is it updated for this problem?
