### ISSUE TITLE
Using k8s for service discovery，Host wrong

### ISSUE THREAD

**Issue by burningg** [ThreeMammals/Ocelot#1065]
## Expected Behavior
I am using ocelot to create an API gateway for microservices / APIs which are deployed in Aliyun Kubernetes. I use kubernetes to realize service discovery Consul.
We use a global configuration:
  "ReRoutes": [
    {
      "DownstreamPathTemplate": "/api/v2/email",
      "DownstreamScheme": "http",
      "UpstreamPathTemplate": "/api/v2/email",
      "UpstreamHttpMethod": [
        "POST"
      ],
      "ServiceName": "msg-email-fat-svc"
   }],
"GlobalConfiguration": {
    "ServiceDiscoveryProvider": {
      "Host": "101.*.**.**",
      "Port": 6443,
      "Token": "***",
      "Namespace": "magnificence-space",
      "Type": "kube"
    }
}
## Actual Behavior
I caught a exception in gateway：“Forbiddenm User:"****" cannot get services in the namespace"**"” .
Then I download the source code of Ocelot, And replaced the Ocelot Nuget with it.
I found that the kubeClient we got was wrong, It's Host And Port Are default value “192.168.0.13”，“443”.
the code in KubernetesProviderFactory class
####
        var kubeClient = provider.GetService<IKubeApiClient>();

They're not what I want， I didn't find the code assigned to them
But My host and port in Configuration.ServiceProviderConfiguration config,
I create a IKubeApiClient that use config's host and port.

####    
        var _port = config.Port;
            var _kubeHost = config.Host;
            IKubeApiClient kubeClient = KubeApiClient.Create(new KubeClientOptions
            {
                ApiEndPoint = new Uri($"https://{_kubeHost}:{_port}"),
                AccessToken = config.Token,
                AuthStrategy = KubeClient.KubeAuthStrategy.BearerToken,
                AllowInsecure = true
            });

Downstream address discovery successfully

I'm not sure if it's my mistake，Or is it a bug?
## Specifications

  - Version:13.5.2
  - Platform: aliyun k8s
  - Subsystem: ASP.NET Core 2.1

**Comment by raman-m** [comment]
> ` "DownstreamScheme": "http",`
> `ApiEndPoint = new Uri($"https://{_kubeHost}:{_port}"),`

You forgot to specify `https` as DownstreamScheme! Bingo! :boom: 
It should be ` "DownstreamScheme": "https",` :exclamation:

**Comment by raman-m** [comment]
```json
"GlobalConfiguration": {
    "ServiceDiscoveryProvider": {
      "Host": "101.*.**.**",
      "Port": 6443,
      "Token": "***",
      "Namespace": "magnificence-space",
      "Type": "kube"
    }
```

Your host is invalid!
Your token is invalid too.

> I caught a exception in gateway：“Forbiddenm User:"****" cannot get services in the namespace"**"” .

Bingo :2nd_place_medal:  :boom: 

Please, report us more fairy tales! :baby:
