### ISSUE TITLE
{everything} placeholder in between the url

### ISSUE THREAD

**Issue by surajsingh30** [ThreeMammals/Ocelot#1067]
## Expected Behavior / New Feature
Is it possible to put {everything} placeholder in UpStreamPath and DownStreamPath like below?
"/api/al/{everything}/auditlog"

## Actual Behavior / Motivation for New Feature
Right now it is not working if I place as above.

## Steps to Reproduce the Problem

I am configuring Api Gateway as below -
```json
      "DownstreamPathTemplate": "/api/al/{everything}/auditlog",
      "DownstreamScheme": "http",
      "DownstreamHostAndPorts": [
        {
          "Host": "localhost",
          "Port": 62209
        }
      ],
      "UpstreamPathTemplate": "/api/al/{everything}/auditlog",
      "UpstreamHttpMethod": [ "Get", "Post", "Put", "Delete" ],
      "Key": "LogService"
```

**Comment by catcherwong** [comment]
It runs well based on your configuration.

![image](https://user-images.githubusercontent.com/8394988/69811034-28c1c200-1228-11ea-861b-7e4feee1668d.png)

Could you provide more information for this issue?

**Comment by surajsingh30** [comment]
> It runs well based on your configuration.
> 
> ![image](https://user-images.githubusercontent.com/8394988/69811034-28c1c200-1228-11ea-861b-7e4feee1668d.png)
> 
> Could you provide more information for this issue?

Yes this works, if I pass like this. But In my case, I want something like below 
![image](https://user-images.githubusercontent.com/16236075/69812903-1d19cf80-1217-11ea-9ef1-204fa972ae24.png)

I don't want to specify 2 route in api gateway and need to keep the auditlog suffix as well.

**Comment by catcherwong** [comment]
Some limitation here!

Ocelot generate below regular expression for  Downstream URL.

```
^(?i)/api/al/[^/]+/auditlog$
```

But `/api/al/youapp/youtype/auditlog` can not match.

**Comment by surajsingh30** [comment]
> Some limitation here!
> 
> Ocelot generate below regular expression for Downstream URL.
> 
> ```
> ^(?i)/api/al/[^/]+/auditlog$
> ```
> 
> But `/api/al/youapp/youtype/auditlog` can not match.

What you suggest for this case?

**Comment by raman-m** [comment]
My suggestion to use [Catch All](https://ocelot.readthedocs.io/en/latest/features/routing.html#catch-all) feature like this
```json
      "DownstreamPathTemplate": "/api/al/{everything}",
      "UpstreamPathTemplate": "/api/al/{everything}",
```
Please note! Placeholders in the middle cannot be considered as Catch All ones! They are simple placeholder between 2 slashes: `/{simpleplaceholder}/` &rarr; `/alpha-numeric-alphabet-without-slashes/`

Hope it helps!
