### ISSUE TITLE
Unable to see consul service discovery is working in Docker Overlay Network 

### ISSUE THREAD

**Issue by ToeToeAung** [ThreeMammals/Ocelot#1068]
Docker Overlay Network 

I tried to create docker service using docker overlay network in SIT environment.
The docker detail infor is as below. How to check docker overlay network and how to see the service is working or not. Please let me know. 

Client:
 Debug Mode: false
 Plugins:
  cluster: Manage Docker clusters (Docker Inc., v1.0.1)

Server:
 Containers: 68
  Running: 1
  Paused: 0
  Stopped: 67
 Images: 44
 Server Version: 19.03.1
 Storage Driver: windowsfilter
  Windows:
 Logging Driver: json-file
 Plugins:
  Volume: local
  Network: ics l2bridge l2tunnel nat null overlay transparent
  Log: awslogs etwlogs fluentd gcplogs gelf json-file local logentries splunk syslog
 Swarm: active
  NodeID:  
  Is Manager: true
  ClusterID:  
  Managers: 1
  Nodes: 2
  Default Address Pool: 10.0.0.0/8
  SubnetSize: 24
  Data Path Port: 4789
  Orchestration:
   Task History Retention Limit: 5
  Raft:
   Snapshot Interval: 10000
   Number of Old Snapshots to Retain: 0
   Heartbeat Tick: 1
   Election Tick: 10
  Dispatcher:
   Heartbeat Period: 5 seconds
  CA Configuration:
   Expiry Duration: 3 months
   Force Rotate: 0
  Autolock Managers: false
  Root Rotation In Progress: false
  Node Address: 192.168.xxx.xxx
  Manager Addresses:
   192.168.xxx.xxx:2377
 Default Isolation: process
 Kernel Version: 10.0 14393 (14393.3053.amd64fre.rs1_release_inmarket.190612-1836)
 Operating System: Windows Server 2016 Standard Version 1607 (OS Build 14393.3053)
 OSType: windows
 Architecture: x86_64
 CPUs: 1
 Total Memory: 
 Name: XXXX
 ID: XXXX
 Docker Root Dir: C:\ProgramData\docker
 Debug Mode: false
 HTTP Proxy:
 Username: 
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

## Steps to Reproduce the Problem

  1.
  1.
  1.

## Specifications

  - Version:
  - Platform:
  - Subsystem:

**Comment by hifeamin** [comment]
Hi. 
Can anyone solve this problem? Or any idea to use consul service discovery in docker container?

**Comment by cecilphillip** [comment]
I'm running into this problem as well

**Comment by raman-m** [comment]
Hi @ToeToeAung !
Thanks for your interest in Ocelot!

In order to understand what's happening you need to enable logging for appropriate service discovery provider which is Consul.
After that you will be able to read Ocelot logs and continue to find root cause of your issue.

I'm pleased to announce that related PR 1366 will help you much!

**Comment by raman-m** [comment]
@ToeToeAung Let me know if your bug/question is still actual.
