### ISSUE TITLE
Custom Request Aggregation

### ISSUE THREAD

**Issue by stefanvoicila** [ThreeMammals/Ocelot#1069]
## Expected Behavior / New Feature

I am trying to aggregate two requests in a way in which a value from the first response is used in the second response as a parameter.

I want to return the results from both requests in a way that resembles something like this:
"Response": [
       FirstResponse_FirstItem:{
               "Key": 1,
               SecondResponse_Item1: {
                         "ForeignKey": 1,
                         "Value" : "aaaaa"
                 }
      }
]

## Actual Behavior / Motivation for New Feature

I've been trying to set up an aggregator to do this implementing IDefinedAggregator (as described in the docs) but I had no success. Also, I am struggling to find examples of aggregators in order to have any starting points or ideas on how to do this.

## Steps to Reproduce the Problem

  1. config:
{
  "ReRoutes": [
    {
      "DownstreamPathTemplate": "/api/{everything}",
      "UpstreamPathTemplate": "/api/logistics/{everything}",
      "UpstreamHttpMethod": [ "Get", "Post", "Put", "Delete" ],
      "DownstreamScheme": "https",
      "DownstreamHostAndPorts": [
        {
          "Host": "localhost",
          "Port": 5001
        }
      ],
      "SwaggerKey": "Logistics"
    },
    {
      "DownstreamPathTemplate": "/api/{everything}",
      "UpstreamPathTemplate": "/api/identity/{everything}",
      "UpstreamHttpMethod": [ "Get", "Post", "Put", "Delete" ],
      "DownstreamScheme": "https",
      "DownstreamHostAndPorts": [
        {
          "Host": "localhost",
          "Port": 50026
        }
      ],
      "SwaggerKey": "Identity"
    },
    {
      "DownstreamPathTemplate": "/api/Buildings",
      "UpstreamPathTemplate": "/buildings",
      "UpstreamHttpMethod": [ "Get" ],
      "DownstreamScheme": "https",
      "DownstreamHostAndPorts": [
        {
          "Host": "localhost",
          "Port": 5001
        }
      ],
      "Key": "buildings"
    },
    {
      "DownstreamPathTemplate": "/api/Device/{Id}",
      "UpstreamPathTemplate": "/devices/{Id}",
      "UpstreamHttpMethod": [ "Get" ],
      "DownstreamScheme": "https",
      "DownstreamHostAndPorts": [
        {
          "Host": "localhost",
          "Port": 5001
        }
      ],
      "Key": "devices"
    }
  ],
  "SwaggerEndPoints": [
    {
      "Key": "Logistics",
      "Config": [
        {
          "Name": "Logistics API",
          "Version": "v1",
          "Url": "https://localhost:5001/swagger/v1/swagger.json"
        }
      ]
    },
    {
      "Key": "Identity",
      "Config": [
        {
          "Name": "Identity API",
          "Version": "v1",
          "Url": "https://localhost:50026/swagger/v1/swagger.json"
        }
      ]
    }
  ],
  "Aggregates": [
    {
      "ReRouteKeys": [
        "devices",
        "buildings"
      ],
      "UpstreamPathTemplate": "/both",
      "Aggregator": "TestAggregator"
    }
  ],
  "GlobalConfiguration": {
    "BaseUrl": "https://localhost"
  }
}

  2. Startup: 
            services.AddOcelot(Configuration).AddSingletonDefinedAggregator();
  3. Aggregator:
    public class TestAggregator : IDefinedAggregator
    {
public async Task<DownstreamResponse> Aggregate(List<DownstreamContext> responses)
        {
          ??
         }
    }

## Specifications

  - Version: 13.9.0-alpha0115
  - Platform: Windows 10
  - Subsystem: .NET Core 3.0

**Comment by jr-araujo** [comment]
Hi,

I think that you are missing something in your Ocelot configuration.

In the picture below is showing the Ocelot version which has configured in my project:
![image](https://user-images.githubusercontent.com/11546614/78514001-0d9f2a00-77a7-11ea-94ec-5feb9da87e2b.png)

Here is my **Program.cs** configuration. And here is your missing point, take a look:
![image](https://user-images.githubusercontent.com/11546614/78514016-21e32700-77a7-11ea-8650-d38d10e829dd.png)

And here is my **ocelot.json**:
![image](https://user-images.githubusercontent.com/11546614/78514036-39221480-77a7-11ea-80cb-d7e4d527310a.png)

I hope all of this can help you to solve this problem.

**Comment by neetra** [comment]
@stefanvoicila  [here ](https://github.com/ThreeMammals/Ocelot/issues/1207#issuecomment-618895233)is the sample.

**Comment by debayanmitra002-git** [comment]
Is this issue resolved? I am fairly new to Ocelot and what I could understand if we are aggregating two service calls and the key is same, then it can be handled via the reroute stuff.
However, if I have a requirement where I hit the first service with the parameter I am passing from client but want to use a different value from the response of first downstream service as a parameter of next downstream service, how can I do that even with IDefinedAggregator. Any example will help
