### ISSUE TITLE
LoadBalancerOptions not skip DownstreamHostAndPorts is not work.

### ISSUE THREAD

**Issue by uopeydel** [ThreeMammals/Ocelot#1071]
I have "DownstreamHostAndPorts" start in my server 3 port 8001 , 8003 , 8004
It can have any accident once day 8003 is stop work.
I need to let it auto skip / auto call to another DownstreamHostAndPorts index is work fine , It doesn't. Now it will call success 2 time , return 500 one time when it call to  8003  and  loop.
`
 {
  "ReRoutes": [
    {
      "DownstreamPathTemplate": “/test/{version}/hub/{everything}",
      "DownstreamScheme": "http",
      "DownstreamHostAndPorts": [ 
        {
          "Host": “localhost",
          "Port": 8004
        },
        {
          "Host": "localhost
          "Port": 8001
        },
        {
          "Host": "localhost
          "Port": 8003
        }
      ],
      "UpstreamPathTemplate": "/api/test/{version}/hub/{everything}",
      "UpstreamHttpMethod": [ "POST" ],
      "LoadBalancerOptions": {
        "Type": "CookieStickySessions",
        "Key": "ASP.NET_SessionId",
        "Expiry": 1800000
      } 
    } 
  ],
  "GlobalConfiguration": {
     
  }
}
`

**Comment by dongphh** [comment]
same my prob

**Comment by raman-m** [comment]
Ocelot team is not responsible for Heath of your downstream services. If you get error then it is normal to have the error in logs!
Apply Health Checks for your downstream services to keep them always online. This is DevOps task.

**Comment by raman-m** [comment]
Not Ocelot issue!
