### ISSUE TITLE
Ocelot API gateway returns invalid data in dotnet core

### ISSUE THREAD

**Issue by ramesh26** [ThreeMammals/Ocelot#1072]
I have received below invalid data when using API gateway in dotnet core

![image](https://user-images.githubusercontent.com/13754399/70138132-99982c80-16b5-11ea-892e-1d5ac6032687.png)

**Ocelot Code:**
![image](https://user-images.githubusercontent.com/13754399/70138150-a3219480-16b5-11ea-9901-2b9e289a7f81.png)

**POSTMAN Error:**

![image](https://user-images.githubusercontent.com/13754399/70138415-42468c00-16b6-11ea-87a5-f1fc902d877e.png)

**Comment by OPavlinOBILOG** [comment]
![image](https://user-images.githubusercontent.com/57350327/72158075-aea16300-33b9-11ea-9c0c-40c60b09262c.png)
![image](https://user-images.githubusercontent.com/57350327/72158362-561e9580-33ba-11ea-9cfa-d66700f44a41.png)

Same problem here but without aggregation. Only simple 3 projects API solution, when requesting directly the API i get a correct JSON format, when requesting through ocelot port i get incorrect format return

**Comment by MSeifAllah** [comment]
Resolved 
@ramesh26 , @OPavlinOBILOG 
[](https://github.com/ThreeMammals/Ocelot/issues/716#issuecomment-577371572)

**Comment by neetra** [comment]
@ramesh26 .
Ocelot return you compressed data, you need to decompress it. Decompression should happen based on the Content-Encoding header.

[Look here for sample](https://github.com/ThreeMammals/Ocelot/issues/1207#issuecomment-618895233)

**Comment by raman-m** [comment]
@ramesh26 
You have sufficient answers by the community :point_right: 
- https://github.com/ThreeMammals/Ocelot/issues/1072#issuecomment-618973151
- https://github.com/ThreeMammals/Ocelot/issues/1072#issuecomment-577592761
- https://github.com/ThreeMammals/Ocelot/issues/716#issuecomment-632940791
- https://github.com/ThreeMammals/Ocelot/issues/1207#issuecomment-618895233

Going to close...

**Comment by raman-m** [comment]
Answered in ##1900 
- #1900
