### ISSUE TITLE
Injected routing to DownStream path based on content within request body

### ISSUE THREAD

**Issue by grahambunce** [ThreeMammals/Ocelot#1075]
## New Feature

We are migrating a Java RPC based service api running in Glassfish to a SOA/Microservice api. The URL path for the incoming request is always the same (e.g. /rpc). The request body contains details that we can interrogate to identify the actual request content, e.g. 
{ "method" : "internal class reference" } where we can use the "internal class reference" to decide which service(s) the incoming request should be mapped to.

## Actual Behavior / Motivation for New Feature

The Dynamic routing means we have to call out to Consul/Eureka but as we have a specialized use case what we really want is to be able to inject a .NET class that gives us complete customization of the analysis of the incoming request to decide what to do. In our case, we need to check the method, check the credentials (via an api call we would make), map the url and credentials to an appropriate regional service and then pass that back to Ocelot to make the call.

The additional complexity is that we also want to use the injectable Request Aggregator feature as one incoming rpc call may not map to one microservice. We may need to take the one rpc and map to several services and aggregate the content; hence the need to completely customize the request analysis and the forward request via injectable plugins.

**Comment by kg73** [comment]
I too am interested in modifying downstream routing based on request content.

Is there an existing extensibility point where this could be done?

My use case is a bit simpler. If a request body contains a certain JSON value, such as "ABC", I'd like to route to a different downstream than if the value was "DEF".

Is this possible?

**Comment by raman-m** [comment]
@grahambunce 
Please fork Ocelot repo into your account and develop whatever you want.
Good luck!
