### ISSUE TITLE
ocelot return 500 when consul and micro-service on the same host 

### ISSUE THREAD

**Issue by dianond** [ThreeMammals/Ocelot#1076]
## Steps to Reproduce the Problem

  1. run consul on 192.168.1.100
  2. run micro-service 1 on 192.168.1.100 port 20000
  3. run micro-service 2 on 192.168.1.101 port 20000
  4. ocelot UseServiceDiscovery
  5. micro-service 1 can not receive from ocelot , micro-service 2 work normal

## Specifications

  - Version: 13.8.0
  - Platform: ubuntu18.04.3
  - Subsystem: net core 3.1  consul 1.6.2

**Comment by raman-m** [comment]
Ancient issue
