### ISSUE TITLE
allow to limit the number of concurrent tcp connection to a downstream service

### ISSUE THREAD

**Issue by buretjph** [ThreeMammals/Ocelot#1077]
## New Feature
limit the number of concurrent tcp connection to a downstream service

## Motivation for New Feature
We are using Ocelot to route http traffic to different http service of our own.
Some of these servjces limit the number of concurrent tcp connection. When the number of allowed connection is reach, requests are rejected.
By default, Ocelot instanciate one HttpClient per Downstream route and use default parameters of its HttpClientHandler object. the defaut value of HttpClientHandler::MaxConnectionPerServer is int.MaxValue.
Our proposition is to allow to customize "MaxConnectionPerServer", allowing to add a new parameter inside Ocelot.Json. The accurate place could be inside the "HttpHandlerOptions" section. let's keep .net default value if the parameters is not used.

## Steps to Reproduce the Problem

  1. send tons of request to Ocelot and check using netstat -an how many socket are open.

## Specifications

  - Version: 13.8.0
  - Platform: windows 
  - Subsystem: ?

**Comment by buretjph** [comment]
I've done the work and about to push the PR

**Comment by raman-m** [comment]
> I've done the work and about to push the PR

Sorry?

**Comment by raman-m** [comment]
`HttpClientHandler::MaxConnectionPerServer`

Why do we need to decrease the number of connections if the value has maximum theoretical value?

If you don't know how to setup your Kestrel webserver instance, please go to Microsoft Kestrel team forums and ask your questions.
