### ISSUE TITLE
Provide Route informations (ReRoute Key, input request context) in User defined aggregators.

### ISSUE THREAD

**Issue by pierre-seiitra** [ThreeMammals/Ocelot#1079]
## Expected Behavior / New Feature
Provide Route informations (ReRoute Key, input request context) in User defined aggregators.

Task<DownstreamResponse> Aggregate(List<DownstreamResponse> responses, List<string> rerouteKeys, List<HttpContext> inputRequests)

## Actual Behavior / Motivation for New Feature
I want to enrich the results of a fowarded request with the results of some other requests (Ex : The 1st request (Route A) returns an entity A, which contains the key of an entity B. I want to add the label of the entity B to the DownstreamReponse). 

I would like to be able to do it by config (having some json like :
```json
  "ResultEnrichers": [
    {
      "ReRouteKey": "get_A",
      "JoinResults": [
        {
          "SourceKey": "B_key",
          "UrlPattern": "http://B_entity_api/api/B_entity/{B_key}",
          "ProjectedFields": [
            {
              "SourceName": "property_name_of_label_in_B_object",
              "TargetName": "property_name_of_label_in_A_object"
            }
          ]
        }
      ]
    }
  ],
```
I though i could achieve this in a custom aggregator but : 
- i don't have access to the headers of the first request to use them for the second request
- as the config is in a json file (so done at runtime), i need to know the ReRoute Key to know which config i should use.

**Comment by pierre-seiitra** [comment]
Linked to [issue  1069](https://github.com/ThreeMammals/Ocelot/issues/1069)

**Comment by raman-m** [comment]
>Provide Route informations (ReRoute Key, input request context) in User defined aggregators.

Route can be obtained from context like this:
```C#
    public async Task<DownstreamResponse> Aggregate(List<HttpContext> responseHttpContexts)
    {
        var route = responseHttpContexts[0].Items.DownstreamRoute();
        // ...
    }
```

----

> I would like to be able to do it by config (having some json like :
> ```json
>   "ResultEnrichers": [
>     {
>       "ReRouteKey": "get_A",
>       "JoinResults": [
>         {
>           "SourceKey": "B_key",
>           "UrlPattern": "http://B_entity_api/api/B_entity/{B_key}",
>           "ProjectedFields": [
>             {
>               "SourceName": "property_name_of_label_in_B_object",
>               "TargetName": "property_name_of_label_in_A_object"
>             }
>           ]
>         }
>       ]
>     }
>   ],
> ```
> 

You want customs properties for the route. It is not implemented right now, but we have nice PR for that
- #1843 

And this feature will be delivered in version 24.0
