### ISSUE TITLE
New feature: Provide reroute configuration via Consul instead of manually managing a local config

### ISSUE THREAD

**Issue by tenfortyeight** [ThreeMammals/Ocelot#1081]
## New Feature
Being new to Ocelot it has already proven to be quite simpel and straightforward. But I have been searching far and wide for a way to provide reroute configuration from Consul but have found none so far.

Since one of the key benefits that you want from microservices is speed and flexibility, I would like to see a way to provide the reroute information directly from the originating service instead of having to go into another place to ensure the api gateway. Centralising the configuration to Consul, and it being provided directly from the source service/downstream, via conventions would make things a whole lot easier to manage and less error prone. Also one source to manage a service, it will be autonomous and self contained.

## Motivation for New Feature
One way to provide this would be to make use of the tags in Consul. It would be clearly visible and ensure the autonomy of the downstream service. I imagine it something along the way of this
```
new AgentServiceRegistration
{
    ID = _registrationId,
    Name = _config.ServiceName,
    Address = uri?.Host,
    Port = uri?.Port ?? 80,
    Tags = new string[] {
        $"SwaggerKey:{_config.ServiceName}",
        "UpstreamPathTemplate:/my/{id}/path/",
        "UpstreamHttpMethod:[\"Get\", \"Post\"]",
        "DownstreamScheme:http",
        "DownstreamPathTemplate:/slight/different/{id}"
    }
}```

**Comment by raman-m** [comment]
We won't do that!

To have single source of Ocelot config saved in Consul: [Store Configuration in Consul](https://ocelot.readthedocs.io/en/latest/features/configuration.html#store-configuration-in-consul)
