### ISSUE TITLE
Support for SocketsHttpHandler 

### ISSUE THREAD

**Issue by k-u-s** [ThreeMammals/Ocelot#1082]
## Expected Behavior / New Feature
Any plans on supporting [SocketsHttpHandler](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.socketshttphandler?view=netcore-3.1) announced in https://devblogs.microsoft.com/dotnet/announcing-net-core-2-1/ section "Networking Performance Improvements" instead of HttpClientHandler when targeting net core 2.1+

## Actual Behavior / Motivation for New Feature
HttpClientHandler is used on net core 2.1+ 

## Steps to Reproduce the Problem

  1. Start any sample project
  1. Source: https://github.com/k-u-s/Ocelot/blob/ed3b6f41ab3a9f7cdbe50b27b3dfb1017d18f9e8/src/Ocelot/Requester/HttpClientBuilder.cs lines 71 to 106

## Specifications

  - Version: any
  - Platform: any
  - Subsystem: any

**Comment by pengweiqhca** [comment]
.net core 2.1+ HttpClientHandler internal use SocketsHttpHandler

**Comment by k-u-s** [comment]
Probably enforcing it isn't the best Idea
