### ISSUE TITLE
Integrate Opentracing(Jaeger)

### ISSUE THREAD

**Issue by icebergdelphi** [ThreeMammals/Ocelot#1085]
Hi  I have a doubt , I wonder myself if is possible integrate OpenTracing (Jaeger) due I need to Monitoring The request From APIGateway to Final API? Thank you.

**Comment by thiagoloureiro** [comment]
https://ocelot.readthedocs.io/en/latest/features/tracing.html

**Comment by mohammadfiroozi** [comment]
is there any sample? 
jaeger setting (api , ..) how to config?
