### ISSUE TITLE
Ocelot Administration doesn't work with .NET Core 3.x

### ISSUE THREAD

**Issue by CesarD** [ThreeMammals/Ocelot#1088]
## Expected Behavior / New Feature
Administration API should work after being properly configured in a .NET Core 3.x project.

## Actual Behavior / Motivation for New Feature
Ocelot throws error when executed in pipeline claiming that `.UseMvc` method should not be used on .NET Core 3.x projects.

## Steps to Reproduce the Problem

  1. Create a .NET Core 3.x project
  1. Install and configure Ocelot and Ocelot Administration (with IdentityServer authentication)
  1. Run the app.

## Specifications

  - Version: 13.8.0
  - Platform: ---
  - Subsystem: ---

As far as I can see, it all comes because of this line: https://github.com/ThreeMammals/Ocelot/blob/release/13.8.0/src/Ocelot.Administration/IdentityServerMiddlewareConfigurationProvider.cs#L30

I'm just starting to migrate stuff to .NET Core 3.x and still trying to come around with the new Endpoints stuff it brings, but I assume Ocelot should make use of them to properly configure it?

If I remove the `.AddAdministration()` configuration from my `Startup`, the Ocelot application runs with no further issues.

**Comment by squoyster** [comment]
Same issue as above.

**Comment by ussamoo** [comment]
Same issue as above

**Comment by ussamoo** [comment]
I confirm it's fixed with the last version.

**Comment by raman-m** [comment]
@CesarD 
> If I remove the `.AddAdministration()` configuration from my Startup, the Ocelot application runs with no further issues.

Sounds like a success story!

**Comment by raman-m** [comment]
> Administration API should work after being properly configured in a **.NET Core 3.x** project.

We don't support .NET Core 3.1 as Microsoft does the same. We support only .NET 6+
