### ISSUE TITLE
Issues between app.UseOcelot() and app.UseSpa()

### ISSUE THREAD

**Issue by ghost** [ThreeMammals/Ocelot#1089]
As both middlewares should be at the end of the pipeline, they cannot work together.

## Expected Behavior / New Feature

It is expected to allow Ocelot to "bypass" the calls if they do not match a pattern, for example. That way, the request could go to the next middleware. In this case, the dotnet Spa middleware.

This could be a parameter in the configuration when adding Ocelot

## Actual Behavior / Motivation for New Feature

- If Ocelot is defined before the Spa middleware: the APIs gateway works, but we do not have the SPA feature
- If Ocelot is defined after the Spa middleware: the APIs gateway doesn't work, as all the requests are proxied to the Spa (in my case: Angular)

The motivation is to allow adding more middlewares to the pipeline, without assuming Ocelot should be the last one.

## Steps to Reproduce the Problem

Just configure the middleware with .UseOcelot() and .UseSpa() in whatever the order you want.

## Specifications

  - Version: 13.5.2 (latest stable for .Net core 2.2)

## How to fix the problem

I fixed the issue by adding Ocelot first, and controlling the calls via a simple validation:

- If the request starts with "/gw" then I should process it
- Otherwise: continue with the next middleware in the pipeline

I copied the code from **OcelotMiddlewareExtensions.cs** and added a simple validation:
```

private static string gateWayPrefix = "/gw";

private static IApplicationBuilder CreateOcelotPipeline(IApplicationBuilder builder, OcelotPipelineConfiguration pipelineConfiguration)
{
  ...
                builder.Use(async (context, task) =>
                {
                    var defaultHttpContext = context as Microsoft.AspNetCore.Http.DefaultHttpContext;

                    if (defaultHttpContext != null && 
                        !defaultHttpContext.Request.Path.StartsWithSegments(new Microsoft.AspNetCore.Http.PathString(gateWayPrefix)))
                    {
                        // We are not receiving a "gw" API call. Therefore, we should just pass the request 
                        // to the next object in the pipeline
                        await task.Invoke();
                    }
                    else
                    {
                        // Processing as usual...
                        var downstreamContext = new DownstreamContext(context);
                        await firstDelegate.Invoke(downstreamContext);
                    }
                });
}

```

this simple trick solves my problem, although I'm not sure if it's in line with the development of the library.

**Comment by ripebananas** [comment]
Bump. I would like to see such Ocelot feature as well.
@jparaya, thanks for sharing your solution.

**Comment by gkumar1234** [comment]
> As both middlewares should be at the end of the pipeline, they cannot work together.
> 
> ## Expected Behavior / New Feature
> It is expected to allow Ocelot to "bypass" the calls if they do not match a pattern, for example. That way, the request could go to the next middleware. In this case, the dotnet Spa middleware.
> 
> This could be a parameter in the configuration when adding Ocelot
> 
> ## Actual Behavior / Motivation for New Feature
> * If Ocelot is defined before the Spa middleware: the APIs gateway works, but we do not have the SPA feature
> * If Ocelot is defined after the Spa middleware: the APIs gateway doesn't work, as all the requests are proxied to the Spa (in my case: Angular)
> 
> The motivation is to allow adding more middlewares to the pipeline, without assuming Ocelot should be the last one.
> 
> ## Steps to Reproduce the Problem
> Just configure the middleware with .UseOcelot() and .UseSpa() in whatever the order you want.
> 
> ## Specifications
> * Version: 13.5.2 (latest stable for .Net core 2.2)
> 
> ## How to fix the problem
> I fixed the issue by adding Ocelot first, and controlling the calls via a simple validation:
> 
> * If the request starts with "/gw" then I should process it
> * Otherwise: continue with the next middleware in the pipeline
> 
> I copied the code from **OcelotMiddlewareExtensions.cs** and added a simple validation:
> 
> ```
> 
> private static string gateWayPrefix = "/gw";
> 
> private static IApplicationBuilder CreateOcelotPipeline(IApplicationBuilder builder, OcelotPipelineConfiguration pipelineConfiguration)
> {
>   ...
>                 builder.Use(async (context, task) =>
>                 {
>                     var defaultHttpContext = context as Microsoft.AspNetCore.Http.DefaultHttpContext;
> 
>                     if (defaultHttpContext != null && 
>                         !defaultHttpContext.Request.Path.StartsWithSegments(new Microsoft.AspNetCore.Http.PathString(gateWayPrefix)))
>                     {
>                         // We are not receiving a "gw" API call. Therefore, we should just pass the request 
>                         // to the next object in the pipeline
>                         await task.Invoke();
>                     }
>                     else
>                     {
>                         // Processing as usual...
>                         var downstreamContext = new DownstreamContext(context);
>                         await firstDelegate.Invoke(downstreamContext);
>                     }
>                 });
> }
> ```
> 
> this simple trick solves my problem, although I'm not sure if it's in line with the development of the library.

Do you have a working sample? i have same problem and i getting ambiguous error between my new class and Ocelot library,when i copy and place this code.

**Comment by raman-m** [comment]
The author's account was deleted!
