### ISSUE TITLE
"IServiceCollection" doesn't contain any definition for "AddOcelot"

### ISSUE THREAD

**Issue by shiro997** [ThreeMammals/Ocelot#1092]
i'm trying to implement Api GateWay using ocelot and .Net Core 3.0 but in Program class when i try to add ocelot VS2019 shows me this error: "IServiceCollection" doesn't contain a definition for "AddOcelot" or an accessible extension method "AddOcelot" that accepts a first argument of type "IServiceCollection" (is any directive using or an assembly reference missing?)

**Comment by jlukawska** [comment]
using Ocelot.DependencyInjection; 

;)

**Comment by jmezach** [comment]
@shiro997 What @jlukawska suggested should fix your issue so I'm closing this for now. Do not hesitate to re-open if it is still an issue for you and I'll be happy to help you out.
