### ISSUE TITLE
Flexible placeholders endpoints settings

### ISSUE THREAD

**Issue by tkhametov** [ThreeMammals/Ocelot#1097]
Hi everyone.

I use Ocelot in my Routing Service and I love this library so much! It's a truly powerful library that allows me to develop microservices and not care about routings.

I store all my configuration related to Ocelot in `routing.json`. Also, I use this file to build documentation for API of all microservices. 

But recently I ran into a problem that I have to copy-paste a lot of configuration peaces to add new endpoint of my microservices.
For example, I have microservices that upload images to store. I describe this one in my configuration as:

```
{
      "Key": "ImageUploader",
      "DownstreamPathTemplate": "/image-uploader-microservice/upload-images",
      "DownstreamScheme": "http",
      "DownstreamHostAndPorts": [
        {
          "Host": "localhost",
          "Port": 5000
        }
      ],
      "UpstreamPathTemplate": "/image-uploader-microservice/upload-images",
      "UpstreamHttpMethod": [ "POST" ],
}
    
```

But when I am adding new endpoint to ImageUploader microservice (for example `/delete-images`) I have to copy this block of configuration and paste with replacing `/upload-images` to /`delete-images`).

I've read that I can use placeholders in the `UpstreamPathTemplate`, but in this case, I will broke my main logic of documentation building. Are there more attractive way that allows me to configure routings more flexible? Something like this:

```
 "UpstreamPathTemplate": "/image-uploader-microservice/{action}",
 "AvailablePlaceholders": {
    "action": [
       "upload-images",
       "delete-images"
    ]
 }
```

**Comment by raman-m** [comment]
Define one [Catch All](https://ocelot.readthedocs.io/en/latest/features/routing.html#catch-all) route with required HTTP verbs!
