### ISSUE TITLE
HTTP response 500 is cached

### ISSUE THREAD

**Issue by wast** [ThreeMammals/Ocelot#1108]
## Expected Behavior / New Feature
Errors 500 shouldn't be cached.

## Actual Behavior / Motivation for New Feature
Errors 500 are cached.

## Steps to Reproduce the Problem

  1. Add Caching
`.AddCacheManager(x =>
                {
                    x.WithDictionaryHandle();
                });`
  2. Add FileCacheOptions in ocelot.json for service.
  3. Make a HTTP 500 response from service.
  4. Response is cached but service doesn't return HTTP 500 anymore.

## Specifications

  - Version: v13.8.0
  - Platform: .NET Core 3.1
  - Subsystem: N/A

I'm not sure if this should be reported here or at MichaCo/CacheManager. Looking for advice.

**Comment by raman-m** [comment]
Dear Stjepan,

You were the member of ThreeMammals org for the years!
What is the result of your membership? These [2 commits](https://github.com/ThreeMammals/Ocelot/commits?author=wast) only? One of which was delivered by me...
You should understand once you've joined the project/organization you should contribute!
Regarding this issue... I believe you have enough C# expertise to fix it by your own.
Good luck!

**Comment by wast** [comment]
Time is a resource which is limited and life happens all the way. No need to be passive aggressive.
