### ISSUE TITLE
Aggregation not working when the Downstream has authentication

### ISSUE THREAD

**Issue by rusodan** [ThreeMammals/Ocelot#1109]
## Expected Behavior
Get  an unique result in one call from different microservices

## Actual Behavior
The result of microservices is empty because are unauthorized. With microservices that has no security, the aggregation is working fine.

## Example
If I try any microservice individually, they return the expected result (I have authentication in both microservices):

![image](https://user-images.githubusercontent.com/60117370/72763247-8b8c6580-3ba8-11ea-99e0-36e624d018e2.png)

After login, I see the correct user (DanielCol) in the result of both microservice:
![image](https://user-images.githubusercontent.com/60117370/72763291-cf7f6a80-3ba8-11ea-9096-0a0d567c99ba.png)

![image](https://user-images.githubusercontent.com/60117370/72763299-d8703c00-3ba8-11ea-9e23-5911bbe20dbe.png)

If I use the aggregation, I see empty result from both services:
![image](https://user-images.githubusercontent.com/60117370/72763502-ae6b4980-3ba9-11ea-8a52-effa75be9980.png)

Unauthorized error is raised in both: 
![image](https://user-images.githubusercontent.com/60117370/72763509-b5925780-3ba9-11ea-917a-b5933ba31aab.png)

Any way to fix this?

This is my custom aggregator:
![image](https://user-images.githubusercontent.com/60117370/72763547-dd81bb00-3ba9-11ea-9bd9-902f680d1b8c.png)

The configuration of the aggregate:
![image](https://user-images.githubusercontent.com/60117370/72763558-ee323100-3ba9-11ea-8c4f-8aeb02302a26.png)

And the microservices:
![image](https://user-images.githubusercontent.com/60117370/72763569-f9855c80-3ba9-11ea-8d04-5538f9985a71.png)

##Another test
I added NTLM authentication to the net core app:
![image](https://user-images.githubusercontent.com/60117370/72769760-6bb56b80-3bc1-11ea-8ab3-92c006bdaa4f.png)

![image](https://user-images.githubusercontent.com/60117370/72769774-7c65e180-3bc1-11ea-8865-ba481e6858d9.png)

And I tried to pass those credentials to the aggregation but I don´t know how, may be in the AuthenticationMiddleware.

## Specifications
  - Version: Ocelot 13.8.0 and .NET Core 3.1
  - Platform: Windows 10

**Comment by BharathaAravind** [comment]
seeing the same issue as well.

**Comment by raman-m** [comment]
@rusodan 
Add anonymous route to allow anonim traffic goes to authentication endpoint.
Or exclude  authentication endpoint from Ocelot config at all to get token/cookie and other auth artifact to allow your auth route working.
