### ISSUE TITLE
Ocelot + Asp.Net Core 3.1 Web API Redirects Http Downstream URL to Https URL

### ISSUE THREAD

**Issue by PirasannaRavi** [ThreeMammals/Ocelot#1111]
Below is my Ocelot.json
```json
{
    "ReRoutes": [
        {
            "DownstreamPathTemplate": "/api/{catchAll}",
            "DownstreamScheme": "http",
            "DownstreamHostAndPorts": [
                {
                    "Host": "localhost",
                    "Port": 7001
                }
            ],
            "UpstreamPathTemplate": "/karma-api/{catchAll}",
            "HttpHandlerOptions": {
                "AllowAutoRedirect": false
            },
            "DownstreamHeaderTransform": {
              "Location": "{DownstreamBaseUrl}, {BaseUrl}"
            }
        }
    ],
    "GlobalConfiguration": {
        "BaseUrl": "http://localhost:7000"
    }
}
```
And when I make a call to http://localhost:7000/karma-api/karma/get, I expect the call will be forwarded to http://localhost:7001/api/karma/get but the call actually forwards to the Https URL instead that is https://localhost:7001/api/karma/get.

I commented the app.UseHttpsRedirection(); in the Configure method of Startup class. Still the issue continues.

How to fix this?

**Comment by raman-m** [comment]
Yes, this is the karma! :rofl: 

I guess you had some special status code or special downstream service behavior.
Please, write us more fairy tales!
