### ISSUE TITLE
How to disable changing ocelot config on runtime

### ISSUE THREAD

**Issue by damirci** [ThreeMammals/Ocelot#1112]
I want to disable this '/configuration' route of Ocelot that is using for changing and reading configuration on runtime. 
I tried to ignore this route by asp.net APIs but it seems that Ocelot rewrite my configuration.

also using [administration auth configs](https://ocelot.readthedocs.io/en/latest/features/administration.html#administration-api) do not effect on /configuration route

## Specifications

  - Version: 12.1

**Comment by raman-m** [comment]
## :rofl:
