### ISSUE TITLE
Asp.Net Core 3.1 Web API Redirect localhost -->locahost (301_loopback_error)

### ISSUE THREAD

**Issue by jurgi** [ThreeMammals/Ocelot#1113]
With .netCore 2.2 and Ocelot 13.5.2 version, simple routing works well.
With .netCore 3.1 and Ocelot 14.0.3 I get the following answer:
```
301 Redirect Loop Detected (301_loopback_error)
Your request results in redirection back to 127.0.
```

## Steps to Reproduce the Problem
To do the test I created a solution with a project with Ocelot and a basic aspnet core mvc project.
Make a GET request https://localhost: 3300/Home/Privacy

### Ocelot logging
Now listening on: https://localhost:3300
Application started. Press Ctrl+C to shut down.
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/2 GET https://localhost:3300/Home/Privacy
info: Ocelot.RateLimit.Middleware.ClientRateLimitMiddleware[0]
      requestId: 0HLT0LF3TFCT3:00000001, previousRequestId: no previous request id, message: EndpointRateLimiting is not enabled for /Home/Privacy
info: Ocelot.Authentication.Middleware.AuthenticationMiddleware[0]
      requestId: 0HLT0LF3TFCT3:00000001, previousRequestId: no previous request id, message: No authentication needed for /Home/Privacy
info: Ocelot.Authorisation.Middleware.AuthorisationMiddleware[0]
      requestId: 0HLT0LF3TFCT3:00000001, previousRequestId: no previous request id, message: /Home/Privacy route does not require user to be authorised
info: Ocelot.Requester.Middleware.HttpRequesterMiddleware[0]
      requestId: 0HLT0LF3TFCT3:00000001, previousRequestId: no previous request id, message: 301 (Moved Permanently) status code, request uri: https://localhost:44316/Home/Privacy
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished in 686.7222ms 301 text/html; charset=utf-8
	  
### Configuration
```
{
  "ReRoutes": [
    {
      "DownstreamPathTemplate": "/Home/Privacy",
      "DownstreamScheme": "https",
      "DownstreamHostAndPorts": [
        {
          "Host": "localhost",
          "Port": 44316
        }
      ],
      "UpstreamPathTemplate": "/Home/Privacy",
      "HttpHandlerOptions": {
        "AllowAutoRedirect": false
      },
      "UpstreamHttpMethod": [ "Get", "Post" ]
    }
  ],
  "DangerousAcceptAnyServerCertificateValidator": true,
  "GlobalConfiguration": {
    "RequestIdKey": "OcRequestId",
    "BaseUrl": "http://localhost:3300"
  }
}
```

### Program.cs
```
 public class Program
    {
        public static void Main(string[] args)
        {
            new WebHostBuilder()
            .UseKestrel()
            .UseContentRoot(Directory.GetCurrentDirectory())
            .ConfigureAppConfiguration((hostingContext, config) =>
            {
                config
                    .SetBasePath(hostingContext.HostingEnvironment.ContentRootPath)
                    .AddJsonFile("appsettings.json", true, true)
                    .AddJsonFile($"appsettings.{hostingContext.HostingEnvironment.EnvironmentName}.json", true, true)
                    .AddJsonFile("ocelot.json", optional: false, reloadOnChange: true)
                    .AddEnvironmentVariables();
            })
            .ConfigureServices(s =>
            {
                s.AddOcelot();
            })
            .ConfigureLogging((hostingContext, logging) =>
            {
                logging.AddConsole();
            })
            .UseIISIntegration()
            .Configure(app =>
            {
                app.UseOcelot().Wait();
            })
            .Build()
            .Run();
        }
    }
```

## Specifications

  - Version: 14.0.3
  - Platform: Windows 10
  - Subsystem: VS2019 16.4.3 .netCore SDK 3.1.101

**Comment by billyhiuwali** [comment]
Hi , i am facing this loopback problem. 
May i know if you have already found the solution or the cause?

**Comment by jmzagorski** [comment]
I notice in IIS when I am sending the request downstream to another website's application the final status code in the "Failed Request Tracing" is a 301, even though on my client I am getting a 404. Not sure if this is related.

**Comment by raman-m** [comment]
Hi @jurgi !
Could you upgrade your solution to .NET 7 & Ocelot 19 please?
And, let me know testing results plz!

**Comment by raman-m** [comment]
@jurgi  Please, write us more fairy tales!

**Comment by raman-m** [comment]
The author doesn't care!
