### ISSUE TITLE
SocketException on binding to localhost using several ports when running Ocelot acceptance tests

### ISSUE THREAD

**Issue by jlukawska** [ThreeMammals/Ocelot#1115]
## Expected Behavior / New Feature

All acceptance tests can be run successfully independently from Windows configuration.

## Actual Behavior / Motivation for New Feature

Since I installed Docker and Hyper-V on my machine, several acceptance tests crash on binding to localhost. The exception is:

```
System.IO.IOException : Failed to bind to address http://localhost:51388.
    ---- System.AggregateException : One or more errors occurred. (An attempt was made to access a socket in a way forbidden by its access permissions.) (An attempt was made to access a socket in a way forbidden by its access permissions.)
    -------- System.Net.Sockets.SocketException : An attempt was made to access a socket in a way forbidden by its access permissions.
```
    
First, I thought that something opened these ports, but they are not opened (netstat does not list them as used). It turned out that they are reserved by Hyper-V. And what worse, the reserved port ranges can change after system reboot. 

Here you can find a discussion about this problem and possible workarounds on Docker github: https://github.com/docker/for-win/issues/3171

I would like to start a discussion about that issue and possible solutions. Maybe ports to use in the acceptance tests should be randomly generated  and checked if the binding to them is possible. If the problem with binding to the port exists, a new port should be generated. What do you think?

I think this is quite important, because there is high probability that when you have Hyper-V enabled you will not be able to run all the tests successfully.

Maybe this issue is the reason for changes made in the following commit 07df311094a25329153dffa451d63c8036c4d77c ?

## Steps to Reproduce the Problem

  1. Enable Hyper-V in Windows
  1. Run all Ocelot acceptance tests

## Specifications

  - Platform: Windows 10 Pro

**Comment by TomPallister** [comment]
this is now merged into master

**Comment by raman-m** [comment]
Merge commit is https://github.com/ThreeMammals/Ocelot/commit/263f26ed51df87ebe5f2a8446be0337c21690cd7
