### ISSUE TITLE
Ocelot on IIS

### ISSUE THREAD

**Issue by mohamed-mohamed2563** [ThreeMammals/Ocelot#1118]
hello everybody,
 i have 2 apps, each app in different directory in IIS , when call any api return 404 and apps as the following :

- first app called "OcelotGateway" in directory "localhost/XYZ/OcelotGateway"

- second app calld "Authentication" in directory "localhost/XYZ/Authentication"

how to write configuration of Reroutes to handle something like this  

my ocelot.json file is

```
{
 "ReRoutes": [
    {
      "DownstreamPathTemplate": "/api/{everything}",
      "DownstreamScheme": "http",
      "DownstreamHostAndPorts": [
        {
          "Host": "localhost/XYZ/OcelotGateway",
          "port": 58748

        }
      ],
      "UpstreamPathTemplate": "/api/auth/{everything}",
      "UpstreamHttpMethod": [
        "POST"
      ]
    },
],
 "GlobalConfiguration": {
    "BaseUrl": "http://localhost:5000/xyz/OcelotGateway"
  }
}
```

thanks in advanced

**Comment by jmezach** [comment]
@mohamed-mohamed2563 Okay, so the `DownstreamPathTemplate`, `DownstreamScheme` and `DownstreamHostAndPorts` refer to what will essentially be behind your API gateway, while the `UpstreamPathTemplate` and `UpstreamHttpMethod` properties refer to what the client will be calling on your API gateway.

So assuming that `http://localhost:5000/XYZ/OcelotGateway` is the base URI of your API gateway and you want to put `http://localhost:58748/XYZ/Authentication` behind that gateway and expose that through `/api/auth/{everything}` you'll want to have the following configuration:

```json
{
 "ReRoutes": [
    {
      "UpstreamPathTemplate": "/api/auth/{everything}",
      "UpstreamHttpMethod": [
        "POST"
      ],
      "DownstreamPathTemplate": "/XYZ/Authentication/{everything}",
      "DownstreamScheme": "http",
      "DownstreamHostAndPorts": [
        {
          "Host": "localhost",
          "Port": 58748
        }
      ]
    },
],
 "GlobalConfiguration": {
    "BaseUrl": "http://localhost:5000/xyz/OcelotGateway"
  }
}
```

Does that answer your question?

**Comment by HorjeaCosmin** [comment]
Hi @jmezach,

I have a similar approach / issue on my staging server, using IIS.

This is my ocelot.json file:

{
  "ReRoutes": [
    {
      "DownstreamPathTemplate": "/commonFolder/api1/api/products/{everything}",
      "DownstreamScheme": "http",
      "DownstreamHostAndPorts": [
        {
          "Host": "localhost",
          "Port": 80
        }
      ],
      "UpstreamPathTemplate": "/api1/{everything}",
      "UpstreamHttpMethod": [ "Post" ],

    }
  ],
  "GlobalConfiguration": {
    "BaseUrl": "https://mydomain.com/commonFolder/gateway"
  }
}

When I use Postman with the following url https://mydomain.com/commonFolder/gateway/api1/post I get nothing more then a  HTTP Error 500.37 - ANCM Failed to Start Within Startup Time Limit.

My solution is build using .net core 3.1 and Ocelot 14.0.11. Btw, running on my machine using IISExpress, everything works fine. 

Any help will be very appreciated.

Regards,
C

**Comment by jmezach** [comment]
The ANCM Failed To Start Within Startup Time Limit error suggests that something is going wrong during startup of your API gateway application. You could try enabling logging through the Web.config as documented [here[(https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/aspnet-core-module?view=aspnetcore-3.1#log-creation-and-redirection) to figure out what's going wrong.

**Comment by HorjeaCosmin** [comment]
This is what I get on log:

[aspnetcorev2.dll] Initializing logs for 'C:\Program Files\IIS\Asp.Net Core Module\V2\aspnetcorev2.dll'. Process Id: 7864.. File Version: 13.1.20018.2. Description: IIS ASP.NET Core Module V2. Commit: c3acdcac86dad91c3d3fbc3b93ecc6b7ba494bdc.
[aspnetcorev2.dll] Resolving hostfxr parameters for application: '.\APIGateway.exe' arguments: '' path: 'C:\mydomain.com\commonFolder\Gateway\'
[aspnetcorev2.dll] Known dotnet.exe location: ''
[aspnetcorev2.dll] Process path '.\APIGateway.exe' is not dotnet, treating application as standalone or portable with bootstrapper
[aspnetcorev2.dll] Checking application.dll at 'C:\mydomain.com\commonFolder\Gateway\.\expressoft.Connect.APIGateway.dll'
[aspnetcorev2.dll] Checking hostfxr.dll at 'C:\mydomain.com\commonFolder\Gateway\.\hostfxr.dll'
[aspnetcorev2.dll] hostfxr.dll found app local at 'C:\mydomain.com\commonFolder\Gateway\.\hostfxr.dll', treating application as portable with launcher
[aspnetcorev2.dll] Resolving absolute path to dotnet.exe from 'dotnet'
[aspnetcorev2.dll] Invoking where.exe to find dotnet.exe
[aspnetcorev2.dll] where.exe invocation returned: 'C:\Program Files\dotnet\dotnet.exe
C:\Program Files (x86)\dotnet\dotnet.exe
'
[aspnetcorev2.dll] Current process bitness type detected as isX64=1
[aspnetcorev2.dll] Processing entry 'C:\Program Files\dotnet\dotnet.exe'
[aspnetcorev2.dll] Binary type 6
[aspnetcorev2.dll] Found dotnet.exe via where.exe invocation at 'C:\Program Files\dotnet\dotnet.exe'
[aspnetcorev2.dll] Resolving absolute path to hostfxr.dll from 'C:\Program Files\dotnet\dotnet.exe'
[aspnetcorev2.dll] hostfxr.dll located at 'C:\Program Files\dotnet\host\fxr\3.1.2\hostfxr.dll'
[aspnetcorev2.dll] Parsed hostfxr options: dotnet location: 'C:\Program Files\dotnet\dotnet.exe' hostfxr path: 'C:\Program Files\dotnet\host\fxr\3.1.2\hostfxr.dll' arguments:
[aspnetcorev2.dll] Argument[0] = 'C:\Program Files\dotnet\dotnet.exe'
[aspnetcorev2.dll] Argument[1] = 'C:\mydomain.com\commonFolder\Gateway\.\expressoft.Connect.APIGateway.dll'
[aspnetcorev2.dll] Loading hostfxr from location C:\Program Files\dotnet\host\fxr\3.1.2\hostfxr.dll
[aspnetcorev2.dll] Canceling standard stream pipe reader
[aspnetcorev2.dll] Loading request handler:  'C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\3.1.2\aspnetcorev2_inprocess.dll'
[aspnetcorev2.dll] Creating handler application
[aspnetcorev2_inprocess.dll] Initializing logs for 'C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\3.1.2\aspnetcorev2_inprocess.dll'. Process Id: 7864.. File Version: 13.1.20018.2. Description: IIS ASP.NET Core Module V2 Request Handler. Commit: c3acdcac86dad91c3d3fbc3b93ecc6b7ba494bdc.
[aspnetcorev2_inprocess.dll] Waiting for initialization
[aspnetcorev2_inprocess.dll] Starting in-process worker thread
[aspnetcorev2_inprocess.dll] Resolving hostfxr parameters for application: '.\APIGateway.exe' arguments: '' path: 'C:\mydomain.com\commonFolder\Gateway\'
[aspnetcorev2_inprocess.dll] Known dotnet.exe location: 'C:\Program Files\dotnet\dotnet.exe'
[aspnetcorev2_inprocess.dll] Process path '.\APIGateway.exe' is not dotnet, treating application as standalone or portable with bootstrapper
[aspnetcorev2_inprocess.dll] Checking application.dll at 'C:\mydomain.com\commonFolder\Gateway\.\expressoft.Connect.APIGateway.dll'
[aspnetcorev2_inprocess.dll] Checking hostfxr.dll at 'C:\mydomain.com\commonFolder\Gateway\.\hostfxr.dll'
[aspnetcorev2_inprocess.dll] hostfxr.dll found app local at 'C:\mydomain.com\commonFolder\Gateway\.\hostfxr.dll', treating application as portable with launcher
[aspnetcorev2_inprocess.dll] Resolving absolute path to hostfxr.dll from 'C:\Program Files\dotnet\dotnet.exe'
[aspnetcorev2_inprocess.dll] hostfxr.dll located at 'C:\Program Files\dotnet\host\fxr\3.1.2\hostfxr.dll'
[aspnetcorev2_inprocess.dll] Parsed hostfxr options: dotnet location: 'C:\Program Files\dotnet\dotnet.exe' hostfxr path: 'C:\Program Files\dotnet\host\fxr\3.1.2\hostfxr.dll' arguments:
[aspnetcorev2_inprocess.dll] Argument[0] = 'C:\Program Files\dotnet\dotnet.exe'
[aspnetcorev2_inprocess.dll] Argument[1] = 'C:\mydomain.com\commonFolder\Gateway\.\expressoft.Connect.APIGateway.dll'
[aspnetcorev2_inprocess.dll] Setting environment variable ASPNETCORE_IIS_HTTPAUTH=anonymous;
[aspnetcorev2_inprocess.dll] Setting environment variable ASPNETCORE_IIS_PHYSICAL_PATH=C:\mydomain.com\commonFolder\Gateway\
[aspnetcorev2_inprocess.dll] Loading hostfxr from location C:\Program Files\dotnet\host\fxr\3.1.2\hostfxr.dll
[aspnetcorev2_inprocess.dll] Initial Dll directory: '', current directory: 'c:\windows\system32\inetsrv'
[aspnetcorev2_inprocess.dll] Setting dll directory to c:\windows\system32\inetsrv
[aspnetcorev2_inprocess.dll] Setting current directory to C:\mydomain.com\commonFolder\Gateway\
[aspnetcorev2_inprocess.dll] Stopping CLR
[aspnetcorev2_inprocess.dll] Starting shutdown sequence 0
[aspnetcorev2_inprocess.dll] Clr thread wait ended: clrThreadExited: 0
[aspnetcorev2_inprocess.dll] Canceling standard stream pipe reader
[aspnetcorev2_inprocess.dll] Stopping in-process worker thread
[aspnetcorev2_inprocess.dll] Event Log: 'Application '/LM/W3SVC/2/ROOT/expressoft.connect/Gateway' with physical root 'C:\mydomain.com\commonFolder\Gateway\' failed to load coreclr. Exception message:
Managed server didn't initialize after 120000 ms.' 
End Event Log Message.
[aspnetcorev2_inprocess.dll] InvalidOperationException 'Managed server didn't initialize after 120000 ms.' caught at F:\workspace\_work\1\s\src\Servers\IIS\AspNetCoreModuleV2\InProcessRequestHandler\inprocessapplication.cpp:420 
[aspnetcorev2_inprocess.dll] Failed HRESULT returned: 0x8007023e at F:\workspace\_work\1\s\src\Servers\IIS\AspNetCoreModuleV2\InProcessRequestHandler\dllmain.cpp:131 
[aspnetcorev2_inprocess.dll] Starting app_offline monitoring in application 'C:\mydomain.com\commonFolder\Gateway\'
[aspnetcorev2_inprocess.dll] Starting file watcher thread

Tks,
C

**Comment by HorjeaCosmin** [comment]
Hi again,

I found a solution based on "failed dto load creclr" exception and now everything works fine if I switch from inprocess to outOfProcess hostingModel.

Thank you very much for your time @jmezach!

Regards,
C

**Comment by jmezach** [comment]
Cool! No problem. Glad I could help you out. I'll go ahead and close this issue.
