### ISSUE TITLE
Ocelot not depending on .net standard

### ISSUE THREAD

**Issue by TheElectricCo** [ThreeMammals/Ocelot#1136]
## Expected Behavior / New Feature

As stated in the ReadMe, Ocelot depends on .net standard 2.0 and should be usable with full .net framework

## Actual Behavior / Motivation for New Feature

Nuget states that Ocelot 14.0.9 depends on .net core 3.1

![image](https://user-images.githubusercontent.com/8233632/74723598-25dcd900-523b-11ea-9798-12b8e31bf164.png)

**Comment by jmezach** [comment]
This was changed as part of the .NET Core 3.0 upgrade (see #1025). I remember we discussed this at the time and decided that it was fine to switch to using netcoreapp3.1 and figured that folks who want to keep using it on older versions of .NET should stick with the older versions of Ocelot.

We should at least update the documentation to point this out, but  I'm wondering if you have a particular use case in mind that requires you to have Ocelot target .NET Standard 2.0?

**Comment by TheElectricCo** [comment]
Hi @jmezach,

thanks for the reply! 

No, I don't have an actual use case, but I was following the MS Microservices architecture paper and it also stated that Ocelot targets .net standard 2.0 and you could use it with .net core or full .net. I was experimenting with a asp.net core application targeting the full .net framework (net48), noticing that my Ocelot package was complaining. 

meanwhile I changed the package to netcoreapp 3.1 and everything works as a charm, thank you for this fine piece of software!

**Comment by jmezach** [comment]
I see. Not sure what we can about the Microsoft docs to be honest, I'll have to check with @TomPallister. And its really him you should be thanking, since he wrote most of the code here.

We'll update the README here though so that folks know that we do not target .NET Standard anymore ;)

**Comment by raman-m** [comment]
Not an issue!
Fixed by #1025
