### ISSUE TITLE
Got HTTP 404 if builderAction parameter is specified when calling app.UseOcelot method

### ISSUE THREAD

**Issue by daxnet** [ThreeMammals/Ocelot#1137]
## Expected Behavior / New Feature
When I specifies the builderAction parameter in app.UseOcelot method, run the api gateway and navigate to the upstream URL, I would expect that api gateway can return me the API response from downstream.

## Actual Behavior / Motivation for New Feature
I got HTTP 404 error.

## Steps to Reproduce the Problem
ocelot.configuration.json:
```
{
  "ReRoutes": [
    {
      "DownstreamPathTemplate": "/api/themes",
      "DownstreamScheme": "http",
      "DownstreamHostAndPorts": [
        {
          "Host": "localhost",
          "Port": 5010
        }
      ],
      "UpstreamPathTemplate": "/themes-api/themes",
      "UpstreamHttpMethod": [ "Get" ]
    }
  ]
}
```
Program.cs:
```
public class Program
{
    public static void Main(string[] args)
    {
        CreateHostBuilder(args).Build().Run();
    }

    public static IHostBuilder CreateHostBuilder(string[] args) =>
        Host.CreateDefaultBuilder(args)
            .ConfigureWebHostDefaults(webBuilder =>
            {
                webBuilder.UseStartup<Startup>();
            })
            .ConfigureAppConfiguration(configBuilder =>
            {
                configBuilder.AddJsonFile("ocelot.configuration.json");
            })
            .ConfigureServices((buildContext, services) =>
            {
                services.AddOcelot();
            });
}
```
Startup.cs:
```
public class Startup
{
    public void ConfigureServices(IServiceCollection services)
    {
    }

    public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
    {
        if (env.IsDevelopment())
        {
            app.UseDeveloperExceptionPage();
        }
        app.UseRouting();
        app.UseEndpoints(endpoints =>
        {
            endpoints.MapGet("/", async context =>
            {
                await context.Response.WriteAsync("Hello World!");
            });
        });

        var config = new OcelotPipelineConfiguration();
        app.UseOcelot((b, c) =>
        {
           // NOTE: Do nothing here will cause HTTP 404, if I call 'app.UseOcelot();', everything worked fine.
        }).Wait();
    }
}
```
My questions are
- I can only see `BuildOcelotPipeline`, `MapWhen` and `UseMiddleware` extension methods if I add `using Ocelot.Middleware.Pipeline;` using directive, where is the `UseDownstreamRouteFinderMiddleware` method defined?
- How can I use a middleware in Ocelot? Seems even if I use b.UseMiddleware in the above code, I can only get HTTP 404, is there any documentation on this? 

## Specifications

  - Version: 14.0.9
  - Platform: Windows 10
  - Subsystem: Windows

**Comment by jmezach** [comment]
Hmm, that's interesting. I've tried this a while back and it was working, although I agree that the documentation isn't very clear on how this should work. But I wasn't getting any 404's as far as I can recall. Do you have some logging that you can share so we can figure out what's going on here?

**Comment by daxnet** [comment]
Hi @jmezach ,
Thanks for the feedback.
I made a very simple example app and pushed to github:
[https://github.com/daxnet/OcelotDemo](https://github.com/daxnet/OcelotDemo)
You can have a test by first running `OcelotDemo.API` then `OcelotDemo.Gateway`, you will see everything works fine. But if you comment the line:
`app.UseOcelot().Wait();`
and uncomment the line:
`app.UseOcelot((builder, config) => { }).Wait();`
in the Startup.cs file of `OcelotDemo.Gateway` and then restart the stuff, you will see 404 if you navigate to `http://localhost:9999/weather`.

**Comment by raman-m** [comment]
@daxnet 
Please continue to write us more short stories! :smile:
