### ISSUE TITLE
Failed Auth Alerting

### ISSUE THREAD

**Issue by jords1987** [ThreeMammals/Ocelot#1139]
## New Feature
Alerting of failed auth events

## Motivation for New Feature
Would be nice to be able to easily push out an alert for a failed auth event, currently these are logged in the log files. This could be very useful information for attack/intrusion notification. Maybe this could be done in custom middleware?

Looking for others suggestions or if anyone has an implementation, awesome.

**Comment by jmezach** [comment]
I like this idea, although I guess you could already create this by centralising your logging into something like the Elastic Stack and putting alerts on it there. But I agree that having something built-in would be nice. I am curious as to where we would sent those notifications though. Do you have something in mind already?

**Comment by jords1987** [comment]
Thanks @jmezach... If this feature existed already, I would fire it into our opsgenie probably (https://www.atlassian.com/software/opsgenie) through a webhook or similar.

Ideally would include some sort of limit threshold, or not and we aggregate them into an alerting threshold somewhere else (app insights maybe?)

**Comment by jmezach** [comment]
Makes sense, although I don't think we'll want to have all kinds of integrations with different products in Ocelot itself, nor would we probably want to build and maintain all of them.

I could imagine defining some kind of interface though that users of Ocelot can implement themselves as needed and register with DI. We can then call into that implementation from Ocelot when we have some auditable event. @TomPallister What do you think about this?

@jords1987 I'm wondering what kind of information you would like to see for this?

**Comment by jords1987** [comment]
Yeah totally agree implementation would be with the app rather than in ocelot itself.

Not really sure what info, the basics:
- datetime
- request source 
- upstream path

Do you have any other ideas?

**Comment by jmezach** [comment]
I guess we could add something like this:

```csharp
public interface IAuditEventListener
{
    Task NotifyAuditEvent(AuditableEvent @event);
}

public class AuditableEvent
{
    public string EventType { get; } // Could be AuthorizationFailed, AuthorizationSuccessful, etc.
    public DateTime Timestamp { get; }
    public string RequestPath { get; }
    public string SourceIP { get; }
}
```

@jords1987 Would that work for you?
@TomPallister Curious to hear your thoughts on this. Is this something you'd like to see in Ocelot?

**Comment by jords1987** [comment]
@jmezach that would work for me brilliantly, what do you think to including the whole HttpContext so people can take from it what they need to? maybe thats overkill? could probably just use IHttpContextAccessor if they really want to see that.

**Comment by jords1987** [comment]
Any more thoughts on this one @jmezach @TomPallister ?

**Comment by raman-m** [comment]
@jords1987 
>Would be nice to be able to easily push out an alert for a failed auth event, currently these are logged in the log files. This could be very useful information for attack/intrusion notification. Maybe this could be done in custom middleware?

You have to design and develop your own AuthenticationMiddleware with desired events. After that you need to override the middleware by [Middleware Injection](https://ocelot.readthedocs.io/en/latest/features/middlewareinjection.html). 
Regarding authentication events. Every auth provider has own set of the events. Ocelot is not responsible for supporting them.
We won't do what you've requested.
Please fork Ocelot repository and develop whatever you want.
Good luck!

### P.S.
In future we expect PRs. Adding very basic auth events into native [AuthenticationMiddleware](https://github.com/search?q=repo%3AThreeMammals%2FOcelot%20AuthenticationMiddleware&type=code) still makes sense. But we have no time for that.
