### ISSUE TITLE
[Question] Ocelot jwt authentication with web api (not .net core api)

### ISSUE THREAD

**Issue by dongphh** [ThreeMammals/Ocelot#1142]
Hi,

How do i using bearer jtw authication with my web api 2 ?

I have setup ocelot with jwt auth, it run ok. 
Now I have 1 web api 2 (not .net core api) that I want to authenticate using ocelot auth. How to configure in web api 2 to auth token request.Can you give me example.

My system diagram

client ---> ocelot gateway <---  auth using jwt token -- > web api 2
 ocelot include ( Logging,jwt bearer token)

![api](https://user-images.githubusercontent.com/43638657/75089167-b93e4300-5588-11ea-9507-93a8f44ac29a.jpg)

i used source in : https://www.c-sharpcorner.com/article/building-api-gateway-using-ocelot-in-asp-net-core-part-two/
Thanks.

**Comment by raman-m** [comment]
## Answer
- [JWT Tokens](https://ocelot.readthedocs.io/en/latest/features/authentication.html#jwt-tokens)
