### ISSUE TITLE
Instead of merging, why we cannot extend the environment configuration with global configuration reroutes

### ISSUE THREAD

**Issue by HariSittu** [ThreeMammals/Ocelot#1146]
In my project, the count of reroutes is quite more. In case of new environment, the changes to the global configuration is DownstreamPath. But what i have to do is, copy the whole configuration and change the DownstreamPath of each route.
Instead why can't we implement below like example,

global json,
```json
{
  "Routes": [{
      "Key" : "one",
      "AuthenticationOptions": {
        "AuthenticationProviderKey": "",
        "AllowedScopes": []
      },
      "DownstreamPathTemplate": "/SomePath",
      "UpstreamPathTemplate": "/SomePath",
      "UpstreamHttpMethod": [
        "GET"
      ],
      "DownstreamScheme": "https",
      "DownstreamHostAndPorts": [
        {
          "Host": "{somehost}",
          "Port": 443
        }
      ]
    }],
  "GlobalConfiguration": {
    "BaseURL": "http://localhost:50130"
  }
}
```
my new environment json,
```json
{
  "Routes": [{
      "Key" : "one",
      "DownstreamHostAndPorts": [
        {
          "Host": "{ChangedHost}",
          "Port": 4430
        }
      ]
    }]
}
```
For Creating json, extending by key would help more

**Comment by raman-m** [comment]
Why not to use [Consul](https://ocelot.readthedocs.io/en/latest/features/servicediscovery.html#consul) and [Service Discovery](https://ocelot.readthedocs.io/en/latest/features/servicediscovery.html) feature?
I believe [Dynamic Routing](https://ocelot.readthedocs.io/en/latest/features/servicediscovery.html#dynamic-routing) is exactly what you wanted! 
You will write zero routes! :wink:
