### ISSUE TITLE
UpstreamHeaderTransform doesn't work

### ISSUE THREAD

**Issue by CwjXFH** [ThreeMammals/Ocelot#1147]
Hi,

The [doc](https://ocelot.readthedocs.io/en/latest/features/headerstransformation.html) said, can use **UpstreanHeaderTransform** to add header to upstream request.
I configure ocelot like this:
```json
  "ReRoutes": [
    {
      "DownstreamHostAndPorts": [
        {
          "Host": "localhost",
          "Port": 5001
        }
      ],
      "DownstreamPathTemplate": "/order/{everything}",
      "DownstreamScheme": "http",

      "UpstreamPathTemplate": "/eason/order/{everything}",
      "UpstreamHttpMethod": [],
      "UpstreamHeaderTransform": {
        "Accept": "application/json",
        "ocelot": "netcore apigateway"
      }
    }
  ]
```
But the **UpstreamHeaderTransform** doesn't add headers to the upstream request.

![](https://user-images.githubusercontent.com/11468733/75617992-231aa600-5ba2-11ea-9e11-1a0bd4206b76.PNG)

My dev environment:

**.NET Core Version**: 3.1
**Ocelot Version**: 14.0.11

**Comment by RomainHautefeuille** [comment]
I suspect vscode-restclient displaying only the request headers that it generates (User-Agent & accept-encoding).
Ocelot being a proxy, there is no way for vscode-restclient to know which headers are added to the request by the proxy and display them, at least none that I am aware of.
Are you sure that the headers are not correctly received by the webapi? I would suspect they actually are.
Also might be useful to look at debug logs.

**Comment by jlukawska** [comment]
Hello,

UpstreamHeaderTransform adds a header to the request. As I see you expect your headers in the response. 

If you want add headers to responses you should use DownstreamHeaderTransform. 

If you want to use UpstreamHeaderTransform and check if headers are added in the request, you can find them e.g. in service controller actions using Request.Headers["ocelot"].

**Comment by CwjXFH** [comment]
@RomainHautefeuille @jlukawska 
You're right, thanks!
