### ISSUE TITLE
Unexpected behavior of Polly

### ISSUE THREAD

**Issue by mphelt** [ThreeMammals/Ocelot#1153]
## Expected Behavior
Having:
```
"QoSOptions": {
  "TimeoutValue":10000
}
```
and no Polly everything works as expected - timeout is respected as per #604 .
I would expect everything to work exactly the same after .AddPolly() is added.

## Actual Behavior
Unfortunatelly after .AddPolly() is added it doesn't work anymore.
The following error is logged: "Error in CircuitBreakingDelegatingHandler.SendAync".
It starts to work again with the following change:
```
"QoSOptions": {
 "ExceptionsAllowedBeforeBreaking":1,
 "TimeoutValue":10000
}
```

Is this by design or a bug?

## Specifications
  - Version: 14.1.0
  - Platform: Windows 10 x64

**Comment by raman-m** [comment]
Ancient issue!

We have upgraded Polly provider much. Please use our new version [23.2](https://github.com/ThreeMammals/Ocelot/milestone/5) where Polly v8 functionality introduced with resilience pipelines. You will be able to implement any Polly behavior!
See PR #1914 for more details.
