### ISSUE TITLE
Why have I been making 500 errors under.net CORE 3.1

### ISSUE THREAD

**Issue by JHeLiu** [ThreeMammals/Ocelot#1156]
Why have I been making 500 errors under.net CORE 3.1

**Comment by jmezach** [comment]
Hi @JHeLiu, could you elaborate a little bit about your setup? What kind of errors are you seeing? Do you see anything in the logs? What does your Program.cs and/or Startup.cs and configuration look like?

**Comment by JHeLiu** [comment]
@jmezach Sorry, I saved it directly with browser access, if I can request it with program, may this be my problem?Maybe you can turn it off,
Another question I would like to ask is can the upstream server carry the request header to the downstream service?

**Comment by jmezach** [comment]
Headers coming into your API gateway should be forwarded to the downstream service by default yes. This should work out of the box and should not require any configuration. Have a look at the [docs](https://ocelot.readthedocs.io/en/latest/features/headerstransformation.html) if you need some kind of transformation.

**Comment by raman-m** [comment]
The question has been [answered](https://github.com/ThreeMammals/Ocelot/issues/1156#issuecomment-602166616)!
