### ISSUE TITLE
Mutiple SignalR hubs failed

### ISSUE THREAD

**Issue by HorjeaCosmin** [ThreeMammals/Ocelot#1163]
## Expected Behavior / New Feature
Using bellow config:
```json
    {
      "DownstreamPathTemplate": "/rootFolder/project1/hubs/{project1Hub}",
      "DownstreamScheme": "ws",
      "DownstreamHostAndPorts": [
        {
          "Host": "localhost",
          "Port": 80
        }
      ],
      "UpstreamPathTemplate": "/hubs/{project1Hub}",
      "UpstreamHttpMethod": [ "GET", "POST", "PUT", "DELETE", "OPTIONS" ]
    },

    {
      "DownstreamPathTemplate": "/rootFolder/project2/hubs/{project2Hub}",
      "DownstreamScheme": "ws",
      "DownstreamHostAndPorts": [
        {
          "Host": "localhost",
          "Port": 80
        }
      ],
      "UpstreamPathTemplate": "/hubs/{project2Hub}",
      "UpstreamHttpMethod": [ "GET", "POST", "PUT", "DELETE", "OPTIONS" ]
    }
```
I was expected to be able to connect on both hubs.

## Actual Behavior / Motivation for New Feature

I was able to connect only to project1Hub, but on the second hub I get 404 error.

## Specifications

  - Versions: Ocelot v.14.0.11 & net core 3.1 solution

**Comment by jlukawska** [comment]
Hello,

There seems to be a typo in the following line before "project2/":

"DownstreamPathTemplate": "/rootFolder/**l**project2/hubs/{project2Hub}"

**Comment by HorjeaCosmin** [comment]
Kidding right? 

Used names are demo only, in production everything is configured fine.

One more hint, it seams that if I do switch project1 with project2, now project2 is running and the other throw 404.

**Comment by HorjeaCosmin** [comment]
Any clue / workaround, anybody?

Regards,
Cosmin

**Comment by jlukawska** [comment]
Hello, 
Both your reRoutes are the same: they have the same `UpstreamPathTemplate` ("/hubs/{whatever}") and `UpstreamHttpMethod`, but maybe it is only one more simplification in your example?

I can imagine the situation where the routing would work as you wrote... If your example is ok and a request is to '/hubs/project2Hub' then the first reroute will work, so the downstream path will be look like '/rootFolder/project1/hubs/project2Hub' and maybe it is not what you want?

**Comment by HorjeaCosmin** [comment]
Hi,

My initial idea was to have all hubs together under the same upstreamPath (/hubs). One solution would  be if I could configure to match exactly upstreamPath to downstreamPath but I think this is not possible. If there is not other option I will change the upstreamPath for the second project.

**Comment by raman-m** [comment]
### Duplicated routes!

Must be one [Catch All](https://ocelot.readthedocs.io/en/latest/features/routing.html#catch-all):
```json
    {
      "DownstreamPathTemplate": "/rootFolder/project1/hubs/{hub}",
      "UpstreamPathTemplate": "/hubs/{hub}",
    },
```

OR
```json
    {
      "DownstreamPathTemplate": "/rootFolder/{project}/hubs/{hub}",
      "UpstreamPathTemplate": "/hubs/{project}/{hub}",
    },
```

Hope it helps!
