### ISSUE TITLE
Ocelot with JWT .NETCORE 3.0 - ERROR

### ISSUE THREAD

**Issue by FrankGasparotto** [ThreeMammals/Ocelot#1170]
Hi there, please i need a little help, i´ve followed the documentation and i´ve configured my JWT and app to run BUT, i´m getting this message: "Unable to start Ocelot, errors are: Authentication Options AuthenticationProviderKey:TestKey,AllowedScopes:[] is unsupported authentication provider" everytime i try to run the service.

I´m using: 
.net core 3.0;
AspNetCore.Authentication.JwtBearer (3.1);
Ocelot 14.1

My ocelot.json is configured as: 
"AuthenticationOptions": {
        "AuthenticationProviderKey": "TestKey",
        "AllowedScopes": []
      } 

Can anybody help me with this issue please ! Thanx !

**Comment by wast** [comment]
`.AddJwtBearer("TestKey", x =>`
must match 
`"AuthenticationProviderKey": "TestKey"`

**Comment by jawand** [comment]
@FrankGasparotto any solution you found?

**Comment by metalrose24** [comment]
I've run into this issue as well. 

Following the example in the Ocelot docs produces this error for me

**Comment by metalrose24** [comment]
I manged to solve this. For me, I had configuration in both Startup.cs and Program.cs. It wasn't using my Startup.cs for the Ocelot config. If your following the samples then the configuration for authentication needs to be under the .ConfigureServices part of the WebHostBuilder e.g. in Program.cs Main method:

            new WebHostBuilder()
                .UseKestrel()
                .UseContentRoot(Directory.GetCurrentDirectory())
                .ConfigureAppConfiguration((hostingContext, config) =>
                {
                    config
                        .SetBasePath(hostingContext.HostingEnvironment.ContentRootPath)
                        .AddJsonFile("appsettings.json", true, true)
                        .AddJsonFile($"appsettings.{hostingContext.HostingEnvironment.EnvironmentName}.json", true, true)
                        .AddJsonFile("ocelot.json", false, true)
                        .AddEnvironmentVariables();
                })
                .ConfigureServices(services =>
                {
                    void Options(IdentityServerAuthenticationOptions o)
                    {
                        o.Authority = authenticationServerBaseAddress;
                        o.ApiName = ServiceClientId;
                        o.SupportedTokens = SupportedTokens.Both;
                        o.ApiSecret = ServiceSecret;
                    }

                    services.AddAuthentication()
                        .AddIdentityServerAuthentication(authenticationProviderKey, Options);

                    services.AddOcelot();
                })
                .ConfigureLogging((hostingContext, logging) =>
                {
                    //add your logging TODO
                })
                .UseIISIntegration()
                .Configure(app =>
                {
                    app.UseOcelot().Wait();
                })
                .Build()
                .Run();

I found it useful to actually take a copy of the code so I could debug through it then it made more sense what it was doing and why it wasn't picking up my authentication config

Hope this helps someone !

**Comment by raman-m** [comment]
@FrankGasparotto 
### [The answer](https://github.com/ThreeMammals/Ocelot/issues/1170#issuecomment-607504877) by @wast 

The reason of getting `Authentication Options AuthenticationProviderKey:TestKey,AllowedScopes:[] is unsupported authentication provider` error is forgotten unregistered auth provider for the key/scheme.

During 22.x+ releases we have updated [Authentication](https://ocelot.readthedocs.io/en/latest/features/authentication.html) feature, so read the docs.
