### ISSUE TITLE
How to Validate a JWT token from the API?

### ISSUE THREAD

**Issue by pmjaleel** [ThreeMammals/Ocelot#1178]
We are creating an application where Ocelot Gateway is going to be used for the API Gateway. How will we validate a JWT token at the Gateway?

Regards
Parvez

**Comment by wast** [comment]
Same as in any other application.
In Startup - ConfigureServices

`            var key = Encoding.ASCII.GetBytes(Configuration.GetValue<string>("Token:Secret"));
            services.AddAuthentication(x =>
            {
                x.DefaultAuthenticateScheme = "Jwt";
                x.DefaultChallengeScheme = "Jwt";
            })
            .AddJwtBearer("ApiSecurity", x =>
            {
                x.SaveToken = true;
                x.TokenValidationParameters = new TokenValidationParameters
                {
                    ValidateIssuerSigningKey = true,
                    IssuerSigningKey = new SymmetricSecurityKey(key), //todo
                    ValidateIssuer = false,
                    ValidateAudience = false,
                    ValidateLifetime = true
                };
            });`

**Comment by pmjaleel** [comment]
> Same as in any other application.
> In Startup - ConfigureServices
> 
> ```cs
>            var key = Encoding.ASCII.GetBytes(Configuration.GetValue<string>("Token:Secret"));
>             services.AddAuthentication(x =>
>             {
>                 x.DefaultAuthenticateScheme = "Jwt";
>                 x.DefaultChallengeScheme = "Jwt";
>             })
>             .AddJwtBearer("ApiSecurity", x =>
>             {
>                 x.SaveToken = true;
>                 x.TokenValidationParameters = new TokenValidationParameters
>                 {
>                     ValidateIssuerSigningKey = true,
>                     IssuerSigningKey = new SymmetricSecurityKey(key), //todo
>                     ValidateIssuer = false,
>                     ValidateAudience = false,
>                     ValidateLifetime = true
>                 };
>             });
> ```
> 
> Also check [stackoverflow](https://stackoverflow.com/questions/51943722/how-to-validate-jwt-token-in-aspnet-core-web-api)

@wast
