### ISSUE TITLE
Missing documentation for Secured WebSocket downstream scheme (wss) with SignalR

### ISSUE THREAD

**Issue by sam9291** [ThreeMammals/Ocelot#1179]
## Expected Behavior / New Feature
When using SignalR with secure web sockets, we must use the `wss` downstream scheme to have a successful web socket connection.

## Actual Behavior / Motivation for New Feature
The documentation only mentions to use the `ws` scheme, it should contain instructions for `wss`

## Steps to Reproduce the Problem

https://ocelot.readthedocs.io/en/latest/features/websockets.html
 
## Specifications

  - Version: 14.1.0
  - Platform: Windows 10

**Comment by raman-m** [comment]
Watch for the new release 20.0.1, see #1755  
The Websockets page will not have `wss` scheme mentioning, but I guess, it will be pretty easy to update your current PR.
