### ISSUE TITLE
Aggregation routing configuration does not allow configuring URL parameter in a different spot

### ISSUE THREAD

**Issue by jr-araujo** [ThreeMammals/Ocelot#1181]
## Expected Behavior / New Feature

I've been using Ocelot for a while and I have pretty much appreciated for this package. However, I see that the configuration in the Aggregation section doesn't allow to do something like this as depicted in the image below:

![image](https://user-images.githubusercontent.com/11546614/78514473-72f41a80-77a9-11ea-8b9f-b8a70e035eac.png)

So, it would be very interesting to have the freedom to configure the Aggregation route as you need or depending on the API design in your company. Exactly as I showed in the image above, that is, having some parameters between the composition of the aggregation route.

## Actual Behavior / Motivation for New Feature

Today, to do so, it is only possible to have this sort of configuration:

![image](https://user-images.githubusercontent.com/11546614/78514611-265d0f00-77aa-11ea-80e4-300eb734cd1d.png)

If you take a look at the image below, it will be clear that the route parameter is only allowed to be placed at the end of the aggregation route.

## Steps to Reproduce the Problem

N/A

## Specifications

  - Version: 13.8.0
  - Platform: Windows 10
  - Subsystem: .NET Core 3.0

**Comment by jlukawska** [comment]
Hello,

Could you provide more details? How do you know that it's not allowed? Do you have any validation failures? Have you checked the application log?

**Comment by jr-araujo** [comment]
Hi @jlukawska 

for all your questions, there is one answer: take a look at in all scenarios before, try to reproduce and you'll see that what I tried to show doesn't work.

**Comment by jlukawska** [comment]
I've tried to reproduce the problem and it seems to work fine. That's why I'm asking for details what exactly does not work.

**Comment by jr-araujo** [comment]
@jlukawska 

I'm tried, Again, tmy project and... the result was this:

![image](https://user-images.githubusercontent.com/11546614/80321504-6ba6b680-8815-11ea-809c-07b598d41ef5.png)

![image](https://user-images.githubusercontent.com/11546614/80321509-811be080-8815-11ea-87d1-23a321ff6a52.png)

That is, this kind of route doesn't work when you are trying to configure it as an Aggregation route.

Only this way works:

![image](https://user-images.githubusercontent.com/11546614/80321565-e53ea480-8815-11ea-9df2-f0c7f55cbef6.png)

![image](https://user-images.githubusercontent.com/11546614/80321576-fbe4fb80-8815-11ea-8e4d-a3a8925288e8.png)

![image](https://user-images.githubusercontent.com/11546614/80321584-1b7c2400-8816-11ea-8897-a8aaeac90d41.png)

It was this that I'm talked about in the previous posts here.

@TomPallister can you help us to try to understand what is happing in this configuration or what am I suppose doing wrong?

**Comment by jlukawska** [comment]
Hi, 
I still can't reproduce this problem based on your code, but... I can guess. If your ocelot.json contains a ReRoute with `UpstreamPathTemplate="/customers/{id}"`, the result can be 404, because this reroute will be will be used first (id will be: "your_guid/orders"). 

If this is the reason, to make it work you can add a priority (value should be greater than 1) for the aggregate config e.g.
`"Priority": 10`

**Comment by raman-m** [comment]
Not an issue!
The author didn't attach full config JSON but arguing and wondering.
Possible reason of this issue is existence of other route with similar templates.
But the author didn't want to show the full JSON.
