### ISSUE TITLE
Claims to Claims Transformation - Important query

### ISSUE THREAD

**Issue by pmjaleel** [ThreeMammals/Ocelot#1184]
Hi There,

Without explicitly writing the below configuration: 

"AddClaimsToRequest": {
    "UserType": "Claims[sub] > value[0] > |",
    "UserId": "Claims[sub] > value[1] > |"
}

Is there a way that all the claims automatically gets transformed to the outgoing requests?
As there could be frequent change in the claims implementation, configuring each and every claims for every request could be a tedious task.

Please let us know?

**Comment by pmjaleel** [comment]
Anyone with this information. As I need to get this implemented.

**Comment by tmkhan** [comment]
@pmjaleel if u have resolved this issue then can u plz share me the solution. I need it urgently. Thanks in advance.

**Comment by santosh7100** [comment]
if u have resolved this issue then can u plz share me the solution. I need it urgently. Thanks in advance.

**Comment by raman-m** [comment]
Hello, @pmjaleel !
Do you still need our recommendations on possible implementations?
Sorry for the late response after 4 years.

**Comment by santosh7100** [comment]
Yes we do

**Comment by raman-m** [comment]
@santosh7100  You are **not** the author! Sorry!
