### ISSUE TITLE
Reading Multiple Configuration Files from Specific Folder - throwing: Unable to start Ocelot, errors are reRoute has duplicate 

### ISSUE THREAD

**Issue by JakubSlonka** [ThreeMammals/Ocelot#1186]
Hello,

I have encountered some strange behaviour while loading and merging multiple ocelot configuration files from specific folder.

## Background Description:
We have a big project that has tens of microservices on the backend. Since we want to ease the development for out frontend developers we have decided to implement Ocelot Gateway as a single point of contact between frontend and backend. 

In this scenario it makes sense to split the ReRoute configuration into multiple files to make the configuration more maintainable and readable.

Therefore I have implemented standard confguration of ocelot based on the documentation.

Program.cs
![image](https://user-images.githubusercontent.com/46593282/78789307-41e43780-79ad-11ea-9798-c83b56ae10d0.png)

StartUp.cs
![image](https://user-images.githubusercontent.com/46593282/78789172-0ea1a880-79ad-11ea-8579-43819d61ce64.png)

I have stored the configuration files in folder structure 
{rootfolder}/
         etc/
           config/
               ocelot.file1.json
               ocelot.file2.json
               ocelot.file3.json
               ocelot.file4.json
               .....

In this scenarion Ocelot throws: Unable to start Ocelot, errors are reRoute has duplicate .

My guess is that this issue occurs due to method .AddOcelot, which is being called twice.
For the first time it is used in Program.cs, second time it is being called in StartUp.cs

Unfortunately neither of them can be removed. When one of them is removed Ocelot stops working immeditely.

I've tried to place the configuration files into the root folder and I have replaced the call in Program.cs with:
![image](https://user-images.githubusercontent.com/46593282/78790330-ab187a80-79ae-11ea-8cfe-4dc5d4f69b26.png)

In this scenario the ocelot works as expected. It loads the files and generates ocelot.json.

The issue only occurs when you are trying to load them from specific folder.

## Expected Behavior
- Scan specified folder for files that correspond the Ocelot Configuration File Pattern (ocelot.([a-zA-Z0-9]*).json ).
- Generate ocelot.json file with all definitions.

## Actual Behavior
- Ocelot throws Error: Unable to start Ocelot, errors are reRoute has duplicate.

## Steps to Reproduce the Problem

  1. Create Web Api Project - .Net Core 3.1.2
  2. Implement Ocelot regarding the documentation
  3. Create Multiple Configuration files and place them in folder structure
  4. Run the application and make an api call.
  5. Application fails during the configuration load. 

## Specifications

  - Version: Ocelot 14.1.0
  - Platform: .Net Core 3.1.2

**Comment by Weidaicheng** [comment]
I believe Ocelot doesn't support multiple configurations yet.
Maybe a new feature required.

**Comment by JakubSlonka** [comment]
> I believe Ocelot doesn't support multiple configurations yet.
> Maybe a new feature required.

Hello, the multi config was requested quite a long time ago and was already Implemented.

The issue here is if config files are placed in specific folder.

 If you place them into the root folder it works fine.

Documentation:
![image](https://user-images.githubusercontent.com/46593282/78868758-c2ee0e00-7a43-11ea-84fe-5182638adce5.png)

**Comment by jlukawska** [comment]
I prepared a sample project that uses merging multiple config files from a specific folder and everything works fine.

There are two extension methods AddOcelot: IConfigurationBuilder.AddOcelot() and IServiceCollection.AddOcelot(), so it's not the same method call.

Have you checked the result ocelot.json file? Is the whole content of the files really duplicated?

**Comment by JakubSlonka** [comment]
Ok guys, so I have found out what was causing the strange behaviour.

It was the folder structure that we are using in Kubernetes for our configuration files.

Generally placing configuration files in the folder structure described below will cause described issue.

Folder structure:
etc/config/

**Comment by sachinvaid1604** [comment]
> Ok guys, so I have found out what was causing the strange behaviour.
> 
> It was the folder structure that we are using in Kubernetes for our configuration files.
> 
> Generally placing configuration files in the folder structure described below will cause described issue.
> 
> This could be written in the documentation as a note.
> 
> Folder structure: etc/config/

Hi, Can you please provide a working code that can read multiple route configurations for each microservice and can run both. In my case, I can only access the last added route configuration.

Here is my program.cs file

using Microsoft.AspNetCore;
using Microsoft.AspNetCore.Hosting;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Ocelot.DependencyInjection;
using Ocelot.Middleware;
using System.IO;

public class Program
{
    public static void Main(string[] args)
    {
        CreateWebHostBuilder(args)
            .Build()
            .Run();
    }

    static IWebHostEnvironment _hostingContextEnvironment = null;

    public static IWebHostBuilder CreateWebHostBuilder(string[] args) =>
        WebHost.CreateDefaultBuilder(args)
            .UseContentRoot(Directory.GetCurrentDirectory())
            .ConfigureAppConfiguration((hostingContext, config) =>
            {
                _hostingContextEnvironment = hostingContext.HostingEnvironment;

                config
                    .SetBasePath(hostingContext.HostingEnvironment.ContentRootPath)
                    .AddJsonFile("appsettings.json", true, true)
                    .AddJsonFile("ocelot.json", false, true)
                    .AddJsonFile("student.ocelot.Development.json", false, true)
                    .AddJsonFile("teacher.ocelot.Development.json", false, true)
                    .AddEnvironmentVariables();
            })
            .ConfigureServices(s =>
            {
                s.AddOcelot();
            })
            .Configure(app =>
            {
                app.UseOcelot().Wait();
            });
}

![image](https://github.com/ThreeMammals/Ocelot/assets/4758765/cf81ff81-3d4e-4df5-86a8-09643981f334)

**Comment by raman-m** [comment]
Hi @sachinvaid1604
What's the problem?
Why do you write into closed thread?
