### ISSUE TITLE
websocket from Jupyter notebook does not work

### ISSUE THREAD

**Issue by evertonrds** [ThreeMammals/Ocelot#1194]
## Expected Behavior / New Feature
use the ocelot as a gateway for jupyter notebook

## Actual Behavior / Motivation for New Feature
The Http is working fine, but when I start a notebook, the kernel does not connect and I can not use the notebook. 

### 1
Use the jupyter notebook without any gateway and it works fine
### 2 Configure the gateway
```json
    {
      "DownstreamPathTemplate": "/jupyternb/{url}",
      "DownstreamScheme": "ws",
      "DownstreamHostAndPorts": [
        {
          "Host": "localhost",
          "Port": yourport
        }
      ],
      "UpstreamPathTemplate": "/jupyternb/{url}",
      "UpstreamHttpMethod": [ "GET", "POST", "PUT", "PATCH", "DELETE", "OPTIONS" ]
    },
    {
      "DownstreamPathTemplate": "/jupyternb/{url}",
      "DownstreamScheme": "http",
      "DownstreamHostAndPorts": [
        {
          "Host": "localhost",
          "Port": yourport
        }
      ],
      "UpstreamPathTemplate": "/jupyternb/{url}",
      "UpstreamHttpMethod": [ "GET", "POST", "PUT", "PATCH", "DELETE", "OPTIONS" ]
    },
```
### 3
Try to use the jupyter notebook and it will open but it can not connect to the kernel.

## Specifications

  - Version:
  - Platform:
  - Subsystem:

**Comment by raman-m** [comment]
> `"Port": yourport`

Your port must be numeric value!
Please, write more fairy tales!
