### ISSUE TITLE
Limit current for a single ip,

### ISSUE THREAD

**Issue by tkggusraqk** [ThreeMammals/Ocelot#1202]
Limit the amount of one ip access over a period of time, is this solution https://github.com/ThreeMammals/Ocelot/issues/1050?

**Comment by tkggusraqk** [comment]
@binarymash

**Comment by raman-m** [comment]
@tkggusraqk
Yes, we will try to implement this in #1050. I've reopened #1050 just today.

Any your contribution is welcome!

**Comment by raman-m** [comment]
As a temp solution you could try to use :point_down:  
- [Future and ASP.NET Core Implementation](https://ocelot.readthedocs.io/en/latest/features/ratelimiting.html#future-and-asp-net-core-implementation)

**Comment by raman-m** [comment]
Duplicate of #1050
