### ISSUE TITLE
Adding basic logical on RouteClaimsRequirement

### ISSUE THREAD

**Issue by 16130586** [ThreeMammals/Ocelot#1205]
## Expected Behavior / New Feature
I just demo something likes bellow 

"RouteClaimsRequirement": {
       "UserRole": "role1 OR role2 OR role3"
}

## Actual Behavior / Motivation for New Feature
On this current version, I saw that your project only support for claim value validation is IN   user claims. I need some logical checking on claim values!

I actually navigated on the project's source code and adding RPN processing on ClaimsAuthoriser.Authorise method and new code perfectly work likes what I  wanted.
But I cannot figure how to adding my piece of codes to my own project without modifying Ocelot source code. I mean could you please guide me  how to create an  new implementation of IClaimsAuthoriser then use DI to inject into my project.

**Comment by 16130586** [comment]
Thanks to your team that the project used same DI container with host project. I have been working hardly for 2 days and now I get the answer.
* First:
- Adding mycustom IClaimsAuthoriser with RPN or anything like syntax parser
* Second:
- In startup.cs file, inside ConfigureServices method, you adding your new claimsAuthorizer by  services.TryAddSingleton<IClaimsAuthoriser , YourCusomClaimAuthorizer>() before your AddOcelot();
*Finally
- Make sure you do not override AuthorisationMiddleware
P/s: I don't know why my codes works but i can't debug on my CustomAuthorizer. Debug mode don't let me go into custom code's break points

**Comment by pateljeel** [comment]
Hey, can you share your ClaimAuthorizer implementation? I am looking for something very similar and have not been able to figure it out
