### ISSUE TITLE
Need a way to pre-check the request after the route-matched by myself in ocelot.json

### ISSUE THREAD

**Issue by yangbocheng** [ThreeMammals/Ocelot#1219]
## Want to check the request before ocelot turns to downstream
I want to check the requset-headers by myself after the ocelot matches the url, but before going to the down stream. 

-- It's there anyway to add a pre-check Class before upstream to downstream?
-- I can add middleware for some url check, but it's better to config it in ocelot.json so i don't need to re-analyse the url-route

Forexample: in ocelot.json
```csharp
"DownstreamPathTemplate": "/test/todo/{id}",
"DownstreamScheme": "http",
"DownstreamHostAndPorts": [
   {
       "Host": "localhost",
        "Port": 5001
  }
],
"BeforeUp2Down":"--myprecheckClass--"
"UpstreamPathTemplate": "/todos/{id}",
"UpstreamHttpMethod": [ "Get" ],
```
And in  [myprecheckClass] , i should couldreject the request just like in Middleware,
Some other similiar designs like 'beforeDown2Up' should be also useful

**Comment by raman-m** [comment]
Use [Delegating Handlers](https://ocelot.readthedocs.io/en/latest/features/delegatinghandlers.html)!

Route custom properties will be implemented by PR #1843
