### ISSUE TITLE
Is Custom Service Discovery or Dynamic Route Registration Supported?

### ISSUE THREAD

**Issue by schwede** [ThreeMammals/Ocelot#1225]
If you are not using Consul or Eureka and you have routes that are not static but still need to registered dynamically, is this possible with the current release?

**Comment by raman-m** [comment]
@leonluc-dev  You are assigned! 😸

**Comment by raman-m** [comment]
@schwede  Hi Swede!
I don't know why don't you reply, but I'm just answering on your 2nd question:
> Dynamic Route Registration Supported?

Yes and No! We need to understand who is performer of this dynamic routes registration.

If this is well-known service discovery provider with reflection to Ocelot Routes then it looks like the same functionality as it was requested in issue #340.  This is [Dynamic Routing](https://ocelot.readthedocs.io/en/latest/features/servicediscovery.html#dynamic-routing) paragraph for [Service Discovery](https://ocelot.readthedocs.io/en/latest/features/servicediscovery.html#service-discovery) feature.

If you meant that Ocelot is responsible for service registrations then it looks like the role of service provider is delegated to Ocelot core, and we have the case of completely custom solution for custom service discovery provider. This case is covered by current #1656 PR. It is not production ready solution, but it shows the direction of implementation of custom service discovery provider being hosted inside the Ocelot core. The business logic can be implemented inside the gateway core or as a developer you could integrate to those service discovery providers which are not mentioned in current release. And this solution will be a **custom service discovery** solution.

I believe the #1656 PR will close your feature request. 
And you are welcome to enhance new Service Discovery sample in future.

**Comment by raman-m** [comment]
The issue has been [accepted](#event-9484592699) due to open PR #1656 
- #1656
