### ISSUE TITLE
Dynamically set/add Configuration for rate limiting

### ISSUE THREAD

**Issue by neetra** [ThreeMammals/Ocelot#1228]
## Expected Behavior / New Feature
For every re-route, we need to add  
 "RateLimitOptions": {
        "ClientWhitelist": [],
        "EnableRateLimiting": true,
        "Period": "10s",
        "PeriodTimespan": 3,
        "Limit": 1
      }

Now, if I want to fetch this configuration from a database or any file at run time and assign it for specific routes

For eg"
Startup.cs
```
ConfigureServices()
{
services.AddOcelot().AddRateLimitingConfiguration( Datatable or file )
}

```

**Comment by raman-m** [comment]
@neetra Hi Netra!
Could you look at linked PR please?
This PR contains new Ocelot feature to load configuration from memory, from dynamic `FileConfiguration` object. You can load data from DB, from anywhere and construct the configuration on the fly.
Enjoy after upcoming release soon.
