### ISSUE TITLE
AddOcelot() excludes selected enviroment

### ISSUE THREAD

**Issue by Melchy** [ThreeMammals/Ocelot#1230]
## Expected Behavior / New Feature

`ConfigurationBuilderExtensions.AddOcelot(config,"Development");` should load ocelot.Development.json.

## Actual Behavior / Motivation for New Feature

I have ocelot.Development.json, ocelot.Testing.json. When I use  `ConfigurationBuilderExtensions.AddOcelot(config,"Development");` ocelot.Testing.json is loaded instead of ocelot.Development.json.

Looking at the sourcode there is 

```csharp
const string subConfigPattern = @"^ocelot\.(.*?)\.json$";

string excludeConfigName = env?.EnvironmentName != null ? $"ocelot.{env.EnvironmentName}.json" : string.Empty;

var reg = new Regex(subConfigPattern, RegexOptions.IgnoreCase | RegexOptions.Singleline);

var files = new DirectoryInfo(folder)
                .EnumerateFiles()
                .Where(fi => reg.IsMatch(fi.Name) && (fi.Name != excludeConfigName))
                .ToList();

```

If this is expected behavior what is the purpouse of specifiing Hosting enviroment?

## Steps to Reproduce the Problem

  1. Use `ConfigurationBuilderExtensions.AddOcelot(config,"Development");`
  2. ocelot.Development.json is not loaded

## Specifications

  - Version: 15.0.6
  - Platform: .net core
  - Subsystem:

**Comment by jlukawska** [comment]
Hello,
the explanation is in the docs here: https://ocelot.readthedocs.io/en/latest/features/configuration.html?highlight=addocelot#merging-configuration-files

**Comment by Melchy** [comment]
Thanks, I didn't noticed the last line.
