### ISSUE TITLE
Always getting a 404 Not found

### ISSUE THREAD

**Issue by emoji-m** [ThreeMammals/Ocelot#1231]
## Expected Behavior / New Feature
Call will be forwarded after positive authentication to the destination route

## Actual Behavior / Motivation for New Feature
Request is positive authenticated in self-made authentication middleware within HandleAuthetnicateAsync() but crashes with a 404 Not found

## Steps to Reproduce the Problem
  1. Send via Postman: https://localhost:44329/api/v1/gateway/wheels/8P9P-CQC8
  2. Always getting an 404 

## Specifications

  - Version: 15.0.6
  - Platform: .NET Core 3.1

## Program.cs
        public static IWebHostBuilder CreateHostBuilder(string[] args)
        {
            return WebHost.CreateDefaultBuilder(args)
                .UseContentRoot(System.IO.Directory.GetCurrentDirectory())
                .UseApplicationInsights()
                .ConfigureAppConfiguration((host, config) =>
                {
                    config.AddJsonFile(Path.Combine("Ocelot", "configuration.json"));
                })
                 .ConfigureServices(s =>
                 {
                     s.AddOcelot();
                 })
                .UseIISIntegration()
                .Configure(app =>
                {
                    app.UseOcelot().Wait();
                })
                .UseStartup<Startup>();
        }

## Startup.cs

**Add handmade authentication middleware**
            services.AddAuthentication(TwoStepAuthenticationDefaults.AuthenticationScheme)
                .AddScheme<TwoStepAuthenticationOptions, TwoStepAuthenticationHandler>(TwoStepAuthenticationDefaults.AuthenticationScheme, options => { });
...

## Ocelot/Configuration.json
{
  "ReRoutes": [
    {
      "DownstreamPathTemplate": "/carService/api/v{apiVersion}/wheels/{everything}",
      "DownstreamScheme": "https",
      "DownstreamHostAndPorts": [
        {
          "Host": "myfancyserver.aaa.com",
          "Port": 444
        }
      ],
      "UpstreamPathTemplate": "/api/v{apiVersion}/gateway/wheels/{everything}",
      "UpstreamHttpMethod": [ "Get", "Put", "Post" ]
    }
  ],
  "GlobalConfiguration": {
    "BaseUrl": "https://localhost:44329"
  }
}

**Comment by 51tharea** [comment]
Could you try  "ReRoutes" to "Routers"?
[https://ocelot.readthedocs.io/en/latest/features/configuration.html](url)

**Comment by emoji-m** [comment]
Thank`s for your reply. I played a bit arround with the provided example solution and encountered a Bad Gateway issue. Therefore I moved to another proxy approach (https://github.com/damianh/ProxyKit). At the end I get a Bad Gateway as well :-| So decided to implement a referse proxy by my own. Anyway, the ocelot project is pretty cool 👍
