### ISSUE TITLE
Extend AddOcelot to EnumerateFiles in subfdirectories

### ISSUE THREAD

**Issue by christoff85** [ThreeMammals/Ocelot#1235]
## Expected Behavior / New Feature
Search ocelot.json files in given directory and all subdirectories.

## Actual Behavior / Motivation for New Feature
Currently AddOcelot only enumerates files in top directory only.

 I would like to add even more structure to my ocelot files and keep them as small and maintainable as possible.

## Steps to Reproduce the Problem
Only one piece of code would need to be changed in:
**Ocelot.DependencyInjection.ConfigurationBuilderExtensions.AddOcelot(this IConfigurationBuilder builder, string folder, IWebHostEnvironment env)** 
starting at line **37**:

var files = new DirectoryInfo(folder)
                **.EnumerateFiles("*", SearchOption.AllDirectories)**
                .Where(fi => reg.IsMatch(fi.Name) && (fi.Name != excludeConfigName))
                .ToList();

## Specifications
  - Version: 14.0.9

**Comment by raman-m** [comment]
@christoff85 Hi Krzysztof!
Thanks for your interest in Ocelot!

Soon you will be able to do everything in Ocelot core services, add/remove services from DI.
We will have Custom MVC Builder feature soon: #1655 
Also we will have Ocelot config file extensions in linked #1569 where you will be able to load Ocelot configuration from memory being constructed it as you wish, read from anywhere, including reading file from everywhere. 

Also, you can hack current `AddOcelot` by specifying `string folder` param you want during Ocelot startup! So you can traverse the directory tree as you wish.

**Comment by raman-m** [comment]
@christoff85 
The base support of your idea is available now.
If you still need to enumerate subdirectories, please, open PR!
