### ISSUE TITLE
Are code based routes possible?

### ISSUE THREAD

**Issue by softwareguy74** [ThreeMammals/Ocelot#1236]
Rather than hard coding routes, we'd like to inspect the incoming host/path and through code determine the route.

**Comment by raman-m** [comment]
Sorry? Possibly you wanted [Service Discovery](https://ocelot.readthedocs.io/en/latest/features/servicediscovery.html) ?...
OR [Dynamic Routing](https://ocelot.readthedocs.io/en/latest/features/servicediscovery.html#dynamic-routing)
