### ISSUE TITLE
Is there anyway to ignore SSL validation?

### ISSUE THREAD

**Issue by v2codes** [ThreeMammals/Ocelot#1237]
In my case：
At the development environment, I use the dynamic routing with Consul，and all Services start up with HTTPS。
I got SSL connection error， like this：
![image](https://user-images.githubusercontent.com/32858631/82692863-0c608880-9c93-11ea-95fc-c165e7602808.png)

## Steps to Reproduce the Problem
ocelot.json config ：
![image](https://user-images.githubusercontent.com/32858631/82693048-5cd7e600-9c93-11ea-963c-40d7685565c3.png)

## Specifications

  - Version: 15.0.6

**Comment by ggleo08** [comment]
I tried resolve like this, and it worked. 
By the way, In multiple configuration file case , just need to configure "DangerousAcceptAnyServerCertificateValidator" to "true" for this problem. But it doesn't work for dynamic routing.
So I‘m not sure it's the best way to resolve it. 
I'm looking forward to your help, tks very much.

**Here is my way.**

**Startup file**

`
services.AddOcelot(Configuration).AddConsul().AddPolly().AddDelegatingHandler<IgnoreSSLValidateDelegatingHandler>(true);
`

**IgnoreSSLValidateDelegatingHandler**
`

    public class IgnoreSSLValidateDelegatingHandler : DelegatingHandler
    {
        private readonly X509CertificateCollection _certificates = new X509CertificateCollection();
        public IgnoreSSLValidateDelegatingHandler()
        {
        }
        protected override async Task<HttpResponseMessage> SendAsync(HttpRequestMessage request, System.Threading.CancellationToken cancellationToken)
        {
            var inner = InnerHandler;
            while (inner is DelegatingHandler)
            {
                inner = ((DelegatingHandler)inner).InnerHandler;
            }
            // inner is HttpClientHandler
            if (inner is HttpClientHandler httpClientHandler)
            {
                if (httpClientHandler.ServerCertificateCustomValidationCallback == null)
                {
                    httpClientHandler.ServerCertificateCustomValidationCallback = (message, cert, chain, errors) =>
                    {
                        return true;
                    };
                }
            }
            return await base.SendAsync(request, cancellationToken);
        }
    }

`

**Comment by raman-m** [comment]
@v2codes It is very strange that **DangerousAcceptAnyServerCertificateValidator** property did not help you.
Do you think the PR #1377 will solve the problem? I think soo...

Did you debug the code to figure out why dynamic routing switched off the **DangerousAcceptAnyServerCertificateValidator** property?
