### ISSUE TITLE
Ocelot support gRPC services?

### ISSUE THREAD

**Issue by AdwardNguyen** [ThreeMammals/Ocelot#1238]
I have a plan to change rest api to grpc but i can't find grpc configuration documentation from ocelot. 
.Net core 3.1 / Windows / gRPC

**Comment by trendfollowerpl** [comment]
https://docs.microsoft.com/en-us/dotnet/architecture/microservices/multi-container-microservice-net-applications/implement-api-gateways-with-ocelot

**Comment by raman-m** [comment]
https://github.com/search?q=repo%3AThreeMammals%2FOcelot+grpc&type=discussions

**Comment by raman-m** [comment]
### Discussion
- #1822
