### ISSUE TITLE
HTTP ERROR 404 This localhost page can’t be found

### ISSUE THREAD

**Issue by Flave1** [ThreeMammals/Ocelot#1241]
I Have Configured my API gateway to be accessed using "/cast", Still does not seem to work
 
This is my startup file
    
     public class Startup
    {
        public IConfiguration Configuration { get; }
        public Startup(IConfiguration configuration)
        {
            Configuration = configuration;
        }

        public void ConfigureServices(IServiceCollection services)
        {
            services.AddOcelot(Configuration);
        }

        public async void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }
            await app.UseOcelot(); 

            app.Run(async (context) =>
            {
                await context.Response.WriteAsync("Hello World!");
            });
        }
    }

This is my program.cs file
   
    public static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)
                .ConfigureWebHostDefaults(webBuilder =>
                {
                    webBuilder.UseStartup<Startup>();
                }).ConfigureAppConfiguration((host, config) =>
                {
                    config.AddJsonFile("ocelot.json");
                });

And this is my ocelot configuration file
   
   {
  "ReRoutes": [
    {
      "DownstreamPathTemplate": "/api/cast",
      "DownstreamScheme": "https",
      "DownStreamHostAndPorts": [
        {
          "Host": "localhost",
          "Port": "44340"
        }
      ],
      "UpstreamPathTemplate": "/cast"
]
}
![Capture 1](https://user-images.githubusercontent.com/46898561/82749848-f2fb3180-9da3-11ea-8670-4e9b774f1676.PNG)

Please What next should I do to make this work

API GATEWAY Using Ocelot in .Net core 3.1

  - Version: ocelot 16.0.0
  - Platform: Visual Studio 2019

**Comment by TomPallister** [comment]
https://ocelot.readthedocs.io/en/latest/features/configuration.html Reroutes is now called routes

**Comment by Flave1** [comment]
Thanks for this, I actually tried it sometime this year using ReRoute Object and it worked fine.
I never new changes were made
