### ISSUE TITLE
About OcelotManager

### ISSUE THREAD

**Issue by water1st** [ThreeMammals/Ocelot#1245]
## New Feature

If the API gateway needs to be serve multiple teams, each team can only manage its own services, so we need a management UI. Each team can manage its own services in the management UI, and there is no need to modify the API gateway JSON configuration file.I want to develop a management UI, it can automatically notify all API gateway nodes to update the configuration, but when I look at the ocelot source code, I find that config is loaded when it is initialized. Is there any other way for me to change the configuration dynamically?

**Comment by kjellegafvelin** [comment]
You could either use the Consul integration https://ocelot.readthedocs.io/en/latest/features/configuration.html#store-configuration-in-consul or the Administration API to change the configuration.

**Comment by raman-m** [comment]
[Answered](https://github.com/ThreeMammals/Ocelot/issues/1245#issuecomment-634666126)!
