### ISSUE TITLE
When using Aggregates, "Key" is automatically set on reRoute without key. 

### ISSUE THREAD

**Issue by artyomabrahamyan** [ThreeMammals/Ocelot#1246]
## Expected Behavior
I have a config json, with aggregate section and some reRoutes with keys to use in aggregates. 
Whenever I do not add a key on reRoute in .json file reRoute should have a **null** key. 

## Actual Behavior
Some of reRoutes get an existing key from another reRoute gets added to another reRoute with the missing key whenever I read json file, and later **FileConfigurationFluentValidator** AllReRoutesForAggregateExist method return false because the count of keys in aggregates does not match the one in reRoutes

## Steps to Reproduce the Problem

  1. Create a .json config with the reRoutes. 
  2. Add key(s) on some of the reReutes below
  3. Add Aggregates section that uses the key(s) right after 
  4. FileAggregateReRoute gets messed up and assigned keys to the ones without keys.

## Specifications

  - Version: Ocelot 14.0.3
  - Platform: .NET Core 3.1
  - Subsystem: Windows 10 home

**Comment by neetra** [comment]
@artyomabrahamyan can you please share your configuration file?
