### ISSUE TITLE
have some diffculty while following in Ocelot tutorial.

### ISSUE THREAD

**Issue by billyhiuwali** [ThreeMammals/Ocelot#1248]
## Expected Behavior / New Feature

i am following  Ocelot Offical document to build up a API gateway under .Net Core 3.1.
https://ocelot.readthedocs.io/en/latest/introduction/gettingstarted.html

i expected that i browse "http://localhost:65307/todos/1" in Browser
then, i would get the result from http://jsonplaceholder.typicode.com/todos/1

My Project repo is here : https://github.com/billyhiuwali/ocelot-api-2/tree/master/ocelot-api-2

## Actual Behavior / Motivation for New Feature

when i browse "http://localhost:65307/todos/1" in Browser
the browser is Looping .  

i have been trying on this tuturial  for a whole day. but still dont know what else i have missed. 
Could you please, help me .

## Steps to Reproduce the Problem

  1.  install Ocelet by running "Install-Package Ocelot"
  2.  create a ocelot.json
  3.  override program.cs
  4.  update the BaseUrl in ocelot.json

**ocelt.json**
```
{
  "Routes": [
    {
      "DownstreamPathTemplate": "/todos/{id}",
      "DownstreamScheme": "https",
      "DownstreamHostAndPorts": [
        {
          "Host": "jsonplaceholder.typicode.com",
          "Port": 443
        }
      ],
      "UpstreamPathTemplate": "/todos/{id}",
      "UpstreamHttpMethod": [ "Get" ]
    }
  ],
  "GlobalConfiguration": {
    "BaseUrl": "http://localhost:65307"
  }
}
```
**Program.cs**
```
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Logging;
using Ocelot.DependencyInjection;
using Ocelot.Middleware;

namespace ocelot_api_2
{
    public class Program
    {
        public static void Main(string[] args)
        {
            new WebHostBuilder()
            .UseKestrel()
            .UseContentRoot(Directory.GetCurrentDirectory())
            .ConfigureAppConfiguration((hostingContext, config) =>
            {
                config
                    .SetBasePath(hostingContext.HostingEnvironment.ContentRootPath)
                    .AddJsonFile("appsettings.json", true, true)
                    .AddJsonFile($"appsettings.{hostingContext.HostingEnvironment.EnvironmentName}.json", true, true)
                    .AddJsonFile("ocelot.json")
                    .AddEnvironmentVariables();
            })
            .ConfigureServices(s => {
                s.AddOcelot();
            })
            .ConfigureLogging((hostingContext, logging) =>
            {
                   //add your logging
               })
            .UseIISIntegration()
            .Configure(app =>
            {
                app.UseOcelot().Wait();
            })
            .Build()
            .Run();
        }

    }
}

```

## Specifications

  - Version: Dotnet core 3.1 ,Ocelot version 15.0.0
  - Platform: 
  - Subsystem:

**Comment by jlukawska** [comment]
Hello, 
Please try to change "Routes" to "ReRoutes" in ocelot.json or upgrade Ocelot to the newest version. It seems that Ocelot has changed this key word somewhere between 15.0 and 16.0.1 versions...

And another thing: are you sure that your project is starting using the right port? I suggest to add logging to the project (e.g. serilog) to see what happens.

**Comment by billyhiuwali** [comment]
@jlukawska  Thank you so much . i have updated it. now it works.

**Comment by raman-m** [comment]
Sounds like success story!
