### ISSUE TITLE
RequestIdKey Header Fallback value not set correctly to TraceIdentifier in downstream

### ISSUE THREAD

**Issue by zisiszaverdas** [ThreeMammals/Ocelot#1253]
## Expected Behavior / New Feature
If RequestIdKey header was not found in the request, the default fallback was to use httpContext.TraceIdentifier and add it to downstream request headers.

## Actual Behavior / Motivation for New Feature
After upgrading to 15.0.7 i get something as "0HM07JSN2G9K0" which is not the current httpContext.TraceIdentifier. 

After attempting to debugging i think the change from https://github.com/ThreeMammals/Ocelot/blob/99a15d866828270c810d4c62930c0cec67b9f977/src/Ocelot/RequestId/Middleware/ReRouteRequestIdMiddleware.cs#L32
to
https://github.com/ThreeMammals/Ocelot/blob/fe3e8bd23a666daa31ed2e8b00dce2c4630c23a7/src/Ocelot/RequestId/Middleware/ReRouteRequestIdMiddleware.cs#L33 
cause https://github.com/ThreeMammals/Ocelot/blob/fe3e8bd23a666daa31ed2e8b00dce2c4630c23a7/src/Ocelot/RequestId/Middleware/ReRouteRequestIdMiddleware.cs#L39
to return true even if the header does not exist.

## Steps to Reproduce the Problem

  1. Send request to ocelot without "RequestIdKey" header set
  2. Downstream has header set to "RequestIdKey" but the value is not the httpContext.TraceIdentifier

## Specifications

  - Version: 15.0.7
  - Platform: .NET Core SDK (3.1.202)

**Comment by zisiszaverdas** [comment]
I can confirm with 23.1+ working as expected!

**Comment by raman-m** [comment]
But after my little research of the C# of the  class yesterday I see that the code mostly the same for both versions 23.1 (current **main** branch) and 99a15d866828270c810d4c62930c0cec67b9f977   [13.5.2](https://github.com/ThreeMammals/Ocelot/releases/tag/13.5.2)

So, probably your statements are still true... Need to double check it...

**Comment by zisiszaverdas** [comment]
Ok let me add some more info, my project is .net6.0 and i am using Ocelot.Cache.CacheManager and Ocelot.Provider.Polly.
I remember that i could replicate the issue with only a new project and just ocelot 15.0.7 version.

My workaround was using a Middleware to set the header before ocelot would parse the request.
```
 public Task InvokeAsync(HttpContext context)
        {
            var identifier = context.Request.HttpContext.TraceIdentifier;
            if (context.Request.Headers.TryGetValue("X-Correlation-ID", out var correlationId))
            {
                identifier = correlationId.First();
            }
            else
            {
                context.Request.Headers.TryAdd("X-Correlation-ID", identifier);
            }
            using (LogContext.PushProperty("CorrelationId", identifier)) { return _next(context); }            
        }
```
and my config
```
"GlobalConfiguration": {
    "RequestIdKey": "X-Correlation-ID"
}
```

Also on my workaround i found a link on the following issue #327

**Comment by raman-m** [comment]
OK If you would like to improve the [RequestIdMiddleware](https://github.com/ThreeMammals/Ocelot/blob/develop/src/Ocelot/RequestId/Middleware/RequestIdMiddleware.cs) we will be waiting for your PRs with your proposals.
