### ISSUE TITLE
[Question] Proper way to add custom authorization logic?

### ISSUE THREAD

**Issue by ig-sinicyn** [ThreeMammals/Ocelot#1254]
## Expected Behavior / New Feature
We want to add a custom logic to be performed exactly after current authorization step (IClaimsAuthoriser/IScopesAuthoriser check) but before rest of the ocelot pipeline.

As far as I can see it can be achieved in multiple ways:
1. Replace/wrap default `AuthorisationMiddleware`. Bad idea as it will break if the AuthorisationMiddleware will become internal or change it's constructor signature
2. Use OcelotPipelineConfiguration.PreQueryStringBuilderMiddleware. Looks like abuse but should work
3. Post a PR that adds OcelotPipelineConfiguration.PostAuthorisationMiddleware:)

Could you suggest a proper way to go?

## Specifications

  - Version: ocelot v15.0.6
  - Platform: .net core 3.1

**Comment by artyomabrahamyan** [comment]
You may use Pre-Authorization middleware.

**Comment by ig-sinicyn** [comment]
@artyomabrahamyan, we need to have access to the authorization results (current principal, parsed token etc). These are filled by AuthorisationMiddleware. so our code has be registered after it.
