### ISSUE TITLE
Upstream match problem in a simple scenario

### ISSUE THREAD

**Issue by AminEsmaeily** [ThreeMammals/Ocelot#1257]
## Main Scenario
I have developed a WebAPI application that is accessible via this **http://localhost:5930** link and am able to call its actions using the _Postman_ and a console DotNet core application.
I created a Web application too to host the Ocelot and API Gateway. This application runs on the following URLs:
**http://localhost:2700/** and **https://localhost:44381/**
The Ocelot configuration is as follows:
``` JSON
{
  "ReRoutes": [
    {
      "DownstreamPathTemplate": "/FileHelper/{everything}",
      "DownstreamScheme": "http",
      "DownstreamHostAndPorts": [
        {
          "Host": "localhost",
          "Port": 5930
        }
      ],
      "UpstreamPathTemplate": "/FileHelper/{everything}",
      "UpstreamHttpMethod": [ "Get", "Post" ],
      "QoSOptions": {
        "TimeoutValue": 360000
      }
    }
  ],
  "HttpHandlerOptions": {
    "UseTracing": true
  },
  "GlobalConfiguration": {
    "AdministrationPath": "/administration",
    "BaseUrl": "https://localhost:44381"
  }
}
```

I changed my _Program_ class to read the Ocelot configuration file like this:
``` c#
public static IHostBuilder CreateHostBuilder(string[] args)
        {
            var builder = Host.CreateDefaultBuilder(args)
                .ConfigureWebHostDefaults(webBuilder =>
                {
                    webBuilder.UseStartup<Startup>();
                });

            builder.ConfigureServices(s => s.AddSingleton(builder))
                .ConfigureAppConfiguration(f =>
                {
                    f.AddJsonFile("configuration.json", optional: false, reloadOnChange: true);
                });

            return builder;
        }
```
And added `services.AddOcelot();` DI in _ConfigureServices_ method and `app.UseOcelot().Wait();` Middleware in _Configure_ method of the _Startup_ class.

## Behavior
Whenever I call the **SaveBillingFile** action (https://localhost:44381/FileHelper/SaveBillingFile) with _post_ method, I get 404 error with two warnings from the Ocelot in console:
```
warn: Ocelot.DownstreamRouteFinder.Middleware.DownstreamRouteFinderMiddleware[0]
      requestId: xxxx, previousRequestId: no previous request id, message: DownstreamRouteFinderMiddleware setting pipeline errors. IDownstreamRouteFinder returned Error Code: UnableToFindDownstreamRouteError Message: Failed to match Route configuration for upstream path: /FileHelper/SaveBillingFile, verb: POST.
warn: Ocelot.Responder.Middleware.ResponderMiddleware[0]
      requestId: xxxx, previousRequestId: no previous request id, message: Error Code: UnableToFindDownstreamRouteError Message: Failed to match Route configuration for upstream path: /FileHelper/SaveBillingFile, verb: POST. errors found in ResponderMiddleware. Setting error response for request path:/FileHelper/SaveBillingFile, request method: POST
```

I should notice that I can call this method directly from the main API Service without any problem.
To be able to trace the requests and actions, I used the [Butterfly](https://github.com/ThreeMammals/Ocelot.Tracing.Butterfly) library, but it didn't help me too.
It seems that the Ocelot middleware doesn't read the configuration.

## Specifications

  - Version: 16.0.1
  - Platform: Windows

**Comment by amweiss** [comment]
As of version 16.0.0 `ReRoutes` was renamed to `Routes`. Try updating that and see if it works.

**Comment by AminEsmaeily** [comment]
Yes, It worked. Thank you.
