### ISSUE TITLE
Call api error(401)  with  axios

### ISSUE THREAD

**Issue by vankhanhpr** [ThreeMammals/Ocelot#1260]
I have some problem  when I call api with axios (client). It is success if I using postman to get,
I add Cor to my ocelot.json file below:
![image](https://user-images.githubusercontent.com/22538732/83946675-86207680-a83c-11ea-90b7-33914f607aaa.png)
![image](https://user-images.githubusercontent.com/22538732/83946753-ec0cfe00-a83c-11ea-8475-0612dd4807f2.png)

My error below:
![image](https://user-images.githubusercontent.com/22538732/83946695-a7816280-a83c-11ea-8edd-2fcd943886b2.png)
![image](https://user-images.githubusercontent.com/22538732/83946825-63db2880-a83d-11ea-9345-050b04e5d414.png)
![image](https://user-images.githubusercontent.com/22538732/83946837-7b1a1600-a83d-11ea-91f6-ecc1655e5d04.png)

Ocelot's file  like: 
`{
      "DownstreamPathTemplate": "/api/user/{catchAll}",
      "DownstreamScheme": "http",
      "DownstreamHostAndPorts": [
        {
          "Host": "localhost",
          "Port": 3004
        }
      ],
      "UpstreamPathTemplate": "/api/user/{catchAll}",
      "UpstreamHttpMethod": [ "Options", "Get", "Post", "Put", "Delete" ],
      "AuthenticationOptions": {
        "AuthenticationProviderKey": "TestKey",
        "AllowedScopes": []
      },
      "RateLimitOptions": {
        "ClientWhitelist": [],
        "EnableRateLimiting": true,
        "Period": "1s",
        "PeriodTimespan": 10,
        "Limit": 10
      }
    }`
I user postman worked:
![image](https://user-images.githubusercontent.com/22538732/83946785-1eb6f680-a83d-11ea-981f-7ccb93e140b1.png)

How can I help you and thanks so much!.

**Comment by trendfollowerpl** [comment]
Hello. 
If it works from Postman then it has 401 error is not related with Ocelot configuration. 
Please validate Axios generated request or its configuration.

**Comment by raman-m** [comment]
Could you reproduce it for the latest versions 23.1+ please? And report if required!

What I see is misconfiguration issue.
