### ISSUE TITLE
Error when downloading a large file (>2Gb) 

### ISSUE THREAD

**Issue by evgslyusar** [ThreeMammals/Ocelot#1262]
## Expected Behavior
Download a large file (> 2 GB)

## Actual Behavior 
An error occurs: Cannot write more bytes to the buffer than the configured maximum buffer size: 2147483647

## Steps to Reproduce the Problem
1. The HTTP service returns a file larger than 2 GB.

## Notes
When I download a large file (> 2 GB), an error occurs: Cannot write more bytes to the buffer than the configured maximum buffer size: 2147483647. If to use the _HttpCompletionOption.ResponseHeadersRead_ parameters when calling the _HttpClient.SendAsync_ method, then an error does not occur. But I did not find a way how this can be used in the current version of Ocelot. 

## Specifications
  - Version: 13.5.2
  - Platform: Windows

**Comment by alekshura** [comment]
I've resolved it implementing own `IHttpRequester` (only for one endpoint that returns big files - "contents")

`
public class HttpRequester : IHttpRequester
{
    private readonly IHttpClientCache _cacheHandlers;
    private readonly IOcelotLogger _logger;
    private readonly IDelegatingHandlerHandlerFactory _factory;
    private readonly IExceptionToErrorMapper _mapper;
    private readonly IHttpClientFactory _httpClientFactory;

    public HttpRequester(IOcelotLoggerFactory loggerFactory,
        IHttpClientCache cacheHandlers,
        IDelegatingHandlerHandlerFactory factory,
        IExceptionToErrorMapper mapper, IHttpClientFactory httpClientFactory)
    {
        _logger = loggerFactory.CreateLogger<HttpClientHttpRequester>();
        _cacheHandlers = cacheHandlers;
        _factory = factory;
        _mapper = mapper;
        _httpClientFactory = httpClientFactory;
    }

    public async Task<Response<HttpResponseMessage>> GetResponse(HttpContext httpContext)
    {
        if (httpContext.Request.Path.ToString().Contains("contents"))
        {
            var client = _httpClientFactory.CreateClient();
            var request = httpContext.Items.DownstreamRequest();
            var response = await client.SendAsync(request.ToHttpRequestMessage(), HttpCompletionOption.ResponseHeadersRead);
            return new OkResponse<HttpResponseMessage>(response);
        }

        var builder = new HttpClientBuilder(_factory, _cacheHandlers, _logger);
        var downstreamRoute = httpContext.Items.DownstreamRoute();
        var downstreamRequest = httpContext.Items.DownstreamRequest();
        var httpClient = builder.Create(downstreamRoute);

        try
        {
            var response = await httpClient.SendAsync(downstreamRequest.ToHttpRequestMessage(), httpContext.RequestAborted);
            return new OkResponse<HttpResponseMessage>(response);
        }
        catch (Exception exception)
        {
            var error = _mapper.Map(exception);
            return new ErrorResponse<HttpResponseMessage>(error);
        }
        finally
        {
            builder.Save();
        }
    }
}
`

and adding to DI container before Ocelot:

`
builder.Services.AddHttpClient();
builder.Services.TryAddSingleton<IHttpRequester, HttpRequester>();
builder.Services.AddOcelot(configuration);
`

**Comment by ggnaegi** [comment]
@raman-m ```var response = await client.SendAsync(request.ToHttpRequestMessage(), HttpCompletionOption.ResponseHeadersRead);``` for the downloads https://learn.microsoft.com/en-us/dotnet/api/system.net.http.httpcompletionoption?view=net-8.0

**Comment by raman-m** [comment]
> @ggnaegi commented [on Dec 12](https://github.com/ThreeMammals/Ocelot/issues/1262#issuecomment-1851606667)

Got it! We will link this issue to the next your PR(s) for Dec'23 release...

**Comment by ggnaegi** [comment]
@raman-m this point is addressed in https://github.com/ThreeMammals/Ocelot/pull/1824

**Comment by raman-m** [comment]
> @alekshura commented [on Apr 6, 2023](https://github.com/ThreeMammals/Ocelot/issues/1262#issuecomment-1499323324)
```csharp
if (httpContext.Request.Path.ToString().Contains("contents"))
```
You are cool C# hacker definitely! 😉 🤣

**Comment by raman-m** [comment]
@evgslyusar commented [on Jun 8, 2020](https://github.com/ThreeMammals/Ocelot/issues/1262#issue-634545700):
>When I download a large file (> 2 GB), an error occurs: Cannot write more bytes to the buffer than the configured maximum buffer size: 2147483647. **If to use the _HttpCompletionOption.ResponseHeadersRead_ parameters when calling the _HttpClient.SendAsync_ method, then an error does not occur.** But I did not find a way how this can be used in the current version of Ocelot. 

We removed `HttpCompletionOption.ResponseHeadersRead` life hack in #1853 because we've implemented completely new Http Request processing design by `StreamHttpContent` vs a new `RequestMapper` which solve the problem of streaming including large files. Please, see #1724 !

----
And please, re-fork [Ocelot repo](https://github.com/evgslyusar/Ocelot): it is [outdated](https://github.com/evgslyusar/Ocelot/compare/master...ThreeMammals%3AOcelot%3Adevelop) now having `master` as a default branch.
So, I've created [PR 1](https://github.com/evgslyusar/Ocelot/pull/1) 😉

**Comment by raman-m** [comment]
- Fixed by https://github.com/ThreeMammals/Ocelot/pull/1724
