### ISSUE TITLE
How to replace host before final middleware call?

### ISSUE THREAD

**Issue by joe127123** [ThreeMammals/Ocelot#1266]
Introducing a new gateway that will reference an existing implementation of Ocelot, this existing implementation of ocelot has a custom middleware call in OcelotPipelineExtensions.cs that edits the host based on specific rules as here:

`            //custom code - route to specific host
            builder.UseDownstreamHostFinderMiddleware();

            // Not sure if this is the best place for this but we use the downstream url
            // as the basis for our cache key.
            builder.UseOutputCacheMiddleware();

            //We fire off the request and set the response on the scoped data repo
            builder.UseHttpRequesterMiddleware();

            return builder.Build();`

My issue is I want to call another middleware after this custom one without actually editing the Ocelot project (used by another team and trying not to make any edits that result in additional testing) in this case OcelotPipelineExtensions.cs in particular. I am trying to achieve that I can put some logic in my gateway only that will call an additional middle ware before the final call to  builder.UseHttpRequesterMiddleware();. I have tried the following using Middleware Injection and Overrides:

`            var configuration = new OcelotPipelineConfiguration
            {
                     
                PreQueryStringBuilderMiddleware = async (ctx, next) =>
                {
                    ctx.DownstreamRequest.Host = "MyOverRiddenHost";
                    await next.Invoke();
                }
            };`

But my issue with all the overrides I have tried is that they are all called before the custom middle ware that sets the host to something else. Is there any way from the gateway level without editing Ocelot project to insert a custom middle ware/override and also define the order (run just before last middle ware in this case). Thanks in advance and thanks also for Ocelot, its great.

**Comment by MirzaMerdovic** [comment]
Have you tried going about your problem using [Delegating Handlers](https://ocelot.readthedocs.io/en/latest/features/delegatinghandlers.html), we use that approach at work when we want to change the request's host value before the request gets send to the downstream service?

**Comment by joe127123** [comment]
This is great, thank you @MirzaMerdovic. I didn't realize this functionality existed. I take it you use it something like this also: 
                                      `var newUri = new UriBuilder(request.RequestUri);
                                       newUri.Host = "newhost";
                                        request.RequestUri = newUri.Uri;
                                        return await base.SendAsync(request, cancellationToken);`
