### ISSUE TITLE
Manipulate headers to downstream hosts

### ISSUE THREAD

**Issue by jeroenvheel** [ThreeMammals/Ocelot#1267]
Hi is was playing with Ocelot and was wondering if it was possible to add information in the headers for the downstream hosts

I'm trying to add the subdomain to the headers so my back end logic can switch things based on a tenant domain.

I found this in the closed issues https://github.com/ThreeMammals/Ocelot/issues/1011 

            var configuration = new OcelotPipelineConfiguration()
            {
                PreQueryStringBuilderMiddleware = async (context, next) =>
                {
                    var host = $"{context.HttpContext.Request.Host.Value}";
                    context.DownstreamRequest.Headers.Add("OriginalHost", host);
                    await next.Invoke();
                }
            };

but the solution gives a error on the **HttpContext** and the **DownstreamRequest**
when i try to fix the code i can't find the **DownstreamRequest**

Ocelot version: 16.0.1

**Comment by jeroenvheel** [comment]
I reverted back to 15.0.6 and found out the above code is working.
Sinds version 15.0.7 the solution is broken.

**Comment by rh101** [comment]
@jeroenvheel This may be an alternative solution for you:

```
public class HostInjectorDelegatingHandler : DelegatingHandler
{
    private readonly IHttpContextAccessor _httpContextAccessor;

    public SessionIdInjectorDelegatingHandler(IHttpContextAccessor httpContextAccessor)
    {
        _httpContextAccessor = httpContextAccessor;
    }

    protected override Task<HttpResponseMessage> SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
    {
        var host = $"{_httpContextAccessor.HttpContext.Request.Host.Value}";
        request.Headers.Add("OriginalHost",  host);
        return base.SendAsync(request, cancellationToken);
    }
}
```

In Startup.cs, add the handler like this:
```
            services.AddHttpContextAccessor(); // This is required to enable access to the HttpContext

            services.AddOcelot()
                .AddDelegatingHandler<HostInjectorDelegatingHandler>();
```

**Comment by jeroenvheel** [comment]
@rh101 Thanks ! this is working perfect.
