### ISSUE TITLE
[Question] : Is there simple content transform?

### ISSUE THREAD

**Issue by jstafford5380** [ThreeMammals/Ocelot#1270]
Is there a way to declare a transform in the configuration file? For example, I would implement some interface like `IResponseTransform` and then specify it in the route similar to how you specify an aggregator. This would allow me to intercept the response of a single downstream route and change it. I could probably do this with a delegating handler, but I was wondering if there was a more "first class" way to do so.

**Comment by raman-m** [comment]
Not supported now! And seems it will not be.

You need to implement `IDefinedAggregator`
Or, develop [delegating handler](https://ocelot.readthedocs.io/en/latest/features/delegatinghandlers.html) which will plat the role of this magic **"first class"** 😉
