### ISSUE TITLE
Configuration is restoring after restart

### ISSUE THREAD

**Issue by manishtiwari25** [ThreeMammals/Ocelot#1276]
## Expected Behavior / New Feature
As per #463 if we change anything from admin API it should update the config file(this part is working fine), but when I restart my service it is overwriting the whole configuration file.

## Actual Behavior / Motivation for New Feature
while using admin API it should not restore the configuration file.

## Steps to Reproduce the Problem
project files are available on [Github](https://github.com/manishtiwari25/ocelot-test).

## Specifications

  - Version: 16.0.1
  - Platform: .net core 3.1
  - Subsystem: IIS express on windows 10

**Comment by gebiWangshushu** [comment]
same issue.

**Comment by raman-m** [comment]
Upload your config file as config part file:
- ocelot.update1.json

After uploading it will be merged to 
- ocelot.json

That's how to prevent primary file overwriting.

Makes sense?
