### ISSUE TITLE
Requests on ie11 are not successfully forwarded after HTTP 307 (Temporary Redirection)(v16.0.1)

### ISSUE THREAD

**Issue by luccasmf** [ThreeMammals/Ocelot#1280]
For every browser but ie11 the requests are working but, with ie11 I get an HTTP 401 response

I'm using the Ocelot v16.0.1.

![image](https://user-images.githubusercontent.com/5990448/86402312-00002000-bc82-11ea-9618-27ef0c5c012a.png)

The headers on ie11 after the Redirection are:

![image](https://user-images.githubusercontent.com/5990448/86402527-5c633f80-bc82-11ea-94f8-55c4d5490180.png)

The header on other browsers after the Redirection are:

![image](https://user-images.githubusercontent.com/5990448/86402741-b6fc9b80-bc82-11ea-910f-ae95a64a6f71.png)

The Ocelot route are as the following (:

```
 "Routes": [
    {
      "DownstreamHostAndPorts": [
        {
          "Host": "brf-api-global-auth-dev.azurewebsites.net",
          "Port": 80
        }
      ],
      "DownstreamPathTemplate": "/{everything}",
      "DownstreamScheme": "http",
      "SwaggerKey": "auth",
      "UpstreamHttpMethod": [ "POST", "PUT", "GET", "OPTIONS", "DELETE" ],
      "UpstreamPathTemplate": "/auth/{everything}"
    },
//other endpoints suppresed for brevity
]
```
I don't know how to solve it, I really didn't found any answer anywhere.

**Comment by raman-m** [comment]
You possible fix will be based on
- [Follow Redirects aka HttpHandlerOptions](https://ocelot.readthedocs.io/en/latest/features/configuration.html#follow-redirects-aka-httphandleroptions)

And use `AllowAutoRedirect` option!
