### ISSUE TITLE
The swagger not working when hosting gateway in a virtual directory on IIS

### ISSUE THREAD

**Issue by jigneshnarain** [ThreeMammals/Ocelot#1281]
The swagger endpoint does not update to the virtual hosted gateway. The endpoint remain "/swagger/docs". When clicking on the it open a link to the service swagger without the virtual host name.

**Expected** /gateway/swagger/docs/v1/servicename
**Actual** /swagger/docs/v1/servicename

However, when I manually navigate to the path /gateway/swagger/docs/v1/servicename, the json renders as expected.

Additionally, I tried the following but no luck.
app.UseSwaggerForOcelotUI(opt => {
	opts.ServerOcelot = "/siteName/gateway" ;
})

How do I get swagger to work when hosting the gateway in a virtual directory.

**Comment by raman-m** [comment]
### We don't support [Swagger](https://ocelot.readthedocs.io/en/latest/introduction/notsupported.html#swagger) officially❗ 

But we believe it will be supported in future, see 
- #1429 
- #1904 
- more [discussions](https://github.com/search?q=repo%3AThreeMammals%2FOcelot+swagger&type=discussions)

### We don't recommend to deploy to IIS ❕ 
- See [IIS Gotchas](https://ocelot.readthedocs.io/en/latest/introduction/gotchas.html#iis)
