### ISSUE TITLE
Redirection to the API is not working

### ISSUE THREAD

**Issue by rudar23** [ThreeMammals/Ocelot#1282]
## Expected Behavior / New Feature

I have configured Ocelot and it should redirect to the API's
## Steps to Reproduce the Problem

  1. Program.cs
 
     public class Program
    {
        public static void Main(string[] args)
        {
            CreateHostBuilder(args).Build().Run();
        }

        public static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)
             .ConfigureAppConfiguration((hostingContext, config) =>
             {
                 config.AddJsonFile(Path.Combine("Configuration", "configuration.json"));
             })
                .ConfigureWebHostDefaults(webBuilder =>
                {
                    webBuilder.UseStartup<Startup>();
                });
    }
  1.

public class Startup
    {
        public Startup(IConfiguration configuration)
        {
            Configuration = configuration;
        }

        public IConfiguration Configuration { get; }

        // This method gets called by the runtime. Use this method to add services to the container.
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddControllers();
            services.AddOcelot();
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }

            app.UseHttpsRedirection();

            app.UseRouting();

            app.UseAuthorization();
            
            app.UseEndpoints(endpoints =>
            {
                endpoints.MapControllers();
            });

            app.UseOcelot().Wait();
        }
    }
  3. Configuration
{
  "ReRoutes": [
    //product api
    {
      "DownstreamPathTemplate": "/api/Product/{everything}",
      "DownstreamScheme": "http",
      "DownstreamHostAndPorts": [
        {
          "Host": "localhost",
          "Port": 57651
        }
      ],
      "UpstreamPathTemplate": "/api/Product/{everything}",
      "UpstreamHttpMethod": [
        "GET",
        "POST",
        "PUT",
        "DELETE"
      ]
      
    },
    {
      "DownstreamPathTemplate": "/api/Customer/{everything}",
      "DownstreamScheme": "http",
      "DownstreamHostAndPorts": [
        {
          "Host": "localhost",
          "Port": 57582
        }
      ],
      "UpstreamPathTemplate": "/api/Customer/{everything}",
      "UpstreamHttpMethod": [
        "GET",
        "POST",
        "PUT",
        "DELETE"
      ]
      
    }
  ],
  "GlobalConfiguration": {
    "BaseUrl": "http://localhost:5001"

  }

}

## Specifications

  - Version:Ocelot 16.0.1
  - Platform:Windows
  - Subsystem:

**Comment by jlukawska** [comment]
Hello, 
Change "ReRoutes" to "Routes" in ocelot.json. It has been changed in the recent versions.

**Comment by rudar23** [comment]
Now I am getting 
This page isn’t workinglocalhost is currently unable to handle this request.
HTTP ERROR 502

**Comment by jlukawska** [comment]
502 status code means that the service is unavailable. Are you sure that the downstream service is listening?
