### ISSUE TITLE
Ocelot Authorization -- How to provide access to a Microservice for Admin Role via Ocelot Gateway

### ISSUE THREAD

**Issue by chaitanyaphanikumar** [ThreeMammals/Ocelot#1286]
I'm new to Ocelot and trying to implement. I have 3 Microservices which I've configured the routes in Ocelot. I have a requirement that **Admin** login can create customers but not **User** login.  So, I've created custom **role** Claim in JWT token generation. My Authentication is successful and customer creation is working. But it is working for both **Admin** token and **User** token.

I'm not sure how to authorize **Admin** role alone to access my CreateCustomer Microservice.. And normal User should not access that Microservice.. 

Any help is appreciated !!

Here is my JWT Token generation in Login Microservice

`   public string GenerateToken(Guid userId, string role)
        {            
            var signingKey = new SymmetricSecurityKey(Encoding.UTF8.GetBytes(options.Secret.ToString()));
            var signingCredentials = new SigningCredentials(signingKey, SecurityAlgorithms.HmacSha256);
            var claims = new Claim[]
            {
                new Claim("userId", userId.ToString()),
                new Claim("role", role)                
             };
            var expiration = DateTime.Now.AddMinutes(options.ExpiryMinutes);
            var jwt = new JwtSecurityToken(
                issuer: options.Iss,
                audience: options.Aud,
                claims : claims, 
                signingCredentials: signingCredentials, 
                expires: expiration);            
            return new JwtSecurityTokenHandler().WriteToken(jwt);
        } 
`

Here is my Startup.cs in Ocelot

`  public void ConfigureServices(IServiceCollection services)
        {            
            services.AddOcelot(Configuration);
            services.AddAuthorization();
            JwtConfiguration(services);
            services.AddCors(options => {
                                    options.AddPolicy("CorsPolicy", builder => builder.AllowAnyOrigin()
                                                                                      .AllowAnyMethod()
                                                                                      .AllowAnyHeader());
                                });

        }

     public async void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }
            else
            {                
                app.UseHsts();
            }
            app.UseCors("CorsPolicy");
            app.UseAuthentication();
            app.UseHttpsRedirection();
            await app.UseOcelot();
        }

   private void JwtConfiguration(IServiceCollection services)
        {
            var jwtConfig = Configuration.GetSection("jwt");
            var signingKey = new SymmetricSecurityKey(Encoding.UTF8.GetBytes(jwtConfig["secret"]));
            var tokenValidationParameters = new TokenValidationParameters
            {
                RequireExpirationTime = true,
                ValidateIssuer = true,
                ValidIssuer = jwtConfig["Iss"],
                ValidateAudience = true,
                ValidAudience = jwtConfig["Aud"],
                ValidateIssuerSigningKey = true,
                IssuerSigningKey = signingKey
            };
            services.AddAuthentication(o =>
            {
                o.DefaultAuthenticateScheme = JwtBearerDefaults.AuthenticationScheme;
                o.DefaultChallengeScheme = JwtBearerDefaults.AuthenticationScheme;
            }).
            AddJwtBearer(JwtBearerDefaults.AuthenticationScheme, x =>
            {
                x.RequireHttpsMetadata = false;
                x.SaveToken = true;
                x.TokenValidationParameters = tokenValidationParameters;
            });
        }
`
Here is my Ocelot Configuration.json

`{
  "ReRoutes": [
    //customer creation config
    {
      "DownstreamPathTemplate": "/api/v1/createcustomer",
      "DownstreamScheme": "https",
      "DownstreamHostAndPorts": [
        {
          "Host": "localhost",
          "Port": 44320
        }
      ],
      "UpstreamPathTemplate": "/v1/createcustomer",
      "UpstreamHttpMethod": [ "POST" ],
      "AuthenticationOptions": {
        "AuthenticationProviderKey": "Bearer",
        "AllowedScopes": []
      },
      "RoutesClaimsRequirement": {
        "role": "Admin"
      }
    },

--- Other routes ---
`

Here is my CreateCustomer Microservice Startup.cs

` public void ConfigureServices(IServiceCollection services)
        {
            services.AddDbContextPool<AppDbContext>(
                options => options.UseSqlServer(Configuration.GetConnectionString("CustomersConnection")));
           
            services.AddScoped<ICustomerRepository, CustomerRepository>();
            services.AddScoped<IAccountRepository, AccountRepository>();
            services.AddScoped<IFundsRepository, FundsRepository>();
            
            //services.AddAuthorization(o =>
            //{
            //    o.AddPolicy("AdminPolicy", policy => policy.RequireClaim("role", "Admin"));
            //});

            services.AddApiVersioning(o =>
            {
                o.ReportApiVersions = true;
                o.AssumeDefaultVersionWhenUnspecified = true;
                o.DefaultApiVersion = new ApiVersion(1, 0);
            });

            services.AddSwaggerGen(c => {
                c.SwaggerDoc("v1", new OpenApiInfo { Title = "Customer Service", Version = "v1" });
            });
            
            IdentityModelEventSource.ShowPII = true;
            services.AddMvc().SetCompatibilityVersion(CompatibilityVersion.Version_2_2).AddXmlSerializerFormatters();
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }
            else
            {               
                app.UseHsts();
            }

            app.UseHttpsRedirection();
            app.UseAuthentication();
            app.UseSwagger();
            app.UseSwaggerUI(c =>
            {
                c.SwaggerEndpoint("/swagger/v1/swagger.json", "Customer Service V1");
            });            
            app.UseMvc();           
        }
`

CreateCustomer Controller 

`    [ApiVersion("1.0")]
    [Route("api/v{version:apiVersion}/[controller]")]
    [ApiController]
    public class CreateCustomerController : ControllerBase
    {
        private readonly ICustomerRepository customerRepository;
        private readonly IAccountRepository accountRepository;

        public CreateCustomerController(ICustomerRepository customerRepository, IAccountRepository accountRepository)
        {
            this.customerRepository = customerRepository;
            this.accountRepository = accountRepository;
        }

        //[Authorize(Policy = "AdminPolicy")]    ---> Tried this.. It did not work
        [HttpPost]
        public async Task<IActionResult> CreateCustomer([FromBody]Customer customer)
        {
           // Custom logic
        }
  
`

## Specifications

  - Version: Ocelot 13.5
  - Platform: .Net core 2.2

Any suggestions/help is appreciated..

**Comment by wast** [comment]
Use RouteClaimsRequirement 

Read here https://ocelot.readthedocs.io/en/latest/features/authorisation.html
