### ISSUE TITLE
route -url char missing

### ISSUE THREAD

**Issue by yangbocheng** [ThreeMammals/Ocelot#1288]
# Route Bug

## Steps to Reproduce the Problem
1. Ocelot run at **localhost:9999** with configuration:
```json
{
      "DownstreamPathTemplate": "/cpx/t1/{id}",
      "DownstreamScheme": "http",
      "DownstreamHostAndPorts": [
        {
          "Host": "localhost",
          "Port": 5002
        }
      ],
      "UpstreamPathTemplate": "/safe/{id}",
      "UpstreamHttpMethod": [ "Get" ],
      "AllowAutoRedirect": true
}
```
2. Then call `http://localhost:9999/safe/3?id1=2312`  then log is:
```
info: Ocelot.Requester.Middleware.HttpRequesterMiddleware[0]
      requestId: 0HM17NUPUA37Q:00000001, previousRequestId: no previous request id, message: 200 (OK) status code, 
request uri: http://localhost:5002/cpx/t1/3?d1=2312
```
it should be `xxxx?id1=2312` , **The char `i` disappeared, id1 &rarr; d1**

## Specifications

  - Version: Ocelot **16.0.1**
  - Platform: **win10**

**Comment by raman-m** [comment]
@yangbocheng 
Hi xyyyy!
Thanks for your interest in Ocelot!

```diff
+ Accepted
```
... because of ready PR #1335 by @jlukawska 

---

> Version: Ocelot **16.0.1**

I guess the bug exists in current **v19** release too.

**Comment by yangbocheng** [comment]
it's works now, thanks
![image](https://github.com/ThreeMammals/Ocelot/assets/32633109/9f51ae3f-e4de-4f02-afc9-cebacbfb811a)

**Comment by raman-m** [comment]
@yangbocheng Congrats! 🥳
