### ISSUE TITLE
Integrating Identity Server4  with Ocelot for Hybrid and other granttypes

### ISSUE THREAD

**Issue by Dheerajmentor** [ThreeMammals/Ocelot#1293]
Dear, 

requesting you to kindly write a blog for Integrating Ocelot with Identity server 4 for authenticating different client (SPA, Mobile, Wapp-  at least Hybrid Grant type ) on docker 

i am looking for help for last 3 days and not able to make web application authenticate on Gateway(Ocelot) with Identity server 4 and if request authenticated and authorized and pass on to api behind gateway. 

it will be great help if you can provide a working sample in asp.net core 3.1

I have also created a dummy setup, it has a gateway(ocelot) , an api(asp.net core 3.1) , IdentityService (Identity server 4) and web application (asp.net core 3.1)

if you can help me solve this than i can contribute in updating document from my learning and can send you for review.

GitHub Link : https://github.com/Dheerajmentor/Microservice.git

Thank you 
Dheeraj Kumar

**Comment by pmjaleel** [comment]
We have done this in our project

**Comment by Dheerajmentor** [comment]
@pmjaleel , how does your comment helps here ?

**Comment by pmjaleel** [comment]
Sorry,
I was hoping if I could be any helpful in promoting this implementation. If you still think that this is of no use, you could let me know. I would delete them.

**Comment by Dheerajmentor** [comment]
You need not to be sorry, if you have insight how can it be help then please

**Comment by raman-m** [comment]
@Dheerajmentor 
Seems you wanted to have multiple authentication providers attached to Ocelot pipeline.
To have different auth schemes you need to ->
- Use native Asp.net Authentication Policies feature
- use Ocelot [Multiple Authentication Schemes](https://ocelot.readthedocs.io/en/latest/features/authentication.html#multiple-authentication-schemes) feature

Good luck!
