### ISSUE TITLE
RouteClaimsRequirement does not work properly, My request returns 403 Forbidden

### ISSUE THREAD

**Issue by mybirthname** [ThreeMammals/Ocelot#1296]
## Expected Behavior / New Feature
I make a request to the specific endpoint I expect when the token contains role Administrator to have access to the resource.

## Actual Behavior / Motivation for New Feature
I receive 403 Forbidden response

## Steps to Reproduce the Problem
How the microservice is configured in ocelot.json:
```
       {
      "DownstreamPathTemplate": "/api/v1/product/{everything}",
      "DownstreamScheme": "https",
      "DownstreamHostAndPorts": [
        {
          "Host": "product",
          "Port": 443
        }
      ],
      "UpstreamPathTemplate": "/product/{everything}",
      "UpstreamHttpMethod": [ "Get", "Post", "Delete" ],
      "AuthenticationOptions": {
        "AuthenticationProviderKey": "Bearer",
        "AllowedScopes": []
      },
      "RouteClaimsRequirement": {
        "Role": "Administrator"
      },
      "DangerousAcceptAnyServerCertificateValidator": true,
      "RateLimitOptions": {
        "ClientWhitelist": [],
        "EnableRateLimiting": true,
        "Period": "5s",
        "PeriodTimespan": 6,
        "Limit": 8
      }
    }
```

How Startup.cs looks like:

        public void ConfigureServices(IServiceCollection services)
        => services
            .AddCors()
            .AddTokenAuthentication(Configuration)
            .AddOcelot();

        public static IServiceCollection AddTokenAuthentication(
            this IServiceCollection services,
            IConfiguration
             configuration,
            JwtBearerEvents events = null)
        {
            var secret = configuration
                .GetSection(nameof(ApplicationSettings))
                .GetValue<string>(nameof(ApplicationSettings.Secret));

            var key = Encoding.ASCII.GetBytes(secret);

            services
                .AddAuthentication(authentication =>
                {
                    authentication.DefaultAuthenticateScheme = JwtBearerDefaults.AuthenticationScheme;
                    authentication.DefaultChallengeScheme = JwtBearerDefaults.AuthenticationScheme;
                })
                .AddJwtBearer(bearer =>
                {
                    bearer.RequireHttpsMetadata = false;
                    bearer.SaveToken = true;
                    bearer.TokenValidationParameters = new TokenValidationParameters
                    {
                        ValidateIssuerSigningKey = true,
                        IssuerSigningKey = new SymmetricSecurityKey(key),
                        ValidateIssuer = false,
                        ValidateAudience = false
                    };

                    if (events != null)
                    {
                        bearer.Events = events;
                    }
                });

            services.AddHttpContextAccessor();
            services.AddScoped<ICurrentUserService, CurrentUserService>();

            return services;

        }

        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            app
                .UseCors(options => options
                    .AllowAnyOrigin()
                    .AllowAnyHeader()
                    .AllowAnyMethod())
                .UseAuthentication()
                .UseAuthorization()
                .UseOcelot().Wait();
        }

How token is generated

```
        public string GenerateToken(User user, IEnumerable<string> roles = null)
        {
            var tokenHandler = new JwtSecurityTokenHandler();
            var key = Encoding.ASCII.GetBytes(this.applicationSettings.Secret);

            var claims = new List<Claim>
            {
                new Claim(ClaimTypes.NameIdentifier, user.Id),
                new Claim(ClaimTypes.Name, user.Email)
            };

            if (roles != null)
            {
                claims.AddRange(roles.Select(role => new Claim(ClaimTypes.Role, role)));
            }

            var tokenDescriptor = new SecurityTokenDescriptor
            {
                Subject = new ClaimsIdentity(claims),
                Expires = DateTime.UtcNow.AddDays(7),
                SigningCredentials = new SigningCredentials(
                    new SymmetricSecurityKey(key),
                    SecurityAlgorithms.HmacSha256Signature)
            };

            var token = tokenHandler.CreateToken(tokenDescriptor);
            var encryptedToken = tokenHandler.WriteToken(token);

            return encryptedToken;
        }

```

How the decrypted token looks like:
```
{
  "nameid": "e18d5f1f-a315-435c-9e38-df9f2c77ad20",
  "unique_name": "test@abv.bg",
  "role": "Administrator",
  "nbf": 1595460189,
  "exp": 1596064989,
  "iat": 1595460189
}
````
If I remove the "RouteClaimsRequirement" part from ocelot.json the microservice is acceptable without a problem. 

Also hints how I can I can debug issues like this are helpfull.

## Specifications

  - Version: 16.0.1
  - Platform: Linux docker container 
  - Subsystem:

**Comment by tmvan** [comment]
The key in `RouteClaimsRequirement` is case sensitive. Did you try to change the key from `Role` to `role`? Just like this:
```
"RouteClaimsRequirement": {
    "role": "Administrator"
}
```

**Comment by mybirthname** [comment]
@tmvan  the problem is the same like in https://github.com/ThreeMammals/Ocelot/issues/679#issuecomment-662905004. Thanks for your solution !
