### ISSUE TITLE
Ocelot.Provider.Consul Support Tag 

### ISSUE THREAD

**Issue by 842549829** [ThreeMammals/Ocelot#1298]
## Expected Behavior / New Feature
`var queryResult = await _consul.Health.Service(_config.KeyOfServiceInConsul, string.Empty, true);`
Tag is string.Empty
## Actual Behavior / Motivation for New Feature
Old
```json
"Routes":[
    {"ServiceName":"ServiceName"}
]
```
New
```json
{
    "Routes":[
        {
            "Service":{
                "Name":"ServiceName",
                "Tag":[
                    "v1",
                    "v2",
                    "v3"
                ],
                "Datacenter":"dc1"
            }
        }
    ]
}
```

**Comment by raman-m** [comment]
@842549829 What's your goal having Consul tags?
Will you personally contribute to implement this feature?

**Comment by raman-m** [comment]
Dear @842549829,
Update version to [23.3.0](https://github.com/ThreeMammals/Ocelot/releases/tag/23.3.0)
With [Consul Service Builder](https://ocelot.readthedocs.io/en/latest/features/servicediscovery.html#consul-service-builder) and [Metadata](https://ocelot.readthedocs.io/en/latest/features/configuration.html#route-metadata) features develop whatever you want.
See more details in PR #2067 
### You have the right to reopen this issue in the future if you come with a PR ready
You you want official properties in route options then you have to contribute!
