### ISSUE TITLE
I can't access my service through the gateway. Am I mismatched

### ISSUE THREAD

**Issue by 344089386** [ThreeMammals/Ocelot#1302]
![image](https://user-images.githubusercontent.com/22017199/88498596-28b3d500-cff6-11ea-9746-fd7d9cbe62b9.png)
![image](https://user-images.githubusercontent.com/22017199/88498620-35382d80-cff6-11ea-8f80-f41cfccb9413.png)
![image](https://user-images.githubusercontent.com/22017199/88498643-3f5a2c00-cff6-11ea-818f-7ddc9efde406.png)

**Comment by raman-m** [comment]
This K8s provider bug was fixed in version [23.0](https://github.com/ThreeMammals/Ocelot/releases/tag/23.0.0)
See PR #1954
