### ISSUE TITLE
Add:Support for load balancing on Consul cluster

### ISSUE THREAD

**Issue by HonghuiHu** [ThreeMammals/Ocelot#1303]
## Expected Behavior / New Feature
At present, the configuration file only supports a single point of Consul address configuration, cannot access Consul to achieve load balancing

## Actual Behavior / Motivation for New Feature
Consul  Server-Client cluster

## Steps to Reproduce the Problem

  1.
  1.
  1.

## Specifications

  - Version:
  - Platform:
  - Subsystem:

**Comment by raman-m** [comment]
@ggnaegi  What did the author said?

**Comment by raman-m** [comment]
@HonghuiHu 
Will you personally contribute to implement this feature?
