### ISSUE TITLE
Two problems in Ocelot Service Discovery using Consul

### ISSUE THREAD

**Issue by cdyhj** [ThreeMammals/Ocelot#1304]
## Expected Behavior / New Feature

Ocelot uses Consul for service discovery.

## Actual Behavior / Motivation for New Feature
Ocelot uses Consul for service discovery.

## Steps to Reproduce the Problem

1. Using Ocelot and `Ocelot.Provider.Consul`  Version 16.0.1
2. The IP address obtained from the service is the name value of the node, not the actual IP address of the service
3. The address of the service cannot be loaded when it is loaded for the first time. It can be used normally if it is refreshed again

### Modification `Ocelot.Provider.Consul`
The `BuildService` method of the Consul class is as follows:
```csharp
private Service BuildService(ServiceEntry serviceEntry, Node serviceNode)
{
            return new Service(
                serviceEntry.Service.Service,
                new ServiceHostAndPort(serviceEntry.Service.Address, serviceEntry.Service.Port),
                serviceEntry.Service.ID,
                GetVersionFromStrings(serviceEntry.Service.Tags),
                serviceEntry.Service.Tags ?? Enumerable.Empty<string>());
}
```
And `Ocelot.Provider.Consul` public `Task<List<Service>> Get()` of `PollConsul` class is as follows:
```csharp
public  Task<List<Service>> Get()
{
    int PollNum = 0;
    if (_services.Count <= 0)
    {
        Poll().Wait();
    }
    return Task.FromResult(_services);
}
```

## Specifications
  - Version: **16.0.1**

**Comment by stann1** [comment]
I can confirm. I have Ocelot configured with Consul as service discovery. I have one service configured for load-balancing with ` "LoadBalancerOptions": {
        "Type": "RoundRobin"
      } `

When I start the service it always gives 404 `Error Code: ServicesAreEmptyError Message: There were no services in NoLoadBalancer errors found in ResponderMiddleware`

Note - this issue SOMETIMES disappears after a few minutes. It is only on version 16.0.1. I was running 14.1.0 until now - but had to upgrade because load balancing was not working at all.

My consul config:
`
"ServiceDiscoveryProvider": {
      "Scheme": "http",
      "Host": "consul",
      "Port": 8500,
      "ConfigurationKey": "GatewayConfig",
      "Type": "Consul"
    }
`

**Comment by matteoPhre** [comment]
Same problem here. When I hit an API for the first time, always returns 404 ` ServicesAreEmptyError Message: services were empty for UsersService errors found in ResponderMiddleware.`. If I try to call again the same api, with same headers and same body..everythings fine.

**Comment by raman-m** [comment]
@cdyhj @stann1 @matteoPhre 
Hello! **FYI**
I believe the linked PR #1670 will fix this bug. You can review the code and validate the bug fix.
- #1670

**Comment by Dshekar** [comment]
> I can confirm. I have Ocelot configured with Consul as service discovery. I have one service configured for load-balancing with `"LoadBalancerOptions": { "Type": "RoundRobin" }`
> 
> When I start the service it always gives 404 `Error Code: ServicesAreEmptyError Message: There were no services in NoLoadBalancer errors found in ResponderMiddleware`
> 
> Note - this issue SOMETIMES disappears after a few minutes. It is only on version 16.0.1. I was running 14.1.0 until now - but had to upgrade because load balancing was not working at all.
> 
> My consul config: `"ServiceDiscoveryProvider": { "Scheme": "http", "Host": "consul", "Port": 8500, "ConfigurationKey": "GatewayConfig", "Type": "Consul" }`
> 
> EDIT: looks like general problem with Consul service discovery, because even when I remove the load balancing it is the same result...

Same issue as explained above with 1.20.2 version. I am trying to run a very basic setup of ocelot consul and a microservice in docker containers. when i use service discovery its using nodename instead of localhost. in logs i can see it goes to url like http://4e12yy176234:5001/api/someendpoint

**Comment by raman-m** [comment]
>@Dshekar commented [on Jan 13, 2025](https://github.com/ThreeMammals/Ocelot/issues/1304#issuecomment-2587633790)

Did you read [Service Discovery](https://ocelot.readthedocs.io/en/latest/features/servicediscovery.html) docs?
The answers can be found at the end of the document:
- [Consul Service Builder](https://ocelot.readthedocs.io/en/latest/features/servicediscovery.html#consul-service-builder)
- [AddConsul&lt;T&gt; method](https://ocelot.readthedocs.io/en/latest/features/servicediscovery.html#addconsul-t-method)

Hope it helps!
