### ISSUE TITLE
Hi ,i have created the mvc application using auth0 using OPIC flow when user logged in getting token  and i am sending to API Gateway to reroute to  other service ,but i am unable to get that token validated in ai gate way 

### ISSUE THREAD

**Issue by sadanand0033** [ThreeMammals/Ocelot#1306]
## Actual Behavior / Motivation for New Feature
.AddOpenIdConnect("Auth0", options =>
          {
              // Set the authority to your Auth0 domain
              options.Authority = $"https://{Configuration["Auth0:Domain"]}";

              options.TokenValidationParameters = new TokenValidationParameters
              {
                  ValidAudiences =new string[] { "https://PrimePayOneXdev-Gateway.com" },
                  NameClaimType = "name",
                  RoleClaimType = ClaimTypes.Role,

              };
              // Configure the Auth0 Client ID and Client Secret
              options.ClientId = Configuration["Auth0:ClientId"];
              options.ClientSecret = Configuration["Auth0:ClientSecret"];
              options.GetClaimsFromUserInfoEndpoint = true;
              // Set response type to code
              options.ResponseType = OpenIdConnectResponseType.CodeIdToken;
              // options.us = false;

              // Configure the scope
              options.Scope.Clear();
              options.Scope.Add("openid");
              options.Scope.Add("profile");
              options.Scope.Add("email");

              // Set the callback path, so Auth0 will call back to http://localhost:3000/callbackAsync
              // Also ensure that you have added the URL as an Allowed Callback URL in your Auth0 dashboard
              options.CallbackPath = new PathString("/account/callback");

              // Configure the Claims Issuer to be Auth0
              options.ClaimsIssuer = "Auth0";

              // Saves tokens to the AuthenticationProperties
              options.SaveTokens = true;

              options.Events = new OpenIdConnectEvents
              {
                  OnRedirectToIdentityProvider = context =>
                  {
                      context.ProtocolMessage.SetParameter("audience", "https://PrimePayOneXdev-Gateway.com");

                      return Task.FromResult(0);
                  },
                  // handle the logout redirection 
                  OnRedirectToIdentityProviderForSignOut = (context) =>
                  {
                      var logoutUri = $"https://{Configuration["Auth0:Domain"]}/v2/logout?client_id={Configuration["Auth0:ClientId"]}";

                      var postLogoutUri = context.Properties.RedirectUri;
                      if (!string.IsNullOrEmpty(postLogoutUri))
                      {
                          if (postLogoutUri.StartsWith("/"))
                          {
                              // transform to absolute
                              var request = context.Request;
                              postLogoutUri = request.Scheme + "://" + request.Host + request.PathBase + postLogoutUri;
                          }
                          logoutUri += $"&returnTo={ Uri.EscapeDataString(postLogoutUri)}";
                      }

                      context.Response.Redirect(logoutUri);
                      context.HandleResponse();

                      return Task.CompletedTask;
                  }
              };
          })
 
  }
in ocelot API gate way is below code 
 services.AddAuthentication(options =>
            {
                options.DefaultAuthenticateScheme = JwtBearerDefaults.AuthenticationScheme;
                options.DefaultChallengeScheme = JwtBearerDefaults.AuthenticationScheme;
            }).AddJwtBearer(options =>
            {
                options.Authority = "https://primepayonex-dev.us.auth0.com/";
                options.Audience = "https://PrimePayOneXdev-Gateway.com";
            });
I need to use the context user who is logged in but I couldnt
## Steps to Reproduce the Problem

  1.
  1.
  1.

## Specifications

  - Version:
  - Platform:
  - Subsystem:

**Comment by raman-m** [comment]
Please, help yourself!
We are not consultancy firm!
