### ISSUE TITLE
Alternate array syntax to resolve : issue in key names for RouteClaimsRequirement option in configuration

### ISSUE THREAD

**Issue by ghorsey** [ThreeMammals/Ocelot#1308]
## New Feature
Add an alternate syntax to the `RouteClaimsRequirement` configuration.  Instead of the current shorter (and nicer) current syntax of:

```json
"RouteClaimsRequirement": {
  "{ClaimType}": "{ClaimValue}"
}
```

Support a more verbose array syntax as well: 
````json
"RouteClaimsRequirement": [
  {
    "type": "{ClaimType}",
    "value": "{ClaimValue}"
  }
]
````

## Motivation for New Feature

Microsoft uses a <kbd>:</kbd> to signify hierarchy in configuration files. 
See https://github.com/dotnet/extensions/issues/782

There is a great workaround [on issue 679](https://github.com/ThreeMammals/Ocelot/issues/679#issuecomment-662905004) that would be unnecessary if an alternate syntax could be used without the <kbd>:</kbd> in a key value.

The most common/reported issue is with the default MS role claim type `http://schemas.microsoft.com/ws/2008/06/identity/claims/role`

Currently this does not work and requires a workaround:
````json
"RouteClaimsRequirement": {
  "http://schemas.microsoft.com/ws/2008/06/identity/claims/role": "Administrator"
}
````

Having an alternate syntax would fix this and "just work":
````json
"RouteClaimsRequirement": [
  {
    "type": "http://schemas.microsoft.com/ws/2008/06/identity/claims/role",
    "value": "Administrator"
  }
]

````

**Comment by ShvetsovAU** [comment]
Don't implemented?

**Comment by olssonp** [comment]
I'm having the same problem and was about to suggest the same feature.

**Comment by raman-m** [comment]
@ghorsey 
Hi Geoff!
Will you personally contribute and be responsible for feature delivery?

**Comment by raman-m** [comment]
Dear @ghorsey,
Update version to [23.3.0](https://github.com/ThreeMammals/Ocelot/releases/tag/23.3.0)!
With [Metadata](https://ocelot.readthedocs.io/en/latest/features/configuration.html#route-metadata) feature do whatever you want. Good luck!

### You have the right to reopen this issue in the future if you come with a PR ready
