### ISSUE TITLE
Forwarded authenticated request are unauthorized

### ISSUE THREAD

**Issue by ildoc** [ThreeMammals/Ocelot#1309]
I managed to authenticate my api calls to ocelot with identityserver4 as described [here](https://ocelot.readthedocs.io/en/latest/features/authentication.html#identity-server-bearer-tokens) but when the request arrives to the target service, the authorization header seems to be there but it fails to check for scopes, claims, etc.

When from my SPA I make an authenticated call to /test/weatherforecast I get this in ocelot logs:

```
      Request starting HTTP/2 OPTIONS https://localhost:5005/test/weatherforecast  
[11:35:59 INF] Request starting HTTP/2 OPTIONS https://localhost:5005/test/weatherforecast   <s:Microsoft.AspNetCore.Hosting.Diagnostics>
info: Microsoft.AspNetCore.Cors.Infrastructure.CorsService[4]
      CORS policy execution successful.
[11:35:59 INF] CORS policy execution successful. <s:Microsoft.AspNetCore.Cors.Infrastructure.CorsService>
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished in 41.902ms 204 
[11:35:59 INF] Request finished in 41.902ms 204  <s:Microsoft.AspNetCore.Hosting.Diagnostics>
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/2 GET https://localhost:5005/test/weatherforecast application/json 
[11:35:59 INF] Request starting HTTP/2 GET https://localhost:5005/test/weatherforecast application/json  <s:Microsoft.AspNetCore.Hosting.Diagnostics>
info: Microsoft.AspNetCore.Cors.Infrastructure.CorsService[4]
      CORS policy execution successful.
[11:35:59 INF] CORS policy execution successful. <s:Microsoft.AspNetCore.Cors.Infrastructure.CorsService>
info: Ocelot.RateLimit.Middleware.ClientRateLimitMiddleware[0]
      requestId: 0HM1QOO77J8KJ:00000003, previousRequestId: no previous request id, message: EndpointRateLimiting is not enabled for /{everything}
[11:35:59 INF] requestId: 0HM1QOO77J8KJ:00000003, previousRequestId: no previous request id, message: EndpointRateLimiting is not enabled for /{everything} <s:Ocelot.RateLimit.Middleware.ClientRateLimitMiddleware>
info: Ocelot.Authentication.Middleware.AuthenticationMiddleware[0]
      requestId: 0HM1QOO77J8KJ:00000003, previousRequestId: no previous request id, message: /test/weatherforecast is an authenticated route. AuthenticationMiddleware checking if client is authenticated
[11:35:59 INF] requestId: 0HM1QOO77J8KJ:00000003, previousRequestId: no previous request id, message: /test/weatherforecast is an authenticated route. AuthenticationMiddleware checking if client is authenticated <s:Ocelot.Authentication.Middleware.AuthenticationMiddleware>
info: Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler[2]
      Successfully validated the token.
[11:36:00 INF] Successfully validated the token. <s:Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler>
info: Ocelot.Authentication.Middleware.AuthenticationMiddleware[0]
      requestId: 0HM1QOO77J8KJ:00000003, previousRequestId: no previous request id, message: Client has been authenticated for /test/weatherforecast
[11:36:00 INF] requestId: 0HM1QOO77J8KJ:00000003, previousRequestId: no previous request id, message: Client has been authenticated for /test/weatherforecast <s:Ocelot.Authentication.Middleware.AuthenticationMiddleware>
info: Ocelot.Authorisation.Middleware.AuthorisationMiddleware[0]
      requestId: 0HM1QOO77J8KJ:00000003, previousRequestId: no previous request id, message: route is authenticated scopes must be checked
[11:36:00 INF] requestId: 0HM1QOO77J8KJ:00000003, previousRequestId: no previous request id, message: route is authenticated scopes must be checked <s:Ocelot.Authorisation.Middleware.AuthorisationMiddleware>
info: Ocelot.Authorisation.Middleware.AuthorisationMiddleware[0]
      requestId: 0HM1QOO77J8KJ:00000003, previousRequestId: no previous request id, message: user scopes is authorised calling next authorisation checks
[11:36:00 INF] requestId: 0HM1QOO77J8KJ:00000003, previousRequestId: no previous request id, message: user scopes is authorised calling next authorisation checks <s:Ocelot.Authorisation.Middleware.AuthorisationMiddleware>
info: Ocelot.Authorisation.Middleware.AuthorisationMiddleware[0]
      requestId: 0HM1QOO77J8KJ:00000003, previousRequestId: no previous request id, message: /{everything} route does not require user to be authorised
[11:36:00 INF] requestId: 0HM1QOO77J8KJ:00000003, previousRequestId: no previous request id, message: /{everything} route does not require user to be authorised <s:Ocelot.Authorisation.Middleware.AuthorisationMiddleware>
warn: Ocelot.Requester.Middleware.HttpRequesterMiddleware[0]
      requestId: 0HM1QOO77J8KJ:00000003, previousRequestId: no previous request id, message: 401 (Unauthorized) status code, request uri: http://webapplication1/weatherforecast
[11:36:01 WRN] requestId: 0HM1QOO77J8KJ:00000003, previousRequestId: no previous request id, message: 401 (Unauthorized) status code, request uri: http://webapplication1/weatherforecast <s:Ocelot.Requester.Middleware.HttpRequesterMiddleware>
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished in 1622.9384ms 401 
[11:36:01 INF] Request finished in 1622.9384ms 401  <s:Microsoft.AspNetCore.Hosting.Diagnostics>
```

My ocelot startup.cs

    [...]
    var authenticationProviderKey = "TestKey";

    services.AddAuthentication(IdentityServerAuthenticationDefaults.AuthenticationScheme)
        .AddIdentityServerAuthentication(authenticationProviderKey, options =>
        {
            options.Authority = "https://identity";
            options.ApiName = "myproject.api";
            options.SupportedTokens = SupportedTokens.Both;
        });
    [...]

ocelot config

```
{
  "Routes": [
    {
      "ReRouteIsCaseSensitive": false,
      "DownstreamPathTemplate": "/{everything}",
      "DownstreamScheme": "http",
      "DownstreamHostAndPorts": [
        {
          "Host": "webapplication1",
          "Port": 80
        }
      ],
      "UpstreamPathTemplate": "/test/{everything}",
      "AuthenticationOptions": {
        "AuthenticationProviderKey": "TestKey",
        "AllowedScopes": ["api"]
      }
    }
  ],
  "GlobalConfiguration": {
    // "BaseUrl": "https://api.mybusiness.com"
  }
}
```

my service startup.cs

    [...]
    services.AddAuthentication("Bearer")
        .AddJwtBearer("Bearer", options =>
        {
            options.Authority = "https://identity";
        });
    [...]

my service controller

    [ApiController]
    [Authorize]
    [Route("[controller]")]
    public class WeatherForecastController : ControllerBase
    {
        [HttpGet]
        public IEnumerable<WeatherForecast> Get()
        {
    [...default stuff...]

The user which makes the call has also other claims and a role, I tried to check for those but in the service controller the `User` is blank

**Comment by jdprigioni-stefanini** [comment]
I have a similar problem with Azure AD B2C integration.
It's seems to the authentication is Ok but then a 401 is returned.
Did you could resolve the problem?

info: Ocelot.RateLimit.Middleware.ClientRateLimitMiddleware[0]
      requestId: 0HM3FE978D2O2:00000001, previousRequestId: no previous request id, message: EndpointRateLimiting is not enabled for /balance
Ocelot.RateLimit.Middleware.ClientRateLimitMiddleware: Information: requestId: 0HM3FE978D2O2:00000001, previousRequestId: no previous request id, message: EndpointRateLimiting is not enabled for /balance

info: Ocelot.Authentication.Middleware.AuthenticationMiddleware[0]
Ocelot.Authentication.Middleware.AuthenticationMiddleware: Information: requestId: 0HM3FE978D2O2:00000001, previousRequestId: no previous request id, message: /api/v1/balance is an authenticated route. AuthenticationMiddleware checking if client is authenticated
      requestId: 0HM3FE978D2O2:00000001, previousRequestId: no previous request id, message: /api/v1/balance is an authenticated route. AuthenticationMiddleware checking if client is authenticated

info: Ocelot.Authentication.Middleware.AuthenticationMiddleware[0]
     requestId: 0HM3FE978D2O2:00000001, previousRequestId: no previous request id, message: Client has been authenticated for /api/v1/balance
Ocelot.Authentication.Middleware.AuthenticationMiddleware: Information: requestId: 0HM3FE978D2O2:00000001, previousRequestId: no previous request id, message: **Client has been authenticated for /api/v1/balance**

info: Ocelot.Authorisation.Middleware.AuthorisationMiddleware[0]
      requestId: 0HM3FE978D2O2:00000001, previousRequestId: no previous request id, message: route is authenticated scopes must be checked
Ocelot.Authorisation.Middleware.AuthorisationMiddleware: Information: requestId: 0HM3FE978D2O2:00000001, previousRequestId: no previous request id, message: route is authenticated scopes must be checked
Ocelot.Authorisation.Middleware.AuthorisationMiddleware: Information: requestId: 0HM3FE978D2O2:00000001, previousRequestId: no previous request id, message: user scopes is authorised calling next authorisation checks

info: Ocelot.Authorisation.Middleware.AuthorisationMiddleware[0]
      requestId: 0HM3FE978D2O2:00000001, previousRequestId: no previous request id, message: user scopes is authorised calling next authorisation checks

info: Ocelot.Authorisation.Middleware.AuthorisationMiddleware[0]
      requestId: 0HM3FE978D2O2:00000001, previousRequestId: no previous request id, message: /balance route does not require user to be authorised
Ocelot.Authorisation.Middleware.AuthorisationMiddleware: Information: requestId: 0HM3FE978D2O2:00000001, previousRequestId: no previous request id, message: /balance route does not require user to be authorised

warn: Ocelot.Requester.Middleware.HttpRequesterMiddleware[0]
      requestId: 0HM3FE978D2O2:00000001, previousRequestId: no previous request id, message: 401 (Unauthorized) status code, request uri: http://balance/balance
Ocelot.Requester.Middleware.HttpRequesterMiddleware: Warning: requestId: 0HM3FE978D2O2:00000001, previousRequestId: no previous request id, message: **401 (Unauthorized) status code**, request uri: http://balance/balance

**Comment by Rabosa616** [comment]
Any news?
I have the same issue with Azure AD B2C

**Comment by Rabosa616** [comment]
@jdprigioni-stefanini I figure out how to solve the issue with the Azure AD B2C
I have this configuration:
`
{
  "Routes": [
    {
      "DownstreamPathTemplate": "/{everything}",
      "DownstreamScheme": "http",
      "DownstreamHostAndPorts": [
        {
          "Host": "agrira.fields",
          "Port": 80
        }
      ],
      "UpstreamPathTemplate": "/{everything}",
      "ServiceName": "fields",
      "SwaggerKey": "fields",
      "AuthenticationOptions": {
        //"AuthenticationProviderKey": "AgriraIdenityServer",
        "AuthenticationProviderKey": "AgriraFields",
        "AllowedScopes": [
          "agrira_read_fields",
          "agrira_write_fields"
        ]
      }
    }
  ]
}
`
As you can see I have 2 scopes
The problem comes when the access token is deserialized and pass to the middlewares that instead of 2 scopes I get this: 
"agrira_read_fields agrira_write_fields".

If you look the code of the file [ClaimsParser](https://github.com/ThreeMammals/Ocelot/blob/develop/src/Ocelot/Infrastructure/Claims/Parser/ClaimsParser.cs) line 41 does not split the scopes so I get 1 scope, then [ScopesAuthorizer.cs](https://github.com/ThreeMammals/Ocelot/blob/develop/src/Ocelot/Authorization/ScopesAuthorizer.cs) at line 36 does not find any matching scopes. 

my solution:
I've created my own ClaimsParser:
public class ClaimsParser : IClaimsParser
    {
        public Response<string> GetValue(IEnumerable<Claim> claims, string key, string delimiter, int index)
        {
            var claimResponse = GetValue(claims, key);

            if (claimResponse.IsError)
            {
                return claimResponse;
            }

            if (string.IsNullOrEmpty(delimiter))
            {
                return claimResponse;
            }

            var splits = claimResponse.Data.Split(delimiter.ToCharArray());

            if (splits.Length <= index || index < 0)
            {
                return new ErrorResponse<string>(new CannotFindClaimError($"Cannot find claim for key: {key}, delimiter: {delimiter}, index: {index}"));
            }

            var value = splits[index];

            return new OkResponse<string>(value);
        }

        public Response<List<string>> GetValuesByClaimType(IEnumerable<Claim> claims, string claimType)
        {
            List<string> values = new List<string>();

            values.AddRange(claims.Where(x => x.Type == claimType).SelectMany(x => x.Value.Split(" ")).ToList());

            return new OkResponse<List<string>>(values);
        }

        private Response<string> GetValue(IEnumerable<Claim> claims, string key)
        {
            var claimValues = claims.Where(c => c.Type == key).Select(c => c.Value).ToArray();

            if (claimValues.Length > 0)
            {
                return new OkResponse<string>(new StringValues(claimValues).ToString());
            }

            return new ErrorResponse<string>(new CannotFindClaimError($"Cannot find claim for key: {key}"));
        }
    }

and I've inject to the DI  at Startup class like this:
public void ConfigureServices(IServiceCollection services)
        { 
                services.TryAddSingleton<IClaimsParser, ClaimsParser>();
                ...

Hope it helps you.

**Comment by raman-m** [comment]
@Rabosa616  do we still have the same problem in Claims Parser in the latest 23.1+ versions?

**Comment by raman-m** [comment]
## Outdated issue :exclamation: 
@ildoc Update version to [23.3.0](https://github.com/ThreeMammals/Ocelot/releases/tag/23.3.0)!
### You have the right to reopen this issue in the future if you come with a PR ready
