### ISSUE TITLE
When upstream and downstream path are same, ocelot does not act as a proxy, tried using catch all

### ISSUE THREAD

**Issue by neetra** [ThreeMammals/Ocelot#1311]
@TomPallister , @binarymash , @geffzhang , @thiagoloureiro 
As we are planning to use ocelot.
 I need this 1-1 mapping feature(especially ratelimiting, caching ) for my project, and I am using ocelot in many areas of my project.
Thanks in advance.

I would be very very grateful if you help me with this.

##  New Feature
 ocelot **do not act as proxy** when  upstream and downstream path are same, and downstream services are running on the same host and port where ocelot is integrated.

**For instance:**
My application in which ocelot is integrated is running at https://localhost:44360
My controller endpoint is https://localhost:44360/WeatherForecast.
 
I have also tried configuring
```{
      "DownstreamPathTemplate": "/{url}",
      "DownstreamScheme": "https",
      "DownstreamHostAndPorts": [
        {
          "Host": "localhost",
          "Port": 44360
        }
      ],

      "UpstreamPathTemplate": "/{url}"

    }
```
**### ocelot.json**
```
{
  "Routes": [

    {
      "DownstreamPathTemplate": "/WeatherForecast",
      "DownstreamScheme": "https",
      "DownstreamHostAndPorts": [
        {
          "Host": "localhost",
          "Port": 44360
        }
      ],

      "UpstreamPathTemplate": "/WeatherForecast"

    },
    {
      "DownstreamPathTemplate": "/WeatherForecast",
      "DownstreamScheme": "https",
      "DownstreamHostAndPorts": [
        {
          "Host": "localhost",
          "Port": 44360
        }
      ],

      "UpstreamPathTemplate": "/one/WeatherForecast"

    },
    {
      "DownstreamPathTemplate": "/WeatherForecast",
      "DownstreamScheme": "https",
      "DownstreamHostAndPorts": [
        {
          "Host": "localhost",
          "Port": 44360
        }
      ],

      "UpstreamPathTemplate": "/WeatherForecast/two"

    },
    {
      "DownstreamPathTemplate": "/{url}",
      "DownstreamScheme": "https",
      "DownstreamHostAndPorts": [
        {
          "Host": "jsonplaceholder.typicode.com",
          "Port": 443
        }
      ],

      "UpstreamPathTemplate": "/{url}"

    }
  ]
    }
```

**Case A:**

Startup.cs
           
                     // Used before map controllers
                     app.UseOcelot().Wait();

                   app.UseEndpoints(endpoints =>
                  {
                          endpoints.MapControllers();
                   });
           ```

Output:

1. Request Url : https://localhost:44360/posts
![image](https://user-images.githubusercontent.com/30404609/90601705-3b48b500-e216-11ea-8e44-cfe1241eb854.png)
2. https://localhost:44360/WeatherForecast ,  https://localhost:44360/one/WeatherForecast,  
     https://localhost:44360/WeatherForecast/two

Produces infinite output
![image](https://user-images.githubusercontent.com/30404609/90602168-ed807c80-e216-11ea-9e86-396e915c8160.png)
Thus I can infer that may be Ocelot.HttpRequestMiddleware is not called.



** Case B:**


Startup.cs
           
                     
                   app.UseEndpoints(endpoints =>
                  {
                          endpoints.MapControllers();
                   });
                // Used after map controllers
                     app.UseOcelot().Wait();

           ```

Output:

1. Request Url : https://localhost:44360/posts
![image](https://user-images.githubusercontent.com/30404609/90601705-3b48b500-e216-11ea-8e44-cfe1241eb854.png)
2.  Request Url :  https://localhost:44360/one/WeatherForecast,   https://localhost:44360/WeatherForecast/two

Ocelot acts as an proxy
![image](https://user-images.githubusercontent.com/30404609/90602830-fa51a000-e217-11ea-8dab-1d75e344ba16.png)

3. Request Url :  https://localhost:44360/WeatherForecast
Ocelot does not act as proxy
[Expected output : Gateway should act as an proxy]
I will be very grateful if someone helps me to achieve my expected output.

## Specifications

  - Version:16.0.1
  - Platform:Windows 10

**Comment by neetra** [comment]
@jlukawska  have you faced this?

**Comment by lommez** [comment]
I got the same problem...
When DownstreamPathTemplate and UpstreamPathTemplate starts with "/api", ocelot can redirect the requests:

Here is my ocelot configuration, is very simple:

```json
{
  "Routes": [
    {
      "DownstreamPathTemplate": "/api/app/person",
      "DownstreamScheme": "http",
      "DownstreamHostAndPorts": [
        {
          "Host": "localhost",
          "Port": 5002
        }
      ],
      "UpstreamPathTemplate": "/api/person",
      "UpstreamHttpMethod": [ "Get" ]
    }
  ],
  "HttpHandlerOptions": {
    "UseTracing": true
  },
  "GlobalConfiguration": {
    "BaseUrl": "http://localhost:5000"
  }
}
```

If i change the UpstreamPathTemplate value to anything that doesnt starts with "/api" everything works fine.
Is that a limitation or a bug?

**Comment by neetra** [comment]
> I got the same problem...
> When DownstreamPathTemplate and UpstreamPathTemplate starts with "/api", ocelot can't redirect the requests:
> 
> Here is my ocelot configuration, is very simple:
> 
> ```json
> {
>   "Routes": [
>     {
>       "DownstreamPathTemplate": "/api/app/person",
>       "DownstreamScheme": "http",
>       "DownstreamHostAndPorts": [
>         {
>           "Host": "localhost",
>           "Port": 5002
>         }
>       ],
>       "UpstreamPathTemplate": "/api/person",
>       "UpstreamHttpMethod": [ "Get" ]
>     }
>   ],
>   "HttpHandlerOptions": {
>     "UseTracing": true
>   },
>   "GlobalConfiguration": {
>     "BaseUrl": "http://localhost:5000"
>   }
> }
> ```
> 
> If i change the UpstreamPathTemplate value to anything that doesnt starts with "/api" everything works fine.
> Is that a limitation or a bug?

My use case is i am using same upstreampath and downstream path, ocelot not act as proxy
   {
      "DownstreamPathTemplate": "/WeatherForecast",
      "DownstreamScheme": "https",
      "DownstreamHostAndPorts": [
        {
          "Host": "localhost",
          "Port": 44360
        }
      ],

      "UpstreamPathTemplate": "/WeatherForecast"

    }

**Comment by neetra** [comment]
> I got the same problem...
> When DownstreamPathTemplate and UpstreamPathTemplate starts with "/api", ocelot can't redirect the requests:
> 
> Here is my ocelot configuration, is very simple:
> 
> ```json
> {
>   "Routes": [
>     {
>       "DownstreamPathTemplate": "/api/app/person",
>       "DownstreamScheme": "http",
>       "DownstreamHostAndPorts": [
>         {
>           "Host": "localhost",
>           "Port": 5002
>         }
>       ],
>       "UpstreamPathTemplate": "/api/person",
>       "UpstreamHttpMethod": [ "Get" ]
>     }
>   ],
>   "HttpHandlerOptions": {
>     "UseTracing": true
>   },
>   "GlobalConfiguration": {
>     "BaseUrl": "http://localhost:5000"
>   }
> }
> ```
> 
> If i change the UpstreamPathTemplate value to anything that doesnt starts with "/api" everything works fine.
> Is that a limitation or a bug?

I will be very thankful @lommez  if you try same on your side and let me know if it is working at your end

**Comment by lommez** [comment]
@neetra , I have made a test with the same path for Down and Upstream and didn't work.
Only works if the first word between the "/" is different.

**Comment by zTheProgrammer** [comment]
I am trying to implement both http and https for same upstream route like following but it does not for work for both as a same time. Kindly help
![image](https://user-images.githubusercontent.com/75984925/102178135-b705f600-3ec6-11eb-9de8-d36cf40adf8c.png)

**Comment by neetra** [comment]
@lommez The way I fixed it was filtering the incoming request and if it configured to pass via gateway.
In asp net core I used  app.MapWhen



@zTheProgrammer  may be this approach help in your case
