### ISSUE TITLE
Question Ocelot and Blazor

### ISSUE THREAD

**Issue by MitchWenceInfocorp** [ThreeMammals/Ocelot#1318]
## Expected Behavior / New Feature
Having a Blazor microservice routing via Ocelot work by going to `https://myOcelotMicroserviceIP:Port/myBlazorRoute`

## Actual Behavior / Motivation for New Feature
Going to the Ocelot route gives an error page and opening up the dev console returns this:

```
bootstrap.min.css:1 Failed to load resource: the server responded with a status of 404 (Not Found)
default.css:1 Failed to load resource: the server responded with a status of 404 (Not Found)
... and the rest of the resources of the Blazor app

```
It should be noted that the Blazor app does load correctly on its own.  The Ocelot is able to route API correctly.  I know the Ocelot is routing to the specific Blazor app as I am able to change the error message on the page and it is updated

## Steps to Reproduce the Problem

  1.  Configure the routing json like this:

```
{
      "DownstreamPathTemplate": "/{url}",
      "DownstreamScheme": "https",
      "DownstreamHostAndPorts": [
        {
          "Host": "myBlazorApp",
          "Port": 5000
        }
      ],
      "UpstreamPathTemplate": "/myBlazorRoute/{catchAll}",
      "UpstreamHttpMethod": []
    }
```
  2.  Start both the Ocelot microservice and Blazor microservice
  3. Try going to `https://myOcelotMicroserviceIP:Port/myBlazorRoute`

## Specifications

  - Version: Ocelot : .NET Core 2.2 Ocelot 13.5.2 / Blazor: .NET Core 3.1
  - Platform: Tested on Windows and Linux

**Comment by raman-m** [comment]
> Version: Ocelot : .NET Core 2.2 Ocelot 13.5.2 / Blazor: .NET Core 3.1

Ancient issue! We support only .NET 6+, the same versions as Microsoft does.

If Blazor endpoint uses Websocks then you must change route scheme from `https` to `wss`:
> "DownstreamScheme": "wss",
