### ISSUE TITLE
Cycle deteched when using dotnet add package ocelot or nuget

### ISSUE THREAD

**Issue by d4046949** [ThreeMammals/Ocelot#1323]
## Expected Behavior / New Feature
Package should install correctly

## Actual Behavior / Motivation for New Feature
Instead, I'm geting a circular dependency issue reported. 
`
S C:\Users\xxx\source\repos\Ocelot\Ocelot> dotnet add package ocelot
  Determining projects to restore...
  Writing C:\Users\xxx\AppData\Local\Temp\tmp14EA.tmp
info : Adding PackageReference for package 'ocelot' into project 'C:\Users\xxx\Source\repos\Ocelot\Ocelot\Ocelot.csproj'.
info : Restoring packages for C:\Users\xxx\source\repos\Ocelot\Ocelot\Ocelot.csproj...
error: Cycle detected.
error:   Ocelot -> ocelot (>= 0.0.0).
info : Package 'ocelot' is compatible with all the specified frameworks in project 'C:\Users\xxx\source\repos\Ocelot\Ocelot\Oc
elot.csproj'.
error: Value cannot be null. (Parameter 'path1')
`

## Steps to Reproduce the Problem

  1.Create a new blank dotnetcore 3.1 web api
  1. attempt to install ocelot via nuget package manager or dotnorecore cli
  1. notice the failure

**Comment by jlukawska** [comment]
Hello, try to name your project with a name other than "Ocelot".

**Comment by raman-m** [comment]
We don't support .NET 3.1 anymore. Microsoft doesn't support .NET 5 and below...
