### ISSUE TITLE
Bad Gateway (502) Error with Service Discovery - Docker / Consul

### ISSUE THREAD

**Issue by nemanjapyr** [ThreeMammals/Ocelot#1325]
Set up API Gateway to accept HTTPS messages, but passing on to services running HTTP, using Consul and Docker configuration.

Service discovery only works when sending HTTP requests to API Gateway. When trying to use HTTPS, get 502 Bad Gateway error. 

Error Code: ConnectionToDownstreamServiceError Message: **Error connecting to downstream service**, exception: System.Net.Http.HttpRequestException: **The SSL connection could not be established**, see inner exception.

---> System.IO.IOException: **The handshake failed due to an unexpected packet format.**

at System.Net.Security.SslStream.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)

at System.Net.Security.SslStream.PartialFrameCallback(AsyncProtocolRequest asyncRequest)

My API gateway runs on http://localhost:7000 and https://localhost:7001. 

When sending a request to the former, it works perfectly, when sending to the latter, i get the above error. The consul service discovery mechanism seems to work just fine when passing on http messages, but for some reason cannot do HTTPS. 

In addition, consul is set up to use http://consul:8500 (a docker container running consul), while the services can accept both HTTP and HTTPS messages. 

Has anyone else had this issue? I keep going round in circles and can't seem to figure it out.

**Comment by johha86** [comment]
@nemanjapyr had you tried run the API Gateway and services in a console for each project? Sometimes this kind of issues come up because to something related to the Docker Network between the containers.

**Comment by nemanjapyr** [comment]
hi @johha86, 

i tried to run only a single service, along with consul (in docker) and the API gateway running in console mode. this seems to work, even with consul exposed via http only (port 8500), and the API and underlying service exposing https. 

so it seems that your hunch was correct - but the question is, how does one then configure it so that this works when everything is in docker? they are all on the same docker network and seem to be able to see each other via http, just not https. 

if you've got any ideas for how to debug that it will be very useful?

**Comment by johha86** [comment]
Hi @nemanjapyr 
You are right about run everything in console mode. I did that test once. In my side I have a **500 error instead a 502 error** when I run everything with docker and docker composer. But, after some test I tried to use **Consul without ocelot**, I mean, just create a Web API project with a controller that works as an API Gateway, and inside the actions perform the Downstream call using the Service Discovery with Consul. _Note: Everything was running with docker and docker composer._

After that I realize that when I call the Consul Client inside the action at the first time **using async/await the client throw an exception**. But at the second time, the client response was correct with the information of all the services registered inside it. So, I decided perform pretty different approach. I tried to do not use async/await(DONT DO THIS IN PRODUCTION) to call the method in the client. In this case, everything was fine at first time and the next invocations.

From this point I decided to rollback and return to Ocelot with Service Discovery using Consul. In my first call to an address Postman shown me a 500 error, like in the begining, but this time I decided to not turn off the execution and try it again. The second, third and so on calls were fine, with **response 200**.

So, I guess that in some place inside ocelot the library do something similar to the test with async/await. But this is my explanation for my 500 error, but maybe give you a clue to solve you problem.

**Comment by nemanjapyr** [comment]
thanks for that @johha86 - unfortunately this doesn't seem to be making much of a difference on my side. 

the issue seems to be that, for whatever reason, when ocelot receives calls via HTTPS, it seems unable to route them onwards to the downstream services via consul service discovery. i've tried a number of different configurations and it seems to identify the correct services, and attempt to connect to them i get different variations of errors. 

when connecting to a downstream service with **http**, it shows this error: 

`Error connecting to downstream service, exception: System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.

---> System.IO.IOException: The handshake failed due to an unexpected packet format.`

when connecting with **https**, i get this instead: 

`Error connecting to downstream service, exception: System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.

---> System.Security.Authentication.AuthenticationException: The remote certificate is invalid according to the validation procedure.`

in the latter case, i've seen other issues suggesting the answer is to set 

`"DangerousAcceptAnyServerCertificateValidator": true,`

this makes no discernible difference in my case. 

it's a real head scratcher...

**Comment by goldmannyc** [comment]
This error normally indicated errors of sending https over http port. 

What downstream url ocelot received from consul when processing the request? Make sure ocelot sends https to https port and http to http port accordingly.  There might be an issue if your api services registers both http and https,  and ocelot just uses the https scheme on http, which could cause the above error. In my case I just enforces the Api services to register https to consul which solved the problem for the time being.

**Comment by nemanjapyr** [comment]
hi @goldmannyc , thanks for the answer. it does sound like it may be something along these lines. 

when you say: 

'What downstream url ocelot received from consul when processing the request? '

how does one determine this? i also thought it would be helpful to see how it is trying to redirect, but was unable to find the logs that would show what url it was actually sending the requests to. 

'There might be an issue if your api services registers both http and https, and ocelot just uses the https scheme on http, which could cause the above error'

Are you saying in the above that if some of the downstream services are http and other https, then ocelot will send https to all of them? Also - does this mean that if we access the ocelot API via https, that it will also automatically use https to access downstream services, even if they are all http?

**Comment by jlukawska** [comment]
How have you set up API Gateway to accept HTTPS messages on the docker container?

I've done a sample and it works for me:
Ocelot api (docker container, configured https with a cert configured)
Consul (docker container)
service app (docker container, http)
Requests with https to ocelot api return 200 in my sample.

**Comment by nemanjapyr** [comment]
Hi @jlukawska , 

I've generally set it up in a similar way, except the cert configured for Ocelot. I just have a self-signed cert for development purposes.

Otherwise it was: 

Ocelot API - docker container, https with a self signed cert
Consul  - in a docker container - just standard http on port 8500
Service app(s) - docker container (tried both http and https - getting different errors as described above)

The requests come in to ocelot via HTTPS, but I get Bad Gateway Errors (502) - either with issues decoding packets information, or around invalid certificates. 

Is there no way to set this up using a basic self-signed cert or must it be something more properly configured? 

Could you maybe share your docker compose file that you used in the sample and the ocelot.json so I can see how it all ties together? 

Btw - when I switch off service discovery and just use Ocelot with services defined in ocelot.json, it works perfectly with HTTPS on the gateway, and HTTP on the downstream services. 

Thanks,
Nemanja

**Comment by jlukawska** [comment]
Ok, for a summary, the problem is that when you call a https request and Consul returns you the proper ip and port, the url composed by Ocelot uses "https" instead of "http"? 

Could you show your ocelot.json? Do you have DownstreamScheme configured? 


I use self-signed certificate also and I used instructions from [here ](https://github.com/dotnet/dotnet-docker/blob/master/samples/host-aspnetcore-https.md) to set up https for a container. But as I see now, you have problems with a certificate when you try https request to get to https on downstream service. So, as I understand, it's not this issue.

**Comment by nemanjapyr** [comment]
Hi @jlukawska ,

Thanks for the quick response and your help with this. 

Yes - I *think* that may be the issue, though I don't know how to actually see the URL that Consul returns. 

Here is my docker-compose.override.yaml: 

    api.gateway:
        ports:
            - "7000:80"
            - "7001:443"
        environment: 
            - ASPNETCORE_ENVIRONMENT=$ENV
            - ASPNETCORE_URLS=$URLS
            - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/Gateway.Api.OS.pfx
            - ASPNETCORE_Kestrel:Certificates:Default:Password=$CERT_PWD
        volumes:
            - .:/https/

    consul:
        ports:
            - "8500:8500"
            
    app.svc:
        ports:
            - "8081:80"
        environment: 
            - ServiceConfig__serviceDiscoveryAddress=http://consul:8500
            - ServiceConfig__serviceAddress=http://app-svc:80
            - ServiceConfig__serviceName=app-svc
            - ServiceConfig__serviceId=app-svc-v1


The ocelot.json file looks like this: 

{
  "ReRoutes": [
    {
      "DownstreamPathTemplate": "/{everything}",
      "DownstreamScheme": "http",
      "ServiceName": "app-svc",
      "UpstreamPathTemplate": "/app-svc/{everything}",
      "RateLimitOptions": {
        "ClientWhitelist": [],
        "EnableRateLimiting": true,
        "Period": "1s",
        "PeriodTimespan": 1.0,
        "Limit": 3
      }
    }],
  "GlobalConfiguration": {
    "BaseUrl": "https://localhost:7001",
    "RateLimitOptions": {
      "ClientIdHeader": "ClientId",
      "QuotaExceededMessage": "Rate limit exceeded",
      "RateLimitCounterPrefix": "ocelot",
      "DisableRateLimitHeaders": false,
      "HttpStatusCode": 429
    },
    "ServiceDiscoveryProvider": {
      "Scheme": "http",
      "Host": "consul",
      "Port": 8500,
      "Type": "Consul"
    }
  }
}

So yes - I do have the downstream scheme set up for the service, and I do have the scheme set for Cosul as well. 

Can you see anything in here that stands out? 

Thanks,
Nemanja

**Comment by jlukawska** [comment]
Could you tell me what Ocelot version do you use? However, as I see in the latest code, the scheme is set simply from the route configuration (if it is set).
Consul doesn't return a url, it returns the (configured for a given service name) IP address and port. Ocelot combines it together with the scheme from the route configuration. 
When the log level is set to Debug, you will find the result url (and more useful information) in the ocelot api logs. I suggest you look at these logs (especially what is "Request starting" url and "Downstream url is" url).

**Comment by nemanjapyr** [comment]
Hi @jlukawska ,

The version of Ocelot I'm using is 16.0.1, which is also the version of the Ocelot.Provider.Consul package. 

<ItemGroup>
    <PackageReference Include="Ocelot" Version="16.0.1" />
    <PackageReference Include="MMLib.SwaggerForOcelot" Version="2.5.0" />
    <PackageReference Include="Ocelot.Provider.Consul" Version="16.0.1" />
</ItemGroup>

Having set the debug level to trace, I can see that Ocelot is transforming the URL into an https request for some reason. 

So using the example from my previous reply, the 'Downstream url' log entry shows: 

Downstream url is https://app-svc:80/api/Profile/calc/2c4d8e78-b39b-4eda-a690-2d46ee1e8776

Prior to this one, other logs I can see are: 

Upstream url path is /app-svc/api/Profile/calc/2c4d8e78-b39b-4eda-a690-2d46ee1e8776

And: 

downstream templates are /api/Profile/calc/2c4d8e78-b39b-4eda-a690-2d46ee1e8776

So it seems to be finding the templates and services properly, it's just that it's selecting to use https rather than http for the service, even though the actual URL is the http endpoint for the service itself. 

I am setting the downstream template on each of the services that it points to, so this is quite strange. The only thing that has https is the BaseUrl of the API gateway itself...

**Comment by jlukawska** [comment]
I'll take a closer look at your answer in the next week, but... if you use 16.0.1, you should have "Routes" word in ocelot.json, not "ReRoutes" (unless it's a typo?)

**Comment by nemanjapyr** [comment]
to be honest, i had 'routes' set before and was having some issues which were resolved by changing to reroutes. however, now that you said to change it, i did, leaving everything else in place and it seems to be working! 

so that seems to be what was causing it to mix them up. 

out of interest, what is the difference between using routes and reroutes that would cause it to do this?

**Comment by nemanjapyr** [comment]
hi @jlukawska ,

i seem to have spoken too soon... 

after merging the changes i tried on saturday into the dev branch, for some reason, i'm now getting a different error, but again only with service discovery. 

one of my services is called 'dbsync', and it has the following input in docker-compose: 

`dbsync:
        ports:
            - "8081:80"
        environment:
            - ServiceConfig:serviceDiscoveryAddress=$CONSUL_URL
            - ServiceConfig:serviceAddress=http://dbsync:80
            - ServiceConfig:serviceName=dbsync
            - ServiceConfig:serviceId=dbsync-v1`

The container name in the docker compose file is 'dbsync'. 

In the ocelot.json file, this service is defined with this code: 

{
      "DownstreamPathTemplate": "/{everything}",
      "DownstreamScheme": "http",
      // "ServiceName": "dbsync",
      "DownstreamHostAndPorts": [
        {
          "Host": "dbsync",
          "Port": 80
        }
      ],
      "UpstreamPathTemplate": "/dbsync/{everything}",
      "RateLimitOptions": {
        "ClientWhitelist": [],
        "EnableRateLimiting": true,
        "Period": "1s",
        "PeriodTimespan": 1.0,
        "Limit": 3
      }
    },

I have the 'service name' property commented out because when I use service discovery and name the service 'dbsync', which matches the service name in the environment variable being passed in, much the same way in previous posts. 

I now get a 500 error, with the following message in the ocelot logs: 

gateway                           | System.Net.Http.HttpRequestException: Cannot assign requested address
gateway                           |  ---> System.Net.Sockets.SocketException (99): Cannot assign requested address
gateway                           |    at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
gateway                           |    --- End of inner exception stack trace ---

It seems like an issue within the docker network, but unfortunately the logs don't indicate which URL it is trying to connect to, for some reason. 

However, when I comment out the service name as above, and instead use the host and port definition, which passes in the same url, i.e. http://dbsync:80, it works perfectly, and the downstream URL is shown in the logs, as expected: 

 Downstream url is http://dbsync/api/schema/pea?dbName=Northwind

This is a real head scratcher for me, not least because it seemed to be working with this exact configuration a couple of days ago...

**Comment by jlukawska** [comment]
> so that seems to be what was causing it to mix them up.

When you use ReRoutes instead of Routes in ocelot.json using 16.0.1 Ocelot version, the routes are not found at all and UnableToFindDownstreamRouteError appears then and I don't know how it had worked for you with different errors ;)

> 
> out of interest, what is the difference between using routes and reroutes that would cause it to do this?

This word was simply replaced, so the routes in ReRoutes section when using the latest ocelot versions will not be found.



"Cannot assign requested address" error when using docker often happens when trying to use "localhost" inside docker network. Have you check if the service is properly registered in Consul? E.g. check consul UI?

**Comment by nemanjapyr** [comment]
thanks for the quick reply as always @jlukawska . much appreciated.

Regarding the Routes / ReRoutes issue, makes complete sense. I will make sure to keep that in mind going forward. 

Regarding the network address issue, I did come across a few support tickets where this was the case, though from what I can tell, this is not happening here. I have attached a screen grab from the consul UI and it shows the service is accessible and it seems to be properly registered with the correct url. I've also got no mention of localhost anywhere in the setup, so it should be pointing to the right place. 

![image](https://user-images.githubusercontent.com/67321504/94566850-bc0dbe80-0262-11eb-825e-aef1d9986075.png)


The service address when I copy it to the clipboard is: 

_dbsync_ 

This is the network name of the service within docker. It also works when I pass the exact same address to Ocelot and skip using Consul. 

The code that I use to set up the connection to Consul is the following: 

`public static void RegisterConsulServices(this IServiceCollection services, ServiceConfig serviceConfig)
        {
            if (serviceConfig == null)
                return; // don't throw an exception when config is null, simply don't register for service discovery
                //throw new ArgumentNullException(nameof(serviceConfig));
            
            var consulClient = CreateConsulClient(serviceConfig);
            services.AddSingleton(serviceConfig);
            services.AddSingleton<IHostedService, ServiceDiscoveryHostedService>();
            services.AddSingleton<IConsulClient, ConsulClient>(p => consulClient);
        }

        private static ConsulClient CreateConsulClient(ServiceConfig serviceConfig)
        {
            return new ConsulClient(config =>
            {
                config.Address = serviceConfig.ServiceDiscoveryAddress;
            });
        }`

The serviceConfig object is created using the environment variables from docker compose in the following way: 

`public static ServiceConfig GetServiceConfig(this IConfiguration configuration)
        {
            if (configuration == null || configuration.GetChildren().All(i => i.Key != "ServiceConfig"))
                return null;
            
            var serviceConfig = new ServiceConfig
            {
                ServiceDiscoveryAddress = configuration.GetValue<Uri>("ServiceConfig:serviceDiscoveryAddress"),
                ServiceAddress = configuration.GetValue<Uri>("ServiceConfig:serviceAddress"),
                ServiceName = configuration.GetValue<string>("ServiceConfig:serviceName"),
                ServiceId = configuration.GetValue<string>("ServiceConfig:serviceId")
            };

            return serviceConfig;
        }`

**Comment by jlukawska** [comment]
Maybe check "$CONSUL_URL". E.g. try to replace it with the proper consul ip address?

**Comment by nemanjapyr** [comment]
I tried this, but the end result is the same - this is just a variable in the .env file, which just has the basic http://consul:8500 path. 

![image](https://user-images.githubusercontent.com/67321504/94689480-d3ae7b00-0326-11eb-8fd3-b525c09124cb.png)

as you can see in the docker override, i can set it explicitly and it still has the same issue. 

is there any way to get ocelot to log the url it's trying to call before it calls it? this seems to be crashing out before it does the downstream url trace log, so it's hard to see what the issue is. 

i also tried to bash into the ocelot docker container i'm running, and i can ping the dbsync service without any issues from there, which also makes sense given that it works when i set the url in ocelot explicitly. 

am i doing anything wrong in the consul registration process by any chance?

**Comment by jlukawska** [comment]
"consul" is not an IP address ;) I think it can be a problem with the docker networks and/or name resolution. I don't know how many networks do you use and which containers belong to which networks. I suggest to try to check IPs of the containers (ocelot api, consul and the service) and use them in the configurations, registrations etc. to see if the network names are resolved as you expect it.
It seems that the problem is not connecting to the downstream service, but connecting to the consul.

**Comment by nemanjapyr** [comment]
my bad - i misunderstood what you meant!

in terms of the docker network configuration, i have a single network that all the containers use to talk to each other, and in every other instance, i've been able to use the container name as the network address to reference them, including ocelot, sql server and the services themselves. 

i did try and get the ip address of the consul service and added it to the ocelot.json as well as the service registration url in the example above, but it's still showing the same thing. 

is there any way i can inspect the url ocelot gets back from consul and log it so i can maybe see what the issue is?

**Comment by jlukawska** [comment]
I don't know if Consul has such logs. You can use something like tcpdump to find these information.

**Comment by nemanjapyr** [comment]
Hi - sorry I don’t think I expressed myself clearly. 

It’s not the consul logs, it’s the Ocelot logs I’m looking for. 

In a previous example, Ocelot logged the downstream URL it was directing to, but with this new error, it seems to fail while trying to connect to the URL or while building it up. What I meant was how can we set logging in Ocelot so that it outputs the url it’s attempting to connect to before it executes the statement which falls over?

Does that make sense? 

Thanks - apologies for the lengthy thread. I really appreciate your time with this.

**Comment by jlukawska** [comment]
I suppose that the problem is with connecting to the consul and that's why you don't see the downstream url in the logs.

"Downstream url is ... " message is logged before sending the request to the downstream service.

**Comment by nemanjapyr** [comment]
I think you’re right - when I run it all locally, the service discovery works properly and there are no issues, but there’s something about the way that it tries to contact consul when going through docker that causes problems - though what it is I’m doing wrong specifically is mystifying at this stage. 

question - does the “ServiceDiscoveryProvider” section in the ocelot.json file do anything? I tried to comment it out and it seems to make no difference as I’m getting the exact same error. Is this something that used to be a thing but isn’t used anymore?

It specifies the consul details, but then each service has to provide the service discovery address anyway? 

btw - do you have a sample project by any chance that has a working configuration of this that uses docker? just a basic project with a fake downstream service that this will work on with the new version? i assume this must be a fairly common use case, but the only one i found was an old version on GitHub that uses 13.5 I think, and there are some differences - plus I struggle to get the thing to actually work in any case...

**Comment by jlukawska** [comment]
I've uploaded a simple sample [here](https://github.com/jlukawska/OcelotConsulDockerExample)

**Comment by nemanjapyr** [comment]
thanks very much! i'll take a look at this and compare to what I'm doing to see if this can help crack. 

much appreciated, as always

**Comment by nemanjapyr** [comment]
hi @jlukawska ,

apologies for the delay in getting back on this - i've only just now had a chance to look at your sample project. 

it worked perfectly on my end, and allowed me to get my code working as well. 

what appears to have been the issue, is that the "ServiceDiscoveryProvider" section in the ocelot.json was misplaced in my sample. i had it **outside** of the "GlobalConfiguration" section, which is why ocelot was struggling to reach consul to actually get the addresses of the downstream services! 

i did notice that you've got a different approach in your sample in that you don't have any registration code in the services themselves, but reference the service in the CONSUL_LOCAL_CONFIG environment setting on the Consul container itself.

This option also worked for me, though using the services themselves to self-register was also okay. Is there any specific reason why you'd take the one approach over the other? Just want to make sure we're setting it up in the best way. 

thanks a lot for all your help with this.

**Comment by jlukawska** [comment]
The simplest mistake is the hardest to see ;)

> i did notice that you've got a different approach in your sample in that you don't have any registration code in the services themselves, but reference the service in the CONSUL_LOCAL_CONFIG environment setting on the Consul container itself.
> 
> This option also worked for me, though using the services themselves to self-register was also okay. Is there any specific reason why you'd take the one approach over the other? Just want to make sure we're setting it up in the best way.

There are many ways to register services in Consul. It's only a simple example showing how the parts work together and I used the way of registration that is the most convenient and readable to me for this simple example.

> thanks a lot for all your help with this.

No problem :)
