### ISSUE TITLE
 Failing to ReRoutes leads to 404 when using UpstreamPath in get url

### ISSUE THREAD

**Issue by yashadsingh** [ThreeMammals/Ocelot#1327]
I have to implement Ocelot in my project. I was working around a sample project to get the basic structure/information/workflow of Ocelot. I am unable to hit the API via Ocelot API gateway. For reference I have added my sample project
[repos.zip](https://github.com/ThreeMammals/Ocelot/files/5146557/repos.zip)

**Comment by yashadsingh** [comment]
This one is resolved when I used "Routes" instead of "ReRoutes". But now I another issue. When I am trying to hit my Web API via gateway, it is saying 

This page isn’t working
localhost is currently unable to handle this request.
HTTP ERROR 500

Can any help?

**Comment by raman-m** [comment]
Sounds like a success story!

## 🤣
