### ISSUE TITLE
Ocelot APIGateway error 502 when running in docker containers

### ISSUE THREAD

**Issue by jinsaini** [ThreeMammals/Ocelot#1331]
Hi I am new to .net core/docker/ocelot so please forgive my basic knowledge regarding these technologies.
I have tried to create a test solution consisting of 2 microservices and an API gateway using .net core 3.1 and Ocelot 16.0.1

## Expected Behavior / New Feature
Ocelot 16.0.1 .net core 3.1
APIGateway should redirect upstream requests to downstream template

## Actual Behavior / Motivation for New Feature
when running Ocelot APIGateway in docker containers in docker desktop windows (with docker compose or separate containers) get a 502 error.
If API Gateway is run in debug in VS2019 IIS it works fine, only errors in docker container
Microservices are both available directly

Ocelot JSON:
{
  "Routes": [
    {
      "DownstreamPathTemplate": "/stockcheck",
      "DownstreamScheme": "http",
      "DownstreamHostAndPorts": [
        {
          "Host": "stocks.local",
          "Port": 30000
        }
      ],
      "UpstreamPathTemplate": "/companylist",
      "UpstreamHttpMethod": [ "Get" ]

    },
    {
      "DownstreamPathTemplate": "/stockcheck/GetStockPrice/{id}",
      "DownstreamScheme": "http",
      "DownstreamHostAndPorts": [
        {
          "Host": "stocks.local",
          "Port": 30000
        }
      ],
      "UpstreamPathTemplate": "/getstock/{id}",
      "UpstreamHttpMethod": [
        "Get"
      ]
    },
    {
      "DownstreamPathTemplate": "/currency/GetAllCountries",
      "DownstreamScheme": "http",
      "DownstreamHostAndPorts": [
        {
          "Host": "currency.local",
          "Port": 30001
        }
      ],
      "UpstreamPathTemplate": "/countries",
      "UpstreamHttpMethod": [
        "Get"
      ]
    },
    {
      "DownstreamPathTemplate": "/currency/GetAllCurrencies",
      "DownstreamScheme": "http",
      "DownstreamHostAndPorts": [
        {
          "Host": "currency.local",
          "Port": 30001
        }
      ],
      "UpstreamPathTemplate": "/currencies",
      "UpstreamHttpMethod": [
        "Get"
      ]
    },
    {
      "DownstreamPathTemplate": "/currency/Convert/{amount}/{from}/{to}",
      "DownstreamScheme": "http",
      "DownstreamHostAndPorts": [
        {
          "Host": "currency.local",
          "Port": 30001
        }
      ],
      "UpstreamPathTemplate": "/convert/{amount}/{from}/{to}",
      "UpstreamHttpMethod": [
        "Get"
      ]
    }
  ],
  "GlobalConfiguration": {
    "BaseUrl": "http://api.local:30002"
  }
}

Docker cmds to spin up containers (with and without network)
docker network create -d ics jsbridge
docker run --name jsapigateway --network jsbridge -d -p 30002:80 mshapigateway
docker run --name jscurrencyconverter --network jsbridge -d -p 30001:80 mshcurrencyconverter
docker run --name jsstockcheck --network jsbridge -d -p 30000:80 mshstockcheck
OR
docker run --name jsapigateway -d -p 30002:80 mshapigateway
docker run --name jscurrencyconverter -d -p 30001:80 mshcurrencyconverter
docker run --name jsstockcheck -d -p 30000:80 mshstockcheck

Please help, and many thanks in advance.

Jin

**Comment by jlukawska** [comment]
Hello,
publishing ports e.g. "-p 30001:80" is for Docker host only. So if you use 30001 in your ocelot.json, it will work only if the api gateway is running from the host. When the api gateway is running from the container, it communicates with other services in containers using 80 port and that port should be used in ocelot.json to work.

It is good to add some application logging to make finding problems easier. 502 status code may have many reasons and logs can help.

**Comment by jinsaini** [comment]
> Hello,
> publishing ports e.g. "-p 30001:80" is for Docker host only. So if you use 30001 in your ocelot.json, it will work only if the api gateway is running from the host. When the api gateway is running from the container, it communicates with other services in containers using 80 port and that port should be used in ocelot.json to work.
> 
> It is good to add some application logging to make finding problems easier. 502 status code may have many reasons and logs can help.

Hi, thanks for the reply, I have already fixed the issue and forgot to close but you are right, it was the ocelot downstream port I incorrectly configured. :)
