### ISSUE TITLE
Improve wording for catch-all routes

### ISSUE THREAD

**Issue by sliekens** [ThreeMammals/Ocelot#1332]
I found some paragraphs that seem to contradict each other in the routing documentation: <https://ocelot.readthedocs.io/en/latest/features/routing.html>

> Ocelot’s routing also supports a catch all style routing where the user can specify that they want to match all traffic.
> [...]
> **The catch all has a lower priority than any other Route. If you also have the Route below in your config then Ocelot would match it before the catch all.**
> [...]
> 0 is the lowest priority, Ocelot will always use 0 for /{catchAll} Routes and this is still hardcoded. After that you are free to set any priority you wish.
> [...]
> In the example above if you make a request into Ocelot on /goods/delete Ocelot will match /goods/delete Route. **Previously it would have matched /goods/{catchAll} (because this is the first Route in the list!)**.

The behavior I'm seeing is closer to what the last paragraph describes, which is that order matters when no Priority is explicitly assigned.

What's the expected behavior? What's the default priorty for routes without a catch-all token?

PS I'm using Ocelot v13.5.2 and I'm unable to upgrade for technical reasons.

**Comment by StevenLiekens** [comment]
I did a little more digging and I think my problem is that this route is not prioritized as a catch-all route?

❌`/goods/{catchAll}`

Only this route gets de-prioritized:

✔`/{catchAll}`

**Comment by StevenLiekens** [comment]
If someone can please confirm my suspicion then I can create a PR for the documentation to explain Priority for open-ended path templates.

**Comment by raman-m** [comment]
@sliekens 
What's your PR number?

**Comment by raman-m** [comment]
🆗 Steven, if you still believe this is an issue, then come back to us with PR. I agree this logic is quite unclear, and it will be hard to improve something in this [Priority](https://ocelot.readthedocs.io/en/latest/features/routing.html#priority) feature.
Maybe we could implement some advanced Priority route config validator adding more rules to [FileConfigurationFluentValidator](https://github.com/search?q=repo%3AThreeMammals%2FOcelot%20FileConfigurationFluentValidator&type=code) class.

For now, developers are able to change priority.

Please show us your strong intention to contribute, and we will reopen this issue.
