### ISSUE TITLE
 Not Found (404) Error with version 16.0.1

### ISSUE THREAD

**Issue by lianxue7851** [ThreeMammals/Ocelot#1338]
## Expected Behavior / New Feature
Reroute to the downstream path

## Actual Behavior / Motivation for New Feature
Any requests report a 404 error

> warn: Ocelot.DownstreamRouteFinder.Middleware.DownstreamRouteFinderMiddleware[0]
> requestId: 0HM2L4QLFA2EO:00000001, previousRequestId: no previous request id, message: DownstreamRouteFinderMiddleware setting pipeline errors. IDownstreamRouteFinder returned Error Code: UnableToFindDownstreamRouteError Message: Failed to match Route configuration for upstream path: /Test/HeaderTransform/GetHeaderInfo, verb: GET.
> warn: Ocelot.Responder.Middleware.ResponderMiddleware[0]
 ## Steps to Reproduce the Problem
### describe

> Hello, I recently upgraded the previously used version 14 to the current version 16. With the same configuration parameters, version 14 can be forwarded normally, but 404 appears in version 16, indicating that the correct downstream route cannot be found. May I ask whether version 16 has made some other modifications to version 14?

###   1.Ocelot config

> {
>   "ReRoutes": [
>     {
>       "UpstreamPathTemplate": "/Test/{controller}/{action}",
>       "DownstreamPathTemplate": "/{controller}/{action}", 
>       "DownstreamScheme": "http",
>       "DownstreamHostAndPorts": [
>         {
>           "Host": "localhost",
>           "Port": 6000
>         }
>       ],
>       "UpstreamHttpMethod": [ "POST", "PUT", "GET" ],
>       "AuthenticationOptions": {
>         "AuthenticationProviderKey": "OcelotKey",
>         "AllowedScopes": []
>       }
>     }
>   ],
>   "GlobalConfiguration": {
>     "BaseUrl": "http://localhost:5200/" 
>   }
> }

### System startup configuration
 

>  1.The system startup parameters and configuration parameters use the default Settings provided in the official documentation

## Specifications
  - Version:16.0.1 .net core3.1
  - Platform:Windows 
  - Subsystem:

**Comment by jlukawska** [comment]
Hello, change the word "ReRoutes" to "Routes" in ocelot.config.

**Comment by lianxue7851** [comment]
> Hello, change the word "ReRoutes" to "Routes" in ocelot.config.
Thank you very much for your answer. It solves my problem.
