### ISSUE TITLE
Don't get file in wwwroot in service 

### ISSUE THREAD

**Issue by vankhanhpr** [ThreeMammals/Ocelot#1339]
How to get file in wwwroot's forder . Try link  https://localhost:44336/salary/combohome/demo.xlsx not working for me. Help me please!
`{
      "DownstreamPathTemplate": "/api/salary/{catchAll}",
      "DownstreamScheme": "http",
      "DownstreamHostAndPorts": [
        {
          "Host": "localhost",
          "Port": 3003
        },
        {
          "Host": "localhost",
          "Port": 3007
        }
      ],
      "UpstreamPathTemplate": "/api/salary/{catchAll}",
      //"LoadBalancerOptions": { "Type": "RoundRobin" },
      "UpstreamHttpMethod": [ "Options", "Get", "Post", "Put", "Delete" ],
      "UpstreamPathTemplate": "/api/salary/combohome",
      "AuthenticationOptions": {
        "AuthenticationProviderKey": "TestKey",
        "AllowedScopes": []
      },
      "QoSOptions": {
        "ExceptionsAllowedBeforeBreaking": 1,
        "DurationOfBreak": 7200001,
        "TimeoutValue": 7200000

      },
      "RateLimitOptions": {
        "ClientWhitelist": [],
        "EnableRateLimiting": true,
        "Period": "10s",
        "PeriodTimespan": 1,
        "Limit": 10
      }
    },`

![Uploading image.png…](
![image](https://user-images.githubusercontent.com/22538732/92901214-812a1f00-f44a-11ea-9e31-9d15b8413800.png)

**Comment by raman-m** [comment]
Not Ocelot issue!
