### ISSUE TITLE
Ocelot not working with browser access..

### ISSUE THREAD

**Issue by normarclone** [ThreeMammals/Ocelot#1340]
Hi everyone! I'm new in Ocelot. I tried to implement some basic example from [https://github.com/catcherwong-archive/APIGatewayDemo](url), and Youtube.
I've seen them (Youtuber) accessing it (Ocelot example link) on browser but I can't do it (HTTP ERROR 502) whether I can access it by using postman.
Can anyone explain the reason to me??

  - Version: 16.0.1
  - Platform: .NetCore3.1

**Comment by jlukawska** [comment]
Hello, the first thing that might be a problem is that if you use the newest version of Ocelot in the older example, you should change the word "ReRoutes" to "Routes" in ocelot.json.

**Comment by normarclone** [comment]
Yes, I'd changed it

**Comment by jlukawska** [comment]
Could you add more details? What is "Ocelot example link"? What youtube tutorial do you mean?
It is good to add some application logging to check such problems.

**Comment by normarclone** [comment]
@jlukawska Here is the tutorial  [https://www.youtube.com/watch?v=hlUGZ6Hmv6s](url)  
the config
`"Routes": [
    {
      "DownstreamPathTemplate": "/api/values", //http://localhost:5002/api/values
      "DownstreamScheme": "https",
      "DownstreamHostAndPorts": [
        {
          "Host": "localhost",
          "Port": 5001
        }
      ],
      "UpstreamPathTemplate": "/getA",
      "UpstreamHttpMethod": [ "Get", "Options" ]
    },
    {
      "DownstreamPathTemplate": "/api/values",
      "DownstreamScheme": "http",
      "DownstreamHostAndPorts": [
        {
          "Host": "localhost",
          "Port": 5002
        }
      ],
      "UpstreamPathTemplate": "/getB",
      "UpstreamHttpMethod": [ "Get", "Options" ]
    }
  ],
  "GlobalConfiguration": {
    "BaseUrl": "https://localhost:5021/"
  }`
and the result
![image](https://user-images.githubusercontent.com/52033721/93324405-08f39d00-f840-11ea-85cc-7f16af5d7892.png)
but post man still okay 
![image](https://user-images.githubusercontent.com/52033721/93324527-3d675900-f840-11ea-979a-e26f166008e4.png)

**Comment by jlukawska** [comment]
The browser that you use is Edge Beta, am I right? Have you tried any other browser?

**Comment by normarclone** [comment]
Sure, chrome, firefox same :(

**Comment by jlukawska** [comment]
And can you find any errors/exceptions in the the application logs of the ocelot api? 
Does this problem also occur for http?

**Comment by normarclone** [comment]
Here! 
![image](https://user-images.githubusercontent.com/52033721/93545904-cb9c2600-f98b-11ea-9986-257c1852b332.png)

**Comment by jlukawska** [comment]
Here you requested https://localhost:5001 and you received 404. It is not the case from this issue. Please configure logs in your application on the information level and request the url that causes the problem.

**Comment by sharpn** [comment]
postman is probably ignoring the self signed cert for localhost, where as chrome will not

**Comment by redplane** [comment]
Any solution for this ? It still happens in 2022
