### ISSUE TITLE
How to access DownstreamContext in the AuthorisationMiddleware.

### ISSUE THREAD

**Issue by pateljeel** [ThreeMammals/Ocelot#1345]
## Expected Behavior / New Feature
I was using the AuthorisationMiddleware in OcelotPipelineConfiguration to intercept requests and only allow certain roles with custom logic. (https://github.com/ThreeMammals/Ocelot/issues/746). Here is what the code looked like.
```
            var configuration = new OcelotPipelineConfiguration
            {
                AuthorisationMiddleware = async (ctx, next) =>
                    {
                        if (this.Authorize(ctx))
                        {
                            await next.Invoke();
                        }
                        else
                        {
                            ctx.Errors.Add(new UnauthorisedError($"Fail to authorize. The user does not have the permission to access the endpoint."));
                        }
                    }
            };
```
``` 
private bool Authorize(DownstreamContenxt ctx)
{
            if (ctx.DownstreamRoute.AuthenticationOptions.AuthenticationProviderKey == null)
            {
                return true;
            }

            var auth = false;

            // Claims of the jwt token
            var claims = ctx.User.Claims.ToArray();

            // Claims listed on the route.
            var requiredClaims = ctx.DownstreamReRoute.RouteClaimsRequirement;
.
.
.

```

However, I cant use `DownstreamContext` anymore because the AuthorisationMiddleware takes in an `HttpContext`. How can i access properties such as AuthenticationOptions, RouteClaimsRequirements so my code works?

**Comment by eeefbal** [comment]
@pateljeel hi,
i agree with you and also have a problem about multiple RouteClaimsRequirement objects.

**Comment by Savio-Fernandes-Git** [comment]
> 

https://stackoverflow.com/questions/65649254/how-to-allow-multiple-roles-to-access-route-through-routeclaimsrequirement

**Comment by vadsemenov** [comment]
` private bool Authorize(HttpContext ctx)
        {
           // var aa = ctx.Items.DownstreamRoute();
            if (string.IsNullOrWhiteSpace(ctx.Items.DownstreamRoute()?.AuthenticationOptions?.AuthenticationProviderKey)) return true;
            else
            {

                bool auth = false;
                Claim[] claims = ctx.User.Claims.ToArray<Claim>();
                Dictionary<string, string> required = ctx.Items.DownstreamRoute().RouteClaimsRequirement;
                Regex reor = new Regex(@"[^,\s+$ ][^\,]*[^,\s+$ ]");
                MatchCollection matches;

                Regex reand = new Regex(@"[^&\s+$ ][^\&]*[^&\s+$ ]");
                MatchCollection matchesand;
                int cont = 0;
                foreach (KeyValuePair<string, string> claim in required)
                {
                    matches = reor.Matches(claim.Value);
                    foreach (Match match in matches)
                    {
                        matchesand = reand.Matches(match.Value);
                        cont = 0;
                        foreach (Match m in matchesand)
                        {
                            foreach (Claim cl in claims)
                            {
                                if (cl.Type == claim.Key)
                                {
                                    if (cl.Value == m.Value)
                                    {
                                        cont++;
                                    }
                                }
                            }
                        }
                        if (cont == matchesand.Count)
                        {
                            auth = true;
                            break;
                        }
                    }
                }
                return auth;
            }
        }
`

**Comment by NihadAxund** [comment]
Not wokring in GET mehtod only working POST
