### ISSUE TITLE
Docs/Kubernetes provider are wrong

### ISSUE THREAD

**Issue by shawnwildermuth** [ThreeMammals/Ocelot#1346]
## Expected Behavior / New Feature
In the docs, it explains that the type should be "kube" but that means that the code will fallback to the consul type (as evidenced by the error messages saying that there is something wrong with consul).  

## Actual Behavior / Motivation for New Feature
When I setup Kubernetes with this configuration snippet:

```
	"GlobalConfiguration": {
		"BaseUrl": "http://localhost:5999/",
		"ServiceDiscoveryProvider": {
			"Host": "kubernetes.docker.internal",
			"Port": 6443,
			"Token": "XXX",
			"Namespace": "default",
			"Type": "kube"
		}
	}
```

It fails with a consul error.

## Steps to Reproduce the Problem

  1. Setup Kubernetes provider.
  2. Use kube as the service type (see above).
  3. Get consul error instead.

## Recommendation 

Either change the docs or change the name of the class for the type to:

```
 "Type": "KubernetesServiceDiscoveryProvider"
```

My preference would be to change the provider name to "Kube" as it would be an internal fix. Alternatively, have the code look at the type and search for the type name, the name + ServiceDiscoveryProvider, which would be useful to not have to have the provider names supershort. 

I am happy to do a PR for these changes. Let me know. I already dug through the source to find the problem.

## Specifications

  - Version: 16.0.1
  - Platform: Kubernetes (docker desktop)
  - Subsystem:

**Comment by raman-m** [comment]
Hi Shawn!
This issue was fixed in version [23.0](https://github.com/ThreeMammals/Ocelot/releases/tag/23.0.0)!
See PR https://github.com/ThreeMammals/Ocelot/pull/1954
