### ISSUE TITLE
Version16.0.0,16.0.1 Error Code: UnableToFindDownstreamRouteError

### ISSUE THREAD

**Issue by yunjie-yao** [ThreeMammals/Ocelot#1349]
**Same .json file,when i user version 15.0.7,it works;but when i user version 16,it doesn't work!**

warn: Ocelot.Responder.Middleware.ResponderMiddleware[0]
      requestId: 0HM352O0406QP:00000001, previousRequestId: no previous request id, 
message: Error Code: **UnableToFindDownstreamRouteError** 
Message: Failed to match Route configuration for upstream path: /t/topic, verb: GET.
 errors found in ResponderMiddleware. 
Setting error response for request path:/t/topic, request method: GET

The .josn file
```
{
  "ReRoutes": [
    {
      "DownstreamPathTemplate": "/api/{everything}",
      "DownstreamScheme": "http",
      "DownstreamHostAndPorts": [
        {
          "Host": "localhost",
          "Port": 1001
        }
      ],
      "UpstreamPathTemplate": "/good/{everything}",
      "UpstreamHttpMethod": [ "Get", "Post" ]
    },
    {
      "DownstreamPathTemplate": "/api/{everything}",
      "DownstreamScheme": "http",
      "DownstreamHostAndPorts": [
        {
          "Host": "localhost",
          "Port": 8081
        }
      ],
      "UpstreamPathTemplate": "/t/{everything}",
      "UpstreamHttpMethod": [ "Get", "Post" ]
    }
  ],
  "GlobalConfiguration": {

  }
}
```

**Comment by jlukawska** [comment]
see #1338

**Comment by yunjie-yao** [comment]
**change the word "ReRoutes" to "Routes" in ocelot.config.**
