### ISSUE TITLE
Can common config be written in "GlobalConfiguration"

### ISSUE THREAD

**Issue by abhiphirke** [ThreeMammals/Ocelot#1350]
## Expected Behavior / New Feature
The documentation states:   The Global configuration is a bit hacky and allows overrides of Route specific settings. It’s useful if you don’t want to manage lots of Route specific settings.

Based on this, my understanding is that if the following few configurations are common for all the entries in `ReRoutes`, then the following way of putting it together should work:

    "GlobalConfiguration": {
        "DownstreamScheme": "https",
        "DangerousAcceptAnyServerCertificateValidator": true,
        "QoSOptions": {
            "TimeoutValue": 60000
        }
    }

## Actual Behavior / Motivation for New Feature
It is not working at my end. Looks like one of the possibilities:
1. My understanding is wrong: Then documentation should be made more explanatory.
2. My understanding is right: Ocelot may have some problem. Since this configuration otherwise (if I repeat these in each entry in `ReRoutes`) has been working for 20 services that my Ocelot instance is serving.

In either case, please help!

**Comment by fauresco** [comment]
I agree with @abhiphirke. After reading the docs I have thought that it was possible to use "AddHeadersToRequest" inside "GlobalConfiguration" in order to add common headers to all requests but it did not work.

**Comment by nedimg** [comment]
Any updates on this? This would be a very nice feature to have...

**Comment by gao-artur** [comment]
Looks like `GlobalConfiguration` section is limited for specific scenarios. Check [this file](https://github.com/ThreeMammals/Ocelot/blob/def55b3c3c43688d38c40841b922ba2544cc663a/src/Ocelot/Configuration/File/FileGlobalConfiguration.cs) to see what can be configured via `GlobalConfiguration`. But you can extend it with using `PostConfigure` trick. Check [my answer](https://stackoverflow.com/a/63601248/2557855) on SO for example.

**Comment by abhiphirke** [comment]
> Looks like `GlobalConfiguration` section is limited for specific scenarios. Check [this file](https://github.com/ThreeMammals/Ocelot/blob/def55b3c3c43688d38c40841b922ba2544cc663a/src/Ocelot/Configuration/File/FileGlobalConfiguration.cs) to see what can be configured via `GlobalConfiguration`. But you can extend it with `PostConfigure` trick. Check [my answer](https://stackoverflow.com/a/63601248/2557855) on SO for example.

I tried with the options supported in `FileGlobalConfiguration`, specifically `DownstreamScheme` and `QoSOptions`, but in vain. 
I created global configuration like this:

    "GlobalConfiguration": {
        "QoSOptions": { "TimeoutValue": 30000 },
        "DownstreamScheme": "https"
    }
Am I missing something here?

Secondly, Your answer on SO is nice but it'd increase my service load time. Besides, if I need to perform conversion at startup, then I'd prefer to store the configuration in a CSV since it is easier to manage and can be edited in excel.
AFAIK, Ocelot does not support that. Or does it?
Please let me know.

**Comment by john-larson** [comment]
@TomPallister Documentation seems to imply that every property in the routes can be overridden in the GlobalConfiguration section. Could you please update this part in order to reflect the current situation? Or is there any work in progress to make this happen?

**Comment by raman-m** [comment]
Dear @abhiphirke,
### You have the right to reopen this issue in the future if you come with a PR ready
