### ISSUE TITLE
Ocelot overides System.Text.Json parser and uses Newtonsoft

### ISSUE THREAD

**Issue by neetra** [ThreeMammals/Ocelot#1351]
## Expected Behavior / New Feature
When try using ocelot, Newtonsoft parser is used, but i want to use System.text.json

## Steps to Reproduce the Problem

  1.
  1.
  1.

## Specifications

  - Version:
  - Platform:
  - Subsystem:

**Comment by marciocristian** [comment]
It happens to me too. But when I try to use Newtonsoft parser instead, doesn't work either returning to me always the default value.

**Comment by neetra** [comment]
@marciocristian  I found this fix by adding system.text.json input and output formatters to Startup.cs in asp net core

**Comment by marciocristian** [comment]
> @marciocristian I found this fix by adding system.text.json input and output formatters to Startup.cs in asp net core

ty

**Comment by raman-m** [comment]
@neetra @marciocrmendes 
Hello, Oceloters!
Say Yahooo! 😉 
Soon, you will be able to remove/add any DI services including Newtonsoft & TextJson.
Reopen! 🎉
