### ISSUE TITLE
使用Ocelot网关时，请求接口服务第一次404，第二次请求200成功

### ISSUE THREAD

**Issue by weiwoducui** [ThreeMammals/Ocelot#1355]
## Actual Behavior / Motivation for New Feature
我创建了一个网关，几个api接口，当我使用轮询方式时，
  "Type": "PollConsul", //Consul为默认类型，PollConsul是轮询状态
      "PollingInterval": 100 //轮询时间间隔以毫秒为单位
就好出现第一次请求是404，第二次200

我使用的是.Net Core 3.1,在ConfigureServices中配置
 services.AddOcelot(new ConfigurationBuilder().AddJsonFile("OcelotConfiguration.json", false,true).Build()).AddPolly().AddConsul();
在Configure中配置 app.UseOcelot().Wait();

我在Api节点的配置
 public static void RegisterConsul(this IConfiguration configuration)
        {
            //创建Consul客户端
            ConsulClient client = new ConsulClient(c => {
                c.Address = new Uri("http://10.137.210.187:8500/");
                c.Datacenter = "dc1";
            });
            //重命令行中获取 ip port weight(权重) 目的是重复反向代理
            string ip = "10.137.36.85";
            int port = 6001;
            //当为空时权重为 10
            int weight = 10;
            client.Agent.ServiceRegister(new AgentServiceRegistration()
            {
                ID = "ServiceWebApiPod1",//唯一的
                Name = "api",//服务组名称
                Address = ip,//ip需要改动
                Port = port,//不同实例
                Tags = new string[] { weight.ToString() }, //权重设置
                Check = new AgentServiceCheck() //健康检测
                {
                    Interval = TimeSpan.FromSeconds(12), //每隔多久检测一次
                    HTTP = $"http://{ip}:{port}/api/Health/get", //检测地址
                    Timeout = TimeSpan.FromSeconds(5), //多少秒为超时
                    Status = HealthStatus.Passing,//注册时初始化状态为通过
                    DeregisterCriticalServiceAfter = TimeSpan.FromSeconds(60) //在遇到异常后关闭自身服务通道
                }
            });
        }
现在我怀疑是轮询的机制有问题导致第一次没有请求到Consul的地址

## Steps to Reproduce the Problem
 //api接口配置
 { //匹配下游的WebApiPod服务的接口地址
      "DownstreamPathTemplate": "/api/{url}", //下游服务器请求路由模板
      "DownstreamScheme": "http",
      "UpstreamPathTemplate": "/api/{url}",
      "UpstreamHttpMethod": [ "Get", "Post" ],
      "ServiceName": "api",
      //"Priority": 0,//优先级，0最低
      "RateLimitOptions": { //限流全局配置
        "ClientWhitelist": [], // 白名单(在请求头中包含ClientId=admin或者admin1的请求不受限流控制)
        "EnableRateLimiting": true, // 是否启用限流
        "Period": "1m", // 统计时间段：1s, 5m, 1h, 1d
        "PeriodTimespan": 5, // 多少秒之后客户端可以重试
        "Limit": 50 // 在统计时间段内允许的最大请求数量
      },
      //"AuthenticationOptions": { //JWT权限验证参数
      //  "AuthenticationProviderKey": "BenBearer", //与业务代码中的默认架构相同
      //  "AllowedScopes": []
      //},
      "LoadBalancerOptions": { //负载均衡
        "Type": "LeastConnection" //LeastConnection
      }
    },
    { //匹配下游的WebApiPod服务的接口地址
      "DownstreamPathTemplate": "/api1/{url}", //下游服务器请求路由模板
      "DownstreamScheme": "http",
      "UpstreamPathTemplate": "/api1/{url}",
      "UpstreamHttpMethod": [ "Get", "Post" ],
      "ServiceName": "api1",
      //"Priority": 0,//优先级，0最低
      "RateLimitOptions": { //限流全局配置
        "ClientWhitelist": [], // 白名单(在请求头中包含ClientId=admin或者admin1的请求不受限流控制)
        "EnableRateLimiting": true, // 是否启用限流
        "Period": "1m", // 统计时间段：1s, 5m, 1h, 1d
        "PeriodTimespan": 5, // 多少秒之后客户端可以重试
        "Limit": 50 // 在统计时间段内允许的最大请求数量
      },
      //"AuthenticationOptions": { //JWT权限验证参数
      //  "AuthenticationProviderKey": "BenBearer", //与业务代码中的默认架构相同
      //  "AllowedScopes": []
      //},
      "LoadBalancerOptions": { //负载均衡
        "Type": "LeastConnection" //LeastConnection
      }
    },
 // 与Consul交互的配置
  "ServiceDiscoveryProvider": { //Consul配置
      //"Scheme": "https",
      "Host": "10.137.210.187",
      "Port": 8500
      "Type": "PollConsul", //Consul为默认类型，PollConsul是轮询状态
      "PollingInterval": 100 //轮询时间间隔以毫秒为单位
    },

## Specifications

  - Version: 15.0.7
  - Platform:
  - Subsystem:

**Comment by zcgg2zhmm** [comment]
我用k8s的时候，也是这样，第一次的时候，它要去k8s同步所有可用endpoint列表，第二次正好同步好了，于是成功了。
consul应该也是这样，仅供参考！！

**Comment by raman-m** [comment]
From China with love!
