### ISSUE TITLE
Advanced route aggregation/json batching

### ISSUE THREAD

**Issue by HaydnDias** [ThreeMammals/Ocelot#1357]
## New Feature/Pointers
Looking at creating a custom kind of aggregate/delegated handler to act as something similar to [Microsoft Graph Json Batching](https://docs.microsoft.com/en-us/graph/json-batching)

Not expecting this as a feature/development done inside ocelot (although I think it'd be a really cool feature), just looking for potential pointers as I'm unfamiliar with the ocelot codebase.

Requirements I have are things like parsing the batch request and using the ocelot downstream route matching with the authorization(scope matching) etc so we can still flow it through the ocelot pipeline as a batched request and return a batched result with headers, status codes and data included in the return body per request.

## Motivation for New Feature/Pointers
Being able to batch requests and let the gateway handle the distribution of requests would aid in complexity as well as allowing us to potentially chain requests together. 

Route aggregation is a cool feature, but very limited by design, this would almost be an expansion of that.

**Comment by gao-artur** [comment]
I have implemented same behavior in custom middleware. This middleware should be registered before `DownstreamRouteFinderMiddleware`.

```
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Net.Mime;
using System.Threading.Tasks;

using ApiGateway.Extensions;

using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.WebUtilities;

using Newtonsoft.Json;

using Ocelot.Logging;
using Ocelot.Middleware;

using MediaTypeHeaderValue = System.Net.Http.Headers.MediaTypeHeaderValue;

namespace ApiGateway.Batch
{
    public class BatchMiddleware : OcelotMiddleware
    {
        private const string RequestName = "RequestName";

        private readonly RequestDelegate _next;

        public BatchMiddleware(
            RequestDelegate next,
            IOcelotLoggerFactory loggerFactory)
            : base(loggerFactory.CreateLogger<BatchMiddleware>())
        {
            _next = next;
        }

        public async Task Invoke(HttpContext httpContext)
        {
            var batchRequests = await httpContext.Request.DeserializeArrayAsync<BatchRequestItem>();

            var requestTasks = await FireRequests(httpContext, batchRequests);

            var responseContexts = await Task.WhenAll(requestTasks);

            var batchResponsesTasks = responseContexts.Select(CreateResponseItem);

            var batchResponses = await Task.WhenAll(batchResponsesTasks);

            var jsonBatchResponses = JsonConvert.SerializeObject(batchResponses);

            var stringContent = new StringContent(jsonBatchResponses)
            {
                Headers = { ContentType = new MediaTypeHeaderValue(MediaTypeNames.Application.Json) }
            };

            var newDownstreamResponse = new DownstreamResponse(
                stringContent,
                HttpStatusCode.OK,
                new List<KeyValuePair<string, IEnumerable<string>>>(),
                HttpStatusCode.OK.ToString());

            httpContext.Items.UpsertDownstreamResponse(newDownstreamResponse);
        }

        private async Task<Task<HttpContext>[]> FireRequests(
            HttpContext httpContext,
            IList<BatchRequestItem> batchRequests)
        {
            var tasks = new Task<HttpContext>[batchRequests.Count];

            for (var i = 0; i < batchRequests.Count; i++)
            {
                var request = batchRequests[i];

                var newHttpContext = await CreateHttpContext(httpContext, request);

                newHttpContext.Items.Add("RequestId", httpContext.Items["RequestId"]);

                newHttpContext.Items.SetIInternalConfiguration(httpContext.Items.IInternalConfiguration());

                tasks[i] = FireRequest(newHttpContext); // do not await here
            }

            return tasks;
        }

        private async Task<HttpContext> CreateHttpContext(HttpContext source, BatchRequestItem request)
        {
            var target = new DefaultHttpContext();

            // copy
            foreach (var (key, value) in source.Request.Headers)
            {
                target.Request.Headers.TryAdd(key, value);
            }

            target.Request.Host = source.Request.Host;
            target.Request.PathBase = source.Request.PathBase;
            target.Request.Protocol = source.Request.Protocol;
            target.Request.Query = source.Request.Query;
            target.Request.QueryString = source.Request.QueryString;
            target.Request.Scheme = source.Request.Scheme;
            target.Request.IsHttps = source.Request.IsHttps;
            target.Request.RouteValues = source.Request.RouteValues;
            target.Connection.RemoteIpAddress = source.Connection.RemoteIpAddress;
            target.RequestServices = source.RequestServices;

            // set
            target.Request.ContentType = MediaTypeNames.Application.Json;
            target.Request.Body = await request.Body.ToStream();
            target.Request.Method = request.Method;
            target.Request.Path = GetNormalizedPath(request.Url);
            target.Request.QueryString = GetQueryString(request.Url);

            target.Items[RequestName] = request.Name;

            return target;
        }

        private string GetNormalizedPath(string path)
        {
            var relative = path.StartsWith('/') ? path : $"/{path}";

            var parsed = relative.Split('?', StringSplitOptions.RemoveEmptyEntries);

            return parsed.First();
        }

        private QueryString GetQueryString(string path)
        {
            var parsed = path.Split('?', StringSplitOptions.RemoveEmptyEntries);

            if (parsed.Length > 1)
            {
                return new QueryString("?" + parsed.Last());
            }

            return new QueryString();
        }

        private async Task<HttpContext> FireRequest(HttpContext httpContext)
        {
            await _next.Invoke(httpContext);
            return httpContext;
        }

        private async Task<BatchResponseItem> CreateResponseItem(HttpContext responseContext)
        {
            BatchResponseItem response;

            var errors = responseContext.Items.Errors();

            if (errors.Any())
            {
                var error = errors.First();

                response = new BatchResponseItem
                {
                    Name = (string)responseContext.Items[RequestName],
                    HttpCode = error.HttpStatusCode,
                    StatusDescription = ReasonPhrases.GetReasonPhrase(error.HttpStatusCode)
                };
            }
            else
            {
                var downstreamResponse = responseContext.Items.DownstreamResponse();

                if (!downstreamResponse.StatusCode.IsSuccessStatusCode())
                {
                    response = new BatchResponseItem
                    {
                        Name = (string)responseContext.Items[RequestName],
                        HttpCode = (int)downstreamResponse.StatusCode,
                        StatusDescription = downstreamResponse.ReasonPhrase,
                        Body = await downstreamResponse.Content.ReadAsStringAsync()
                    };
                }
                else
                {
                    var jsonBody = await downstreamResponse.Content.ReadAsStringAsync();

                    var body = string.IsNullOrEmpty(jsonBody)
                                   ? null
                                   : JsonConvert.DeserializeObject(jsonBody);

                    response = new BatchResponseItem
                    {
                        Name = (string)responseContext.Items[RequestName],
                        HttpCode = (int)downstreamResponse.StatusCode,
                        StatusDescription = downstreamResponse.ReasonPhrase,
                        Body = body
                    };
                }
            }

            return response;
        }
    }
}
```

```
    public static class Extensions
    {
        public static async Task<IList<T>> DeserializeArrayAsync<T>(this HttpRequest httpRequest)
        {
            return await httpRequest.Body.DeserializeArrayAsync<T>();
        }

        public static async Task<IList<T>> DeserializeArrayAsync<T>(this Stream stream)
        {
            using var streamReader = new HttpRequestStreamReader(stream, Encoding.UTF8);

            using var jsonReader = new JsonTextReader(streamReader);

            var json = await JArray.LoadAsync(jsonReader);

            return json.ToObject<List<T>>();
        }

        public static async Task<Stream> ToStream(this string body)
        {
            if (string.IsNullOrEmpty(body))
            {
                return null;
            }

            var stream = new MemoryStream();
            var writer = new StreamWriter(stream);
            await writer.WriteAsync(body);
            await writer.FlushAsync();
            stream.Position = 0;

            return stream;
        }
    }
```

```
    public class BatchRequestItem
    {
        public string Name { get; set; }

        public string Url { get; set; }

        public string Method { get; set; }

        public string Body { get; set; }
    }

    public class BatchResponseItem
    {
        public string Name { get; set; }

        public int HttpCode { get; set; }

        public string StatusDescription { get; set; }

        public object Body { get; set; }
    }

**Comment by HaydnDias** [comment]
@gao-artur Wow thank you, that looks great, I think we could make that work for us with a few tweaks, amazing work.

**Comment by raman-m** [comment]
Guys, why not to contribute?

**Comment by raman-m** [comment]
> act as something similar to [Microsoft Graph Json Batching](https://docs.microsoft.com/en-us/graph/json-batching)

Interesting!...
@ggnaegi What about this functionality?

**Comment by HaydnDias** [comment]
@raman-m I no longer use Ocelot, as it appeared abandoned after the announcement of YARP, I think it's been about 3yrs since I was last involved in a project with it.

I notice that the project seems to have picked up again! What's the plans/future for Ocelot? I may look at contributing in the future as 4-5 years ago when using this it was instrumental, and afaik nothing has really taken its place, YARP is very cool, but requires implementing a lot of the functionality yourself (that ocelot handles). Has Ocelot been rebuilt around YARP/any plans to do so? I could envision it being built on top of YARP, or extending it rather.

**Comment by ggnaegi** [comment]
Hello @HaydnDias we have reused some yarp ideas yes, but we can't follow the yarp logic, since the Ocelot logic is request based and yarp on some aspects is following a more static approach. As an example, yes you can use the rate limiter policies dynamically, referencing them in the clusters configuration, but you need to instantiate them first during startup. Delegating handlers are an Ocelot core functionality but they can't be ported that easily to Yarp. I have myself implemented a test project with yarp, oidc and consul, and I had some issues with delegating handlers. Yes Yarp supports SSE, is optimized, very performant, but as you wrote it's bring-your-own-code. @raman-m As for the functionality, yes, it's interesting indeed.

**Comment by raman-m** [comment]
@HaydnDias commented [on Mar 27](https://github.com/ThreeMammals/Ocelot/issues/1357#issuecomment-2022949551)

> I no longer use Ocelot, as it appeared abandoned after the announcement of YARP, I think it's been about 3yrs since I was last involved in a project with it.

It’s indeed disheartening to learn that Ocelot is no longer in use. The project’s journey seems to have encountered some challenges. As you mentioned, Tom made a significant project management mistake and an architecture decision that didn’t pan out well in 2020. [It appears that after realizing these missteps, development and management came to a halt in the latter part of that year](https://github.com/ThreeMammals/Ocelot/issues/1539).

Reflecting on such experiences can be valuable for future endeavors. Perhaps there are lessons to be learned from Ocelot’s trajectory.

---
> I notice that the project seems to have picked up again! 

In 2023, I became the member of the organization, and now, in 2024, I am leading this project. Rest assured, everything is on track! The project is no longer abandoned.

----
> What's the plans/future for Ocelot?

“The future of Ocelot hinges on the activity of our vibrant community. While I anticipate steady growth, it may not reach the heights seen before 2020. However, remember that each contributor plays a crucial role in shaping Ocelot’s destiny. For more insights into our development and plans, check out our Release Notes. Happy reading!

----
> I may look at contributing in the future as 4-5 years ago when using this it was instrumental, and afaik nothing has really taken its place, YARP is very cool, but requires implementing a lot of the functionality yourself (that ocelot handles).

I won’t pester you every month with pleas for contributions, but you’ll always have the opportunity to contribute, just like any regular GitHub user. To get started, **fork our repository** to signal your intention to make a difference. That’s the crucial first step

----
> Has Ocelot been rebuilt around YARP/any plans to do so?

**No!** Why would we rebuild using YARP? To “kill” the project or waste time? It seems there might be some misunderstanding about YARP’s architecture compared to Ocelot’s. Gui [provided an explanation](https://github.com/ThreeMammals/Ocelot/issues/1357#issuecomment-2023643738) that sheds light on the differences.

That’s an interesting question. Why did you ask it? Perhaps you’re curious about the motivations behind such a move. Unlike Tom’s approach in 2020 when he talked much to Microsoft managers, I prefer a more measured and pragmatic approach as the project coordinator.

----
> I could envision it being built on top of YARP, or extending it rather.

We won’t pursue that path! Tom has entrusted me with full rights to manage this project. Ocelot’s evolution will take a distinct trajectory. Honestly, as a team, we aren’t overly concerned about YARP’s future. It’s puzzling why you’re so keen on expressing your YARP affection within the Ocelot repository.

**Comment by raman-m** [comment]
@ggnaegi commented [on Mar 27](https://github.com/ThreeMammals/Ocelot/issues/1357#issuecomment-2023643738):
> As for the functionality, it's interesting indeed.

🆗 I will keep this issue open. But I have no idea who and how will deliver this Multiplexer feature...
But it would be good to have the feature in the list.

**Comment by HaydnDias** [comment]
@raman-m Please don't misunderstand me, I'm just catching up on the project status, 4 years ago there were discussions around potentially rebasing on YARP, I remember the configs being changed to more closely match YARPs, I'm not expressing affection at all, it was a simple question.

**Comment by raman-m** [comment]
@HaydnDias 
Will you contribute to deliver this feature?

**Comment by raman-m** [comment]
>@HaydnDias commented [on Apr 2](https://github.com/ThreeMammals/Ocelot/issues/1357#issuecomment-2032177830)

👌 Let us know when you have some free time for OSS Ocelot fun! 😉 

Please note that an issue for which a PR has been opened will be accepted automatically❕

**Comment by raman-m** [comment]
Dear @HaydnDias,
### You have the right to reopen this issue in the future if you come with a PR ready
