### ISSUE TITLE
Ocelot eureka sample not work

### ISSUE THREAD

**Issue by niufwshd** [ThreeMammals/Ocelot#1359]
## Expected Behavior / New Feature
    Ocelot eureka configuration ok,and http://localhost:5000/NCORERAT/Category can return string content

## Actual Behavior / Motivation for New Feature
    http://localhost:5000/NCORERAT/Category  return 404 not found
  but   http://localhost:5000/NCORERAT/api/Category work 
## Steps to Reproduce the Problem

  1.
  1.
  1.

## Specifications

  - Version:
  - Platform:
  - Subsystem:

**Comment by raman-m** [comment]
I agree that Eureka sample is outdated.
But the problem is Who will upgrade this sample solution?
Will you @niufwshd contribute to update the sample?
If Yes, reply to this thread and I'll reopen the issue...

**Comment by niufwshd** [comment]
eureka stack is not popular for a  few years in china as well as .net microservice。 spring cloud alibaba is preferred。so this sample is not essential。Thank u @raman-m very much！

**Comment by raman-m** [comment]
I don't care about China.
