### ISSUE TITLE
Prepended Middleware Is Being Ignored On The Request finalization.

### ISSUE THREAD

**Issue by JakubSlonka** [ThreeMammals/Ocelot#1369]
Hello,

I have found out strange behaviour, when I tried to prepend middleware before Ocelot in request pipeline.

## Context
Currently Iam working on Hybrid GraphQl-Ocelot-Gateway. 
My idea was to use Ocelot for routing and to use GraphQL for object property manipulation of the final DTO.

The request chain should be follwing GraphQl Middleware -> Ocelot Middleware -> Backend Services

This issue occurs with all middlewares that are being prepended before ocelot in request pipeline. 

## Expected Behavior / New Feature
Once there is an incoming request its picked up by GraphQl  middleware which lets the request slip without anything happing to it, then ocelot does its magic and sends the request on the specific microservice. On the request way back it goes back through Ocelot and it stops in GraphQl middleware. At this point the request response should be run through GraphQl Engine and after the magic of GraphQl is done, the manipulated result should be returned.

## Actual Behavior / Motivation for New Feature
Ocelot finishes the request returning response to the caller before  any of the prepended middlewares finished its job.

Therefore it returns the json response without any graphql manipulation happaning

**Comment by raman-m** [comment]
> Hybrid GraphQl-Ocelot-Gateway

What are you talking about?
Ocelot team is not responsible for any custom solution outside of official Ocelot repository :exclamation: 

### You have the right to reopen this issue in the future if you come with a PR ready
