### ISSUE TITLE
16.0.1 maybe a bug or something by getting serverhost from consul

### ISSUE THREAD

**Issue by wsjun2016** [ThreeMammals/Ocelot#1370]
the source code below:
`        private Service BuildService(ServiceEntry serviceEntry, Node serviceNode)
        {
 return new Service(
                serviceEntry.Service.Service,
                new ServiceHostAndPort(serviceNode == null ? serviceEntry.Service.Address : serviceNode.Name, serviceEntry.Service.Port),
                serviceEntry.Service.ID,
                GetVersionFromStrings(serviceEntry.Service.Tags),
                serviceEntry.Service.Tags ?? Enumerable.Empty<string>());
        }`

when serviceNode is null,service host will be serviceEntry.Service.Address,the result is OK.
when serviceNode is not null,it will take the value of serviceNode.Name.That is what I want to talk about.
Why serviceNode.Name?Why not serviceNode.Address?
serviceNode.Name sometime will be other value which is not a IP ,but like 'agent-one' something.
serviceNode.Address is a IP which looks like '127.0.0.1'.
so one or more exceptions have been thrown when I debug the program.
exception message likes that:
Error Code: ConnectionToDownstreamServiceError Message: Error connecting to downstream service, exception: System.Net.Http.HttpRequestException: 不知道这样的主机。

## Specifications

  - Version:16.0.1

**Comment by raman-m** [comment]
Read Release Notes for version [23.3.0](https://github.com/ThreeMammals/Ocelot/releases/tag/23.3.0) :exclamation: 
It should be fixed!
- See more in PR #2067
