### ISSUE TITLE
set “RateLimitOptions.QuotaExceededMessage” of chinese Encoding is error 

### ISSUE THREAD

**Issue by ImmortalBro** [ThreeMammals/Ocelot#1374]
`
{
  "GlobalConfiguration": {
    "RateLimitOptions": {
    "QuotaExceededMessage": "服务请求过载",
    }
  }
}`

**Comment by asd1094124012** [comment]
![1605606316(1)](https://user-images.githubusercontent.com/17041619/99374434-88afed80-28fd-11eb-9005-0fc06b0dda82.jpg)

**Comment by wsjun2016** [comment]
配置文件编码问题
