### ISSUE TITLE
Upgrading to .NET Core 3.1 and Ocelot 16.0.1 breaks https downstream 

### ISSUE THREAD

**Issue by draxtor** [ThreeMammals/Ocelot#1378]
## Expected Behavior
We were upgrading our application using Ocelot gateway from .net core 2.2 to 3.1. Together with .Net core we upgraded Ocelot as well.
We also renamed ReRoutes to Routes in our configuration files. 
 Expected behavior was that everything is running smoothly in upgraded version.

## Actual Behavior
We  started to receive 404 errors for our services.
Once we change it to http it started to work.

## Steps to Reproduce the Problem

  1. Create .net core services running on HTTPS
  1. Create routes in ocelot
```
{
  "Routes": [
    {
      "DownstreamPathTemplate": "/api/funds",
      "DownstreamScheme": "https",
      "DownstreamHostAndPorts": [
        {
          "Host": "localhost",
          "Port": 5004
        }
      ],
      "UpstreamPathTemplate": "/api/funds",
      "UpstreamHttpMethod": [ "GET" ]
    }
]
}
```
  3. Run the example in postman and it fails

Changing DownstreamScheme to http (and of course turning off https in services) made it work

## Specifications

  - Version: Ocelot 16.0.1 .net core 3.1.403
  - Platform: Windows 10 Enterprise 64 bit 1909
  - Subsystem: VIsual Studio 2019 16.7.7
Additionaly we created new project using 3.1 with one basic service and it is not working also but it is working on other computers not on our corparate network.

We are under corporate firewall and 90% is probability that it is caused by it, but everything works on the same computer running  2.2 .net core and ocelot 13.5.2.

That's why I'm wondering if someone has general idea what's going on? Any idea would be cool.

Consider this more like Q&A than opening an issue to be fixed.

**Comment by raman-m** [comment]
Do you still need an answer?

**Comment by raman-m** [comment]
Please, upgrade your app with Ocelot reference to version 23.1+, and report once again if required.
