### ISSUE TITLE
16.0.1

### ISSUE THREAD

**Issue by 173198205** [ThreeMammals/Ocelot#1379]
## Expected Behavior / New Feature
services.AddConfigStoredInConsul()
The gateway operates normally. When the consul ceases operation, the gateway does not cease operation.

## Steps to Reproduce the Problem

  1.run consul server agent
  2.run gateway()
  3.close consul server agent
  4.gateway termination of the operation(AddConfigStoredInConsul thorw socket Exception)

## Specifications

  - Version:16.0.1
  - Platform:any
  - Subsystem:netcore

**Comment by raman-m** [comment]
>gateway termination of the operation(AddConfigStoredInConsul thorw socket Exception)

If it throws exception then why didn't you include the info?
Where is the call stack?

If you have intention you could reproduce the issue using latest version please.
For now we can't accept the issue.

**Comment by raman-m** [comment]
Lack of description id the user scenario.
