### ISSUE TITLE
Unable to download files larger than 250MB

### ISSUE THREAD

**Issue by rsandsand** [ThreeMammals/Ocelot#1382]
## Expected Behavior / New Feature

Ability to download large files through the Ocelot at least up to 1GB

## Actual Behavior / Motivation for New Feature
When tried to download files larger than 250MB, browser saves an empty file. The response headers has Content-Length= 0
This is not an issue when file size is less than 250MB. Actual API endpoint does not have issues and has correct headers

## Steps to Reproduce the Problem

  1. API with file stream [FilesController]
  ```
        [Route("{fileId}")]
        [HttpGet]
        [ProducesResponseType((int)HttpStatusCode.OK)]
        public IActionResult DownloadFile([FromRoute] FileDownloadQuery query)
        {
           var file= GetFile(query.FileId); //path to large file size > 250MB
           var stream = new FileStream(file.path, FileMode.Open,FileAccess.Read);
            return File(stream, "application/octet-stream", file.name);
        }
```
  2.    API gateway with route configuration

```
    {
      "DownstreamPathTemplate": "/FileAPI/files/{everything}",
      "DownstreamScheme": "https",
      "DownstreamHostAndPorts": [
        {
          "Host": "localhost",
          "Port": "443"
        }
      ],
      "UpstreamPathTemplate": "/files/{everything}",
      "UpstreamHttpMethod": [ "GET", "POST", "PUT", "OPTIONS" ],
      "DangerousAcceptAnyServerCertificateValidator": true
    },
```
  3. Call the API gate way end point https://localhost/files/F001 from browser or Postman

## Specifications

  - Version: Ocelot 16.0.1, .NET Core 3.1
  - Platform: Windows 10 
  - Subsystem: IIS/10.0

**Comment by CheckyChen** [comment]
try change the **web.config**  **hostingModel**  value to **outofprocess** l
`
 <aspNetCore processPath=".\xxxxxx.exe" stdoutLogEnabled="false" stdoutLogFile=".\logs\stdout" hostingModel="outofprocess"  />
`

**Comment by rsandsand** [comment]
Thanks this did the trick

**Comment by wakm** [comment]
I have the same issue and I think #1262 does too. neverthelesss changing the hostingmodel is not a satisfying solution for me. Are there any other solutions? Why is this an issue anyway?
