### ISSUE TITLE
Aggregation response missing Security headers

### ISSUE THREAD

**Issue by Faisal-developer** [ThreeMammals/Ocelot#1384]
## Expected Behavior / New Feature
Aggregation calls should return security header.
## Steps to Reproduce the Problem

  1.Aggregate any two calls
  2.Security headers were missing in response.
 

## Specifications

  - Version:
  - Platform:
  - Subsystem:

**Comment by raman-m** [comment]
### You have the right to reopen this issue in the future if you come with a PR ready
