### ISSUE TITLE
Ocelot to hide identity server4

### ISSUE THREAD

**Issue by froens** [ThreeMammals/Ocelot#1391]
## Expected Behavior / New Feature
Ocelot should mediate requests/responses between client and identityserver4 in a OAuth code flow

## Actual Behavior / Motivation for New Feature
Discovery document contains urls to identityserver4 instead of ocelot

### Our setup
We have a current setup where we use IdentityServer4 as a federation gateway.
https://docs.identityserver.io/en/dev/topics/federation_gateway.html
We use Azure AD for authentication, and then we issue a bearer token (with permission claims) based on a user table in identityserver4.
The bearer token is then used for subsequent calls to our other API's.
![Ocelot - Pre](https://user-images.githubusercontent.com/11017605/101890656-45196e00-3ba1-11eb-99d7-b946495cb3d1.png)

We want to hide some of our internal stuff (like admin-APIs for IdentityServer4) behind Ocelot and only expose the OpenID Connect-part so that people can still login through identity server. The Ocelot-gateway will, from the outside, look like an identity server.
![Ocelot - Post](https://user-images.githubusercontent.com/11017605/101890641-3fbc2380-3ba1-11eb-9584-e25f63a792ce.png)

### How we tried to solve it
We've routed all Open ID-connect requests to IdentityServer4.

### The problem
When client requests /.well-known/openid-configuration, then the document contains direct URL's (e.g. authorization_endpoint) to our IdentityServer4 which is hidden behind a firewall.

I've looked and content transformation through middleware injection, but this seems like a hack:
https://ocelot.readthedocs.io/en/latest/features/middlewareinjection.html

I have a strong feeling that there is some concept that I do not entirely grasp (or something that I got wrong in the way we solve the problem).

## Specifications

  - Version: Ocelot 16.0.1
  - Platform: Asp.Net Core (net5.0)
  - Subsystem: IdentityServer4

**Comment by froens** [comment]
**I found a solution**

As described above: Just forward whatever OpenId Connect requests you get on Ocelot to IS4.

On Ocelot in ocelot.json, add this:
```json
"UpstreamHeaderTransform": {
    "X-Forwarded-Host": "{UpstreamHost}"
}
```
This will add a header X-Forwarded-Host on the forwarded requests to IS4. The value is set to the host (baseUrl) of Ocelot.

On IS4 in startup.configure(), add these lines:
```csharp
services.Configure<ForwardedHeadersOptions>(options =>
{
    options.ForwardedHeaders = ForwardedHeaders.XForwardedHost;
    options.ForwardLimit = 2;  //Limit number of proxy hops trusted
    options.KnownNetworks.Clear();
    options.KnownProxies.Clear();
});
```

This will treat the value in the http header X-Forwarded-Host as host, so that when the response for
/.well-known/openid-configuration 
is generated, then it uses the host of your proxy instead of the host of IS4.

**Comment by swetha-adb** [comment]
Hi froens.  I have the same case.  Angular is my client.  Will the above works for my solution. I will try once
