### ISSUE TITLE
How can I implement policy based authorization with Ocelot?

### ISSUE THREAD

**Issue by tmkhan** [ThreeMammals/Ocelot#1396]
## Feature
- [Request Aggregation](https://ocelot.readthedocs.io/en/latest/features/requestaggregation.html)

## Actual Behavior
Further, I tried to access claims with `HttpContext.User.Identities`, but it giving `null`.

**Comment by aliprogrammer69** [comment]
i have same problem. i tried to access to Claims with context.User.Claims but it return null.
i recently use version 14.0.9 and there was not problem.

**Comment by andrei-manulife** [comment]
I have the same problem. This has to be a bug. I cannot upgrade until I figure out why this is happening.

**Comment by aliprogrammer69** [comment]
i checked the source code and found the problem.
this problem accouris because of  "MultiplexingMiddleware:46" which this is inevitable. to solve the problem, read authorization infos (identities, claims and etc) use PreAuthenticationMiddleware

**Comment by Kation** [comment]
> i checked the source code and found the problem.
> this problem accouris because of "MultiplexingMiddleware:46" which this is inevitable. to solve the problem, read authorization infos (identities, claims and etc) from PreAuthenticationMiddleware

This is bad!!!
If MultiplexingMiddleware DO NOT Passing HttpContext.User, ClaimsToHeadersMiddleware will not work because https://github.com/ThreeMammals/Ocelot/blob/3ef6abd7465fc77632e4b2d5189fbbf47b457867/src/Ocelot/Headers/Middleware/ClaimsToHeadersMiddleware.cs#L34 get default ClaimsPrincipal and its claims is empty!

**Comment by raman-m** [comment]
The bug has been [accepted](#event-10181523655) due to ready PR #1462 
- #1462

**Comment by ggnaegi** [comment]
@raman-m we should keep in mind that issue when refactoring the multiplexing middleware. https://github.com/ThreeMammals/Ocelot/pull/1826

**Comment by raman-m** [comment]
@ggnaegi I'd like to prioritize #1462
