### ISSUE TITLE
Version Change Problem from 15.0.6 to 16.0.1

### ISSUE THREAD

**Issue by swetha-adb** [ThreeMammals/Ocelot#1404]
## Expected Behavior / New Feature
Hi Team,
My task is to update the HttpResponse's body content for a API Call.
Previously I could able do it like below in Ocelot Middleware(in version 15.0.6)

 var configuration = new OcelotPipelineConfiguration
            {
                PreQueryStringBuilderMiddleware = async (ctx, next) =>
                {
                    await next.Invoke();
                    if (ctx.DownstreamReRoute.Key == "Authenticate")
                    {
                        if (ctx.DownstreamResponse != null && ctx.DownstreamResponse.Content != null)
                        {
                           //Reading the response from fabric services API
                            var response = ctx.DownstreamResponse.Content.ReadAsStringAsync().GetAwaiter().GetResult();

                            //Using the above result generating token in Ocelot and updating the Context.Response
                            JObject jobject = JObject.Parse(response);
                            UserIdentity user = CreateUserObject(jobject);
                            UserIdentity updatedUser = TokenGenerator.GenerateToken(user, false);
                            string responseString = ConvertObjectToString(updatedUser);
                            byte[] resultbytes = Encoding.ASCII.GetBytes(responseString);
                            int intStatusCode = setCaseOriginCode(ctx.DownstreamResponse.StatusCode.ToString());
                            ctx.HttpContext.Response.StatusCode = intStatusCode;
                            await ctx.HttpContext.Response.Body.WriteAsync(resultbytes, 0, resultbytes.Length);
                        }
                      }
                }
            };
// here i could able to change the httpcontext with new updatedUser object data

## Actual Behavior / Motivation for New Feature
I have changed the version to 16.0.1 . needed to change code like below

## Steps to Reproduce the Problem

 var configuration = new OcelotPipelineConfiguration
            {
                PreQueryStringBuilderMiddleware = async (ctx, next) =>
                {
                    await next.Invoke();
                    if (ctx.Items.DownstreamRoute().Key == "Authenticate")
                    {
                        if (ctx.Items.DownstreamResponse() != null && ctx.Items.DownstreamResponse().Content != null)
                        {
                            //Reading the response from fabric services API
                            var response = ctx.Items.DownstreamResponse().Content.ReadAsStringAsync().GetAwaiter().GetResult();
                            //Using the above result generating token in Ocelot and updating the Context.Response
                            JObject jobject = JObject.Parse(response);
                            UserIdentity user = CreateUserObject(jobject);
                            UserIdentity updatedUser = TokenGenerator.GenerateToken(user, false);
                            Stream UserStream = SerializeToStream(updatedUser);
                              int intStatusCode = GetStatusCode(ctx.Items.DownstreamResponse().StatusCode.ToString());
                            ctx.Response.StatusCode = intStatusCode;
                            await ctx.Response.Body.CopyToAsync(UserStream);
                        }
                    
                    }
                }
            };

   Here body of the HttpResponse is not updated .  
   Could you please tell me the changes i have to do
## Specifications

  - Version:  16.0.1
  - Platform:  .Net Core 3.1
  - Subsystem:

**Comment by swetha-adb** [comment]
Please any one can respond? I am new to this Ocelot

**Comment by jlukawska** [comment]
After 16.0.1 changes there is a new instance of HttpContext created for each request. If you want to access the original HttpContext, try to use HttpContextAccessor.
