### ISSUE TITLE
Break if we directly use httpContext.Response.WriteAsync

### ISSUE THREAD

**Issue by WeihanLi** [ThreeMammals/Ocelot#1409]
## Expected Behavior

If user had started to write response, ocelot should not do anything but return the raw response

## Actual Behavior

Will throw a null reference exception in `HttpContextResponder.SetResponseOnHttpContext`

## Steps to Reproduce the Problem

  1. Configure the ocelot preauthzation middleware
      ``` csharp
      app.UseOcelot(configuration =>
      {
          configuration.PreAuthenticationMiddleware = (ctx, next) => return ctx.Response.WriteAsync("No Permission");
      });
      ```
  2. Access any path
      ![image](https://user-images.githubusercontent.com/7604648/103669716-aa4f5c00-4fb3-11eb-8019-033534730a52.png)

## Specifications

  - Version: 17.0.0
  - Platform: Windows
  - Subsystem: Windows 10

**Comment by raman-m** [comment]
We redesigned the system kernel. It behaves different now.
And I don't know why should we fix it?...
