### ISSUE TITLE
Response status 404 Not Found after I updated target net5.0 framework

### ISSUE THREAD

**Issue by winlj** [ThreeMammals/Ocelot#1411]
Response status 404 Not Found after I updated target net5.0 framework

.net5
consul
ocelot

{
  "GlobalConfiguration": {
    //"RequestIdKey": "OcRequestId",
    //"BaseUrl": "http://test.dayuntong.com",
    "ServiceDiscoveryProvider": {
      "Host": "192.168.2.82",
      "Port": 8500
      //"Type": "Consul"
      //"ConfigurationKey": "server-1"
    }
  },
"ReRoutes": [
    {
      "UseServiceDiscovery": true,
      "DownstreamPathTemplate": "/swagger/v1/swagger.json",
      "DownstreamScheme": "http",
      "ServiceName": "Token",
      "UpstreamPathTemplate": "/Token/swagger.json",
      "UpstreamHttpMethod": [ "GET", "POST", "DELETE", "PUT" ],
      "LoadBalancerOptions": { "Type": "RoundRobin" }
    },
]

info: Ocelot.DownstreamRouteFinder.Finder.DownstreamRouteProviderFactory[0]
      requestId: 0HM5I8BAN3KNA:00000003, previousRequestId: no previous request id, message: Selected DownstreamRouteCreator as DownstreamRouteProvider for this request
info: Ocelot.RateLimit.Middleware.ClientRateLimitMiddleware[0]
      requestId: 0HM5I8BAN3KNA:00000003, previousRequestId: no previous request id, message: EndpointRateLimiting is not enabled for /swagger.json
info: Ocelot.Authentication.Middleware.AuthenticationMiddleware[0]
      requestId: 0HM5I8BAN3KNA:00000003, previousRequestId: no previous request id, message: No authentication needed for /Token/swagger.json
info: Ocelot.Authorization.Middleware.AuthorizationMiddleware[0]
      requestId: 0HM5I8BAN3KNA:00000003, previousRequestId: no previous request id, message: /swagger.json route does not require user to be authorized
warn: Ocelot.Requester.Middleware.HttpRequesterMiddleware[0]
      requestId: 0HM5I8BAN3KNA:00000003, previousRequestId: no previous request id, message: 404 (Not Found) status code, request uri: http://node1:3003/swagger.json
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/1.1 GET http://192.168.2.81:3017/Token/swagger.json - - - 404 0 - 207.4465ms
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]

**Comment by WeihanLi** [comment]
try update `ReRoute` => `Route`

**Comment by HonghuiHu** [comment]
https://www.nuget.org/packages/Ocelot.Provider.Consul.Extensions/
https://github.com/ilonze/Ocelot.Extensions

**Comment by wast** [comment]
Creator not responding. Most probably  ReRoute => Route
