### ISSUE TITLE
Unexpected behaviour with subdomain in host

### ISSUE THREAD

**Issue by Angoth** [ThreeMammals/Ocelot#1418]
I'm trying to use Ocelot for some simple redirects but it get different results when I use subdomains in the host configuration and did not find any reasons for it in the config.

I want to achieve 2 things:

- Redirect to external websites (with and without subdomains)
- Redirect to a file and start download

Some examples:
**a) Redirecting https://localhost:5001/gateway/redirect/google to https://www.google.com/**

```json
{
  "Routes": [
    {
      "DownstreamPathTemplate": "/",
      "DownstreamScheme": "https",
      "DownstreamHostAndPorts": [
        {
          "Host": "www.google.com",
          "Port": 443
        }
      ],
      "UpstreamPathTemplate": "/gateway/redirect/google/",
      "UpstreamHttpMethod": [ "GET" ]
    }
  ]
}
```
Does not work and I receive a lot of 404 errors when the site tries to load other necessary content. Also the url did not change!
![image](https://user-images.githubusercontent.com/33282804/104602232-78a55780-567b-11eb-928f-a7e2177ca3e0.png)

**b) Redirecting https://localhost:5001/gateway/redirect/google2 to https://www.google.com/**
Almost the same example, but here I use the simple hostname without "www" and the redirect works. Here the URL changed.
```json
{
  "Routes": [
    {
      "DownstreamPathTemplate": "/",
      "DownstreamScheme": "https",
      "DownstreamHostAndPorts": [
        {
          "Host": "google.com",
          "Port": 443
        }
      ],
      "UpstreamPathTemplate": "/gateway/redirect/google2/",
      "UpstreamHttpMethod": [ "GET" ]
    }
  ]
}
```
![image](https://user-images.githubusercontent.com/33282804/104602830-16008b80-567c-11eb-8257-6257aa3cf443.png)

**c) Redirect to download google chrome installer**
The redirect to the file is working and the download starts, but the file ending is missing and the url did not change. So I expect a similar problem as in example a). In the screenshot you see the file "download(2)" but actually it should be "ChromeSetup.exe".

```json

  "Routes": [
    {
      "DownstreamPathTemplate": "/tag/s/appguid%3D%7B8A69D345-D564-463C-AFF1-A69D9E530F96%7D%26iid%3D%7B67205266-72AD-1758-1FD4-71D878C7AFDD%7D%26lang%3Dde%26browser%3D3%26usagestats%3D0%26appname%3DGoogle%2520Chrome%26needsadmin%3Dprefers%26ap%3Dx64-stable-statsdef_1%26brand%3DCHZO%26installdataindex%3Dempty/update2/installers/ChromeSetup.exe",
      "DownstreamScheme": "https",
      "DownstreamHostAndPorts": [
        {
          "Host": "dl.google.com",
          "Port": 443
        }
      ],
      "UpstreamPathTemplate": "/gateway/redirect/download/",
      "UpstreamHttpMethod": [ "GET" ]
    }
  ]
}
```
![image](https://user-images.githubusercontent.com/33282804/104603892-29f8bd00-567d-11eb-9781-8c4e95c7de69.png)

Did I miss something in the configuration or is it a bug? I experienced the same strange behaviour when using other hosts with subdomains like "info.xyz.com". I call it strange because it works, when I do not use subdomains in the hostname.

**Comment by raman-m** [comment]
Use [Follow Redirects aka HttpHandlerOptions](https://ocelot.readthedocs.io/en/latest/features/configuration.html#follow-redirects-aka-httphandleroptions)!!!
