### ISSUE TITLE
An anonymous request was received in between authentication handshake requests.

### ISSUE THREAD

**Issue by Bonsai11** [ThreeMammals/Ocelot#1423]
I'm using this package Microsoft.AspNetCore.Authentication.Negotiate on my .NET Core 3.1 Webservice, and when directly accessing it I can authenticate using windows authentication. 
But as soon as I go through Ocelot to access my webservice, I get the following error: "An anonymous request was received in between authentication handshake requests." 
I wonder where this request is coming from? So right now this is preventing me from using Windows authentiation, even though it could work in theory.  I'm using Ocelot 15.0.6.

**Comment by Bonsai11** [comment]
Any ideas? This is either possible or it is not :(

**Comment by raman-m** [comment]
Interesting... But Ocelot team is not responsible for third-party libs.
Please, ask the team which develops `Microsoft.AspNetCore.Authentication.Negotiate` lib.
