### ISSUE TITLE
Pass access token to the downstream without modification

### ISSUE THREAD

**Issue by B6692** [ThreeMammals/Ocelot#1425]
## Expected Behavior / New Feature
To have an option where in downstream a service handles authentication and authorization. The gateway should just forward the access token to the downstream service. What would be nice is to be able to configure Ocelot to allow downstream services to handle authentication and authorization.

## Actual Behavior / Motivation for New Feature
It appears Ocelot assumes it should do central authentication and would send back "Unauthorized" to a request that has an access token and when authentication is configured in Ocelot, it will block all requests with or without token recognized by Ocelot.

## Steps to Reproduce the Problem

  1. Get an access token from some authority and it to a non-authentication configured Ocelot.
  1. Configure Authentication for Ocelot and send a request with or without an access token from some authority other than Ocelot.
  1.

## Specifications

  - Version: 16.0.1
  - Platform: Windows 
  - Subsystem:

**Comment by wast** [comment]
Have you tried disabling authentication on Ocelot?
Ocelot should just pass headers to downstream and what you want should work.

**Comment by B6692** [comment]
> Have you tried disabling authentication on Ocelot?
> Ocelot should just pass headers to downstream and what you want should work.
> 
> If that doesn't work. You can make token validation always pass.

Yes, I didn't configure authentication in the gateway before but when I send a request with an access token to the ocelot gateway it returns back with unauthorized even when the controller in the downstream is decorated with [Authorize].

How can I make token validation always pass?

**Comment by wast** [comment]
This this out https://stackoverflow.com/questions/49932596/ignore-jwt-bearer-token-signature-i-e-dont-validate-token

**Comment by B6692** [comment]
> This this out https://stackoverflow.com/questions/49932596/ignore-jwt-bearer-token-signature-i-e-dont-validate-token

Thanks for the link you posted. I have tried to follow the link carefully, assuming if I enable authentication and disable all validation checks at the gateway, it will forward my request to the backend service unmolested and then hopefully it will work. But alas, it doesn't . The gateway sees it as its responsibility to evaluate security authentication. It assumes, whether the backend configures security or not , that an endpoint is secured or unsecured if it's authentication configuration is enabled. 

When I send my access tokens in either case , they get rejected by the gateway . This is strange behavior. What is happening here?

**Comment by wast** [comment]
I am using Ocelot like that and it works. Please open a question on stackoverflow if you still have the issue.

**Comment by raman-m** [comment]
@B6692 
> To have an option where in downstream a service handles authentication and authorization. The gateway should just forward the access token to the downstream service. What would be nice is to be able to configure Ocelot to allow downstream services to handle authentication and authorization.

To handle auth stage by downstream service, do the following:
- Switch off auth feature for the route in Ocelot config at all!
- If auth-token is a header, just forward the header value by [Headers Transformation](https://ocelot.readthedocs.io/en/latest/features/headerstransformation.html) feature.
- If auth-token is a query parameter, just keep it in query string of URL, and define appropriate Ocelot everything-route or CatchAll-route by [Routing](https://ocelot.readthedocs.io/en/latest/features/routing.html) feature. Your token will be forwarded to downstream service for evaluation.

Am I right, @wast ? 😃

**Comment by wast** [comment]
Header is propagated to downstream regardless [Headers Transformation](https://ocelot.readthedocs.io/en/latest/features/headerstransformation.html) feature afaik.
