### ISSUE TITLE
Consul provider doesn't support client certificate

### ISSUE THREAD

**Issue by gedcharlton** [ThreeMammals/Ocelot#1426]
## Expected Behavior / New Feature

Our Consul implementation uses mutual TLS, however the Consul provider currently doesn't support client certificates.
The ConsulClient that is used for the connection can be configured to use a client certificate (via the HttpClientHandler in the ConsulClientFactory) but there are no options to configure the client certificate name, location and store.

## Specifications

  - Version: 17.0

**Comment by raman-m** [comment]
@gedcharlton  Will you, Ged?

**Comment by raman-m** [comment]
### You have the right to reopen this issue in the future if you come with a PR ready
