### ISSUE TITLE
Ocelot as Reverse Proxy 

### ISSUE THREAD

**Issue by ajibodu** [ThreeMammals/Ocelot#1427]
I currently use ocelot as a gateway for a number of microservice within my private network which has been working great
and I recently exposed the gateway over the internet to downstream to a microservice in my private network

The ApiGateway has all network permission for my private network.

## Expected Behavior / New Feature
The Gateway to act as a reverse proxy for all requests.
A request over the internet should be able to downstream to my internal service(a private network)

## Actual Behavior / Motivation for New Feature
Unable to reach the downstream microservice as it seems requests are been passed directly from the client(over the internet) to my internal service with the error message stating the internal IP address "connect ETIMEDOUT 172.xx.xx.xx:443"

## Specifications
  - Platform: netcoreapp3.1

**Comment by raman-m** [comment]
Ocelot's architecture doesn't support reverse proxying of a traffic. Ocelot is API gateway!!!

To have functionality of traffic proxying, please use other products like **Nginx** etc.
