### ISSUE TITLE
Disallow body in HEAD, GET, TRACE

### ISSUE THREAD

**Issue by abriening** [ThreeMammals/Ocelot#1432]
## Expected Behavior / New Feature

Downstream HEAD, GET & TRACE requests should not allow a request body.

## Actual Behavior / Motivation for New Feature

If you mistakenly send a request body on HEAD, GET, TRACE requests they forward the body downstream.

More importantly if you map an upstream POST, PUT, etc with a request body to a downstream method that should not support a request body, the body is still sent.

## Steps to Reproduce the Problem

  1. Configure an upstream POST to a downstream GET
  2. Tests in the https://github.com/ThreeMammals/Ocelot/pull/1433 PR fail in the current develop branch
  
## Specifications

  - Version: 17.0.0

**Comment by raman-m** [comment]
The issue has been [accepted](#event-10172146004) due to ready PR #1433 
- #1433

**Comment by RaynaldM** [comment]
I don't agree, you can put a body in a get request, it's not recommended, but it's possible.
Ocelot must remain open to this kind of "exotic" case.

**Comment by raman-m** [comment]
> @RaynaldM commented [on Aug 24](#issuecomment-1691074452)

Yeah, makes sense. But I believe Ocelot could be more flexible: allowing/disallowing this feature.
We can provide an option to manage this "body" feature to follow standards.
By default Ocelot will forward request "as-is" (with bodies). For some routes or hosts we can enable feature to follow web standards (this feature request), ignoring bodies based on web method type.

---
P.S. To @abriening 
We can include [OPTIONS](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/OPTIONS) web method to your list. 😉

**Comment by raman-m** [comment]
> @abriening commented [on Feb 8, 2021](#issue-803664533)

We can include [OPTIONS](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/OPTIONS) web method to your list. 😉

**Comment by abriening** [comment]
I was going off of the W3C http 1.1 spec. It seems silent on whether OPTIONS must not have content. RFC 2616 mentions `Content-Type` headers required if there is content. At some point there was an expectation that OPTIONS requests may have content. I haven't looked at this code in three years, I'll have to dig into it to remember what I was trying to do. But I think it had more to do with mismatched upstream and downstream http methods and having sane expectations of what would happen in those scenarios.

**Comment by raman-m** [comment]
> @RaynaldM commented [on Aug 24](#issuecomment-1691074452)

Taking into consideration [current discussion results](../pull/1433#pullrequestreview-1592851063), it seems **we cannot accept this issue**. And we have to close linked PR...
I agree, Ocelot should behave as proxy: if there is body then Ocelot forwards it. It should not analyze the type of the verb at all. **Ocelot should not ignore bodies or swallow them based on web method.**
That's how to be a proxy, not a filter or transformer, assembler.
