### ISSUE TITLE
Should I move Ocelot to an organisation?

### ISSUE THREAD

**Issue by TomPallister** [ThreeMammals/Ocelot#144]
Hi All,

Ocelot is growing quite a bit now and still sits on my personal GitHub.

Another person has now made an Ocelot specific app https://github.com/TomPallister/Ocelot/issues/116

Should I move Ocelot to an organisation? If so what should it be called? I already own an organisation called ThreeMammals so I could move it to this but maybe something Ocelot specific might make more sense! 

What do people think?

**Comment by geffzhang** [comment]
I very much agree with the use of organizations for management, the 11.15 Microsoft Connect () Conference will also broadcast my video, Video Ocelot is the protagonist。

**Comment by geffzhang** [comment]
This is  case https://customers.microsoft.com/en-us/story/tencent-telecommunications-dotnetcore

**Comment by TomPallister** [comment]
@geffzhang amazing!!!! That is so cool! 

Thanks for linking it here. I think I will move Ocelot soon. I'm just not sure if I want to use the name ThreeMammals or make a new one.

Thanks for using the project and contributing to it!!

**Comment by TomPallister** [comment]
I also found out David Fowler tweeted the project https://twitter.com/davidfowl/status/927784832284758016 !!!

**Comment by tamchitrung** [comment]
I am agree too

**Comment by TomPallister** [comment]
I am going to move Ocelot to an organisation called ocelot-stack soon.

**Comment by CESARDELATORRE** [comment]
I think you should. And then, join the .NET Foundation: http://dotnetfoundation.org/ 
👍

**Comment by TomPallister** [comment]
I will be moving Ocelot to an organisation called threemammals.

I am getting a website and logo sorted at the moment

**Comment by CESARDELATORRE** [comment]
That is way cool! 👍

**Comment by TomPallister** [comment]
OK so moved to ThreeMammals and we have a website and stuff! I will close this one for now and think about the .net core foundation!
