### ISSUE TITLE
Use Ocelot and Kubernetes at same time

### ISSUE THREAD

**Issue by aliprogrammer69** [ThreeMammals/Ocelot#1451]
In my project I store ocelot configurations in consul key value store and also I want to use k8s as service provider. 
But with current ocelot configuration struct it's impossible.

**Comment by raman-m** [comment]
Everything is possible :wink: 😜

- [Kubernetes | Service Discovery](https://ocelot.readthedocs.io/en/latest/features/kubernetes.html)
- [Store Configuration in Consul | Configuration](https://ocelot.readthedocs.io/en/latest/features/configuration.html#store-configuration-in-consul)

Good luck in development!
