### ISSUE TITLE
轮询算法缺陷

### ISSUE THREAD

**Issue by zjhlovewtr** [ThreeMammals/Ocelot#1453]
## Steps to Reproduce the Problem

  1、轮询算法缺乏现实情况考虑，
      目前Ocelot算法中，是基于请求数和取模运算实现的，每一个集群实例，得到的请求数都相等。
      如果集群实例的并发处理能力不一致，就会出现集群奔溃的问题。
      例如：集群实例 A B C , B实例处理能力最弱，到最后所有请求都累计到B实例上，导致系统集群系统崩溃的风险。
      解决：可以使用加权轮询来解决。
## Specifications

  - Version:
  - Platform:
  - Subsystem:

**Comment by raman-m** [comment]
Dear author!
Unfortunately, we do not accept tickets written in languages other than English!
Only English please!
