### ISSUE TITLE
How api gateway realizes real-time perception of offline services

### ISSUE THREAD

**Issue by iseejustdoit** [ThreeMammals/Ocelot#1458]
## Expected Behavior / New Feature

 "ServiceDiscoveryProvider": { "Type": "Eureka" }

I have two same services, one of which needs to be updated, How api gateway realizes real-time perception of offline services?

## Steps to Reproduce the Problem

  
![image](https://user-images.githubusercontent.com/9328155/112740814-9879c580-8fb2-11eb-932b-86992fde16a1.png)

**Comment by raman-m** [comment]
Ocelot can understand that downstream service is offline on DNS level or it will wait for Timeout time and `HttpRequest` will fail with timeout error.
See more: [Server error responses](https://ocelot.readthedocs.io/en/latest/features/errorcodes.html#server-error-responses)
