### ISSUE TITLE
Fix Build Cake

### ISSUE THREAD

**Issue by Ugway77** [ThreeMammals/Ocelot#1463]
## Expected Behavior / New Feature
New PR are passing CircleCI
It seems https://github.com/ThreeMammals/Ocelot/pull/1436 can fix this

## Actual Behavior / Motivation for New Feature
CircleCI fail with errors - new PR checks are failed
![image](https://user-images.githubusercontent.com/82089521/113867291-08f4c380-97b7-11eb-8fa5-4a85b191afb2.png)

## Steps to Reproduce the Problem
Just add new PR

## Specifications
Github

**Comment by raman-m** [comment]
Everything is fine with our build script.
