### ISSUE TITLE
Provide documentation for previous versions of Ocelot

### ISSUE THREAD

**Issue by Deilan** [ThreeMammals/Ocelot#1464]
Since the latest major versions:
1. have breaking changes
2. dropped off support of .NET Core 3.1-

thus some of previous versions are still in LTS, it is crucial to have documentation for previous versions of Ocelot.

## Expected Behavior / New Feature
Docs for the following versions of Ocelot are present:
* latest (17.x)
* 16.x
* 15.x
* 14.x
...

## Actual Behavior / Motivation for New Feature
Docs for the following versions of Ocelot are present:
* latest (17.x)

## Steps to Reproduce the Problem
1. Go to https://ocelot.readthedocs.io/
2. Scroll down the left sidebar
3. Try to change a version

![image](https://user-images.githubusercontent.com/4777512/115189872-63741500-a111-11eb-81b3-9527ab6e2c6c.png)

**Comment by raman-m** [comment]
> dropped off support of .NET Core 3.1

Even Microsoft don't support 3.1 ))
Even .NET 5 is not supported by Microsoft since November '23.

**Comment by raman-m** [comment]
@Deilan  Hi Michael!
We don't support old versions of Ocelot via backporting having built and released new version.
We just not approved such release strategy. Therefore we don't support old docs!

We support only .NET 6+ as Microsoft does it, and we support current latest released version until the next major version.
But we accept reported bugs always. But not for old versions!

Also, you are able to build any version docs checking out old version commit in git, and run docs building script >>> https://github.com/ThreeMammals/Ocelot/blob/develop/docs/make.sh
So, you will have local documentation as HTML webpages. 

@ggnaegi @RaynaldM FYI
