### ISSUE TITLE
Question: priority, same upstream host

### ISSUE THREAD

**Issue by CoderJason123** [ThreeMammals/Ocelot#1466]
In hosting several microservices, the same upstream host is used.  

Each microservice has its own path template, along with some routes that are anonymous.  I'm concerned that each catch all for each microservice will all have priority 0, AND, i will have to set every other route to have a specific priority.  Each microservice has 3 or 4 paths that should be numbered 1-4 on priority.  Now, i will end up with 10 microservices each with matching priorities to other services.

I assume all priority is marked as 0 by default.   I'm worried about getting in a priority mess.  

Can you provide guidance?

**Comment by raman-m** [comment]
Interesting story! :rofl: 
Stay with Ocelot! :muscle:
