### ISSUE TITLE
FluentValidation 10.0+ breaking change

### ISSUE THREAD

**Issue by ahuang321** [ThreeMammals/Ocelot#1468]
On a project where FluentValidation 10 was forced down. Per docs this included breaking changes:

https://docs.fluentvalidation.net/en/latest/upgrading-to-10.html

Currently running Ocelot 17.0 .NET Core 5.0, which now returns this error on startup:

Method not found: 'System.Collections.Generic.IList`1<FluentValidation.Results.ValidationFailure> FluentValidation.Results.ValidationResult.get_Errors()

**Comment by raschmitt** [comment]
I was having a similar issue, not with `Ocelot`, but with another dependency that was also using `FluentValidation`.

I was trying to use `Fluent Validation 10.x`, while my dependency used `9.x`, ended up having to downgrade fluent on my side.

Maybe it can solve your issue until they upgrade it here.

**Comment by Gurgen** [comment]
Could you please update `FluentValidation` to the latest version?

**Comment by Tsukasa42** [comment]
Same issue today. Latest Ocelot and FluentValidation. FluentValidation was added to a core component shared across services. Even though the ocelot service doesn't use it, it's still causing an issue.

**Comment by PatryxCShark** [comment]
Is the issue resolved? I also cannot use FluentValidation <= 10.3.4 because of other libraries and theit dependencies and I don't know how can I use Ocelot v17.0.0 now? Any tips?

**Comment by teomane** [comment]
Any update ?

**Comment by codehunter13** [comment]
any update on this?

**Comment by vaclavholusa** [comment]
Faced the same issue - got it resolved by explicitely installing FluentValidation 11.0.2 together with Ocelot 18.0.0

**Comment by raman-m** [comment]
Hi @ahuang321 
Thanks for reporting 2 years ago! :smile_cat: 

@raschmitt  @Gurgen  @Tsukasa42  @PatryxCShark  @teomane  @codehunter13  @vaclavholusa 
The `FluentValidation` package was updated in 19.0.2 release.
The current version of the package is [11.5.2](../blob/19.0.2/src/Ocelot/Ocelot.csproj#L27)
Please update your [Ocelot](https://www.nuget.org/packages/Ocelot) package reference to [19.0.2](https://www.nuget.org/packages/Ocelot/19.0.2) version please! And consider upgrading the project to .NET 7 plz!

I'm going to close the issue...
