### ISSUE TITLE
Ocelot with WebSockets returns 499 on IIS

### ISSUE THREAD

**Issue by ivonask** [ThreeMammals/Ocelot#1471]
I'm using Ocelot as a reverse proxy in a .NET 5 application. I tried to test the WebSockets functionality with a simple route that points to the "echo.websocket.org" demo server downstream.

```json
{
  "Routes": [
     {
      "DownstreamPathTemplate": "/",
      "DownstreamScheme": "ws",
      "DownstreamHostAndPorts": [
        {
          "Host": "echo.websocket.org",
          "Port": 80
        }
      ],
      "UpstreamPathTemplate": "/hello/",
      "UpstreamHttpMethod": []
    }
  ]
}
```
## Expected Behavior
Websocket connection established when using Ocelot route.

## Actual Behavior
The routing is successful when running code from Visual Studio using IISExpress, and when packing my application in a Docker container.
However, when I package my app in a MSI Installer and run it with IIS, I'm getting a 499 status code - the request is cancelled by the client after waiting for the response 90 seconds until the timeout. It seems that the request cannot pass through the IIS.
I have tried both with the WebSockets Windows feature enabled and disabled. In the docs it's written that it should be disabled.

## Steps to Reproduce the Problem

  1. Run Ocelot route with IIS

## Specifications

  - Version: 15.0.6
  - Platform: .NET 5

Please let me know if I need to provide some more information.

**Comment by eddex** [comment]
Might be related to the issue I just created: #1473
Have you tried if it works if you set the `UpstreamPathTemplate` to `/` or `/{everything}`?

**Comment by gyula-uszkai** [comment]
I had the same issue and took me some time and research to understand that you can set the individual timeout for each route using 
"QoSOptions": {
        "TimeoutValue": 180000
      }
See 
So in your example to set timeout to 3 minutes that would be
{
	"ReRoutes": [
		{
			"DownstreamPathTemplate": "/",
			"DownstreamScheme": "ws",
			"DownstreamHostAndPorts": [
				{
					"Host": "echo.websocket.org",
					"Port": 80
				}
			],
			"QoSOptions": {
				"TimeoutValue": 180000
			},
			"UpstreamPathTemplate": "/hello/",
			"UpstreamHttpMethod": []
		}
	]
}

**Comment by raman-m** [comment]
@ivonask 
> I'm using Ocelot as a reverse proxy in a .NET 5 application.

We don't support .NET 5 anymore.
We don't recommend to use IIS for deployments.
Sorry, can't help you more...
