### ISSUE TITLE
When uploading a file, the file forwarded to downstream is empty

### ISSUE THREAD

**Issue by mcslove808** [ThreeMammals/Ocelot#1477]
## Steps to Reproduce the Problem

  1.There are files in custom Ocelot middleware
![image](https://user-images.githubusercontent.com/31118200/120099244-17cf7500-c16d-11eb-9363-065c0451d812.png)

  2.There are no documents downstream
![image](https://user-images.githubusercontent.com/31118200/120099296-477e7d00-c16d-11eb-8ceb-a87957c56b8c.png)

  1.

## Specifications

  - Version:
  - Platform:
  - Subsystem:

**Comment by ks1990cn** [comment]
@mcslove808 Please try on latest version. Issue is not replicated on latest version.

**Comment by raman-m** [comment]
@mcslove808
Hi! And welcome to Ocelot world!

As far as I know Ocelot doesn't support routing of form-data and its files.
So we need to open a feature ticket to work on it...

We welcome your PR to create!
For now, I will keep this issue open to be able to return back in future to work on it as a feature.

**P.S.** And, if you use our gateway, please fork Ocelot into your account!

@ggnaegi  FYI

**Comment by raman-m** [comment]
@mcslove808 
Upgrade to the latest version please!
And if issue still persists, open a PR with the fix please, and reopen this one.
