### ISSUE TITLE
There is an error in OcelotBasic sample

### ISSUE THREAD

**Issue by xdqa01** [ThreeMammals/Ocelot#1480]
I downloaded this repository,and in devlop branch.
then run OcelotBasic  sample.
There is an error happened.
I changed ConfigureLogging in Program.cs to
`
               .ConfigureLogging((hostingContext, logging) =>
               {
                   logging.AddConsole();
                   //add your logging
               })
`
Then ,i get some message:
`
E:\CodeSource\Ocelot\samples\OcelotBasic>dotnet run
Hosting environment: Development
Content root path: E:\CodeSource\Ocelot\samples\OcelotBasic
Now listening on: https://localhost:5001
Now listening on: http://localhost:5000
Application started. Press Ctrl+C to shut down.
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/2 GET https://localhost:5001/posts/1 - -
warn: Ocelot.DownstreamRouteFinder.Middleware.DownstreamRouteFinderMiddleware[0]
      requestId: 0HM99G7K9HT6F:00000001, previousRequestId: no previous request id, message: DownstreamRouteFinderMiddleware setting pipeline errors. IDownstreamRouteFinder returned Error Code: UnableToFindDownstreamRouteError Message: Failed to match ReRoute configuration for upstream path: /posts/1, verb: GET.
warn: Ocelot.DownstreamRouteFinder.Middleware.DownstreamRouteFinderMiddleware[0]
      requestId: 0HM99G7K9HT6F:00000001, previousRequestId: no previous request id, message: Failed to match ReRoute configuration for upstream path: /posts/1, verb: GET.
warn: Ocelot.Responder.Middleware.ResponderMiddleware[0]
      requestId: 0HM99G7K9HT6F:00000001, previousRequestId: no previous request id, message: Error Code: UnableToFindDownstreamRouteError Message: Failed to match ReRoute configuration for upstream path: /posts/1, verb: GET. errors found in ResponderMiddleware. Setting error response for request path:/posts/1, request method: GET
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/2 GET https://localhost:5001/posts/1 - - - 404 0 - 20.4051ms
`

**Comment by kirkhaines** [comment]
The Ocelot NuGet package used by the OcelotBasic sample looks like it is on version 14 instead of 17.  If you update it to 17 it seems to work ok.

**Comment by raman-m** [comment]
@xdqa01 Lack of JSON config to verify you user scenario! I'm sure on 99% that you had config misconfiguration issue.

@kirkhaines Yes, we've removed all explicit references to packages in all samples for v20.0.
Now samples use direct project reference instead of old nuget pack one.

**Comment by raman-m** [comment]
Stay with Ocelot! 😉
