### ISSUE TITLE
Protecting /configuration endpoint with a role claim

### ISSUE THREAD

**Issue by default-kaas** [ThreeMammals/Ocelot#1481]
## Expected Behavior 
I would like to protect the /configruation path (from ocelot FileConfiguration) with a role (claim), but i can't figure out how it is possible.
Between the existing issues i can't find anyone with a smiliar problem.

Ocelot does check if someone has a valid JWT.
But it won't check the role (claim) that the user has.

## Actual Behavior
I can't find a way to protect the /configuration, with a role.
I am doing something wrong, with my configuration 
Or should it be done in a different way.

I would like to use this for example, to protect the route:
```json
{
  "Routes": [
    {
      "UpstreamPathTemplate": "/configuration",
      "Priority": 1,
      "UpstreamHttpMethod": [ "POST" , "GET"],
      "DownstreamPathTemplate": "/configuration",
      "DownstreamScheme": "http",
      "DownstreamHostAndPorts": [
        {
          "Host": "localhost",
          "Port": 44301
        }
      ],
      "AuthenticationOptions": {
        "AuthenticationProviderKey": "Bearer"
      },
      "RouteClaimsRequirement": { "role": "1" }
    }
  ],
  "GlobalConfiguration": {
    "BaseUrl": "https://localhost:44301"
  }
}
```

## Steps to Reproduce the Problem

I have the authentication and the ocelot gateway in the same service.

  1. Configure your setup with the JSON above
  2. Use a Bearer schema for authentication

## Specifications

  - Version: 17.0.0
  - Platform: .NET 5
  - Subsystem: Windows

## Extra
I am capable of protecting other routes with role claims to other services.
But it does not seem to work for routes to the severice it self (where ocelot it self is configured on).

**Comment by default-kaas** [comment]
Is this project abboned or death?

@TomPallister 

Because a question like this shouldn't be open for over 3 months,
Any body else that has dealt with this problem?

**Comment by raman-m** [comment]
Please, ask your questions in our new [Discussions](https://github.com/ThreeMammals/Ocelot/discussions) space.
