### ISSUE TITLE
AddJsonFile reloadOnChange is not working on azure linux app service

### ISSUE THREAD

**Issue by Ghyath-Serhal** [ThreeMammals/Ocelot#1483]
I am working with Ocelot, I have a problem with **reloadOnChange** on azure linux app service. When changing the json configuration, they are not reflected until restarting the app service.

It working fine locally and when trying it on an azure windows app service.

The code is
config.AddJsonFile($"ocelot.json", false, true);

**Comment by raman-m** [comment]
It is possibly an issue of Azure virtual cloud environment without access to a storage, HDD and SSD.
Try to run your solution locally using your local workstation, laptop or desktop. The Ocelot app should work.
Also try https://ocelot.readthedocs.io/en/latest/features/administration.html
