### ISSUE TITLE
Error related to aggregate key when deploying service.

### ISSUE THREAD

**Issue by konrad682** [ThreeMammals/Ocelot#1490]
I'm using Ocelot in a .NET Core 3.1 service. Recently I encountered an error deploying a service with Ocelot configuration to k8s. During the investigation, it turned out that the problem is with the key used for aggregation, namely: 'tenant-service-api-get-tenants-upgrades'. The use of such a key did not allow the service to be deployed, which ended with the error

![image](https://user-images.githubusercontent.com/24483667/124915546-f37b7980-dff1-11eb-874a-c57a7bd61033.png)

Changed the key to 'tenant-service-api-get-tenant-upgrades' (tenant without 's') resolved the problem. During the investigation, various keys of different lengths were tested, and it turned out that the problem was only with the 'tenant-service-api-get-tenants-upgrades' key. The exact cause of the problem was not found, but changing the key to a different one solves the problem. Can you tell why this was happening, and what could be causing the problem?

mountedConfigMap:
  ocelot.json:
```json
    {
    "Routes": [
	//.
	//.
	//.
      {
        "DownstreamPathTemplate": "/api/{version}/Tenants/tenant-upgrades",
        "DownstreamScheme": "http",
        "DownstreamHostAndPorts": [
          {
            "Host": "another-service-k8s-cluster",
            "Port": 5000
          }
        ],
        "UpstreamPathTemplate": "/api/tenants/{version}/tenant-upgrades",
        "UpstreamHttpMethod": [ "GET" ],
        "AuthenticationOptions": {
          "AuthenticationProviderKey": "Bearer"
        },
        "Key": "tenant-service-api-get-tenants-upgrades"
      },
	  //.
	  //.
	  //.
    ],
    "Aggregates": [
      {
        "RouteKeys": [
          "key-to-antoher-service",
          "tenant-service-api-get-tenants-upgrades"
        ],
        "UpstreamPathTemplate": "/api/{version}/get-tenants-upgrades",
        "Aggregator": "GetTenantsUpgradesAggregator"
      }
    ],
    }
```

## Expected Behavior / New Feature
Service is deploying without any errors.

## Actual Behavior / Motivation for New Feature
Key used for aggregation, namely: 'tenant-service-api-get-tenants-upgrades' did not allow the service to be deployed, which ended with the error in the picture above. Change the key to any other one,  e.g. 'tenant-service-api-get-tenant-upgrades' fixes the deployment error.

## Steps to Reproduce the Problem

  1. Run Ocelot with above config.

## Specifications

  - Version: 16.0.1
  - Platform: .NET Core 3.1

**Comment by raman-m** [comment]
Hi Konrad!
You are lucky with the key! 🔑 🤣 
Post such issues more! 😄 

Kubernetes is the best! ✌️
