### ISSUE TITLE
Request Host Header

### ISSUE THREAD

**Issue by robertok77** [ThreeMammals/Ocelot#1492]
what are the basic overriding made by ocelet when receiving upstream ?

let's say  ocelot.json
```
      "DownstreamPathTemplate": "/{url}",
      "DownstreamScheme": "https",
      "DownstreamHostAndPorts": [
        {
          "Host": "hostserver.com",
          "Port": 443
        }
      ],

      "UpstreamPathTemplate": "/{url}",
      "UpstreamHttpMethod": [ "Get" ],
      "HttpHandlerOptions": {
        "AllowAutoRedirect": true,
        "UseCookieContainer": true
      },
      "DelegatingHandlers": [
        "HeaderTransformHandler"
      ]
```

however I am not sure how it works. I got response 403 but when I make the same request directly to hostserver.com I got response 200. (using postman I only change **host** header from localhost:5001 to hostserver.com)

**Comment by raman-m** [comment]
Hi Robert!
But you are C# developer... Cannot you debug the code to find a root cause?

But I guess the problem can be in **AllowAutoRedirect**...

So, please attach logs, exception info and reopen the issue...
