### ISSUE TITLE
consul QoSOptions invalid

### ISSUE THREAD

**Issue by wesonder** [ThreeMammals/Ocelot#1495]
When  I  use Ocelot only  the QoSOptions and RateLimitOptions  is  Available，but  when  I use consul  , QoSOptions and RateLimitOptions is  invalid。 i can not find a method to solve  that

**Comment by raman-m** [comment]
Sorry, man! I cannot get you!

**Comment by raman-m** [comment]
Lack of description!
Official bug template is not used!
