### ISSUE TITLE
Aggregates not working : Does not call the second Route Key

### ISSUE THREAD

**Issue by kps-promad** [ThreeMammals/Ocelot#1498]
## Expected Behavior / New Feature
Aggregates should work as expected and defined in the doc 

## Actual Behavior / Motivation for New Feature

info: Ocelot.RateLimit.Middleware.ClientRateLimitMiddleware[0]
      requestId: 0HMAGJ2TTS6T3:00000002, previousRequestId: no previous request id, message: EndpointRateLimiting is not enabled for /api/v1/hello
info: Ocelot.Authentication.Middleware.AuthenticationMiddleware[0]
      requestId: 0HMAGJ2TTS6T3:00000002, previousRequestId: no previous request id, message: No authentication needed for /hithereyou
info: Ocelot.Authorization.Middleware.AuthorizationMiddleware[0]
      requestId: 0HMAGJ2TTS6T3:00000002, previousRequestId: no previous request id, message: /api/v1/hello route does not require user to be authorized
info: Ocelot.Requester.Middleware.HttpRequesterMiddleware[0]
      requestId: 0HMAGJ2TTS6T3:00000002, previousRequestId: no previous request id, message: 200 (OK) status code, request uri: https://localhost:5001/api/v1/hello
warn: Ocelot.Responder.Middleware.ResponderMiddleware[0]
      requestId: 0HMAGJ2TTS6T3:00000002, previousRequestId: no previous request id, message: Error Code: UnmappableRequestError Message: Error when parsing incoming request, exception: System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'start')
         at System.Buffers.ReadOnlySequence`1.TryGet(SequencePosition& position, ReadOnlyMemory`1& memory, Boolean advance)
         at System.IO.Pipelines.PipeReader.CopyToAsyncCore[TStream](TStream destination, Func`4 writeAsync, CancellationToken cancellationToken)
         at Ocelot.Request.Mapper.RequestMapper.ToByteArray(Stream stream)
         at Ocelot.Request.Mapper.RequestMapper.MapContent(HttpRequest request)
         at Ocelot.Request.Mapper.RequestMapper.Map(HttpRequest request, DownstreamRoute downstreamRoute) errors found in ResponderMiddleware. Setting error response for request path:/hithereyou, request method: GET

It seems like the 2nd call is never made. I am not sure what is wrong here. Any help would be highy appreciated.
## Steps to Reproduce the Problem
Here is my Ocelot.Json

{
  "Routes": [
    {
      "DownstreamPathTemplate": "/api/v1/actions/{actionId}",
      "DownstreamScheme": "https",
      "DownstreamHostAndPorts": [
        {
          "Host": "localhost",
          "Port": 5001
        }
      ],
      "UpstreamPathTemplate": "/actions/{actionId}",
      "UpstreamHttpMethod": [ "Get", "Post" ]
    },
    {
      "DownstreamPathTemplate": "/api/v1/hello",
      "UpstreamPathTemplate": "/hi",
      "UpstreamHttpMethod": [
        "Get"
      ],
      "DownstreamScheme": "https",
      "DownstreamHostAndPorts": [
        {
          "Host": "localhost",
          "Port": 5001
        }
      ],
      "Key": "hi"
    },
    {
      "DownstreamPathTemplate": "/api/v1/lonely",
      //"DownstreamPathTemplate": "/api/weather",
      "UpstreamPathTemplate": "/there",
      "UpstreamHttpMethod": [
        "Get"
      ],
      "DownstreamScheme": "https",
      "DownstreamHostAndPorts": [
        {
          "Host": "localhost",
          "Port": 5001
        }
      ],
      "Key": "there"
    }
  ],
  "Aggregates": [
    {
      "RouteKeys": [
        "hi",
        "there"
      ],
      "UpstreamPathTemplate": "/hithereyou"
      //"Aggregator": "FakeDefinedAggregator"
    }
  ],
  "GlobalConfiguration": {
    "BaseUrl": "https://localhost:5006"
    
  }
}

## Specifications

  - Version:17.0
  - Platform: Windows / Dot Net 5
  - Subsystem:

**Comment by raman-m** [comment]
Learn Ocelot more! 🤣 
- [Request Aggregation](https://ocelot.readthedocs.io/en/latest/features/requestaggregation.html)

Aggregation feature works great.

------
>Message: Error when parsing incoming request, exception:

Root cause of having error: Bad format of JSON data.
Ocelot cannot parse JSON, possibly.
Try to debug problem.
Try to call downstream service manually and check returned JSON formatting!
