### ISSUE TITLE
Be able to extract route items (id) from an UpstreamPathTemplate for Authorisation

### ISSUE THREAD

**Issue by excelthoughts** [ThreeMammals/Ocelot#1507]
## Expected Behavior / New Feature
Be able to extract route items (id) from an UpstreamPathTemplate for Authorisation

## Actual Behavior / Motivation for New Feature
Cannot find any examples or how to do this?

## Steps to Reproduce the Problem

Routes..
{
      "UpstreamPathTemplate": "/api/v1/persons/{id}",
      "UpstreamHttpMethod": [
        "Get"
      ],
      "DownstreamPathTemplate": "/api/v1/persons/{id}",
      "DownstreamScheme": "http"
    }

implement class PassthroughMiddleware: OcelotMiddleware

in Invoke(HttpContext context)
{
 var route = context.Items.DownstreamRoute();//this  null, want to get the UpstreamPathTemplate that matched this request, and pull the id out 
}

in Startup
            app.UseMiddleware<PassthroughMiddleware>();
            app.UseOcelot().Wait();

## Specifications

  - Version: 17.0
  - Platform: Win10
  - Subsystem:

**Comment by abdulmoizlogiciel** [comment]
any luck ?
