### ISSUE TITLE
Issue with default Newtonsoft Serializer

### ISSUE THREAD

**Issue by WajahatAliAbid** [ThreeMammals/Ocelot#1510]
## Expected Behavior
With .net core 3.1 and above, asp.net core projects use System.Text.Json serializer by default. But when we add Ocelot in our DI, asp.net core projects start using Newtonsoft.json. I tried diagnosing this issue and found that Ocelot was adding NewtonsoftJson in the dependency tree which changed the default serializer to NewtonsoftJson instead of the expected System.Text.Json with .net core 3.1 and above projects. For reference: [OcelotBuilder](https://github.com/ThreeMammals/Ocelot/blob/3ef6abd7465fc77632e4b2d5189fbbf47b457867/src/Ocelot/DependencyInjection/OcelotBuilder.cs#L150)

I've an HTTP Client which uses System.Text.Json as the serializer and it is receiving a dynamic JSON object which I expect to be serialized properly when returning as `ActionResult` from Controller. Following is my expected response
```json
{
    "DynamicObject": {
        "Field1": "Value1",
        "Field2": "Value2"
    }
}
```

## Actual Behavior
I get the following response instead which is basically serialized by Newtonsoft.Json
```json
{
    "DynamicObject": {
        "ValueKind": 1
    }
}
```

## Steps to Reproduce the Problem

  1. Add Ocelot and register it in startup
  2. Create a json string and deserialize it into object type using `System.Text.Json.JsonSerializer`
  3. Return that object from controller action
  ```csharp
class DynamicResultType
{
    public object DynamicObject { get; set; }
}

[ApiController]
[Route("/api")]
public class HomeController : ControllerBase
{
    public ActionResult<DynamicResultType> Get()
    {
        var text = "{\"DynamicObject\": {\"Field1\": \"Value1\",\"Field2\": \"Value2\"}}";
        var obj = System.Text.Json.JsonSerializer.Deserialize<DynamicResultType>();
        return obj;
    }
}

  ```

## Specifications

  - Version: 17.0.0
  - Platform: Linux (Manjaro KDE)

**Comment by PavelFischerCoupa** [comment]
Run into the same issue during migration of project from net 3.1 to 6.0

**Comment by psavoldelli** [comment]
as a workaround
Adding newtonsoft (from ocelot service builder) removed the input and output formatter. 

Can be revert after the AddOcelot()

```
services.AddOptions<MvcOptions>().PostConfigure<IOptions<JsonOptions>, ILoggerFactory>((opts, jsonOpts, logger) => {
      if (opts.InputFormatters.OfType<SystemTextJsonInputFormatter>().Count() == 0)
      {
          opts.InputFormatters.RemoveType<NewtonsoftJsonInputFormatter>();
          opts.InputFormatters.Add(new SystemTextJsonInputFormatter(jsonOpts.Value,
              logger.CreateLogger<SystemTextJsonInputFormatter>()
          ));
      }
      if (opts.OutputFormatters.OfType<SystemTextJsonOutputFormatter>().Count() == 0)
      {
          opts.OutputFormatters.RemoveType<NewtonsoftJsonOutputFormatter>();
          opts.OutputFormatters.Add(new SystemTextJsonOutputFormatter(jsonOpts.Value.JsonSerializerOptions));
      }
  });
```

**Comment by raman-m** [comment]
Hi @WajahatAliAbid !
Thanks for your interest in Ocelot!

I hope your problem will be resolved by the linked PR in Development, right?
The linked PR has extensions, docs and samples including how to remove NewtonsoftJson lib from Ocelot core.
Enjoy! And watch for new release on October 1...  Soon... ⏲️

**Comment by WajahatAliAbid** [comment]
@raman-m Thank you. I went through the pull request and it certainly seems to solve the problem. Looking forward to the new release.

**Comment by raman-m** [comment]
@WajahatAliAbid
Use [20.0.0](https://www.nuget.org/packages/Ocelot/) version officially
