### ISSUE TITLE
Placeholder value does not correctly replace when the placeholder is defined between round braces

### ISSUE THREAD

**Issue by PratikPatel-Mtech** [ThreeMammals/Ocelot#1512]
## Expected Behavior 
The specified placeholder variable value should be replaced within the Downstream URI provided in the UpstreamPathTemplate and DownStreamPathTemplate. For instance,

Route Configurations:
```json
{
  "DownstreamPathTemplate": "/api/subscriptions({subscriptionId})/updates",
  "UpstreamPathTemplate": "/v1/subscriptions({subscriptionId})/updates",
  "UpstreamHttpMethod": [ "Get" ],
  "DownstreamScheme": "http",
  "DownstreamHostAndPorts": [
    { "Host": "localhost", "Port": 50110 }
  ]
}
```
When the request URI is `http://localhost:5001/v1/subscriptions(123)/updates`
Then the downstream request URI should be  `http://localhost:50110/api/subscriptions(123)/updates`

## Actual Behavior
It's adding extra round braces `)` in the Downstream request. It's a clear issue of replacing placeholder variables.

When the request URI is  `http://localhost:5001/v1/subscriptions(123)/updates`
Then the downstream request URI is `http://localhost:50110/api/subscriptions(123))/updates`

## Steps to Reproduce the Problem

  1. Add a route with the placeholder within the round braces
  2. Get parameter value in the downstream. Observed the value received at the downstream application.

**NOTE**: An issue is not with specific round braces. It reproduces with any other routes where the placeholder does not exactly(eg. `/{id}/` ) provide between slashes.

## Specifications

  - Version: 17.0.0
  - Platform: .NET 5

**Comment by ks1990cn** [comment]
Looks like this is from Microsoft aspnet inbuilt thing for Placeholder Value comming through HttpContext. 

But its really strange to note that from swagger for these routes we get right result.

probably swagger can implement this as it has UI for input, but from postman its tough to find any specific pattern. Example from swagger `/su((!))/row` is valid for route `/su({string}/row` 

 @raman-m @ggnaegi Any thoughts on this? 
 
![Screenshot (5)](https://github.com/ThreeMammals/Ocelot/assets/29522704/accbd20a-2f46-4ef9-9088-3e9c42773ee4)

**Comment by raman-m** [comment]
## Outdated issue :exclamation: 
Dear @PratikPatel-Mtech,
You need to upgrade your Ocelot solution to the latest version [23.3.0](https://github.com/ThreeMammals/Ocelot/releases/tag/23.3.0)!
Try to reproduce, and if the bug still persists then reopen new or this issue.
### You have the right to reopen this issue in the future if you come with a PR ready.
