### ISSUE TITLE
Dependency Injection extensions build the service provider

### ISSUE THREAD

**Issue by ArwynFr** [ThreeMammals/Ocelot#1518]
When using the default DI extension to register the Ocelot service, the library builds the service provider.
This causes problems with the dependency injection library.

- [Dependency injection in ASP.NET Core | Microsoft Learn](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/dependency-injection?view=aspnetcore-5.0#recommendations)

Source : https://github.com/ThreeMammals/Ocelot/blob/bb795876c493af958f1d58c852ea56e94263906d/src/Ocelot/DependencyInjection/ServiceCollectionExtensions.cs#L20

**Comment by ArwynFr** [comment]
Looks like using the extension method with the additional `IConfiguration` parameter does not build the service provider. Give it a try ?

**Comment by raman-m** [comment]
Hi @ArwynFr !
Welcome to Ocelot world! 🐯 

Does the problem persist in .NET 6+?
With Ocelot v18, . NET 6
With Ocelot v19, 20, .NET 7

**Comment by ArwynFr** [comment]
Hi @raman-m

I was using Ocelot for a project I'm no longer the maintainer of.
However the main branch source code still contains the faulty instruction:
https://github.com/ThreeMammals/Ocelot/blob/bb795876c493af958f1d58c852ea56e94263906d/src/Ocelot/DependencyInjection/ServiceCollectionExtensions.cs#L20

My understanding is that Ocelot builds the service provider in order to retrieve the root configuration section when the user does not provide it. This configuration section is then used to register the `FileConfiguration` option in the service collection. Instead of that, I suggest you look into [`OptionsBuilderConfigurationExtensions.BindConfiguration<TOptions>`](https://learn.microsoft.com/en-us/dotnet/api/microsoft.extensions.dependencyinjection.optionsbuilderconfigurationextensions.bindconfiguration?view=dotnet-plat-ext-8.0#microsoft-extensions-dependencyinjection-optionsbuilderconfigurationextensions-bindconfiguration-1(microsoft-extensions-options-optionsbuilder((-0))-system-string-system-action((microsoft-extensions-configuration-binderoptions)))) method to bind the option to a configuration path instead of instance.

The code would look like this:
```cs
Services.AddOptions<FileConfiguration>.BindConfiguration("DefaultPath");
```

However it will also make you unable to valuate the `OcelotBuilder.Configuration` property, so you have to check how this would impact the rest of the library. It would require to replace all code that accesses the `IConfiguration` section by options patterns.

Another strategy is to make the `IConfiguration` parameter mandatory by deprecating other extension methods.

**Comment by raman-m** [comment]
>@ArwynFr commented [on Jan 13](https://github.com/ThreeMammals/Ocelot/issues/1518#issuecomment-1890698747)

Arwyn, come on! Our project features were designed by Tom and the community 5+ years ago in times of .NET Core 1.1, 2.0, 3.1 🤣 
Thanks for your recommendations!
We need to remove ugly `IConfiguration` obj issue from extensions.
The problem is that we have hard nut validation feature which should be moved to a separate validation module making the pipeline more ASP.NET friendly.
As a team, we have some future plans to migrate from custom **ocelot.json** config files injection to standard **appsettings.json** files following standard approach of providing configurations in ASP.NET apps.
I have no idea why Tom had designed custom JSON files injection. It requires to write a lot of extra classes to perform additional extra checks. So, definitely usage of **appsettings.json** will solve a lot of design issues and limitations by **ocelot.json**.

@ggnaegi  FYI

**Comment by raman-m** [comment]
@ArwynFr  Do you have intention to contribute to resolve [the issue](https://github.com/ThreeMammals/Ocelot/issues/1518#issuecomment-1890698747)?

**Comment by ArwynFr** [comment]
I might contribute depending on the strategy you want to adopt, if that's not too much work.

I've looked into the removal of the `OcelotBuilder.Configuration` property but it breaks the forwarding of the `IConfiguration` instance to the Steeltoe discovery client in Eureka. I've made some dirty tweaks I think it should be better for SDC to use the root appsettings.json even when Ocelot uses another section of the configuration as a source, but that would be a breaking change. Also perhaps Ocelot should not use the root of appsettings.json but rather a default path (such as `Ocelot`) unless told otherwise. Again, depends on your vision of where the config of each component is expected to be stored by default and how non-breaking you want the change to be.

You can check my code here: https://github.com/ThreeMammals/Ocelot/compare/develop...ArwynFr:Ocelot:ArwynFr/issue1518

There's a tricky part near the `AddJwtBearer()`, that accesses the service provider to resolve services used the lambda that configures the authentication options ; you may deffer the access to the service provider by writing a `IConfigureNamedOptions<T>` which gets resolved with DI so you can inject your services at runtime.

Unfortunately I was unable to pass your tests on develop, so I'm unsure whether my code breaks stuff or not.

To access both the `ServiceCollection` and the `IConfiguration` you may consider extending the `IHostBuilder` instead of the `ServiceCollection`. This grants you access to the `IHostBuilder.ConfigureServices()` method which has a lambda with both. However this approach breaks most of your tests, so there's a lot of code rewrite to be expected.

**Comment by raman-m** [comment]
@ArwynFr  Let me come back to this issue after the release these days...

**Comment by raman-m** [comment]
@ArwynFr 
I'm inviting the rest of the team to discuss the topic about **ocelot.json** file design issue...

@RaynaldM @ggnaegi Welcome!
Seems we have to perform some design review of the Configuration feature which is based on **ocelot.json** file...
And migration to **appsettings.json** file is a right direction!...

**Comment by RaynaldM** [comment]
Absolutely not. "Ocelot" configurations can be very long, and mixing them up in appsettings.json seems counter-productive.
Even if you could make one or more partial appsettings.ocelot.json files, I don't see the point.

**Comment by ggnaegi** [comment]
> Absolutely not. "Ocelot" configurations can be very long, and mixing them up in appsettings.json seems counter-productive. Even if you could make one or more partial appsettings.ocelot.json files, I don't see the point.

Same opinion as @RaynaldM

**Comment by raman-m** [comment]
@RaynaldM @ggnaegi 
:ok: Here is my last try...
appsettings.json the file is tightly integrated into the ASP.NET pipeline and is controlled by the kernel.
This file and its configuration related services are optimized in the core, in pipeline and in DI... So, it has top performance and best usage practices. Developers recognize `IOptions` pattern and uses all config feature out of the ASP.NET box...
My opinion is that Tom had added support of parallel configuration pipeline just for having dev fan and learning ASP.NET possibilities.
His design is large and complex. Seems this design duplicates mostly all config features of ASP.NET...
Why should we support this monster logic with a long list of bugs and design gaps?

Regarding long ocelot-files... We can develop extra ETL tool to migrate from **ocelot.json** to **appsettings.json** easily.
All code-base will be decreased possibly in times.
But if Tom's ocelot.json config design has some interesting features, let me know please!

**Comment by raman-m** [comment]
@ArwynFr When will you create a PR to review?
As a team, we would like to fix only extra `BuildServiceProvider` calls inside of methods, nothing more

**Comment by RaynaldM** [comment]
I'm not an expert, and I haven't explored it thoroughly, but I think Tom has made full use of the standard configurationBuilder, and that, if you like, you can already put the contents of Ocelot.json in appSettings.json.

**Comment by ArwynFr** [comment]
> But if Tom's ocelot.json config design has some interesting features, let me know please!

@raman-m 
There's one feature that it has that cannot be replaced is the separation of the `ocelot.global.json` subpath.
In a dotnet 6+ context you would have to register 2 different `IOptions<T>`.
Also in order to support `ocelot.{env}.json` you need to pass the environment name which is not available from the context.

So I'm afraid in both cases you need to break the existing public interface :(

**Comment by ArwynFr** [comment]
So I finally managed to make a hotfix that does not brake current implementation at all, by building a separate ServiceProvider.

This code now works:
```cs
var builder = WebApplication.CreateBuilder();
builder.Configuration.AddJsonFile("ocelot.json");
builder.Services.AddOcelot();

var app = builder.Build();
await app.UseOcelot();
app.Run();
```

Beware that the `ConfigurationBuilderExtensions` class probably does not work like intended.
It mixes files with or without environment name, and does not seem consistent with `IFileConfigurationRepository`.

You now have basically 2 options regarding the options pattern adoption:
- You could keep all the `IFileConfigurationRepository` stuff as a facade, and have it acces either IOptionsMonitor<T> or Consul
- You could replace everything with the options pattern, in which case you need to turn Consul into a ConfigurationSource

Features like POSTing to the FileConfigurationController can be made tricky in the second case.

There is also a problem with the Ocelot middlewares preventing access to the controllers.

And there is still a problem with Steeltoe discovery client that also builds the service provider.
This should be fixed on their side.

**Comment by ggnaegi** [comment]
@ArwynFr Ok, it makes sense from architectural standpoint. From my side, I don't like that kind of black box approaches.

**Comment by ggnaegi** [comment]
@ArwynFr @raman-m It's probably the whole IOcelotBuilder logic that should be rewritten. It's a bit like what we have seen with the IOcelotLogger or the Http Client Pool. Some layers are not needed imo.

**Comment by raman-m** [comment]
We will return back to this problem after [Feb'24](https://github.com/ThreeMammals/Ocelot/milestone/5) release...
But you both can start refactoring now if you want.

**Comment by ArwynFr** [comment]
> It's probably the whole IOcelotBuilder logic that should be rewritten.

Yes that's exactly my point.
This, in turn, has huge side effects on Consul / Eureka as well as JWT auth.
#1986 is a first step, a mere hotfix to prevent some apps from crashing.

**Comment by raman-m** [comment]
@ArwynFr 
> https://github.com/ThreeMammals/Ocelot/pull/1986 is a first step, a mere hotfix to prevent some apps from crashing.

Sorry? What are you talking about, Arwyn?
Is this issue a bug? If bug, why not to describe it?
And, what apps are crashing? Could you be more concrete please?

What I know exactly now is that usage of service collection after the 1st building of service provider is very bad. And building collection or reading a service directly from service collection can lead to unpredicted behavior or even worst app crashing.
But we deal with legacy system and we have a lot of DI injection ignoring. Abuse of `delegate` usage makes me crazy when I support Ocelot... But we need to detect bottlenecks first, fix them, and after that we can start thinking about full re-design and full re-write of `OcelotBuilder`... @ggnaegi Do you have so much time to re-design `OcelotBuilder`? Seems not. Where? During your vacations?
@ArwynFr Or you, Arwyn, would like to re-write Ocelot kernel to follow best practices of DI usage? Seems we have to add extra 100 interfaces or even more, and add them to DI.

I suggest to focus on a small change with high level description being this issue. But I see zero PRs and zero proposals?
Only proposals... Nothing more.

**Comment by ArwynFr** [comment]
> Sorry? What are you talking about, Arwyn?
> Is this issue a bug? If bug, why not to describe it?
> And, what apps are crashing? How? When? Could you be more concrete please?

See https://github.com/ThreeMammals/Ocelot/issues/1518#issuecomment-923999886

Originally it was simply a "philosophical" problem, but it turned out some users had app crashes.
This affects any application trying to use Ocelot using a WebApplicationBuilder instead of Startup/Host pattern.
Startup and Host can still be used, but developpers are encouraged to migrate to WAB pattern since dotnet 6.

As you noticed, modifying the service collection after building the service provider is a bad practice and can cause the app to crash. The problem is with `AddOcelot()` extension methods without IConfiguration parameters. Developpers expect such methods to register service descriptors without building the service provider, so they can register multiple libs using a fluent API, then build the provider once they are done. As incriminated methods did build the provider and then tried to add descriptors, this caused apps to fail, and even crash depending on context.

PR #1986 fixes that by retrieving the IConfiuguration instance from the descriptor instead of building the provider.

For the future, Ocelot should move towards the `IOptionsMonitor<T>` pattern instead, but that's a lot of rewrite. This rewrite would allow to restrain OcelotBuilder to registering service decriptors without any reference to the IConfiguration. These services could access the configuration values by DI, without any knowledge of the configuration source. This would allow developpers to manage configuration sources independently from application feature services.

For example, you could write an aspnet application referencing Ocelot to provide API gateway features, and another lib providing configuration source from MongoDB. Ocelot would be able to source it's configuration from a MongoDB storage without Ocelot having to write any line of code. It would work out of the box, simply because the MongoDB configuration lib is an IConfiguration source provider and Ocelot is an IConfiguration source consumer.

**Comment by raman-m** [comment]
> The problem is with `AddOcelot()` extension methods without `IConfiguration` parameters.

I agree! This is the constant source of problems!
My proposal to remove this method (without `IConfiguration` parameter) at all!
Marking `[Obsolete]` will be fine too with your fix, @ArwynFr .
But I would like to remove the bad extension altogether and write release notes with a “Breaking Changes” paragraph to draw the community’s attention to the need to migrate application startups.

@ArwynFr @ggnaegi @RaynaldM   Your opinion? Let's vote!

**Comment by raman-m** [comment]
> For the future, Ocelot should move towards the `IOptionsMonitor<T>` pattern instead, but that's a lot of rewrite. This rewrite would allow to restrain `OcelotBuilder` to registering service descriptors without any reference to the `IConfiguration`. These services could access the configuration values by DI, without any knowledge of the configuration source. This would allow developers to manage configuration sources independently from application feature services.

Yes, exactly! Thanks you, @ArwynFr !
I will discuss with team this migrations...
My understanding is the following:
- **1st stage**. If there is no service injection in constructor and there is service builder called, then inject `IConfiguration` object to get required options.
- **2nd stage**. If Ocelot will behave stable, we can replace `IConfiguration` object with `IOptions<T>` or `IOptionsMonitor<T>` ones.

Seems releasing strategy requires separate milestone with an independent development.

**Comment by raman-m** [comment]
@RaynaldM  Don't worry, Ray, in this release it won't be removed. 🤣 
And in a couple of releases seems too. Considering our super low progress... 😏 
Once this time will come, we will start a debates again.
And finally, seems I've got why you joined the team... Not for public viewing
