### ISSUE TITLE
Is that Ocelot should be configured to support client credential flow(client id, secret)

### ISSUE THREAD

**Issue by chitharansivasamy** [ThreeMammals/Ocelot#1524]
## Expected Behavior / New Feature
Should support client credential (client_id, secret) and return bearer token then should send to ocelot endpoint. expecting should get a response once validated bearer token.

## Actual Behavior / Motivation for New Feature
unable to get a response 

## Steps to Reproduce the Problem

  . added download and upload stream path 
  . added middleware to get bearer token 
  

## Specifications

  - Version:
  - Platform:
  - Subsystem:

**Comment by raman-m** [comment]
Lack of description!
The description is abstract!
As a team, we cannot accept this issue.
