### ISSUE TITLE
.NET 6.0 support validation

### ISSUE THREAD

**Issue by kyrvlasiuk** [ThreeMammals/Ocelot#1533]
## New Feature .NET 6.0 support validation

Has anyone tried to validate that .NET 6 would work with latest version of ocelot? Currently we are on .NET Core 3.1 and planning a migration to .NET 6.0 (LTS releases). Seems that this project is not moving forward past .NET 5, so I would like to know how compatible .NET 5 release of ocelot is with .NET 6.  

Microsoft has published compatibility guidelines for migration to .NET 6: [Breaking changes in .NET 6](https://docs.microsoft.com/en-us/dotnet/core/compatibility/6.0). Has anyone investigated how ocelot is affected by these? 

About 50 percent of breaking changes are binary compatible, so there is hope.

**Comment by q7164518** [comment]
> ## New Feature .NET 6.0 support validation
> Has anyone tried to validate that .NET 6 would work with latest version of ocelot? Currently we are on .NET Core 3.1 and planning a migration to .NET 6.0 (LTS releases). Seems that this project is not moving forward past .NET 5, so I would like to know how compatible .NET 5 release of ocelot is with .NET 6.
> 
> Microsoft has published compatibility guidelines for migration to .NET 6: [Breaking changes in .NET 6](https://docs.microsoft.com/en-us/dotnet/core/compatibility/6.0). Has anyone investigated how ocelot is affected by these?
> 
> About 50 percent of breaking changes are binary compatible, so there is hope.

It works. I've already verified it in the test environment

**Comment by Guyiming** [comment]
Works well

**Comment by majid325** [comment]
f you wanna migrate to Dotnet 6, check this (#1548)

**Comment by raman-m** [comment]
Hi @kyrvlasiuk !

You can try any version of Ocelot packages.
Please note, Ocelot supports .NET 7 now after [19.0.2](https://www.nuget.org/packages/Ocelot) release. 
I would recommend you to upgrade your projects to this latest version!

**Comment by raman-m** [comment]
@kyrvlasiuk 
Your issue is outdated and obsolete!
