### ISSUE TITLE
Will Ocelot update again?

### ISSUE THREAD

**Issue by q7164518** [ThreeMammals/Ocelot#1534]
Will Ocelot update again?

**Comment by cryoelite** [comment]
Probably, but given Tom's status I doubt he has any time to work on Ocelot (Source below). Even if he does, there's a lot of stuff that would need to be kept updated regularly so it needs continuous maintenance. 

I would suggest moving to a more frequently updated gateway service like Consul, Istio, Tyk, KrakenD or something. Custom Authentication is also possible in some of them like in Tyk where you make a plugin out of your authentication project in .net. 

https://twitter.com/ThreeMammals/status/1404477172341948421?s=20

**Comment by q7164518** [comment]
> 可能吧， 但考虑到汤姆的地位， 我怀疑他是否有时间在奥塞洛特工作 （下面的来源） 。即使他这样做了， 也有很多东西需要定期更新， 所以它需要持续维护。
> 
> 我建议转到更频繁更新的网关服务， 如领事， 伊斯蒂奥， 泰克， 克拉肯德或什么的。自定义身份验证也是可能的，在其中一些，如在Tyk，在那里你使一个插件，你的认证项目在.net。
> 
> https://twitter.com/ThreeMammals/status/1404477172341948421?s=20

Ok, thank you for your answer
