### ISSUE TITLE
Problems accessing and using Register API documentation using Swagger UI

### ISSUE THREAD

**Issue by MetinTAPAN58** [ThreeMammals/Ocelot#1544]

**Comment by raman-m** [comment]
@ks1990cn  Tanmay,
Here is more funny problem from the same author! 🤣 

"I have problems" 😄 
- "[**Houston, we have a problem!**](https://www.youtube.com/watch?v=YwG4F-16Tno&t=40s)"  🤣

**Comment by raman-m** [comment]
@MetinTAPAN58 
We don't support Swagger!
See docs please: [Not Supported | Swagger](https://ocelot.readthedocs.io/en/latest/introduction/notsupported.html#swagger)

Sorry about that! 😇
