### ISSUE TITLE
Adding Tags to HostAndPort Section

### ISSUE THREAD

**Issue by burakoner** [ThreeMammals/Ocelot#1551]
## New Feature
Adding Tags to HostAndPort Section

## Motivation for New Feature
I have a project that contains both free and paid usage. People also can buy different levels of paid usage. But All users will use same endpoint (for example: api.example.com). I'm also using Load Balancer feature of Ocelot. So I created a CustomLoadBalancer to find out that user is free or paid. I'm redirecting free users to free servers, and paid users to paid servers. In fact I can do it now with my CustomLoadBalancer. But I'm using a hardcoded way. I assumefirst entry in ocelot.json DownstreamHostAndPorts as FREE SERVER, and second one as PAID SERVER. But I'll have lots of free and paid servers later. So I think if there is an Tags (string array) for each in DownstreamHostAndPorts entry, I can achieve my goal without pain. It'll become as below after change

```
"DownstreamHostAndPorts": [
  {
    "Host": "localhost",
    "Port": 7011,
    "Tags": ["Free"],
  },
  {
    "Host": "localhost",
    "Port": 7021,
    "Tags": ["Paid", "Tier 1"],
  },
  {
    "Host": "localhost",
    "Port": 7022
    "Tags": ["Paid", "Tier 2"],
  }
],
```

I'll be grateful if you add this feature in json config file. Have a nice day.

**Comment by burakoner** [comment]
Up

**Comment by moaz-fs** [comment]
Up

**Comment by raman-m** [comment]
Hi Burak!
Seems you need extra properties for the route, right?
Pay attention we have such request for custom route properties:
- #651 
- #1183 

```
"DownstreamHostAndPorts": [
  {
    "Host": "localhost",
    "Port": 7011,
    "Tags": ["Free"],
  },
  {
    "Host": "localhost",
    "Port": 7021,
    "Tags": ["Paid", "Tier 1"],
  },
  {
    "Host": "localhost",
    "Port": 7022
    "Tags": ["Paid", "Tier 2"],
  }
],
```
OK You've added tags to the object. What's next? Will still use your custom Load Balancer? See my recommendation below :point_down: 
You can control your hosts/ports by the following:
- Custom Load Balancer (you use this approach)
- Service Discovery (via Consul etc.)
- Custom properties with custom Delegating Handler (you have to wait for this feature)

And, sorry! We **will not** add new Tags property to the `DownstreamHostAndPort` model for your user scenario! You have to wait for Route Custom Props feature being delivered...

**Comment by raman-m** [comment]
**The feature request has not been accepted!**
