### ISSUE TITLE
Unable to use Quality of Service

### ISSUE THREAD

**Issue by somasundar1997** [ThreeMammals/Ocelot#1560]
# The enumerable of policies to form the wrap must contain at least two policies
Error Code: UnableToCompleteRequestError Message: Error making http request, exception: System.ArgumentException: The enumerable of policies to form the wrap must contain at least two policies. (Parameter 'policies')
         at Polly.Policy.WrapAsync(IAsyncPolicy[] policies)
         at Ocelot.Provider.Polly.PollyCircuitBreakingDelegatingHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)         at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
         at Ocelot.Requester.HttpClientHttpRequester.GetResponse(HttpContext httpContext) errors found in ResponderMiddleware. Setting error response for request path:/GetToken, request method: POST
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]

## Specifications
  - Version: 18.0.0 (both Ocelot & Ocelot.Provider.Polly)
  - Dotnet Version: 6.0

## Repository
I have attached the repository Url for your reference. 
Repository Url: https://github.com/somasundar1997/TestGateway

**Comment by carmendiem** [comment]
did you ever resolve this? if so how? thanks

**Comment by somasundar1997** [comment]
@carmendiem  I think this issue already has a PR #1279 I found that a few days after creating the issue. I was using this solution from then upto now that is working fine.

**Comment by somasundar1997** [comment]
@carmendiem I used that branch's build files(dll) in my project to fix the issue.

**Comment by somasundar1997** [comment]
@carmendiem when can I expect this PR #1279 to get merged

**Comment by somasundar1997** [comment]
@carmendiem ???

**Comment by carmendiem** [comment]
I don't know, I was only asking previously because I encountered the same issue in my code.

**Comment by raman-m** [comment]
@somasundar1997 and @carmendiem 
Hi! Thanks for discussion in the past!

PR #1279 was merged [on Sep 22, 2023](https://github.com/ThreeMammals/Ocelot/pull/1279#event-10450501693) in commit https://github.com/ThreeMammals/Ocelot/commit/21bc4a4a4bd848e5300a1595d3536cbe19429372 and released [on Oct 7, 2023](https://github.com/ThreeMammals/Ocelot/releases/tag/20.0.0).

Going to close this issue...
I look forward to your future contributions with interesting PRs! 😉 
Stay with Ocelot! 🐅

**Comment by raman-m** [comment]
Already fixed by PR https://github.com/ThreeMammals/Ocelot/pull/1279

@somasundar1997  FYI
We have some interesting updates of QoS in version [22.0.0](https://github.com/ThreeMammals/Ocelot/releases/tag/22.0.0). See commit dabb4b5e19f4b7bee428b8a4e992663ddc0a6d7d plz!
