### ISSUE TITLE
The archive entry was compressed using an unsupported compression method.

### ISSUE THREAD

**Issue by NamanV19** [ThreeMammals/Ocelot#1564]
## Expected Behavior / New Feature
Error should not be thrown when decompressing.

## Steps to Reproduce the Problem

1. I followed the example of custom aggregation by miss Neetra. The keys and aggregates in ocelot.json are okay too.
My Code:
![image](https://user-images.githubusercontent.com/43335375/155546803-83cfd1d8-5611-4cdc-9d43-d1a8023d922a.png)

The error:
![image](https://user-images.githubusercontent.com/43335375/155547437-13c85180-c9f6-4159-a5f1-1a9346322bfd.png)

## Specifications
![image](https://user-images.githubusercontent.com/43335375/155546973-3e975bdb-d002-4115-98e6-dbb36313da2c.png)

**Comment by raman-m** [comment]
Hi Naman!
What did you do? :confused:

> ## Expected Behavior / New Feature
> Error should not be thrown when decompressing.

Are you kidding?
Ocelot is not responsible for your custom code in custom user classes.
To catch and process the exception, wrap code snippet by `try-catch` block.

I don't see your `Decompress` method. Cannot advise or review!

**Have you tried this compression/decompression setup in empty ASP.NET Web app project?** Seems you haven't!...
Are you sure it works at all?

**Comment by raman-m** [comment]
Sorry, we cannot accept the issue.
You have the right to reopen in future if you will show real arguments that this is Ocelot's problem.
