### ISSUE TITLE
How to define multiple DownstreamPathTemplates to work for one UpstreamPathTemplate?

### ISSUE THREAD

**Issue by fdevGit** [ThreeMammals/Ocelot#1574]
Hello,
quick question. How to set up an incoming request to redirect to more than one endpoint

I'm thinking something like this, I will meet at separate endpoints for both the function and the counter of a request.

Regards !

**Comment by ks1990cn** [comment]
Just want to hit two enpoints means? you can use HttpClient from polly libraray and in same controller you can call two endpoints.
Ocelot is api gateway, these things are not part of gateway instead you need your backend logic for it.

@fdevGit

**Comment by ggnaegi** [comment]
@fdevGit You could implement your own delegating handler https://ocelot.readthedocs.io/en/latest/features/delegatinghandlers.html and call the counter endpoint from there with HttpClient.

**Comment by ks1990cn** [comment]
@ggnaegi I have question here: if anyone add some time consuming logic in SendAsync method, will it slow down application startup time or any time for request to reach controller level of same api?
