### ISSUE TITLE
Support several AuthenticationProviderKey values in the Route

### ISSUE THREAD

**Issue by MayorSheFF** [ThreeMammals/Ocelot#1580]
## New Feature
Opportunity to support several [AuthenticationProviderKey](https://ocelot.readthedocs.io/en/latest/features/authentication.html?highlight=AuthenticationProviderKey) values in the Route.

## Motivation for New Feature
At the moment, [Route](https://github.com/ThreeMammals/Ocelot/blob/develop/src/Ocelot/Configuration/DownstreamRoute.cs) can contain one [AuthenticationProviderKey](https://github.com/ThreeMammals/Ocelot/blob/develop/src/Ocelot/Configuration/AuthenticationOptions.cs#L12) value only. So, if we want to handle Route for different authentication providers, we have to specify two Routes and make Route path unique. Sometime it is not so easy to specify unique paths for the same endpoint.

## Useful Links
- [Features | Authentication](https://ocelot.readthedocs.io/en/latest/features/authentication.html) &rarr; ([authentication.rst](https://github.com/ThreeMammals/Ocelot/blob/develop/docs/features/authentication.rst)), Ocelot docs
- [Authorize with a specific scheme in ASP.NET Core | Use multiple authentication schemes](https://learn.microsoft.com/en-us/aspnet/core/security/authorization/limitingidentitybyscheme?view=aspnetcore-8.0#use-multiple-authentication-schemes), Microsoft Learn
- [Basic Authentication in C# / .NET](https://scatteredcode.net/basic-authentication-in-c-sharp-net/), ScatteredCode by Alexandru Puiu
- [.NET 6.0 - Basic Authentication Tutorial with Example API](https://jasonwatmore.com/post/2021/12/20/net-6-basic-authentication-tutorial-with-example-api), Jason Watmore's Blog

## Related
- #446 
- #1002

**Comment by MayorSheFF** [comment]
I made some changes locally to solve it, but I just want to discuss if it is necessary for everyone and maybe someone is currently trying to solve too.

**Comment by MayorSheFF** [comment]
I am still having these changes. Can someone from owners look at it and accept if it is OK?

**Comment by sivapriyanc** [comment]
Hi @MayorSheFF  could you please share the code snippet

**Comment by MayorSheFF** [comment]
Hi, @sivapriyanc.

This function was added into `AuthenticationMiddleware` class.


        private async Task<AuthenticateResult> AuthenticateAsync(HttpContext httpContext, DownstreamRoute route)
        {
            AuthenticateResult result = null;

            if (!string.IsNullOrWhiteSpace(route.AuthenticationOptions.AuthenticationProviderKey))
            {
                result = await httpContext.AuthenticateAsync(route.AuthenticationOptions.AuthenticationProviderKey);
                if (result.Succeeded)
                {
                    return result;
                }
            }

            IEnumerable<string> authenticationProviderKeys =
                route
                .AuthenticationOptions
                .AuthenticationProviderKeys
                ?.Where(apk => !string.IsNullOrWhiteSpace(apk))
                ?? Array.Empty<string>();

            foreach (var authenticationProviderKey in authenticationProviderKeys)
            {
                result = await httpContext.AuthenticateAsync(authenticationProviderKey);
                if (result.Succeeded)
                {
                    break;
                }
            }

            return result;
        }

Then, it is using in `Invoke` method, namely `var result = await AuthenticateAsync(httpContext, downstreamRoute);` row.

        public async Task Invoke(HttpContext httpContext)
        {
            var downstreamRoute = httpContext.Items.DownstreamRoute();

            if (httpContext.Request.Method.ToUpper() != "OPTIONS" && IsAuthenticatedRoute(downstreamRoute))
            {
                Logger.LogInformation($"{httpContext.Request.Path} is an authenticated route. {MiddlewareName} checking if client is authenticated");

                var result = await AuthenticateAsync(httpContext, downstreamRoute);

                httpContext.User = result.Principal;

                if (httpContext.User.Identity.IsAuthenticated)
                {
                    Logger.LogInformation($"Client has been authenticated for {httpContext.Request.Path}");
                    await _next.Invoke(httpContext);
                }
                else
                {
                    var error = new UnauthenticatedError(
                        $"Request for authenticated route {httpContext.Request.Path} by {httpContext.User.Identity.Name} was unauthenticated");

                    Logger.LogWarning($"Client has NOT been authenticated for {httpContext.Request.Path} and pipeline error set. {error}");

                    httpContext.Items.SetError(error);
                }
            }
            else
            {
                Logger.LogInformation($"No authentication needed for {httpContext.Request.Path}");

                await _next.Invoke(httpContext);
            }
        }

The following files were changed too. It allows to get values from the configuration.

- `AuthenticationOptions` class;
- `AuthenticationOptionsBuilder` class;
- `AuthenticationOptionsCreator` class;
- `FileAuthenticationOptions` class;
- `RouteOptionsCreator` class.

**Comment by MayorSheFF** [comment]
Hi @raman-m,

I would be very glad to push my local branch to GitHub, but I have the following issue.

```
Remote: Permission to ThreeMammals/Ocelot.git denied to MayorSheFF.
Error encountered while pushing to the remote repository: Git failed with a fatal error.
Git failed with a fatal error.
unable to access 'https://github.com/ThreeMammals/Ocelot.git/': The requested URL returned error: 403
```

Maybe I make something wrong. Can someone help to figure out the reason?

**Comment by sivapriyanc** [comment]
@raman-m  Even we have a scenario to support multiple identity server, one for internal and external

**Comment by raman-m** [comment]
@MayorSheFF  Igor,

> I would be very glad to push my local branch to GitHub, but I have the following issue.
> ```
> Remote: Permission to ThreeMammals/Ocelot.git denied to MayorSheFF.
> Error encountered while pushing to the remote repository: Git failed with a fatal error.
> Git failed with a fatal error.
> unable to access 'https://github.com/ThreeMammals/Ocelot.git/': The requested URL returned error: 403
> ```
>Maybe I make something wrong.

Yes, you may!
You need to create a fork of Ocelot in your account!
Read these articles which will help you to make new forked repository:
- [About forks](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/about-forks)
- [Fork a repo](https://docs.github.com/en/get-started/quickstart/fork-a-repo)

As soon as you've created a fork you will be able to create feature branches, and create PR(s) for feature delivery to upstream (parent) repository, which is **ThreeMammals/Ocelot** repo.

**Comment by raman-m** [comment]
Igor, 

On my opinion, the easiest solution for your user's scenario will be the following:
- Create two controllers in one ASP.NET Web API app to separate security models
- Implement 2 authorization filters for each security model (for each Azure Active Directory)
- Embed, add 2 authorization filters into ASP.NET MVC pipeline to authorization middleware
- Create 2 Routes in Ocelot config to separate traffic for these 2 security models having one AuthenticationProviderKey scheme only for Ocelot Authentication middleware

What about this solution?

**Comment by MayorSheFF** [comment]
Hi, @raman-m.

> You need to create a fork of Ocelot in your account!

I will try to look at it today. Thank you for your advice.

**Comment by MayorSheFF** [comment]
@raman-m,

I will answer on all your suggestions what your described in two last messages.

On the figure below you can see very rough architecture how it was before these changes and how it is after these changes (new implementation).

![image](https://github.com/ThreeMammals/Ocelot/assets/54959243/e448679c-e568-4de3-b9c0-a4b1cd9a423e)

Just imagine. Before our application had the internal users only. So, these internal users send requests to our microservices by means of different clients (web, mobile, desktop etc.). Then, business came to developers and infrastructures and ask for giving an ability other users to use the microservices. At that moment, external users appeared in our system. But the main question for business is how to do it with less resources: money, time, development, delivery etc. and leave our architecture transparent. Starting from this point, I will ask you the question. Will you implement all your suggestions and in the same time adhere business requirements? Our answer was: "We can extend our API Gateway / Ocelot to handle two identity providers." So, we extended Ocelot to authenticate requests via several identity providers. It took about 3 days. OK. Let's say 5 days (1 working week). Maybe 4 days if you are in the country where 1 working week = 4 days. So, these 5 days are development, test and delivery. Also, it is good solution too from architecture perspective.

Maybe it is very rough description, but the general idea is like that.

I my standpoint, this implementation can be useful for other people too who will run into the same questions. Due to it, I suggested to look at it Ocelot team.

**Comment by raman-m** [comment]
> @MayorSheFF commented [on Jun 1](#issuecomment-1571519668)

🆗 I see... Having multiple identity services in the project is the real challenge! 🤣 
How did you solve the problem? Is your solution based on Ocelot [AuthenticationMiddleware overriding](#issuecomment-1567969390) to eliminate the problem of single provider key?!

You could also split Ocelot gateway into 2 instance which of them should support one provider key. But this approach requires more hardware resources and DevOps.

Also, as @clintonbale suggested [on Jun 27, 2022](#issuecomment-1167724993), you can setup Active Directory services to generate special custom header, forward that HTTP header to Ocelot gateway, and reuse Clinton's solution services setup to recognize AD user and auth provider key.

**So, what solution is in production now?**

**Comment by raman-m** [comment]
The issue has been [accepted](#event-10320268222) due to already opened PR #1666 
- #1666

**Comment by raman-m** [comment]
@MayorSheFF Igor,
Can I ask your help to search for the similar [issues in backlog](../issues) please?
Use key words: `AuthenticationProviderKey`, `Authentication`, etc.
We could attach them to your current open PR if those issues will be relevant...

**Comment by dkornel** [comment]
Hi all,

What is the status of this PR https://github.com/ThreeMammals/Ocelot/pull/1870 ?

Do you need help with testing ?

We are waiting for this feature and we are wondering if we can wait for you to release that or we need to implement the way around it.

Is it the matter of week/month ?

**Comment by raman-m** [comment]
@dkornel  Hi Kornel!

> What is the status of this PR https://github.com/ThreeMammals/Ocelot/pull/1870 ?

**In Progress**. The author doesn't develop his PR anymore. As a Pair Programming participant I am finishing the PR to get "Code Complete" status. 

----
> Do you need help with testing ?

Sorry? How you could help us?  Unit tests are ready. I'm finishing acceptance testing... They are most complicated part of the PR.  Will you write some interesting user scenarios?
Pay attention I work in the author's feature branch. I have access as repo Maintainer. But you cannot push to [forked repo](https://github.com/MayorSheFF/MayorSheFF-Ocelot) [branch](https://github.com/MayorSheFF/MayorSheFF-Ocelot/tree/feature/1580-several-auth-options). Asking the author to add you as collaborator probably will take to much time, finally with no reply from the author.
Also, I will not move the code to head repo branch because it is too late.

---
> We are waiting for this feature and we are wondering if we can wait for you to release that or we need to implement the way around it.
Is it the matter of week/month ?

Week. No more!

**Comment by raman-m** [comment]
@dkornel If you need this feature ASAP then there are 2 possible ways
- you just clone author's repo and checkout the feature branch, and compile dedicated DLL with the feature which is 99% ready. **Note!** The feature branch contains all features of current upcoming release!
- you write custom authorization policy by native ASP.NET features: 
  - [Selecting the scheme with policies](https://learn.microsoft.com/en-us/aspnet/core/security/authorization/limitingidentitybyscheme?view=aspnetcore-8.0#selecting-the-scheme-with-policies)
  - [Policy-based authorization in ASP.NET Core](https://learn.microsoft.com/en-us/aspnet/core/security/authorization/policies?view=aspnetcore-8.0)

**Comment by raman-m** [comment]
@clintonbale commented [on Jun 27, 2022](https://github.com/ThreeMammals/Ocelot/issues/1580#issuecomment-1167724993):

> 
> config:
> ```json
> "AuthenticationProviderKey": "AnyAuthenticated"
> ```
> ### ...
> But I'm not the happiest with this approach and would prefer having support for an array in the config, something like:
> 
> ```json
> "AuthenticationProviderKeys": [ "Bearer", "ExampleAuthScheme" ]
> ```

Clinton,
Why did you propose the new property as extra one for `AuthenticationProviderKey`?
Why array-like approach?
Maybe 👇 
```json
"AuthenticationProviderKey": "Bearer ExampleAuthScheme",
```
Will not this simple convention work when you write all schemes in old property, separating by whitespace?

If extend the idea of using old property, we can propose any delimiter approach 👉 
```json
"AuthenticationProviderKey": "Bearer ExampleAuthScheme",
"AuthenticationProviderKey": "Bearer, ExampleAuthScheme",
"AuthenticationProviderKey": "Bearer | ExampleAuthScheme",
"AuthenticationProviderKey": "Bearer+Bearer2+ExampleAuthScheme",
```
So, having non-alpha character in the value will instruct the validator and logic that we are running into multiple auth schemes workflow.
I am not a fan of the new `AuthenticationProviderKeys` property in plural form of old one.

**Comment by dkornel** [comment]
@raman-m 

We had a team discussion, that we will need this feature, and we need to assess if we have time to wait for this PR to land in the ocelot release or we should rather start developing our solution. We don't need this feature now but in a month. 

> Sorry? How could you help us? Unit tests are ready. I'm finishing acceptance testing... They are most complicated part of the PR. Will you write some interesting user scenarios?

I kindly ask if you need help because if the PR stucked, I could talk with manager and dedicate c# developer for help (explaining that time of building our solution > time of supporting this PR).

No offence.

**Comment by raman-m** [comment]
@dkornel 🆗 Wait for our official release please next week! This feature will be merged next week before [the release](https://github.com/ThreeMammals/Ocelot/milestone/2) for sure.
We're finishing of testing in Prod env of our team member now...

Any contributions and interesting PRs are welcome! But seems we needn't your urgent help here.
The #1870 PR was stuck because I was on sick leave for 2+ weeks. 😉

**Comment by clintonbale** [comment]
> @clintonbale commented [on Jun 27, 2022](https://github.com/ThreeMammals/Ocelot/issues/1580#issuecomment-1167724993):
> 
> > config:
> > ```json
> > "AuthenticationProviderKey": "AnyAuthenticated"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ### ...
> > But I'm not the happiest with this approach and would prefer having support for an array in the config, something like:
> > ```json
> > "AuthenticationProviderKeys": [ "Bearer", "ExampleAuthScheme" ]
> > ```
> 
> Clinton, Why did you propose the new property as extra one for `AuthenticationProviderKey`? Why array-like approach? Maybe 👇
> 
> ```json
> "AuthenticationProviderKey": "Bearer ExampleAuthScheme",
> ```
> 
> Will not this simple convention work when you write all schemes in old property, separating by whitespace?
> 
> If extend the idea of using old property, we can propose any delimiter approach 👉
> 
> ```json
> "AuthenticationProviderKey": "Bearer ExampleAuthScheme",
> "AuthenticationProviderKey": "Bearer, ExampleAuthScheme",
> "AuthenticationProviderKey": "Bearer | ExampleAuthScheme",
> "AuthenticationProviderKey": "Bearer+Bearer2+ExampleAuthScheme",
> ```
> 
> So, having non-alpha character in the value will instruct the validator and logic that we are running into multiple auth schemes workflow. I am not a fan of the new `AuthenticationProviderKeys` property in plural form of old one.

Plural approach makes sense because it is listing multiple keys. But for backwards compatibility the singular property should not be removed of course.

You could have both properties maybe? `AuthenticationProviderKey` could get/set `AuthenticationProviderKeys[0]`. Only one property allowed to be set at a time at the config level.

If this is too difficult then your white space approach is acceptable, just needs to be well documented. White space would no longer be acceptable in the key names either.

**Comment by raman-m** [comment]
@clintonbale Good proposal...

> But for backwards compatibility the singular property should not be removed of course.

Agree.

As a team, we've [decided](https://github.com/ThreeMammals/Ocelot/pull/1870#issuecomment-1912072576) to go with the current design. So, this is the same you've recommended.
And we will mark old `AuthenticationProviderKey` property with `[Obsolete]` attribute.
