### ISSUE TITLE
Upload big file but return  499 Client Closed Request

### ISSUE THREAD

**Issue by zrf518** [ThreeMammals/Ocelot#1584]
There is a question:

use postman/swagger to upload large files directly succeeded.
But when using the gateway Ocelot, it returns 499. 

The gateway module is also configured with large file upload.
 my NetCore is 3.1 and Ocelot is 16.0.1. 
 
Why? How to deal with it,Tks!!!
![image](https://user-images.githubusercontent.com/32395201/179183928-30f4017b-d0c6-45da-bb08-94532addaafb.png)

**Comment by ks1990cn** [comment]
Hi,

@zrf518 can you please explain how you have configured to accept large file upload & please us know hosting environment on which you faced this issue.

Issue https://github.com/ThreeMammals/Ocelot/issues/749 and I also tried that above 30MB file upload we get 404, so I raised PR for status code 413.

**Comment by raman-m** [comment]
@zrf518 Are you still with Ocelot?

**Comment by raman-m** [comment]
## Outdated issue :exclamation: 
@zrf518 You have to upgrade your solution to the latest Ocelot version [23.3.0](https://github.com/ThreeMammals/Ocelot/releases/tag/23.3.0), and try to reproduce the bug once again.
We believe this problem should not be in latest versions.

### You have the right to reopen this issue in the future if you come with a PR ready.
