### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by 1nfected** [ThreeMammals/Ocelot#1588]
Is this still being actively deveoped any more?

I ask because I don't see any meaninful feature additions in a while.
There's hardly any response on open issues either.

Sorry if this is rude.

**Comment by li-zheng-hao** [comment]
maybe, It's been six months since a new commit

**Comment by default-kaas** [comment]
> Is this still being actively deveoped any more?
> 
> I ask because I don't see any meaninful feature additions in a while. There's hardly any response on open issues either.
> 
> Sorry if this is rude.

You could try Yarp.

https://github.com/microsoft/reverse-proxy

https://microsoft.github.io/reverse-proxy/articles/authn-authz.html

**Comment by ks1990cn** [comment]
I think members are no more active!

**Comment by ks1990cn** [comment]
Yeah seems like no one is handling this any more but we can use its features, it cool!
