### ISSUE TITLE
Service Discovery and SignalR support

### ISSUE THREAD

**Issue by jbonnett92** [ThreeMammals/Ocelot#1599]
## Expected Behavior / New Feature
Using service discovery, enable the selction of multiple services to get a SignalR connection.

In my case I have multiple API services that host a SignalR endpoint, I am using a SignalR [backplane](https://docs.microsoft.com/en-us/aspnet/signalr/overview/performance/scaleout-in-signalr) to route messages to the multiple endpoints, so that no matter the endpoint the client is connected to gets the message.

Using config like the following:
```
{
  "Routes": [
    {
      "DownstreamPathTemplate": "/signalr",
      "DownstreamScheme": "ws",
      "ServiceName": [
        "identity-http-api-service",
        "products-http-api-service"
      ],
      "UpstreamPathTemplate": "/signalr",
      "LoadBalancerOptions": {
        "Type": "CookieStickySessions"
      }
    },
    {
      "DownstreamPathTemplate": "/signalr/{path}",
      "DownstreamScheme": "ws",
      "ServiceName": [
        "identity-http-api-service",
        "products-http-api-service"
      ],
      "UpstreamPathTemplate": "/signalr/{path}",
      "LoadBalancerOptions": {
        "Type": "CookieStickySessions"
      }
    }
  ]
}
```

## Actual Behavior / Motivation for New Feature
Not able to select multiple services using the "ServiceName" config. This is a huge problem if you want to split functionality up into multiple services.

## Steps to Reproduce the Problem
  1. Host multiple services with a SignalR connection with multiple instances of each
  2. Add to the config the service names you wish to access SignalR via
  3. Check connection

## Specifications

  - Version: 18.0.0
  - Platform: All
  - Subsystem: All

**Comment by raman-m** [comment]
@jbonnett92  Hi Jamie!
Good idea!
Are you still with Ocelot?

**Comment by raman-m** [comment]
@ggnaegi 
What do you think?

**Comment by jbonnett92** [comment]
> @jbonnett92 Hi Jamie! Good idea! Are you still with Ocelot?

No, I moved to YARP which has this functionality and it is arguably better.

**Comment by raman-m** [comment]
Did I understand right, you are not interested anymore and you don't use Ocelot too?
🆗 man!
Wish you good luck with Ya-Ya gateway!

**Comment by raman-m** [comment]
@ggnaegi 
I'm still open for discussions, but without the author. We can open another discussion thread.
