### ISSUE TITLE
Internal server error after updating Ocelot to version 18

### ISSUE THREAD

**Issue by SydFranco** [ThreeMammals/Ocelot#1600]
## Expected Behavior / New Feature
I'm getting error 500 after updating Ocelot to version 18.0.0.

## Actual Behavior / Motivation for New Feature
I was using Ocelot 13.8 but had to update my app to .net 6.0, so I took Ocelot to version 18.

## Steps to Reproduce the Problem
I have a pipeline like this in Startup.cs:

`
app.UseOcelot((builder, configuration) =>
{
    ILog log = app.ApplicationServices.GetRequiredService<ILog>();

    // This is registered to catch any global exceptions that are not handled It also
    // sets the Request Id if anything is set globally
    builder.UseExceptionHandlerMiddleware();

    // This is registered first so it can catch any errors and issue an appropriate response
    app.UseResponderMiddleware();

    // Then we get the downstream route information
    builder.UseDownstreamRouteFinderMiddleware();

    // This security module, IP whitelist blacklist, extended security mechanism
    builder.UseSecurityMiddleware();

    // Add request logging middleware using logger.
    builder.UseRequestLogMiddleware(log);

    // Ensuring standard new relic metrics categorization.
    builder.UseNewRelicTransactionsMiddleware();

    // Now we have the ds route we can transform headers and stuff?
    builder.UseHttpHeadersTransformationMiddleware();

    // Initialises downstream request
    builder.UseDownstreamRequestInitialiser();

    // We check whether the request is ratelimit, and if there is no continue processing
    builder.UseRateLimiting();

    // This adds or updates the request id (initally we try and set this based on global
    // config in the error handling middleware) If anything was set at global level and
    // we have a different setting at re route level the global stuff will be
    // overwritten This means you can get a scenario where you have a different request
    // id from the first piece of middleware to the request id middleware.
    builder.UseRequestIdMiddleware();

    // Now we know where the client is going to go we can authenticate them.
    builder.UseAuthenticationMiddleware();

    // The next thing we do is look at any claims transforms in case this is important
    // for authorisation
    builder.UseClaimsToClaimsMiddleware();

    // Now we have authenticated and done any claims transformation we can authorise the request
    builder.UseAuthorizationMiddleware();

    // Now we can run the claims to headers transformation middleware
    builder.UseClaimsToHeadersMiddleware();

    // Now we can run any claims to query string transformation middleware
    builder.UseClaimsToQueryStringMiddleware();

    // Get the load balancer for this request
    builder.UseLoadBalancingMiddleware();

    // This takes the downstream route we retrieved earlier and replaces any
    // placeholders with the variables that should be used
    builder.UseDownstreamUrlCreatorMiddleware();

    // Not sure if this is the best place for this but we use the downstream url as the
    // basis for our cache key.
    builder.UseOutputCacheMiddleware();

    //We fire off the request and set the response on the scoped data repo
    builder.UseHttpRequesterMiddleware();

    builder.Build();
}).GetAwaiter().GetResult();
`

In case I use only one app.UseOcelot().Wait(); everything works, but I need the pipeline steps as is.

## Specifications

  - Version: NETCore 6.0
   - Platform: Ocelot 18.0.0
   - Subsystem:

**Comment by ashumakov** [comment]
Hi,

Here you are missing two middlewares.
1. At the beginning of your pipeline configuration  -   **builder.UseDownstreamContextMiddleware();**
2. Add this one before builder.UseSecurityMiddleware() - **builder.UseMultiplexingMiddleware();**

**Comment by SydFranco** [comment]
Thanks @ashumakov. Add the 2 lines and it's working again! 

Thank you!!
