### ISSUE TITLE
Unable to start Ocelot because either a Route or GlobalConfiguration are using ServiceDiscoveryOptions but no ServiceDiscoveryFinderDelegate has been registered

### ISSUE THREAD

**Issue by michalgrzyska** [ThreeMammals/Ocelot#1602]
I have this error:

`System.AggregateException: 'One or more errors occurred. (Unable to start Ocelot, errors are: Unable to start Ocelot, errors are: Unable to start Ocelot because either a Route or GlobalConfiguration are using ServiceDiscoveryOptions but no ServiceDiscoveryFinderDelegate has been registered in dependency injection container. Are you missing a package like Ocelot.Provider.Consul and services.AddConsul() or Ocelot.Provider.Eureka and services.AddEureka()?,Unable to start Ocelot, errors are: Unable to start Ocelot because either a Route or GlobalConfiguration are using ServiceDiscoveryOptions but no ServiceDiscoveryFinderDelegate has been registered in dependency injection container. Are you missing a package like Ocelot.Provider.Consul and services.AddConsul() or Ocelot.Provider.Eureka and services.AddEureka()?)'`

My ocelot.json:

```
{
  "Routes": [
    {
      "DownstreamPathTemplate": "/Auth/{everything}",
      "DownstreamHostAndPorts": [
        {
          "Host": "localhost",
          "Port": 7074
        }
      ],
      "UpstreamPathTemplate": "/api/auth/{everything}",
      "ServiceName": "auth",
      "SwaggerKey": "auth"
    },
    {
      "DownstreamPathTemplate": "/User/{everything}",
      "DownstreamHostAndPorts": [
        {
          "Host": "localhost",
          "Port": 7244
        }
      ],
      "UpstreamPathTemplate": "/api/user/{everything}",
      "ServiceName": "user",
      "SwaggerKey": "user"
    }
  ],
  "SwaggerEndPoints": [
    {
      "Key": "auth",
      "Config": [
        {
          "Name": "Auth API",
          "Version": "v1",
          "Url": "https://localhost:7074/swagger/v1/swagger.json"
        }
      ]
    },
    {
      "Key": "user",
      "Config": [
        {
          "Name": "User API",
          "Version": "v1",
          "Url": "https://localhost:7244/swagger/v1/swagger.json"
        }
      ]
    }
  ],
  "GlobalConfiguration": {
    "BaseUrl": "http://localhost"
  }
}

```
My Program.cs:

```
using Ocelot.DependencyInjection;
using Ocelot.Middleware;

var builder = WebApplication.CreateBuilder(args);
builder.Configuration.AddJsonFile("ocelot.json");

builder.Services.AddControllers();
builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen();

builder.Services.AddOcelot();
builder.Services.AddSwaggerForOcelot(builder.Configuration);

var app = builder.Build();

if (app.Environment.IsDevelopment())
{
    app.UseSwagger();
    app.UseSwaggerUI();
}

app.UseHttpsRedirection();

app.UseAuthorization();
app.UseSwaggerForOcelotUI();
app.MapControllers();
app.UseOcelot().Wait();

app.Run();
```

What else is needed? Why should I use Eureka or Consul?

**Comment by ashumakov** [comment]
Hi,

Just remove "ServiceName" from ocelot.json.

**Comment by raman-m** [comment]
> What else is needed? Why should I use Eureka or Consul?

The [ServiceName](https://ocelot.readthedocs.io/en/latest/features/servicediscovery.html?highlight=ServiceName) property is a part of [Service Discovery](../blob/develop/docs/features/servicediscovery.rst) feature.
And you haven't enabled Service Discovery in configs. That's why you see exception.

It seems you define classic routes without service discovery. As @ashumakov [suggested](#issuecomment-1250380268), you have to remove **ServiceName** property from routes.
