### ISSUE TITLE
ocelot Error: socket hang up docker

### ISSUE THREAD

**Issue by mohrmz** [ThreeMammals/Ocelot#1609]
ocelot only works when visual studio debug is running in docker compose but when visual studio stop debugging I have Error: socket hang up in docker

{
  "Routes": [
    {
      "DownstreamPathTemplate": "/Patient/",
      "DownstreamScheme": "http",
      "DownstreamHostAndPorts": [
        {
          "Host": "fhir-api",
          "Port": "8080"
        }
      ],
      "UpstreamPathTemplate": "/Patient/",
      "UpstreamHttpMethod": [ "POST", "PUT" ],
      "FileCacheOptions": { "TtlSeconds": 40 }
    },
    {
      "DownstreamPathTemplate": "/Patient{everything}",
      "DownstreamScheme": "http",
      "DownstreamHostAndPorts": [
        {
          "Host": "fhir-api",
          "Port": "8080"
        }
      ],
      "UpstreamPathTemplate": "/Patient{everything}",
      "UpstreamHttpMethod": [ "GET" ]
    }
  ]
}

I request in post man with
http://localhost:8010/Patient/?given=Mohammad

my containers is running but Ocelot only works with visual studio debugging

**Comment by raman-m** [comment]
:rofl:
