### ISSUE TITLE
Need more features for the Websockets

### ISSUE THREAD

**Issue by dimevit** [ThreeMammals/Ocelot#1613]
##  New Feature
We are very interesting in integrating the Ocelot in our project, however we do need some of the websocket features with the following priorities

Delegating Handlers
Authentication - If anyone requests it we might be able to do something with basic authentication.
Authorization
Header Transformation

RequestId
Tracing
Request Aggregation
Rate Limiting
Quality of Service
Middleware Injection
Claims Transformation
Caching

are any plans to develope them?

**Comment by raman-m** [comment]
> are any plans to develope them?

Any plans on contribution to our project?

**Comment by raman-m** [comment]
@dimevit 
You need features? &rarr; **Contribute!**

**Comment by raman-m** [comment]
Dear @dimevit,
### You have the right to reopen this issue in the future if you come with a PR ready.
