### ISSUE TITLE
Add more context to logs (for example the request trace id)

### ISSUE THREAD

**Issue by shahargl** [ThreeMammals/Ocelot#1617]
## Expected Behavior / New Feature
I'll be able to extend the default logging context - for example, extract trace id from the header and add it to the logs

## Actual Behavior / Motivation for New Feature
This is not currently possibly

## Steps to Reproduce the Problem

  1. Any request to the ocelot gw with trace id header

**Comment by shahargl** [comment]
Is there any way to achieve this?

**Comment by shahargl** [comment]
And on another note - is there any way to get invitation to the slack workspace?

**Comment by raman-m** [comment]
Hi @shahargl 
Which Slack workspace are you talking about?

**Comment by raman-m** [comment]
I guess this PR #1745 will be interesting for you because we enhance logging now. But we improve performance... it is not about extra data in logs:
- #1745 
Could you review the PR please?

**Comment by raman-m** [comment]
> I'll be able to extend the default logging context - for example, extract trace id from the header and add it to the logs

Have you ever heard about [delegating handlers](https://ocelot.readthedocs.io/en/latest/features/delegatinghandlers.html)?
I recommend to develop custom delegating handler module, attach to Ocelot pipeline.
Good luck!

-----
> This is not currently possibly

This is the lie from lazy developer.
