### ISSUE TITLE
httpclient is slow without rules

### ISSUE THREAD

**Issue by yoholiao** [ThreeMammals/Ocelot#1618]
in my production env.  one post request httpclient will slow without rules, and the request qps is low (6/s).

**skywalking trace:**
![oap](https://user-images.githubusercontent.com/49606277/200525043-db777c27-24b7-426c-92af-dc7a181d105c.png)

**kibana request log:**
![kibana](https://user-images.githubusercontent.com/49606277/200525034-40225a0e-dadf-44d7-afe1-797ef7e6a78b.png)

**ocelot.conf**

```json
{
  "Routes": [
    {
      "DownstreamPathTemplate": "/api/v1/task/sync",
      "DownstreamScheme": "http",
      "UpstreamPathTemplate": "/oacenter/api/v1/task/sync",
      "UpstreamHttpMethod": ["GET", "POST", "PUT", "DELETE", "OPTIONS"],
      "ServiceName": "oacenter-sync",
      "LoadBalancerOptions": {
        "Type": "LeastConnection"
      }
    }
  ],
  "GlobalConfiguration": {
    "ServiceDiscoveryProvider": {
      "Scheme": "http",
      "Host": "consul-server",
      "Port": 8500,
      "Type": "Consul",
      "ConfigurationKey": "gateway.ocelot"
    },
    "RateLimitOptions": {
      "DisableRateLimitHeaders": false,
      "QuotaExceededMessage": "Too Many Requests",
      "HttpStatusCode": 999,
      "ClientIdHeader": "X-Forwarded-For"
    }
  }
}
```
**Startup.cs**
```c#
services
.AddOcelot()
.AddDelegatingHandler<CookieHandler>(true)
.AddDelegatingHandler<RequestHandler>(true)
.AddConsul()
.AddConfigStoredInConsul()
;
```
version: net5.0 + ocelot 17.0.0
platform: Kubelet v1.18.6 , docker19.3.8

**Comment by raman-m** [comment]
@yoholiao Hello!

Is this issue a question or a bug? Let's consider that first...

**Comment by raman-m** [comment]
> without rules 

Considering your complex Ocelot setup: Consul service discovery, Load Balancer, Delegating handlers (two types), Kubernetes hosting... I would say your solution and setup is quite complex.
Your delegating handlers can do additional tasks which affect total processing time of the request...
I would say the root cause can be inside of your delegating handlers.

**Comment by raman-m** [comment]
Sorry we cannot accept the issue because it is related to your environment.
