### ISSUE TITLE
Redirect to outside of gateway

### ISSUE THREAD

**Issue by EvaldasVasiliauskas** [ThreeMammals/Ocelot#1621]
## Expected Behavior
API endpoint behind Ocelot gateway return Redirect response (full url) to a different domain.
Expected behavious is to redirect to that domain with url params.

## Actual Behavior

Redirect does not change the root path, only the query string. Root path remains API gateway.
If the endpoint is called directly (not using api gateway) - redirect is successful.

## Steps to Reproduce the Problem

  1. Create simple NET Core project with redirect endpoint
  2. Add its mapping to Ocelot config
  3. Try calling the redirect endpoint directly and through API Gateway

## Specifications

  - Version: 18
  - Platform: Net 7.0 core api 
  - Subsystem: Windows

**Comment by raman-m** [comment]
Hi Evaldas!
I can confirm we have this problem of swallowing of real status code.
How did you solve the problem?

When do you create a PR with a fix?

**Comment by raman-m** [comment]
It's good that the problem is gone in latest version. 👍 
As a team, we are curious about your production environment.
**Could you describe Prod env please?**
I mean, technical stack in Production: deployment type, web server type, clustering, Docker or cloud orchestration etc.

**Comment by EvaldasVasiliauskas** [comment]
I'm using Ocelot gateway in several projects where everything was separated in several microservices. Have deployed those solutions on windows server and on Ubuntu servers (simple manual configuration and deploy as Kestrel processes, nothing fancy :) ). Tried using with Consul, it worked well too. Ocelot also plays nicely with SignalR without any problems.

Thank you for your efforts and for keeping this project alive. Seemed like abandoned some while ago, but now versions are rolling :).

**Comment by raman-m** [comment]
> Thank you for your efforts and for keeping this project alive. Seemed like abandoned some while ago, but now versions are rolling :).

You are welcome!
Which version of SignalR do you use?
**Could you describe SignalR tech stack more please?**
How did you setup it, how do you link peers of the communication?
