### ISSUE TITLE
About the downstream protocol version (http2 vs http3)

### ISSUE THREAD

**Issue by 842549829** [ThreeMammals/Ocelot#1632]
Hi,
The current http protocol of my downstream service is http2.0 and http3.0. How to configure the downstream protocol and protocol version.

**Comment by raman-m** [comment]
Hi [liuxiaoji](https://github.com/842549829)!
You can ensure about current supported HTTP versions in this paragraph: [DownstreamHttpVersion](https://ocelot.readthedocs.io/en/latest/features/configuration.html?highlight=DownstreamHttpVersion#downstreamhttpversion)
I believe Ocelot doesn't support HTTP 3. It requires testing and development with usage of new `HttpClient` class which support HTTP 3.
And, the **DownstreamHttpVersion** property is a part of [Route](https://ocelot.readthedocs.io/en/latest/features/routing.html).

You can try to specify HTTP3 route and let us know your testing results, please.
