### ISSUE TITLE
ODATA Action route is not supported

### ISSUE THREAD

**Issue by SViradiya-MarutiTech** [ThreeMammals/Ocelot#1633]
The specified placeholder variable value should be replaced within the Downstream URI provided in the **UpstreamPathTemplate** and **DownStreamPathTemplate**.

For instance,

Route Configurations:
```json
{
  "DownstreamPathTemplate": "/api/subscriptions({subscriptionId})/updates",
  "UpstreamPathTemplate": "/v1/subscriptions({subscriptionId})/updates",
  "UpstreamHttpMethod": [ "Get" ],
  "DownstreamScheme": "http",
  "DownstreamHostAndPorts": [
    {
      "Host": "localhost",
      "Port": 50110
    }
  ]
}
```
When the request URI is http://localhost:5001/v1/subscriptions(123)/updates
Then the downstream request URI should be http://localhost:50110/api/subscriptions(123)/updates

## Actual Behavior

It's adding extra round braces ) in the Downstream request. It's a clear issue of replacing placeholder variables.

When the request URI is http://localhost:5001/v1/subscriptions(123)/updates
Then the downstream request URI is http://localhost:50110/api/subscriptions(123))/updates
## Steps to Reproduce the Problem

    Add a route with the placeholder within the round braces
    Get parameter value in the downstream. Observed the value received at the downstream application.

NOTE: An issue is not with specific round braces. It reproduces with any other routes where the placeholder does not exactly (eg. `/{id}/` ) provide between slashes.

## Specifications

    Version: 17.0.0
    Platform: .NET 5

**Comment by raman-m** [comment]
Hi Sagar!
Thank you for the issue reporting!

What about .NET 7 and Ocelot 19.0.2 ? 😉 

Did you fix this issue somehow?
I see that you haven't forked the repo...

I guess we need to write some acceptance test(s) to reproduce the issue...

**Comment by SViradiya-MarutiTech** [comment]
@raman-m Do you mean to say this issueis resolved with Ocelot 19.0.2?

**Comment by raman-m** [comment]
No, sure! 😄 
I need to reproduce it first using v.19, or it should be reproduced by someone from the team. But team doesn't care...

Do you have the fix? Did you fix it at all in the past?

If Yes,
Could you prepare and create PR please? 
And I'll review it with pleasure. 😉 

Can we have some pair programming to create acceptance test first?

**Comment by raman-m** [comment]
Dear @SViradiya-MarutiTech ,
### You have the right to reopen this issue in the future if you come with a PR ready.
