### ISSUE TITLE
Migrate to Net 7.0

### ISSUE THREAD

**Issue by RaynaldM** [ThreeMammals/Ocelot#1640]
## Migrate to .Net 7.0
And make some improvements, code cleaning/modernization and packages update

**Comment by TomPallister** [comment]
Hi @RaynaldM sure submit the PR and I will take a look! I was going to upgrade to .NET 7 this weekend!

**Comment by RaynaldM** [comment]
> Hi @RaynaldM sure submit the PR and I will take a look! I was going to upgrade to .NET 7 this weekend!

Unfortunately, I still don't have the right to do a push of my branch, and therefore to do my PR

**Comment by TomPallister** [comment]
I think you need to fork Ocelot and create a PR from the fork

**Comment by ggnaegi** [comment]
> Hi @RaynaldM sure submit the PR and I will take a look! I was going to upgrade to .NET 7 this weekend!

Great News! Thanks a lot!

**Comment by RaynaldM** [comment]
@TomPallister PR Ready
