### ISSUE TITLE
is ocelot api gateway deprecated ?

### ISSUE THREAD

**Issue by MehdiSadeghi1996** [ThreeMammals/Ocelot#1644]
# is ocelot api gateway deprecated ?

## Specifications
  - Version: 18.0.0

**Comment by RaynaldM** [comment]
not yet :)

**Comment by FHocs-Xpollens** [comment]
Yes not any merge since 1year +, their website is down, it seems dead for me

**Comment by raman-m** [comment]
> not yet :)

#1645 
@RaynaldM, congrats on upgrading this piece of art to .NET 7 ! 😄

**Comment by TomPallister** [comment]
Thank you @RaynaldM and @raman-m you can get the net7.0 version from https://www.nuget.org/packages/Ocelot now. Latest version is 19.0.1

**Comment by raman-m** [comment]
Version: [19.0.2](https://www.nuget.org/packages/Ocelot/19.0.2)
