### ISSUE TITLE
Unable to access consul when configuring ocelot in .Net 6

### ISSUE THREAD

**Issue by Danimatar0** [ThreeMammals/Ocelot#1650]
I have installed consul server on a local server which i have access to and verified the installation is correct because i could open the dashboard on default port 8500. But when trying to configure ocelot with consul within an api gateway project in .Net 6 with an ocelot configuration hosted on consul dashboard inside a key value token, not in an local ocelot.json file, it’s automatically looking for the consul server on localhost and not on the domain indicated in the configuration in the kv. Any idea how to make it work?

**Comment by raman-m** [comment]
**1st**, double check your configurations!

**2nd**, ensure this is not DNS issue. So, all services should be visible to each other. Note, that Docker container services don't see your local host!

**3rd**, provide all configurations here!

**Comment by Danimatar0** [comment]
Here is the configuration hosted in consul ui:
{
  "Routes": [
    {
      "DownstreamPathTemplate": "/api/{everything}",
      "ServiceName": "UserManagement",
      "UpstreamPathTemplate": "/gateway/UserManagement/{everything}",
      "UpstreamHttpMethod": [
        "GET",
        "PUT",
        "POST"
      ],
      "UseServiceDiscovery": true,
      "LoadBalancerOptions": {
        "Type": "LeastConnection"
      },
      "ReRoutesCaseSensitive": false,
      "RateLimitOptions": {
        "ClientWhitelist": [],
        "EnableRateLimiting": true,
        "Period": "1s",
        "PeriodTimespan": 1,
        "Limit": 1
      }
    }
  ],
  "DynamicRoutes": [],
  "Aggregates": [],
  "GlobalConfiguration": {
    "ServiceDiscoveryProvider": {
      "Host": "192.168.153.110",
      "Port": 8500,
      "Type": "Consul",
      "PollingInterval":500
    }
  }
}

**Comment by raman-m** [comment]
At least, dear @Danimatar0 , could you paste well-formatted code block of the config please?
Are you familiar with .md formatting?
So, it is hard to read your copy-paste messages!

**Comment by raman-m** [comment]
You have to create public repository in GitHub with your draft solution. And maybe the community will help you.
So, you have to show your code!

As for me I expect wrong setup of gateway project on your side.
Please, read Ocelot [**documentation**](https://ocelot.readthedocs.io/en/latest/introduction/gettingstarted.html), page by page, and provide correct configuration.

As I asked you, did you check an ensure that your problem is not DNS issue?

**Comment by raman-m** [comment]
@Danimatar0  Hi Dani!
Sorry, I cannot help you.
Reason: the lack of information.
