### ISSUE TITLE
Microservice architecture Using OCELOT publish in IIS

### ISSUE THREAD

**Issue by Shonzon** [ThreeMammals/Ocelot#1654]
Hi I have an API gateway which is using OCELOT ,In my local host it works fine but when I am publishing in IIS, it returns "

ps://localhost:7215/api/' from origin 'http://localhost:4200' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

but when run from visual studio no error occoured

**Comment by raman-m** [comment]
@Shonzon 
Be accurate while providing draft configuration of Ocelot ASP.NET web app. Try to follow best practices described in docs: [Configuration](https://ocelot.readthedocs.io/en/latest/features/configuration.html)
If you host Ocelot app at IIS, make sure about: [Gotchas](https://ocelot.readthedocs.io/en/latest/introduction/gotchas.html)
For hosting, I would recommend Docker & Self-hosted (Kestrel) scenario.

To resolve CORS problem, make sure about calling `UseCors` and/or `AddCors` in your ASP.NET web apps.
More: [Enable Cross-Origin Requests (CORS) in ASP.NET Core](https://learn.microsoft.com/en-us/aspnet/core/security/cors?view=aspnetcore-7.0)

Good luck in your gateway building with Ocelot!
