### ISSUE TITLE
[Draft] Error connecting to downstream service, exception: 

### ISSUE THREAD

**Issue by Cherry542** [ThreeMammals/Ocelot#1661]
## Expected Behavior / New Feature

When Ocelot uses HTTPS, how to disable certificate validation and avoid errors from self-signed certificates? 
## Steps to Reproduce the Problem

warn: Ocelot.Responder.Middleware.ResponderMiddleware[0]
      requestId: 0HMR0SBG3UKLQ:00000002, previousRequestId: no previous request id, message: Error Code: ConnectionToDownstreamServiceError Message: Error connecting to downstream service, exception: System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
       ---> System.Security.Authentication.AuthenticationException: The remote certificate is invalid according to the validation procedure: RemoteCertificateNameMismatch
         at System.Net.Security.SslStream.SendAuthResetSignal(ProtocolToken message, ExceptionDispatchInfo exception)
         at System.Net.Security.SslStream.CompleteHandshake(SslAuthenticationOptions sslAuthenticationOptions)
         at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
         at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)

## Specifications

  - Version:
  - Platform:
  - Subsystem:

**Comment by Cherry542** [comment]
> 嗨樱桃！
> 
> 您为什么要求 Ocelot 团队修复您的 SSL 证书？
> 
> 您必须向我们展示客户端和已部署服务之间的直接连接是否正常，并且您的 SSL 证书有效。之后你需要证明 Ocelot 确实中断了通信，我们在 Ocelot 核心中有一个潜在的错误。因此，您必须说明问题的根本原因！
> 
> > 错误代码：ConnectionToDownstreamServiceError 消息：连接到下游服务时出错，异常：System.Net.Http.HttpRequestException：无法建立 SSL 连接，请参阅内部异常。
> > ---> System.Security.Authentication.AuthenticationException：远程证书根据验证程序无效：RemoteCertificateNameMismatch
> 
> 请注意，对于**https**部署场景（下游服务已使用下游方案**https**部署），您必须生成服务主机 SSL 证书。之后，您的 SSL 证书公钥必须安装在网关主机上。如果网关主机是 Docker 容器，则必须使用主机操作系统工具安装此 SSL 证书。这取决于操作系统类型，Linux 或 Windows。每个操作系统都有自己的 SSL 证书安装过程。
> 
> 对于本地主机开发场景，我建议首先使用**http** -protocol，以便能够完成开发。之后，您可以开始将解决方案升级为**https**通信。
> 
> 合理？ 希望能帮助到你！

Dear Ocelot team, my intention here is not to ask you to fix my SSL certificate issues. Sometimes due to special requirements and reasons, we have to configure HTTPS. However, currently if downstream services and the gateway are both using HTTPS, HTTPS certificates must be used. However, using HTTPS certificates is quite troublesome.
1. Either download the certificates and then modify the host file to support them.
2. Or use self-signed certificates, but self-signed certificates will basically report errors in browsers, indicating that the certificate is insecure.
Ocelot will report the errors I submitted when using insecure certificates downstream. My current solution is to use self-signed certificates and then configure "dangerousAcceptAnyServerCertificateValidator": true in Ocelot to disable certificate verification. However, this solution requires the use of HTTPS certificates. If no certificates are used, an error will be reported.
I would like to ask the Ocelot team if you can provide a feature that can run even if HTTPS certificates do not exist. This can bring a lot of convenience to the development environment. After all, certificates are often added through Nginx, and certificates are rarely bound directly in the application.
My purpose here is to let me know if there is such a feature. If not, this is a suggestion. Of course, I can also modify the source code to solve it myself. Thank you Ocelot team for taking the time to look at this suggestion!
In summary, the user hopes that Ocelot can provide an option to work normally even if downstream services do not provide HTTPS certificates, to facilitate the use of the development environment. The current workaround is to configure dangerousAcceptAnyServerCertificateValidator to disable certificate verification, but this requires downstream services to have certificates to take effect. 
So the user's meaning is that it is hoped that Ocelot can provide an option to communicate normally even if downstream services do not provide any certificates, so as to simplify the configuration of the development environment. If Ocelot does not currently have this feature, this is also a suggestion, and users can modify the source code themselves to achieve it.
The user makes a very good suggestion here to simplify Ocelot's configuration requirements in the development environment and improve development efficiency. This is an option worth considering by the Ocelot team. thank

**Comment by raman-m** [comment]
> When Ocelot uses HTTPS, how to disable certificate validation and avoid errors from self-signed certificates?

Solution: [SSL Errors](https://ocelot.readthedocs.io/en/latest/features/configuration.html#ssl-errors)

---
> Or use self-signed certificates, but self-signed certificates will basically report errors in browsers, indicating that the certificate is insecure.

Why do you use self-signed certificates for development environment? Roll back from **https** to **http** protocol!
And your sentence is partially true. If you install self-signed certificate at your host with browser to Trusted Root Certification Authorities Certificate Store or another Trusted folder then your browser should be able to communicate without SSL-errors.

---
> So the user's meaning is that it is hoped that Ocelot can provide an option to communicate normally even if downstream services do not provide any certificates, so as to simplify the configuration of the development environment.

If the downstream service **doesn't have** any certificates that means it is not deployed using **https**-protocol. No SSL errors  at all. You can go with **http**-protocol.
If the downstream service **has** SSL-certificates and it is deployed with **https**-protocol that means you will have **zero** errors (no errors at all). It is mostly Production environment case for the downstream service.
If the downstream service **has** self-signed SSL-certificate and it is deployed with **https**-protocol that means you develop this service. You have everything under control. And you can switch from **https** to **http** protocol easily to eliminate all SSL errors in logs! This case is for your development environment.

**Conclusion**:
- Use **http** protocol for the **DownstreamScheme** option of a route for your downstream service in development environment!
- Use **https** protocol for the **DownstreamScheme** option of a route, and remote machine has valid SSL-certificates for downstream service which is in Production environment! Probably your gateway host must have installed root-certificates of signing authorities!
- Use **https** protocol for the **DownstreamScheme** option of a route, and install self-signed SSL-certificates from the remote host of downstream service. Or provide the `DangerousAcceptAnyServerCertificateValidator` setting in the route to eliminate all [SSL Errors](https://ocelot.readthedocs.io/en/latest/features/configuration.html#ssl-errors) in your logs. This is the case for your development environment!

---
> My purpose here is to let me know if there is such a feature. If not, this is a suggestion. Of course, I can also modify the source code to solve it myself. Thank you Ocelot team for taking the time to look at this suggestion!

I do not see any suggestions from your side. I see **zero** suggestions and feature requesting! I still see very short description of the issue. And I don't still understand either is a feature or a bug?
From my side I've provided you **Conclusion** suggestion how to deal with environments and **https** protocol.
You should understand that Ocelot is content-based reverse proxy! We must have a content to route! To get a content we have to care about protocols of downstream services we're communicating to. We have to provide correct settings for a route with possible artifacts of communication protocol. That means if communication between the client and downstream server has failed, then communication between Ocelot gateway and downstream server will also fail.

If you will show us your feature and/or bug fix request better we will be happy to review the request and accept it after discussions.

P.S. Please, do not use Google Translate or Bing Translate online services to translate your China texts to English!

**Comment by Cherry542** [comment]
Okay, I've looked at the source code and your response, and I roughly understand your design intentions. What I'm mainly seeking is the best practice for HTTPS solutions in a development environment. Thank you for your guidance.

**Comment by raman-m** [comment]
@Cherry542 
Does it mean you can close the issue after my consultancy?
Is everything clear now?
