### ISSUE TITLE
How to work with array in get query parameter.  Something like `url/controller-path?id[]=2`

### ISSUE THREAD

**Issue by Abhinav1217** [ThreeMammals/Ocelot#1674]
## Expected Behavior / New Feature
Hi, I searched for some discord or other platform for Q/A but I couldn't find anything like that, hence asking for solution here. It may be a missing feature because I did find some issues about optional parameters, but nothing was specifically asking for array in parameters.

I am trying to get a List<int> as a query parameter. Something like `url/controller-path?id[]=2&id[]=3&id[]=4 `. The problem is when I try using following in config `"UpstreamPathTemplate": "/api/dashboard/carer?id[]={Ids}",`  the gateway crashes.
 **If I remove the square brackets, then it will work. But I need to support an array of integers.** 

## Actual Behavior / Motivation for New Feature
Should be able to forward parameter array to mvc controller which does support array params and optional params. 

## Steps to Reproduce the Problem

  1. Basically create a controller path which accepts a array of values, like result from checkboxes, etc
 
## Specifications

  - Version:
    ```
    <PackageReference Include="Ocelot" Version="18.0.0" />
    <PackageReference Include="Ocelot.Provider.Polly" Version="18.0.0" />
    ```

  - Platform: Dotnet Core 6
  - Subsystem: Windows

**Comment by raman-m** [comment]
Hi Abhinav!
Thanks for your interest in Ocelot gateway!

---
> `<PackageReference Include="Ocelot" Version="18.0.0" />`

You should use v19 as .NET 7 release. Usage of old releases is on your own risks.

---
Current implemented "placeholders" logic/features:
- [Placeholders](https://ocelot.readthedocs.io/en/latest/features/headerstransformation.html#placeholders) of [Headers Transformation](https://ocelot.readthedocs.io/en/latest/features/headerstransformation.html) feature
- Other "placeholders" helpers: [Search Results for "placeholder" in Ocelot docs](https://ocelot.readthedocs.io/en/latest/search.html?q=placeholder&check_keywords=yes&area=default)

---
> ## Actual Behavior / Motivation for New Feature
> Should be able to forward parameter array to mvc controller which does support array params and optional params. 

To fix your problem with query params forwarding you have to use [Routing](https://ocelot.readthedocs.io/en/latest/features/routing.html) feature in advance:
- define classic `{everything}`-route for your downstream endpoint: [Routes](https://ocelot.readthedocs.io/en/latest/features/routing.html#routing)
- or define special [Catch All](https://ocelot.readthedocs.io/en/latest/features/routing.html#catch-all) route for your downstream endpoint

Please use these 2 route definition techniques and you "**will be able to forward parameter array to mvc controller**"!

---
>I am trying to get a List<int> as a query parameter. Something like `url/controller-path?id[]=2&id[]=3&id[]=4 `. The problem is when I try using following in config `"UpstreamPathTemplate": "/api/dashboard/carer?id[]={Ids}",`  the gateway crashes.

Such kind of placeholders are not supported by Ocelot. Wrong usage of [current placeholders](https://ocelot.readthedocs.io/en/latest/search.html?q=placeholder&check_keywords=yes&area=default)!
I believe you need to define your route like this:
```json
{
    "DownstreamPathTemplate": "/url/{everything}",
    "UpstreamPathTemplate": "/api/dashboard/{everything}"
}
```
Maybe definition of a concrete route will be required. But you have to wrap you query params by `{everything}`!

--- 
> **If I remove the square brackets, then it will work. But I need to support an array of integers.** 

It seems you've misused square brackets! ASP.NET API app binding logic understands array values in query params without square brackets!
More here: [Parameter binding in Minimal API applications | Microsoft Learn](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis/parameter-binding?view=aspnetcore-7.0#bind-arrays-and-string-values-from-headers-and-query-strings)
So, your query string is invalid, ASP.NET pipeline params binder cannot parse it!

To support array of integers **you have to wrap you query params** by `{everything}` in [Routes](https://ocelot.readthedocs.io/en/latest/features/routing.html#routing) feature!

---
Hope it helps!

**Comment by raman-m** [comment]
Let's find some workaround within one week please!
Your issue will be accepted or declined until July 10.
---

**Comment by Abhinav1217** [comment]
Someone from reddit gave me the solution. Query parameters are not required to be mentioned on ocelot, So I just wrote `/api/dashboard` and pointed it to `/api/MobileDashboard` and it worked. All the Get Parameters are passed as is. This helped me cleanup my ocelot.json a lot. 

That person also pointed me to https://github.com/ThreeMammals/Ocelot/issues/797 for another problem I was facing where I have an optional REST path which at present is not supported by ocelot.
