### ISSUE TITLE
RequestMapper performance issue: ToByteArray(request.Body)

### ISSUE THREAD

**Issue by weichaohh** [ThreeMammals/Ocelot#1679]
## Expected Behavior / New Feature

File: [RequestMapper.cs](../blob/develop/src/Ocelot/Request/Mapper/RequestMapper.cs)
Method: [Task&lt;HttpContent&gt; MapContent(HttpRequest request)](/search?q=repo%3AThreeMammals%2FOcelot%20%22Task%3CHttpContent%3E%20MapContent(HttpRequest%20request)%22&type=code)
Line:
```csharp
var content = new ByteArrayContent(await ToByteArray(request.Body));
```
There are performance issues.
Maybe Can change to use `ArrayPool` like YARP, This can reduce GC `byte[]`.

**Comment by raman-m** [comment]
Hi weichao!
Thanks for your interest in Ocelot gateway!

Could you correct your English text description please? It is hard to read it!

In general I understand the issue, but we need to work on description and user scenario to accept the issue.

Do you have some draft solution with a fix?

**Comment by weichaohh** [comment]
> 



> Hi weichao! Thanks for your interest in Ocelot gateway!
> 
> Could you correct your English text description please? It is hard to read it!
> 
> In general I understand the issue, but we need to work on description and user scenario to accept the issue.
> 
> Do you have some draft solution with a fix?

Hi
Thanks for your reply,
Sorry, my english leve very low.

because i have a large number of iot,they post realy data to service. so every time "memStream.ToArray()" to allocate "new byte[]". this will increase the burden of gc.

I found that “YARP ->StreamCopier.cs" use "ArrayPool<byte>.Shared", this can buffer "byte[]",so reduce gc.I think this is a good choice

**Comment by raman-m** [comment]
Yes, this is a good choice!
Are you going to create a PR to fix this problem?
Have you provided some performance tests and/or comparison of YARP and Ocelot?

**Comment by ggnaegi** [comment]
@weichaohh Could you check the changes and give us a feedback?

**Comment by raman-m** [comment]
The issue has been **[accepted](#event-10657806353)** due to opened PR #1724 
- #1724

**Comment by raman-m** [comment]
@ggnaegi  Gui, the author doesn't want to fix and closed the issue 😄 What will we do?
So, cause we're closely to the end and you are working on #1724 , I've decided to reopen this issue. OK?

**Comment by ggnaegi** [comment]
Ok @raman-m could you assign me? Thanks!
