### ISSUE TITLE
Unstable test "Open circuit should not effect different route"

### ISSUE THREAD

**Issue by raman-m** [ThreeMammals/Ocelot#1706]
## Expected Behavior / New Feature
The test `Ocelot.AcceptanceTests.PollyQoSTests.Open_circuit_should_not_effect_different_route` doesn't fail in 100% of running

## Actual Behavior / Motivation for New Feature
Currently the test [Open_circuit_should_not_effect_different_route](/search?q=repo%3AThreeMammals%2FOcelot%20Open_circuit_should_not_effect_different_route&type=code) fails sometimes, very rarely.
Possible reason: unknown.

## Steps to Reproduce the Problem
- PR builds: [1884](https://app.circleci.com/pipelines/github/ThreeMammals/Ocelot/1004/workflows/c97b3e46-4b2e-49a1-bc63-fdc8d0aebdc9/jobs/1884?invite=true#step-102-303655_56), [1732](https://app.circleci.com/pipelines/github/ThreeMammals/Ocelot/928/workflows/93b20a29-a8ed-4e24-862f-8dd383aad00f/jobs/1732?invite=true#step-102-309194_56), [1728](https://app.circleci.com/pipelines/github/ThreeMammals/Ocelot/926/workflows/e63bc07b-0abd-44d1-8037-da384cf6c509/jobs/1728?invite=true#step-102-256440_56)
- It is also reproducible in Visual Studio: [see screenshot](1700#issuecomment-1733220654)

## Specifications
  - Version: latest, 19.0.3
  - Platform: any
  - Subsystem: CircleCI/Docker, Visual Studio

**Comment by ggnaegi** [comment]
@raman-m Well, it's very odd... At some point, we have a timing problem... It's very difficult to manage. First I thought, ok instead of using the local variable _requestCount, let's inject a singleton IRequestCountService like this:
``` c#
.ConfigureServices(services =>
                {
                    services.AddSingleton<IRequestCountService, RequestCountService>();
                })
```
and then refactor the method like that:
``` c#
private void GivenThereIsAPossiblyBrokenServiceRunningOn(string url, string responseBody)
        {
            _serviceHandler.GivenThereIsAServiceRunningOn(url, async context =>
            {
                var requestCountService = context.RequestServices.GetService<IRequestCountService>();
                context.Response.StatusCode = 200;

                if (requestCountService.GetRequestCount() == 1)
                {
                    await Task.Delay(1000);
                    await context.Response.WriteAsync("delayed service");
                    return;
                }

                await context.Response.WriteAsync(responseBody);
            });
        }
```
It brings a bit more stability, but that's not it yet...

**Comment by raman-m** [comment]
> 200-300 iterations

After what number of iterations we have a fail of the test now?

You are assigned! Okay?

**Comment by ggnaegi** [comment]
@raman-m I will have a go on this next week (wednesday probably)

**Comment by raman-m** [comment]
> @ggnaegicommented [on Oct 13](#issuecomment-1762132963)

Ah, never mind!
Assigned to you with low priority, because it is not critical for builds.

We will fix it in November if you'll have a time... 
Also, I'm not going to include this to October's release...
