### ISSUE TITLE
Getting error due to serviceDiscoveryProvider in GlobalConfiguration after update to 18.0.0 from 13.0.0

### ISSUE THREAD

**Issue by bob5296** [ThreeMammals/Ocelot#1715]
I had this config in **ocelot.json**
```json
 "GlobalConfiguration": {
    "RequestIdKey": "OcRequestId",
    "ServiceDiscoveryProvider": {
      "Host": "********DNSname",
      "Port": 19081,
      "Type": "ServiceFabric"
    }
```
and in route 
```json
{
      "DownstreamPathTemplate": "/api/Configuration/{url}",
      "UpstreamPathTemplate": "/Configuration-API/{url}",
      "UpstreamHttpMethod": [
        "Get",
        "Options",
        "Post",
        "Put",
        "Delete"
      ],
      "DownstreamScheme": "http",
      "ServiceName": "ServiceNameInServiceFabric"
}
```
Before upgrade it was not searching for the DNS provided in GlobalConfiguration and it was working.
After upgrade it started giving below error:
```
Ocelot.Responder.Middleware.ResponderMiddleware[0]
     requestId: 0HMU5N5H75RMD:00000002, previousRequestId: no previous request id, message:
     Error Code: ConnectionToDownstreamServiceError
     Message: Error connecting to downstream service, exception:
     System.Net.Http.HttpRequestException: No such host is known.
```
Any particular reason it was not giving error in versions 13 but started giving error in version 18

**Comment by raman-m** [comment]
Hi Bob!
How do you host your Ocelot app?
What is the hosting environment?

Please provide a description of hosting environments for both: client and server. Ocelot app and downstream service.

Also, make Postman requests directly to downstream service:
- from Ocelot's machine
- from your local environment
Attach all screenshots please...

Also, provide full calling stack from debugging in case of error.

Without additional details I cannot advice you something...

**Comment by raman-m** [comment]
> Any particular reason it was not giving error in versions 13 but started giving error in version 18

Bob!
So... You've upgraded framework from `.NET Standard 2.0` to `.NET 6.0`, right?
Quite a risky upgrade! 🙉 

Do you know the fact that in version [16.0.0 release](../releases/tag/16.0.0) we have a breaking changes aka **ReRoutes** &rarr: **Routes** renaming introduced by Tom? Sorry, current old release notes don't point to Breaking Changes.
So, Ocelot v16- (and lower) apps upgrading will fail. And v13 (.NET Standard 2) solution in C# code cannot be compatible to v18 (.NET 6). But I would suggest you to upgrade to .NET 7 and Ocelot v19+ which has (will have) more builds with new features and bugfixes.

Your team should:
- upgrade .NET framework to .NET 6 with reference to Ocelot v18
- carefully review current ocelot.json config, and rename ReRoutes to Routes
- disable any hard features like Service Discovery, Load Balancing, etc.
- ensure that new app based on Ocelot v18 can route the traffic to all downstreams without problems
- after that start to switch on hard features: Service Discovery, etc.

Sounds good plan?

**Comment by ks1990cn** [comment]
Interested, but anything here @bob5296 ?

Probably you can check your `serviceName` of gateway and downstream is visible at ServiceFabric, to just to verify again its getting registered correctly.

**Comment by raman-m** [comment]
@bob5296 You don't care, right?
Are you ghost?  Your [repos](https://github.com/bob5296?tab=repositories) are empty! 😏 

I provided and shared upgrading plan to you [on October 6](#issuecomment-1750811984), but you don't care...
OK, man... I don't see any sense to keep this issue open.
