### ISSUE TITLE
Unable to generate documentation on ReadTheDocs

### ISSUE THREAD

**Issue by ggnaegi** [ThreeMammals/Ocelot#1731]
## Expected Behavior / New Feature
We would expect the documentation to be generated on a regular basis, to avoid misunderstandings. 😸 

## Actual Behavior / Motivation for New Feature
The documentation generation process fails at the moment:
[Build #22151302 | Ocelot | Read the Docs](https://readthedocs.org/projects/ocelot/builds/22151302/)

The reason is that Read the Docs has stopped supporting docs generation without the `.readthedocs.yaml` config file:
[Migrate your project to .readthedocs.yaml configuration file v2 — Read the Docs Blog](https://blog.readthedocs.com/migrate-configuration-v2/)

## Solution
A simple solution is given in the PR. By adding a config file to the solution's root folder the docs are generated.
See demo account by @ggnaegi: https://ocelot-test.readthedocs.io/en/bug-fix_documentation_generation/

**Comment by raman-m** [comment]
Thanks for creation! 👍 
```diff
+ Accepted
```
Do we build **main** branch commits or **develop** one too?
https://readthedocs.org/projects/ocelot/versions/
For now I cannot get the difference between **stable** and **latest** version...

**Comment by ggnaegi** [comment]
@raman-m stable are the releases and latest is main. So, you should add the yaml to main as well.

**Comment by raman-m** [comment]
@ggnaegi  The hotfix has been delivered to [release/20.0](../tree/release/20.0) branch, see commit 640b0051d44b5fa6b3c4d2a577e6798eca22a459
The release PR is #1755 .
Would you like to wait until the release done and close the ticket, or could we attach this issue to #1755 ?

**Comment by ggnaegi** [comment]
@raman-m Do what suits you best.

**Comment by raman-m** [comment]
> @raman-m Do what suits you best.

It is better to link issue to the PR, and it'll be closed automatically.
PRs to release branches don't close issues because there is no protection rules defined for release branches.
We have two protected branches: **main** and **develop**

**Comment by raman-m** [comment]
Released in [20.0.1](../releases/tag/20.0.1)
Commit: d3a623ee7ae6de00b939fd847cc7cef6d4c89276
