### ISSUE TITLE
Kubernetes provider guidelines in docs don't match available methods

### ISSUE THREAD

**Issue by Palisar** [ThreeMammals/Ocelot#1746]
## Expected Behavior / New Feature
When you view the docs for K8s is shows simply to use 
`s.AddKubernetes();`

in the configure services in program.cs

## Actual Behavior / Motivation for New Feature

the extension method `.AddKubernetes()` doesn't appear to be available to this method.

## Steps to Reproduce the Problem

  1. Copy the example setup from the docs
  2. Install the package `Ocelot.Provider.Kubernetes` as instructed in the docs
  3. scroll down to line where we configure services and type `s.AddKubernetes();` and it will show this method is not longer there.

## Specifications

  - Version: 20.0.0
  - Platform: Rider
  - Subsystem: unsure

**Comment by raman-m** [comment]
@ggnaegi  Could you confirm that plz?

**Comment by Palisar** [comment]
![image](https://github.com/ThreeMammals/Ocelot/assets/83838480/71bdd1a2-5302-40b9-a4ab-29a224432a08)
Here is a screen shot for more context

**Comment by ggnaegi** [comment]
@Palisar @raman-m the extension method is foreseen for an  ```IOcelotBuilder``` object, therefore you should write 
``` c#
services
      .AddOcelot(Configuration)
      .AddKubernetes()
```
since AddOcelot will return an IOcelotBuilder
The docs for version 20.0 are fine though:
![image](https://github.com/ThreeMammals/Ocelot/assets/58469901/80baf483-4539-485b-ade7-5d903416cd9d)

**Comment by Palisar** [comment]
Ah , sorry it was my mistake not overriding this. Thanks for the clarification and sorry for the misunderstanding.

**Comment by raman-m** [comment]
Dear Paul,
We have very simple K8s demo app: [OcelotKube sample](https://github.com/ThreeMammals/Ocelot/tree/develop/samples/OcelotKube)
Here are exact lines which should help you: [OcelotKube / ApiGateway / Startup.cs](https://github.com/ThreeMammals/Ocelot/blob/develop/samples/OcelotKube/ApiGateway/Startup.cs#L17-L18)
Extension definition: [Ocelot.Provider.Kubernetes.OcelotBuilderExtensions.AddKubernetes](https://github.com/ThreeMammals/Ocelot/blob/develop/src/Ocelot.Provider.Kubernetes/OcelotBuilderExtensions.cs#L8)
