### ISSUE TITLE
Allow services to register with Ocelot Cluster

### ISSUE THREAD

**Issue by TomPallister** [ThreeMammals/Ocelot#175]
I'm putting this here because I had a thought on the train. This potentially removes the need for consul providing the service locations. However fully understand sticking with consul as it is probably way better than my raft implementation and does a lot of other stuff!

**Happy path**
When raft finished allow services to register with Ocelot.
The service can call Ocelot's administration API with IdentityServer client auth workflow?
This Administration controller would fire a command to the Cluster leader to add a new service to the registry. 
The registry is persisted to the cluster.
Ocelot looks at the registry for services it can call.

**Comment by raman-m** [comment]
Outdated! The author doesn't care!
