### ISSUE TITLE
Less logs for circuit breakers (and other Polly exceptions)

### ISSUE THREAD

**Issue by RaynaldM** [ThreeMammals/Ocelot#1783]
We'd like to know more about the exceptions raised in [PollyPoliciesDelegatingHandler](https://github.com/ThreeMammals/Ocelot/blob/ec555044292ea69e526fb3f01bcf22426d82910d/src/Ocelot.Provider.Polly/PollyPoliciesDelegatingHandler.cs#L11), in order to get the origin of the log like this:

 ```
try
 {
     // at least one policy (timeout) will be returned
     // AsyncPollyPolicy can't be null
     // AsyncPollyPolicy constructor will throw if no policy is provided
     var policy = qoSProvider.GetPollyPolicyWrapper(_route).AsyncPollyPolicy;
     return await policy.ExecuteAsync(async () => await base.SendAsync(request, cancellationToken));
 }
 catch (BrokenCircuitException ex)
 {
     _logger.LogError($"Reached to allowed number of exceptions. Circuit is open for {request.RequestUri}", ex);
     throw;
 }
 catch (HttpRequestException ex)
 {
     _logger.LogError($"Error in {nameof(PollyPoliciesDelegatingHandler)}.{nameof(SendAsync)} for {request.RequestUri}", ex);
     throw;
 }
```

**Comment by raman-m** [comment]
@ggnaegi  ❓ 🤣

**Comment by RaynaldM** [comment]
in fact 
`catch (BrokenCircuitException ex)
{
    _logger.LogError($"Reached to allowed number of exceptions. Circuit is open for {request.RequestUri}", ex);
    throw;
}`
is useless because we have almost the same log [here](https://github.com/ThreeMammals/Ocelot/blob/ec555044292ea69e526fb3f01bcf22426d82910d/src/Ocelot.Provider.Polly/PollyQoSProvider.cs#L53)

 ```
 exceptionsAllowedBeforeBreakingPolicy = Policy
      .HandleResult<HttpResponseMessage>(r => _serverErrorCodes.Contains(r.StatusCode))
      .Or<TimeoutRejectedException>()
      .Or<TimeoutException>()
      .CircuitBreakerAsync(route.QosOptions.ExceptionsAllowedBeforeBreaking,
          durationOfBreak: TimeSpan.FromMilliseconds(route.QosOptions.DurationOfBreak),
          onBreak: (ex, breakDelay) => _logger.LogError(info + $"Breaking the circuit for {breakDelay.TotalMilliseconds} ms!", ex.Exception),
          onReset: () => _logger.LogDebug(info + "Call OK! Closed the circuit again."),
          onHalfOpen: () => _logger.LogDebug(info + "Half-open; Next call is a trial."));
```

@raman-m @ggnaegi agree with that ?

**Comment by ggnaegi** [comment]
@RaynaldM well, probably one or two test cases will fail but imho we can remove the whole try/catch, ```BrokenCircuitException``` is thrown and handled later in ErrorMessages. ```BrokenCircuitException``` is thrown by policy.ExecuteAsync, when conditions for circuit breaker are met. As for the ```HttpRequestException``` I don't think that they are thrown anyway. Soo...

**Comment by ggnaegi** [comment]
@RaynaldM So, both are useless...

**Comment by raman-m** [comment]
I agree, this logic can be optimized.

**Comment by raman-m** [comment]
Guys, do you understand that if we removed `try-catch` block then all exceptions not being processed by Polly will go to Error mapping logic?
Will it be OK ?

**Comment by RaynaldM** [comment]
Right, this try-catch (and associated logs) is useless

**Comment by raman-m** [comment]
I have a bad joke regarding Polly but I'm not going to say it now, after release... how is it useful or useless.

**Comment by raman-m** [comment]
"More accurate logs"
Cannot get the phrase. What does accuracy mean here?
- Less log records
- Efficient code to process exceptions
- something else

What is the goal, @RaynaldM ?
