### ISSUE TITLE
how to change servicename dynamically  by form value

### ISSUE THREAD

**Issue by d0apga** [ThreeMammals/Ocelot#1785]
## Expected Behavior / New Feature
I want to set servicename dynamically by querystring value or form post value.
for example
upstream url: /openapi
form post: api=task.control&params={}
or form post: api=task.new&params={}
when api value=task.control,set servicename to "taskcontrolservice", when api value=task.new,set servicename to "createtaskservice",
is there a convenient way to implement it now?

## Actual Behavior / Motivation for New Feature
servicename only can set from route

## Steps to Reproduce the Problem

  1.
  1.
  1.

## Specifications

  - Version: 20.0.0
  - Platform: windows
  - Subsystem: windows11

**Comment by ks1990cn** [comment]
Yes, we can do. I don't think we have any thing as such for now. 

But it looks like can be quite complicated if we gradually start considering alot of things to route dynamically.

Consider following scenario:

1.) For same upstream url `/UpstreamURL`, there can be downstream with different authentication - maybe any downstream uses JWT, maybe anyone uses only key value pair or maybe LDAP.
2.) There can be situation we have to consider if any route can be connected to web socket / SignalR
3.) There can be situation with different body/headers.
4.) Different Ratelimiting, QoS etc..

And for everything we have to revisit our Ocelot.Json and the way we configure.

@ggnaegi @raman-m What are your thoughts on this?

**Comment by d0apga** [comment]
@ks1990cn Yes, it does need to consider multiple impacts. Currently, I am trying to rewrite the Consul service discovery to achieve this goal.

**Comment by raman-m** [comment]
@d0apga commented [on Nov 15](#issue-1994720123)
> is there a convenient way to implement it now?

No

My dear fried from China,
Why is your GitHub repo is empty? It has only forked repos. Why?

**Comment by raman-m** [comment]
> @d0apga commented [on Nov 16](#issuecomment-1814709014)
Currently, I am trying to rewrite the Consul service discovery provider to achieve this goal.

You can do any Ocelot researches, but inside of your forked Ocelot repo in your account!

**Comment by raman-m** [comment]
> I want to set servicename dynamically by querystring value or form post value.

You must use Service Discovery tools! More [here](https://ocelot.readthedocs.io/en/latest/features/servicediscovery.html)


> Yes, it does need to consider multiple impacts. Currently, I am trying to rewrite the Consul service discovery provider to achieve this goal.

First, stop lying us!
Second, fork Ocelot repo! And, good luck!
