### ISSUE TITLE
Multiple Ocelot.Json Configuration Issue

### ISSUE THREAD

**Issue by SheruGaur** [ThreeMammals/Ocelot#1791]
We are facing issue in on fly changes in multiple ocelots. Json files, when any Ocelot. Json file configuration changed then require changes not reflecting in respective configuration file in Api gateway.  Kindly suggest any prior solution to resolve this issue.

Thanks,

**Comment by raman-m** [comment]
Hey, Sheru!
Why didn't you fork the repository?

Based on your description in 2 sentences, I would say, I don't see any issues.
Just keep all config files in repo or in file system of gateway app. And restart your app to get all files merged to one **ocelot,json** file. Re-distribute this file! And be happy!

**Comment by SheruGaur** [comment]
Hey Raman - Thank you for being provided solution but I did understand for given solution.  I have to scenario please suggest prior solution in detailed manner.

1.  I have two service configurations Json file A and B, when I have created ocelot.global.json file in gateway then ocelot. Json file created in gateway but when not included ocelot.global.json file then ocelot. Json file not created. So, it is compulsory to include ocelot.global.json file for working with multiple service configuration files? On fly changes will be reflect when dynamic downstream configuration updated in any service configuration file without restart the Api gateway.

3.  How to call swagger when working with multiple service configuration files?
