### ISSUE TITLE
Latest build breaking

### ISSUE THREAD

**Issue by ks1990cn** [ThreeMammals/Ocelot#1797]
Latest build breaking @raman-m @ggnaegi 

## Steps to Reproduce the Problem
<img width="944" alt="image" src="https://github.com/ThreeMammals/Ocelot/assets/29522704/d77a64de-95ed-40ac-8733-5618e15e6864">

**Comment by raman-m** [comment]
Hello, Tanmay!
Are you posting to us your build errors from your Visual Studio of unknown solution, as for me?!
Or what are you doing?
If you would like to discuss latest released version, then how were we be able to release in case of build errors?
Our CI-CD build for the release 21.0 is green: [Build 2640](https://circleci.com/gh/ThreeMammals/Ocelot/2640)

**Comment by ks1990cn** [comment]
Yes I can see its green, I am not sure what the problem I am getting. My develop branch of fork is up todate and my pull is getting me this error.

**Comment by ks1990cn** [comment]
Its running fine now for me too, just system restart, clean and build help me. Not sure why VS behave stupid.

**Comment by ks1990cn** [comment]
> Hello, Tanmay! Are you posting to us your build errors from your Visual Studio of unknown solution, as for me?! Or what are you doing? If you would like to discuss latest released version, then how were we be able to release in case of build errors? Our CI-CD build for the release 21.0 is green: [Build 2640](https://circleci.com/gh/ThreeMammals/Ocelot/2640)

Its Ocelot solution, you can see GIT below.

**Comment by raman-m** [comment]
Tanmay, Tanmay... 😉

**Comment by raman-m** [comment]
Pay attention when you switch Git branches in VS you will have invalid builds of previous branch. In this case VS behavior is unpredicted! You can experience errors, warnings and etc...

I recommend you to reload solution in VS, and even clean solution, and rebuild once again.
So, just use very useful VS command "Build -> Clean Solution" ⚠️ 

Good luck in Ocelot development! :wink:

**Comment by ks1990cn** [comment]
Yeah I struggled, not sure why cleanup wasn't helping me, even VS restart too🤣.
I know I faced most stupid thing but I felt issue & you were online.

**Comment by ks1990cn** [comment]
Obviously no one can't merge breaking changes

**Comment by raman-m** [comment]
Choose the real bug from [backlog](https://github.com/ThreeMammals/Ocelot/issues?q=is%3Aopen+is%3Aissue+label%3Abug) and work on it, plz!
