### ISSUE TITLE
Use Polly v8 syntax

### ISSUE THREAD

**Issue by RaynaldM** [ThreeMammals/Ocelot#1875]
Use Polly 8's specific syntax to define resiliencePipelines (vs. PollyPolicies)

_"Polly v8 introduces the concept of [resilience pipelines](https://www.pollydocs.org/pipelines/index.html), a powerful tool that blends one or more resilience strategies. This new API foundation echoes the Policy Wrap of previous versions but is now integrated seamlessly into the core API. All strategies start with a pipeline."_

in v7, we written 
```
// Create and use the IAsyncPolicy
IAsyncPolicy asyncPolicy = Policy
    .Handle<Exception>()
    .WaitAndRetryAsync(3, _ => TimeSpan.FromSeconds(1));

```

in v8, it becomes 

```
// Use the ResiliencePipelineBuilder to start building the resilience pipeline
ResiliencePipeline pipeline = new ResiliencePipelineBuilder()
    .AddRetry(new RetryStrategyOptions
    {
        ShouldHandle = new PredicateBuilder().Handle<Exception>(),
        Delay = TimeSpan.FromSeconds(1),
        MaxRetryAttempts = 3,
        BackoffType = DelayBackoffType.Constant
    })
    .Build(); // After all necessary strategies are added, call Build() to create the pipeline.
```

**Comment by raman-m** [comment]
Wow! Good to know about new Polly 8 features... I see you are big fan of Polly 😉

**Comment by raman-m** [comment]
You need to choose release number: Annual (aka 24.0) or Jan'24 (aka 24.1)
We can include this upgrade even in Annual'23, I see the feature branch, seems we are going to create a PR soon.
Finally you need to choose release to include this feature in. OK?

**Comment by RaynaldM** [comment]
In 24.1

**Comment by raman-m** [comment]
@RaynaldM commented [on Jan 5](https://github.com/ThreeMammals/Ocelot/issues/1875#issuecomment-1878887285):
> In 24.1

No. It will belong to version 23.1 actually. See the milestone version!
