### ISSUE TITLE
Authentication docs could do with a note around .NET 8 changes

### ISSUE THREAD

**Issue by devsbryan** [ThreeMammals/Ocelot#1876]
## Docs Update Suggestion

The section in the authentication docs that deals with overriding the mapping of the `scp` claim no longer applies in .net 8. 
- [Ocelot Authentication | Auth0 by Okta](https://ocelot.readthedocs.io/en/latest/features/authentication.html#auth0-by-okta)

The `JwtSecurityTokenHandler` is no longer the default, and has been replaced by `JsonWebTokenHandler`

The example in the docs will work in .net 8 by simply replacing the reference to the `JwtSecurityTokenHandler`.

i.e.

```csharp
JsonWebTokenHandler.DefaultInboundClaimTypeMap.Remove("scp");
JsonWebTokenHandler.DefaultInboundClaimTypeMap.Add("scp", "scope");
```

It is perhaps also worth mentioning in the docs that this does not solely apply to using Okta (in my case it also applies to Azure AD)

References:

- https://github.com/dotnet/AspNetCore.Docs/issues/30935
- https://learn.microsoft.com/en-us/aspnet/core/security/authentication/claims?view=aspnetcore-8.0#claims-namespaces-default-namespaces
- https://github.com/aspnet/Announcements/issues/508

## Motivation for New Feature
1. Avoid confusion for anyone attempting to configure Ocelot authentication on .NET 8.
2. Without this change, scopes do not work.

## Steps to Reproduce the Problem

n/a

## Specifications

n/a

**Comment by raman-m** [comment]
Hi Bryan!
Welcome to Ocelot world! 🐯 

Thanks for reporting this issue and letting us know about these changes in claims mapping!
**Will you contribute to update the docs?**

Ideally, this issue ticket can be closed by a PR with [acceptance tests](https://github.com/ThreeMammals/Ocelot/tree/develop/test/Ocelot.AcceptanceTests) or develop a [sample](https://github.com/ThreeMammals/Ocelot/tree/develop/samples) to merge.
Writing acceptance tests is not easy.
Create a sample is a bit easier.
But I believe simple updating of our [docs](https://github.com/ThreeMammals/Ocelot/tree/develop/docs) will be fine too.

**Do you have an intention to work on this issue being created by you?**

**Comment by raman-m** [comment]
@devsbryan  Could you help us to upgrade docs plz?

**Comment by jvanderlei** [comment]
@ramam-m Can I do it? 

I would first update the docs, then develop a sample as you suggested earlier

**Comment by raman-m** [comment]
@jvanderlei  Welcome! You are assigned!

**Comment by raman-m** [comment]
Please be aware that we have a strict deadline to complete the [.NET 9 milestone](https://github.com/ThreeMammals/Ocelot/milestone/11) tasks. How soon can you open a pull request?

**Comment by jvanderlei** [comment]
I'll send the PR for the documentation today, I'm now just reading the details on the breaking changes.

**Comment by raman-m** [comment]
> ## Motivation for New Feature
> 1. Avoid confusion for anyone attempting to configure Ocelot authentication on .NET 8.
> 2. Without this change, scopes do not work.
> 

[~bug]: https://img.shields.io/badge/-bug-ee0701.svg

@jvanderlei Please note that the issue has been marked with a [![label: bug][~bug]](https://github.com/ThreeMammals/Ocelot/labels/bug) label. Therefore it would be advisable to write actual unit & acceptance tests to demonstrate the issue. Please include them in the current open PR.
However I have a concern: does Okta Auth provide a sandbox environment for testing and development purposes? How do you utilize Okta?

**Comment by jvanderlei** [comment]
@raman-m All right. I'm not the most versed dev on acceptance testing, but I'll try my best to deliver it until tomorrow. 
And yes, Okta Auth0 provides a development enviroment when you register a new app on them. I'm developing a personal project as a angular SPA and .Net backend

**Comment by raman-m** [comment]
>@jvanderlei [wrote](https://github.com/ThreeMammals/Ocelot/issues/1876#issuecomment-2543127822):

Please don't rush! Please relax this weekend. You may return to writing tests on Monday.
**FYI**, we have a dedicated project for tests: [Ocelot.AcceptanceTests](https://github.com/ThreeMammals/Ocelot/tree/develop/test/Ocelot.AcceptanceTests). Specifically, the tests should be placed in: [AuthenticationTests](https://github.com/ThreeMammals/Ocelot/blob/develop/test/Ocelot.AcceptanceTests/Authentication/AuthenticationTests.cs). However, you may create a `OktaAuthenticationTests` class.

> And yes, Okta Auth0 provides a development environment when you register a new app on them. I'm developing a personal project as a angular SPA and .Net backend

Very well. Could you help us register an Ocelot native account for testing from both local and CircleCI environments? We need your instructions on that...

**Comment by jvanderlei** [comment]
Perfect. And yes, I can. I'll look some more about the registering for CI pipeline, and return to you about this process.

**Comment by raman-m** [comment]
@jvanderlei Any news?
