### ISSUE TITLE
The Getting Started document could be updated for .NET 8

### ISSUE THREAD

**Issue by MatheusXavier** [ThreeMammals/Ocelot#1912]
## Doc Update Suggestion
A little while ago I migrated my project to dotnet 8 and I noticed that the [Getting Started](https://ocelot.readthedocs.io/en/latest/introduction/gettingstarted.html) documentation is a little outdated, for example:
- A namespace is being declared in the `Program` class
- The `Program` class is being declared
- The `Program` class is implementing the `Main` method
- Not using `WebApplication.CreateBuilder`

**Not that these points are serious problems**, but I believe that the documentation could be updated.

During the migration I I implemented my Main class a little differently and published [this article on medium](https://medium.com/p/723d342b828a) to demonstrate my approach.

I am willing to make a PR if you fine folks think this kind of changes is welcome.

**Comment by raman-m** [comment]
Hi Matheus!
Welcome to Ocelot world! 🐯 

Nice [article](https://medium.com/p/723d342b828a)! Thanks you! 
Have you posted this article to LinkedIn network?

---
> **Not that these points are serious problems**, but I believe that the documentation could be updated.

Not serious! It could be, because we support .NET 6+ only since November'23.

Have you ever thought in terms of backward compatibility?
This old, legacy `Program.Main` startup approach is supported by .NET 6+ SDKs also...
But Yes, because .NET 6+ app can have implicit entry point aka [Top-level statements](https://learn.microsoft.com/en-us/dotnet/csharp/fundamentals/program-structure/top-level-statements) so it  makes sense to upgrade the docs and [samples](https://github.com/ThreeMammals/Ocelot/tree/develop/samples) apps.

I you have intention to contribute, I would ask you update all [samples](https://github.com/ThreeMammals/Ocelot/tree/develop/samples) apps too... 🆗 ❔

**Comment by MatheusXavier** [comment]
Hello Raman!

Thank you!

---

> Have you posted this article to LinkedIn network?

No, I have not, only on medium.

---

> Have you ever thought in terms of backward compatibility?

Thinking about backwards compatibility, I don't think it will be a problem because we don't need to apply everything in the article and almost everything in it works in dotnet 6.

---

> If you have intention to contribute, I would ask you update all [samples](https://github.com/ThreeMammals/Ocelot/tree/develop/samples) apps too... 🆗 ❔

Ok, I'll update the [samples apps](https://github.com/ThreeMammals/Ocelot/tree/develop/samples) and the [getting started doc](https://github.com/ThreeMammals/Ocelot/blob/develop/docs/introduction/gettingstarted.rst).


Can you create a new branch for me so I can work on it?

**Comment by ggnaegi** [comment]
@MatheusXavier you should fork the repo, then create your own branch in the forked repo. When you are ready, you can from there create a PR.

**Comment by raman-m** [comment]
@MatheusXavier As @ggnaegi said, you have to fork Ocelot repo and create feature branch in your forked repo.
More about our development process: [Release Process](https://ocelot.readthedocs.io/en/latest/building/releaseprocess.html)

**Comment by raman-m** [comment]
Three months have passed!..
@MatheusXavier, where are you?
You need to update your [develop branch](https://github.com/MatheusXavier/Ocelot/commits/develop/) to be identical to head repo one! Not it has [the diff](https://github.com/MatheusXavier/Ocelot/compare/develop...ThreeMammals%3AOcelot%3Adevelop). The diff must be zero, no changes at all.

Also I see the feature branch: [1912-update-docs-and-apps-samples](https://github.com/MatheusXavier/Ocelot/tree/1912-update-docs-and-apps-samples)
But it has [no much changes](https://github.com/ThreeMammals/Ocelot/compare/develop...MatheusXavier:Ocelot:1912-update-docs-and-apps-samples), very initial development.
Why did you stop development on Jan 13?
What's your plan of delivery?

**Comment by raman-m** [comment]
You have the right to reopen this issue in the future if you come with a PR ready.

**Comment by raman-m** [comment]
@MatheusXavier Hello Matheus!
How have you been in 2024? Have you written articles on Medium blogs related to Ocelot? 😉 I have an idea to publish them in Discussions [Show and Tell](https://github.com/ThreeMammals/Ocelot/discussions/show-and-tell) articles, as we currently do not have a dedicated Ocelot blog.

> Thinking about backwards compatibility, I don't think it will be a problem because we don't need to apply everything in the article and almost everything in it works in dotnet 6.

Please note that we have discontinued support for .NET 6 and 7 and we are now migrating Ocelot to .NET 9, with .NET 8 as the major LTS version. Consequently, your issue opened on January 9 has become highly relevant. It appears we need to address the ticket and move it into active progress. **Are you still with Ocelot and able to assist us?**

**Comment by raman-m** [comment]
@MatheusXavier commented [on Jan 9, 2024](https://github.com/ThreeMammals/Ocelot/issues/1912#issue-2071401466)
> I am willing to make a PR if you fine folks think this kind of changes is welcome.

An entire year has passed 🤔  What is a PR number? 🙉

**Comment by MatheusXavier** [comment]
Hi @raman-m 

Unfortunately I didn't have time to implement that, I also switch between job and now I'm not working with Ocelot anymore, thank you for all support but I'm going to close this issue.

**Comment by raman-m** [comment]
Updating samples is required!
