### ISSUE TITLE
UpstreamHost not working

### ISSUE THREAD

**Issue by nrllhylmz** [ThreeMammals/Ocelot#1925]
Hi,

I upgraded ocelot. (18.0.0 -> 22.0.1)
"UpstreamHost" worked without problems in the old version but it doesn't work in the latest version.
Ocelot failed to match routes.
I deleted this feature. Routes matched. But i want to seperate host(UpstreamHost).

Thanks

**Comment by raman-m** [comment]
> ### UpstreamHost not working

Why do you think so? Our unit & acceptance tests are green! 😉 

----
> I upgraded ocelot. (18.0.0 -> 22.0.1)

Maybe something wrong with the upgrade process...

----
> Ocelot failed to match routes.

Wow! Please provide more details: **ocelot.json** file, logs with errors info, and etc.
Which routes? We don't see them! 😉 

----
>I deleted this feature. Routes matched. But i want to seperate host(UpstreamHost).

Sorry? What have you deleted and how?

**Comment by nrllhylmz** [comment]
Ocelot 18.0.0 working but Ocelot 22.0.1 not working.
Deleted UpstreamHost. Working. But i want to seperate upstreamhost.
 
Warnings;
 
requestId: 0HN0MJFAEUU8F:00000009, previousRequestId: No PreviousRequestId, message: 'Error Code: UnableToFindDownstreamRouteError Message: Failed to match Route configuration for upstream path: /test/WeatherForecast, verb: GET. errors found in ResponderMiddleware. Setting error response for request path:/test/WeatherForecast, request method: GET'
 
requestId: 0HN0MJFAEUU8F:00000009, previousRequestId: No PreviousRequestId, message: 'DownstreamRouteFinderMiddleware setting pipeline errors. IDownstreamRouteFinder returned Error Code: UnableToFindDownstreamRouteError Message: Failed to match Route configuration for upstream path: /test/WeatherForecast, verb: GET.'
 
My ocelot.json:
 
{
  "Routes": [
    {
      "DownstreamPathTemplate": "/{everything}",
      "UpstreamPathTemplate": "/test/{everything}",
      "UpstreamHttpMethod": [
      ],
      "DownstreamHttpMethod": null,
      "AddHeadersToRequest": {
      },
      "UpstreamHeaderTransform": {
      },
      "DownstreamHeaderTransform": {
      },
      "AddClaimsToRequest": {
      },
      "RouteClaimsRequirement": {
      },
      "AddQueriesToRequest": {
      },
      "ChangeDownstreamPathTemplate": {
      },
      "RequestIdKey": null,
     "FileCacheOptions": {
        "TtlSeconds": 0,
        "Region": null
      },
      "RouteIsCaseSensitive": false,
      "ServiceName": null,
      "ServiceNamespace": null,
      "DownstreamScheme": "https",
      "QoSOptions": {
        "ExceptionsAllowedBeforeBreaking": 0,
        "DurationOfBreak": 0,
        "TimeoutValue": 0
      },
      "LoadBalancerOptions": {
        "Type": null,
        "Key": null,
        "Expiry": 0
      },
      "RateLimitOptions": {
        "ClientWhitelist": [
        ],
        "EnableRateLimiting": false,
        "Period": null,
        "PeriodTimespan": 0.0,
        "Limit": 0
      },
      "AuthenticationOptions": {
        "AuthenticationProviderKey": null,
        "AllowedScopes": [
        ]
      },
      "HttpHandlerOptions": {
        "AllowAutoRedirect": false,
        "UseCookieContainer": false,
        "UseTracing": false,
        "UseProxy": true,
        "MaxConnectionsPerServer": 2147483647
      },
      "DownstreamHostAndPorts": [
        {
          "Host": "localhost",
          "Port": 7071
        }
      ],
      "UpstreamHost": "localhost:6001",
      "Key": null,
      "DelegatingHandlers": [
      ],
      "Priority": 1,
      "Timeout": 0,
      "DangerousAcceptAnyServerCertificateValidator": false,
      "SecurityOptions": {
        "IPAllowedList": [
        ],
        "IPBlockedList": [
        ]
      },
      "DownstreamHttpVersion": null
    }
  ],
  "DynamicRoutes": [
  ],
  "Aggregates": [
  ],
  "GlobalConfiguration": {
    "RequestIdKey": null,
    "ServiceDiscoveryProvider": {
      "Scheme": null,
      "Host": null,
      "Port": 0,
      "Type": null,
      "Token": null,
      "ConfigurationKey": null,
      "PollingInterval": 0,
      "Namespace": null
    },
    "RateLimitOptions": {
      "ClientIdHeader": "ClientId",
      "QuotaExceededMessage": null,
      "RateLimitCounterPrefix": "ocelot",
      "DisableRateLimitHeaders": false,
      "HttpStatusCode": 429
    },
    "QoSOptions": {
      "ExceptionsAllowedBeforeBreaking": 0,
      "DurationOfBreak": 0,
      "TimeoutValue": 0
    },
    "BaseUrl": "https://localhost:6001",
    "LoadBalancerOptions": {
      "Type": null,
      "Key": null,
      "Expiry": 0
    },
    "DownstreamScheme": null,
    "HttpHandlerOptions": {
      "AllowAutoRedirect": false,
      "UseCookieContainer": false,
      "UseTracing": false,
      "UseProxy": true,
      "MaxConnectionsPerServer": 2147483647
    },
    "DownstreamHttpVersion": null
  }
}

**Comment by nrllhylmz** [comment]
I delete "UpstreamHost":"localhost:6001" and it worked.
I want to use "UpstreamHost"

**Comment by raman-m** [comment]
> I upgraded ocelot. (18.0.0 -> 22.0.1)

then
> Setting error response for request path:**/test/WeatherForecast**, request method: GET'

Aha... 🤣 He upgraded... Aha! 😠 

Why do you lie, my dear anonim? 😡

**Comment by raman-m** [comment]
> @nrllhylmz commented [5 hours ago](https://github.com/ThreeMammals/Ocelot/issues/1925#issuecomment-1893826657)

Now it is better, my dear Anonim! We have your JSON! 🤣 
Why did you copied-pasted all JSON schema for Route definition?

-----
Your very zipped JSON
```json
  "Routes": [],
  "DynamicRoutes": [],
  "Aggregates": [],
```
Do you understand that JSON is invalid?
Why do you use static routes and dynamic routes simultaneously? 👶

**Comment by raman-m** [comment]
@nrllhylmz commented [on Jan 16](https://github.com/ThreeMammals/Ocelot/issues/1925#issuecomment-1893838806):

----
> I delete "UpstreamHost":"localhost:6001" and it worked.
> I want to use "UpstreamHost"

But why do you need to use `UpstreamHost` if you have single route in development environment? 😄
Read [UpstreamHost](https://ocelot.readthedocs.io/en/latest/features/routing.html#upstream-host) docs and you will get that feature is based on `Host` header! You just cannot make request from Ocelot instance app to itself!

-----
Your very zipped JSON
```json
{
  "Routes": [
    {
      "DownstreamPathTemplate": "/{everything}",
      "UpstreamPathTemplate": "/test/{everything}",
      "DownstreamScheme": "https",
      "DownstreamHostAndPorts": [
        {
          "Host": "localhost", "Port": 7071
        }
      ],
      "UpstreamHost": "localhost:6001",
    }
  ],
  "GlobalConfiguration": {
    "BaseUrl": "https://localhost:6001",
    "DownstreamHttpVersion": null
  }
}
```
Don't you see the issue?
You cannot use "**UpstreamHost**" with value `localhost:6001` because "**BaseUrl**" is `https://localhost:6001` !!!
You cannot make requests from Ocelot instance to itself!
"**UpstreamHost**" property is used to filter incoming requests from various domains in DNS form but not from Base URL of Ocelot host & port! It is impossible!
That is why you have error: ` Failed to match Route configuration for upstream path: /test/WeatherForecast` which says that Ocelot cannot find route!

**What are you doing?** 🤯

**Comment by nrllhylmz** [comment]
Dear @raman-m,

I did not lie. 
I upgraded the ocelot package. (18.0.0 -> 22.0.1).
ocelot.json worked fine for ocelot 18.0.0. 
But it didn't work for 22.0.1.
I loged the above warnings.
Then I deleted the ("UpstreamHost": "localhost:6001") attribute. 
The route matched.

"Why did you copy-paste all JSON schema for Route definition?" => I read configurations from multiple files, merged them and created "ocelot.json" when starting the service.

--------------------------------------------------------------
My scenario:

For Ocelot 18.0.0:
"localhost:6001/test/WeatherForecast" route matched.
"localhost:6002/test/WeatherForecast" route not found.

For Ocelot 22.0.1: (there is ("UpstreamHost": "localhost:6001") property)
"localhost:6001/test/WeatherForecast" route not found.
"localhost:6002/test/WeatherForecast" route not found.

For Ocelot 22.0.1:  (there is ("UpstreamHost": "localhost:6001") property)
"localhost:6001/test/WeatherForecast" route matched.
"localhost:6002/test/WeatherForecast" route matched.
--------------------------------------------------------------

Please don't treat me like I'm lying.
trust me. just try Configuration. You will see that it is correct.
Thanks.

**Comment by raman-m** [comment]
What's your full name, my dear anonymous liar?
Otherwise I will stop communication

**Comment by raman-m** [comment]
> trust me. just try Configuration. You will see that it is correct.

Don't ask for my trust while saying trash!

**Comment by nrllhylmz** [comment]
I guess you won't believe me.
Anyway thank you for your answers.

**Comment by raman-m** [comment]
What's your name my experienced engineer?

**Comment by raman-m** [comment]
Nurullah Yılmaz

Got it!
I recommend you to start reading [Ocelot docs](https://ocelot.readthedocs.io/en/latest/introduction/gettingstarted.html) from very beginning.

**Comment by raman-m** [comment]
@nrllhylmz commented [on Jan 16](https://github.com/ThreeMammals/Ocelot/issues/1925#issuecomment-1894466419):
>**I guess you won't believe me.**
Anyway thank you for your answers.

I guess you waste my time.
Please, help yourself!

**Comment by nrllhylmz** [comment]
I ran the routes with ocelot 18.0.0.
There is no problem in my project.
My goal is to help you.
I can continue ocelot 18.0.0
There is a situation where ocelot 18.0.0 works but ocelot 22.0.1 does not.
Not working feature "UpstreamHost"
I showed an example project above.
What you need to do is to start multiple projects.
I explained everything above.
Stop being angry at me. Correct your approach.
Just open Visual Studio.
Run multiple start projects. As I said above.
You will see routes that do not match.
It won't take 5 minutes.
Please,help yourself

**Comment by raman-m** [comment]
Your next created #1926 will be checked by our QA engineer... You can talk to him.
