### ISSUE TITLE
Ocelot is missing NuGet package README file

### ISSUE THREAD

**Issue by lyndaidaii** [ThreeMammals/Ocelot#1959]
We've noticed that your package on NuGet.org is missing a README file.

  ## Why READMEs are Important
  A README is essential for users to understand your package's purpose and functionality quickly. It's the first thing users see on NuGet.org and helps them decide if your package meets their needs.

  ## Get Started with READMEs

  ### How to Add a README
  If you're new to NuGet READMEs, follow guidance on [how to add one to your package](https://devblogs.microsoft.com/nuget/add-a-readme-to-your-nuget-package/).

  ### How to write high quality of READMEs
  Follow [a blog post](https://devblogs.microsoft.com/nuget/write-a-high-quality-readme-for-nuget-packages/) with README best practices and a template file to help you get started. 

  ## We Value Your Feedback
  We value your feedback. If you encounter any issues or have suggestions, please reply to this issue.

  Thank you for your contribution to the NuGet community.

**Comment by ggnaegi** [comment]
Hello @lyndaidaii,

Thank you for your feedback. We're committed to improving our documentation and will include a revised README with our upcoming release. Unfortunately, your suggestions arrived just after we finalized Release 23.0.0, so we couldn't incorporate them this time.

**Comment by raman-m** [comment]
Scope of work
- Update **.csproj** files
- Update README
- DevOps tasks related to NuGet

@ggnaegi  FYI
We are blocked on DevOps tasks due to permissions
I've added this issue to Annual'23 milestone

**Comment by raman-m** [comment]
### NuGet administration
- [Ocelot](https://www.nuget.org/packages/Ocelot) package has 3 owners now including new [ThreeMammals](https://www.nuget.org/profiles/ThreeMammals) organization account
- [ThreeMammals](https://www.nuget.org/profiles/ThreeMammals) profile page correctly displays 1 [Ocelot](https://www.nuget.org/packages/Ocelot) package now
- [Ocelot](https://www.nuget.org/packages/Ocelot) package is/will be managed by 3 owners: [mijitt0m](https://www.nuget.org/profiles/mijitt0m), [raman-m](https://www.nuget.org/profiles/raman-m) and [ThreeMammals](https://www.nuget.org/profiles/ThreeMammals) org

**Comment by hogwartsdeveloper** [comment]
I'd like to do this

**Comment by hogwartsdeveloper** [comment]
#2074

**Comment by hogwartsdeveloper** [comment]
#2074

**Comment by raman-m** [comment]
@hogwartsdeveloper OK You are assigned
