### ISSUE TITLE
Rate Limiting issues in Ocelot

### ISSUE THREAD

**Issue by SheruGaur** [ThreeMammals/Ocelot#1975]
Rate Limit is not working when period and period timespan values are different. When we are making same value for period and period timespan then it is working for Rate limiting on configured service. In below configuration first case Rate Limiting is working and in second case Rate Limiting is not working.
1. First Case
 "RateLimitOptions": {
   "ClientWhitelist": ["HOR777"],
   "EnableRateLimiting": true,
   "Period": "10s",
   "PeriodTimespan": 10,
   "Limit": 2
 },
1. Second Case
 "RateLimitOptions": {
   "ClientWhitelist": ["HOR777"],
   "EnableRateLimiting": true,
   "Period": "10s",
   "PeriodTimespan": 15,
   "Limit": 2
 },
Please provide the solution because rate Limiting is not working as per Ocelot documentation. Please provide it is product backlog or ongoing issues.

**Comment by raman-m** [comment]
Thanks for reporting to us once again! But this is well-known #1590 bug ❕

**Comment by raman-m** [comment]
And stop terrifying us with duplicated bugs ❗ 

Please start your contribution the project! 🆗 ❔

**Comment by SheruGaur** [comment]
Thanks, you @raman-m for update and solution.  Currently I am fully occupied in my ongoing project.  Sure, I will be ready to contribute to your project whenever i am free up here.

**Comment by SheruGaur** [comment]
@raman-m  My linkdin id is Sheru Kumar Gaur

**Comment by raman-m** [comment]
Please watch for PR #1592 #1590 news!
Closing because of duplication...
