### ISSUE TITLE
Ocelot Downstream Request Timeout

### ISSUE THREAD

**Issue by SheruGaur** [ThreeMammals/Ocelot#1976]
Dear Team,

What is the default Ocelot Downstream Request Timeout which giving error code  503?

**Comment by raman-m** [comment]
@SheruGaur  Sorry?
Default HTTP request timeout is 90 seconds, without QoS/Polly setup.

----
> which giving error code 503?

What are you talking about?

**Comment by SheruGaur** [comment]
Thanks for update @raman-m

**Comment by raman-m** [comment]
Please, update the description, otherwise the issue will be closed!

**Comment by SheruGaur** [comment]
Thanks for update now you can close it , my doubt is clear now
