### ISSUE TITLE
404 exception caused by QoS configuration item conflict

### ISSUE THREAD

**Issue by RainySeason673** [ThreeMammals/Ocelot#2075]
## Steps to Reproduce the Problem

  1. use follow two configuration items together:
`
"QoSOptions": {
        "ExceptionsAllowedBeforeBreaking": 3, 
        "TimeoutValue": 3000 
      }
`
  2. send any Route request
  3. get a 404 error response

## Specifications

  - Version:23.1.0
  - Platform:.Net 7.0
  - Subsystem:

**Comment by raman-m** [comment]
Dear Tang,
We can't accept this short description and reproduce your problem!

Could you please provide additional details on the issue? Such as logs, configuration JSON, and the health check status of the downstream service, etc.?

Additionally, you may pose [questions](https://github.com/ThreeMammals/Ocelot/discussions/categories/q-a) in the [Discussions](https://github.com/ThreeMammals/Ocelot/discussions) space.

**Comment by RainySeason673** [comment]
This is an obvious and simple bug, and I have tried to print some logs for your reference

**Comment by RainySeason673** [comment]
downstream service status is normal, success open by Url

**Comment by RainySeason673** [comment]
downstream service status is normal, success open by Url , when i comment  "ExceptionsAllowedBeforeBreaking" or "TimeoutValue",everything will be OK

**Comment by RaynaldM** [comment]
> downstream service status is normal, success open by Url , when i comment "ExceptionsAllowedBeforeBreaking" or "TimeoutValue",everything will be OK

try to add  "DurationOfBreak": yourValue in QoS Section

**Comment by raman-m** [comment]
> when i comment "ExceptionsAllowedBeforeBreaking" or "TimeoutValue",everything will be OK

If the route works well without enabled [QoS](https://ocelot.readthedocs.io/en/latest/features/qualityofservice.html), then why are you writing us and reporting the issue?
Read the docs &rarr; [QoS](https://ocelot.readthedocs.io/en/latest/features/qualityofservice.html)

If you have more questions then post them to [Q-&-A](https://github.com/ThreeMammals/Ocelot/discussions/categories/q-a) discussions❗

As a team, we don't see any issues with Ocelot. There is misconfiguration issue of your `ocelot.json`

**Comment by raman-m** [comment]
@RaynaldM  It can be a bug...

> 
> 1. use follow two configuration items together:
> ```json
> "QoSOptions": {
>         "ExceptionsAllowedBeforeBreaking": 3, 
>         "TimeoutValue": 3000 
>       }
> ````
> 

So, possibly absence of `DurationOfBreak` can generate an exception. But I wonder if there is no default value for `DurationOfBreak`.

It seems we have to investigate this case...

**Comment by RainySeason673** [comment]
> > downstream service status is normal, success open by Url , when i comment "ExceptionsAllowedBeforeBreaking" or "TimeoutValue",everything will be OK
> 
> try to add "DurationOfBreak": yourValue in QoS Section

actually, I have already configured this item, but the problem is not with it

**Comment by RainySeason673** [comment]
> @RainySeason673
> 
> > when i comment "ExceptionsAllowedBeforeBreaking" or "TimeoutValue",everything will be OK
> 
> If the route works well without enabled [QoS](https://ocelot.readthedocs.io/en/latest/features/qualityofservice.html), then why are you writing us and reporting the issue? Read the docs → [QoS](https://ocelot.readthedocs.io/en/latest/features/qualityofservice.html)
> 
> If you have more questions then post them to [Q-&-A](https://github.com/ThreeMammals/Ocelot/discussions/categories/q-a) discussions❗
> 
> As a team, we don't see any issues with Ocelot. There is misconfiguration issue of your `ocelot.json`

My configurations are all from official [documents](https://ocelot.readthedocs.io/en/latest/features/qualityofservice.html) , so why do you think there is misconfiguration of my ocelot.json? and why not confirm if this issue exists？

**Comment by RainySeason673** [comment]
`
{
  "Routes": [
    {
      "DownstreamPathTemplate": "/profile",
      "DownstreamScheme": "http",
      "DownstreamHostAndPorts": [
        {
          "Host": "localhost",
          "Port": 5001
        }
      ],
      "DownstreamHeaderTransform": {
        "Access-Control-Allow-Oringin": "http://localhost:8070" //允许前端地址跨域
      },
      "UpstreamPathTemplate": "/profile",
      "UpstreamHttpMethod": [ "Get" ], //TODO 这里配置options是否可以直接处理预检请求？如果不行还是自定义一个中间件来实现
      // 熔断设置
      "QoSOptions": {
        "ExceptionsAllowedBeforeBreaking": 3, //允许多少个异常请求
        "DurationOfBreak": 10000, // 熔断的时间，单位为ms
        "TimeoutValue": 36000 //单位ms 如果下游请求的处理时间超过多少则自如将请求设置为超时 默认90秒
      }
    },
    {
      "UpstreamPathTemplate": "/order/swagger/v1/swagger.json",
      "UpstreamHttpMethod": [ "Get" ],
      "DownstreamPathTemplate": "/swagger/v1/swagger.json",
      "DownstreamScheme": "http",
      "DownstreamHostAndPorts": [
        {
          "Host": "localhost",
          "Port": 5931
        }
      ]
    },
    {
      "UpstreamPathTemplate": "/user/swagger/v1/swagger.json",
      "UpstreamHttpMethod": [ "Get" ],
      "DownstreamPathTemplate": "/swagger/v1/swagger.json",
      "DownstreamScheme": "http",
      "DownstreamHostAndPorts": [
        {
          "Host": "localhost",
          "Port": 5930
        }
      ]
    }
  ],

  "GlobalConfiguration": {
    "RequestIdKey": "ot-traceid"
  }
}

`
this is my ocelot.json

**Comment by raman-m** [comment]
Define [Catch All](https://ocelot.readthedocs.io/en/latest/features/routing.html#catch-all) route for `/user` and `/order` paths and forget about the issue:
```json
"UpstreamPathTemplate": "/order/{catchAll}",
"DownstreamPathTemplate": "/{catchAll}",
```
and
```json
"UpstreamPathTemplate": "/user/{catchAll}",
"DownstreamPathTemplate": "/{catchAll}",
```
Also you need define all possible HTTP verbs.

Hope it helps!
