### ISSUE TITLE
 Error Code: UnableToFindDownstreamRouteError (404)

### ISSUE THREAD

**Issue by ldc999** [ThreeMammals/Ocelot#2108]
Hi,I encountered a tricky problem and need help.
## Steps to Reproduce the Problem

1.I referred to the [doucement ](https://ocelot.readthedocs.io/en/latest/introduction/gettingstarted.html)page and established the following project code as shown in the image.
![image](https://github.com/ThreeMammals/Ocelot/assets/32814992/fc7f21b1-eeee-4a31-b418-04d17b960ff0)
2.Then, I tried to request the interface, but the response was 404. However, if I comment out app.UseOcelot().Wait();, it is accessible
  
![image](https://github.com/ThreeMammals/Ocelot/assets/32814992/57aa71c5-342a-42b2-af4a-d0dbdab868bb)

3. And VisualStdio Console output:
  Ocelot.DownstreamRouteFinder.Middleware.DownstreamRouteFinderMiddleware: Warning: requestId: 0HN4G6KHG2BGO:00000002, previousRequestId: No PreviousRequestId, message: 'DownstreamRouteFinderMiddleware setting pipeline errors. IDownstreamRouteFinder returned Error Code: UnableToFindDownstreamRouteError Message: Failed to match Route configuration for upstream path: /WeatherForecast, verb: GET.'
Ocelot.Responder.Middleware.ResponderMiddleware: Warning: requestId: 0HN4G6KHG2BGO:00000002, previousRequestId: No PreviousRequestId, message: 'Error Code: UnableToFindDownstreamRouteError Message: Failed to match Route configuration for upstream path: /WeatherForecast, verb: GET. errors found in ResponderMiddleware. Setting error response for request path:/WeatherForecast, request method: GET'

  - Version: Ocelot V23.3.3
  - Platform:.NET8
  - Subsystem:Windows

**Comment by raman-m** [comment]
## 🤣
