### ISSUE TITLE
Invalid pattern **

### ISSUE THREAD

**Issue by JonHsiang** [ThreeMammals/Ocelot#2113]
Invalid pattern '\burl=api/ResumeSearch/SearchResultList/10-635**1/1/10\b' at offset 48. Nested quantifier '*'.

**Comment by raman-m** [comment]
Dear Jon,
You have to use **issue** template from the [.github](https://github.com/ThreeMammals/Ocelot/tree/develop/.github) folder.


Please add more details and reopen the issue.
I'm going to close because of the lack of details
