### ISSUE TITLE
New Feature - Websocket support

### ISSUE THREAD

**Issue by gromanev** [ThreeMammals/Ocelot#212]
Hello. Tell me, does Ocelot work with a websocket? And if it works, tell me how to configure your server to work with it?

My config:

> {
      "DownstreamPathTemplate": "/signalr/{everything}",
      "DownstreamScheme": "ws",
      "DownstreamPort": 5000,
      "DownstreamHost": "localhost",
      "UpstreamPathTemplate": "/signalr/{everything}",
      "UpstreamHttpMethod": [ "Get", "Post", "Options" ]
    },

**Comment by TomPallister** [comment]
@gromanev Thanks for your interest in the project.

Ocelot doesnt have any websockets support at the moment, this is something that may be added in the future. If you need it now I would suggest finding another piece of software that supports it or study the Ocelot source code and implement the functionality!

**Comment by gromanev** [comment]
@TomPallister Thanks for the answer. I already use the nginx as a reverse proxy for the websocket. But I do not particularly like this decision, but if the plans to implement support for a web-site - it will be wonderful. Hardly I can help with the implementation, since my programming level is unfortunately weak.

**Comment by TomPallister** [comment]
@gromanev no one is weak! Just need time and experience to learn :)

**Comment by TomPallister** [comment]
https://stackoverflow.com/questions/39220423/chain-2-websockets-in-net-using-asp-net-4-5

^^ might be useful

**Comment by geffzhang** [comment]
This Project has a websocket Middleware https://github.com/radu-matei/websocket-manager

**Comment by SrikanthNalam** [comment]
@TomPallister. Any further update on this regarding the implementation of Web-sockets in Ocelot Package ?

**Comment by TomPallister** [comment]
@SrikanthNalam I have something working that takes the websocket request and sets up a proxy with a downstream server also listening for websockets. Basically a websockets proxy. Is this what you are looking for?

**Comment by TomPallister** [comment]
Just released version 5.3.0 that has the websockets proxy support...check out the docs http://ocelot.readthedocs.io/en/latest/features/websockets.html

**Comment by ogomaemmanuel** [comment]
Does it work with signalr

**Comment by TomPallister** [comment]
@ogomaemmanuel not yet. There is another issue open for this.
