### ISSUE TITLE
.NET 9 update will break one of the tests because of a new `TrimStart` overload

### ISSUE THREAD

**Issue by AndyAyersMS** [ThreeMammals/Ocelot#2145]
## Expected Behavior / New Feature

Updating to .NET 9 is easy.

## Actual Behavior / Motivation for New Feature

Updating to .NET 9 will cause the GetServiceVersion_HasTags_HappyPath to fail, because a new `TrimStart` overload was added that takes priority over https://github.com/ThreeMammals/Ocelot/blob/19a8e2f8b3e773fbe962a56fc2e7067b6b19132b/src/Ocelot/Infrastructure/Extensions/StringExtensions.cs#L5

See https://github.com/dotnet/runtime/issues/103892

## Steps to Reproduce the Problem

Update to .NET 9.
Run tests.

## Specifications

  - Version:
  - Platform:
  - Subsystem:

**Comment by raman-m** [comment]
Hello Andy,
Thank you for bringing this humorous issue to our attention!
Rest assured, we will address it and rename the extension method accordingly while migrating Ocelot to .NET 9 in November'24.

**Comment by ggnaegi** [comment]
@raman-m Whaaaat? 😸

**Comment by RaynaldM** [comment]
@raman-m I think it's premature to plan a migration to net 9, it's still in preview, I think it would be wise to wait for a 9.0.1 or 9.0.2 in January or February.

**Comment by raman-m** [comment]
@RaynaldM 
>I think it would be wise to wait for a 9.0.1 or 9.0.2 in January or February.

Did you mean 9.1.0 or 9.2.0? 😄  So, in January/February '25 we will definitely have versions 9.1.0+ 🤣 
OK not kidding... In my opinion we have to migrate to .NET 9 right after the big release allowing Ocelot fans to migrate too.
This upgrade is important because we will:
- remove `net6.0` and `net7.0` targets
- add new `net9.0` target in addition to `net8.0`

I expect to migrate in a week (Nov 15-20) after .NET 9.0 release on November 12, 2024

**Comment by KeterSCP** [comment]
Note, that there is a PR that removes new overloads: https://github.com/dotnet/runtime/pull/108537

**Comment by raman-m** [comment]
@KeterSCP Referencing the .NET repository may not address the issue at hand, as it is not related to Ocelot's functionality. The resolution timeline for this in .NET 9 is uncertain. Nonetheless, we plan to rename our extension method prior to the release of Ocelot's .NET 9 edition. The method in question is referenced only once in our repository. While removal is an option, renaming is preferable for continuity.

**Comment by KeterSCP** [comment]
@raman-m the issue here is related strictly to the new BCL method, and that's why I referenced runtime repo which "fixes" the root cause of this issue. I suppose the removal will be backported to .NET 9 RC2 before global release in November

**Comment by raman-m** [comment]
@KeterSCP Dear Sergiusz,
I'm not concerned with Microsoft's affairs. Currently, Ocelot does not have a .NET 9 edition, and my attention to this issue stems solely from an official request by a Microsoft developer who seems to be engaging with forked repositories of Ocelot.
I recommend you also not wasting the time with any .NET 9 games until official Ocelot `net9.0` release.

**Comment by raman-m** [comment]
### .NET Runtime
In the .NET codebase, we have the following extensions: Search for [TrimStart](https://github.com/search?q=repo%3Adotnet%2Fruntime%20TrimStart&type=code).
It is advisable to move away from this name, thus renaming the method in Ocelot is necessary.
