### ISSUE TITLE
The final slash is missing from downstream path

### ISSUE THREAD

**Issue by ushenkodmitry** [ThreeMammals/Ocelot#2155]
## Expected Behavior / New Feature
With configuration:
```
      "DownstreamPathTemplate": "/some/fancy/{someId}/path/",
      "UpstreamPathTemplate": "/some/fancy/{someId}/path/blah",
```
I expect that called downstream url will be .../some/fancy/{someId}/path/ (contains final slash)
## Actual Behavior / Motivation for New Feature
Actual downstream path is .../some/fancy/{someId}/path (no final slash)

## Steps to Reproduce the Problem

  1.
  1.
  1.

## Specifications

  - Version: 23.3.3
  - Platform: Windows, Linux
  - Subsystem:

**Comment by raman-m** [comment]
Hello, Dmitry!

To preserve the last slash, you can utilize the [Empty Placeholders](https://ocelot.readthedocs.io/en/latest/features/routing.html#empty-placeholders) feature. Therefore, you should move the `/blah` suffix to the prefix section like this:
```json
      "DownstreamPathTemplate": "/some/fancy/{someId}/path/",
      "UpstreamPathTemplate": "/blah/some/fancy/{someId}/path/",
```
When both `{someId}/path/` segments match, they can be consolidated into a true [Catch All](https://ocelot.readthedocs.io/en/latest/features/routing.html#catch-all) placeholder:
```json
      "DownstreamPathTemplate": "/some/fancy/{something}",
      "UpstreamPathTemplate": "/blah/some/fancy/{something}",
```
The routing should function as follows:
- The URL `/blah/some/fancy` &rarr; `/some/fancy` downstream.
- The URL `/blah/some/fancy/` &rarr; `/some/fancy/` downstream.
- The URL `/blah/some/fancy/123` &rarr; `/some/fancy/123` downstream.
- The URL `/blah/some/fancy/123/` &rarr; `/some/fancy/123/` downstream.
- The URL `/blah/some/fancy/123/path` &rarr; `/some/fancy/123/path` downstream.
- The URL `/blah/some/fancy/123/path/` &rarr; `/some/fancy/123/path/` downstream.

To maintain the `{someId}` placeholder for custom classes (middlewares), your solution appears to be:
```json
      "DownstreamPathTemplate": "/some/fancy/{someId}/path/{blah}",
      "UpstreamPathTemplate": "/some/fancy/{someId}/path/{blah}",
```
The routing should function as follows:
- The URL `/some/fancy/123/path` &rarr; `/some/fancy/123/path` downstream.
- The URL `/some/fancy/123/path/` &rarr; `/some/fancy/123/path/` downstream.
- The URL `/some/fancy/123/path/blah` &rarr; `/some/fancy/123/path/blah` downstream.
- The URL `/some/fancy/123/path/blah/` &rarr; `/some/fancy/123/path/blah/` downstream.
- The URL `/some/fancy/123/path/blah?x=1` &rarr; `/some/fancy/123/path/blah?x=1` downstream.

Hope it helps!

**Comment by ushenkodmitry** [comment]
Thank you, Roman.
In my real case CatchAll placeholder doesn't fit.  Will try with empty
placeholders.

пн, 30 сент. 2024 г. в 15:22, Raman Maksimchuk ***@***.***>:

**Comment by raman-m** [comment]
I'm R**a**man, not R**o**man!
