### ISSUE TITLE
trimming problem IOcelotBuilder.AddDelegatingHandler<T>

### ISSUE THREAD

**Issue by LeonSchourek** [ThreeMammals/Ocelot#2158]
## Expected Behavior / New Feature
programm runs without error

## Actual Behavior / Motivation for New Feature
cant find delegating handler

on IOcelotBuilder.AddDelegatingHandler<T>: [DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicConstructors)] is missing

## Steps to Reproduce the Problem
1
IOcelotBuilder obuilder = builder.Services.AddOcelot();
obuilder.AddDelegatingHandler<Something>();

2
Compile with full trimming enabled

## Specifications

  - Version: 23.2.2
  - Platform: Net 8.0 (Linux)
  - Subsystem:

**Comment by raman-m** [comment]
Hello, Leon!
I'm struggling to understand the problem. Are you suggesting that the issue might be with this code?
https://github.com/ThreeMammals/Ocelot/blob/58d87c9273c1252a9da64a8900b080c96511d480/src/Ocelot/DependencyInjection/OcelotBuilder.cs#L274-L292

Please, provide `ocelot.json`, full content.
Please provide the complete C# startup and configuration code.
Additionally, the full custom delegating handler in C# is required for review.

**Comment by raman-m** [comment]
Please revise "Steps to Reproduce the Problem" as they seem too abstract. Detailed, concrete steps for reproduction are necessary.

**Comment by raman-m** [comment]
The author is not responsive
