### ISSUE TITLE
Issue with IP Blocking and Allowing in global configuration

### ISSUE THREAD

**Issue by CavidH** [ThreeMammals/Ocelot#2165]
I configured IP blocking and allowing in Ocelot using SecurityOptions, but it's not working.

 
```
{
  "GlobalConfiguration": {
    "BaseUrl": "http://localhost:5000",
    "SecurityOptions": {
      "IPBlockedList": ["192.168.0.23"]
    }
  }
}


```

The IP blocking configuration is not working as expected.

**Comment by raman-m** [comment]
Hello, Cavid!
It appears we don't have support for global settings.
You should define the options for each individual route.

**Comment by raman-m** [comment]
Hello @Fabman08,
The absence of global settings support is a significant issue. Here's the current usage of [SecurityOptionsCreator](https://github.com/ThreeMammals/Ocelot/blob/develop/src/Ocelot/Configuration/Creator/SecurityOptionsCreator.cs):

https://github.com/ThreeMammals/Ocelot/blob/6088515173b70abd52798e544e5ded409680dbdb/src/Ocelot/Configuration/Creator/RoutesCreator.cs#L111

Consequently, the method should accept two arguments, including global settings:
https://github.com/ThreeMammals/Ocelot/blob/6088515173b70abd52798e544e5ded409680dbdb/src/Ocelot/Configuration/Creator/SecurityOptionsCreator.cs#L8
Would you be able to allocate some time to address this?

**Comment by Fabman08** [comment]
Hi @raman-m!
Sure, I'll be able to fix the issue this or next week. ☺️ 

@CavidH thank you for reporting this issue! 👍

**Comment by CavidH** [comment]
Thank you very much for your help. We will eagerly await the new version.

**Comment by CavidH** [comment]
> Hello, Cavid! It seems we lack support for global settings. The potential solutions could be:
> 
> 1. Solely using `ocelot.json`. Define the options for each route individually.
> 2. Utilizing C# coding. Replace the `ISecurityOptionsCreator` service in the DI container by redeveloping the `SecurityOptionsCreator` class to consider only the global settings.
>    https://github.com/ThreeMammals/Ocelot/blob/6088515173b70abd52798e544e5ded409680dbdb/src/Ocelot/DependencyInjection/OcelotBuilder.cs#L141
> 
> Which solution would be more convenient for you?

I had thought of the first option, but since I have too many services, it will be difficult to control this

**Comment by Fabman08** [comment]
@raman-m just a little question about Global Settings behaviours.

I've found three ways to fix the issue:
1. Every properties in Route FileSecurityOptions overrides their Global Settings values
eg.
- Global:
Allowed: B,C
Blocked: E
ExcludeAllowedFromBlocked: true
- Route:
Allowed: **A,B,C**
Blocked: **D,E,F**
ExcludeAllowedFromBlocked: **false**
- Final:
Allowed: **A,B,C**
Blocked: **D,E,F**
ExcludeAllowedFromBlocked: **false**

2. Only the existing properties in Route FileSecurityOptions overrides their Global Settings values
eg.
- Global:
Allowed: B,C
Blocked: **E**
ExcludeAllowedFromBlocked: **true**
- Route:
Allowed: **A,B,C**
Blocked: *null*
ExcludeAllowedFromBlocked: *null*
- Final:
Allowed: ***A,B,C***
Blocked: **E**
ExcludeAllowedFromBlocked: **true**

3. The Route FileSecurityOptions values will be merged to Global Settings values
eg.
- Global:
Allowed: **A,B,C**
Blocked: **D,E**
ExcludeAllowedFromBlocked: true
- Route:
Allowed: **F,G,H**
Blocked: **I,K**
ExcludeAllowedFromBlocked: **false**
- Final:
Allowed: **A,B,C,F,G,H**
Blocked: **D,E,I,K**
ExcludeAllowedFromBlocked: **false**

Which one is the best?

**Comment by raman-m** [comment]
@Fabman08  Your research is too complicated!
> Which one is the best?

It is best to prioritize the route-specific `FileSecurityOptions` object over the global settings. Therefore, if route settings are defined, all global settings should be disregarded. In practice, if the route object is null, then the global settings should be utilized.

> Every properties in Route FileSecurityOptions overrides their Global Settings values

Yes. If route opts are defined, ignore all global ones! We will pay user's attention to this in docs. No merging at all. This will be the simplest solution and single right one, because merging props will be wrong because they will run into conflict in the algorithm. So merging is the source of bugs.
