### ISSUE TITLE
upgrade version 18.0.0 to 23.3.3+ Consul module was error

### ISSUE THREAD

**Issue by BarryJame** [ThreeMammals/Ocelot#2167]
## Expected Behavior / New Feature
Consul service get Ip address was normal from version 18.0.0 , while turn IP into  0.0.0.1 since upgrade to latest version 23.3.3+

## Actual Behavior / Motivation for New Feature

![image](https://github.com/user-attachments/assets/a062b845-8aa8-4299-bac2-adb6e2b2e402)

## Steps to Reproduce the Problem

  1. context.Services.AddOcelot(context.Services.GetConfiguration()).AddConsul();
  1. app.UseAuthentication() // 先鉴权,启用身份认证
     .UseRouting()
     .UseAuthorization() // 然后授权.
     .UseConfiguredEndpoints()
     .UseOcelot().Wait();
  1.

## Specifications

  - Version:
  - Platform:
  - Subsystem:

**Comment by raman-m** [comment]
Additionally, it may be beneficial to review this: [Consul Service Builder](https://ocelot.readthedocs.io/en/latest/features/servicediscovery.html#consul-service-builder)❗

**Comment by raman-m** [comment]
It's already **fixed by https://github.com/ThreeMammals/Ocelot/pull/2151**
