### ISSUE TITLE
UpstreamHeaderTemplate with duplicated UpstreamPathTemplate

### ISSUE THREAD

**Issue by felipepiresdejesus** [ThreeMammals/Ocelot#2176]
## Expected Behavior / New Feature

Redirect to downstream endpoint based on header, ignoring duplication of upstream path template

## Actual Behavior / Motivation for New Feature

Ocelot does not allow duplicated upstream path with different header template

## Steps to Reproduce the Problem
Use the following configuration:
```json
{
  "Routes": [
    {
      "DownstreamPathTemplate": "/",
      "DownstreamScheme": "https",
      "DownstreamHostAndPorts": [
        {"Host": "www.google.com", "Port": 443}
      ],
      "UpstreamPathTemplate": "/{everything}",
      "UpstreamHeaderTemplate": {
        "app": "google"
      },
      "UpstreamHttpMethod": ["GET", "POST"]
    },
    {
      "UpstreamPathTemplate": "/{everything}",
      "UpstreamHeaderTemplate": {
        "app": "postman"
      },
      "UpstreamHttpMethod": ["GET", "POST"],
      "DownstreamPathTemplate": "/",
      "DownstreamScheme": "https",
      "DownstreamHostAndPorts": [
        {"Host": "www.postman.com", "Port": 443}
      ]
    }
  ],
  "GlobalConfiguration": {
    "BaseUrl": "http://localhost:5194/"
  }
}
```
## Specifications

  - Version: 23.3.4
  - Platform: .NET 8
  - Subsystem: Mac OS

## Feature
- [Routing | Upstream Headers](https://ocelot.readthedocs.io/en/latest/features/routing.html#upstream-headers)

**Comment by raman-m** [comment]
>### Actual Behavior / Motivation for New Feature
>Ocelot does not allow duplicated upstream path with different header template

Are you certain? I was under the impression that the matching process should disregard upstream paths entirely, focusing solely on `UpstreamHeaderTemplates`.

>### Expected Behavior / New Feature
>Redirect to downstream endpoint based on header, ignoring duplication of upstream path template

It appears that the upstream path might be completely ignored when `UpstreamHeaderTemplates` is defined in the route. We should verify this with the validators.
Additionally, could you provide a complete solution rather than just a single Ocelot JSON configuration?

**Comment by raman-m** [comment]
@jlukawska Hello, Jolanta! Could you please assist this user?

**Comment by jlukawska** [comment]
@felipepiresdejesus, there is a typo in the configuration. This is the cause of the problem. `UpstreamHeaderTemplate` should be `UpstreamHeaderTemplates` with "s" at the end.

Please try to correct your _ocelot.json_ and let us know if it works as you expect.

**Comment by felipepiresdejesus** [comment]
Oh, my bad!
Thank you @jlukawska

**Comment by raman-m** [comment]
@felipepiresdejesus Don't you read docs? &rarr; [Upstream Headers](https://ocelot.readthedocs.io/en/latest/features/routing.html#upstream-headers)  &rarr; [UpstreamHeaderTemplates](https://ocelot.readthedocs.io/en/latest/features/routing.html#upstream-headers:~:text=UpstreamHeaderTemplates) ❗
