### ISSUE TITLE
consul config option resolving address

### ISSUE THREAD

**Issue by LeonSchourek** [ThreeMammals/Ocelot#2184]
## Expected Behavior / New Feature
option to define if address should be read from node name or from address

## Actual Behavior / Motivation for New Feature
reads from node name

i updated ocelot and all requests dont worked after debugging and searching i found the problem 
 #2119

## Steps to Reproduce the Problem
update ocelot from 22.* to 23.3.4

## Specifications

  - Version: 23.3.4
  - Platform:
  - Subsystem:

**Comment by raman-m** [comment]
Is this question or real bug?

**Comment by raman-m** [comment]
>i updated ocelot and all requests dont worked **after debugging** and searching i found the problem #2119

If you are able to debug .NET app, why don't you read our docs? &rarr; [Consul Service Builder](https://ocelot.readthedocs.io/en/latest/features/servicediscovery.html#consul-service-builder)

**Comment by LeonSchourek** [comment]
oh i always read the old config....
i googled the docs and the results linked me to a old version
