### ISSUE TITLE
Ocelot can't match placeholders between slashes

### ISSUE THREAD

**Issue by ggnaegi** [ThreeMammals/Ocelot#2199]
## Expected Behavior / New Feature

Ocelot should be capable of matching paths that contain placeholders embedded between slashes, such as: 
`/api/invoices_{url0}/{url1}-{url2}_abcd/{url3}?urlId={url4}.`

## Actual Behavior / Motivation for New Feature

Currently, Ocelot cannot match placeholders embedded between slashes. For example: `/api/test/{url}-2` -> request: `/api/test/a-2` -> the result will incorrectly return `{url} = a-2`.

## Steps to Reproduce the Problem

  1. Try any template with placeholders embedded between slashes

**Comment by raman-m** [comment]
### Accepted due open PR #2200
