### ISSUE TITLE
[Feature Request] Optional dictionary style configuration for array values

### ISSUE THREAD

**Issue by Ghostbird** [ThreeMammals/Ocelot#2242]
## New Feature

Currently loading routes from `appsettings.json` configuration in Ocelot is done from the merged app configuration files. It would be very nice to allow the `Routes` and maybe other critical configuration to be optionally specified in object/dictionary notation instead of array notation to make overrides unambiguous.

We've been bitten by this kind of problem before with Serilog.Settings.Configuration, which has the same weakness. However they have implemented the dictionary configuration mechanism which means our overrides now are nice and stable.

> When overriding settings with [environment variables](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?view=aspnetcore-3.1#environment-variables) it becomes less convenient and fragile, so you can specify custom names:[^1]

## Motivation for New Feature

When overriding specific options using environment specific files, or environment variables, this becomes inconvenient, fragile, and might lead to accidental credential leaks.

### A simple configuration

A common pattern is shown below. Here some common options for the route are defined at the global level, and specific values are filled in at the environment level[^2]:

##### appsettings.json
```
{
  "Routes": [
    {
      "UpstreamPathTemplate": "foo/{everything}",
      "UpstreamHeaderTransform": {
        "Authentication": "ApiKey FILL_IN_KEY",
      }
    },
    {
      "UpstreamPathTemplate": "bar/{everything}"
    }
  ]
}
```

##### appsettings.staging.json
```
{
  "Routes": [
    {
      "UpstreamHeaderTransform": {
        "Authentication": "ApiKey O28ceMSXnPs0j0eQ/IbUVQ==",
      }
    }
  ]
}
```

Note: The _staging_ environment could have achieved the same by setting the environment variable `Routes__0__UpstreamHeaderTransform__Authentication` to `ApiKey O28ceMSXnPs0j0eQ/IbUVQ==` [^3]

### A problematic configuration

Consider that our global configuration looked like this instead:

##### appsettings.json

```
{
  "Routes": [
    {
      "UpstreamPathTemplate": "bar/{everything}"
    },
    {
      "UpstreamPathTemplate": "foo/{everything}",
      "UpstreamHeaderTransform": {
        "Authentication": "ApiKey FILL_IN_KEY",
      }
    }
  ]
}
```

Now if we try to override the authentication header transform, it will potentially leak our secret API key to a completely different upstream service.

##### appsettings.staging.json
```
{
  "Routes": [
    {
      "UpstreamHeaderTransform": {
        "Authentication": "ApiKey O28ceMSXnPs0j0eQ/IbUVQ==",
      }
    }
  ]
}
```

We _must_ specify an empty override of the first route to avoid this:

##### appsettings.staging.json
```
{
  "Routes": [
    { },
    {
      "UpstreamHeaderTransform": {
        "Authentication": "ApiKey O28ceMSXnPs0j0eQ/IbUVQ==",
      }
    }
  ]
}
```

### A configuration using the proposed solution

It would be great to incorporate the dictionary loading into Ocelot too. Then our configuration could look like this:

##### appsettings.json

```
{
  "Routes": {
    "bar": {
      "UpstreamPathTemplate": "bar/{everything}"
    },
    "foo": {
      "UpstreamPathTemplate": "foo/{everything}",
      "UpstreamHeaderTransform": {
        "Authentication": "ApiKey FILL_IN_KEY",
      }
    }
  }
}
```

##### appsettings.staging.json

```
{
  "Routes": {
    "foo": {
      "UpstreamHeaderTransform": {
        "Authentication": "ApiKey O28ceMSXnPs0j0eQ/IbUVQ==",
      }
    }
  }
}
```

Note: The Routes keys `foo` and `bar` are never seen beyond the configuration loader. They're only used at the IConfiguration loader level to disambiguate.

[^1]: https://github.com/serilog/serilog-settings-configuration#writeto-enrich-auditto-destructure-sections
[^2]: https://learn.microsoft.com/en-gb/aspnet/core/fundamentals/configuration#application-configuration-providers
[^3]: https://learn.microsoft.com/en-gb/aspnet/core/fundamentals/configuration#naming-of-environment-variables

**Comment by raman-m** [comment]
Who are you, Mister?
What's your full name?
What are the links to your social networks?

**Comment by Ghostbird** [comment]
> Who are you, Mister? What's your full name? What are the links to your social networks?

We've discussed this answer internally in our company and have three outcomes:

- You really think this is an appropriate reply
- You're drunk / high and on Github
- Your account has been taken over by a bot

The consensus is that it's safest to treat this as a bot answer indicating that your account has been compromised. We have frozen our use of Ocelot and are looking for an alternative API Gateway.

However, since we cannot be entirely sure, please remove your previous comment, and post the answer to the picture below:

![image](https://github.com/user-attachments/assets/b816fc67-3c57-4a28-a76b-f17f364e9cb0)

If you do, we'll delete this message and pretend none of this ever happened.

**Comment by ggnaegi** [comment]
@Ghostbird 🤣

**Comment by raman-m** [comment]
@ggnaegi  What's funny?

**Comment by raman-m** [comment]
@Ghostbird You are banned!

**Comment by raman-m** [comment]
> #### A configuration using the proposed solution
> It would be great to incorporate the dictionary loading into Ocelot too. Then our configuration could look like this:
> 
> ##### appsettings.json
> ```json
> {
>   "Routes": {
>     "bar": {
>       "UpstreamPathTemplate": "bar/{everything}"
>     },
>     "foo": {
>       "UpstreamPathTemplate": "foo/{everything}",
>       "UpstreamHeaderTransform": {
>         "Authentication": "ApiKey FILL_IN_KEY",
>       }
>     }
>   }
> }
> ```
> 

Use Metadata in configurations, my dear AI friend.
- [Route Metadata](https://ocelot.readthedocs.io/en/latest/features/configuration.html#route-metadata)
- [Metadata](https://ocelot.readthedocs.io/en/latest/features/metadata.html)

We are not going to implement your proposal!
Good luck in custom Ocelot development and using AI generation tools!
