### ISSUE TITLE
implements the Circuit Breaker Pattern (using Polly from thepollyproject.org)

### ISSUE THREAD

**Issue by geffzhang** [ThreeMammals/Ocelot#23]
HttpClientHttpRequester need implements the Circuit Breaker Pattern，I using Polly from thepollyproject.org https://github.com/App-vNext/Polly/wiki/Transient-fault-handling%3A-why-Retry-and-Circuit-Breaker%3F

**Comment by TomPallister** [comment]
@geffzhang I know Polly so this should be quite simple. The hard part will be configuring it in the Json. Maybe have a go implementing this with a pull request.

**Comment by geffzhang** [comment]
I go to implement Polly configuration which should be on the ReRoute

**Comment by geffzhang** [comment]
#27 @TomPallister I have refactor polly circuit breaker pattern， config it in json： 
"ExceptionsAllowedBeforeBreaking","DurationOfBreak","TimeoutValue"

**Comment by TomPallister** [comment]
@geffzhang I have reviewed the code looks good, when I merge the changes I will add information to the README to tell people how to use the feature.

**Comment by TomPallister** [comment]
closing this as pull request merged
