### ISSUE TITLE
Known Users

### ISSUE THREAD

**Issue by geffzhang** [ThreeMammals/Ocelot#236]
With the number of Ocelot star Breakthrough 1000, more users are interested in Ocelot。Like https://identityserver.io/#customers For open Source User reference。Add a doc pages show use case

**Comment by geffzhang** [comment]
This is case https://customers.microsoft.com/en-us/story/tencent-telecommunications-dotnetcore

**Comment by TomPallister** [comment]
@geffzhang thank you! A good idea. 

I am going to make a website for Ocelot but I need to decide on the organisation name! I can't make up my mind. I own the domain threemammals.co.uk but could also get something ocelot related.

**Comment by TomPallister** [comment]
@geffzhang I have done this! Thank you very much for the suggestion.

New website is http://threemammals.com/

It is OK...not very fancy but I do not have much time :)

**Comment by geffzhang** [comment]
It's great.
