### ISSUE TITLE
Support ServiceFabric

### ISSUE THREAD

**Issue by siliond** [ThreeMammals/Ocelot#238]
What are the steps to configure (Program.cs, Startup.cs, etc.) Ocelot in a Service Fabric stateless service for an on premise deployment?

**Comment by TomPallister** [comment]
@siliond thanks for your interest in the project!

Ocelot is just a NuGet package so all you have to do is pull it into an asp.net project and wire it up following the instructions [here](http://ocelot.readthedocs.io/en/latest/introduction/gettingstarted.html). I'm not sure if stateless services can write to local disk which is something Ocelot will do sometimes depending on your configuration.

Other than this it should be just like deploying another other asp.net application into service fabric. However this is not something I have done myself.

**Comment by siliond** [comment]
Getting a weird  _reRoute /EquipmentInterfaces has duplicate_ error:

`System.AggregateException
  HResult=0x80131500
  Message=One or more errors occurred. (Unable to start Ocelot, errors are: reRoute /EquipmentInterfaces has duplicate,reRoute /EquipmentInterfaces has duplicate)
  Source=System.Private.CoreLib
  StackTrace:
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at API.Core.Gateway.Startup.Configure(IApplicationBuilder app, IHostingEnvironment env) in C:\work\StarLims\v11\source\AITP\SEI\API.Core.Gateway\Startup.cs:line 41

Inner Exception 1:
Exception: Unable to start Ocelot, errors are: reRoute /EquipmentInterfaces has duplicate,reRoute /EquipmentInterfaces has duplicate`

This is my configuration.json:
`{
  "ReRoutes": [
    {
      "DownstreamPathTemplate": "/api/values",
      "DownstreamScheme": "http",
      "DownstreamHostAndPorts": [
        {
          "Host": "localhost",
          "Port": 8940
        }
      ],
      "UpstreamPathTemplate": "/EquipmentInterfaces",
      "UpstreamHttpMethod": [ "Get" ]
    }
  ],
  "GlobalConfiguration": {
    "RequestIdKey": "OcRequestId",
    "AdministrationPath": "/administration"
  }
} `

Please advise.

**Comment by TomPallister** [comment]
@siliond Ill have a look asap!

**Comment by TomPallister** [comment]
@siliond 

What version of Ocelot are you using? I notice that you have the administration path in your configuration.json. This is no longer supported. Maybe I have not updated the docs will check.

I have put a PR with your config and a passing test [here](https://github.com/TomPallister/Ocelot/pull/242) 

Maybe upgrade to latest Ocelot (might be an old bug) Install-Package Ocelot -Version 3.1.5 and try this configuration.json

```json
{
    "ReRoutes": [
        {
            "DownstreamPathTemplate": "/api/values",
            "UpstreamPathTemplate": "/EquipmentInterfaces",
            "UpstreamHttpMethod": [
                "Get"
            ],
            "DownstreamHostAndPorts": [
                {
                    "Host": "localhost",
                    "Port": 8940
                }
            ]        
        }
    ],
    "GlobalConfiguration": {
        "RequestIdKey": "OcRequestId"
    }
}
```

Hope this helps!

**Comment by siliond** [comment]
I have Ocelot 3.1.5.

Tried with the configuration.json provided, no luck - error below. Maybe there are extra steps required for Service Fabric that I'm not aware of.

Error:
```
System.AggregateException
  HResult=0x80131500
  Message=One or more errors occurred. (Unable to start Ocelot, errors are: reRoute /EquipmentInterfaces has duplicate,reRoute /EquipmentInterfaces has duplicate)
  Source=System.Private.CoreLib
  StackTrace:
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at API.Core.Gateway.Startup.Configure(IApplicationBuilder app, IHostingEnvironment env) in C:\work\StarLims\v11\source\AITP\SEI\API.Core.Gateway\Startup.cs:line 41

Inner Exception 1:
Exception: Unable to start Ocelot, errors are: reRoute /EquipmentInterfaces has duplicate,reRoute /EquipmentInterfaces has duplicate
```

Thank you very much.

**Comment by TomPallister** [comment]
@siliond could you paste your program.cs / startup.cs

**Comment by TomPallister** [comment]
@siliond I have had a better look into this. I didnt have any problems with Ocelot starting and using the configuration pasted above. However Ocelot will not currently work in service fabric as it needs to look up the names of services from the naming service. 

Good information [here ](https://dzimchuk.net/implementing-a-rest-client-for-internal-communication-in-service-fabric/)

I will keep this issue open and rename it to support service fabric.

Can I ask what your use case is? I assume expose ocelot over http and that communicates to various services within service fabric cluster?

**Comment by TomPallister** [comment]
Implementation plan

Think we could implement a service discovery provider like we have with consul that uses the service fabric naming service to look up the service address from canonical name. Not sure if the configuration.json model would suppor this at the moment. 

We can do something like this to lookup the service from naming service

```csharp
  string proxyUrl = $"http://localhost:{this.configSettings.ReverseProxyPort}/{serviceUri}?cmd=instance";
  HttpResponseMessage response = await this.httpClient.GetAsync(proxyUrl);
```

but I dont know if this works with partitioned services so we might also need to support

```csharp
    ServicePartitionResolver resolver = ServicePartitionResolver.GetDefault();
     ResolvedServicePartition partition = 
        await resolver.ResolveAsync("fabric:/BookFast/FacilityService", new ServicePartitionKey(), 
    cancellationToken);
    
    ResolvedServiceEndpoint endpoint = partition.GetEndpoint();
```

Anyway these are initial thoughts...I have downstream aggregation to finish before I would start looking at this so if anyone fancies giving it a go that would be awesome!

**Comment by TomPallister** [comment]
https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-reverseproxy

**Comment by TomPallister** [comment]
might be able to use dns service to make this easier?

https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-dnsservice

**Comment by TomPallister** [comment]
After looking at naming service more Ocelot will work fine if all your downstream services have dns names and the dns service is on.

**Comment by siliond** [comment]
@TomPallister 
Correct, the use case is implement an API gateway for Service Fabric services.

Digesting all the info.
A Microsoft consultant on Service Fabric will pay me a visit next Thursday and this will be one of the topics, will update the thread with findings.

**Comment by TomPallister** [comment]
@siliond I've just released version 3.1.8 to NuGet that adds support for Service Fabric. Please see sample project [here](https://github.com/ThreeMammals/Ocelot/tree/develop/samples/OcelotServiceFabric) maybe use this as a basis if you want to use Ocelot in Service Fabric. Also docs are [here](http://ocelot.readthedocs.io/en/latest/features/servicefabric.html). 

This only supports instance / stateless services at the moment so it won't work with actors / statefull because I am not sure about the best way to deal with partition keys etc. 

Let me know if this doesn't solve you issue!

**Comment by TomPallister** [comment]
actually the client can jsut send them in the query string..there is no way ocelot can now which partition key to choose...i can make those changes..

**Comment by petargg** [comment]
Is it possible to provide example for configuration.json for stateful service
