### ISSUE TITLE
Static code analysis

### ISSUE THREAD

**Issue by binarymash** [ThreeMammals/Ocelot#253]
Now we're getting a larger number of contributors it might be useful to enforce a few rules around code style. 

I use https://github.com/DotNetAnalyzers/StyleCopAnalyzers on most of my projects, which uses Roslyn analyzers to flag up violations at build time and, if you're using Visual Studio, when you're editing the code.

If we do implement this I want to avoid making it a painful experience for contributors... many of the rules are contentious, so I'd suggest that we start off with most rules turned off and then add in whatever we think will be useful to improve the code quality. 

Roslyn analyzers are not currently supported in vscode (though it looks like there is progress -
 see https://github.com/OmniSharp/omnisharp-vscode/issues/43) so anyone using vscode would only see the failures or warnings when building on the command line, which adds a lot of friction to the dev experience.

I've pushed up a work in progress which has most of the rules turned off - see https://github.com/binarymash/ocelot/tree/feature/AddStyleCopAnalyzers - and in the meantime, we can argue about whether `using` statements should be in alphabetical order ;)

**Comment by TomPallister** [comment]
@binarymash looks good to me. Maybe everything should be a warning instead of none then we can get to fixing them. Once we are at 0 warnings then we can turn them to errors? Not sure what best approach is.

Submit a PR and let's get cracking! I'd love to improve the quality of the code.

**Comment by binarymash** [comment]
Good stuff, I'll try to find some time this weekend. 

I think it'll be cleaner to disable all the violations, then for a particular rule turn it on, fix and commit, and then move on to the next rule. Turning them all to warnings will just generate a *lot* of noise (try building https://github.com/binarymash/Ocelot/commit/df86052a31235d4dd740020dc8ddf574b3b1b81a ...)

I'm very much of the opinion that you shouldn't get any build warnings if you can help it... we've all worked on code that generates 500 warnings, and you just start to ignore them, and the code deteriorates. If there's a good reason for violating a rule, then in those cases you should wrap the code in a `#pragma warning disable` - `#pragma warning restore`

**Comment by TomPallister** [comment]
@binarymash yep makes sense! Agree with everything.
