### ISSUE TITLE
Manage services through workflow ui

### ISSUE THREAD

**Issue by jefferson** [ThreeMammals/Ocelot#257]
It's possible to create a UI to map services e manage them through workflow?
Example, using this libray: http://sebastien.drouyer.com/jquery.flowchart-demo/#advanced

It's interesting, or viable functionality?

**Comment by TomPallister** [comment]
@jefferson thanks for your interest in the project! Yes this would be possible either by editing configuration.json or using Ocelots admin API. Docs for that are here http://ocelot.readthedocs.io/en/latest/features/administration.html

A few people have previously built configuration generators of various forms.

**Comment by TomPallister** [comment]
Here is a previous issue that is similar https://github.com/ThreeMammals/Ocelot/issues/116 the comment by ravinsp on 23 Nov 2017 might be useful.

Here is the editor https://github.com/dbarkwell/Ocelot.ConfigEditor

**Comment by jefferson** [comment]
Hi, 

I'm starting a small project to build this feature with a small initial scope: to produce static routes based on ReRoutes in configuration.json

Here is the project: https://github.com/jefferson/route-graph-visualization
