### ISSUE TITLE
CI - Reduce the number of build warnings

### ISSUE THREAD

**Issue by binarymash** [ThreeMammals/Ocelot#260]
## New Feature

Reduce the number of build warnings - work ongoing from #253

## Motivation for New Feature

We want to minimise the number of build warnings, enforce a common coding style and identify any common gotchas in the code

## Steps to Reproduce the Problem

Do a build ;)

## Specifications

n/a

**Comment by TomPallister** [comment]
@binarymash much appreciated, just had a quick look! Only a few things that i commented on and they are my mistakes! Would be awesome if you have time to fix it :p you thought you got away from tidying up my shit code!

**Comment by TomPallister** [comment]
@binarymash thanks for merging chief. Was just in the water poet near Liverpool Street. Was a Huddersfield exciles sticker in the bogs. Exciting.

**Comment by simonjefford** [comment]
Warnings now 0...

Used a pragma to squash the warning about `AddBaseUrl` being obsolete as it was test code (and setup code at that). Also, I switched off package analysis to shut up the warning about the summary text (see https://github.com/NuGet/Home/issues/4587 for more).

**Comment by TomPallister** [comment]
@simonjefford awesome!! Thanks 👍 

AddBaseUrl is some crap that wasn't very well thought out :( I need to get rid of it but focusing on other features at the moment. We have an issue for it!

**Comment by TomPallister** [comment]
@binarymash not sure if you want to re-open this but will leave closed for now as @simonjefford (a friend of mine from real life..yes I have two of them!) has helped out here!
