### ISSUE TITLE
Content-Encoding headers are not preserved

### ISSUE THREAD

**Issue by mjrousos** [ThreeMammals/Ocelot#263]
## Actual Behavior
Downstream requests from Ocelot do not contain Content-Encoding headers even if upstream requests do. This causes rerouted gzip-encoded requests to fail.

## Analysis
Headers are mapped in [`RequestMapper.MapHeaders`](https://github.com/ThreeMammals/Ocelot/blob/a53338312bcc1ca99a6ee901e35ac24b07079d03/src/Ocelot/Request/Mapper/RequestMapper.cs#L72), but they are all added to the downstream request by calling `requestMessage.Headers.TryAddWithoutValidation`. This doesn't work for Content-Encoding,
 though, because .NET understands it as a [content header](https://github.com/dotnet/corefx/blob/3e72ee5971db5d0bd46606fa672969adde29e307/src/System.Net.Http/src/System/Net/Http/Headers/KnownHeaders.cs) (so it should be added via `requestMessage.Content.Headers.TryAddWithoutValidation`).

`RequestMapper` should be updated to properly forward content headers like Content-Encoding and Content-Language. Content-Type is already handled in [`RequestMapper.MapContent`](https://github.com/ThreeMammals/Ocelot/blob/a53338312bcc1ca99a6ee901e35ac24b07079d03/src/Ocelot/Request/Mapper/RequestMapper.cs#L50). Perhaps that method could be updated to check for other content headers.

## Steps to Reproduce the Problem

  1. Attempt to re-route a request with compressed contents (and a gzip Content-Encoding header)
  1. Notice that the downstream request is missing the header and, consequently, the request fails.

## Specifications

  - Version: 3.1.7
  - Platform: Windows 10 x64

**Comment by TomPallister** [comment]
@mjrousos yep makes sense will look at this ASAP!

**Comment by TomPallister** [comment]
@mjrousos I have created a PR to fix this issue, please feel free to take a look. I've added unit and acceptance tests around the functionality. Hopefully this works properly going forward.

**Comment by TomPallister** [comment]
open until release

**Comment by TomPallister** [comment]
Ive just pushed version 4.0.0 that should fix this.
