### ISSUE TITLE
Feature Request: Customize Polly policies

### ISSUE THREAD

**Issue by mjrousos** [ThreeMammals/Ocelot#264]
## Feature Request

This isn't urgent, but it would be great if we could somehow customize Polly policies used for some reroutes. As examples, I'd like to be able to add a retry policy or change the callback used when the circuit breaker opens.

It would be easy to add my own policies in a `DelgateHandler` but then they would apply to all reroutes (which is undesirable since one bad API would open the circuit breaker for all).

Perhaps there's a way we could inject Policy[] via DI to override the defaults?

**Comment by TomPallister** [comment]
@mjrousos Yeh this is a useful feature. I will have a look ASAP.

**Comment by TomPallister** [comment]
Basically we want ReRoute specific delegating handlers, do you agree?

So we need some way of mapping ReRoutes to handlers, the easiest way to do this would be to have an array of delegating handlers on the ReRoute in configuration.json. 

Maybe on the ReRoute we have

```json
"Handlers": [
    "Tracer",
    "PollyOne"
]
```

then in Ocelot

```csharp
services.AddOcelot()
    .AddDelegatingHandler<PollyOne>()
    .AddDelegatingHandler<Tracer>()
    .AddDelegatingHandler<Foo>();
```

When the http client is built for the ReRoute we pick out the delegating handlers that matched the string in json.

Seems simple enough!

**Comment by mjrousos** [comment]
Yea, that would do the trick. In this model, I could put whatever custom Polly policies I want in a delegating handler and then use it with particular routes. A couple concerns, though -

* Some delegating handlers would still be useful to apply globally, so we may need a way to specify in AddDelegatingHandler if the handler should always apply or if it should only reply when requested.
* In the Polly case that I'm thinking of specifically, I may want to create one delegating handler with a circuit breaker, for example, and request it on multiple reroutes via `"Handlers": []` but I won't want that circuit breaker opening for one of the reroutes to affect the other. So, it will be good if each reroute that uses a delegating handler could get its own instance (so that they can have separate instances of policies  or other local state).

**Comment by TomPallister** [comment]
Cool sounds like a plan...I’ll make sure each reroute gets its own!

**Comment by TomPallister** [comment]
@mjrousos OK ive just pushed version 5.0.0 that has changes that should let you do all of the things we talked about (hopefully). Let me know if this isn't the case.

Updated docs [here](http://ocelot.readthedocs.io/en/latest/features/delegatinghandlers.html) hopefully they make sense.

**Comment by mjrousos** [comment]
Awesome; thanks! I'll check it out and let you know.

**Comment by Cristiano7Zhang** [comment]
Is it compatible with core 2.x？

**Comment by david-sackstein** [comment]
Is it possible to get the context of the request in the delegating handler?
I need this in order to enrich the request from information that I extract from the HttpContext.User

**Comment by Cristiano7Zhang** [comment]
> 
You can get the httpcontextAccessor via DI.

**Comment by raman-m** [comment]
> @david-sackstein commented [on Nov 22, 2021](#issuecomment-975196348)

Is not it too late? 😃 
Use this coding recipe to have `HttpContext` in your custom [delegating handler](https://ocelot.readthedocs.io/en/latest/features/delegatinghandlers.html):
- [Issue 1252, AgentShark commented on June 26, 2023](1252#issuecomment-1606496115)
