### ISSUE TITLE
ResponderMiddleware Error: requestId: no request id

### ISSUE THREAD

**Issue by NicoKno** [ThreeMammals/Ocelot#271]
I'm getting an error message when calling my services. Postman delivers a 404 status after that. Calling my service directly via postman is successful.

`[41m[30mfail[39m[22m[49m: Ocelot.Responder.Middleware.ResponderMiddleware[0]
requestId: no request id, previousRequestId: no previous request id, message: 1 pipeline errors found in ResponderMiddleware. Setting error response status code
Ocelot.Responder.Middleware.ResponderMiddleware:Error: requestId: no request id, previousRequestId: no previous request id, message: 1 pipeline errors found in ResponderMiddleware. Setting error response status code
[41m[30mfail[39m[22m[49m: Ocelot.Responder.Middleware.ResponderMiddleware[0]`

**Comment by TomPallister** [comment]
@NicoKno can you paste your configuration.json here?

Also would it be possible to paste the full log from beginning to end?

**Comment by NicoKno** [comment]
This is the configuration I use. I obfuscated the hostname which is a service name of a docker-compose-file.

`
{
  "ReRoutes": [
    {
      "DownstreamPathTemplate": "/api/v1/{everything}",
      "DownstreamScheme": "https",
      "DownstreamHostAndPorts": [
        {
          "Host": "<docker-service-name>",
          "Port": 5000
        }
      ],
      "UpstreamPathTemplate": "/api/v1/{everything}",
      "UpstreamHttpMethod": [ "Put", "Get", "Post" ]
    },
    {
      "DownstreamPathTemplate": "/connect/token",
      "DownstreamScheme": "https",
      "DownstreamHostAndPorts": [
        {
          "Host": "<other-docker-service-name>",
          "Port": 5001
        }
      ],
      "UpstreamPathTemplate": "/connect/token",
      "UpstreamHttpMetahod": [ "Post" ]
    }
  ],
  "GlobalConfiguration": {
    "RequestIdKey": "OcRequestId"
  }
}
`

And this is the output generated when I call the service:

`Loaded '/usr/share/dotnet/shared/Microsoft.NETCore.App/2.0.5/System.Numerics.Vectors.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded '/usr/share/dotnet/store/x64/netcoreapp2.0/system.runtime.compilerservices.unsafe/4.4.0/lib/netstandard2.0/System.Runtime.CompilerServices.Unsafe.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Microsoft.AspNetCore.Hosting.Internal.WebHost:Information: Request starting HTTP/1.1 PUT https://localhost:8080/api/v1/modules/Test application/json 52
[40m[32minfo[39m[22m[49m: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
Request starting HTTP/1.1 PUT https://localhost:8080/api/v1/modules/Test application/json 52
[40m[32minfo[39m[22m[49m: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
=> RequestId:0HLC9FDIE2EJR:00000001 RequestPath:/api/v1/modules/Test => RequestId:0HLC9FDIE2EJR:00000001 RequestPath:/api/v1/modules/Test
Request starting HTTP/1.1 PUT https://localhost:8080/api/v1/modules/Test application/json 52
[40m[37mtrce[39m[22m[49m: Ocelot.Logging.OcelotDiagnosticListener[0]
requestId: no request id, previousRequestId: no previous request id, message: MiddlewareStarting: Microsoft.AspNetCore.Builder.UseExtensions+<>c__DisplayClass0_1; /api/v1/modules/Test,
[40m[37mtrce[39m[22m[49m: Ocelot.Logging.OcelotDiagnosticListener[0]
=> RequestId:0HLC9FDIE2EJR:00000001 RequestPath:/api/v1/modules/Test => RequestId:0HLC9FDIE2EJR:00000001 RequestPath:/api/v1/modules/Test
requestId: no request id, previousRequestId: no previous request id, message: MiddlewareStarting: Microsoft.AspNetCore.Builder.UseExtensions+<>c__DisplayClass0_1; /api/v1/modules/Test,
Ocelot.Logging.OcelotDiagnosticListener:Trace: requestId: no request id, previousRequestId: no previous request id, message: MiddlewareStarting: Microsoft.AspNetCore.Builder.UseExtensions+<>c__DisplayClass0_1; /api/v1/modules/Test,
Ocelot.Errors.Middleware.ExceptionHandlerMiddleware:Debug: requestId: no request id, previousRequestId: no previous request id, message: ocelot pipeline started,
[40m[37mdbug[39m[22m[49m: Ocelot.Errors.Middleware.ExceptionHandlerMiddleware[0]
requestId: no request id, previousRequestId: no previous request id, message: ocelot pipeline started,
[40m[37mdbug[39m[22m[49m: Ocelot.Errors.Middleware.ExceptionHandlerMiddleware[0]
=> RequestId:0HLC9FDIE2EJR:00000001 RequestPath:/api/v1/modules/Test => RequestId:0HLC9FDIE2EJR:00000001 RequestPath:/api/v1/modules/Test
requestId: no request id, previousRequestId: no previous request id, message: ocelot pipeline started,
[40m[37mdbug[39m[22m[49m: Ocelot.DownstreamRouteFinder.Middleware.DownstreamRouteFinderMiddleware[0]
requestId: no request id, previousRequestId: no previous request id, message: upstream url path is /api/v1/modules/Test,
Ocelot.DownstreamRouteFinder.Middleware.DownstreamRouteFinderMiddleware:Debug: requestId: no request id, previousRequestId: no previous request id, message: upstream url path is /api/v1/modules/Test,
[40m[37mdbug[39m[22m[49m: Ocelot.DownstreamRouteFinder.Middleware.DownstreamRouteFinderMiddleware[0]
=> RequestId:0HLC9FDIE2EJR:00000001 RequestPath:/api/v1/modules/Test => RequestId:0HLC9FDIE2EJR:00000001 RequestPath:/api/v1/modules/Test
requestId: no request id, previousRequestId: no previous request id, message: upstream url path is /api/v1/modules/Test,
Loaded '/usr/share/dotnet/store/x64/netcoreapp2.0/microsoft.aspnetcore.http.extensions/2.0.1/lib/netstandard2.0/Microsoft.AspNetCore.Http.Extensions.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
[40m[37mdbug[39m[22m[49m: Ocelot.RateLimit.Middleware.ClientRateLimitMiddleware[0]
requestId: no request id, previousRequestId: no previous request id, message: EndpointRateLimiting is not enabled for Ocelot.Values.PathTemplate,
Ocelot.RateLimit.Middleware.ClientRateLimitMiddleware:Debug: requestId: no request id, previousRequestId: no previous request id, message: EndpointRateLimiting is not enabled for Ocelot.Values.PathTemplate,
[40m[37mdbug[39m[22m[49m: Ocelot.RateLimit.Middleware.ClientRateLimitMiddleware[0]
=> RequestId:0HLC9FDIE2EJR:00000001 RequestPath:/api/v1/modules/Test => RequestId:0HLC9FDIE2EJR:00000001 RequestPath:/api/v1/modules/Test
requestId: no request id, previousRequestId: no previous request id, message: EndpointRateLimiting is not enabled for Ocelot.Values.PathTemplate,
Loaded '/usr/share/dotnet/shared/Microsoft.NETCore.App/2.0.5/System.Security.Principal.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
[40m[37mtrce[39m[22m[49m: Ocelot.Authentication.Middleware.AuthenticationMiddleware[0]
requestId: no request id, previousRequestId: no previous request id, message: No authentication needed for /api/v1/modules/Test,
Ocelot.Authentication.Middleware.AuthenticationMiddleware:Trace: requestId: no request id, previousRequestId: no previous request id, message: No authentication needed for /api/v1/modules/Test,
[40m[37mtrce[39m[22m[49m: Ocelot.Authentication.Middleware.AuthenticationMiddleware[0]
=> RequestId:0HLC9FDIE2EJR:00000001 RequestPath:/api/v1/modules/Test => RequestId:0HLC9FDIE2EJR:00000001 RequestPath:/api/v1/modules/Test
requestId: no request id, previousRequestId: no previous request id, message: No authentication needed for /api/v1/modules/Test,
[40m[37mdbug[39m[22m[49m: Ocelot.Authorisation.Middleware.AuthorisationMiddleware[0]
requestId: no request id, previousRequestId: no previous request id, message: /api/v1/{everything} route does not require user to be authorised,
Ocelot.Authorisation.Middleware.AuthorisationMiddleware:Debug: requestId: no request id, previousRequestId: no previous request id, message: /api/v1/{everything} route does not require user to be authorised,
[40m[37mdbug[39m[22m[49m: Ocelot.Authorisation.Middleware.AuthorisationMiddleware[0]
=> RequestId:0HLC9FDIE2EJR:00000001 RequestPath:/api/v1/modules/Test => RequestId:0HLC9FDIE2EJR:00000001 RequestPath:/api/v1/modules/Test
requestId: no request id, previousRequestId: no previous request id, message: /api/v1/{everything} route does not require user to be authorised,
[40m[37mdbug[39m[22m[49m: Ocelot.DownstreamUrlCreator.Middleware.DownstreamUrlCreatorMiddleware[0]
requestId: no request id, previousRequestId: no previous request id, message: downstream url is https://<docker-service-name>:5000/api/v1/modules/Test,
Ocelot.DownstreamUrlCreator.Middleware.DownstreamUrlCreatorMiddleware:Debug: requestId: no request id, previousRequestId: no previous request id, message: downstream url is https://<docker-service-name>:5000/api/v1/modules/Test,
[40m[37mdbug[39m[22m[49m: Ocelot.DownstreamUrlCreator.Middleware.DownstreamUrlCreatorMiddleware[0]
=> RequestId:0HLC9FDIE2EJR:00000001 RequestPath:/api/v1/modules/Test => RequestId:0HLC9FDIE2EJR:00000001 RequestPath:/api/v1/modules/Test
requestId: no request id, previousRequestId: no previous request id, message: downstream url is https://<docker-service-name>:5000/api/v1/modules/Test,
[40m[37mdbug[39m[22m[49m: Ocelot.Requester.Middleware.HttpRequesterMiddleware[0]
requestId: no request id, previousRequestId: no previous request id, message: IHttpRequester returned an error, setting pipeline error,
Ocelot.Requester.Middleware.HttpRequesterMiddleware:Debug: requestId: no request id, previousRequestId: no previous request id, message: IHttpRequester returned an error, setting pipeline error,
[40m[37mdbug[39m[22m[49m: Ocelot.Requester.Middleware.HttpRequesterMiddleware[0]
=> RequestId:0HLC9FDIE2EJR:00000001 RequestPath:/api/v1/modules/Test => RequestId:0HLC9FDIE2EJR:00000001 RequestPath:/api/v1/modules/Test
requestId: no request id, previousRequestId: no previous request id, message: IHttpRequester returned an error, setting pipeline error,
[41m[30mfail[39m[22m[49m: Ocelot.Responder.Middleware.ResponderMiddleware[0]
requestId: no request id, previousRequestId: no previous request id, message: 1 pipeline errors found in ResponderMiddleware. Setting error response status code
Ocelot.Responder.Middleware.ResponderMiddleware:Error: requestId: no request id, previousRequestId: no previous request id, message: 1 pipeline errors found in ResponderMiddleware. Setting error response status code
[41m[30mfail[39m[22m[49m: Ocelot.Responder.Middleware.ResponderMiddleware[0]
=> RequestId:0HLC9FDIE2EJR:00000001 RequestPath:/api/v1/modules/Test => RequestId:0HLC9FDIE2EJR:00000001 RequestPath:/api/v1/modules/Test
requestId: no request id, previousRequestId: no previous request id, message: 1 pipeline errors found in ResponderMiddleware. Setting error response status code
The thread 111 has exited with code 0 (0x0).
The thread 0x6f has exited with code 0 (0x0).
[40m[37mdbug[39m[22m[49m: Ocelot.Errors.Middleware.ExceptionHandlerMiddleware[0]
requestId: no request id, previousRequestId: no previous request id, message: ocelot pipeline finished,
Ocelot.Errors.Middleware.ExceptionHandlerMiddleware:Debug: requestId: no request id, previousRequestId: no previous request id, message: ocelot pipeline finished,
[40m[37mdbug[39m[22m[49m: Ocelot.Errors.Middleware.ExceptionHandlerMiddleware[0]
=> RequestId:0HLC9FDIE2EJR:00000001 RequestPath:/api/v1/modules/Test => RequestId:0HLC9FDIE2EJR:00000001 RequestPath:/api/v1/modules/Test
requestId: no request id, previousRequestId: no previous request id, message: ocelot pipeline finished,
[40m[37mtrce[39m[22m[49m: Ocelot.Logging.OcelotDiagnosticListener[0]
requestId: no request id, previousRequestId: no previous request id, message: MiddlewareFinished: Microsoft.AspNetCore.Builder.UseExtensions+<>c__DisplayClass0_1; 200,
Ocelot.Logging.OcelotDiagnosticListener:Trace: requestId: no request id, previousRequestId: no previous request id, message: MiddlewareFinished: Microsoft.AspNetCore.Builder.UseExtensions+<>c__DisplayClass0_1; 200,
[40m[37mtrce[39m[22m[49m: Ocelot.Logging.OcelotDiagnosticListener[0]
=> RequestId:0HLC9FDIE2EJR:00000001 RequestPath:/api/v1/modules/Test => RequestId:0HLC9FDIE2EJR:00000001 RequestPath:/api/v1/modules/Test
requestId: no request id, previousRequestId: no previous request id, message: MiddlewareFinished: Microsoft.AspNetCore.Builder.UseExtensions+<>c__DisplayClass0_1; 200,
Loaded '/usr/share/dotnet/store/x64/netcoreapp2.0/microsoft.aspnetcore.webutilities/2.0.1/lib/netstandard2.0/Microsoft.AspNetCore.WebUtilities.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
[40m[32minfo[39m[22m[49m: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
Request finished in 407.9077ms 404
Microsoft.AspNetCore.Hosting.Internal.WebHost:Information: Request finished in 407.9077ms 404
[40m[32minfo[39m[22m[49m: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
=> RequestId:0HLC9FDIE2EJR:00000001 RequestPath:/api/v1/modules/Test => RequestId:0HLC9FDIE2EJR:00000001 RequestPath:/api/v1/modules/Test
Request finished in 407.9077ms 404`

**Comment by TomPallister** [comment]
@NicoKno thanks for the extra information! Is <docker-service-name> obfuscated or is that what you are actually setting in the DownstreamHostAndPorts.Host? If it is I'm not sure how that would work. It needs to be a valid hostname such as localhost, test.com I don't think <docker-service-name> is :o

**Comment by NicoKno** [comment]
Just as I said in my last post, the hostnames are obfuscated for the sake of posting here. Normally those are service names from my docker-compose.yml where the gateway service and the services I try to call are started from.

**Comment by TomPallister** [comment]
@NicoKno the error you are getting suggests that when the HttpClient calls your downstream service it is getting an exception (the logging here is absolutely useless, I will improve it). I will wait to find out about "<docker-service-name>"!

**Comment by TomPallister** [comment]
@NicoKno OK thanks sorry I missed that! Can Ocelot network to the downstream services and is your https certificate valid?

**Comment by NicoKno** [comment]
Ocelot is in the same docker-network just as my services. My https certificate is a self-signed one which I created and passed to each one of the services.

**Comment by TomPallister** [comment]
@NicoKno I will add some extra logging so we can work this out! I’m sorry the logging is rubbish! Will try and do it tonight so you can pull a new package ASAP!

**Comment by TomPallister** [comment]
@NicoKno please can you install this package

Install-Package Ocelot -Version 5.1.0-unstable0004	

Then try your request again and hopefully we should see the error. If you paste the whole it here I should be able to help more!

**Comment by NicoKno** [comment]
@TomPallister Thanks for the quick improvement.

This is the concrete error I get now:

`Ocelot.Responder.Middleware.ResponderMiddleware:Error: requestId: no request id, previousRequestId: no previous request id, message: Error making http request, exception: System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.CurlException: Couldn't connect to server
   at System.Net.Http.CurlHandler.ThrowIfCURLEError(CURLcode error)
   at System.Net.Http.CurlHandler.MultiAgent.FinishRequest(StrongToWeakReference`1 easyWrapper, CURLcode messageResult)
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ocelot.Requester.HttpClientHttpRequester.<GetResponse>d__4.MoveNext()
[41m[30mfail[39m[22m[49m: Ocelot.Responder.Middleware.ResponderMiddleware[0]
=> RequestId:0HLCAAM8E6N6S:00000001 RequestPath:/connect/token => RequestId:0HLCAAM8E6N6S:00000001 RequestPath:/connect/token
requestId: no request id, previousRequestId: no previous request id, message: Error making http request, exception: System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.CurlException: Couldn't connect to server
at System.Net.Http.CurlHandler.ThrowIfCURLEError(CURLcode error)`

It seems like my Gateway with Ocelot can't connect to the other service somehow. I also tried to switch from the docker service name to "localhost" in the configuration.json. But with the same error as outcome. Luckily I now can track the issue down further, but I seems as if it is not an Ocelot issue, but on with my docker environment. If there are any ideas anyway, they would be most welcome.

**Comment by TomPallister** [comment]
@NicoKno I'm not sure to be honest :( debugging docker networking can be a pain. 

This might help https://deis.com/blog/2016/connecting-docker-containers-1/ or this https://stackoverflow.com/questions/41093812/how-to-get-docker-containers-to-talk-to-each-other-while-running-on-my-local-hos

I will close the issue now because I don't think this is Ocelot specific. But feel free to reopen it if you find that it is!! Or any other issue!

**Comment by NicoKno** [comment]
Just for the sakes of completeness. I got it working. It was a combination of https and docker networking. I used the externally mapped port of my docker-service, which is not necessary if the gateway runs in the same docker-network, you just use the port which is exposed internally by the specific docker-container.
The other thing was, that I tried to forward the incoming https requests as https to docker-containers having no open https-ports in the internal network. 
This maybe of some help for someone.

**Comment by saitejaprattipati** [comment]
I have similar issue and i have tried solution @NicoKno above but had no luck and getting same error as mentioned at beginning .

My configuration file:
		{
  			"ReRoutes": [
    			{
      				"DownstreamPathTemplate": "/api/{everything}",
      				"DownstreamScheme": "http",
      				"DownstreamHostAndPorts": [
        				{
          					"Host": "authoradmin.command.api",
          					"Port": 80
        				}
      					],
      				"UpstreamPathTemplate": "/api/ad/{everything}",
      				"UpstreamHttpMethod": [ "POST", "PUT", "GET" ]
    			}
  				],
  			"GlobalConfiguration": {
    				"RequestIdKey": null,
    				"AdministrationPath": null
  			}
		}

my Docker file is follows:

  		authoradmin.command.api:
    			image: ${DOCKER_REGISTRY-}authoradmincommandapi
    			build:
      			context: .
      			dockerfile: CommandStack/AuthorAdmin.Command.API/Dockerfile
    			depends_on:
      				- rabbitmq
    			links: 
      				- rabbitmq


docker override is as follows:

  			authoradmin.command.gateway:
    			environment:
      				- ASPNETCORE_ENVIRONMENT=Development
      				- IdentityUrl=http://identity.api
    			ports:
      				- "50106:80"
    			volumes:
      				- ./CommandStack/AuthorAdmin.Command.API:/app/configuration

Any help is appreciated.

**Comment by saitejaprattipati** [comment]
@TomPallister  Can you please help me regarding the issue i have commented above.

**Comment by saad569** [comment]
> Just for the sakes of completeness. I got it working. It was a combination of https and docker networking. I used the externally mapped port of my docker-service, which is not necessary if the gateway runs in the same docker-network, you just use the port which is exposed internally by the specific docker-container. The other thing was, that I tried to forward the incoming https requests as https to docker-containers having no open https-ports in the internal network. This maybe of some help for someone.
> 
> @TomPallister Thanks again for the effort, it really helped me along the way.

would you please explain it in details as I am also having the same issue, Please explain it in ocelot config change and docker-compose changes

**Comment by rajeev-jha-india** [comment]
@NicoKno I am having similar issue, could you please share some detailed explanation, how you had fixed that one.
