### ISSUE TITLE
New Feature - find and replace on response body

### ISSUE THREAD

**Issue by rokjank** [ThreeMammals/Ocelot#275]
Hi, 

I have an issue with the website which are hosted under the Ocelot. 

I have Ocelot running on port :82 and another website on port :5000.

configuration is:
"ReRoutes": [
    {
      "DownstreamPathTemplate": "/{everything}",
      "DownstreamScheme": "http",
      "DownstreamPort": "5000",
      "DownstreamHost": "localhost",
      "UpstreamPathTemplate": "/abc/{everything}",
      "UpstreamHttpMethod": [ "Get", "Post" ]
}],
  "GlobalConfiguration": {
"BaseUrl": "http://localhost:82"
  }

When I open the website directly so localhost:5000/{something} everything is ok, but when I open it over the Ocelot (so localhost:82/abc/{something}) all css/js files are loaded from incorrect path. In the developer tools console on the browser tt shows these resources were tried to load from localhost:82/css but actually they should be loaded from localhost:82/abc/css.

Can I achieve this behavior using Ocelot?

**Comment by TomPallister** [comment]
@rokjank thanks for your interest in the project! :)

Ocelot can be used in front of a website but the URLS your html returns to the browser must have the correct path in them for Ocelot. In your example your html is (although i have not seen it) returning localhost:82/css and you want it to be localhost:82/abc/css. In this case you would need to do a find and replace or something on the HttpResponse Body. 

That is not a feature that Ocelot supports at the moment but you could use this feature http://ocelot.readthedocs.io/en/latest/features/middlewareinjection.html to hook into the Ocelot pipeline and add the find and replace logic yourself.

e.g.

```csharp
var configuration = new OcelotMiddlewareConfiguration
{
    PreErrorResponderMiddleware = async (ctx, next) =>
    {
        await next.Invoke();
        //do your transformation here on ctx.HttpContext.Response
    }
};

app.UseOcelot(configuration);
```

I will keep this ticket open and change the title to add a new feature for find and replace in HttpResponse body.

**Comment by TomPallister** [comment]
@rokjank I should also add find and replace might break other things so may not fix your issue! It might be that you just cant do what you want with Ocelot!

**Comment by TomPallister** [comment]
decided not to do this, easy feature could be done with DelegatingHandler
