### ISSUE TITLE
Does Ocelot has the support for WebSockets

### ISSUE THREAD

**Issue by SrikanthNalam** [ThreeMammals/Ocelot#277]
## Expected Behavior / New Feature
  @TomPallister : Could you please let us know if there is any support for Web Sockets for Ocelot right now.Right now,I see there is no documentation related this.Could you please let me know what are your plans on this ?

## Actual Behavior / Motivation for New Feature
 Spring gateway in Java has a similar feature which supports the Web Sockets.It is good to have this kind of functionality in Ocelot as well for .net core world or for .net world.

URLS :
 1) https://github.com/spring-cloud/spring-cloud-gateway/blob/master/docs/src/main/asciidoc/spring-cloud-gateway.adoc
2) https://github.com/spring-cloud/spring-cloud-gateway/issues/6

## Steps to Reproduce the Problem

  1.
  1.
  1.

## Specifications

  - Version:
  - Platform:
  - Subsystem:

**Comment by TomPallister** [comment]
@SrikanthNalam not yet! Someone else has asked for this feature on #212 so I will close this issue and reference your request there.

I have been working on the feature and I got a proxy working but I'm having a hard time trying to work out how to make it testable and learning about websocket implementation!
