### ISSUE TITLE
New Feature - Add the traceid in the response headers

### ISSUE THREAD

**Issue by zpf1989** [ThreeMammals/Ocelot#280]
Hi,we are using Butterfly in Ocelot for tracing.
Generally,when client request fails,we want to find the exact trace quickly.
I think it is fastest to search a trace by traceId ,because it matches only one trace.
So could you add the traceid in the response headers when using tracing before return?
Just like this below:
responseMessage.Headers.TryAddWithoutValidation("TraceId", span.SpanContext.TraceId);
https://github.com/ThreeMammals/Ocelot/blob/c1b315173f5be626a8eba98c7a71eebd9e7a10d5/src/Ocelot/Requester/OcelotHttpTracingHandler.cs#L58
Thanks!

**Comment by zpf1989** [comment]
Yeah,that's considerate!
Thanks!

**Comment by TomPallister** [comment]
released in version 5.1.0
