### ISSUE TITLE
New Feature - Provide more detailed log

### ISSUE THREAD

**Issue by yuleyule66** [ThreeMammals/Ocelot#287]
Hello ,  I encountered some difficulties in configuring error lookups.

Can you provide more detailed content in the logging content?  like the request URL and current error configuration.

This is the current logging content :
```
requestId: no request id, previousRequestId: no previous request id, message: DownstreamRouteFinderMiddleware setting pipeline errors. IDownstreamRouteFinder returned Error Code: UnableToFindDownstreamRouteError Message: UnableToFindDownstreamRouteError
```
and

```
requestId: no request id, previousRequestId: no previous request id, message: 1 pipeline errors found in ResponderMiddleware. Setting error response status code
```

When I have a lot of configuration, it's hard to find out which configuration item caused the error.

Thanks~!

**Comment by TomPallister** [comment]
@yuleyule66 I agree this could be a lot better.

**Comment by TomPallister** [comment]
I log errors at the end of the pipeline...would make more sense to log them as they happen.

**Comment by TomPallister** [comment]
@yuleyule66 what do you mean by "current error configuration"? asp.net core should indicate the type of log in the message e.g. error, debug etc

**Comment by TomPallister** [comment]
Maybe add url to log context, maybe we just need some sort of log context object with all these things on...it would be nice to just log when an error object is created (hook into this somehow)

Maybe an error object pool and when you take  from it, something calls the logger, no idea just throwing ideas out!

**Comment by yuleyule66** [comment]
@TomPallister 
"current error configuration" That is to say, I am currently configuring the wrong configuration item in configuration.json, such as "DownstreamHostAndPorts" to specify the wrong address or port. we can print them out when logging. I don't know if this is more difficult to implement,  just an idea !

**Comment by TomPallister** [comment]
@yuleyule66 yep that makes sense, I will see if we can make it better!

**Comment by TomPallister** [comment]
close after release

**Comment by TomPallister** [comment]
logging improved in version 5.5.0
