### ISSUE TITLE
Duplicate named query strings are remove when mapping claims to query strings

### ISSUE THREAD

**Issue by david-martyn-ford** [ThreeMammals/Ocelot#289]
## Expected Behavior
Duplicate named query strings should be passed to the downstream service when using the claim to query string mapping.

Upstream Request: `GET: /?test=1&test=2`
Downstream Request: `GET: /?test=1&test=2&userType={value}`

## Actual Behavior
Only the first query string is mapped to the downstream service.

Upstream Request: `GET: /?test=1&test=2`
Downstream Request: `GET: /?test=1&userType={value}`

Duplicates are removed with the following code:
https://github.com/ThreeMammals/Ocelot/blob/b51df71d7bd2c532323fc4fc1d4fbba6afbb76bf/src/Ocelot/QueryStrings/AddQueriesToRequest.cs#L57:L59

### Request
`GET: http://localhost:5000/httpbin?test=1&test=2`

### ReRoute
```
{
  "DownstreamPathTemplate": "/get",
  "DownstreamScheme": "https",
  "DownstreamHostAndPorts": [
    {
      "Host": "httpbin.org",
      "Port": 443
    }
  ],
  "UpstreamPathTemplate": "/httpbin/",
  "UpstreamHttpMethod": [ "Get" ],
  "AuthenticationOptions": {
    "AuthenticationProviderKey": "TestKey",
    "AllowedScopes": [
      "openid",
      "offline_access"
    ]
  },
  "AddQueriesToRequest": {
    "UserType": "Claims[sub] > value[0] > |"
  }
}
```

**Comment by TomPallister** [comment]
@david-martyn-ford thanks for your interest in the project. 

First thoughts I agree. I'll have a look at this as current priority!

**Comment by david-martyn-ford** [comment]
@TomPallister Just upgraded and it is now working as expected! Really appreciate the quick turn around on this, was a big pain in the backside.

**Comment by pr0mming** [comment]
This doesn't works, I had test the 17.0.0 and the 18.0.0 :(
