### ISSUE TITLE
New Feature - Support Consul ACL token

### ISSUE THREAD

**Issue by toby2o12** [ThreeMammals/Ocelot#295]
consul server is enbled acl.
how did set consulclient configuration token field?

**Comment by TomPallister** [comment]
@toby2o12 Thanks for your interest in the project. I don't think this feature is supported at the moment. 

This is something we can definitely add. If you would like to do it yourself and submit a PR let me know and I will give you advice on how to complete the feature.

**Comment by Basil1991** [comment]
+1，Need it too.

**Comment by JCelento** [comment]
@TomPallister I would like to help, how can I complete the feature?

**Comment by TomPallister** [comment]
@JCelento awesome :)

I haven't looked at how to do this yet but my guess would be the following class needs to pass the key to Consul?

https://github.com/ThreeMammals/Ocelot/blob/develop/src/Ocelot/ServiceDiscovery/Providers/ConsulServiceDiscoveryProvider.cs

I would add the key to FileServiceDiscoveryProvider and call it Key so other things might be able to use the same property.

Map this onto ServiceProviderConfiguration internal object..
Then map that to ConsulRegistryConfiguration..

This would then be available to use in ConsulServiceDiscoveryProvider..

ConsulClient is from another lib and I guess it has functionality to handle the key in a nice way!

The other use case would be to add it to ConsulFileConfigurationRepository which might also need it when calling Consul.

Does this help you get started?

**Comment by TomPallister** [comment]
@JCelento I'm going to start working on this now, just wanted to let you know in case you started :)

**Comment by TomPallister** [comment]
will close after new package released

**Comment by TomPallister** [comment]
Can add ACL token in version 5.5.1 (just released). Please see docs [here](http://ocelot.readthedocs.io/en/latest/features/servicediscovery.html#acl-token)
