### ISSUE TITLE
New Feature - Merge configuration files

### ISSUE THREAD

**Issue by AaronFixer** [ThreeMammals/Ocelot#296]
## Expected Behavior / New Feature
This may already be a feature but I see no mention of it in the documentation and it isn't working in my project. 

It would be good to support multiple .json files, potentially with better naming conventions. I have an app with a number of services and routes, and it would be nice to separate them out into dedicated files rather then have one huge `configuration.json`. 

For example: 

 * AccountRoutes.json <- Would have all routes for the account controller/service
 * ComponentActions.json  <- Would have all the routes for component actions controller/service

etc. etc. 

Is this already possible? It seems that when I define multiple `.AddJsonFile()` it only picks up the routes in the last file it pinks up with the `ReRoutes` field.

**Comment by TomPallister** [comment]
@AaronFixer thanks for your interest in the project! 

This feature isn't supported yet I will but it on the backlog but if you would like to have a go yourself please feel free to submit a PR.

There are a couple of considerations here.

1. Ocelot uses configuration.json as a database so a solution would need to take multiple files and merge them into configuration.json or have a second file that ocelot uses as a database (not sure I like this).

2. Been thinking about this for a while completely change how configuration works. I was thinking of making it more like identity server where it is provided statically in c# / database. 

3. You could just do this yourself in ConfigureAppConfiguration with something like below and it would not need to be part of Ocelot.

```csharp
.ConfigureAppConfiguration((hostingContext, config) =>
                {
                    merger.Merge();
      
                    config
                        .SetBasePath(hostingContext.HostingEnvironment.ContentRootPath)
                        .AddJsonFile("configuration.json");
                })
```

I think 1 and 3 are better options at the moment for me but that could change!

Anyway let me know if you want to give this a try and I will be of as much assistance as I can...otherwise I'm afraid you will have to wait a bit for the feature :(

**Comment by AaronFixer** [comment]
For me this is definitely something I think I (and many others) could potentially benefit from with large projects wanting to use a Gateway! 

I'll have to do this in my spare time, although I don't imagine it should take too long. 

1 and 3 both work. 3 is something I could just use for the time being as a workaround. I'll see if I get a chance to work on a PR for 1. in the meantime.

Thanks for getting back to me!

**Comment by TomPallister** [comment]
Yep I agree this would be a useful feature! If you don't get round to it its on my list and I expect to do it in the next months or so.

**Comment by TomPallister** [comment]
@AaronFixer Ive merged a change that lets you have multiple configuration files..the docs for this are [here](http://ocelot.readthedocs.io/en/latest/features/configuration.html#merging-configuration-files). Can you let me know if you have any suggestions or this meets you use case before I release the change to NuGet?

**Comment by TomPallister** [comment]
@AaronFixer no worries, Ive just released this in 5.5.3, hopefully its OK, if not let me know and re-open issue!

**Comment by CesarD** [comment]
Hello, people.
I think I'm hitting a bug with this feature.

I have `ocelot.Development.json`, `ocelot.Testing.json` and `ocelot.global.json`. 
When I run the app on debug from VS, which should stick to the `Development` environment, it loads the `Testing` configuration in ocelot.json.

After taking a look at Ocelot's source code, I see this [line](https://github.com/ThreeMammals/Ocelot/blob/959a92ec6a32ae61bf8bac6023551085b0031b85/src/Ocelot/DependencyInjection/ConfigurationBuilderExtensions.cs#L45):
```
string excludeConfigName = env?.EnvironmentName != null ? $"ocelot.{env.EnvironmentName}.json" : string.Empty;
...
var files = new DirectoryInfo(folder)
                .EnumerateFiles()
                .Where(fi => reg.IsMatch(fi.Name) && (fi.Name != excludeConfigName))
                .ToList();
```
Unless I'm getting this wrong, it's excluding my `Development` environment file and keeping only the `Testing` one, which I think goes against the purpose of this feature, isn't it? It should include `Development` as it's the current environment in which the app is running and exclude all other environment files so they don't get merged into a conflicting configuration.

**Comment by CesarD** [comment]
BTW, and sorry for the double post, it would be great to extend this feature into detecting file naming as the following:
```
ocelot.customers.{environment}.json
ocelot.users.{environment}.json
ocelot.products.{environment}.json
```

This way this would allow us to better isolate groups of APIs also for each environment.

**Comment by zhutoutou** [comment]
Can this method support IHostEnvironment Or How transform IHostEnvironment to IWebHostEnvironment ?

**Comment by zhutoutou** [comment]
Can this method support IHostEnvironment Or How transform IHostEnvironment to IWebHostEnvironment ?

**Comment by Faisal-developer** [comment]
@zhutoutou use this

   public static IHostBuilder CreateHostBuilder(string[] args) =>
                 Host.CreateDefaultBuilder(args)
                    .ConfigureWebHostDefaults(webBuilder =>
                    {
                        webBuilder.ConfigureAppConfiguration((hostingContext, config) =>
                          {
                              config.AddOcelot("Routes", hostingContext.HostingEnvironment);
                              config.SetBasePath(hostingContext.HostingEnvironment.ContentRootPath)
                                    .AddJsonFile("ocelot.json",true)
                                    .AddEnvironmentVariables();
                          })
                         .ConfigureServices(services =>
                         {
                             services.AddOcelot();
                         })
                        .Configure(app =>
                        {
                            //app.UseRouting();
                            //app.UseEndpoints(endpoints => {
                            //    endpoints.MapControllers();
                            //});
                            app.UseOcelot().Wait();

**Comment by Flave1** [comment]
> ocelot

Hi,
Please how do you then make the program.cs file identify this json files

**Comment by NicoJuicy** [comment]
> @zhutoutou use this
> 
> public static IHostBuilder CreateHostBuilder(string[] args) =>
> Host.CreateDefaultBuilder(args)
> .ConfigureWebHostDefaults(webBuilder =>
> {
> webBuilder.ConfigureAppConfiguration((hostingContext, config) =>
> {
> config.AddOcelot("Routes", hostingContext.HostingEnvironment);
> config.SetBasePath(hostingContext.HostingEnvironment.ContentRootPath)
> .AddJsonFile("ocelot.json",true)
> .AddEnvironmentVariables();
> })
> .ConfigureServices(services =>
> {
> services.AddOcelot();
> })
> .Configure(app =>
> {
> //app.UseRouting();
> //app.UseEndpoints(endpoints => {
> // endpoints.MapControllers();
> //});
> app.UseOcelot().Wait();

A bit better formatting, it wasn't clear what changed to me ( fyi it's the part with wrapping ConfigureAppConfiguration with ConfigureWebHostDefaults

      Host.CreateDefaultBuilder(args)
                .ConfigureWebHostDefaults(webBuilder =>
                {
                    webBuilder.UseStartup<Startup>();
                })
            .ConfigureWebHostDefaults(webBuilder =>//this is a requirement to wrap ConfigureAppConfiguration in, for .net core 3.0 for multiple configurations
            {
                webBuilder.UseUrls("https://*:44326")
                .ConfigureAppConfiguration((hostingContext, config) =>
                {
                    config.SetBasePath(hostingContext.HostingEnvironment.ContentRootPath)
                    //  .AddJsonFile("gateway/v1/orders.json")
                    //.AddJsonFile("gateway/v1/orders.json")
                    //.AddJsonFile("gateway/v1/shipping.json") //this won't work to load multiple configs
                    .AddEnvironmentVariables()
                    .AddOcelot("gateway/v1", hostingContext.HostingEnvironment); //loads multiple configurations : https://github.com/ThreeMammals/Ocelot/issues/1047
                });
            })

**Comment by raman-m** [comment]
@CesarD  Hi César!
Are you still with Ocelot?
**FYI** #1183

**Comment by CesarD** [comment]
> > @CesarD commented [on Jun 21, 2019](#issuecomment-504517067)
> > @CesarD commented [on Jun 21, 2019](#issuecomment-504518229)
> 
> Hi César!
> Are you still with Ocelot?
> **FYI** #1183 

No, sorry, I moved onto YARP since quite a while ago.

**Comment by raman-m** [comment]
@CesarD  LoL It is OK that you've moved to another gateway.
I found your past comments really valuable, and we can include these requirements as extra ones to #651 and #1183

**Comment by CesarD** [comment]
Yeah, sorry, is just that for a couple years there was no movement and it was difficult to justify implementing Ocelot while there was another MS-backed project doing similar stuff and being actively developed... 😅

**Comment by raman-m** [comment]
@CesarD  Hmm... Bla-bla gateway can merge configuration files, right? If Yes, could you share links to me plz? 
**To**: dotnet044 [at] gmail.com
Don't you mind if

**Comment by CesarD** [comment]
Well, bla-bla gateway doesn't require to load the configuration from a specific file or type of files, you can very well have its config in the appsettings.json directly and you just need to specifiy the section where you want to pull the config from... If you want to load extra files into the configuration it's up to you, as long as the files don't overlap same configurations between each other, so it provides another kind of flexibility that I got used to.
Perhaps you can adapt Ocelot likewise...

**Comment by raman-m** [comment]
> @CesarD commented [on Nov 11](#issuecomment-1806863696)
being actively developed...

Aha! Especially when you have a team of 3+ full time senior developers on-site at Microsoft with bla-bla salaries. 😛 

----
> @CesarD commented [on Nov 11](#issuecomment-1806877918)
config in the **appsettings.json**

Yeap! Ocelot has strange design of configuration feature based on **ocelot.json** file. We will discuss and plan to migrate to **appsettings.json** with significant refactoring of Configuration feature. Current design is ugly, and developers are confused that they must write special files to configure app instead of well-known ASP.NET approach to use  **appsettings.json**.
