### ISSUE TITLE
Request Aggregates Response Is not a Standard Json

### ISSUE THREAD

**Issue by dasajia2lang** [ThreeMammals/Ocelot#304]
## Expected Behavior / New Feature
if a key.s response is a string not a object ,zhen the Aggregates responses a not a standdard json .
the string response has miss  double quotation marks。

## Steps to Reproduce the Problem

  1.{
  "ReRoutes": [
    {
      "DownstreamPathTemplate": "/demoApi1/values/{id}",
      "DownstreamScheme": "http",
      "DownstreamHostAndPorts": [
        {
          "Host": "localhost",
          "Port": 5001
        }
      ],
      "UpstreamPathTemplate": "/OcelotAPIGateWay/demoApi1/values/{id}",
      "UpstreamHttpMethod": [ "Get" ],
      "Key": "ids"
    },
    {
      "DownstreamPathTemplate": "/demoApi1/values",
      "DownstreamScheme": "http",
      "DownstreamHostAndPorts": [
        {
          "Host": "localhost",
          "Port": 5001
        }
      ],
      "UpstreamPathTemplate": "/OcelotAPIGateWay/demoApi1/values",
      "UpstreamHttpMethod": [ "Get" ],
      "Key": "values"
    }
  ],
  "GlobalConfiguration": {
  },
  "Aggregates": [
    {
      "ReRouteKeys": [
        "values",
        "ids"
      ],
      "UpstreamPathTemplate": "/OcelotAPIGateWay/Aggregates"
    }
  ]
}
  2.    // GET api/values/5
        [HttpGet("{id}")]
        public string Get(int id)
        {
            return "value";
        }
  3.{"ids":value,"values":["demoApi1","请求"]}

## Specifications

  - Version:5.5.0
  - Platform:core 2.0
  - Subsystem:window

**Comment by TomPallister** [comment]
@dasajia2lang thanks for your interest in the project, I will take a look at this asap!

**Comment by TomPallister** [comment]
@dasajia2lang This is currently how the feature is intended to work. If you have a look at the docs [here](http://ocelot.readthedocs.io/en/latest/features/requestaggregation.html#gotcha-s-further-info) it should make sense. 

Basically the basic request aggregation only works with services that return JSON.

I intend to improve this functionality and you can track the progress in issue #298.
