### ISSUE TITLE
Graphql support

### ISSUE THREAD

**Issue by Rajivhost** [ThreeMammals/Ocelot#306]
Hi,
Any plan to provide a Graphql support?

[Reference](https://stackoverflow.com/questions/44416904/use-kong-as-api-gateway-to-graphql-rest-services)

Best regards,
Rajiv.

**Comment by TomPallister** [comment]
@Rajivhost It is something I have considered but I think GraphQL is a separate concern to API Gateway. 

If you want to use GraphQL with Ocelot I would suggest having Ocelot forward requests to another service running GraphQL. In this way you can use Ocelot's cross cutting features such as authorisation, authentication etc and the power of GraphQL to find and aggregate data. 

Ocelot does have a very basic aggregation feature because many users requested it, but I don't want to make it too complicated or Ocelot will start to bloat :( However GraphQL is very tempting and could be used in the future but no concrete plans to implement at the moment!

**Comment by Rajivhost** [comment]
@TomPallister like you suggest, I was thinking use Ocelot to forward requests, the problem is Ocelot should expose just one endpoint "/graphql" in order to my client apps use graphql. With this unique endpoint, it's hard for me to redirect request to differents microservices behind the Api-gateway.

**Comment by TomPallister** [comment]
@Rajivhost can you explain your target architecture more? If you are using GraphQL will you not have one endpoint anyway e.g.

Ocelot => GraphQL => n services

Does that make sense?

**Comment by Rajivhost** [comment]
Thank you @TomPallister for this example.

**Comment by Rajivhost** [comment]
How do you handle this kind of scenrio where you can replace GraphQL as API Gateway by Ocelot.
![image](https://user-images.githubusercontent.com/3539984/38780852-b436a066-40d4-11e8-833e-f4b16cf2617c.png)

Best regards,
Rajiv

**Comment by TomPallister** [comment]
@Rajivhost I would not advise replacing GraphQL with Ocelot.

GraphQL is for aggregating data
Ocelot is an API Gateway

However if you really want to do this. Like I have shown in the sample project you would need to have all your GraphQL logic into the same application as Ocelot. Then call your GraphQL logic with a DelegatingHandler.

This would allow you to use Ocelot for authorisation, authentication, caching etc but Ocelot's routing wont work, you need to code this up like you would in a normal GraphQL application with the resolvers etc.

I think it might make sense to have Ocelot deployed in front of GraphQL in this architecture. That way you separate the concerns of GraphQL and API Gateway. Have the clients send requests to Ocelot, Ocelot forwards them to GraphQL after doing whatever logic is required. 

I think the major trade off is one extra hop from Ocelot to GraphQL so you need to make this as fast as possible, you could in theory run Ocelot and GraphQL server in a sidecar configuration so the hop doesnt go out to the network but this then makes configuration tricky.

Other than this I think it is win win to separate GraphQL and API Gateway.

**Comment by Rajivhost** [comment]
@TomPallister ok, I think I will do like you suggest. Let Ocelot handles all the authorisation, authentication, caching etc parts and make Routing to the microservices behind manually.
Thank you.

**Comment by TomPallister** [comment]
@Rajivhost good luck!

**Comment by QuocNguyen2501** [comment]
Could we implement like this picture ??
![capture33](https://user-images.githubusercontent.com/5207501/44075761-249acbfa-9fc8-11e8-86b9-c9406aa8cc8e.PNG)

**Comment by TomPallister** [comment]
Yes but you need different endpoints on Ocelot to route to your graphql services!

**Comment by QuocNguyen2501** [comment]
Thank @TomPallister , I try it.
