### ISSUE TITLE
New Feature - Add custom HTTP Header

### ISSUE THREAD

**Issue by FelixBoers** [ThreeMammals/Ocelot#313]
It should be possible to configure custom HTTP header with static values (without transformation!) for both the downstream response and the upstream request. Currently it's only possible to set them for the downstream response (see #280).

Sample configuration:

```json
{
  "ReRoutes": [
    {
      "DownstreamHeaderTransform": {
        "X-Custom-Header": "Value put into response to downstreams"
      },
      "UpstreamHeaderTransform": {
        "X-Custom-Header": "Value put into request for upstream"
      },
    }
  ]
}
```

If the header is sent in the origin request then it gets overwritten.

Related to #280 

**Checklist**
- [x] Write some tests
- [x] Edit documentation

**Comment by TomPallister** [comment]
@FelixBoers thank you so much for this contribution! Really nice to get some help 😄 

Will close the issue now I merged the PR!

**Comment by SimantoR** [comment]
I'm wondering if this is possible programmatically? I need to be able to pass user id and I was thinking maybe I could plug it somewhere within Ocelot's pipeline to add name from Principle to the header before passing it downstream.

**Comment by FelixBoers** [comment]
@SimantoR I'm not exactly sure if I'm understanding you right but I think this will get you there: https://ocelot.readthedocs.io/en/latest/features/delegatinghandlers.html

So I would suggest to write a DelegatingHandler which manipulates the downstream request and then calls the base handler. 

As far as I know there is no direct whay for achieving this functionality.
