### ISSUE TITLE
据说 腾讯要用？

### ISSUE THREAD

**Issue by handashuai** [ThreeMammals/Ocelot#315]
## Steps to Reproduce the Problem

  1.
  1.
  1.

## Specifications

  - Version:
  - Platform:
  - Subsystem:

**Comment by geffzhang** [comment]
see Customers：https://customers.microsoft.com/en-us/story/tencent-telecommunications-dotnetcore

**Comment by TomPallister** [comment]
Not sure what this issue is about the title translates to "It is said that Tencent wants to use" in google translate. Please re-open if there is actually anything that needs help etc!
