### ISSUE TITLE
Support sticky sessions for load balancer

### ISSUE THREAD

**Issue by darting** [ThreeMammals/Ocelot#322]
Hi there,

Does Ocelot support sticky session for load balance? And how to configure it?

Thanks

**Comment by TomPallister** [comment]
@darting thanks for your interest in the project. At the moment Ocelot does not have any specific support for sticky sessions.

**Comment by darting** [comment]
hi @TomPallister, do you have any plan to support it? :)

**Comment by TomPallister** [comment]
@darting I’m not sure, Ocelot has a load balancer abstraction so using some kind of identifier it shouldn’t be too hard. How would you want this to work?

**Comment by darting** [comment]
I think should be same with haproxy 

https://www.haproxy.com/blog/load-balancing-affinity-persistence-sticky-sessions-what-you-need-to-know/

**Comment by TomPallister** [comment]
@darting OK Ill take a look ASAP!

**Comment by darting** [comment]
thanks :)

**Comment by TomPallister** [comment]
@Burnaster take a look at ILoadBalancer and it’s implementations. Also look at the load balancing middleware. You might be able to do the work here with a new load balancer. 

All the requests get a guid from asp.net HttpContext.TraceIdentifier already!
