### ISSUE TITLE
How can I change the port when I used the Administration API

### ISSUE THREAD

**Issue by dasajia2lang** [ThreeMammals/Ocelot#323]
## Expected Behavior / New Feature

when I used the admin Api,bind the path http://localhost:57063,not the 5000,I succeed to get a token,but when I want to get the config, it it error.  where is it I must change the default port 5000?

WebHost.CreateDefaultBuilder(args)
                .UseStartup<Startup>().UseUrls("http://localhost:57063")

## Steps to Reproduce the Problem

  1.IOException: IDX10804: Unable to retrieve document from: 'http://localhost:5000/administration/.well-known/openid-configuration'.
Microsoft.IdentityModel.Protocols.HttpDocumentRetriever+<GetDocumentAsync>d__8.MoveNext()

InvalidOperationException: IDX10803: Unable to obtain configuration from: 'http://localhost:5000/administration/.well-known/openid-configuration'

## Specifications

  - Version:
  - Platform:
  - Subsystem:

**Comment by TomPallister** [comment]
@dasajia2lang this is in the global configuration BaseUrl

```json
{
    "ReRoutes": [],
    "GlobalConfiguration": {
        "BaseUrl": "http://localhost:57063"
    }
}
```

Hope this helps!

**Comment by TomPallister** [comment]
Going to close the issue, let me know if still have problems.

**Comment by TomPallister** [comment]
@dasajia2lang I’m not sure, how does the authorization header look?

**Comment by dasajia2lang** [comment]
@TomPallister ,Authorization:Bearer {{token}},this is the format.my get method is ok,

**Comment by TomPallister** [comment]
@dasajia2lang if you set logging level to trace, can you paste the log here?

**Comment by dasajia2lang** [comment]
@TomPallister ，I used postman to send a request ,it do not work ,but I used the code to request  it is ok!!
thanks help!!

**Comment by TomPallister** [comment]
@dasajia2lang awesome! I will close this issue for now :)
