### ISSUE TITLE
Need help regarding Request ID / Co-relation Id

### ISSUE THREAD

**Issue by shah-keyur** [ThreeMammals/Ocelot#327]
Need help regarding Request ID / Co-relation Id

My flow will be like this
**Request from Postman -> Service 1(GetYears)(via API Gateway) ->( Rest call to API gateway )->Service 2(GetMakes)->Response**

I want the co-relation Id to be same and logged in each service.

How can I achieve it? 

My config is like
"GlobalConfiguration": {
    // It is use to configure the Co-Relation Id/ RequestId  for logging purpose
    "RequestIdKey": "OcRequestId",
    "AdministrationPath": "/administration"
  }

**Comment by shah-keyur** [comment]
@TomPallister ,

One more thing,

Request->Postman->Service1.GetYears() -> Service2.GetMakes()

**Log for service1.GetYears() is** 

dbug: Ocelot.Errors.Middleware.ExceptionHandlerMiddleware[0]
      => ConnectionId:0HLD9LTVL850A => RequestId:0HLD9LTVL850A:00000001 RequestPath:/vs/v1/vehicle/years
      requestId: no request id, previousRequestId: no previous request id, message: ocelot pipeline started,

**Log  for Service2.GetMakes() is**
dbug: Ocelot.Errors.Middleware.ExceptionHandlerMiddleware[0]
      requestId: 0HLD9LTVL8506:00000001, 0HLD9LTVL8506:00000002, 0HLD9LTVL850A:00000001, previousRequestId: 0HLD9LTVL8506:00000001, 0HLD9LTVL8506:00000002, 0HLD9LTVL850A:00000001, message: ocelot pipeline finished,

I can see multiple Requet id  in RequestId.
I am trying to understand why ?

**Comment by TomPallister** [comment]
@shah-keyur this is strange!!

Where is Ocelot in this  Request->Postman->Service1.GetYears() -> Service2.GetMakes() ?

**Comment by shah-keyur** [comment]
Hi @TomPallister ,

Sorry, 
Let me write it in better way.

Request ->Postmat-> Service1.GetYears() (Via Api Gateway -Ocelot) -> Call to service2.GetMakes(using Rest call from client library via APi Gateway)-> response.

I want to track the request in service1.GetYears and service2.GetMakes with same co-relation id.

Hope this helps to understand what I am looking for.

Thanks,
Keyur

**Comment by TomPallister** [comment]
feel free to re-open if you can send me the information requested above 😄

**Comment by shah-keyur** [comment]
Hi TomPallister,

Just I found that I was keep adding the OcRequestId without removing the previous id so OcRequestId was having semicolon(;) seperated multiple OcRequestId.

My problem is solved.

Thanks for your help.

your info helped me to resolve the issue.
 "It looks like you are configuration everything correctly. With your setup, Ocelot will look for a header called OcRequestId and look for its value. It will then use that value for logging and forward the header to downstream services as OcRequestId. If there is no header in the request Ocelot should create one and use the asp.net context traceidentifier as its value."

**Comment by abuzaforfagun** [comment]
Hi,
I have a similar question.
Here is my flow: Swagger -> Gateway -> Service 1.

When I request to the gateway. I found ```requestId: 0HMC126R3VIF8:00000007``` as the request id.
In Service 1, ```_httpContextAccessor.HttpContext.Request.Headers["OcRequestId"]``` returns 0HMC126T1OEDC.

I want to get the same correlation id in Gateway and other services.
Here is my ocolet.json:
```"GlobalConfiguration": {
    "BaseUrl": "https://localhost:44300",
    "RequestIdKey": "OcRequestId"
  }```
  You also can find the repo in: [https://github.com/abuzaforfagun/Invoice.Microservices.ThirdPartyAPIIntegration](https://github.com/abuzaforfagun/Invoice.Microservices.ThirdPartyAPIIntegration)
  
  Did I miss anything?

**Comment by amopan** [comment]
Have the same problem with @abuzaforfagun. As I can see the problem in MutiplexingMiddleware and hardcoded RequestId header key. In that middleware ocelot starts nested HttpContext with new randomly generated TraceId and that TraceId used as RequestId instead of the TraceId from original HttpContext. So in output logs we always see identifier from original request but all downstream routes used TranceId from nested HttpContext. This bug does not allow to match upstream and downstream requests by CorelationId/RequestId
