### ISSUE TITLE
Need help regarding Ratelimit

### ISSUE THREAD

**Issue by shah-keyur** [ThreeMammals/Ocelot#343]
Hi @TomPallister ,

We are  planning to use Ocelot extensively and its features.

Few questions regarding the Ocelot rate limiting.

1. How ocelot keeps track of the rate limit per user?
2. Does it track the limit in memory/persist somewhere?
3. If there is load balancer or multiple instances of the services then how ocelot handles the rate limit?

My need is:

I want to set a rate limit for the user on a specific endpoint.
Eg, I want to allow a user to access endpoint 25 times in 1 minute.

Appreciate your help.

Thanks,
Keyur

**Comment by TomPallister** [comment]
@shah-keyur thanks for your interest in the project 😄 The rate limiting docs are [here](http://ocelot.readthedocs.io/en/latest/features/ratelimiting.html) are they any help?

1. If you look at ClientRateLimitMiddleware.cs it might make more sense!
2. It is just persisted in memory, I guess redis would be the next feature to implement here!
3. Ocelot does not currently share the state across instances...this could be solved with redis.

I hope these answers help!

**Comment by svipandi** [comment]
I am not having any kind of configuration for rate limit in configuration.json.
When i try to make more than 5000 request per minute request is not reaching the api gateway.

Is ocelot handles any default rate limit ?
