### ISSUE TITLE
Create Kubernetes ServiceDiscoveryProvider 

### ISSUE THREAD

**Issue by sivakumar2999** [ThreeMammals/Ocelot#345]
## Steps to Reproduce the Problem

  1.
  1.
  1.

## Specifications

  - Version:
  - Platform:
  - Subsystem:

**Comment by sivakumar2999** [comment]
is support kubernetes default service registry

**Comment by TomPallister** [comment]
@sivakumar2999 can you explain in more detail what you expect here?

Ocelot already works with kubernetes dns service provider. You can see an example of how you might configure Ocelot [here](https://github.com/dotnet-architecture/eShopOnContainers/blob/dev/k8s/ocelot/configuration-mobile-marketing.json)

**Comment by TomPallister** [comment]
@sivakumar2999 are you referring to this API https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.10/#endpoints-v1-core and then load balance across the pods?

**Comment by TomPallister** [comment]
This might be useful for this feature https://github.com/kubernetes-client/csharp

We just need to implement IServiceDiscoveryProvider for k8s that watches the api above
