### ISSUE TITLE
Skip reroutings or reroute everything except

### ISSUE THREAD

**Issue by AmbroiseCouissin** [ThreeMammals/Ocelot#348]
Hi there! Thanks for the tool, it's pretty awesome.

## Expected Behavior / New Feature
I'd like to skip some reroutings. What if I want to have an UI and serve static files in the same webapp?
I didn't manage to find a way to skip in the pipeline with a "if (no routing specified) { next(context)}" somewhere.

## Actual Behavior / Motivation for New Feature
Right now, the first one in the pipeline has priority.

## Steps to Reproduce the Problem
```
            app.UseSpa(spa =>
            {
                spa.Options.SourcePath = "ClientApp";
                if (env.IsDevelopment())
                {
                    spa.UseReactDevelopmentServer(npmScript: "start");
                }
            });

            app.UseOcelot().Wait();
```

Cheers!

**Comment by TomPallister** [comment]
@AmbroiseCouissin thanks for your interest in the project. My first thoughts are Ocelot isn't really designed to front static assets however some people are using it for this purpose as I have had to fix issues with it in the past :)

Does [this](http://ocelot.readthedocs.io/en/latest/features/routing.html?highlight=priority#priority) help with your scenario? You can set the priority of ReRoutes which means the order in the config is not relevant.

**Comment by AmbroiseCouissin** [comment]
Hi @TomPallister 
It's not exactly what I'm looking for. I want to be able to escape Ocelot middleware for some urls. Or go through it but not reroute at all. It's not about rerouting priority, it's about not rerouting at all.

I know Ocelot is not really supposed to be working well with other middlewares but if you have a solution for this, I would be really grateful. It would also help some of the graphql peeps in here for those who don't want to have three/four different gateways.

**Comment by TomPallister** [comment]
@AmbroiseCouissin mmm maybe the .net core MapWhen method in asp.net core middleware might help. The docs are [here](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/middleware/?view=aspnetcore-2.1&tabs=aspnetcore2x). 

You might be able to do something like app.MapWhen(x => IsStatic(x)) do something else.

You would need to do the MapWhen before calling app.UseOcelot().Wait();

**Comment by techaum** [comment]
@AmbroiseCouissin  You solve that?

Im trying to running a SPA and ocelot, but both didnt work together.
