### ISSUE TITLE
Question - Ocelot use Consul UseServiceDiscovery not working.

### ISSUE THREAD

**Issue by capyu** [ThreeMammals/Ocelot#350]
When I specify DownstreamHostAndPorts then every thing is fine. But as long as remove DownstreamHostAndPorts  info, and set UseServiceDiscovery = true, then Ocelot will got error.

Any body can help me ?  Thanks

> fail: Ocelot.Responder.Middleware.ResponderMiddleware[0]
>       requestId: no request id, previousRequestId: no previous request id, message: 1 pipeline errors found in ResponderMiddleware. Setting error response status code
> fail: Ocelot.Responder.Middleware.ResponderMiddleware[0]
>       requestId: no request id, previousRequestId: no previous request id, message: Error making http request, exception: System.UriFormatException: Invalid URI: The hostname could not be parsed.
>          at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
>          at System.Uri..ctor(String uriString)
>          at System.UriBuilder.get_Uri()
>          at Ocelot.Request.Middleware.DownstreamRequest.ToHttpRequestMessage()
>          at Ocelot.Requester.HttpClientHttpRequester.<GetResponse>d__4.MoveNext()
> 

my config :

```
{
	"ReRoutes": [
					{
						"DownstreamPathTemplate": "/webapi/api/Values",
						"DownstreamScheme": "http",
						//"DownstreamHostAndPorts": [
						//	{
						//		"Host": "192.168.2.11",
						//		"Port": 80
						//	}
						//],
						"UpstreamPathTemplate": "/api/Values",
						"UpstreamHttpMethod": [ "Get" ],
						"ServiceName": "NetCoreAPI",
						"UseServiceDiscovery": true,
						"ReRouteIsCaseSensitive": false
					},
					{
						"DownstreamPathTemplate": "/webapi/api/Values/{id}",
						"DownstreamScheme": "http",
						//"DownstreamHostAndPorts": [
						//	{
						//		"Host": "192.168.2.11",
						//		"Port": 80
						//	}
						//],
						"UpstreamPathTemplate": "/api/Values/{id}",
						"UpstreamHttpMethod": [ "Get" ],
						"ServiceName": "NetCoreAPI",
						"UseServiceDiscovery": true,
						"ReRouteIsCaseSensitive": false
					}
	],
	"GlobalConfiguration": {
		"BaseUrl": "http://localhost:14485",
		"RequestIdKey": "OcRequestId",
		"ServiceDiscoveryProvider": {
			"Provider": "Consul",
			"Host": "192.168.2.11",
			"Port": 8500
		}
	}
}

```
and I can query service from Consul   
http://192.168.2.11:8500/v1/health/service/NetCoreAPI

then I get

[{"Node":{"ID":"4c800427-7d34-9ec1-e848-28782581b92c","Node":"Consul-One","Address":"192.168.2.11","Datacenter":"dc1","TaggedAddresses":{"lan":"192.168.2.11","wan":"192.168.2.11"},"Meta":{"consul-network-segment":""},"CreateIndex":16386,"ModifyIndex":16389},"Service":{"ID":"NetCoreAPI","Service":"NetCoreAPI","Tags":["api"],"Address":"","Meta":null,"Port":80,"EnableTagOverride":false,"CreateIndex":17048,"ModifyIndex":17048},"Checks":[{"Node":"Consul-One","CheckID":"ping","Name":"ping","Status":"passing","Notes":"","Output":"\r\nPing 192.168.2.1 (\ufffdϥ\ufffd 32 \ufffd줸\ufffdժ\ufffd\ufffd\ufffd\ufffd\ufffd):\r\n\ufffd^\ufffdЦ\ufffd 192.168.2.1: \ufffd줸\ufffd\ufffd=32 time\u003c1ms TTL=128\r\n\ufffd^\ufffdЦ\ufffd 192.168.2.1: \ufffd줸\ufffd\ufffd=32 time\u003c1ms TTL=128\r\n\ufffd^\ufffdЦ\ufffd 192.168.2.1: \ufffd줸\ufffd\ufffd=32 time\u003c1ms TTL=128\r\n\ufffd^\ufffdЦ\ufffd 192.168.2.1: \ufffd줸\ufffd\ufffd=32 time\u003c1ms TTL=128\r\n\r\n192.168.2.1 \ufffd\ufffd Ping \ufffdέp\ufffd\ufffd\ufffd\ufffd:\r\n    \ufffdʥ]: \ufffdw\ufffdǰe = 4\ufffdA\ufffdw\ufffd\ufffd\ufffd\ufffd = 4, \ufffdw\ufffd\ufffd\ufffd\ufffd = 0 (0% \ufffd\ufffd\ufffd\ufffd)\ufffdA\r\n\ufffdj\ufffd\ufffd\ufffd\ufffd\ufffdӦ^\ufffdɶ\ufffd (\ufffd@\ufffd\ufffd):\r\n    \ufffd̤p\ufffd\ufffd = 0ms\ufffdA\ufffd̤j\ufffd\ufffd = 0ms\ufffdA\ufffd\ufffd\ufffd\ufffd = 0ms\r\n","ServiceID":"","ServiceName":"","ServiceTags":[],"Definition":{},"CreateIndex":16386,"ModifyIndex":17054},{"Node":"Consul-One","CheckID":"serfHealth","Name":"Serf Health Status","Status":"passing","Notes":"","Output":"Agent alive and reachable","ServiceID":"","ServiceName":"","ServiceTags":[],"Definition":{},"CreateIndex":16386,"ModifyIndex":16386},{"Node":"Consul-One","CheckID":"service:NetCoreAPI","Name":"Service 'NetCoreAPI' check","Status":"passing","Notes":"","Output":"  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current\r\n                                 Dload  Upload   Total   Spent    Left  Speed\r\n\r  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0\r100    22    0    22    0     0  22000      0 --:--:-- --:--:-- --:--:-- 22000[\"Resource\",\"Service\"]\r\n","ServiceID":"NetCoreAPI","ServiceName":"NetCoreAPI","ServiceTags":["api"],"Definition":{},"CreateIndex":17048,"ModifyIndex":17117}]},{"Node":{"ID":"b2cc92f0-0e82-d428-e28f-9ac6a60fd598","Node":"Consul-Two","Address":"192.168.2.12","Datacenter":"dc1","TaggedAddresses":{"lan":"192.168.2.12","wan":"192.168.2.12"},"Meta":{"consul-network-segment":""},"CreateIndex":17056,"ModifyIndex":17057},"Service":{"ID":"NetCoreAPI","Service":"NetCoreAPI","Tags":["api"],"Address":"","Meta":null,"Port":80,"EnableTagOverride":false,"CreateIndex":17057,"ModifyIndex":17057},"Checks":[{"Node":"Consul-Two","CheckID":"ping","Name":"ping","Status":"passing","Notes":"","Output":"\r\nPing 192.168.2.1 (\ufffdϥ\ufffd 32 \ufffd줸\ufffdժ\ufffd\ufffd\ufffd\ufffd\ufffd):\r\n\ufffd^\ufffdЦ\ufffd 192.168.2.1: \ufffd줸\ufffd\ufffd=32 time\u003c1ms TTL=128\r\n\ufffd^\ufffdЦ\ufffd 192.168.2.1: \ufffd줸\ufffd\ufffd=32 time\u003c1ms TTL=128\r\n\ufffd^\ufffdЦ\ufffd 192.168.2.1: \ufffd줸\ufffd\ufffd=32 time\u003c1ms TTL=128\r\n\ufffd^\ufffdЦ\ufffd 192.168.2.1: \ufffd줸\ufffd\ufffd=32 time\u003c1ms TTL=128\r\n\r\n192.168.2.1 \ufffd\ufffd Ping \ufffdέp\ufffd\ufffd\ufffd\ufffd:\r\n    \ufffdʥ]: \ufffdw\ufffdǰe = 4\ufffdA\ufffdw\ufffd\ufffd\ufffd\ufffd = 4, \ufffdw\ufffd\ufffd\ufffd\ufffd = 0 (0% \ufffd\ufffd\ufffd\ufffd)\ufffdA\r\n\ufffdj\ufffd\ufffd\ufffd\ufffd\ufffdӦ^\ufffdɶ\ufffd (\ufffd@\ufffd\ufffd):\r\n    \ufffd̤p\ufffd\ufffd = 0ms\ufffdA\ufffd̤j\ufffd\ufffd = 0ms\ufffdA\ufffd\ufffd\ufffd\ufffd = 0ms\r\n","ServiceID":"","ServiceName":"","ServiceTags":[],"Definition":{},"CreateIndex":17059,"ModifyIndex":17062},{"Node":"Consul-Two","CheckID":"serfHealth","Name":"Serf Health Status","Status":"passing","Notes":"","Output":"Agent alive and reachable","ServiceID":"","ServiceName":"","ServiceTags":[],"Definition":{},"CreateIndex":17056,"ModifyIndex":17056},{"Node":"Consul-Two","CheckID":"service:NetCoreAPI","Name":"Service 'NetCoreAPI' check","Status":"passing","Notes":"","Output":"  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current\r\n                                 Dload  Upload   Total   Spent    Left  Speed\r\n\r  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0\r100    22    0    22    0     0  22000      0 --:--:-- --:--:-- --:--:-- 22000[\"Resource\",\"Service\"]\r\n","ServiceID":"NetCoreAPI","ServiceName":"NetCoreAPI","ServiceTags":["api"],"Definition":{},"CreateIndex":17057,"ModifyIndex":17106}]}]

**Comment by TomPallister** [comment]
@capyu Thanks for your interest in the project 😄 

I noticed that your downstream host is 192.168.2.11 and your Consul service discovery provider host is also 192.168.2.11. Are you intending to call Consul in your ReRoutes because this is not calling a downstream service.

In the response from consul I cannot see an Address registered for the services 

```json
 "Service": {
            "ID": "NetCoreAPI",
            "Service": "NetCoreAPI",
            "Tags": [
                "api"
            ],
            "Address": "",
            "Meta": null,
            "Port": 80,
            "EnableTagOverride": false,
            "CreateIndex": 17057,
            "ModifyIndex": 17057
        },
```

Ocelot uses the Address field as the address it makes the downstream request to.

Try adding your services IP to address and it should work.

**Comment by capyu** [comment]
Thanks @TomPallister for your help.

This is my first post in github.  Sorry for forget question label and thanks your friendly help.
I really forget to check sonsul's service config.  Indeed, I lost to define my service ip address.

Thanks a lot.

**Comment by TomPallister** [comment]
@capyu glad to be of help! Don’t worry about the labels it’s just for me!
