### ISSUE TITLE
How to create a jwt token on downstream and request third party server 

### ISSUE THREAD

**Issue by tsirkin** [ThreeMammals/Ocelot#352]
I am trying to configure the Ocelot to make Authentication and Authorization for us.
The plan is to make Ocelot redirect non authenticated requests to a SSO server (SAML) 
and once this is done request access permissions of the user from Access Management (AC) server (separate in our case).
The Ocelot should maintain upstream session/jwt (probably dumb one ) 
and replace this with his own jwt including user info & access claims.

But I can't find a simple way to access AC ,no way to add another jwt for downstream only.
The only way I found was to use DelegatingHandler, the problem with it is that it have no access to DI I could found and thus non configurable, making it's usage unacceptable.

Any ideas please?

**Comment by tsirkin** [comment]
Possibly answering my own question,
Should I override the OcelotPipelineConfiguration with my own middleware for this?

**Comment by TomPallister** [comment]
@tsirkin the delegating handlers use standard .net core di. Any services you register will be injected when the handler is resolved. 

You can also override or do whatever you want with the pipeline!

**Comment by tsirkin** [comment]
Thank you for quick answer.
Unfortunately, after straggling with it for hours I couldn't find a way to DI DelegatingHandler.
Sure, there are examples for doing this, but nothing I could get working under .Net Core 2.
Seems like it was working in .Net 4.5 (maybe Core 1) but not Core 2. Any pointers (or code !) would be highly appreciated.
Thought I understand this is not a .Net forum, sorry.

What middleware do you suggest me to overwrite in OcelotPipelineConfiguration?

**Comment by TomPallister** [comment]
@tsirkin it should work fine, you need to register your dependencies using services.AddXXX<X,X>(); or equivalent. Then in your DelegatingHandler inject the dependencies. 

Look at HttpDelegatingHandlersTests.cs in the Ocelot.AcceptanceTests project for examples of how this works.

Don't worry we will get to bottom of why it is not working 😄

**Comment by tsirkin** [comment]
Tried it already,obviously and it did not work.
Handler is injected fine but if I try to inject (anything, even IServiceCollection) it fails.
I will try later to provide the code

**Comment by TomPallister** [comment]
@tsirkin can you provide the code and configuration you were using? E.g your program.cs, startup.cs, the delegating handler code and json config? I will take a look. Yep

**Comment by tsirkin** [comment]
Thank you, here is the gist (no Startup.cs - I used Program.cs for the configuration)
https://gist.github.com/tsirkin/131871d18bd5b297ffc73fd29af1577b

**Comment by TomPallister** [comment]
@tsirkin I finally had a chance to look at this. The main problem is your constructor is not public for asp.net core DI cannot use it.

If you change your class to the following it will resolve the JwtDownstreamHandler(IServiceProvider serviceProvider) constructor. 

Even if you make the JwtDownstreamHandler(HttpMessageHandler innerHandler, IServiceProvider serviceProvider) : base(innerHandler) constructor public asp.net core wont be able to resolve it because there is no default HttpMessageHandler in the container. Ocelot handles this bit anyway and you cannot override it at the moment. 

```csharp
public class JwtDownstreamHandler : DelegatingHandler
    {
        private readonly IServiceProvider _serviceProvider;

        public JwtDownstreamHandler(IServiceProvider serviceProvider)
        {
            _serviceProvider = serviceProvider;
        }

        protected JwtDownstreamHandler(HttpMessageHandler innerHandler, IServiceProvider serviceProvider) : base(innerHandler)
        {
        }

        protected override async Task<HttpResponseMessage> SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
        {
            return await base.SendAsync(request, cancellationToken);
        }
    }
```

Hope that helps! Let me know if you have anymore problems.

**Comment by tsirkin** [comment]
If you are right then it is such a stupid bug in my part!
(I am sure I it was public and just restoring this code in order to post it here I created it as protected.
No way I was such an idiot.)
Anyway, I will try it and let you know if it works.
Thanks!

**Comment by tsirkin** [comment]
OK, that was it.
Sorry for my stupidity.

**Comment by TomPallister** [comment]
@tsirkin no worries!
