### ISSUE TITLE
Ocelot and identity server

### ISSUE THREAD

**Issue by tatronic** [ThreeMammals/Ocelot#355]
Hello, I wish to set up identiy server and ocelot in my architecture of Micro Services. I do not know if I followed your documentation well but, I confess that I am really troubled.
- Is there any special configuration to do on identity server?
- How to route the authentication request to identity server?
- How to route all other incoming requests after authentication?
thank you.

here are my configurations

1 - Identity server

           return new List<ApiResource>
            {
                new ApiResource("Api1", "Api service"),
                new ApiResource("gateway", "Api gateway")
            };

2 - Ocelot - Startup

           var authenticationProviderKey = "ID4";
            services.AddAuthentication()
            .AddIdentityServerAuthentication(authenticationProviderKey, options =>
            {
                options.RequireHttpsMetadata = false; 
                options.Authority = "http://localhost:5000";
                options.ApiName = "gateway";
                options.SupportedTokens = SupportedTokens.Both;
            });
            services.AddOcelot();

3 - Ocelot - Configuration file

            "ReRoutes": [
               {
                   "DownstreamHostAndPorts": [
                        {
                          "Host": "localhost",
                          "Port": 5000
                        }
                    ],
                    "DownstreamPathTemplate": "/",
                    "UpstreamPathTemplate": "/",
                    "UpstreamHttpMethod": [ "Post" ],
                   "ReRouteIsCaseSensitive": false,
                   "DownstreamScheme": "http",
                   "AuthenticationOptions": {
                   "AuthenticationProviderKey": "ID4",
                   "AllowedScopes": []
                }
             }
              ],
             "GlobalConfiguration": {
            }

**Comment by TomPallister** [comment]
- Is there any special configuration to do on identity server?
A: No
- How to route the authentication request to identity server?
A: Ocelot does this for you based on the options passed into AddIdentityServerAuthentication in startup. If you look at Ocelot class AuthenticationMiddleware.cs this might make more sense.
- How to route all other incoming requests after authentication?
A: The routing docs are [here](http://ocelot.readthedocs.io/en/latest/features/routing.html) all you need to do differently is add your authentication provider key to the ReRoute configuration as described [here](http://ocelot.readthedocs.io/en/latest/features/authentication.html).

Hope that helps. Let me know if it doesn't.

**Comment by tatronic** [comment]
Hi Tom,
Thank you for your answer.
Other questions still come to my mind and what I would like to know is:
- With respect to identityServer, Ocelot behaves like a client or as an API resource?
- In the case of authentication, if we provide the authentication options such as authenticationProviderKey, what will be the use of the downStreamHostAndPort which is in the reRoute?
 Thank you

**Comment by TomPallister** [comment]
@tatronic Ocelot behaves like a resource. The key tells Ocelot which authentication provider to use for a given reroute. The downstreamhostandport tells Ocelot where the downstream service is you are protecting with Ocelot + Identity Server.

**Comment by shirishgadre** [comment]
Tom,
I am having trouble setting up ID Server and Ocelot. Ocelot creates its own ID server path even if I tell it http://localhost:5000. My ID Server is running on that Port but I see Ocelot going to a different Port and using the /administration path in the URL. Here are the Logs from executing a GET on the first URL.

APIGateway>       Request starting HTTP/1.1 GET http://localhost:9000/api/customers/samplenames  
APIGateway>       Request starting HTTP/1.1 GET http://localhost:33676/administration/.well-known/openid-configuration  -- this is a wrong path. Why is Ocelot using this and why is it appending /administration?

The Second URL must be http://localhost:5000/.well-known/openid-configuration . I didn't set Port 33676 anywhere in the code or config, but I see it being used. Please help out as I have spent too much time on this.

Also my ID Server Options in startup include the same path. All other settings are the same as the examples:
 var authenticationProviderKey = "TestKey";
            Action<IdentityServerAuthenticationOptions> options = o =>
            {
                o.Authority = "http://localhost:5000";

**Comment by shirishgadre** [comment]
Tom, 
Does Ocelot support anything other than Bearer Tokens from Identity Server? For example Resource Owner or OpenID Connect? I did not see any examples on the site. Are they located elsewhere?

Thanks,
Shirish

**Comment by mehdipayervand** [comment]
Hi everybody
I could not understand what is  "AuthenticationProviderKey" and how works, please give an example.
