### ISSUE TITLE
how can i config consul in ocelot if there is a consul cluster?  use virtual ip?

### ISSUE THREAD

**Issue by jrlygdsj** [ThreeMammals/Ocelot#361]
"ServiceDiscoveryProvider": {
      "Provider": "Consul",
      "Host": "localhost",
      "Port": 8500
    }

**Comment by TomPallister** [comment]
@jrlygdsj if you run a cluster you should have a consul agent running as a client installed as a sidecar next to Ocelot. Ocelot calls the local agent and the agent is connected to the cluster.

**Comment by TomPallister** [comment]
@jrlygdsj that is correct but it should not matter because you should have a load balancer in front of Ocelot  that’s knows the service is down and doesn’t route requests to it.
