### ISSUE TITLE
 why LoadBalancer  not work

### ISSUE THREAD

**Issue by jkingzhu** [ThreeMammals/Ocelot#363]
my Ocelot.json like that
`{
  "ReRoutes": [
    {
      "DownstreamPathTemplate": "/api/values",
      "DownstreamScheme": "http",
      "DownstreamHostAndPorts": [
        {
          "Host": "localhost",
          "Port": 5002
        },
        {
          "Host": "localhost",
          "Port": 5001
        }
      ],
      "LoadBalancer": "RoundRobin",
      "UpstreamPathTemplate": "/api/values",
      "UpstreamHttpMethod": [ "Get" ],
      "QoSOptions": {
        "ExceptionsAllowedBeforeBreaking": 3,
        "DurationOfBreak": 10,
        "TimeoutValue": 5000
      }
    }
    
  ],
  "GlobalConfiguration": {
  }
}
`
but  LoadBalancer not work !
in "DownstreamHostAndPorts" if i let 5001 first ! it always visit 5001
then i let 5002 first   it always visit 5002 !!!! why???
I use the lastest version 7.1.0-unstable0005

**Comment by TomPallister** [comment]
@jkingzhu thanks for your interest in Ocelot! please can you paste your startup.cs and program.cs?

**Comment by jkingzhu** [comment]
First Thank for your replay ! Next I will paste them!
startup.cs like that 
` public Startup(IHostingEnvironment hostingEnvironment)
        {
            var builder = new ConfigurationBuilder();
            builder.SetBasePath(hostingEnvironment.ContentRootPath);
            builder.AddJsonFile("appsettings.json", false, true)
                .AddJsonFile($"appsettings.{hostingEnvironment.EnvironmentName}.json", false, true)
                .AddJsonFile("Ocelot.json", false, true)
                .AddEnvironmentVariables();
            Configuration = builder.Build();
            
        }

        public IConfiguration Configuration { get; }

        // This method gets called by the runtime. Use this method to add services to the container.
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddOcelot(Configuration);
            //services.AddMvc();
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public async void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)
        {
            loggerFactory.AddConsole(Configuration.GetSection("Logging"));
            loggerFactory.AddDebug();
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }
            await app.UseOcelot();
           // app.UseMvc();
        }`


program.cs code like this

`public static void Main(string[] args)
        {
            IWebHostBuilder builder = new WebHostBuilder();
            builder.ConfigureServices(s=> {
                s.AddSingleton(builder);
            });
            builder.UseKestrel()
                .UseContentRoot(Directory.GetCurrentDirectory())
                .UseIISIntegration()
                .UseStartup<Startup>()
                .UseApplicationInsights();
            var host = builder.Build();
            host.Run();
        }`

**Comment by jkingzhu** [comment]
Thank you very much, as you said the problem has been solved!
