### ISSUE TITLE
Upgrade Pivotal.Discovery.Client to Pivotal.Discovery.ClientCore

### ISSUE THREAD

**Issue by catcherwong** [ThreeMammals/Ocelot#364]
## Expected Behavior / New Feature

Based on the [documentation](http://steeltoe.io/docs/steeltoe-discovery/#1-2-1-add-nuget-reference) of Steeltoe , Using **Pivotal.Discovery.ClientCore** to replace **Pivotal.Discovery.Client** may be better. 

## Steps to Reproduce the Problem

  1.
  1.
  1.

## Specifications

  - Version:
  - Platform:
  - Subsystem:

**Comment by TomPallister** [comment]
@catcherwong thanks for your interest in Ocelot I have seen your articles they are very good 😄 

This looks good! Would you like to submit a PR to change this?

**Comment by catcherwong** [comment]
Yes! I am vary glad to do some contribution for this project.

**Comment by TomPallister** [comment]
awesome :)

**Comment by TomPallister** [comment]
@catcherwong thanks for your contribution!
