### ISSUE TITLE
Introduce a middleware to be called after response from downstream

### ISSUE THREAD

**Issue by mfahadi** [ThreeMammals/Ocelot#368]
## Expected Behavior / New Feature

I was playing with Ocelot as API gateway but was not able to find a middleware that would inject some headers in the response after it is returned from the downstream service for example injecting some headers or setting a cookie. 

There are middle wares before the call but none for after. 
http://ocelot.readthedocs.io/en/latest/features/middlewareinjection.html

Please update if there is already a way to do this or guide me how can I add this new feature in this code.

Thank you.

**Comment by TomPallister** [comment]
@mfahadi Thanks for your interest in the project. If you add code after the await next.Invoke(); you can change the http headers but you will need to change them on the DownstreamContext.DownstreamResponse.Headers object as Ocelot will then map these into the HttpResponse object. 

```csharp
var configuration = new OcelotPipelineConfiguration
{
    PreQueryStringBuilderMiddleware = async (ctx, next) =>
    {
        await next.Invoke();
        //add code here because all middleware as run at this point and the request is going to go back up the pipeline.
    }
};

app.UseOcelot(configuration);
```

Let me know if that helps at all? If not we can think of something else!

**Comment by rasti90** [comment]
How can I access DownstreamContext as the ctx object is HttpContext and doesn't have any DownstreamContext property.

**Comment by hamaronooo** [comment]
In some cases I've got `301 Moved Permanently` but in postman received a normal `200 `request. 
How to handle this?

**Comment by raman-m** [comment]
> @atulswagle wrote [on Apr 7](https://github.com/ThreeMammals/Ocelot/issues/368#issuecomment-2784592800)

Why don't you ask in [Discussions](https://github.com/ThreeMammals/Ocelot/discussions)?

Regarding question...
> Exception thrown: 'System.Threading.Tasks.TaskCanceledException' in System.Private.CoreLib.dll: 'A task was canceled.'
> Is there a better to handle this use case?

The exception may be generated due to a Timeout event, but I'm not certain.
Please wrap the code of the delegating handler with a `try-catch` construction and await all async methods.
This will provide a better understanding of what is happening.
