### ISSUE TITLE
Incorrect response StatusCode for middleware added before Ocelot

### ISSUE THREAD

**Issue by AlexKuriatnyk** [ThreeMammals/Ocelot#370]
I am adding request/response logging middleware to the pipeline before Ocelot. 
I noticed that response status code received by this middleware is always 200, even if it is not. At the same time, it is correct in response headers sent to the client. 

Looks like the reason of this is next logic at HttpContextResponder:
`
public void SetErrorResponseOnContext(HttpContext context, int statusCode)
{
            context.Response.OnStarting(x =>
            {
                context.Response.StatusCode = statusCode;
                return Task.CompletedTask;
            }, context);
}
`

Will it cause any problems if to set it directly without using OnStarting delegate?  

## Specifications

  - Version: 6.0.0
  - Platform:
  - Subsystem:

**Comment by TomPallister** [comment]
@AlexKuriatnyk Thanks for your interest in the project! 

asp.net used to throw an exception if your tried to set it without using the OnStarting function and giving it a delegate function. I have not tested it recently though..have you tried it? If you could test this and let me know that would be awesome. If you don't have time I will keep this issue open for now and try and look asap! 😄

**Comment by AlexKuriatnyk** [comment]
Yeah, I tried to set it directly at SetErrorResponseOnContext and this solves the problem

**Comment by TomPallister** [comment]
@AlexKuriatnyk awesome do you want to submit a PR with this change?

**Comment by AlexKuriatnyk** [comment]
@TomPallister , ok, will do.

**Comment by TomPallister** [comment]
Released in 7.0.5
