### ISSUE TITLE
RateLimitCore.ProcessRequest. Is it a bug?

### ISSUE THREAD

**Issue by stacklesshaha** [ThreeMammals/Ocelot#372]
RateLimitCore.ProcessRequest, I think it's a bug. when requests exceed Limit in Period,the next request doesn't have to wait for PeriodTimespan,just wait for a time longer than Period.

**# RateLimitCore.ProcessRequest,  I think it's a bug. when  requests exceed Limit in Period,the next request doesn't have to wait for PeriodTimespan,just wait for a time longer than Period.**

![3](https://user-images.githubusercontent.com/35445580/40536982-4e752366-6040-11e8-967b-83ea1943d09b.png)

![4](https://user-images.githubusercontent.com/35445580/40537461-8af20d30-6041-11e8-9044-d6b8a951494c.png)
![5](https://user-images.githubusercontent.com/35445580/40537467-905104a2-6041-11e8-93fe-e8e1ecb26eec.png)

**Comment by TomPallister** [comment]
@stacklesshaha thanks for your interest in the project! I think you might be correct. I will have a look ASAP

**Comment by TomPallister** [comment]
@stacklesshaha I have had a quick look at this and I'm not sure if there is a problem. Maybe @geffzhang could help us work this out?

I think the code might be OK because RetryAfterFrom uses PeriodTimespan to work out how much time has passed since the counter was created. I think line 37 is just checking to see if the existing counter has expired and uses the same property (Period) as when it is first cached (line 63 + 64).

Maybe you could write a failing test for this functionality so we can understand better?

**Comment by stacklesshaha** [comment]
anyway,thanks a lot （＾＿＾）

**Comment by TomPallister** [comment]
@stacklesshaha sorry I have been much help! Let’s see what geffzhang says

**Comment by stacklesshaha** [comment]
hello,@TomPallister,this is my testdemo,just see my console output and the config
![1](https://user-images.githubusercontent.com/35445580/40873057-f6442352-668b-11e8-8a2a-e4c736876811.png)
![2](https://user-images.githubusercontent.com/35445580/40873059-f6a0e5b0-668b-11e8-9513-5a1c8ee17185.png)

**Comment by TomPallister** [comment]
@stacklesshaha I will take a look at this next week! Sorry for he delay.

**Comment by TomPallister** [comment]
@stacklesshaha I think that Period and PeriodTimespan are meant to be the same value from looking at the acceptance test for this code. I suggest we remove one of the properties and use the same one in both places?

I think I would keep period and change it to an int representing milliseconds. What do you think?

**Comment by TomPallister** [comment]
@stacklesshaha Ive done a PR for this change if you want to take a look and let me know what you think!

**Comment by stacklesshaha** [comment]
or implementation of ratelimiter should be something like [Token Bucket](https://en.wikipedia.org/wiki/Token_bucket),maybe [SmoothRateLimiter.java](https://github.com/google/guava/blob/master/guava/src/com/google/common/util/concurrent/SmoothRateLimiter.java) is an implementation of Token Bucket

**Comment by TomPallister** [comment]
@stacklesshaha your English is very good do not worry. 

I think Period is a better name than PeriodTimespan because we shouldn’t use the type in a name. I will look at the references you have posted!

**Comment by stacklesshaha** [comment]
I think both PeriodTimespan and Period should be preserved,according to the previous document，their definitions are different

**Comment by TomPallister** [comment]
@stacklesshaha I wrote the documentation and it is not very good :( I think it might have confused you :(

After looking at it closely I cannot see why the two things are different? Can you explain why there are different?

**Comment by TomPallister** [comment]
@stacklesshaha with the limit and the period we are able to say how many requests a user can make per x which is all we need at the moment.

I looked at what Kong are doing [here](https://getkong.org/plugins/rate-limiting/) and there API is similar apart from they give more options around specific per x. I think the Kong project is a good example of how rate limiting should work.

**Comment by stacklesshaha** [comment]
oh,my english ⊂^j^⊃! in my testdemo, when requests exceed 1 per 1s,the next request  should have to wait for 10000. that's all my understanding of the document.that's why I think PeriodTimespan should be preserved

**Comment by TomPallister** [comment]
@stacklesshaha ahh I understand now! OK let me think about this :) 

Thank you for being patient. I didnt write the rate limiting code so I'm not very familiar with it.

**Comment by TomPallister** [comment]
@stacklesshaha I have made a new PR, #404 please can you look at it? Does it make sense for you?

**Comment by geffzhang** [comment]
Recently seldom come to pay attention to issue, sorry everybody. It's great to see the tests and documents written by @TomPallister ,, add  more Unit test about 1m,1h,1d 。

**Comment by TomPallister** [comment]
@geffzhang good to hear from you! I hope you are well. I agree we can improve rate limiting!

I have created another issue to discuss improving the rate limiting feature it is #408.

Let's keep this issue for fixing the bug originally raised.

**Comment by TomPallister** [comment]
@stacklesshaha Im going to merge the PR #404 because I hope it fixes this bug. Let me know if you think I have made a mistake.

**Comment by stacklesshaha** [comment]
sorry for having no time to reply，I will have a look ASAP. ^_^

**Comment by TomPallister** [comment]
Released in 7.0.6
