### ISSUE TITLE
How to donate?

### ISSUE THREAD

**Issue by yangzhongke** [ThreeMammals/Ocelot#375]
We're from rupeng.com, an online education company of China.
geffzhang is my friend.
We developed a course on .Net Core Microservice that using Ocelot as API GateWay.
We want to donate Ocelot, but don't know how to donate.Can you provide a way for donation?
thank you.

**Comment by TomPallister** [comment]
@yangzhongke wow! Thank you very much for your interest in the project and support!

I will investigate how you might be able to donate.

**Comment by TomPallister** [comment]
@yangzhongke I am not sure if this will work for you but I have created a PayPal.Me account for Ocelot [here](https://www.paypal.me/ThreeMammals). Let me know if this isn't suitable and I will try something else!

http://www.rupeng.com/ is a cool website 😄

**Comment by yangzhongke** [comment]
The course has not started yet,and orders have been growing.
I will study how to pay to your paypay account from my Chinese account later.
After I paying,I will update this issue.
Thanks for your greate job at Ocelot.

**Comment by TomPallister** [comment]
@yangzhongke awesome! I hope people enjoy the course! 😄

**Comment by yangzhongke** [comment]
I have payed 500 GBP to your paypal account
![ocelot](https://user-images.githubusercontent.com/13821363/41274078-a283a6b4-6e4e-11e8-8ae1-e725190a78d2.png)
!

**Comment by TomPallister** [comment]
@yangzhongke wow that is amazing! Thank you very much. I will think about how we can use this to make Ocelot even better! 

I hope that your course is very successful!!!!!
