### ISSUE TITLE
Prevent external client from making requests other than the ReRouted ones.

### ISSUE THREAD

**Issue by fablacky** [ThreeMammals/Ocelot#381]
I'm probably misunderstanding the excellent documentation. 

From what I could get, the same token is used to authenticate both my gateway and my API. Problem is, if someone using the client finds out my API address, since he is asking for a token which allows it to get through my protection, he could potencially make any request. 

One possible solution would be to release a token managing authentication between the client app and the gateway. Whenever someone makes a request, the gateway obtains another token regulating access to my API (which won't be available to the client). 

I'd like some direction in terms of best practice about this issue. Thank you so much for your work.

**Comment by TomPallister** [comment]
@fablacky the authentication scenario only works if your services are in a trusted private network. It does not work if they are public. If you want public services I suggest just forwarding the auth token to them. This is what Microsoft do.

**Comment by fablacky** [comment]
@TomPallister 
I don't understand. I thought my gateway was already forwarding my token (since my api are protected and are still accessed through the api gateway). I could set up my gateway as both an apiresource and a client asking for a token: my client app requests a token to use my gateway and the gateway itself asks another token to converse with my apis. Let me know what you think.

**Comment by TomPallister** [comment]
@fablacky yes Ocelot does forward the headers so your service will get the auth token. Yes you can have authentication / authorisation between the gateway and your services that is fine. 

I was just explaining that when I built Ocelot it was to access private services so no authentication is required between Ocelot and services in this scenario.

**Comment by fablacky** [comment]
@TomPallister thank you for your answer. 
I have a related request but perhaps it's better to discuss it here:
what if I want to configure the gateway to either ignore or not the querystring on the upstreampath? Or force the user to only put allowed parameters in my querystring? Would that require much effort to implement?

**Comment by TomPallister** [comment]
@fablacky I'm not exactly sure what you want to achieve but you might be able to do this with either http://ocelot.readthedocs.io/en/latest/features/middlewareinjection.html or http://ocelot.readthedocs.io/en/latest/features/delegatinghandlers.html im not sure which one would be better.
