### ISSUE TITLE
Fixed querystring in DownstreamPathTemplate

### ISSUE THREAD

**Issue by fablacky** [ThreeMammals/Ocelot#382]
I'd like to ask another (hopefully silly) question. 
Is it possible to set a querystring on the downstreamPathTemplate? 
`            "DownstreamPathTemplate": "/Instances?attributes=user_key",
            "DownstreamScheme": "https",
            "DownstreamHostAndPorts": [
                {
                    "Host": "customerservice.super.com",
                    "Port": 443
                }
            ],
            "UpstreamPathTemplate": "/Stub/Families",
            "UpstreamHttpMethod": [ "Get" ]
`
Apparently this configuration results in the '?' character being encoded as %3F and no longer recognized by the API receiving the request.
Thank you so much

**Comment by TomPallister** [comment]
@fablacky thanks for your interest in the project. This isn’t supported at the moment. If your request sends the querystring then it will be forwarded to the downstream services. We could implement this if that does not help! Let me know what you think?

**Comment by fablacky** [comment]
@TomPallister 
thank you so much for you quick response. This feature is kinda important but I'd love to keep using your project. Therefore I'd like to ask you if it's not much trouble to implement it. 

I am a bit tight on time and I'll probably try to solve it myself, in this case I'd love to get some advice on where to act (codewise) and in general best practices on how to edit the project.

**Comment by TomPallister** [comment]
@fablacky I think we would need to do this in the same way we can add headers to requests. It wouldn’t make sense to live in the path template code I think. I cannot look in detail until next week. I will reply again then.

**Comment by fablacky** [comment]
Wonderful, for now I simply wrote a quick DelegatingHandler replacing the encoded character and everything works nicely. Let me know next week if you were able to look into it.

**Comment by TomPallister** [comment]
This has been released in Ocelot 8.0.0!
