### ISSUE TITLE
Inject multiple PreQueryStringBuilderMiddleware 

### ISSUE THREAD

**Issue by fbeauche** [ThreeMammals/Ocelot#385]
Hi, Great job with ocelot ! 

I have a small question, is it possible to inject multiple PreQueryStringBuilderMiddleware ?

I have multiple cross-cutting concern I want to address in the my ocelot gateway and i would like to implement it in multiple middleware. 

Thanks.

**Comment by TomPallister** [comment]
@fbeauche thanks for your interest in the project. This is not possible. However you can call into whatever code you want from the pre query string builder middleware. I’m not sure that Ocelot needs this responsibility. If you would like to try and implement it let me know and I can help
