### ISSUE TITLE
how to update ocelot configuration without downtime

### ISSUE THREAD

**Issue by chenzhe014** [ThreeMammals/Ocelot#387]
when i update ocelot configuration，service must be closed. how to update **Configuration.json** online?

### Startup.cs
`services.AddOcelot(new ConfigurationBuilder()
                .AddJsonFile("configuration.json", optional: false, reloadOnChange: true)
                .Build());`
@geffzhang 
@TomPallister

**Comment by Stronhold** [comment]
One options would be use consul kv store as it is explained in the [doc](http://ocelot.readthedocs.io/en/latest/features/configuration.html#store-configuration-in-consul). 
Hope it helps!

**Comment by chenzhe014** [comment]
@Stronhold Thanks a lot！i will try it to slove ,
i saw #36 issue right now,  how to sloved it in #36 ?

**Comment by Stronhold** [comment]
Well, that is the other option, as it is stated in #36, here is the [doc ](http://ocelot.readthedocs.io/en/latest/features/administration.html) you need to solve your problem. I have not tested yet, so I do not know how it works exactly.
Hope it helps!

**Comment by chenzhe014** [comment]
@Stronhold I follow [doc](http://ocelot.readthedocs.io/en/latest/features/configuration.html#store-configuration-in-consull) alter my code.
**Startup.cs**
` 

            //services.AddOcelot(new ConfigurationBuilder()
            //    .AddJsonFile("configuration.json", optional: false, reloadOnChange: true)

            //    .AddEnvironmentVariables()
            //    .Build());

            services.AddOcelot().AddStoreOcelotConfigurationInConsul();`

**configuration.json**
`{
  "GlobalConfiguration": {
    "ServiceDiscoveryProvider": {
      "Host": "localhost",
      "Port": 8500,
      "ConfigurationKey": "Ocelot"
    }
  }
}`

**consul KV**
![consul_kv](https://user-images.githubusercontent.com/10006657/41395316-cb1da524-6fdf-11e8-8ffd-a0b6c8710417.png)

But i failed to run Ocelot successfully. Do I miss anything？
Thanks a lot!

**Comment by TomPallister** [comment]
@chenzhe014 is What error do you get from Ocelot?

**Comment by chenzhe014** [comment]
@TomPallister Just 404...
This is my Reroutes on Consul KV
`{"ReRoutes": [
    {
      "DownstreamPathTemplate": "/api/values",
      "DownstreamScheme": "http",
      "DownstreamHostAndPorts": [
        {
          "Host": "localhost",
          "Port": 5001
        }
      ],
      "UpstreamPathTemplate": "/webapia/values",
      "UpstreamHttpMethod": [ "Get" ]
    },
    {
      "DownstreamPathTemplate": "/api/values",
      "DownstreamScheme": "http",
      "DownstreamHostAndPorts": [
        {
          "Host": "localhost",
          "Port": 5002
        }
      ],
      "UpstreamPathTemplate": "/webapib/values",
      "UpstreamHttpMethod": [ "Get" ]
    },
    {
      "DownstreamPathTemplate": "/api/values/{id}",
      "DownstreamScheme": "http",
      "DownstreamHostAndPorts": [
        {
          "Host": "localhost",
          "Port": 5001
        }
      ],
      "UpstreamPathTemplate": "/WebApiA/values/{id}",
      "UpstreamHttpMethod": [ "Get" ],
      "ReRouteIsCaseSensitive": true
    },
    {
      "DownstreamPathTemplate": "/api/values/{id}",
      "DownstreamScheme": "http",
      "DownstreamHostAndPorts": [
        {
          "Host": "localhost",
          "Port": 5002
        }
      ],
      "UpstreamPathTemplate": "/WebApib/values/{id}",
      "UpstreamHttpMethod": [ "Get" ]
    },
    {
      "DownstreamPathTemplate": "/api/User/GetSex",
      "DownstreamScheme": "http",
      "DownstreamHostAndPorts": [
        {
          "Host": "localhost",
          "Port": 5001
        }
      ],
      "UpstreamPathTemplate": "/Sex",
      "UpstreamHttpMethod": [ "Get" ],
      "Key": "Sex"
    },
    {
      "DownstreamPathTemplate": "/api/User/GetAge",
      "DownstreamScheme": "http",
      "DownstreamHostAndPorts": [
        {
          "Host": "localhost",
          "Port": 5001
        }
      ],
      "UpstreamPathTemplate": "/Age",
      "UpstreamHttpMethod": [ "Get" ],
      "Key": "Age"
    },
    {
      "DownstreamPathTemplate": "/api/User/GetID",
      "DownstreamScheme": "http",
      "DownstreamHostAndPorts": [
        {
          "Host": "localhost",
          "Port": 5001
        }
      ],
      "UpstreamPathTemplate": "/ID",
      "UpstreamHttpMethod": [ "Get" ],
      "Key": "ID"
    },
    {
      "DownstreamPathTemplate": "/api/Counter/Count",
      "DownstreamScheme": "http",
      "UpstreamPathTemplate": "/count",
      "UpstreamHttpMethod": [ "Get" ],
      "ServiceName": "Count",
      "LoadBalancer": "RoundRobin",
      "UseServiceDiscovery": true
    }
  ]}`

**Comment by chenzhe014** [comment]
Do i miss anything?

**Comment by chenzhe014** [comment]
If i store configuration in consul,did i need add `Ocelot.json`  in `Startup.cs`?

**Comment by TomPallister** [comment]
@chenzhe014 I think you need to add the service discovery information into the configuration. See the docs [here](http://ocelot.readthedocs.io/en/latest/features/configuration.html#store-configuration-in-consul) 

e.g. 
```
"GlobalConfiguration": {
    "ServiceDiscoveryProvider": {
        "Host": "localhost",
        "Port": 9500
    }
}
```

Ocelot get's it initial configuration from json and then starts using Consul. I think this might be why it doesn't work. Can you let me know if this fixes the problem? 

If it does I might need to improve the user experience here.

**Comment by Stronhold** [comment]
Yes, you need to add `Ocelot.json` in `Startup.cs`. I think that is the problem, as @TomPallister said. Moreover, remember that if you do not specify ConfigurationKey, ocelot will use as key `InternalConfiguration`

**Comment by chenzhe014** [comment]
i try add `Ocelot.json` in `Startup.cs`

```
services.AddOcelot(new ConfigurationBuilder()
                .AddJsonFile("Ocelot.json", optional: false, reloadOnChange: true)
                .AddEnvironmentVariables()
                .Build()).AddStoreOcelotConfigurationInConsul();
```
it is still 404 ..

then i alert `Program.cs`

```
public static IWebHost BuildWebHost(string[] args) =>
                WebHost.CreateDefaultBuilder(args).ConfigureAppConfiguration((builderContext, config) =>
                {
                    config.AddJsonFile("Ocelot.json", optional: false, reloadOnChange: true);
                })
                .UseStartup<Startup>()
                .Build();
```
it is still 404 ..

How should I add..

**Comment by TomPallister** [comment]
@chenzhe014 have you added your service discovery configuration to Ocelot.json and your consul json?

**Comment by TomPallister** [comment]
@chenzhe014 in your ocelot.json you just need this. The configuration key is whatever you specified in for the Ocelot configuration in Consul.

```
"GlobalConfiguration": {
    "ServiceDiscoveryProvider": {
        "Host": "localhost",
        "Port": 9500,
         "ConfigurationKey": "XXXX"
    }
}
```

Remove below from Startup.cs but keep your entry in Program.cs

```
                .AddJsonFile("Ocelot.json", optional: false, reloadOnChange: true)
```

Now you should have configuration to start Ocelot. When Ocelot starts it will look up your configuration by ConfigurationKey in Consul.

You configuration in Consul must contain the following configuration...{Add Re ReRoutes Here} is just a place holder.

```
"ReRoutes": [{Add Re ReRoutes Here}],
"GlobalConfiguration": {
    "ServiceDiscoveryProvider": {
        "Host": "localhost",
        "Port": 9500,
         "ConfigurationKey": "XXXX"
    }
}
```

Let me know if you need more help! 😄

**Comment by TomPallister** [comment]
@chenzhe014 I will take a look ASAP :)

**Comment by TomPallister** [comment]
@chenzhe014 you need to have 

```json
"ServiceDiscoveryProvider": { "Host": "localhost", "Port": 8500, "ConfigurationKey": "Oceolot" }
```

in your ocelot.json otherwise Ocelot doesn't know which key to use to get the configuration from Consul. Give that a try and let me know if anything changes?

If it doesnt I will look again.

**Comment by chenzhe014** [comment]
@TomPallister Thank you for your reply.
 I'm sorry. the `README.md` is previous version. I forgot to update it .  I delete ConfigurationKey in json  and the key of configuration from Consul is default `InternalConfiguration`,In the latest version.

**Comment by TomPallister** [comment]
@chenzhe014 please can you push those changes to that repo so I can see exactly what you are testing with!

**Comment by chenzhe014** [comment]
@TomPallister I give up storing the configuration in consul. i change configuration during runtime via an authenticated HTTP API successfully . this is more quickly. 
in this issue,i add my demo to Ocelot Source Code for debug and i find it can get the configuration successfully.  I can't find a reason for 404  so far and i don't  want to continue  . my ability is limited,
but i will continue studying Ocelot.  Thanks for your help again !

**Comment by TomPallister** [comment]
@chenzhe014 OK I'm glad you were able to solve your problem.

I'm sure it would have been something small that was causing your problems! Good luck in the future :)

**Comment by samsiu2014** [comment]
@chenzhe014 I would like to ask did your changes saved to the local "Ocelotconfiguration".json?
I followed every steps on the ocelot documents but the configuration json is cached.

**Comment by chenzhe014** [comment]
@samsiu2014 i find in debug environment,it is  changed in `Ocelotconfiguration.Development.json` . if you publish your application,it is changed in 'Ocelotconfiguration.Production.json'

**Comment by chenzhe014** [comment]
@samsiu2014 maybe you would follow the [doc](http://ocelot.readthedocs.io/en/latest/features/configuration.html#multiple-environments).
`.AddJsonFile($"configuration.{hostingContext.HostingEnvironment.EnvironmentName}.json")`

**Comment by samsiu2014** [comment]
@chenzhe014 Thanks for your reply!
After I changed the configuration during runtime via an authenticated HTTP API. The new values would not reflect in the "Ocelot.json". If I try to restart the API Gateway, the previous settings will be applied in instead of the modified one.

**Comment by samsiu2014** [comment]
@TomPallister Thank you so much! However, does the administration API work on "DownstreamHostAndPorts"? It didn't have any effects if i only modified the port number.

**Comment by TomPallister** [comment]
@samsiu2014 there was a bug with that until recently! What version of Ocelot are you using?

**Comment by samsiu2014** [comment]
@TomPallister 7.0.5! Then, i just need to wait the new release right? Thanks!

**Comment by TomPallister** [comment]
@samsiu2014 I think it was fixed in 7.0.6!

Install-Package Ocelot -Version 7.0.6

For that a go!

**Comment by samsiu2014** [comment]
@TomPallister It works! Thanks a lot!

**Comment by TomPallister** [comment]
@samsiu2014 no worries!

**Comment by shubham0990** [comment]
how can i update downstreampath and upstreampath of configuration.json file

**Comment by shubham0990** [comment]
how can i update downstreampath and upstreampath of configuration.json file with the help of angular

**Comment by shubham0990** [comment]
how can i update upstreampath and downstreampath of ocelot configuration.json file

**Comment by WeihanLi** [comment]
you may need [this](https://www.cnblogs.com/weihanli/p/reload-ocelot-configuration.html) @shubham0990 

sample here:

``` csharp
            // PUT /ocelot/admin/configuration
            app.Map(new PathString("/ocelot/admin/configuration"), appBuilder =>
            {
                appBuilder.Use(async (context, next) =>
                {
                    if (context.Request.Method.ToUpper() != "PUT")
                    {
                        context.Response.StatusCode = 404;
                        return;
                    }
                    var authenticateResult = await context.AuthenticateAsync(AuthenticationProviderKey);
                    if (!authenticateResult.Succeeded)
                    {
                        context.Response.StatusCode = 401;
                        return;
                    }
                    if (authenticateResult.Principal.IsInRole("Admin"))
                    {
                        var configurationRepo =
                            context.RequestServices.GetRequiredService<IFileConfigurationRepository>();
                        var ocelotConfiguration = await configurationRepo.Get();
                        var logger = context.RequestServices.GetRequiredService<ILoggerFactory>().CreateLogger("OcelotConfiguration");
                        if (!ocelotConfiguration.IsError)
                        {
                            var internalConfigurationRepo = context.RequestServices.GetRequiredService<IInternalConfigurationRepository>();
                            var internalConfigurationCreator =
                                context.RequestServices.GetRequiredService<IInternalConfigurationCreator>();
                            var internalConfiguration = await internalConfigurationCreator.Create(ocelotConfiguration.Data);
                            if (!internalConfiguration.IsError)
                            {
                                internalConfigurationRepo.AddOrReplace(internalConfiguration.Data);
                                context.Response.StatusCode = 200;
                                return;
                            }
                            else
                            {
                                logger.LogError($"update ocelot configuration error, error in create ocelot internal configuration, error messages:{string.Join(", ", ocelotConfiguration.Errors)}");
                            }
                        }
                        else
                        {
                            logger.LogError($"update ocelot configuration error, error in get ocelot configuration from configurationRepo, error messages:{string.Join(", ", ocelotConfiguration.Errors)}");
                        }
                        context.Response.StatusCode = 500;
                    }
                    else
                    {
                        context.Response.StatusCode = 403;
                    }
                });
            });
```
