### ISSUE TITLE
Open API support?

### ISSUE THREAD

**Issue by SbiCA** [ThreeMammals/Ocelot#397]
##  New Feature
Does ocelot support Open API (a.k.a Swagger)? 

## Motivation for New Feautre
- client code generation 
- service description 
- api documentation

**Comment by TomPallister** [comment]
@SbiCA thanks for your interest in the project! No Ocelot does not support this...please see the docs [here](https://ocelot.readthedocs.io/en/latest/introduction/notsupported.html?highlight=swagger) for more information!
