### ISSUE TITLE
Can Ocelot ReRoute by request parameter ?

### ISSUE THREAD

**Issue by chenzhe014** [ThreeMammals/Ocelot#402]
for example 
 UpStreamPath:`/api/web?method=a` reroute to Downstream `/apiA/web`.
 UpStreamPath:`/api/web?method=b` reroute to Downstream `/apiB/web`.

**Comment by TomPallister** [comment]
@chenzhe014 thanks for your interest in the project. This does not  work at the moment. This feature has already been requested in #382 so I will close this issue a duplicate. Please check that issue for updates.
