### ISSUE TITLE
404 Causing request to try again and again until timing out

### ISSUE THREAD

**Issue by jwyglendowski-precisionlender** [ThreeMammals/Ocelot#409]
When my downstream dotnet core 2.0 MVC service running in service fabric returns a 404 the request keep trying again and again until the upstream service timeouts out with a 504. If I have the same service return back a 403 it returns back without issue. I am running Ocelot 7.0.5 in dotnet core 2.0 project. 

My guess is that Ocelot is automatically retrying the request but I have no empirical evidence to proof it at the moment. I have logging turned on the debug and higher but I am not getting any information that could explain the situation.

To reproduce the issue download the latest Service Fabric sample open up the Values Controller in OcelotApplicationService Controller and change the get method to the following.

`     
     // GET api/values
     [HttpGet]
     public IActionResult Get()
     {
          return NotFound();
          //return new string[] { "value1", "value2" };
     }
`

Put a break point in that method deploy the code to SF and then debug it the service and execute that piece of code using postman or even just your browser and you will see what I mean.

It looks like you should be able to return a 404 without this behaviour. I found an article on microsoft's blog showing just the same situation. 

https://blogs.msdn.microsoft.com/cesardelatorre/2018/05/15/designing-and-implementing-api-gateways-with-ocelot-in-a-microservices-and-container-based-architecture/ 

Any assistance would be appreciated.

Kind Regards,

Jason Wyglendowski

**Comment by TomPallister** [comment]
@jwyglendowski-precisionlender thanks for your interest in the project. Ocelot only retries on transient errors if the user has configured it. It won’t retry on 404.

I will take a look at this ASAP and let you know if I work anything out. 

I am confused by the post of the Microsoft article as that does not mention this situation? It is just about using Ocelot.

**Comment by jwyglendowski-precisionlender** [comment]
@TomPallister Sorry if I wasn't clear about the MS article. What I was just trying to say that they were not trying to avoid 404 errors and there isn't any special handling for them. It seems strange though that the behaviour is always with 404s.

**Comment by jwyglendowski-precisionlender** [comment]
@TomPallister It might be service fabric itself with the issue. Looks like there needs to be a special header added on the service end. I am going to test that out.

X-ServiceFabric : ResourceNotFound

https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-reverseproxy

**Comment by jwyglendowski-precisionlender** [comment]
@TomPallister **That was it.** I will probably just create a simple middleware on the Service Side to handle the situation. Which makes perfect sense because all the references I found were not related to SF. Maybe I can put in PR for documentation on Service Fabric.

**Comment by TomPallister** [comment]
@jwyglendowski-precisionlender I would really appreciate a PR for this! ServiceFabric is a minefield ;(
