### ISSUE TITLE
Investigate RuntimeFrameworkVersion in csproj do we need this?

### ISSUE THREAD

**Issue by TomPallister** [ThreeMammals/Ocelot#414]
## Expected Behavior / New Feature

Investigate RuntimeFrameworkVersion in csproj do we need this? https://docs.microsoft.com/en-us/dotnet/core/tools/csproj

## Actual Behavior / Motivation for New Feautre

Seems pointless to have in file unless we need it

## Steps to Reproduce the Problem

  1. Remove from csproj files
  1. Test build process

## Specifications

  - Version:
  - Platform:
  - Subsystem:

**Comment by TomPallister** [comment]
we do

**Comment by bergmeister** [comment]
@TomPallister I was wondering the same. Can you elaborate please? As far as I understand it could only be useful to require a minimum version. If a newer version is available, it will use the newer version anyway (with or without RuntimeFrameworkVersion )

**Comment by TomPallister** [comment]
@bergmeister interesting where did you learn that?

I just removed it and if I remember correctly I had problems with system.runtime dlls after that so gave up for now.
