### ISSUE TITLE
BaseUrl always http://localhost:5000

### ISSUE THREAD

**Issue by danpdc** [ThreeMammals/Ocelot#417]
## Expected Behavior
I have configured a basic API gateway using Ocelot 7.0.5 and everything seems to work fine, except replacing headers with the BaseUrl. Here is a sample from my ocelot.json file: 

```
{
      "DownstreamPathTemplate": "/api/v1/todo/",
      "DownstreamScheme": "http",
      "UpstreamPathTemplate": "/api/v1/todo/",
      "UpstreamHttpMethod": [ "Get", "Post" ],
      "DownstreamHostAndPorts": [
        {
          "Host": "someapp.azurewebsites.net/",
          "Port": 80
        }

      ],
      "DownstreamHeaderTransform": {
        "Location": "{DownstreamBaseUrl}, {BaseUrl}"
      }

    }
  ],
  "GlobalConfiguration": {
    "BaseUrl": "http://anotherapp.azurewebsites.net"
  }
```
When I am doing a request for which the downstream API also specifies a location header, I would expect to see the configured BaseUrl + the path. 

## Actual Behavior / Motivation for New Feautre
Instead, I always get http://localhost:5000 as host. 

![image](https://user-images.githubusercontent.com/16518928/41603213-30cd7828-73e5-11e8-8072-3a7b7decb152.png)

If I remove the "DownstreamHeaderTransform" configuration I receive the downstream API host + path, which is expected

## Steps to Reproduce the Problem

  1. Basic Ocelot Configuration as per documentation
  1. Add DownstreamHeaderTransform

## Specifications

  - Version: Ocelot 7.0.5
  - Platform: ASP.Net Core 2.0

Any idea what is not working as expected?

**Comment by TomPallister** [comment]
@danpdc what url are you actually running Ocelot under? I guess it is localhost:5000? I will take a look and let you know ASAP!

**Comment by danpdc** [comment]
@TomPallister locally I am running it under localhost:58422
I also deployed it to Azure and there I receive the same localhost:5000 when I do the header transform.

**Comment by TomPallister** [comment]
@danpdc thanks for the info I will look ASAP! Sorry I have limited time to work on Ocelot :(

**Comment by TomPallister** [comment]
@danpdc if I run

```
curl -i http://lxtodo.azurewebsites.net/api/v1/todo
```

I get 
```
HTTP/1.1 200 OK
Transfer-Encoding: chunked
Content-Type: application/json; charset=utf-8
Server: Kestrel
X-Powered-By: ASP.NET
Set-Cookie: ARRAffinity=ddde1483dd251c55ce6f0ac2f66f516b197e4a18cc770f85bb239fffc321f328;Path=/;HttpOnly;Domain=lxtodo.azurewebsites.net
Date: Wed, 20 Jun 2018 19:35:01 GMT

[{"id":1,"title":"Test item","description":"Initial test ToDo item"},{"id":2,"title":"Interview","description":".Net developer interview"},{"id":3,"title":"Interview","description":".Net developer interview"},{"id":4,"title":"Interview","description":".Net developer interview"},{"id":5,"title":"Interview","description":".Net developer interview"},{"id":6,"title":"Interview","description":".Net developer interview"},{"id":7,"title":"Interview","description":".Net developer interview"},{"id":8,"title":"Interview","description":".Net developer interview"},{"id":9,"title":"Interview","description":".Net developer interview"},{"id":10,"title":"Interview","description":".Net developer interview"},{"id":11,"title":"Interview","description":".Net developer interview"},{"id":12,"title":"Interview","description":".Net developer interview"},{"id":13,"title":"Interview","description":".Net developer interview"},{"id":14,"title":"Interview","description":".Net developer interview"},{"id":15,"title":"Interview","description":".Net developer interview"},{"id":16,"title":"Interview","description":".Net developer interview"},{"id":17,"title":"Interview","description":".Net developer interview"},{"id":18,"title":"Interview","description":".Net developer interview"},{"id":19,"title":"Interview","description":".Net developer interview"},{"id":20,"title":"Interview","description":".Net developer interview"},{"id":21,"title":"Interview","description":".Net developer interview"},{"id":22,"title":"Interview","description":".Net developer interview"},{"id":23,"title":"Interview","description":".Net developer interview"},{"id":24,"title":"Interview","description":".Net developer interview"},{"id":25,"title":"Interview","description":".Net developer interview"},{"id":26,"title":"Interview","description":".Net developer interview"},{"id":27,"title":"Interview","description":".Net developer interview"},{"id":28,"title":"Interview","description":".Net developer interview"},{"id":29,"title":"Interview","description":".Net developer interview"},{"id":30,"title":"Interview","description":".Net developer interview"},{"id":31,"title":"Interview","description":".Net developer interview"},{"id":32,"title":"Interview","description":".Net developer interview"},{"id":33,"title":"Interview","description":".Net developer interview"},{"id":34,"title":"Interview","description":".Net developer interview"},{"id":35,"title":"Interview","description":".Net developer interview"}]
```

It looks like your service doesnt return a location header so this functionality won't work. I'm not sure if your service just isn't configured right at the moment? If it isn't would you be able to add the location header.

I then took your example to see if Ocelot was adding a Location header for some reason with your config but got the following headers back

```
HTTP/1.1 200 OK
Date: Wed, 20 Jun 2018 19:42:54 GMT
Content-Type: application/json; charset=utf-8
Server: Kestrel
Content-Length: 2475
Set-Cookie: ARRAffinity=ddde1483dd251c55ce6f0ac2f66f516b197e4a18cc770f85bb239fffc321f328;Path=/;HttpOnly;Domain=lxtodo.azurewebsites.net
X-Powered-By: ASP.NET
```

It doesn't appear to return a Location header either so I can't go forward with this until you get back to me re the Location header!

**Comment by danpdc** [comment]
There is an endpoint that returns a location header. Sorry for forgetting to mention it from the first time. 
To get a location header one needs to make a Post request to lxtodo.azurewebsites.net/api/v1/todo with a json body like { "title": "something", "description": "something" }. The response will be 201 Created which inclues a location header. 

As a workaround for now I've added a custom middleware that subscribes to httpResponse.OnStarting and replaces the host in the location header with what the host really is.  So no hurry. 
Thank you very much for looking into this I really appreciate that.

**Comment by TomPallister** [comment]
@danpdc sorry this has taken me so long to look at! Been very busy :)

So I set up the config as below and everything worked fine...

```json
{
  "ReRoutes": [
    {
      "DownstreamPathTemplate": "/api/v1/todo/",
      "DownstreamScheme": "http",
      "UpstreamPathTemplate": "/api/v1/todo/",
      "UpstreamHttpMethod": [ "Get", "Post" ],
      "DownstreamHostAndPorts": [
        {
          "Host": "lxtodo.azurewebsites.net",
          "Port": 80
        }
    
      ],
      "DownstreamHeaderTransform": {
        "Location": "{DownstreamBaseUrl}, {BaseUrl}"
      }
    }
  ],
  "GlobalConfiguration": {
    "BaseUrl": "http://anotherapp.azurewebsites.net"
  }
}
```

Can you give it a try and let me know if the Location header works as expected? I think your original json config had a few issues!

**Comment by RobKraft** [comment]
I have the same problem.  I can't seem to get my deployed site to listen on anything other than Localhost:5000.  My design is that I expect apps calling my REST api to first hit our ocelot gateway and it will reroute to the correct paths in our actual API.  It works on my local machine, but not when I deploy to our servers.  My config looks like this:
{
  "ReRoutes": [
    {
      "DownstreamPathTemplate": "/20/lucitywebrestapi/{all}", //Launching with Docker only seems to work on the deployed site
      "DownstreamScheme": "http",
      "DownstreamHostAndPorts": [
        {
          "Host": "lct-tlb-01",
          "Port": 80
        }
      ],

      "UpstreamPathTemplate": "/{all}",
      "UpstreamHttpMethod": [ "Get", "Post", "Put", "Options" ]
    }

  ],
  "GlobalConfiguration": {
    "BaseUrl": "http://lct-tlb-01/20/LucityAPIGateway/"
  }

}

**Comment by RobKraft** [comment]
For the record here, I got this resolved.  First, after finding an issue mentioned in ASP.Net Core - but the better fix is further below.  Here was my first fix:
`            new WebHostBuilder()
                .UseContentRoot(Directory.GetCurrentDirectory())
                .UseKestrel()
                .UseIIS()
                .UseIISIntegration()
                //I added this configure services after finding this issue reported in asp.net:
                //https://github.com/aspnet/KestrelHttpServer/issues/2760
                //Another place hinted that UseKestrel should go before UseIIS
                .ConfigureServices(services => {
                    services.Configure<KestrelServerOptions>(options =>
                    {
                        // ...
                    });
                })

**Comment by RobKraft** [comment]
Then I changed the entire start of my app to this:
```
        public static void Main(string[] args)
        {
            CreateWebHostBuilder(args).Build().Run();
        }
        public static IWebHostBuilder CreateWebHostBuilder(string[] args) =>
            WebHost.CreateDefaultBuilder(args)
                .UseContentRoot(Directory.GetCurrentDirectory())
                .ConfigureAppConfiguration((hostingContext, config) =>
                {
                    config
                        .SetBasePath(hostingContext.HostingEnvironment.ContentRootPath)
                        .AddJsonFile("appsettings.json", true, true)
                        .AddJsonFile($"appsettings.{hostingContext.HostingEnvironment.EnvironmentName}.json", true, true)
                        .AddJsonFile("ocelot.json")
                        .AddEnvironmentVariables();
                })
               .ConfigureLogging((hostingContext, logging) =>
               {
                   //TODO - Add logging
                   logging.AddConsole();
               })
               .UseStartup<Startup>();
    }
```

**Comment by pacifyin** [comment]
Ocelot Admin Still Localhost:5000 Can Not Change It. BUG. si SO SO SO.

**Comment by TheoGrimond** [comment]
Hi @TomPallister, I believe this issue is still opened. 

I followed the tutorial material from the Docs but my server still always listens to **http://localhost:5000** even though I properly set the **_GlobalConfiguration:BaseUrl_** parameter in my **ocelot.json**.

I tried this against 2 Ocelot versions, one running with .Net 3.1 and the other running .Net 5.0 
Both were having the same issue
