### ISSUE TITLE
Incorrect routing when UpstreamHost is specified and UpstreamHttpMethod is empty

### ISSUE THREAD

**Issue by davidni** [ThreeMammals/Ocelot#419]
## Expected Behavior
When a reroute rule specifies `UpstreamHost`, it should only match requests with that host name. There's a bug where this check is ignored if the rule has an empty or null `UpstreamHttpMethod`

## Actual Behavior
`UpstreamHost` is ignored

## Specifications

  - Version: 7.0.5
  - Platform: all

I will submit a PR shortly that addresses this.

**Comment by TomPallister** [comment]
@davidni at first glance I agree! This looks good. Let me double check by pulling your code and seeing if I get a failing test!

**Comment by davidni** [comment]
Please double check, thanks. FWIW, I added a test and confirmed it fails before my changes and passes after.

**Comment by TomPallister** [comment]
@davidni really appreciate your help! Thanks 😄

**Comment by TomPallister** [comment]
Released in 7.0.6
