### ISSUE TITLE
Feature: Support arbitrary downstream endpoints

### ISSUE THREAD

**Issue by davidni** [ThreeMammals/Ocelot#423]
The Ocelot config schema today only really works for http(s) endpoints. I'd like to be able to write my downstream endpoint as a `fabric:/` uri, which would then be dynamically resolved by a custom `IHttpRequester` at the end of the pipeline.

## Motivation for New Feature
Ocelot cannot dynamically resolve Service Fabric endpoints today (instead, it relies on SF Reverse Proxy, which adds an unnecessary hop). My proposal is a change in Ocelot that would enable me to build a custom `IHttpRequester` in my application (not a part of Ocelot) to dynamically resolve `fabric:/` uri's and issue the appropriate request.

## Proposal
The limitation today is how `DownstreamScheme` and `DownstreamHostAndPorts` are specified in `ReRoutes`:

```json
"DownstreamScheme": "http",
"DownstreamHostAndPorts": [
  {
    "Host": "localhost",
    "Port": 80,
  }
]
```

which forces me to specify `Host` and `Port`, which only really make sense for http(s). My proposal is for Ocelot to support the following instead:

```json
"DownstreamEndpoints": [
    "http://localhost:80",
    "fabric:/MyApp/MyService"
]
```

## Benefits:
  * Convenient way to specify arbitrary downstream endpoints: `http`, `https`, or anything else, and even to mix them in a single ReRoute rule
  * Less verbose configs
  * Can be built backwards-compatible. Old config syntax `DownstreamScheme + DownstreamHostAndPorts` would still be accepted and parsed into the new model during init

Thoughts?

**Comment by TomPallister** [comment]
@davidni you don’t have to specify host and port for service fabric services. Please see docs http://ocelot.readthedocs.io/en/latest/features/servicefabric.html

**Comment by davidni** [comment]
Not quite. There are 3 common ways to reach Service Fabric services in a cluster:
  1. **Use SF Reverse Proxy explicitly** (default is on port 19081): make an HTTP request to http://localhost:19081/app1/service1/path
  2. **Use SF DNS Service:** make an HTTP request to http://service1.app1:8080/path which will resolve to the IP of a replica of the requested service. Downside is this can't do port resolution since DNS operates at the host name level
  3. **Explicit name resolution with SF Naming Service:** C# code calls `IServicePartitionResolver.ResolveAsync()` to resolve the address of a service, then issues a call directly to it

Ocelot today uses (1). My proposal would enable me to do (3), which gives applications much finer grained control over endpoint resolution policies, retry loops, customized timeouts for each phase of the process, additional telemetry, etc.

The following articles might be helpful:
  * [Connect and communicate with services in Service Fabric](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-connect-and-communicate-with-services)
  * [DNS Service in Azure Service Fabric](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-dnsservice)

**Comment by TomPallister** [comment]
@davidni thanks for more information. I’m happy to go with 3 as it has the most benefit for ServiceFabric users. 

What is your solution at the moment? How would you envision doing this feature?

**Comment by davidni** [comment]
For now I am replacing Ocelot's `IHttpRequester` implementation with a custom class in my application. DI then injects my implementation into Ocelot's Middleware, and I issue the request myself using custom name resolution.

This has a few problems:
  * I am hijacking the entire pipeline to **only** issue Service Fabric service requests. I can't currently have a different route that would just issue a simple HTTP request with Ocelot's built-in `HttpRequester`. That's fine for my application, but probably not a good general assumption
  * Routing config overhead -- in order for the LoadBalancer middlewares to not complain, I am forced to specify a dummy `DownstreamHostAndPorts` for each of my ReRoutes. I literally have the following now:
    ```json
    "DownstreamHostAndPorts": [
      {
        "_description": "These are ignored -- endpoint will be dynamically resolved",
        "Host": "localhost",
        "Port": 1
      }
    ]
    ```

My custom `IHttpRequester` adjusts the outgoing request with the proper hostname and port before issuing the request.

**Comment by TomPallister** [comment]
@davidni awesome thanks for this info! It really helps me out because I am not a ServiceFabric expert at all!! Could you share the custom IHttpRequester? I guess I would just do what I've done for all the other Ocelot things that need a different implementation and use a factory to get the ServiceFabricRequester depending on how the ReRoute is configured.

**Comment by TomPallister** [comment]
@davidni would you be able to share your custom IHttpRequester?

**Comment by davidni** [comment]
There's too much other code involved in my http outgoing request pipeline that I cannot easily strip out, sorry.

That said, my current course of action is to stay with Ocelot's existing model (1) **Use SF Reverse Proxy explicitly**. If I hit any blockers or insurmountable challenges I will revisit, but for now feel free to close this as it doesn't seem like it will be necessary and I am not actively working on it.

Thanks

**Comment by TomPallister** [comment]
@davidni OK cool, maybe we will come back to this one day :)
