### ISSUE TITLE
Ocelot and FIPS

### ISSUE THREAD

**Issue by vramanx** [ThreeMammals/Ocelot#429]
I tried to find information around this. but could not find it. How do i enable FIPS 140.2 compliant SSL offloading in Ocelot? We want to run ocelot on windows containers

**Comment by TomPallister** [comment]
@vramanx Ocelot is not really designed to offload SSL. I would recommend doing this with an appliance designed for that role.

Ocelot can receive a request on HTTPS and then make a subsequent request on HTTP. It does this by the user configuring http for their request to the service. I have no idea if this is FIPS compliant, I guess you can turn FIPS mode on in Windows and see if it still works? Ocelot just uses standard .NET framework for TLS stuff and I have no specific code around it.

Sorry to not be much help, unfortunately I am not a FIPS expert.

**Comment by vramanx** [comment]
@TomPallister - from what i understand, it depends on the openssl version. if .net core can be configured to use the right openssl version - then we should be good. but i have no clue on what that means. I will try it out.

For the second part from your post - Ocelot will terminate SSL and call the microservice endpoint on http or https. Is that right understanding?

**Comment by TomPallister** [comment]
@vramanx yes correct Ocelot can receive HTTPs and proxy on HTTP. I guess this is terminating SSL!
