### ISSUE TITLE
Best practice for logging?

### ISSUE THREAD

**Issue by Rwing** [ThreeMammals/Ocelot#430]
I noticed that will get terrible performance if logging to console via [docs](http://ocelot.readthedocs.io/en/latest/features/logging.html), so what the best practice fro logging in ocelot ?

**Comment by wayne-o** [comment]
I would have thought that anything that doesn't block the execution of the application would be good - anything that logs loads to console is going to slow down - not just ocelot :)

**Comment by TomPallister** [comment]
@Rwing Ocelot uses standard .net core logging framework so anything that integrates with that will work fine. See the docs https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-2.1&tabs=aspnetcore2x

Hope that helps!

**Comment by Rwing** [comment]
@wayne-o @TomPallister  Okay  gotcha, so according to your experience, what about best practice for logging in .net core ? thank you.

**Comment by TomPallister** [comment]
@Rwing imo if you are using Windows write to event viewer and have something pull the logs from event viewer and use the ELK stack to push the logs to ElasticSearch and then view them in Kibana.

If you are using Linux use containers and write the logs into a container and again push them into an ELK stack. 

All I would say is never push them to a relational database as this will cause you various problems.

**Comment by wayne-o** [comment]
serilog has an ELK appender
