### ISSUE TITLE
对于静态文件是否可以提供其他的缓存方式。

### ISSUE THREAD

**Issue by guoming** [ThreeMammals/Ocelot#432]
## Steps to Reproduce the Problem

  1.
  1.
  1.

## Specifications

  - Version:
  - Platform:
  - Subsystem:

**Comment by TomPallister** [comment]
Google translate this to 

For static files can provide other ways to cache.

I don't know what it means though! Maybe someone who speaks Chinese can help? 😄

**Comment by chenzhe014** [comment]
静态文件是指Ocelot.json吗？

**Comment by guoming** [comment]
![image](https://user-images.githubusercontent.com/13638177/42012406-8d9d98a8-7aca-11e8-8c40-e3b6ee19dc0a.png)
今天发现另外一个问题，对于后端的请求如果返回304 Not Modified 状态，Ocelot 会出现303 See Other状态，这时候浏览器显示就出白屏。

**Comment by SnailDev** [comment]
@guoming 你好，能给个还原的步骤，或者示例项目出来吗？ 另，web 项目没有必要走api网关哦，直接走代理服务器就可以了。

**Comment by TomPallister** [comment]
@guoming I am very sorry I do not understand the problem and have become confused!

Please could you upload source code showing the problem and I will be able to investigate further & reopen the issue! 😄
