### ISSUE TITLE
install-package ocelot failed!

### ISSUE THREAD

**Issue by zjlhope** [ThreeMammals/Ocelot#434]
I create a asp.net core empty project with vs2017 which is based on .net core 2.0.
when I try to install the ocelot with nuget tool ,it failed with the error ' install-package : NU1108: 检测到循环。 
  ocelot -> ocelot (>= 7.0.6).'

why?

**Comment by TomPallister** [comment]
@zjlhope thanks for your interest in Ocelot! 😄 

I do not have the same problem as you. I have created a clean Ocelot project with version 7.0.6 [here](https://github.com/TomPallister/TestOcelotInstall) using vs2017. I suggest trying to use this project as the basis for what you are doing.

Hope that helps.

**Comment by zjlhope** [comment]
@TomPallister  thanks for your reply.
I known what you say,when It‘s an .net core console project ,I can install it,but when it's an asp.net core empty project,I can't install it .All is based on .net core 2.0.

**Comment by TomPallister** [comment]
@zjlhope the project I have linked to uses the Empty ASP.NET core template in VS2017!

Could you upload the code that isn't working so I can have a look?

**Comment by zjlhope** [comment]
It's OK now!!
The project name can not be set ocelot!!
otherwise I can't work

**Comment by TomPallister** [comment]
@zjlhope that makes sense, if you call it Ocelot you will get namespace conflicts :)
