### ISSUE TITLE
#Http Status 303 See Other

### ISSUE THREAD

**Issue by guoming** [ThreeMammals/Ocelot#440]
## Expected Behavior / New Feature
304 Not Modified

## Actual Behavior / Motivation for New Feautre
303 See Other

## Steps to Reproduce the Problem

  1.
  1.
  1.

## Specifications

  - Version: 7.0.6
  - Platform: Linux
  - Subsystem: Nodejs

**Comment by TomPallister** [comment]
@guoming Sorry I cannot replicate this issue. I think there is a problem with your server that is returning 303 not 304. The only code that changes status codes in Ocelot is ErrorsToHttpStatusCodeMapper and that does not effect 303 or 304. I have added a test to show this working [here](https://github.com/ThreeMammals/Ocelot/pull/450)

Please can you upload source code showing the issue and I will be able to investigate further.
