### ISSUE TITLE
Pressure test  return 404 - Ocelot

### ISSUE THREAD

**Issue by magnificence-dream** [ThreeMammals/Ocelot#443]
hello  there

my situation:
    
  Pressure test  by  jemeter  ,80 users ,request 100 seconds,  At first it was normal. but sometimes,I  got many 404 

configuration:

"ReRoutes": [
		{
			"DownstreamPathTemplate": "/api/v1/hear-froms",
			"DownstreamScheme": "http",
			"UpstreamPathTemplate": "/api/v1/hear-froms",
			"UpstreamHttpMethod": [ "Get" ],
			"ServiceName": "Lunz.Microservice.WebApp",
			"LoadBalancer": "RoundRobin",
			"UseServiceDiscovery": true,
			"ReRouteIsCaseSensitive": false,
			"QoSOptions": {
				"ExceptionsAllowedBeforeBreaking": 3,
				"DurationOfBreak": 10,
				"TimeoutValue": 5000
			},
			"AuthenticationOptions": {
				"AuthenticationProviderKey": "default",
				"AllowedScopes": [ "lunz-sharp-template" ]
			}
		},

![1](https://user-images.githubusercontent.com/39826801/42077537-d4b456be-7bab-11e8-925c-bace2174a361.png)
![27](https://user-images.githubusercontent.com/39826801/42077539-d5db4408-7bab-11e8-9840-1a1ee7c41467.png)

Log:

[2018-06-29-all.log](https://github.com/ThreeMammals/Ocelot/files/2148097/2018-06-29-all.log)

Any assistance would be appreciated.

**Comment by TomPallister** [comment]
@magnificence-dream thanks for your interest in the project!!

Please could upload your source code for this test project? If you cannot do that then your program.cs / startup.cs and ocelot.json would help. 

Also if you could run the tests with some logging turned on (dont log to console) and paste the logs here that would help.

I have not seen this kind of behaviour before.

**Comment by magnificence-dream** [comment]
@TomPallister  thanks very much

here is the source code:
https://github.com/magnificence-dream/apigateway

the configuration is : configuration.Staging.json

**Comment by TomPallister** [comment]
@magnificence-dream I will look ASAP! thanks for this 😄

**Comment by TomPallister** [comment]
@magnificence-dream this is the next issue I will look at, sorry for the wait.

**Comment by TomPallister** [comment]
@magnificence-dream this is a very strange one!!

If you search the log for this message

There were no services in NoLoadBalancer errors found in ResponderMiddleware. Setting error response for request path:/api/v1/hear-froms, request method: GET 

These errors will return a 404 so that is probably the source of your problem. This means that Ocelot has identified your ReRoute for /api/v1/hear-froms as not needing as using no loadbalancer and not finding any services. This suggests either your service discovery provider has no services or it has defaulted to not using a service discovery provider. However this should not be possible as you specify use service discovery and the round robin load balancer.

After looking more this code might be causing the issue

```csharp
public async void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }

            app.ConfigureCors();

            app.UseStaticFiles();

            app.UseSwagger();

			app.UseMvc();

			await app.UseOcelot();
        }
```

It needs to be as the method cannot be async as far as im aware. I would try this and see if it makes a difference because Ocelot probably has not started properly.

```csharp
 public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }

            app.ConfigureCors();

            app.UseStaticFiles();

            app.UseSwagger();

			app.UseMvc();

			app.UseOcelot().Wait();
        }
```

**Comment by magnificence-dream** [comment]
Thanks @TomPallister for the information

I didn't use load balancing until I released it to the test.
I test again after modify the url to " /api/v1/hf" and then sometimes it's okay(no 404),
unfortunately, sometimes it's not

It's just the one place (modify the UpstreamPathTemplate )to change,is there any special logic for this

Thanks！

**Comment by TomPallister** [comment]
@magnificence-dream there is no special logic, you should not get random 404 errors. Please can you send me the logs while the performance tests are running?

**Comment by magnificence-dream** [comment]
@TomPallister  glad to  your reply~

I tested it with another interface. The problem is the same as before.

**100 users ,request 100 seconds:**
![1](https://user-images.githubusercontent.com/39826801/42668264-527eafbe-8682-11e8-8986-007edd784438.png)

**request url:**
![2](https://user-images.githubusercontent.com/39826801/42668280-5f4f7c96-8682-11e8-8f54-c2a500d90b2b.png)

**confifuration.Staging.json:**
![3](https://user-images.githubusercontent.com/39826801/42668284-68b26956-8682-11e8-9c5d-c6fe8b70b4be.png)

**performance tests result:**
![4](https://user-images.githubusercontent.com/39826801/42668299-762fc934-8682-11e8-888e-ee34ff4c9a64.png)

![5](https://user-images.githubusercontent.com/39826801/42668324-9562993a-8682-11e8-862b-57b55d80e735.png)

**the logfile:**
  https://github.com/magnificence-dream/apigateway



**Retest as follows:**
mofity the url to "/api/v1/hf/{id}",everything else is the same as "/api/v1/hear-from/{id}"

![06](https://user-images.githubusercontent.com/39826801/42668334-a206fc76-8682-11e8-9d8a-97fe50e005c5.png)
![07](https://user-images.githubusercontent.com/39826801/42668355-be01d7d4-8682-11e8-936c-0a3697362c60.png)


I tested it five times in a row,and it was all good
![08](https://user-images.githubusercontent.com/39826801/42668360-c5c84d2c-8682-11e8-9d47-1aecd190d0a3.png)


if i change it back,it's not good again.

**Comment by TomPallister** [comment]
@magnificence-dream very strange I will again ASAP!

**Comment by TomPallister** [comment]
@magnificence-dream it looks like Ocelot doesnt think there are any services available hence the 404...the log example is below.

```2018-07-13 09:09:57.8836||WARN|Ocelot.LoadBalancer.Middleware.LoadBalancingMiddleware|requestId: 0HLF8B81520JR:00000024, previousRequestId: no previous request id, message: There were no services in NoLoadBalancer ```

Either there is a bug in Ocelot where it can break under load, your services have de-registered with Consul, there is a problem calling Consul. It might be a problem calling Consul, from your config it looks like you are not using a Consul agent as a sidecar so the performance might not be great.

The first thing I would suggest doing is get Ocelot version 8.0.0 (there might be a problem with 8.0.1) and set pollconsul as your ServiceDiscoveryProvider e.g.

```json
                "ServiceDiscoveryProvider": {
			"Host": "consul.m.lunztech.cn",
			"Port": 80,
                         "Type": "pollconsul"
		},
```

Then let me know if this makes a difference?

**Comment by TomPallister** [comment]
I will close this for now, let me know if you want to reopen it.
