### ISSUE TITLE
Caching documentation broken

### ISSUE THREAD

**Issue by fleed** [ThreeMammals/Ocelot#453]
The documentation for the caching is broken (external links are not working).
Without the example, it is hard to get it working (it is not clear if caching is enabled by default of if services should be configured to support it).

Documentation revision: `85efcf07`

**Comment by TomPallister** [comment]
@fleed it is not enabled by default! I will take a look at the docs and fix them.

If you look [here](https://github.com/ThreeMammals/Ocelot/blob/develop/test/Ocelot.ManualTest/Program.cs) and the lines 

```csharp
                    s.AddOcelot()
                        .AddCacheManager(x =>
                        {
                            x.WithDictionaryHandle();
                        });
```

Would add cacheing to the project.

Cache manager is [here](https://github.com/MichaCo/CacheManager)

Ive obviously had a brain fart when I wrote those docs.

**Comment by fleed** [comment]
No problem @TomPallister , thank you for the great project and the support!
