### ISSUE TITLE
Using Ocelot in front of SignalR Core

### ISSUE THREAD

**Issue by fleed** [ThreeMammals/Ocelot#462]
Is it supported to load balance SignalR Core clients, eventually using different protocols (e.g. **MessagePack**)?

**Comment by TomPallister** [comment]
@fleed there is no signal r support at the moment! 

You can track the issue [here](https://github.com/ThreeMammals/Ocelot/issues/344) if you are interested. Although there hasn't been much movement on it yet!

**Comment by fleed** [comment]
Thank you @TomPallister and sorry for the duplicate item

**Comment by TomPallister** [comment]
No worries!
