### ISSUE TITLE
Ocelot's customers

### ISSUE THREAD

**Issue by g1336** [ThreeMammals/Ocelot#470]
I've seen that Microsoft it's one of the Ocelot's customers. Does anybody knows what do they use it for? Other than them and Tencent, are any other customers?

Thanks!

**Comment by TomPallister** [comment]
Hi, thanks for your interest in Ocelot. Microsoft use Ocelot in their eshopsoncontainers project so they can have an api gateway in k8s / service fabric.

Other than them and tencent I don’t know of anyone specifically using Ocelot.

**Comment by geffzhang** [comment]
I set up a Ocelot user wechat-group in China, they have already used ocelot, and now more than 30 companies are running online. Not in my statistics range should be far more than this number, the last two years through the user's feedback, Ocelot function has been increasingly perfect
