### ISSUE TITLE
JSON schema for ocelot configurations. 

### ISSUE THREAD

**Issue by anktsrkr** [ThreeMammals/Ocelot#471]
## New Feature
Hi @TomPallister, It would be great if can give auto-complete, live documentation, validation support for ocelot.config file.  

## Motivation for New Feature
Well, It is hard to remember all the configurations 😃 so was thinking if we can give mentioned support via json schema

Here is some examples: 

**Auto-Complete:**

![image](https://user-images.githubusercontent.com/5505886/42722308-5983abf8-8767-11e8-94ec-20a90635cc8f.png)

**Live Documentation:**

![image](https://user-images.githubusercontent.com/5505886/42722314-8d2c9172-8767-11e8-8b8d-55bae82bf630.png)

![image](https://user-images.githubusercontent.com/5505886/42722317-a7584a5a-8767-11e8-9759-6432604e8bbe.png)

**Validation:**
![image](https://user-images.githubusercontent.com/5505886/42722320-b8c99ee2-8767-11e8-84f9-9adcc93d2121.png)

Isn't cool? What you think? I  have created sample schema, let me know if I can help! 

Thanks.

**Comment by xxsybreedxx** [comment]
+1, Schema would be perfect!!!

**Comment by TomPallister** [comment]
@anktsrkr @xxsybreedxx this looks cool! I have no idea how this works 😄 is there any documentation that shows how to do it? What tools you need etc? Is this something you could help with?

**Comment by anktsrkr** [comment]
Hi @TomPallister yes i can help but need your input as well 😃 

Please find the resources from where you will get the idea : 

[Overview](http://json-schema.org/)

[Getting Started Step-By-Step](http://json-schema.org/learn/getting-started-step-by-step.html)

[Schema Store]( http://schemastore.org/json/)

[Tool We Can Use](https://jsonschema.net/)

My suggestion is to create schema using mentioned tool, and then we should work on documentations.

oh, forgot to mention Rider, Visual Studio 2013+, Visual Studio Code, Visual Studio Code for Mac has direct support of json schema, so I believe everyone will love this!  

Let me know what you think.

**Comment by WrathZA** [comment]
This seems to be where the JSON Schema used in visual studio is defined.

https://github.com/SchemaStore/schemastore

**Comment by TomPallister** [comment]
This all looks good, if you guys want to implement this go for it.

**Comment by jediwarpraptor** [comment]
@anktsrkr - are you doing anything with this?

**Comment by briansantura** [comment]
This is done. Here is the pull request for SchemaStore.
https://github.com/SchemaStore/schemastore/pull/595
