### ISSUE TITLE
DownstreamUrlCreatorMiddleware a bug that caused a parameter loss

### ISSUE THREAD

**Issue by aqa510415008** [ThreeMammals/Ocelot#473]
## Expected Behavior / New Feature
Route conversion
Request address: http://localhost:5000/uc/Authorized/refresh?refreshToken=2288356cfb1338fdc5ff4ca558ec785118dfe1ff2864340937da8226863ff66d

## Actual Behavior / Motivation for New Feautre

```
"ReRoutes": [{
     "UpstreamPathTemplate": "/uc/Authorized/{server}/{action}",
      "UpstreamHttpMethod": [ "Post", "Get" ],
      "DownstreamPathTemplate": "/Authorized/{action}?server={server}"
}]
```

## Steps to Reproduce the Problem

  1.  The  `refreshToken` parameter is missing after other routes are converted by `DownstreamUrlCreatorMiddleware`

2、 Debugging found that the problem occurred in this place
 https://github.com/ThreeMammals/Ocelot/blob/8f4ae03290ce4621821396c0baf4d9c227fc8c38/src/Ocelot/DownstreamUrlCreator/Middleware/DownstreamUrlCreatorMiddleware.cs#L55

## Specifications

  - Version: 8.0
  - Platform: Asp.net core 2.1
  - Subsystem: Windows

**Comment by TomPallister** [comment]
@aqa510415008 Which version of Ocelot are you using? I will look at this ASAP. Feels like a bug.

**Comment by aqa510415008** [comment]
This modification can solve my problem, but I don't know if it will cause other problems, I hope to help you.

```
if (string.IsNullOrEmpty(context.DownstreamRequest.Query))
{
	context.DownstreamRequest.Query = GetQueryString(dsPath);
}
else
{
	context.DownstreamRequest.Query += GetQueryString(dsPath).Replace('?', '&');
}
```

**Comment by TomPallister** [comment]
@aqa510415008 thanks, I can add failing test, make the change and see if all the tests still pass!

**Comment by aqa510415008** [comment]
@TomPallister  Is there any progress on this issue?

**Comment by TomPallister** [comment]
@aqa510415008 sorry I haven’t been able to do this yet. Will try ASAP.

**Comment by TomPallister** [comment]
@aqa510415008 I will close this when it is in the main nuget package 😄

**Comment by TomPallister** [comment]
Released in version 8.0.1

**Comment by aqa510415008** [comment]
@TomPallister Thank you for your efforts

**Comment by TomPallister** [comment]
no problem, let me know if it doesnt work!
