### ISSUE TITLE
[Question] ISercviceCollection on Program.cs

### ISSUE THREAD

**Issue by LuketaD2** [ThreeMammals/Ocelot#478]
Hello, everyone!

I'm trying to update the Ocelot (8.0.0) on my project (From core 2.0 to core 2.1), but I'm stuck in this error:

**Program.cs**
`  .ConfigureServices(s => {
                   s.AddOcelot();
               })`

This line give the following error:
'IServiceCollection' does not contain a definition for 'AddOcelot' and no extension method 'AddOcelot'....

All of my packges are up-to-date.

![image](https://user-images.githubusercontent.com/6198950/42906133-8bde517e-8ab0-11e8-9ba3-5a145fd22da4.png)

Thanks and sorry for my rusty english.

**Comment by LuketaD2** [comment]
It worked!!!

But all my routing is returning 404.

It was all working before core 2.1 (was running on 2.0).

![image](https://user-images.githubusercontent.com/6198950/42941757-28f660b8-8b34-11e8-936e-566c8787656a.png)

And my routing (only a part): 

`{
  "ReRoutes": [
    {
      "DownstreamPathTemplate": "/api/product/",
      "DownstreamScheme": "http",
      "DownstreamHostAndPorts": [
        {
          "Host": "localhost",
          "Port": 58782
        }
      ],
      "UpstreamPathTemplate": "/produto/",
      "UpstreamHttpMethod": [ "GET", "OPTIONS" ]
    }
]
}`

**Comment by TomPallister** [comment]
@LuketaD2 awesome :) no problem.
