### ISSUE TITLE
Error 502 after updating to Ocelot 8.0.1

### ISSUE THREAD

**Issue by margaale** [ThreeMammals/Ocelot#490]
## Steps to Reproduce the Problem

  I have ocelot 8.0.0 working, today i was trying to update to 8.0.1 and after running it in my workstation i got an 502 http errorcode. 
I tried it in our development server too and got the same results.
Has something been changed between versions?
  
## Specifications

  - Version: 8.0.1
  - Platform: Windows 8.1/2016
  - Subsystem: Core 2.1.2

**Comment by TomPallister** [comment]
@margaale yes their were changes, looks like GitHub hasn't picked them up correctly :( We added support for query string parameters in upstream path templates, added a way to setup your initial ocelot state from a folder with config files in it, added a way to branch the ocelot pipeline with your own middleware. 

Can you share your json configuration and program.cs / startup.cs and I will take a look?

**Comment by margaale** [comment]
Thanks for your reposnse. 
I just removed the domain form all urls in the config.

[files.zip](https://github.com/ThreeMammals/Ocelot/files/2220779/files.zip)

**Comment by TomPallister** [comment]
Ok cool I will check it out asap.

**Comment by TomPallister** [comment]
@margaale which routes do you get 502 on? Is it all of them?

**Comment by margaale** [comment]
No, only the one not using oauth. It's pretty simple because we are just starting with microservices..

**Comment by margaale** [comment]
The other one I got 401. But I didn't fully test it passing the token

**Comment by TomPallister** [comment]
@margaale can you confirm the exact url you are using to call Ocelot?

Also would it be possible to paste the logs from Ocelot when your request fails here?

**Comment by TomPallister** [comment]
for debugging purposes...

https://ocelotperformancetest.azurewebsites.net/api/values - same problem, deployed latest version of Ocelot also same problem running locally on that URL.

**Comment by TomPallister** [comment]
@margaale please try new verison 8.0.2

**Comment by margaale** [comment]
I will as soon as I get to work. Thanks

**Comment by TomPallister** [comment]
Awesome thanks for bringing this to my attention.
