### ISSUE TITLE
HttpClientHttpRequester: Suggest to get error log if httpcode response is 500

### ISSUE THREAD

**Issue by tungphuong** [ThreeMammals/Ocelot#497]
Hi,

Currently, if downstream service throw exception with httpcode 500, but Ocelot just logs "warning" or "debug". It will not clear and difficult to trace/monitor on production. Because we cannot set log level is debug/info for production.

I suggest we should check status code. If it is 500, we wil log like error.\

Cheers,

Phuong Le

**Comment by TomPallister** [comment]
@tungphuong thanks for your interest in Ocelot. There is another issue open about this problem at #492 so I will close this as a duplicate.
