### ISSUE TITLE
Question: How to implement documentation aggregator using Swashbuckle.AspNetCore

### ISSUE THREAD

**Issue by Marusyk** [ThreeMammals/Ocelot#499]
I know that Ocelot does not support Swagger, but I need some help (or advice) how to add implementation of it by myself. 

So, I have a few service (in Docker containers) that produces swagger.json on endpoint : `{ServiceBaseUrl}/swagger/v1/swagger.json`

ocelot.json is:

```json
"ReRoutes": [
    {
      "ServiceName": "ServiceA",
      "DownstreamPathTemplate": "/{everything}",
      "DownstreamScheme": "http",
      "DownstreamHostAndPorts": [
        {
          "Host": "servicea",
          "Port": 80
        }
      ],
      "UpstreamPathTemplate": "/servicea/{everything}",
      "UpstreamHttpMethod": [ "GET" ]
    },
	{
      "ServiceName": "ServiceB",
      "DownstreamPathTemplate": "/{everything}",
      "DownstreamScheme": "http",
      "DownstreamHostAndPorts": [
        {
          "Host": "serviceb",
          "Port": 80
        }
      ],
      "UpstreamPathTemplate": "/serviceb/{everything}",
      "UpstreamHttpMethod": [ "GET" ]
    },
	{
      "ServiceName": "ServiceC",
      "DownstreamPathTemplate": "/{everything}",
      "DownstreamScheme": "http",
      "DownstreamHostAndPorts": [
        {
          "Host": "servicec",
          "Port": 80
        }
      ],
      "UpstreamPathTemplate": "/servicec/{everything}",
      "UpstreamHttpMethod": [ "GET" ]
    }
  ],
  "GlobalConfiguration": {
  }
```
In gateway service I've tried to add something like aggregator that should discover all services from config and add multiple SwaggerEndpoint like:

```csharp
app.UseSwaggerUI(setup =>
{
	setup.RoutePrefix = "docs";
	foreach (var service in _cfg.Get<FileConfiguration>().ReRoutes)
	{
		var address = service.DownstreamHostAndPorts.FirstOrDefault();
		var url = $"{service.DownstreamScheme}://{address.Host}:{address.Port}/swagger/v1/swagger.json";
		setup.SwaggerEndpoint(url, service.ServiceName);
	}
});
```

How can I get ServiceName and Service base url from ocelot.json? 

```
  setup.SwaggerEndpoint("http://servicea:80/swagger/v1/swagger.json", "ServiceA");
  setup.SwaggerEndpoint("http://serviceb:80/swagger/v1/swagger.json", "ServiceB");
  setup.SwaggerEndpoint("http://servicec:80/swagger/v1/swagger.json", "ServiceC");
```
I got the error:

> Failed to fetch http://servicea:80/swagger/v1/swagger.json
> Fetch errorPossible cross-origin (CORS) issue? The URL origin (http://servicea) does not match the page (http://localhost:86). Check the server returns the correct 'Access-Control-Allow-*' headers

Where `http://localhost:86 ` is endpoint of apigateway in Docker container.

My CORS config:

```
services.AddCors(options =>
            {
                options.AddPolicy("CorsPolicy",
                    builder => builder.AllowAnyOrigin()
                        .AllowAnyMethod()
                        .AllowAnyHeader()
                        .AllowCredentials());
            });

app.UseCors("CorsPolicy");
```

it seems not problem with CORS because when I change Host to unexisting then I get the same error.

**Comment by TomPallister** [comment]
@Marusyk Mmmmm I am not sure what the problem is. It will only be CORS related if the swagger ui in api gateway makes ajax calls to the backend services. Does that happen?

Where / when does the error actually occur?

**Comment by Marusyk** [comment]
@TomPallister Yeah, you are right.  Swagger ui in api gateway makes ajax calls to the backend services. Could you please suggest any solutions?

**Comment by TomPallister** [comment]
@Marusyk did that work? I don't know a better way of doing it tbh.

I think your original plan might work, but you need to proxy the ajax calls through Ocelot to your downstream service. Does that make sense?

**Comment by Marusyk** [comment]
It works when to add this code to each service
```csharp
 app.UseSwagger(options => 
            {
                options.PreSerializeFilters.Add((swaggerDoc, httpReq) => swaggerDoc.BasePath = "/ServiceA"); // service name from ocelot config
                options.RouteTemplate = "/{documentName}/swagger.json";
            });
```

Thanks for your time.

**Comment by TomPallister** [comment]
Awesome no worries

**Comment by yekanthkola** [comment]
> It works when to add this code to each service
> 
> ```cs
>  app.UseSwagger(options => 
> {
>     options.PreSerializeFilters.Add((swaggerDoc, httpReq) => swaggerDoc.BasePath = "/ServiceA"); // service name from ocelot config
>     options.RouteTemplate = "/{documentName}/swagger.json";
> });
> ```
> 
> Thanks for your time.

but This is not working when service is running independently in Local
