### ISSUE TITLE
Question: Globally configure the DownstreamHostAndPorts

### ISSUE THREAD

**Issue by rickesh123** [ThreeMammals/Ocelot#503]
Hi,

I've just started to use Ocelot and it is brilliant! Everything is up and running but I had a quick question to see if it is possible to set the DownstreamHostAndPorts dynamically within code or whether you can set it globally within the GlobalConfiguration section. Our services are hosted within our own custom built service registry and it would be nice to not have to declare the DownstreamHostAndPorts for all services. I could use the catchall option by setting "DownstreamPathTemplate": "/api/{everything}." Would that be the only way?

Many thanks,

Rickesh

**Comment by TomPallister** [comment]
@rickesh123 thanks for your interest in Ocelot. Unfortunately there is no way to do this other than implement an IServiceDiscoveryProvider for your service registry and change the IServiceDiscoveryProviderFactory to return it. This is all custom code so you would need to fork Ocelot probably or just override Ocelots implementations of these things in the asp.net dependency injection container. Ocelot uses TryAddSingleton etc so if it already exists in the container it wont add it.

I'm not sure how the catch all would help so maybe I haven't understood your use case!

**Comment by TomPallister** [comment]
OK cool sounds good!
