### ISSUE TITLE
structured logging of Ocelot request and previous request id

### ISSUE THREAD

**Issue by Marusyk** [ThreeMammals/Ocelot#514]
I need to get some telemetry from my services like requests, dependencies, ect. 
I'm going to add ApplicationInsights to Ocelot. 

I've just installed Microsoft.ApplicationInsights.AspNetCore package and added 
`.UseApplicationInsights();` to WebHost

```csharp
private static IWebHostBuilder CreateWebHostBuilder(string[] args)
{
    return WebHost.CreateDefaultBuilder(args)
        .UseStartup<Startup>()
        .UseApplicationInsights();
}
```
Then I enabled the feature [Request Id / Correlation Id](http://ocelot.readthedocs.io/en/latest/features/requestid.html)

```json
 "GlobalConfiguration": {
    "RequestIdKey": "Request-Id"
  }
```
results is:

> requestId: 0HLFMDHQI9PUD:00000001, previousRequestId: no previous request id, message: Downstream url is http://localhost:50689/api/values 

But when it sends to AppInsights the value of Reuqest Id is 8fb94098-44d54d39eb24a079 which is the same as Operation ID

Could you please suggest if I can pass 0HLFMDHQI9PUD:00000001 as an Operation ID and Reuqest Id?

![screenshot_1](https://user-images.githubusercontent.com/9221694/43428070-0c3693d2-9465-11e8-8225-70d72d00aaf3.png)

**Comment by TomPallister** [comment]
@Marusyk I think this might be because Ocelot doesnt store the request ids as part of a structured log, it might just dump them into a string. Can you see any logs from Ocleot at all in AppInsights?

**Comment by Marusyk** [comment]
Yes, as you can see on the screen (INORMATION logs)

**Comment by TomPallister** [comment]
@Marusyk I missed that :)

so yeh pretty sure this is because of structured logging also not sure what would happen because maybe request id is app insights own request id.

**Comment by TomPallister** [comment]
I guess this feature would be support structured logging for ocelot request and previous request id scenario.
