### ISSUE TITLE
Cannot parse Microsoft claim type

### ISSUE THREAD

**Issue by MaiReo** [ThreeMammals/Ocelot#517]
## ocelot.json
The json is a valid format
```javascript
{
    "ReRoutes":[
      {
        "DownstreamHostAndPorts": [
          {
            "Host": "localhost",
            "Port": 5000
          }
        ],
        "DownstreamPathTemplate": "/api/values",
        "UpstreamPathTemplate": "/api/values",
        "UpstreamHttpMethod": [
          "Get"
        ],
        "ReRouteIsCaseSensitive": false,
        "DownstreamScheme": "http",
        "AuthenticationOptions": {
          "AuthenticationProviderKey": "Bearer",
          "AllowedScopes": [

          ]
        },
        "RouteClaimsRequirement": {
          "http://schemas.microsoft.com/ws/2008/06/identity/claims/role": "Admin"
        }
      }
    ],
    "GlobalConfiguration":{
        "BaseUrl":"http://localhost:5001"
    }
}
```
## The console output.
INFO  2018-07-31 13:32:17,863 [37   ] soft.AspNetCore.Hosting.Internal.WebHost - Request starting HTTP/1.1 GET http://localhost:5001/api/values
INFO  2018-07-31 13:32:17,863 [37   ] uthentication.JwtBearer.JwtBearerHandler - Successfully validated the token.
WARN  2018-07-31 13:32:17,864 [37   ] ddleware.DownstreamRouteFinderMiddleware - requestId: 0HLFMKO86AJ1B:00000001, previousRequestId: no previous request id, message: DownstreamRouteFinderMiddleware setting pipeline errors. IDownstreamRouteFinder returned Error Code: UnableToFindDownstreamRouteError Message: Unable to find downstream route for path: /api/values, verb: GET
WARN  2018-07-31 13:32:17,864 [37   ] ddleware.DownstreamRouteFinderMiddleware - requestId: 0HLFMKO86AJ1B:00000001, previousRequestId: no previous request id, message: Unable to find downstream route for path: /api/values, verb: GET
WARN  2018-07-31 13:32:17,864 [37   ] Responder.Middleware.ResponderMiddleware - requestId: 0HLFMKO86AJ1B:00000001, previousRequestId: no previous request id, message: Error Code: UnableToFindDownstreamRouteError Message: Unable to find downstream route for path: /api/values, verb: GET errors found in ResponderMiddleware. Setting error response for request path:/api/values, request method: GET
INFO  2018-07-31 13:32:17,865 [37   ] soft.AspNetCore.Hosting.Internal.WebHost - Request finished in 1.9942ms 404

**Comment by TomPallister** [comment]
@MaiReo based on your stacktrace I dont think this is a problem with your claim? It seems to not be able to match a route for your request. Please can you share your program.cs, startup.cs and which version of Ocelot you are using?

**Comment by MaiReo** [comment]
@TomPallister  Sorry. I think that it is a json parsing problem.  
If the json key contains the ":" character,  an exception will throwed by the package named 
"Microsoft.Extensions.Options.ConfigurationExtensions".
The error message is "Cannot create instance of type 'System.String'...".
So the correct question may be
"How can we validate claim type which contains colon character such as Microsoft build-in role claim".
Thanks

**Comment by MaiReo** [comment]
Even there is no route information when json parsing failed. It is not a route matching issue.

**Comment by TomPallister** [comment]
@MaiReo from your message it is Microsoft.Extensions.Options.ConfigurationExtensions with the problem? This is not Ocelot code. Maybe the claim should just be `role`?

**Comment by TomPallister** [comment]
@MaiReo Ive looked into this more and it turns out you cannot use ```:``` is a string in a dictionary configuration in asp.net core. I changed the object and was able to get a claim type of http://schemas.microsoft.com/ws/2008/06/identity/claims/role into RouteClaimsRequirement but then it turned out that microsofts claim code wont parse ```http://schemas.microsoft.com/ws/2008/06/identity/claims/role``` into a claim anyway because I think that is a claim value type and the claim should be role. I'm not going to make any changes here and will close this for now!
