### ISSUE TITLE
CI - Set up automated pipeline for mac/linux

### ISSUE THREAD

**Issue by binarymash** [ThreeMammals/Ocelot#52]
Like the appveyor pipeline this would kick off on each commit. However, this would just run the Build task - ie, no publishing of packages. The authoritative build pipeline would still be the appveyor pipeline, and this is what would publish the nuget packages and do the releases.

Looks like the [cake](https://github.com/cake-build/cake) project tests their osx and linux builds Travis and Bitrise.

**Comment by binarymash** [comment]
I now have one of my own projects running through a build pipeline on Ubuntu in Travis, so with what I've learnt it shouldn't be much effort to get this set up for Ocelot.

**Comment by TomPallister** [comment]
@binarymash right im back will pick this up in due course! :)

**Comment by TomPallister** [comment]
I've got the build working on Travis for Linux and OSX with a caveat that the acceptance and intergration tests dont work properly on OSX. Something is going wrong when I start doing the crazy stuff spinning up lots of tasks / threads for various concurrency based tests. This also happens on my mac so will open a seperate issue for this,

**Comment by binarymash** [comment]
Meant to mention to you the other day that I saw that Appveyor now supports linux - at least in beta. See https://www.appveyor.com/beta/. Might have made things a bit easier! 

I guess you can never have too many build systems supported, though, so if I get around to getting this working with my own stuff then I'll see what I can do here too.

**Comment by TomPallister** [comment]
@binarymash yeh that would have! Thanks for th heads up! I also tried circle CI but it was a faff. I ended up copying cakes travis.yml and that worked fine!
