### ISSUE TITLE
Help with configuring json based on web api action

### ISSUE THREAD

**Issue by premsai** [ThreeMammals/Ocelot#526]
Hi 
I have a complex object (parameters to the API) 
an example {beginDate:"01/01/2018",endDate:01/30/2018",productIds: [1,2,3,4]} something like this to a specific action, my controller has few http get methods like
GetProductByIdAndDates(ParameterObject input)
GetProductById(ParameterObject input)  etc
How do i configure the upstreampathtemplate & downstreampathtemplate so that ocelot routes the call to the correct action and I can get the response back, i tried query parameters but the parameters are coming to the api as null, tried posting as json using [FromBody] with no success. Any help is appreciated

Thanks
Prem

**Comment by premsai** [comment]
I got it to work thanks for the input, i used query string to achieve the same

**Comment by TomPallister** [comment]
Awesome!!
