### ISSUE TITLE
Reload config again

### ISSUE THREAD

**Issue by margaale** [ThreeMammals/Ocelot#540]
Hey, nice progress you are doing. Since you are introducing breaking changes can I ask what is your opinion in this?
We added reload config on file change. What if the administration api just write the file so the the internal configuration is reload with the same mechanism for both use cases? Right now the internal configuration is updated twice, one within administration and the other when the  event fires... Obviously thr user would have to set reload config true, that the breaking change. If you are ok I would be glad to implement it. 

Thanks for your time

**Comment by TomPallister** [comment]
@margaale I'm not sure this would change anything.

Yeh I think this idea is fine but I'm not sure that having to specify reload on change true when using the administration API. This adds extra thing for the user to do. Is this a good idea? Is there a way to set reload true outside of the users control in the mechanism that sets up administration API maybe? That would be ideal I think. Or at least have them call the same delegate maybe to consolidate the logic?
