### ISSUE TITLE
[New Features] Custom limits per api/client, Subscription plans per api/client, Billing, Analytics

### ISSUE THREAD

**Issue by stamatiagk** [ThreeMammals/Ocelot#553]
## Expected Behavior / New Feature
1. api limits per client per api, per endpoint in x minutes or in one month
2. subscription plans per api, per client
3. api billing
4. api analytics

## Actual Behavior / Motivation for New Feature
rate limiting

## Steps to Reproduce the Problem

  1.
  1.
  1.

## Specifications

  - Version:
  - Platform:
  - Subsystem:

**Comment by stamatiagk** [comment]
@TomPallister I am very interested in helping with this feature!

**Comment by TomPallister** [comment]
OK cool, I need to have a think about it and finish #529 then clear up all the current bugs before we an go further. I would probably look to take inspiration from aws, azure, apigee, kong and tyk for this feature. I think a bucket based rate limiter probably needs to be implemented. This will be a lot of work I think :) but a really good feature.

**Comment by TomPallister** [comment]
copied from previous issue

At the moment we only support basic rate limiting. Implement something more complex re discussion in #372 such as https://en.wikipedia.org/wiki/Token_bucket, https://github.com/google/guava/blob/master/guava/src/com/google/common/util/concurrent/SmoothRateLimiter.java

**Comment by raman-m** [comment]
> @stamatiagk commented [on Aug 17, 2018](#issuecomment-413771577)
 I am **very interested in helping** with this feature!

How?
How will you help Ocelot?

-----
[Your repos](https://github.com/stamatiagk?tab=repositories) are empty.

> `stamatiagk doesn’t have any public repositories yet.`

Please, help yourself! 🤣

**Comment by raman-m** [comment]
Current situation with [Rate Limiting](https://ocelot.readthedocs.io/en/latest/features/ratelimiting.html) feature: 
- [Rate Limiting | Future and ASP.NET Core Implementation](https://ocelot.readthedocs.io/en/latest/features/ratelimiting.html#future-and-asp-net-core-implementation)
