### ISSUE TITLE
Problems with use of scenarios

### ISSUE THREAD

**Issue by thicktao** [ThreeMammals/Ocelot#566]
I've always had a question.  The kestrel is just a application server not a web server. So  it  is nessary to  erect a nginx in front of ocelot.
But all of them have load balance, all of them  have service discovery... I don't kown the ocelot‘s use of scenarios
In fact I have some api to exposed to the outer net. And I need service discovery and  load balance.

**Comment by TomPallister** [comment]
@thicktao thanks for your interest in the project. 

https://docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel?view=aspnetcore-2.1&tabs=aspnetcore2x

Kestrel is a webserver.

**Comment by thicktao** [comment]
I am so happy to receive your reply!  In fact, I am the one who don't want to use nginx. So I get the ocelot. And my main concern is whether Ocelot can be exposed to the Internet? Such as Security?

**Comment by thicktao** [comment]
I found the microsoft official recommendation to erect nginx before kestrel.

**Comment by TomPallister** [comment]
I’m not sure if you need to put nginx in front of kestrel anymore. Might be worth asking on the kestrel GitHub page!

Btw I would recommend using nginx unless you really really really want to use Ocelot :)

**Comment by thicktao** [comment]
Thanks a lot !

**Comment by wswind** [comment]
I think the concern is from this document:

https://docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel?view=aspnetcore-2.2#when-to-use-kestrel-with-a-reverse-proxy-1

It encourages you to use reverse proxy . But ocelot is a reverse proxy too.
