### ISSUE TITLE
Send Authentication request prior to a request

### ISSUE THREAD

**Issue by REPRESSION** [ThreeMammals/Ocelot#569]
Hi,

I trying to setup your gateway but I am facing a problem, I would like to send an HTTP request to validate a token before a ReRoute. I did not understand the Authentication part of your documentation. 

For example:

- client sends request
- gateway sends the token from the client to an other microservice using HTTP.
- If the microservice validates the client's identity, The ReRoute takes place.

Is this doable with Ocelot ?

**Comment by TomPallister** [comment]
@REPRESSION yes this is possible, Ocelot just uses whatever authentication provider you register with asp.net. I assume you mean [these](https://ocelot.readthedocs.io/en/latest/features/authentication.html) docs? What is it that doesn't make sense?

**Comment by REPRESSION** [comment]
Well I don't understand the 'workflow' of the authentication in ocelot. 

For example I don't get how this works: 

`    var authenticationProviderKey = "TestKey";     `
 
  `  services.AddAuthentication()
        .AddJwtBearer(authenticationProviderKey, x =>
        {
        });`

How does this and the corresponding part in ocelot.json can be used as authentication ?

**Comment by TomPallister** [comment]
@REPRESSION Ocelot uses the key in AuthenticationMiddleware.cs to authenticate the request against the authentication provider registered with the key. Check out that class and it should make more sense.

**Comment by REPRESSION** [comment]
@TomPallister Let's assume that my authentication service lives at 192.168.1.2:80/ValidateToken?token=xxx and i am trying to access mygateway:80/getInfos?token=xxx. I want Ocelot to verify that I am authenticated before Rerouting the request. I really don't get how I can archive this, all examples use either an Identity Server (which I don't) or check the token themselves.

On example I can find uses this kind of Authentication, but it doesn't seem to be what I need :

`        var options = o =>   `
`            {   `
`                o.Authority = "https://whereyouridentityserverlives.com";    `
 `               o.ApiName = "api";    `
 `               o.SupportedTokens = SupportedTokens.Both;    `
 `               o.ApiSecret = "secret";    `
  `          };`
`        services.AddAuthentication()
            .AddIdentityServerAuthentication(authenticationProviderKey, options);`

**Comment by REPRESSION** [comment]
Even trying to validate a simple JWT doesn't work for me. 


```
            services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme).AddJwtBearer("Bearer", options =>
            {
                options.TokenValidationParameters = new TokenValidationParameters
                {
                    ValidateIssuer = true,
                    ValidIssuer = "xxxx.xx",
                    ValidateAudience = false,
                    ValidAudience = "xxxx.xx",
                    ValidateLifetime = true,
                    ValidateIssuerSigningKey = true,
                    IssuerSigningKey = new SymmetricSecurityKey(Encoding.UTF8.GetBytes("xxxxxxxxxxxxxxxx"))
                };
            });
            services.AddOcelot();
```


```
    {
      "DownstreamPathTemplate": "/api/test",
      "DownstreamScheme": "http",
      "DownstreamHostAndPorts": 
      [
        {
          "Host": "authentication",
          "Port": "80"
        }
      ],
      "UpstreamPathTemplate": "/test",
      "UpstreamHttpMethod": [ "Get" ],
      "AuthenticationOptions":
      {
        "AuthenticationProviderKey": "Bearer",
        "AllowedScopes": []
      }
```

**Comment by REPRESSION** [comment]
Finally got the last part (with JWT) working. I was missing this in my header:

Authorization: bearer MYTOKEN

**Comment by TomPallister** [comment]
@REPRESSION ahh Ocelot only integrates with existing authentication providers that are part of asp.net core or other people have already implemented. You would pull their NuGet packages and do the integration that way in Ocelot.

All ocelot does is map the authentication provider you provide with a ReRoute. In your case if you have some custom authentication then you will need to write a custom authentication provider in asp.net that you can then add to the asp.net pipeline and then wire it up with Ocelot.

Does that make sense?

**Comment by REPRESSION** [comment]
@TomPallister Got it working with a custom authentication providers, this issue helped me a lot : 
https://github.com/ThreeMammals/Ocelot/issues/445

**Comment by TomPallister** [comment]
awesome good stuff :)

**Comment by kandasamy-maruthapillai** [comment]
Hi Tom,

I am getting same kind of issue what @REPRESSION faced.  can you please help me on this.

@REPRESSION can you please share where you added  Authorization: bearer MYTOKEN
