### ISSUE TITLE
The Ocelot Service discovery USES Service Fabric

### ISSUE THREAD

**Issue by anlem12** [ThreeMammals/Ocelot#577]
The Ocelot Service discovery USES Service Fabric, and I have a question: if the Service Fabric master node address I provided to Ocelot fails, the entire gateway will be unable to find the Service. Can I provide multiple Service Fabric node addresses when the Service discovery is made? This enables one node to continue to discover services through other nodes.

**Comment by TomPallister** [comment]
@anlem12 at the moment you cannot do this, Ocelot uses the naming service, doesn’t service fabric keep this up?

**Comment by anlem12** [comment]
https://ocelot.readthedocs.io/en/latest/features/servicefabric.html

I mean, there is a failure of Host in ServiceDiscoveryProvider, could you please fill in a few more Host addresses for round hunting
 "Host": "localhost",
`
"ServiceDiscoveryProvider": {
            "Host": "localhost",
            "Port": 19081,
            "Type": "ServiceFabric"
        }

`

**Comment by TomPallister** [comment]
@anlem12 this could certainly be a new feature! @davidni is this needed? I don't know service fabric that well?

**Comment by davidni** [comment]
@anlem12 @TomPallister this seems unnecessary. Service Fabric's Reverse Proxy on localhost:19081 is expected to be always available as long as the node is up. If it ever goes down (for whatever reason), you're better off treating the entire node as unhealthy and **removing the node from your backend pool**, and stop routing incoming traffic to it. Trying to complete your gateway requests through another node's Reverse Proxy would now cause undesirable load on two nodes of your cluster, and would create unnecessary network traffic between your nodes.

Regarding _removing the unhealthy node from your backend pool_, one way to accomplish this if you're running on Azure is to configure Azure Load Balancer health probes to probe an internal HTTP endpoint on your service. Have that endpoint return non-2xx in case an unhealthy condition (such as Reverse Proxy is down) is detected.

**Comment by TomPallister** [comment]
@davidni thanks for this advice, you obviously know Service Fabric very well :)

I will close this ticket then as I don't think it is needed.

**Comment by romina2001** [comment]
@davidni what if we have a website that we want to expose through ocelot from  inside sf that requires SSL to connect to ?  We then get this in firefox when trying to access the website how ocelot acesses it :
```
Websites prove their identity via certificates. Firefox does not trust this site because it uses a 
certificate that is not valid for localhost:19081. The certificate is only valid for the following names: 
example.net, www.example.net
```
Inside Ocelot we get  :
```
2019-07-29 11:53:41|WARN|requestId: 0HLOK316C6NCJ:00000001, previousRequestId: no previous 
request id, message: Error making http request, exception: System.Net.Http.HttpRequestException: 
The SSL connection could not be established, see inner exception. ---> 
System.Security.Authentication.AuthenticationException: The remote certificate is invalid according
 to the validation procedure.
```
Do you have an idea on how could we do this with ocelot ? (we already tried `"SkipSslValidation": true` but the behavior is the same : SSL validation error )
