### ISSUE TITLE
Ocelot container problem

### ISSUE THREAD

**Issue by deadmandrive** [ThreeMammals/Ocelot#579]
Hi Tom
it work really well when test it on Visual Studio but when i try to build it to container,
it dosn't working. it registered with eureka discovery service but when i try access test api it return

This page isn’t working
localhost didn’t send any data.

if i call the other service (in container too) it return correctly.
not sure how can i track down this problem.

Thank you.

**Comment by TomPallister** [comment]
@deadmandrive set the logger level to trace and get the logs from your container, easiest way is probably use console logger (stdout) in asp.net and then do docker logs {containername/id} and you can see them on the terminal...or you can write to disk etc up to you. This might help you track the issue down. 

Most of the time docker problems are because the networking isn't set up correctly and one container cannot talk to another.

**Comment by deadmandrive** [comment]
@TomPallister Thank you. will try it out.

**Comment by deadmandrive** [comment]
@TomPallister i set the logger level to trace but don't understand "use console logger (stdout) in asp.net" part. Do you have some example that i can take a look?
Now i got new error 

This page isn’t working
localhost is currently unable to handle this request.
HTTP ERROR 500

**Comment by TomPallister** [comment]
I mean something like 

```csharp
                .ConfigureLogging((hostingContext, logging) =>
                {
                    logging.AddConfiguration(hostingContext.Configuration.GetSection("Logging"));
                    logging.AddConsole();
                })
```
but you can use any type of logger you want.

**Comment by deadmandrive** [comment]
@TomPallister Ok. Got it will do.

**Comment by deadmandrive** [comment]
@TomPallister I check the connection between Ocelot Gateway and each service containers. they all working find.
I test by ping from Ocelot Gateway container to each service containers.

```
# ping service-a
PING service-a (172.23.0.7) 56(84) bytes of data.
64 bytes from service-a.test-network (172.23.0.7): icmp_seq=1 ttl=64 time=0.154 ms
64 bytes from service-a.test-network (172.23.0.7): icmp_seq=2 ttl=64 time=0.055 ms
64 bytes from service-a.test-network (172.23.0.7): icmp_seq=3 ttl=64 time=0.055 ms
64 bytes from service-a.test-network (172.23.0.7): icmp_seq=4 ttl=64 time=0.146 ms
64 bytes from service-a.test-network (172.23.0.7): icmp_seq=5 ttl=64 time=0.085 ms
64 bytes from service-a.test-network (172.23.0.7): icmp_seq=6 ttl=64 time=0.125 ms
^C
--- service-a ping statistics ---
6 packets transmitted, 6 received, 0% packet loss, time 5192ms
rtt min/avg/max/mdev = 0.055/0.103/0.154/0.041 ms
# ping service-b
PING service-b (172.23.0.9) 56(84) bytes of data.
64 bytes from service-b.test-network (172.23.0.9): icmp_seq=1 ttl=64 time=0.145 ms
64 bytes from service-b.test-network (172.23.0.9): icmp_seq=2 ttl=64 time=0.129 ms
64 bytes from service-b.test-network (172.23.0.9): icmp_seq=3 ttl=64 time=0.071 ms
64 bytes from service-b.test-network (172.23.0.9): icmp_seq=4 ttl=64 time=0.128 ms
64 bytes from service-b.test-network (172.23.0.9): icmp_seq=5 ttl=64 time=0.127 ms
64 bytes from service-b.test-network (172.23.0.9): icmp_seq=6 ttl=64 time=0.077 ms
64 bytes from service-b.test-network (172.23.0.9): icmp_seq=7 ttl=64 time=0.051 ms
64 bytes from service-b.test-network (172.23.0.9): icmp_seq=8 ttl=64 time=0.140 ms
^C
--- service-b ping statistics ---
8 packets transmitted, 8 received, 0% packet loss, time 7242ms
rtt min/avg/max/mdev = 0.051/0.108/0.145/0.035 ms
# ping service-a2
PING service-a2 (172.23.0.8) 56(84) bytes of data.
64 bytes from service-a2.test-network (172.23.0.8): icmp_seq=1 ttl=64 time=0.190 ms
64 bytes from service-a2.test-network (172.23.0.8): icmp_seq=2 ttl=64 time=0.094 ms
64 bytes from service-a2.test-network (172.23.0.8): icmp_seq=3 ttl=64 time=0.103 ms
64 bytes from service-a2.test-network (172.23.0.8): icmp_seq=4 ttl=64 time=0.097 ms
64 bytes from service-a2.test-network (172.23.0.8): icmp_seq=5 ttl=64 time=0.116 ms
64 bytes from service-a2.test-network (172.23.0.8): icmp_seq=6 ttl=64 time=0.155 ms
64 bytes from service-a2.test-network (172.23.0.8): icmp_seq=7 ttl=64 time=0.199 ms
64 bytes from service-a2.test-network (172.23.0.8): icmp_seq=8 ttl=64 time=0.097 ms
^C
--- service-a2 ping statistics ---
8 packets transmitted, 8 received, 0% packet loss, time 7288ms
rtt min/avg/max/mdev = 0.094/0.131/0.199/0.042 ms
#
```

So right  now. I'm not quit sure what the problem is?
But something wrong with this.

```
Ocelot.Requester.Middleware.HttpRequesterMiddleware[0]
requestId: 0HLGDFTAQ9RD9:00000003, previousRequestId: no previous request id, message: Error making http request, exception: System.Net.Http.HttpRequestException: Cannot assign requested address ---> System.Net.Sockets.SocketException: Cannot assign requested address
```

**Comment by TomPallister** [comment]
@deadmandrive interesting, Ocelot is using ```http://localhost:9600/api/values``` as downstream url in your logs but you are pinging service-a is there something wrong with the config?

**Comment by deadmandrive** [comment]
@TomPallister Well i use the same setting when i ran in visual studio debug mode and it worked.
It only not working when run it in docker mode. and i see that in the process ocelot ask the eureka for a list of api that requested and eureka seem like to give it a correct routing. 

Here is my ocelot.json config
```
{
  "ReRoutes": [
    {
      "DownstreamPathTemplate": "/api/values",
      "DownstreamScheme": "http",
      "UpstreamPathTemplate": "/service-a",
      "UseServiceDiscovery": true,
      "ServiceName": "service-test-A",
      "UpstreamHttpMethod": [ "Get" ],
      "LoadBalancerOptions": {
        "Type": "RoundRobin"
      }
    },
    {
      "DownstreamPathTemplate": "/api/values",
      "DownstreamScheme": "http",
      "UpstreamPathTemplate": "/service-b",
      "UseServiceDiscovery": true,
      "ServiceName": "service-test-B",
      "UpstreamHttpMethod": [ "Get" ]
   }
  ],
  "GlobalConfiguration": {
    "RequestIdKey": "null",
    "ServiceDiscoveryProvider": {
      "Type": "Eureka"
    }

  }
}
```

**Comment by deadmandrive** [comment]
@TomPallister I see. That might be a hint. Thank you Tom. I will try to solve it and tell you later what the problem is.

**Comment by deadmandrive** [comment]
@TomPallister Tom, I think i made some progress but still got a new error. now i can get the right url for routing in docker 

```
Microsoft.AspNetCore.Hosting.Internal.WebHost[1] Request starting HTTP/1.1 GET http://localhost:9100/service-a  


      GetInstances returning: Instance[InstanceId=service-a2:9501,HostName=service-a2,IpAddr=172.23.0.7,Status=UP,IsUnsecurePortEnabled=True,Port=9501,IsSecurePortEnabled=False,SecurePort=443,VipAddress=service-test-A,SecureVipAddress=service-test-A,ActionTy
pe=ADDED]
      GetInstances returning: Instance[InstanceId=service-a:9500,HostName=service-a,IpAddr=172.23.0.6,Status=UP,IsUnsecurePortEnabled=True,Port=9500,IsSecurePortEnabled=False,SecurePort=443,VipAddress=service-test-A,SecureVipAddress=service-test-A,ActionType
=ADDED]

requestId: 0HLGHA1ADHD30:00000002, previousRequestId: no previous request id, message: Downstream url is http://service-a2:9501/api/values
```

The load Balancing is working and it Downstream url is correct. Some how this happen.

```
Error making http request, exception: System.Net.Http.HttpRequestException: Connection refused ---> System.Net.Sockets.SocketException: Connection refused
         at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)

Error Code: UnableToCompleteRequestError Message: Error making http request, exception: System.Net.Http.HttpRequestException: Connection refused ---> System.Net.Sock
ets.SocketException: Connection refused
```

Then I try to install curl and check that api is working from testocelot container.

```
# curl --request GET http://service-a/api/values
["This Is Test Service A 1"]#
# curl --request GET http://service-a2/api/values
["This Is Service Test A 2222"]#
# curl --request GET http://service-b/api/values
["This IS SerVice Test BBBB"]#
```

I will try to find out more about Connection Refused Issue. But if you have some suggestion i will happy to hear it. Thank you Tom

**Comment by TomPallister** [comment]
@deadmandrive it might be something to do with TLS, are you using https to connect to the services from Ocelot?

**Comment by TomPallister** [comment]
Ok cool, do you use docker compose btw?

**Comment by deadmandrive** [comment]
@TomPallister I use docker-compose on some services (eureka-server , config-server ,rabbitmq,zipkinserver) and some in docker command in power-shell (dotnet core service,Ocelot-Gateway)

**Comment by TomPallister** [comment]
@deadmandrive I would put everything into docker compose if I was you because that will set up all the networking between the services correctly. Not sure if there is a reason you cant do this though!!

**Comment by deadmandrive** [comment]
@TomPallister I try that before and found problem that all dotnet service not register with eureka-server but I might give it a try again.

**Comment by Esi1984** [comment]
same problem for me!
I got this Error on log:

info: Ocelot.RateLimit.Middleware.ClientRateLimitMiddleware[0]
      requestId: 0HLSC9H156ML7:00000001, previousRequestId: no previous request id, message: EndpointRateLimiting is not enabled for /api/Hello
info: Ocelot.Authentication.Middleware.AuthenticationMiddleware[0]
      requestId: 0HLSC9H156ML7:00000001, previousRequestId: no previous request id, message: No authentication needed for /mygate/Hello
info: Ocelot.Authorisation.Middleware.AuthorisationMiddleware[0]
      requestId: 0HLSC9H156ML7:00000001, previousRequestId: no previous request id, message: /api/Hello route does not require user to be authorised
warn: Ocelot.Requester.Middleware.HttpRequesterMiddleware[0]
      requestId: 0HLSC9H156ML7:00000001, previousRequestId: no previous request id, message: Error making http request, exception: System.Net.Http.HttpRequestException: **Cannot assign requested address**
       ---> System.Net.Sockets.SocketException (99): Cannot assign requested address
         at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
         --- End of inner exception stack trace ---
         at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
         at System.Net.Http.DiagnosticsHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
         at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
         at Ocelot.Requester.HttpClientHttpRequester.GetResponse(DownstreamContext context)
warn: Ocelot.Responder.Middleware.ResponderMiddleware[0]
      requestId: 0HLSC9H156ML7:00000001, previousRequestId: no previous request id, message: Error Code: UnableToCompleteRequestError Message: Error making http request, exception: System.Net.Http.HttpRequestException: Cannot assign requested address
       ---> System.Net.Sockets.SocketException (99): Cannot assign requested address
         at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
         --- End of inner exception stack trace ---
         at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
         at System.Net.Http.DiagnosticsHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
         at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
         at Ocelot.Requester.HttpClientHttpRequester.GetResponse(DownstreamContext context) errors found in ResponderMiddleware. Setting error response for request path:/mygate/Hello, request method: GET

**Comment by Esi1984** [comment]
My Ocelot GateWay Can't assign requested address through the Docker 
but it works correct when I run containers out of Docker 
**has Ocelot any problem on Docker?**

**Comment by alionur07** [comment]
hi i have same issue. 

My Ocelot Gateway doesn't work but my service who works in the k8 pod is work.

does any one solve

**Comment by pacifyin** [comment]
So Bad Gateway. Not Support Docker and Still Load localhost:500 .

**Comment by RavishKumar3788** [comment]
Same issue. Please help us to solve this issue.

info: Ocelot.RateLimit.Middleware.ClientRateLimitMiddleware[0]
      requestId: 0HMA0B2J418UN:00000001, previousRequestId: no previous request id, message: EndpointRateLimiting is not enabled for /api/v1/cms142/{everything}
info: Ocelot.Authentication.Middleware.AuthenticationMiddleware[0]
      requestId: 0HMA0B2J418UN:00000001, previousRequestId: no previous request id, message: No authentication needed for /cms142/getapiname
info: Ocelot.Authorisation.Middleware.AuthorisationMiddleware[0]
      requestId: 0HMA0B2J418UN:00000001, previousRequestId: no previous request id, message: /api/v1/cms142/{everything} route does not require user to be authorised
warn: Ocelot.Responder.Middleware.ResponderMiddleware[0]
      requestId: 0HMA0B2J418UN:00000001, previousRequestId: no previous request id, message: Error Code: ConnectionToDownstreamServiceError Message: Error connecting to downstream service, exception: System.Net.Http.HttpRequestException: No connection could be made because the target machine actively refused it.
       ---> System.Net.Sockets.SocketException (10061): No connection could be made because the target machine actively refused it.
         at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
         --- End of inner exception stack trace ---
         at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
         at System.Net.Http.DiagnosticsHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
         at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
         at Ocelot.Requester.HttpClientHttpRequester.GetResponse(HttpContext httpContext) errors found in ResponderMiddleware. Setting error response for request path:/cms142/getapiname, request method: GET

**Comment by YuBin8** [comment]
> 

have you fix the problem？ would you pls share the solution?

**Comment by YuBin8** [comment]
> Same issue. Please help us to solve this issue.
> 
> info: Ocelot.RateLimit.Middleware.ClientRateLimitMiddleware[0] requestId: 0HMA0B2J418UN:00000001, previousRequestId: no previous request id, message: EndpointRateLimiting is not enabled for /api/v1/cms142/{everything} info: Ocelot.Authentication.Middleware.AuthenticationMiddleware[0] requestId: 0HMA0B2J418UN:00000001, previousRequestId: no previous request id, message: No authentication needed for /cms142/getapiname info: Ocelot.Authorisation.Middleware.AuthorisationMiddleware[0] requestId: 0HMA0B2J418UN:00000001, previousRequestId: no previous request id, message: /api/v1/cms142/{everything} route does not require user to be authorised warn: Ocelot.Responder.Middleware.ResponderMiddleware[0] requestId: 0HMA0B2J418UN:00000001, previousRequestId: no previous request id, message: Error Code: ConnectionToDownstreamServiceError Message: Error connecting to downstream service, exception: System.Net.Http.HttpRequestException: No connection could be made because the target machine actively refused it. ---> System.Net.Sockets.SocketException (10061): No connection could be made because the target machine actively refused it. at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken) --- End of inner exception stack trace --- at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken) at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken) at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken) at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken) at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken) at System.Net.Http.DiagnosticsHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts) at Ocelot.Requester.HttpClientHttpRequester.GetResponse(HttpContext httpContext) errors found in ResponderMiddleware. Setting error response for request path:/cms142/getapiname, request method: GET

have you fix the problem？ would you pls share the solution?
