### ISSUE TITLE
Configuration can do a little bit

### ISSUE THREAD

**Issue by iexapl** [ThreeMammals/Ocelot#581]
## Expected Behavior / New Feature
1, Reroutes elements can be added to the Title describes what this route is a micro-service, easy to generate Swagger route and its description;
2, Request aggregation configuration can do a little bit, do not rely on reroutes node, Reroutekeys refactoring as:
    {
         "Key": {
         "ServiceName":  "string",//value corresponds to ServiceName in reroutes
         "UpstreamRequestUrl":  "string",//value relative to upstreampathtemplate real request path in reroutes
     "HttpMethod":  "post"//value is get,post,put,delete ...
}
} 
Additionally, you can add Claims to Claims, Claims to Headers, Claims to Query String, Claims to Request Body ...

## Steps to Reproduce the Problem

  1.
  1.
  1.

## Specifications

  - Version:
  - Platform:
  - Subsystem:

**Comment by iexapl** [comment]
Lower configuration costs without having to configure multiple nodes in reroutes for each aggregation request

**Comment by TomPallister** [comment]
@iexapl could you do a full example of how this would work?
