### ISSUE TITLE
Aggregator is not used by ocelot

### ISSUE THREAD

**Issue by REPRESSION** [ThreeMammals/Ocelot#582]
Hello,

I followed the documentation on how to implement a custom Aggregator, but for some reasons it isn't used by ocelot. Here is what I've done :

ocelot.json
```
  "Aggregates": [
    {
      "ReRouteKeys": [
        "AuthenticationSwaggerFile"
      ],
      "UpstreamPathTemplate": "/testtest",
      "Aggregator": "SwaggerFilesAggregator"

    }
  ],
```

Aggregator file
```
    class SwaggerFilesAggregator : IDefinedAggregator
    {
        public Task<DownstreamResponse> Aggregate(List<DownstreamResponse> responses)
        {
            Console.WriteLine("This should be written but isn't");
            return new Task<DownstreamResponse>(() =>
            {
                return responses[0];
            });
        }
    }
```

Startup.cs
```
            services.AddOcelot()
                .AddSingletonDefinedAggregator<SwaggerFilesAggregator>();
```

I always get the Result of the first ReRouteKey, even if I change `return responses[0]` tu `return null` in the Aggregator file. It seems like the line `"Aggregator": "SwaggerFilesAggregator"` is ignored.

**Comment by TomPallister** [comment]
@REPRESSION mmmm can you share your source code or at least program.cs, startup.cs and json config and I will look further.

**Comment by REPRESSION** [comment]
I found out what my problem was, I had only one entry in ReRouteKeys.

**Comment by TomPallister** [comment]
OK cool, glad its sorted :)
