### ISSUE TITLE
Routing to multiple Views, not just APIs

### ISSUE THREAD

**Issue by michiwib** [ThreeMammals/Ocelot#588]
## Expected Behavior / New Feature

I am trying to set up Ocelot to route to separate views, but have only seen examples of routing to different apis (makes sense, it is an API Gateway after all). Is there a way for Ocelot to have two downstream hosts, for example Google.com and Bing.com. set to the Ocelot URL, localhost:5000. In this example, I want to connect to Google with the UpstreamPathTemplate /Google/{url} and connect to Bing with /Bing/{url}.

## Actual Behavior / Motivation for New Feature

If I set a website such as the Downstream host then I am just redirected to that website. I have several tools/app services that can be accessed under different URL's, and I am trying to use Ocelot to connect to all of them as well as to work with IdentityServer4. The tools are related, so I want to be able to access them using Ocelot like so, localhost:5000/tool1 || localhost:5000/tool2. If I set the upstream paths as such, then I cannot load any content. I can access one of the services if I set the upstreampathtemplate to {url}

## Specifications

Here is a snippet of my ocelot.json. If i try to go to localhost:5000/tool2 then none of the content will load.

    {
      "DownstreamHostAndPorts": [
        {
          "Host": "localhost",
          "Port": 4200
        }
      ],
      "DownstreamPathTemplate": "/{url}",
      "UpstreamPathTemplate": "/tool2/{url}",
      "UpstreamHttpMethod": [ "Get", "Post", "Put", "Delete" ],
      "ReRouteIsCaseSensitive": false,
      "DownstreamScheme": "http"
    }

  - Version: 10.0.4
  - Platform:
  - Subsystem:

Thanks for working on this great project!

**Comment by TomPallister** [comment]
@michiwib this should work OK there are people who use Ocelot to route to pages that return HTML etc, there might be an issue loading subsequent assets though. Can you share your program.cs / startup.cs and full json configuration so I can take a closer look?

**Comment by michiwib** [comment]
Thanks for getting back to me about this, it is good to know that this is possible. The browser developer tools show that some of the files are missing, so I may be having issues loading associated assets. 

Here is my ocelot.json:
`{
  "ReRoutes": [
    {
      "DownstreamPathTemplate": "/api/{url}",
      "UpstreamPathTemplate": "/service1/{url}",
      "UpstreamHttpMethod": [ "Get", "Post", "Put", "Delete" ],
      "DownstreamHostAndPorts": [
        {
          "Host": "localhost",
          "Port": 64228
        }
      ],
      "DownstreamScheme": "http"
    },
    {
      "DownstreamPathTemplate": "/{url}",
      "UpstreamPathTemplate": "/service2/{url}",
      "UpstreamHttpMethod": [ "Get", "Post", "Put", "Delete" ],
      "DownstreamHostAndPorts": [
        {
          "Host": "localhost",
          "Port": 4200
        }
      ],
      "DownstreamScheme": "http"
    }
  ],
  "GlobalConfiguration": {
    "BaseUrl": "http://localhost:5000"
  }
}`

My Program.cs:
`namespace TestGatewayFromScratch
{
    public class Program
    {
        public static void Main(string[] args)
        {
            new WebHostBuilder()
               .UseKestrel()
               .UseContentRoot(Directory.GetCurrentDirectory())
               .ConfigureAppConfiguration((hostingContext, config) =>
               {
                   config
                       .SetBasePath(hostingContext.HostingEnvironment.ContentRootPath)
                       .AddJsonFile("appsettings.json", true, true)
                       .AddJsonFile($"appsettings.{hostingContext.HostingEnvironment.EnvironmentName}.json", true, true)
                       .AddJsonFile("ocelot.json")
                       .AddEnvironmentVariables();
               })
               .ConfigureServices(s => {
                   s.AddOcelot();
               })
               .ConfigureLogging((hostingContext, logging) =>
               {
                //add your logging
            })
               .UseIISIntegration()
               .Configure(app =>
               {
                   app.UseOcelot().Wait();
               })
               .Build()
               .Run();
        }
    }
}`

And my Startup.cs:
`namespace TestGatewayFromScratch
{
    public class Startup
    {
        // This method gets called by the runtime. Use this method to add services to the container.
        // For more information on how to configure your application, visit https://go.microsoft.com/fwlink/?LinkID=398940
        public void ConfigureServices(IServiceCollection services)
        {
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }

            app.Run(async (context) =>
            {
                await context.Response.WriteAsync("");
            });
        }
    }
}`

**Comment by TomPallister** [comment]
@michiwib there could be a few things causing you issues here.

If you change your config to say

```json
{
  "ReRoutes": [{
      "DownstreamPathTemplate": "/{url}",
      "UpstreamPathTemplate": "/service1/{url}",
      "UpstreamHttpMethod": ["Get", "Post", "Put", "Delete"],
      "DownstreamHostAndPorts": [{
        "Host": "threemammals.com",
        "Port": 80
      }],
      "DownstreamScheme": "http"
    },
    {
      "DownstreamPathTemplate": "/{url}",
      "UpstreamPathTemplate": "/service2/{url}",
      "UpstreamHttpMethod": ["Get", "Post", "Put", "Delete"],
      "DownstreamHostAndPorts": [{
        "Host": "threemammals.com",
        "Port": 80
      }],
      "DownstreamScheme": "http"
    }
  ],
  "GlobalConfiguration": {
    "BaseUrl": "http://localhost:5000"
  }
}
``` 

and then call http://localhost:5000/service1/ocelot you should see the Ocelot site load but some things will be broken such as images etc.

if you call http://localhost:5000/service1/ you will get a 404 because Ocelot will only match on /service1/something when you have configured /service1/{url}. you would need something like /service1/ configured if you want something to load for root.

In terms of the assets not coming down you basically need to set up ReRoutes specifically for them. 

Does that make any sense?

**Comment by michiwib** [comment]
Ah, that makes sense. I was able to get this working with a similar config to what you suggested, and I could get multiple downstream hosts to work by adding another reroute that handles the static assets for each of them.

**Comment by TomPallister** [comment]
OK awesome :D
