### ISSUE TITLE
Unable to start Ocelot because using ServiceDiscoveryOptions but no ServiceDiscoveryFinderDelegate

### ISSUE THREAD

**Issue by Marusyk** [ThreeMammals/Ocelot#596]
I've just updated package from 8.0.0 to 11.0.2 and got this error:

> Unable to start Ocelot, errors are: Unable to start Ocelot because either a ReRoute or GlobalConfiguration are using ServiceDiscoveryOptions but no ServiceDiscoveryFinderDelegate has been registered in dependency injection container. Are you missing a package like Ocelot.Provider.Consul and services.AddConsul() or Ocelot.Provider.Eureka and services.AddEureka()?

I do not use ServiceDiscovery feature. My config is

```
"ReRoutes": [
    {
      "DownstreamPathTemplate": "/profile",
      "DownstreamScheme": "http",
      "UpstreamPathTemplate": "/profile",
      "UpstreamHttpMethod": [ "Get" ],
      "DownstreamHostAndPorts": [
        {
          "Host": "localhost",
          "Port": 5001
        }
      ]
    }
  ],
  "GlobalConfiguration": {
    "RequestIdKey": "X-RequestId",
    "BaseUrl": "http://localhost:58134"
  }
```

## Specifications

  - Version: 11.0,2
  - Platform: Win10
  - Subsystem: ASP.NET CORE  2.1

**Comment by Marusyk** [comment]
I found 

`var useServiceDiscovery = !string.IsNullOrEmpty(fileReRoute.ServiceName);`

So, now if I add `ServiceName` property then I need to use ServiceDiscovery. But why? I'm using that property for name service (for swagger documentations). It's not obvious that property  `ServiceName` 
 enables ServiceDiscovery , isn't it? Where is `UseServiceDiscovery`?

**Comment by TomPallister** [comment]
@Marusyk Yeh maybe it is not a good name, I might change it to KeyForServiceDiscovery, There is a Key property on the ReRoute you can use for swagger maybe?

**Comment by Marusyk** [comment]
@TomPallister, thanks for quick response. 
Yes, Key property will help.  Thx
