### ISSUE TITLE
Duplicate response in aggregation if reRouteKeys are common b/w aggregation sets

### ISSUE THREAD

**Issue by Pradeepkumar-kn** [ThreeMammals/Ocelot#597]
## Expected Behavior / New Feature
If
reRoutes keys are [a,b,c,d]
And
Aggregates is[ { "ReRouteKeys":[a,b,c,d], "UpstreamPathTemplate": "/EmpDetail/IN/{userid}" }, { "ReRouteKeys":[a,b], "UpstreamPathTemplate": "/EmpDetail/US/{userid}" }  ]

if upstream request url is http://ocelotservice/EmpDetail/US/pradeep then expected response is response of key a,b 

## Actual Behavior / Motivation for New Feature
but response is getting repeated i.e  i am getting response of keys a,b in following order a,b,a,b. 

The issues seems to be because of below shown foreach loop since its adding ocelotReRoute  back to reRoutes and the same reRoutes is getting passed to SetUpAggregateReRoute function, its finding matching keys which got resolved in the first iteration.

Class: FileInternalConfigurationCreator
Method: private async Task<Response<IInternalConfiguration>> SetUpConfiguration(FileConfiguration fileConfiguration)
      
            **foreach (var aggregate in fileConfiguration.Aggregates)
            {
                var ocelotReRoute = SetUpAggregateReRoute(reRoutes, aggregate, fileConfiguration.GlobalConfiguration);
               reRoutes.Add(ocelotReRoute);  //<-- adding to separate collection later appending to reRoutes should solve the issue.
            }**

            reRoutes.AddRange(aggrReRoutes);

## Steps to Reproduce the Problem
 Use below ocelot.json 
{
  "ReRoutes": [
    {
      "DownstreamPathTemplate": "/api/values?MailId={userid}",
      "UpstreamPathTemplate": "/key1data/{userid}",
      "UpstreamHttpMethod": [
        "Get"
      ],
      "ServiceName": "",
      "DownstreamScheme": "http",
      "DownstreamHostAndPorts": [
        {
          //Todo: Use load balancer host+port
          "Host": "localhost",
          "Port": 8571
        }
      ],
      "UseServiceDiscovery": false,
      "Key": "key1"
    },
    {
      "DownstreamPathTemplate": "/api/values?MailId={userid}",
      "UpstreamPathTemplate": "/key2data/{userid}",
      "UpstreamHttpMethod": [
        "Get"
      ],
      "ServiceName": "",
      "DownstreamScheme": "http",
      "DownstreamHostAndPorts": [
        {
          //Todo: Use load balancer host+port
           "Host": "localhost",
          "Port": 8571
        }
      ],
      "UseServiceDiscovery": false,
      "Key": "key2"
    },
    {
      "DownstreamPathTemplate": "/api/values?MailId={userid}",
      "UpstreamPathTemplate": "/key3data/{userid}",
      "UpstreamHttpMethod": [
        "Get"
      ],
      "ServiceName": "",
      "DownstreamScheme": "http",
      "DownstreamHostAndPorts": [
        {
          //Todo: Use load balancer host+port
           "Host": "localhost",
          "Port": 8571
        }
      ],
      "UseServiceDiscovery": false,
      "Key": "key3"
    },
    {
      "DownstreamPathTemplate": "/api/values?MailId={userid}",
      "UpstreamPathTemplate": "/key4data/{userid}",
      "UpstreamHttpMethod": [
        "Get"
      ],
      "ServiceName": "",
      "DownstreamScheme": "http",
      "DownstreamHostAndPorts": [
        {
          //Todo: Use load balancer host+port
           "Host": "localhost",
          "Port": 8571
        }
      ],
      "UseServiceDiscovery": false,
      "Key": "key4"
    }
  ],

  "Aggregates": [
    {
      "ReRouteKeys": [
        "key1",
        "key2",
        "key3",
        "key4"
      ],
      "UpstreamPathTemplate": "/EmpDetail/IN/{userid}"
    },
    {
      "ReRouteKeys": [
        "key1",
        "key2"
      ],
      "UpstreamPathTemplate": "/EmpDetail/US/{userid}"
    }
  ],

  "GlobalConfiguration": {
    "RequestIdKey": "CorrelationID"
  }
}

Now request for url which matches /EmpDetail/US/{userid} upstream template(2nd aggregation url). The response that we get is from  keys "key1", "key2","key1", "key2" (key 1 & key2 is repeated) . Response should have been just "key1", "key2" reponses

## Specifications

  - Version:11.0.2
  - Platform:
  - Subsystem:

**Comment by TomPallister** [comment]
@Pradeepkumar-kn mmmm this looks like a genuine issue I will check ASAP! Thanks :)

**Comment by TomPallister** [comment]
@Pradeepkumar-kn would you be able to share your json config to save me time making one? :()

**Comment by Pradeepkumar-kn** [comment]
Hi,

Please find sample ocelot.json that i am using.

Thanks
Pradeep

**Comment by TomPallister** [comment]
Yep sorry I missed that :( long day!

**Comment by TomPallister** [comment]
@Pradeepkumar-kn I had already started refactoring this code in #600 and fixed the bug :o 

I will get the release out ASAP and let you know when fixed. For now I suggest just fork Ocelot and use that until fix is in NuGet package.

**Comment by TomPallister** [comment]
fixed in 11.0.3, any problems let me know
