### ISSUE TITLE
QosOptions.TimeoutValue is not being taken into account

### ISSUE THREAD

**Issue by Deilan** [ThreeMammals/Ocelot#604]
## Steps to Reproduce the Problem
As per [QoS docs section](https://ocelot.readthedocs.io/en/latest/features/qualityofservice.html):
1. Install `Ocelot.Provider.Polly`
2. Add to `Startup#ConfigureServices` the following: `services.AddOcelot().AddPolly();`
3. Add a section into `ocelot.json`:
```json
  "QoSOptions": {
    "TimeoutValue": 1
  }
```
4. Send a request via Ocelot.
5. Wait for a response

## Expected Behavior
Downstream response time (e. g. > 100ms) is greater than an acceptable value (1ms). Downstream request should be cancelled and upstream request should be served with an appropriate error message.
Therefore `QosOptions.TimeoutValue` is being taken into account.

## Actual Behavior
Downstream response time (e. g. > 100ms) is greater than an acceptable value (1ms). Downstream request is not being cancelled and upstream request served with a downstream response.
Therefore `QosOptions.TimeoutValue` is not being taken into account.

## Specifications

  - Version: Ocelot `v11.0.2`, Ocelot.Provider.Polly `v0.1.0`
  - Platform: Windows 10 x64
  - Subsystem: ?

**Comment by TomPallister** [comment]
@Deilan I will check this out asap, should be working but might have been broken :( There is a test for this isn the Ocelot.Provider.Polly projet but who knows.

**Comment by TomPallister** [comment]
@Deilan this is a bug the code that is wrong is QoSOptions.cs

```chsharp
        public bool UseQos => ExceptionsAllowedBeforeBreaking > 0 && TimeoutValue > 0;
```

When you have your config Ocelot doesnt load the QosProvider because ExceptionsAllowedBeforeBreaking is 0. 

I will get this fixed ASAP as it is a bug. If you want a quick fix try set ExceptionsAllowedBeforeBreaking to something and it should work :/

**Comment by TomPallister** [comment]
fixed in 12.0.0, just released to NuGet

**Comment by xianrui69** [comment]
nuget vesion :19.0.2
	  "QoSOptions": {
		"ExceptionsAllowedBeforeBreaking":30,
		"TimeoutValue":300000
	  },

**Comment by xianrui69** [comment]
> @Deilan这是一个bug，错误的代码是QoSOptions.cs
> 
> ```
>         public bool UseQos => ExceptionsAllowedBeforeBreaking> 0&& TimeoutValue> 0;
> ```
> 
> 当你有你的配置时，Ocelot不会加载QosProvider，因为ExceptionsAllowedBeforeBreaking为0。
> 
> 我会尽快修复这个问题，因为它是一个错误。如果你想要一个快速的修复尝试设置ExceptionsAllowedBeforeBreaking的东西，它应该工作：/



> @Deilan this is a bug the code that is wrong is QoSOptions.cs
> 
> ```
>         public bool UseQos => ExceptionsAllowedBeforeBreaking > 0 && TimeoutValue > 0;
> ```
> 
> When you have your config Ocelot doesnt load the QosProvider because ExceptionsAllowedBeforeBreaking is 0.
> 
> I will get this fixed ASAP as it is a bug. If you want a quick fix try set ExceptionsAllowedBeforeBreaking to something and it should work :/

invalid in my code,Two parameters are still needed
