### ISSUE TITLE
Configurable timeout without using Polly

### ISSUE THREAD

**Issue by Deilan** [ThreeMammals/Ocelot#605]
## New Feature
Please let configurable timeout without using Polly provider.

## Motivation for New Feature
Polly is not always needed.

**Comment by TomPallister** [comment]
@Deilan this would be a new feature, I will mark it as such but I do not have time to work on it at the moment. 

However I would suggest just using Polly as I won't have time to do it anytime soon, unless you want to have a go yourself!

**Comment by eoware** [comment]
I know this is an old feature request, but I needed the same functionality. You can do this without having to do your own Ocelot fork/build. Copy and paste the HttpClientBuilder and HttpClientHttpRequester classes from the Github branch you are using into your project and rename the classes (MyHttpClientBuilder and MyHttpClientHttpRequester, for example). 

In HttpClientHttpRequester change this line to create your custom HttpClientBuilder:
` var builder = new MyHttpClientBuilder(_factory, _cacheHandlers, _logger);`

In your custom HttpClientBuilder, change the timeout to what you need:
` _defaultTimeout = TimeSpan.FromSeconds(600);`

In startup.cs, add this AFTER the call to 'AddOcelot':
`services.RemoveAll<IHttpRequester>();`

Then, somewhere after that, add:
`services.TryAddSingleton<IHttpRequester, MyHttpClientHttpRequester>();`

**Comment by raman-m** [comment]
@Deilan  Hi Michael!
Will **New AddOcelot extensions** in PR #1655 help you to overload Polly services in DI and inject your favorite ones?

**Comment by raman-m** [comment]
> @Deilan commented [on Sep 7, 2018](#issue-358122899)
Please let configurable timeout without using Polly provider.

We welcome you to contribute!
Feel free to reopen in future if you will have intention to contribute.
