### ISSUE TITLE
Always 200 response code in middlewares

### ISSUE THREAD

**Issue by allrameest** [ThreeMammals/Ocelot#607]
I'm trying to catch errors both with the built in middlewares and custom middlewares. But `context.Response.StatusCode` is always 200.

This issue seems to be about the same thing and should be solved: https://github.com/ThreeMammals/Ocelot/issues/370
But for me it doesn't work.

I've reproduced it in this repository:
https://github.com/allrameest/OcelotErrorHandling
If you start it and browse to http://localhost:7000/error or /whatever, the correct status code is sent to the client. But in the middleware it is 200.

**Comment by TomPallister** [comment]
@allrameest thanks for this, change was made before and it looks like ive somehow just steamrolled it :/ no idea why.

Will release this to NuGet ASAP.

**Comment by TomPallister** [comment]
fixed in 11.0.3, any problems let me know
