### ISSUE TITLE
Ocelot automatically redirects to micro service

### ISSUE THREAD

**Issue by ICLBS** [ThreeMammals/Ocelot#612]
can you force when to downstream a url instead when a request is sent to the gateway with ocelot? ex first validate that the parameters inserted by the user are correct and if validation is correct then downstream the url?

**Comment by TomPallister** [comment]
@ICLBS Im not 100% sure what you mean but Ocelot supports [authentication](https://ocelot.readthedocs.io/en/latest/features/authentication.html) and basic [authorisation](https://ocelot.readthedocs.io/en/latest/features/authorisation.html)..this might help?
