### ISSUE TITLE
[Question] Are API Keys supported?

### ISSUE THREAD

**Issue by dimitridaras** [ThreeMammals/Ocelot#616]
## Expected Behavior / New Feature
Can the gateway can be configured to allow access to downstream urls only if an api key is provided? A key would be generated for each client that need acess to the the gateway

## Actual Behavior / Motivation for New Feature
We would like to secure our endpoints so that only clients (_not users_) that provide the correct key can use them.
This is pretty common behaviour. Eg, see https://docs.apigee.com/api-platform/security/api-keys

**Comment by TomPallister** [comment]
@dimitridaras not at the moment, this would be a new feature. I will leave this issue open to record the fact it has been requested. 

If you wanted to try and implement this yourself as a middleware you can give it a go and then we could add it to Ocelot later maybe?

**Comment by TomPallister** [comment]
duplicate of #553
