### ISSUE TITLE
Running Ocelot on Service Fabric with ReverseProxy SSL enabled

### ISSUE THREAD

**Issue by gencay** [ThreeMammals/Ocelot#620]
## Expected Behavior / New Feature
When SF is running the reverseProxy(`HttpApplicationGatewayEndpoint`) on `https` I expect Ocelot to figure it out. Maybe I am missing a configuration, however the [documentation ](https://ocelot.readthedocs.io/en/latest/features/servicefabric.html)doesn't mention anything about it, either. @davidni I saw your comment on this issue #555. Were you actually able to run Ocelot using `https://localhost:19081`?

## Actual Behavior / Motivation for New Feature
Because there is no way to provide the serviceDiscoveryProvider scheme the discovery fails as my SF is not running reverse proxy on `http://localhost:19081` but `https://localhost:19081`

This is my stripped version of `ocelot.json`:
```
{
    "ReRoutes": [
      {
        "DownstreamPathTemplate": "/api/{all}",
        "DownstreamScheme": "http",
        "UpstreamPathTemplate": "/api/{all}",
        "UpstreamHttpMethod": [ "Get", "Post", "Delete", "Patch"],
        "ServiceName": "<MyApiServices>",
        "UseServiceDiscovery": true,
        "AuthenticationOptions": {
          "AuthenticationProviderKey": "<MyAuthProviderKey>",
          "AllowedScopes": []
        }
      },
      {
        "DownstreamPathTemplate": "/{url}",
        "DownstreamScheme": "http",
        "UpstreamPathTemplate": "/{url}",
        "UpstreamHttpMethod": [
          "Get"
        ],
        "ServiceName": "<MyFrontendService>",
        "UseServiceDiscovery": true
      }
    ],
    "GlobalConfiguration": {
        "ServiceDiscoveryProvider": {
            "Host": "localhost",
            "Port": 19081,
            "Type": "ServiceFabric"
        }
    }
}
```

I am using version 10.0.3

**Comment by TomPallister** [comment]
@gencay Ocelot uses DownstreamScheme to decide if it calls on https or http at the moment. In your config you have set http at the moment!

Try changing it to https and hopefully it will work!

**Comment by davidni** [comment]
There's really no reason to call Reverse Proxy over https -- the communication happens on the loopback interface and will never leave your machine. I don't think Reverse Proxy even supports listening on localhost over https. It is analogous to trying to encrypt the HttpRequestMessage before sending it to HttpClient.SendAsync. If you cannot trust your local execution environment to process private information, you have bigger problems (and using https on localhost would only be the tip of the iceberg 😄)

To make sure you have encryption in transit, it is enough to ensure that the service you are contacting through Reverse Proxy exposes an https (and not http) endpoint. Then Reverse Proxy will make the outgoing connection over https. You can also specify how much validation you want Reverse Proxy to perform on the SSL cert received from the target service. See `ApplicationCertificateValidationPolicy` [here](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-reverseproxy-configure-secure-communication)

**Comment by TomPallister** [comment]
@davidni thanks for your insight!

**Comment by davidni** [comment]
@gencay my previous comment may have been incorrect (pending investigation -- I'll update this once I have more clarity on the subject). I have learned that Reverse Proxy might refuse to connect to https services unless Reverse Proxy itself has been configured to listen on https. If that turns out to be true, you will be able to create a custom `IHttpRequester` that modifies the outgoing request to use https before sending it.

**Comment by Tadimsky** [comment]
@davidni did you ever come to a conclusion on this one?

**Comment by davidni** [comment]
@Tadimsky  It seems like i made a wrong assumption before -- apparently for reverse Proxy to proxy over https, it must also listen on https. I don't see why it was designed this way since localhost encryption adds no security, but that doesn't matter here. Getting that to work with Ocelot will likely require some (scoped) brain surgery to issue https requests to localhost:19081 and ignore cert validation errors. A custom `IHttpRequester` would do it.

**Comment by ELymar** [comment]
Hi guys,
My team appears to be running into a similar issue. We have a reverse proxy in our cluster with https traffic on port 443. We can't seem to find any combination of Host, Port, and  Scheme that doesn't return a 502 status code. Config of localhost and 19081 works for a local cluster, but not in our staging cluster. @davidni or @TomPallister  did you guys happen to find a workaround or configuration that works? Appreciate any help!

**Comment by ELymar** [comment]
It appears we found a configuration that works. 
Host: our fully qualified domain name
Port: 443
Scheme: https
DownstreamScheme: https
Not sure if this is ideal, but this seems to be working.
