### ISSUE TITLE
[Question]  How does authentication work?

### ISSUE THREAD

**Issue by jlcarpenter** [ThreeMammals/Ocelot#621]
I'm now trying to integrate authentication using auth0.  I have followed documentation provided by adding the following to the configuration file.

       "AuthenticationOptions": {
        "AuthenticationProviderKey": "Auth0",
        "AllowedScopes": ["read:item" ] 
      }

and the audience and authority provided by Auth0 to Startup when calling AddJwtBearer.  I still get a 401.  I am using postman and passing the bearer token as the authorization in the request.  I feel like I am missing another key piece here or not understanding how it all works together.

**Comment by TomPallister** [comment]
@jlcarpenter set your log level to trace and see what gets output by Ocelot. Paste it here if it doesnt make any sense!

If you could paste the code where you add the auth0 stuff to startup minus any secrets as well that might help.

**Comment by jlcarpenter** [comment]
@TomPallister Here is my log

> dbug: Ocelot.DownstreamRouteFinder.Middleware.DownstreamRouteFinderMiddleware[0]
      requestId: 80000008-0005-fe00-b63f-84710c7967bb, previousRequestId: no previous request id, message: Upstream url path is /api/values
dbug: Ocelot.DownstreamRouteFinder.Middleware.DownstreamRouteFinderMiddleware[0]
      requestId: 80000008-0005-fe00-b63f-84710c7967bb, previousRequestId: no previous request id, message: downstream templates are /v1/{everything}
info: Ocelot.RateLimit.Middleware.ClientRateLimitMiddleware[0]
      requestId: 80000008-0005-fe00-b63f-84710c7967bb, previousRequestId: no previous request id, message: EndpointRateLimiting is not enabled for /v1/{everything}
info: Ocelot.Authentication.Middleware.AuthenticationMiddleware[0]
      requestId: 80000008-0005-fe00-b63f-84710c7967bb, previousRequestId: no previous request id, message: /api/values is an authenticated route. AuthenticationMiddleware checking if client is authenticated
warn: Ocelot.Authentication.Middleware.AuthenticationMiddleware[0]
      requestId: 80000008-0005-fe00-b63f-84710c7967bb, previousRequestId: no previous request id, message: Client has NOT been authenticated for /api/values and pipeline error set. Request for authenticated route /api/values by  was unauthenticated
warn: Ocelot.Authentication.Middleware.AuthenticationMiddleware[0]
      requestId: 80000008-0005-fe00-b63f-84710c7967bb, previousRequestId: no previous request id, message: Request for authenticated route /api/values by  was unauthenticated
warn: Ocelot.Responder.Middleware.ResponderMiddleware[0]
      requestId: 80000008-0005-fe00-b63f-84710c7967bb, previousRequestId: no previous request id, message: Error Code: UnauthenticatedError Message: Request for authenticated route /api/values by  was unauthenticated errors found in ResponderMiddleware. Setting error response for request path:/api/values, request method: GET
dbug: Ocelot.Errors.Middleware.ExceptionHandlerMiddleware[0]
      requestId: 80000008-0005-fe00-b63f-84710c7967bb, previousRequestId: no previous request id, message: ocelot pipeline finished
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 253.7693ms 401

Here is my Startup Setup

> services.AddAuthentication()
        .AddJwtBearer("Auth0-KeyVault", x =>
        {
          x.Authority = "mydomain.auth0.com";
          x.Audience = "https://api.mydomain.com/myapi";
          if (_environment.IsEnvironment("Local"))
            x.RequireHttpsMetadata = false;
        });

**Comment by jlcarpenter** [comment]
It looks like my problem that right now I am trying to short circuit the authentication process.  I have not authenticated the user at this point, but was trying to simply take the bearer token provided in the Quick Start API by Auth0 and pass it along in the request.

**Comment by TomPallister** [comment]
@jlcarpenter Your config has `Auth0` as your `AuthenticationProviderKey` and you are registering your auth handler with the key `Auth0-KeyVault`, Is this correct? Ocelot should fail to start under these conditions.

I'm not sure what you mean by short circuit? Have you solved this issue? :O

**Comment by jlcarpenter** [comment]
I have not resolved the issue.  When I say short circuit, I was saying that at this point I have not authenticated the user.  I am simply taking the bearer token provided by Auth0 and using it in the request.  I believe the problem by looking at the response and the code is that I do not have a user (much less one that has been authenticated) in the request.

**Comment by jlcarpenter** [comment]
Was able to resolve the problem! I included some code for AD authentication without realizing it.

**Comment by TomPallister** [comment]
@jlcarpenter good stuff :)
