### ISSUE TITLE
Routing to Downstream Root Problem with {everything}

### ISSUE THREAD

**Issue by bulentrahimkazanci** [ThreeMammals/Ocelot#622]
## Expected Behavior / New Feature

I expect that every url should match.

## Actual Behavior / Motivation for New Feature

When I send a post request, I got "Unable to find downstream route for path" error.

## Steps to Reproduce the Problem

I have the routing definition as follows:

`    {
      "DownstreamPathTemplate": "/api/schedules/{everything}",
      "UpstreamPathTemplate": "/ib/schedules/{everything}",
      "UpstreamHttpMethod": [
        "Get",
        "Post",
        "Options",
        "Put",
        "Delete"
      ],
      "ServiceName": "ScheduleApi",
      "DownstreamScheme": "http",
      "DownstreamHostAndPorts": [
        {
          "Host": "ScheduleApiHost",
          "Port": 80
        }
      ]
    },`

When I send GET request to `/api/schedules/200`, it works fine but if the request is POST to `/api/schedules`, it gives the error "Unable to find downstream route for path" error.

I resolve the problem by separating POST operation's definition and gave it higher priority from the one that I shared above but it doesn't look elegant and in this situation {everything} does not mean that it routes every matching url for me. Right now, what I would like to learn is whether it is a bug or not.

## Specifications

  - Version: 10.0.4
  - Platform: Windows 10

**Comment by TomPallister** [comment]
@bulentrahimkazanci this is the current behaviour of Ocelot.

When you post to /api/schedules it doesn't match because your catch all is /api/schedules/{everything} so Ocelot will only match on /api/schedules/something.

That is why in the docs /{everything} is recommended if you want to catch everything!

**Comment by Fabiest** [comment]
Hello,

I don't agree with this approach:

if i want to forward /foodRecipes* to /api/recipes*, the configuration you suggest means /* -> /api/recipes right? So it doesn't matter if i do /xyz, it will be forwarded to /api/recipes...

I was expecting to be able to configure it like /foodRecipes{everything} to /api/recipes{everything}.

This is needed if i want to hide the name in the backend or make it more friendly.
