### ISSUE TITLE
How to get RemoteIPAddress in Asp.Net core 2.1 Service behind ocelot

### ISSUE THREAD

**Issue by bishopjun11** [ThreeMammals/Ocelot#623]
## Expected Behavior / New Feature
Get User Real IP Address

## Actual Behavior / Motivation for New Feature
Get Ocelot gateway IP Address

## Steps to Reproduce the Problem

  1.Ocelot route http request to my asp.net core 2.1 service;
  2.In asp.net core 2.1 controller get remoteIPAddress from method "var ipAddress = _httpContextAccessor.HttpContext.Connection.RemoteIpAddress.ToString();"

## Specifications

  - Version:9.0.0
  - Platform:CentOS7
  - Subsystem:

**Comment by TomPallister** [comment]
@bishopjun11 the best way for this to happen would be an x forwarded for header. I think this is a new feature. I will get round to it eventually but for now if you want this you would have to implement it yourself either your own piece of middleware that adds it as a header and then ocelot will automatically forward it.

**Comment by TomPallister** [comment]
In terms of implementing this use the header placeholder stuff

**Comment by TomPallister** [comment]
@bishopjun11 Yep that should work fine, good idea. Btw if you are using nginx already you might not need Ocelot! What are you using it for?

**Comment by TomPallister** [comment]
Released in 12.0.1, should be on NuGet soon :)
