### ISSUE TITLE
 when i install  Ocelot version 11.0.3   why  App.Metrics can not get any log..

### ISSUE THREAD

**Issue by hongwei7458** [ThreeMammals/Ocelot#625]
## Actual Behavior / Motivation for New Feature
 a website with App.Metrics   is work  ,when i add Ocelot ,  Ocelot is work, but  App.Metrics can not get 
request log...

## Steps to Reproduce the Problem

  1.  getway solution  add App.Metrics.  is work 
  1. when i add Ocelot   is not work , 
  1

## Specifications

  - Version: Ocelot :11.0.3
  - Platform: windows
  - Subsystem:

**Comment by TomPallister** [comment]
@hongwei7458 I don't anything about App.Metrics I'm afraid. Ocelot is just a normal asp.net core app so I don't know why there framework doesnt work with it. 

My best guess might be because Ocelot implements its own DiagnosticListener for tracing and maybe they need to register a version of this for App.Metrics to work?

**Comment by hongwei7458** [comment]
[App.Metrics](https://www.app-metrics.io/)    it  gathering request log and  Insert  InfluxDB 
when i request  gateway site  ,  the request how to tracing.

**Comment by hongwei7458** [comment]
> @hongwei7458 I don't anything about App.Metrics I'm afraid. Ocelot is just a normal asp.net core app so I don't know why there framework doesnt work with it.
> 
> My best guess might be because Ocelot implements its own DiagnosticListener for tracing and maybe they need to register a version of this for App.Metrics to work?

i find the demo with App.Metrics and ocelot    but  it use Ocelot 2.0

**Comment by TomPallister** [comment]
@hongwei7458 can you send me a link to the demo for Ocelot 2.0? I might be able to identify what has changed.
