### ISSUE TITLE
Is it possible to add a security module

### ISSUE THREAD

**Issue by aqa510415008** [ThreeMammals/Ocelot#628]
Is it possible to add a security module?
IP whitelist, blacklist
AuthorizationToken blacklist

**Comment by TomPallister** [comment]
@aqa510415008 yes it would be possible. This would be a new feature!

You could have a go at implementing this as a piece of middleware and seeing if it works in your project. Then maybe we could add it to Ocelot?

**Comment by aqa510415008** [comment]
@TomPallister  I have started to integrate Ocelot. I discussed feasibility with @geffzhang yesterday. IP whitelists and blacklists are configured through Ocelot, and other security components are extensible. When I submit the PR, you can see if it works.

**Comment by TomPallister** [comment]
I have reviewed the PR, looks good, changes requested! 

Thank you for this. I really appreciate it.

**Comment by TomPallister** [comment]
Ok I will wait for tests :)

**Comment by aqa510415008** [comment]
Ocelot AuthorizationToken的安全保护扩展

Ocelot.Security.AuthorizationToken.EntityFramework

**Comment by TomPallister** [comment]
Released in 12.0.1, should be on NuGet soon :)
