### ISSUE TITLE
I would suggest an error if StatusCode or Response.Body is set for other middleware downstream.

### ISSUE THREAD

**Issue by aqa510415008** [ThreeMammals/Ocelot#630]
I would suggest an error if StatusCode or Response.Body is set for other middleware downstream.

```
if (!context.Response.HasStarted){
        context.Response.StatusCode = statusCode;
}
```

https://github.com/ThreeMammals/Ocelot/blob/f16d201906f996f49effe83c86fd527292aff21a/src/Ocelot/Responder/HttpContextResponder.cs#L60

![image](https://user-images.githubusercontent.com/28291464/45872371-6e803080-bdc2-11e8-8442-7d5488950718.png)

**Comment by TomPallister** [comment]
@aqa510415008 I don't understand how the exception links to the log you have uploaded :(

However the change does seem to make sense?
