### ISSUE TITLE
Auth0 - JWT Token Validation - Request for authenticated route was unauthenticated

### ISSUE THREAD

**Issue by adamsproul** [ThreeMammals/Ocelot#635]
I am having issues validating an Auth0 access token when sent to Ocelot. I want to wrap Ocelot behind Auth0 so only authenticated users can call Ocelot.

Workflow is:
--**issue**--
SPA -- ( Authorization: Bearer {access_token from Auth0} ) --> Ocelot 
--**working**--
Ocelot -- ( Authorization: Bearer {basic auth} --> External service 

## Expected Behavior / New Feature
Sending an Auth0 JWT access token in the request header to Ocelot should authenticate in same way as a regular .NET Core Web API.

## Actual Behavior / Motivation for New Feature
Ocelot does not validate token, and logs the following:

info: Ocelot.Authentication.Middleware.AuthenticationMiddleware[0]
      requestId: 0HLH2U1L1TJ2L:00000001, previousRequestId: no previous request id, message: /api/v1/users/getByUserId is an authenticated route. AuthenticationMiddleware checking if client is authenticated

warn: Ocelot.Authentication.Middleware.AuthenticationMiddleware[0]
      requestId: 0HLH2U1L1TJ2L:00000001, previousRequestId: no previous request id, message: Client has NOT been authenticated for /api/v1/users/getByUserId and pipeline error set. Request for authenticated route /api/v1/users/getByUserId by  was unauthenticated

### Startup.cs

    using Microsoft.AspNetCore.Authentication;
    using Microsoft.AspNetCore.Authentication.JwtBearer;
    using Microsoft.AspNetCore.Builder;
    using Microsoft.AspNetCore.Hosting;
    using Microsoft.AspNetCore.Http;
    using Microsoft.Extensions.Configuration;
    using Microsoft.Extensions.DependencyInjection;
    using Microsoft.Extensions.Logging;
    using Microsoft.IdentityModel.Protocols.OpenIdConnect;
    using Microsoft.IdentityModel.Tokens;
    using Ocelot.Configuration;
    using Ocelot.DependencyInjection;
    using Ocelot.Logging;
    using Ocelot.Middleware;
    using Ocelot.Tracing.Butterfly;
    using System;
    using System.IdentityModel.Tokens.Jwt;
    using System.Threading;
    using System.Threading.Tasks;

    namespace APIGateway
    {
        public class Startup
        {
            private readonly IConfiguration _configuration;

            public Startup(IHostingEnvironment env)
            {
                var builder = new ConfigurationBuilder();
                builder
                    .SetBasePath(env.ContentRootPath)
                    .AddJsonFile($"appsettings.{env.EnvironmentName}.json", true, true)
                    .AddJsonFile($"ocelot.{env.EnvironmentName}.json", optional: false, reloadOnChange: true)
                    .AddEnvironmentVariables();

                _configuration = builder.Build();
            }

            // This method gets called by the runtime. Use this method to add services to the container.
            // For more information on how to configure your application, visit https://go.microsoft.com/fwlink/?LinkID=398940
            public void ConfigureServices(IServiceCollection services)
            {
                services.AddAuthentication(options =>
                {
                    options.DefaultAuthenticateScheme = JwtBearerDefaults.AuthenticationScheme;
                    options.DefaultChallengeScheme = JwtBearerDefaults.AuthenticationScheme;

                }).AddJwtBearer("Auth0", options =>
                {
                    options.Authority = "https://adamsproul-test-ta.auth0.com/";
                    options.Audience = "https://adamsproul.test.com/apigateway";
                });

                services.AddCors(options =>
                {
                    options.AddPolicy("CorsPolicy",
                        builder => builder
                        .AllowAnyOrigin()
                        .AllowAnyMethod()
                        .AllowAnyHeader()
                        .AllowCredentials()
                    );
                });

                services.AddOcelot(_configuration);
            }

            // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
            public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)
            {
                loggerFactory.AddApplicationInsights(app.ApplicationServices, LogLevel.Trace);
                loggerFactory.AddConsole(_configuration.GetSection("Logging"));

                if (env.IsDevelopment())
                {
                    app.UseDeveloperExceptionPage();
                }

                app.UseCors("CorsPolicy");

                app.UseAuthentication();

                app.UseOcelot().Wait();
            }
        }
    }

### ocelot.development.json

  {
    "ReRoutes": [
      {
        "DownstreamPathTemplate": "/rpc/AdministrationUsers/GetUser",
        "DownstreamScheme": "https",
        "DownstreamHostAndPorts": [
          {
            "Host": "svc.wam-dev.ta.com",
            "Port": 443
          }
        ],
        "UpstreamHeaderTransform": {
          "Authorization": "Basic _{basic_auth credentials}_"
        },
        "UpstreamPathTemplate": "/api/v1/users/getByUserId",
        "UpstreamHttpMethod": [ "Post", "Options" ],
        "HttpHandlerOptions": {
          "UseTracing": true
        },
        "AuthenticationOptions": {
          "AuthenticationProviderKey": "Auth0",
          "AllowedScopes": []
        }
      }
    ]
  }

Any help would be greatly appreciated

**Comment by adamsproul** [comment]
As a side note, if I remove the "AuthenticationOptions" from the ReRoute then everything flows through as intended.

But for security I want Ocelot to validate the Auth0 JWT tokens when an SPA makes a request to the API gateway.

**Comment by adamsproul** [comment]
Code was transforming the request header and replacing Auth0 token with the basic token intended for the downstream.

"UpstreamHeaderTransform": {
"Authorization": "Basic {basic_auth credentials}"
},

Removed this code and will look at transforming the request header after auth.

**Comment by adamsproul** [comment]
DownstreamHeaderTransform wouldn't replace the existing Auth0 authorization header. Maybe because the header was already set.

Thank you for your quick response @TomPallister. Very much appreciate the hard work you have put in to this repo.

In the end I added a DelegatingHandler to do the work, feels cleaner and more control, as below:

    namespace APIGateway.Handlers
    {
        public class WamDelegatingHandler : DelegatingHandler
        {
            private readonly string Username;
            private readonly string Password;

            public WamDelegatingHandler(IConfiguration configuration)
            {
                Username = configuration["WamService:Username"];
                Password = configuration["WamService:Password"];
            }

            protected override async Task<HttpResponseMessage> SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
            {
                // update the headers for WAM - uses basic auth
                request.Headers.Remove("Authorization");
                request.Headers.Add("Authorization", $"Basic {GetAuthorizationHeader()}");

                return await base.SendAsync(request, cancellationToken);
            }

            private string GetAuthorizationHeader() => Convert.ToBase64String(Encoding.ASCII.GetBytes($"{Username}:{Password}"));
        }
    }

## Startup.cs
    ...
    services.AddOcelot(_configuration)
                .AddDelegatingHandler<WamDelegatingHandler>();

## ocelot.development.json

    {
      "DownstreamPathTemplate": "/rpc/AdministrationUsers/GetUser",
      "DownstreamScheme": "http",
      "DownstreamHostAndPorts": [
        {
          "Host": "localhost",
          "Port": 52608
        }
      ],
      "UpstreamPathTemplate": "/api/v1/users/getByUserId",
      "UpstreamHttpMethod": [ "Post", "Options" ],
      "HttpHandlerOptions": {
        "UseTracing": true
      },
      "AuthenticationOptions": {
        "AuthenticationProviderKey": "Auth0",
        "AllowedScopes": []
      },
      "DelegatingHandlers": [
        "WamDelegatingHandler"
      ],
    }

**Comment by TomPallister** [comment]
Yeh that looks good!! Thanks for your interest in Ocelot :)

**Comment by Simkiw** [comment]
Hello guys,

Hi @TomPallister, i'm having the same issue as described, but not sure if the solution provided by @adamsproul fits.

**Ocelot.Startup.cs:** (I used both, neither worked)
- And not sure how the TestKey works as I assumed it had nothing to do with the Bearer used on my webAPI (resource i'm securing), as long as it appears on my reroute (ocelot.json)

            `services.AddAuthentication("Bearer")
                .AddIdentityServerAuthentication("TestKey", opt =>
                {
                    opt.Authority = "https://localhost:5001";
                    opt.RequireHttpsMetadata = false;
                    opt.ApiName = "weatherForecastApi";
                    opt.SupportedTokens = SupportedTokens.Both;
                });
            //services.AddAuthentication("Bearer")
            //    .AddJwtBearer("TestKey", opt =>
            //    {
            //        opt.Authority = "https://localhost:5001";
            //        opt.TokenValidationParameters = new TokenValidationParameters
            //        {
            //            ValidateAudience = false
            //        };
            //    });
            services.AddOcelot();`

And my **ocelot config** looks like this (Identity is just another webAPI, nothing to do with IS4)

```
"Routes": 
    //Weather Api
    {
      "DownstreamPathTemplate": "/WeatherForecast",
      "DownstreamScheme": "https",

      "DownstreamHostAndPorts": [
        {
          "Host": "localhost",
          "Port": 7001
        }
      ],
      //"DownstreamHeaderTransform": {
      //  "Authorization": "Basic {basic_auth credentials}"
      //},
      "UpstreamPathTemplate": "/gw/WeatherForecast",
        "UpstreamHttpMethod": [ "Get" ],
        "AuthenticationOptions": {
          "AuthenticationProviderKey": "TestKey",
          "AllowedScopes": [ "weatherForecastApi" ]
        }
      },
      //Identity Api
      {
        "DownstreamPathTemplate": "/Identity", 
```
And my **IS4 config**
```
public static IEnumerable<ApiScope> ApiScopes =>
            new List<ApiScope>
            {
                new ApiScope("weatherForecastApi", "Weather Forecast API"),
                new ApiScope("identityApi", "Identity Api")
            };
        public static IEnumerable<Client> Clients =>
            new List<Client>
            {
                new Client
                {
                    ClientId = "MoBe",

                    // no interactive user, use the clientid/secret for authentication
                    AllowedGrantTypes = GrantTypes.ClientCredentials,

                    // secret for authentication
                    ClientSecrets =
                    {
                        new Secret("MoBe".Sha256())
                    },

                    // scopes that client has access to
                    AllowedScopes = { "weatherForecastApi", "identityApi" }
                }
            };
```

 i'm just using a console app, which does access the secured weather api, the re-routing works just fine (I tested),  but when I add _AuthenticationOptions_ in ocelot.json, I get 401, unautorized: 

 _Ocelot.Authentication.Middleware.AuthenticationMiddleware[0]
      requestId: 0HMERCKN2Q182:00000001, previousRequestId: no previous request id, message: /gw/WeatherForecast is an authenticated route. AuthenticationMiddleware checking if client is authenticated
warn: Ocelot.Authentication.Middleware.AuthenticationMiddleware[0]
      requestId: 0HMERCKN2Q182:00000001, previousRequestId: no previous request id, message: Client has NOT been authenticated for /gw/WeatherForecast and pipeline error set. Request for authenticated route /gw/WeatherForecast by  was unauthenticated
warn: Ocelot.Responder.Middleware.ResponderMiddleware[0]
      requestId: 0HMERCKN2Q182:00000001, previousRequestId: no previous request id, message: Error Code: UnauthenticatedError Message: Request for authenticated route /gw/WeatherForecast by  was unauthenticated errors found in ResponderMiddleware. Setting error response for request path:/gw/WeatherForecast, request method: GET_

Which is ... not normal because, just right before, I make a direct call to the secured API with the same httpClient, and gets the response I want (which means, the client has been authenticated)

Any chance you spot something I've missed?

I'm on .net core 3.1, and use the appororiate version packages:
is4 v4.0.0.0 / ocelot v16.0.1 / Microsoft.AspNetCore.Authentication.JwtBearer v3.1.22

**Comment by Simkiw** [comment]
Ok, the problem seems to be coming from my console client as I instantiated 2 http clients, one for getting the IS4 discovery document and the other making calls to my APIs (and therefore, passing by ocelot)
Which is considered as a bad practice even though it's just 2 instances (not much), so just as a **reminder**:
there should be only one client per project if I understood well (related to sockets connections and stuff ... not my expertise, but that what was messing with my requests)
