### ISSUE TITLE
How to add check helth method to my Gateway project .net core

### ISSUE THREAD

**Issue by lucianoscastro** [ThreeMammals/Ocelot#646]
#Feature

Is there any way to enforce requests to a project controller with Ocelet (my GatewayApi project) for example create the check url to register in the Consul.
URL to check the integrity of my GatewayAPI in the .NET core.

When I make any request for a controller in my GatewayApi project, I always get an error with the message "Could not find the downstream route to the path"

## Steps to Reproduce the Problem

  1. Create a project web.api C# .net core
  2. Add a Controller (InfoController) with one method Foo (retrun date time)
  3. Add reference for Ocelot
  4. Make Request with postman, webbrowser to localhost:9000;

## Specifications

  - Version: last version Ocelot
  - Platform: .net core 
  - Subsystem:

**Comment by q315523275** [comment]
网关的健康检查，可以在预留中间件里添加健康检查地址，不过一半这个地址都是给ngnix使用的

> 
                    var conf = new OcelotPipelineConfiguration()
                    {
                        PreErrorResponderMiddleware = async (ctx, next) =>
                        {
                            if (ctx.HttpContext.Request.Path.Equals(new PathString("/")))
                            {
                                await ctx.HttpContext.Response.WriteAsync("ok");
                            }
                            else
                            {
                                await next.Invoke();
                            }
                        }
                    };
                    app.UseOcelot(conf).Wait();

**Comment by TomPallister** [comment]
@lucianoscastro "Could not find the downstream route to the path" means that Ocelot cannot find your anything in json configuration for your requested route.

Can you share your configuration json?

Ocelot doesn't do health checks at the moment. I would suggest using Consul if you want that functionality.

**Comment by dimitridaras** [comment]
I think the idea behind this is to add a healthcheck endpoint to the ocelot gateway itself, so that you can check that it's up and running.

**Comment by knight1219** [comment]
Did anything ever com from this? having api/controller methods in the gateway that can be called is a very usefull tool.

**Comment by hjchin** [comment]
> @lucianoscastro 网关的健康检查，可以在预留中间件里添加健康检查地址，不过一般这个地址都是给nginx使用的
> 
> > 
> 
> ```
>                 var conf = new OcelotPipelineConfiguration()
>                 {
>                     PreErrorResponderMiddleware = async (ctx, next) =>
>                     {
>                         if (ctx.HttpContext.Request.Path.Equals(new PathString("/")))
>                         {
>                             await ctx.HttpContext.Response.WriteAsync("ok");
>                         }
>                         else
>                         {
>                             await next.Invoke();
>                         }
>                     }
>                 };
>                 app.UseOcelot(conf).Wait();
> ```

maybe path '/hc' is a better path. In my opinion, it is always good to protect the root and returns 404.

**Comment by hjchin** [comment]
> Did anything ever com from this? having api/controller methods in the gateway that can be called is a very usefull tool.

The snippet above does the job, it is a quick workaround. 

Second approach or rather a proper one is setup the Consul with Ocelot and configure the health check url at htttps://_ocelot-host_:8500 (haven't try it)
