### ISSUE TITLE
UpstreamHost problem : not considered

### ISSUE THREAD

**Issue by tbprince** [ThreeMammals/Ocelot#652]
Hello,

first of all thank you for this project. I recently discovered it and I was testing it on Service Fabric or in standalone mode. However, it seems that I cannot make the UpstreamHost parameter work. It is simply ignored. The forwarding scheme I have on my mind requires to route things based on the domain that has been used so my routes would almost always have a UpstreamHost parameter set. However, it seems that setting it makes no difference. Even when a catch-all route has been configured and a specific route for that domain (UpstreamHost) has been added, catch-all route always get called and used.

Speaking of which, I'm also unable to make a website (ASP.NET Core MVC demo, nothing special) work without a catch-all. When I configure a DownstreamPathTemplate and UpstreamPathTemplate both to "/", to enable a website being loaded from a root folder (think about a containerized application where you always have http://site1:port1/ and http://site2:port2/ and so on), the root page (HTML) always get loaded but all of its assets (css, js, images …) always return a 404 so website is not properly loaded.

To make it work, my route should include an UpstreamPathTemplate of "/{url}" and a DownstreamPathTemplate of "/{url}" so also assets will be routed to the same downstream service. I believe this is a catch-all, isn't it ?

I'm sure I am messing something with configuration but I was unable to make it work :-|

By the way, in my scenario having multiple UpstreamHosts would be helpful.

Thanks.

**Comment by TomPallister** [comment]
@tbprince everything you are describing should work fine :(

You are correct re /assets you would need /{url}.

Can you share your configuration json and I can take a closer look?
