### ISSUE TITLE
An exception is thrown when the middleware is rewritten and then blocked back.

### ISSUE THREAD

**Issue by yilezhu** [ThreeMammals/Ocelot#653]
I tried to focus on a stream-limiting middleware, but when I returned, I threw an exception with code like this
![image](https://user-images.githubusercontent.com/18655233/46592730-118db580-caf8-11e8-8cec-bfc0c5c106d6.png)
The code is very simple, that is, meet the conditions directly after return.
However, the exception shown in the following figure appears.
![image](https://user-images.githubusercontent.com/18655233/46592754-413cbd80-caf8-11e8-8883-2321ba2d497d.png)

Then I tried to look at the source code and debug it and found it as follows:
ResponderMiddleware‘s Invoke like this

```csharp
public async Task Invoke(DownstreamContext context)
{
    await _next.Invoke(context);

    if (context.IsError)
    {
        Logger.LogWarning($"{context.Errors.ToErrorString()} errors found in {MiddlewareName}. Setting error response for request path:{context.HttpContext.Request.Path}, request method: {context.HttpContext.Request.Method}");
                
        SetErrorResponse(context.HttpContext, context.Errors);
    }
    else
    {
        Logger.LogDebug("no pipeline errors, setting and returning completed response");
        await _responder.SetResponseOnHttpContext(context.HttpContext, context.DownstreamResponse);
    }
}
```
Under these circumstances， `context.DownstreamResponse` is null   。But In the implementation method, there is no judgement of whether the parameter is empty, so it is used directly. like that 

```csharp
public async Task SetResponseOnHttpContext(HttpContext context, DownstreamResponse response)
{
    _removeOutputHeaders.Remove(response.Headers);

    foreach (var httpResponseHeader in response.Headers)
    {
        AddHeaderIfDoesntExist(context, httpResponseHeader);
    }

    foreach (var httpResponseHeader in response.Content.Headers)
    {
        AddHeaderIfDoesntExist(context, new Header(httpResponseHeader.Key, httpResponseHeader.Value));
    }

    var content = await response.Content.ReadAsStreamAsync();

    if(response.Content.Headers.ContentLength != null)
    {
        AddHeaderIfDoesntExist(context, new Header("Content-Length", new []{ response.Content.Headers.ContentLength.ToString() }) );
    }

    SetStatusCode(context, (int)response.StatusCode);

    context.Response.HttpContext.Features.Get<IHttpResponseFeature>().ReasonPhrase = response.ReasonPhrase;

    using (content)
    {
        if (response.StatusCode != HttpStatusCode.NotModified && context.Response.ContentLength != 0)
        {
            await content.CopyToAsync(context.Response.Body);
        }
    }
}
```

Is this a bug?

**Comment by TomPallister** [comment]
@yilezhu hi thanks for your interest in Ocelot. It is not really a bug. I guess it isnt set because you are skipping the middleware that sets it in the PreQueryStringBuilderMiddleware. 

I guess you need to set it in your middleware.

**Comment by yilezhu** [comment]
Thank you for your reply. First of all, I want to implement permission judgment after the request comes in, and interrupt and return the request without the corresponding permission. So here I'm just simulating a request interrupt, and it shouldn't go down to the middleware after the interrupt. You should respond directly to the client.I am using the code to rewrite your code, so I won't report it wrong.
`public async Task Invoke(DownstreamContext context)
        {
            await _next.Invoke(context);

            if (context.IsError)
            {
              //  Logger.LogWarning($"{context.Errors.ToErrorString()} errors found in {MiddlewareName}. Setting error response for request path:{context.HttpContext.Request.Path}, request method: {context.HttpContext.Request.Method}");

                // SetErrorResponse(context.HttpContext, context.Errors);

                var errmsg = context.Errors[0].Message;
                int httpstatus = _codeMapper.Map(context.Errors);
                var errResult = new ErrorResult() { errcode = httpstatus, errmsg = errmsg };
                var message = errResult.ToJson();
                context.HttpContext.Response.StatusCode = (int)HttpStatusCode.OK;
                await context.HttpContext.Response.WriteAsync(message);
                return;

            }
            else if (context.DownstreamResponse == null)
            {//添加如果管道强制终止，不做任何处理,修复未将对象实例化错误

            }
            else
            {
                Logger.LogDebug("no pipeline errors, setting and returning completed response");
                await _responder.SetResponseOnHttpContext(context.HttpContext, context.DownstreamResponse);
            }
        }`

**Comment by TomPallister** [comment]
@yilezhu yes this makes sense, do you want to submit a PR to fix this? I will mark this ticket as a bug to be looked at.

**Comment by ben-bartholomew** [comment]
I was running into this issue as well after using some custom logic to quit early under certain circumstances in PreQueryStringBuilderMiddleware. 

The other PR addressing this looks like it got closed due to inactivity so I figured I would submit one as well.

**Comment by raman-m** [comment]
```diff
+ Accepted
```
...because of ready PR #1334

**Comment by raman-m** [comment]
Hi @yilezhu 
We have a bug fix solution.
Could you verify the solution please?
