### ISSUE TITLE
Smarter Aggregate base on ForeignKey fields

### ISSUE THREAD

**Issue by abooraja** [ThreeMammals/Ocelot#661]
currently Aggregate feature is awesome. 
It would be very nice if ocelot can act as composite based on main/first Downstream response. then load related data from other micro service.
for example Imagine that we have three tiny micro service.
1-comment
2-post
3-profile
we want in one request get list of comments, and get related post and writer too
can ocelot do this?
thanks

**Comment by AbolfazlRajabpour** [comment]
hi @TomPallister  @binarymash 
Do not have a comment?

**Comment by TomPallister** [comment]
@AbolfazlRajabpour at the moment Ocelot cannot do this you probably want to use GraphQL. Ocelot can integrate with GraphQL docs are [here](https://ocelot.readthedocs.io/en/latest/features/graphql.html) but you don't need to use Ocelot you could just use GraphQL with nginx in front of it would be my recommendation.

**Comment by AbolfazlRajabpour** [comment]
@TomPallister 
any idea?

**Comment by raman-m** [comment]
Fixed/Closed by #704
