### ISSUE TITLE
Multiple Authentication Schemes

### ISSUE THREAD

**Issue by jlcarpenter** [ThreeMammals/Ocelot#667]
I am using Auth0 as my authentication provider.  I have an intranet site where the users log-in to Auth0 and store the bearer token.  I am in the early processes of implementing my Ocelot gateway so I have some of my API controllers still in my intranet code and am moving others to Ocelot.  Below is my Startup code in my Gateway

` 
services
        .AddAuthentication(options =>
        {
          options.DefaultAuthenticateScheme = JwtBearerDefaults.AuthenticationScheme;
          options.DefaultChallengeScheme = JwtBearerDefaults.AuthenticationScheme;
        })
        .AddJwtBearer("Auth0-Alerts", x =>
        {
          x.Authority = Configuration["Auth0:Authority"];
          x.Audience = Configuration["Auth0:AlertsAudience"];
          if (_environment.IsEnvironment("Local") || _environment.IsDevelopment())
            x.RequireHttpsMetadata = false;
        });

      services
        .AddOcelot(Configuration);`

When I make the request from the Intranet to the Gateway, I receive the following log message.
` Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler[7]
      Auth0-Alerts was not authenticated. Failure message: IDX10214: Audience validation failed. Audiences: 'https://dev-intranet.mydomain.com, https://mydomain.auth0.com/userinfo'. Did not match: validationParameters.ValidAudience: 'https://api.mydomain.com/notifications' or validationParameters.ValidAudiences: 'null'.`

I thought the startup in the gateway handled the change in authentication schemes.

Just for reference, my Auth0 is setup with Intranet as an application (user is logged in) with API for Alerts, which is what I set up above in my Gateway startup and I am attempting to access.  I hope to add other routes which will have different authentication options as well.

**Comment by jlcarpenter** [comment]
I have also looked at delegating handlers but my code is not being called. I saw a comment that they might have been removed.  Below is my handler.

`public class AlertHandler : DelegatingHandler
  {
    public AlertHandler()
    {
      int i = 0;
    }


    protected override async Task<HttpResponseMessage> SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
    {
      //do stuff and optionally call the base handler..
      return await base.SendAsync(request, cancellationToken);
    }
  }`

and here is my Startup.
`      services
        .AddOcelot(Configuration)
        .AddDelegatingHandler<AlertHandler>(true);
`

**Comment by TomPallister** [comment]
@jlcarpenter delegating handlers have not been removed and that should work as far as I'm aware :/ 

All Ocelot does is call 
```                
var result = await context.HttpContext.AuthenticateAsync(context.DownstreamReRoute.AuthenticationOptions.AuthenticationProviderKey);
```

Which delegates authorisation to your given key so I'm not sure if your error is Ocelot specific...does it work if you use the auth scheme in a non Ocelot project? E.g. authorize over a controller on normal web api?

**Comment by philproctor** [comment]
#740 will resolve this.
