### ISSUE TITLE
Ocelot doesn't really authenticate does it?

### ISSUE THREAD

**Issue by helzgate** [ThreeMammals/Ocelot#669]
Ocelot documentation says that it performs authentication but it doesn't correct?  It can only very that the user has already been authenticated.  

Currently I'm using Ocelot to verify my external apps have been authenticated through Azure B2C.

The only reason I'm asking is that I'm about to make a presentation on Ocelot and I want to make sure I'm understanding this correctly when my boss asks me, "Why can't the Ocelot do authentication, the website says it has this functionality?".

**Comment by TomPallister** [comment]
@helzgate I dont really understand your question.

Ocelot calls 

```
context.HttpContext.AuthenticateAsync(context.DownstreamReRoute.AuthenticationOptions.AuthenticationProviderKey);
```

in AuthenticationMiddleware.cs this uses asp.net code to authenticate the given http context against the given authentication provider. The code has nothing to do with Ocelot. Ocleot just calls the asp.net authentication stuff. So Ocelot does authentication but nothing other than calling asp.net authentication code.
