### ISSUE TITLE
Websocket not propagating close event

### ISSUE THREAD

**Issue by victormartinsantiago** [ThreeMammals/Ocelot#674]
## Expected Behavior / New Feature
When a socket is closed between ocelot and the destination service, the onclose event is not propagated from Ocelot to the client, so the client is never aware that the socket is no longer usable

## Actual Behavior / Motivation for New Feature

When the onclose event happens in Ocelot, the respective socket between Ocelot and the client should be closed as well so the client can try an reconnect again. This is relevant when both the gateway and the destination services are running as a containers and they are subjet to random restarts.

## Steps to Reproduce the Problem

  1. Open a ws connection to an aspnet core service thru Ocelot running on aspnet core service
  2. Bring the destination service down so the onclosed event is fired
  3. The onclose event shall happen in Ocelot but is never progapaged to the caller (client)

## Specifications

  - Version: 8.0.2
  - Platform: ASPNET Core 2.1.0.4
  - Subsystem:

**Comment by tdejong-tools4ever** [comment]
When trying to use ocelot to proxy between my service and client I have also encountered the issue of the connection not closing properly after the service shuts down. This, however, seems to be an issue in the WampSharp library as it does not send a proper WebSocket closed event.

I do however assume that when the service WebSocket gives an exception with error ConnectionClosedPrematurely something would be wrong with the service and a new connection should be agreed upon. I assume the simplest fix would be to return a closed connection message (although I do not know exactly what issues this could possibly create).

**Comment by raman-m** [comment]
Too outdated issue.
Will be checked as a part of #1040
