### ISSUE TITLE
I get the error : Message	"Method not found: 'FluentValidation.IRuleBuilderOptions`2<!0,!1> FluentValidation.IRuleBuilder`2.SetValidator(FluentValidation.IValidator`1<!1>)'."	string

### ISSUE THREAD

**Issue by preddy4690** [ThreeMammals/Ocelot#706]
I just got the latest version of Ocelot and I'm trying to use it. 

I'm getting the error 👍 
Message	"Method not found: 'FluentValidation.IRuleBuilderOptions`2<!0,!1> FluentValidation.IRuleBuilder`2.SetValidator(FluentValidation.IValidator`1<!1>)'.

What am I doing wrong?

Here's my ocelot.json file. 

{
  "ReRoutes": [
    {
      "DownstreamPathTemplate": "/{everything}",
      "DownstreamScheme": "https",
      "DownstreamHostAndPorts": [
        {
          "Host": "webapi.domain.com",
          "Port": 8080
        }
      ],
      "UpstreamPathTemplate": "/api/{everything}",
      "UpstreamHttpMethod": [ "Get" ],
      "UpstreamHost": "localhost:9021"
    }
  ],
  "GlobalConfiguration": {
    "BaseUrl": "localhost:9021"
  }
}

**Comment by Stians92** [comment]
This seems to be an issue with the newest versions of FluentValidation. I had this problem after updating my nuget packages. Downgrading FluentValidation to v7.6.105 should get you up and running while waiting for an updated version of Ocelot.

**Comment by preddy4690** [comment]
Thank you. That worked!

**Comment by Stians92** [comment]
I agree with dimitridaras. This issue should stay open and Ocelot should be updated to work with the newer versions of FluentValidation.

Keeping it open also makes it easier to find for anyone else who run into this issue.

**Comment by preddy4690** [comment]
Agreed. I'm reopening it until this issue is resolved.

**Comment by narcis-pv** [comment]
This was fixed in the current code base, but it requires to publish a new nuget.

**Comment by TomPallister** [comment]
released in 13.0.0

**Comment by xxsybreedxx** [comment]
Any updates here? Ocelot v13 still has a reference to FluentValidation 7.6.
