### ISSUE TITLE
can't reach IdentityServer4 with Ocelot route

### ISSUE THREAD

**Issue by przemekwojcik** [ThreeMammals/Ocelot#710]
Perhaps i'm doing something wrong, but i'm completely stuck and don't know how to resolve this problem.

## Expected Behavior / New Feature

i expect to reach to identityserver instance at desired url route defined in ocelot configuration file. 

## Actual Behavior / Motivation for New Feature

We're building a bigger apps deployed to Kubernetes with Ingress in-front. I struggle a lot to make to make IdenityServer4 reachable. The first stop is Ocelot. In our app, i can only reach IdenityServer4 if its route is defined at the root url of ocelot (so, http://ocelot). It will not work at any other sub-url (like http://ocelot/identity). I've created a demo app (docker-based) that describes this problem - it's available [here ](https://github.com/przemekwojcik/OcelotIdentity).

Here's my ocelot.config:

`{
  "ReRoutes": [
    {
      "DownstreamPathTemplate": "/{catchAll}",
      "UpstreamPathTemplate": "/identity/{catchAll}",
      "UpstreamHttpMethod": [ "Get", "Options", "Post" ],
      "DownstreamScheme": "http",
      "ServiceName": "identity"
    }
  ],
  "GlobalConfiguration": {
    "RequestIdKey": "OcRequestId",
    "AdministrationPath": "/administration"
  }
}`

## Steps to Reproduce the Problem

Please refer the demo app. It's the simplest possible app with these two components onboard.
  1. Run demo app
  1. IdServ4 should be visible under localhost:7060/identity
  

## Specifications

  - Version: Ocelot 12.0.1
  - Platform: .NET Core 2.2 + Docker (2.0.0.0-win81 (29211))
  - Subsystem: IdentityServer4 (ver. 2.3.2)

**Comment by philproctor** [comment]
Any updates on this? Sorry for the slow response.

I don't see anything obvious from what you've posted here or with the sample code, though I do see you've made some changes since raising this issue.

**Comment by raman-m** [comment]
@przemekwojcik
Hi Przemek!

Seems this issue is rather question than real issue ready for development.
Next time please open a [discussion](https://github.com/ThreeMammals/Ocelot/discussions) with your questions. And community will help you.

---

> - Platform: **.NET Core 2.2** + Docker (2.0.0.0-win81 (29211))

Sorry, we don't support outdated versions of .NET framework. Since November'23 we support only .NET 6+ as Microsoft does it.
Stay with Ocelot!
