### ISSUE TITLE
Websocket authentication token

### ISSUE THREAD

**Issue by Rakiah** [ThreeMammals/Ocelot#718]
Hello, I'm currently using the websocket proxying feature which is working correctly but I would require my system to run a bit of code to check for token validity and token existence, from what I understand this is not implemented, where should I start to implement this kind of feature myself, or is someone already working on something similar ?

I was planning to use a query parameter retrieved by the HttpContext to check for this (I can already do that at micro-service level, but it would be better to do it at gateway level)

**Comment by Rakiah** [comment]
Merge request opened for this issue

**Comment by raman-m** [comment]
Will be fixed in #1040

**Comment by raman-m** [comment]
Duplicate of #1040
