### ISSUE TITLE
Dynamic downstream port assignment

### ISSUE THREAD

**Issue by azeebazy** [ThreeMammals/Ocelot#719]
Is it possible to assign downstream port dynamically from the upstream url parameter

For example if I have two instance of same microservice (say ServiceA) running in port 4444 and 4323.
Is it possible to reroute a url (say http://-url-/ServiceA/{port} dynamically. I was looking something like

```
{
     "DownstreamPathTemplate": "/api/get",
     "DownstreamScheme": "http",
     "UpstreamPathTemplate": "/ServiceA/{port}",
     "UpstreamHttpMethod": [ "Get" ],
     "DownstreamHostAndPorts": [
       {
         "Host": "localhost",
         "Port": **{port}**
       }
     ]
   }
```

**Comment by anktsrkr** [comment]
Hi @azeebazy Thanks for reaching us! Your requirement is more about load balancing between two instances of same microservice, if yes then sure! you can do it using ocelot. I will suggest to check [Documentation](https://ocelot.readthedocs.io/en/latest/features/loadbalancer.html#load-balancer) for more details. 
Please note, Ocelot Load balancer does not support dynamic port assignment like your example, but I believe it will give you the flexibility what you are trying achieve.
Please let us know, In case you need any more details. Thanks!

**Comment by anktsrkr** [comment]
Hi @azeebazy If I understand correctly, requested feature is not available yet. However we would like to know what's the purpose of passing port in the url? Isn't nice if you can configure it dynamically, something like this 
```
 {
    "DownstreamPathTemplate": "/api/get",
    "DownstreamScheme": "https",
    "DownstreamHostAndPorts": [
            {
                "Host": "localhost",
                "Port": 4444,
            },
            {
                "Host": "localhost",
                "Port": 4323,
            }
        ],
    "UpstreamPathTemplate": "/ServiceA",
    "LoadBalancerOptions": {
        "Type": "RoundRobin"
    },
    "UpstreamHttpMethod": [ "Get" ]
}
```

**Comment by azeebazy** [comment]
Thanks for the response. I guess I need  to change my design to meet my requirement. :)
