### ISSUE TITLE
HealthChecks integration?

### ISSUE THREAD

**Issue by fleed** [ThreeMammals/Ocelot#725]
Are there any "utility" methods to easily integrate health checks?

I would like to expose an "aggregated" health status that considers all the health status information coming from the services behind the gateway.

I would expect to configure the health endpoints in the ocelot configuration together with the routes.

**Comment by jducobu** [comment]
Is this feature already exist?

**Comment by raman-m** [comment]
@fleed
 Hi Francesco!
**Will you contribute?**
Converting to a discussion...
