### ISSUE TITLE
Question: Middleware injection ideas

### ISSUE THREAD

**Issue by istvan2015** [ThreeMammals/Ocelot#733]
I have a question regarding middleware injection. I would need a simple way of injecting middleware (to be used as part of the configuration in Startup.cs of a simple ASP.NET Core Gateway). The purpose of the middleware would be to simply intercept and log information about the user that is attempting to access it. 

Note: I do **not** intend to do this in a controller, hence mentioned doing it in Configure

```
public void Configure(IApplicationBuilder app, IHostingEnvironment env)
{
    var configuration = new OcelotPipelineConfiguration
    {
        // inject some useful middleware here
    };
    app.UseOcelot(configuration).Wait();
}
```

How to do it properly? I can intercept information from a lambda expression, but then I don't know when I can really use that to output the desired information.

Thank you, any clarification with a very basic code sample is enough, just as much as correctly intercepting **User.Identity.Name** there, and logging it by using

```
Log.Information(message);
```

Another note: there is already a custom logger provider setup, which is working perfectly.

**Comment by philproctor** [comment]
Two possibilities:

1. Implement an ASP.NET middleware that logs the request prior to passing to the Ocelot pipeline. This will catch all the requests before processing and you can log whatever you want there.
2. Use the OcelotPipelineConfiguration as you've mentioned above with something like the sample below.

```
new OcelotPipelineConfiguration
            {
                //PreQueryStringBuilderMiddleware occurs after authorization
                PreQueryStringBuilderMiddleware = async (ctx, next) =>
                {
                    var name = ctx.HttpContext.User.Identity.Name;
                    Log.Information($"{name}");
                    await next.Invoke();
                }
            };
```

**Comment by philproctor** [comment]
Closing this issue, please re-open if my response did not resolve the problem.
