### ISSUE TITLE
Is there any support for basic authentication?

### ISSUE THREAD

**Issue by walterfranssen** [ThreeMammals/Ocelot#736]
Is there any support for basic authentication? and is there an example for it?

**Comment by philproctor** [comment]
Ocelot will work with any .NET Core authentication, just add the authentication to your .NET Core Pipeline before Ocelot and refer to the scheme in your reroute. Something like this would work: http://jasonwatmore.com/post/2018/09/08/aspnet-core-21-basic-authentication-tutorial-with-example-api#users-controller-cs
