### ISSUE TITLE
Proposal: Authorize routes based off of variable matching

### ISSUE THREAD

**Issue by philproctor** [ThreeMammals/Ocelot#739]
## Expected Behavior / New Feature
Authorize routes based off some variable from the request, including those from #737

## Motivation for New Feature
If route claim authorizations allowed authorization based off of some upstream route variable, when combined with #737, a request can check for a claim for the specified resource before ensuring that the request is routed. This allows greater flexibility in authorizing individual resources.

**Comment by TomPallister** [comment]
@philproctor I think the approach to take here would be integrate whatever .NET provides for authorisation into Ocelot in a nice way. At the moment I have written some custom logic that just checks claims against a list from the config. We probably need to think more holistically. Integrating with .NET and allowing users to provide whatever schemes for authorisation in the standard format would be very powerful and well supported.

**Comment by raman-m** [comment]
Any PR(s), @philproctor ? 😉 
Any discussions?

**Comment by raman-m** [comment]
@philproctor Phil,

>This allows greater flexibility in authorizing individual resources.

Show us your vision and design of your proposal in details please via PR or discussion with real code snippets.
For now, as for me, this proposal looks very abstract and it cannot be accepted for development.
Please go to the [discussion](https://github.com/ThreeMammals/Ocelot/discussions/1903) for #737 and let's get started.
This issue will be closed for now.

**Comment by raman-m** [comment]
Lack of description!
No communication!
