### ISSUE TITLE
Empty placeholders: Failed to match Route configuration for upstream path

### ISSUE THREAD

**Issue by satano** [ThreeMammals/Ocelot#748]
## Expected Behavior

Match upstream path with empty placeholder and map it correctly to downstream.

## Actual Behavior / Motivation for New Feature

Upstream path with placeholder is not working as expected when placeholder is empty. It fails with error:

```UnableToFindDownstreamRouteError Message: Failed to match ReRoute configuration for upstream path: /test```

## Steps to Reproduce the Problem

This special _catch all_ configuration of ReRoute works as expected

```
"DownstreamPathTemplate": "/api/invoices/{url}"
"UpstreamPathTemplate": "/{url}"
```

It maps URLs this way:

```
/ → /api/invoices/
/123 → /api/invoices/123
```

Now this mapping (downstream is the same):

```
"DownstreamPathTemplate": "/api/invoices/{url}"
"UpstreamPathTemplate": "/test/{url}"
```

It works correctly when `{url}` is specified: `/test/123 → /api/invoices/123`

But it fails, when `{url}` is empty. I would expect upstream URL `/test/` to reroute to downstream URL `/api/invoices/`. The error is:

```
dbug: Ocelot.DownstreamRouteFinder.Middleware.DownstreamRouteFinderMiddleware[0]
      requestId: 0HLJQAG2RQPKO:00000005, previousRequestId: no previous request id, message: Upstream url path is /test/
warn: Ocelot.DownstreamRouteFinder.Middleware.DownstreamRouteFinderMiddleware[0]
      requestId: 0HLJQAG2RQPKO:00000005, previousRequestId: no previous request id, message: DownstreamRouteFinderMiddleware setting pipeline errors. IDownstreamRouteFinder returned Error Code: UnableToFindDownstreamRouteError Message: Failed to match ReRoute configuration for upstream path: /test/, verb: GET.
warn: Ocelot.DownstreamRouteFinder.Middleware.DownstreamRouteFinderMiddleware[0]
      requestId: 0HLJQAG2RQPKO:00000005, previousRequestId: no previous request id, message: Failed to match ReRoute configuration for upstream path: /test/, verb: GET.
warn: Ocelot.Responder.Middleware.ResponderMiddleware[0]
      requestId: 0HLJQAG2RQPKO:00000005, previousRequestId: no previous request id, message: Error Code: UnableToFindDownstreamRouteError Message: Failed to match ReRoute configuration for upstream path: /test/, verb: GET. errors found in ResponderMiddleware. Setting error response for request path:/test/, request method: GET
dbug: Ocelot.Errors.Middleware.ExceptionHandlerMiddleware[0]
      requestId: 0HLJQAG2RQPKO:00000005, previousRequestId: no previous request id, message: ocelot pipeline finished
```

As a special case of this, I would also expect routing to ignore trailing slash, because from WEB/API wiew, usually the address with the slash at the end is the same as without it. So upstream URL `/test` would map to downstream URL `/api/invoices`. Maybe this is not exact from the computers point of view, but for me it makes sense from human point of view of configuration. It does not work this way even if the routing is configured without the slashes:

```
"DownstreamPathTemplate": "/api/invoices{url}"
"UpstreamPathTemplate": "/test{url}"
```

It correctly maps non epmty `{url}` which means, it works with the slash at the end, because the slash is the value of the `{url}`. But still not without it:

```
/test/123 → /api/invoices/123
/test/ → /api/invoices/
/test → Failed to match ReRoute configuration for upstream path: /test
```

To make work everything what I want, I need three reroutes (or at least two, if the first one will be without slashes):

```
{
    "DownstreamPathTemplate": "/api/invoices/{url}"
    "UpstreamPathTemplate": "/test/{url}"
},
{
    "DownstreamPathTemplate": "/api/invoices/"
    "UpstreamPathTemplate": "/test/"
},
{
    "DownstreamPathTemplate": "/api/invoices"
    "UpstreamPathTemplate": "/test"
}
```

## Specifications

  - Version: Ocelot 13.0.0
  - Platform: .NET Core 2.2 on Windows

**Comment by margaale** [comment]
I always thought that it was designed to work this way, let's see if we can get some clarification...

**Comment by philproctor** [comment]
#737 changes the way the matching templates are created and used, I did not change this behavior as it appeared to be by design. A few days ago I tried having the catch all catch 0 or more if it's the last segment of the pattern, but this caused some acceptance tests to fail which were explicitly verifying that did not happen. As such, I believe this is an intended behavior, but I think as part of #737 we may have some workarounds, particularly, using a grouping match instead of a placeholder. I will discuss with the team.

**Comment by upadhyaychandan** [comment]
Hi Team,
I want to validate Placeholder  value how we can  do that 
Example:-
Api/test1/{Id}
api/test1/{Id}/test
api/test1/{id}/test/{id2}

Request Url:-
api/test1/{EmptyValue/test
So in Placeholder it is coming {EmptyValue}/test , it should be only {emptyvalue}

**Comment by i02coroj** [comment]
Hi.
I see this ticket is still open and I would be quite interested to know if there's a plan to get this implemented.
The behavior I see with version 18.0.0 of the package it that it still doesn't match the upstream when the placeholder at the end of the path is empty.
so

**Comment by AlyHKafoury** [comment]
@raman-m Can I work on this issue ?

**Comment by raman-m** [comment]
[~needs]: https://img.shields.io/badge/-needs%20validation-7ee5aa.svg

@AlyHKafoury  First of all, please verify (validate, repro) this bug.
I've marked the issue with [![label: needs validation][~needs]](https://github.com/ThreeMammals/Ocelot/labels/needs%20validation) label.

**Comment by AlyHKafoury** [comment]
@raman-m I am adding a unit test for it first and then will fix it, after I reproduce and create a unit test

**Comment by AlyHKafoury** [comment]
@raman-m I can verify the error exists and I have a unit-test for it here https://github.com/ThreeMammals/Ocelot/pull/1911/files
