### ISSUE TITLE
Configure reroutes at runtime

### ISSUE THREAD

**Issue by ChrisSwinchatt** [ThreeMammals/Ocelot#750]
## New Feature

It would be useful if we could generate reroutes configuration at runtime. It seems like it would be fairly simple to expose Ocelot's internal API. It's already possible to create reroutes, but there is no exposed way to pass them to Ocelot. Ocelot is able to update its configuration dynamically (currently as a hack it's possible for a gateway to generate a new configuration and POST it to itself, but this involves serializing the reroutes and POSTing them so that Ocelot can deserialize them again) but the means to do this using CLR objects is not exposed.

## Motivation for New Feature

It would simplify using an API discovery system that isn't explicitly supported by Ocelot. We're currently generating our gateway configuration using a combination of the K8S discovery API and Swagger. It would be nice to have a way to automatically insert a new service into the reroutes without the services themselves having to be do anything new as they would with Consul (i.e. the gateway polls every few minutes for new services, rather than services notifying it via Consul).

**Comment by raman-m** [comment]
Hi Chris!
You've described the case of [Dynamic Routing](https://ocelot.readthedocs.io/en/latest/features/routing.html#dynamic-routing):
- See #340
