### ISSUE TITLE
Match catch-all file extension in upstream path template

### ISSUE THREAD

**Issue by ChrisSwinchatt** [ThreeMammals/Ocelot#754]
## Expected Behavior

When using a reroute like the following:

```json
{
   "DownstreamPathTemplate": "/{json}.json",
   "DownstreamScheme": "http",
   "DownstreamHostAndPorts": [
        {
            "Host": "foo.svc",
           "Port": 80
        }
    ],
    "UpstreamPathTemplate": "/foo/{json}.json",
    "UpstreamHttpMethod": [
        "Get"
    ],
    "Priority": 3
}
```

Ocelot should forward a request such as `/foo/bar.json` to `foo.svc/bar.json`

## Actual Behavior

Ocelot forwards the request to `foo.svc/bar.json.json`

Log:
```
[09:35:30 DBG] message: ocelot pipeline started
[09:35:30 DBG] message: Upstream url path is /foo/bar.json
[09:35:30 DBG] message: downstream templates are /{bar}.json
[09:35:30 INF] message: EndpointRateLimiting is not enabled for /{bar}.json
[09:35:30 INF] message: No authentication needed for /foo/bar.json
[09:35:30 INF] message: /{bar}.json route does not require user to be authorised
[09:35:30 DBG] message: Downstream url is http://foo.svc/bar.json.json
[09:35:30 DBG] message: setting http response message
[09:35:30 DBG] message: no pipeline errors, setting and returning completed response
[09:35:30 DBG] message: ocelot pipeline finished
```

## Steps to Reproduce the Problem

  1. Have a reroute like `/foo/{bar}.json`
  2. Try to access it
  3. Get a 400 and the downstream service logs a message like `GET /foo/swagger/v1/swagger.json.json returned 400`

## Specifications

  - Version: 13.0.0
  - Platform: ASP.Net Core 2.1

**Comment by ChrisSwinchatt** [comment]
Going to try to fix this myself.

**Comment by philproctor** [comment]
@ChrisSwinchatt I believe my in progress work on #737 already resolves this. I will add this test before merge to verify before I merge it in.

**Comment by ChrisSwinchatt** [comment]
Alright, I did some work on it today and wrote a few more tests. I’ll add the rest of them because there are some gotchas that my first attempt didn’t handle.

**Comment by redplane** [comment]
Same problem happened to me.
Any solutions please ?

**Comment by redplane** [comment]
This is actually a bug. 
I think the library should support url regex instead of using { } template.

**Comment by raman-m** [comment]
@ChrisSwinchatt commented [on Jan 16, 2019](https://github.com/ThreeMammals/Ocelot/issues/754#issuecomment-454903452):
> I did some work on it today and wrote a **few more tests**.

Which ones?

**Comment by raman-m** [comment]
@ChrisSwinchatt 
Your route must be [Catch All](https://ocelot.readthedocs.io/en/latest/features/routing.html#catch-all) one!
```json
{
   "DownstreamPathTemplate": "/{all}",
    "UpstreamPathTemplate": "/foo/{all}",
}
```
