### ISSUE TITLE
web site tutorial for ocelot/consul not working

### ISSUE THREAD

**Issue by barron9** [ThreeMammals/Ocelot#755]
web site tutorial for ocelot/consul not working

Consul The first thing you need to do is install the NuGet package that provides Consul support in Ocelot.

Install-Package Ocelot.Provider.Consul
Then add the following to your ConfigureServices method.

s.AddOcelot()
    .AddConsul();
https://ocelot.readthedocs.io/en/latest/features/servicediscovery.html

> 
Severity	Code	Description	Project	File	Line	Suppression State Error	CS1061	'IOcelotBuilder' does not contain a definition for 'AddConsul' and no accessible extension method 'AddConsul' accepting a first argument of type 'IOcelotBuilder' could be found (are you missing a using directive or an assembly reference?)	Gateway C:\Users\berkin.tatlisu\Desktop\ocelot-api-gateway\final\Gateway\Program.cs

**Comment by thiagoloureiro** [comment]
Baron, can you check in my repo is  there is any difference that you're trying to do ?

https://github.com/thiagoloureiro/APIGatewayOcelot

I have Consul implemented, but anyway I will try the tutorial.

**Comment by barron9** [comment]
yes unfortunately my conf is not showing up on consol ui

{
    "ReRoutes": [
        {
            "DownstreamPathTemplate": "/api/values",
            "DownstreamScheme": "http",
            "DownstreamHostAndPorts": [
                    {
                        "Host": "localhost",
                        "Port": 5002
                    }
                ],
            "UpstreamPathTemplate": "/capi/"
        }


    ],
    "GlobalConfiguration": {
        "BaseUrl": "https://localhost:5000"
        ,"ServiceDiscoveryProvider": {
            "Host": "localhost",
            "Port": 8300,
            "Type": "Consul"
        }
    }

    
}
