### ISSUE TITLE
Service discovery/Dynamic routing with dynamic DownstreamScheme

### ISSUE THREAD

**Issue by mrauter** [ThreeMammals/Ocelot#758]
Nice project!

Question: We use Consul and "Dynamic routing" as described in https://ocelot.readthedocs.io/en/latest/features/servicediscovery.html#dynamic-routing

It seems not possible to have different "DownstreamScheme" for different services. For example service1 = "https" and service2 = "ws" if dynamic routing is used. So I would need to change the configuration to manually defined ReRoutes per service as described in: https://ocelot.readthedocs.io/en/latest/features/servicediscovery.html#consul ?

Is this correct? If yes, are there any plans to support dynamic schemes via Consul?

By the way: Is "wss" supported?

Thanks

**Comment by li517451737** [comment]
Hello, how do you solve this problem?

**Comment by mrauter** [comment]
Currently it seems not possible with dynamic routing

**Comment by OrihuelaConde** [comment]
> 
> 
> Hello, how do you solve this problem?

We have the same issue. We are going to run two instance of Ocelot, one targeting "http" and the second one "ws". It isn't the best solution but Ocelot doesn't support this behaviour.

**Comment by vahidarr** [comment]
I set DownstreamScheme to ws and unexpectedly it also support http.

**Comment by mrauter** [comment]
> I set DownstreamScheme to ws and unexpectedly it also support http.

I can confirm this - is this an expected behavior?

**Comment by raman-m** [comment]
@mrauter commented [on Jan 21, 2019](https://github.com/ThreeMammals/Ocelot/issues/758#issue-401283008):
> Is this correct? If yes, are there any plans to support dynamic schemes via Consul?

Yes, if you have intention to work on this feature! Will you contribute to our repo making huge Ocelot refactoring?
