### ISSUE TITLE
Dynamic routing with request body supported ?

### ISSUE THREAD

**Issue by redplane** [ThreeMammals/Ocelot#760]
## Expected Behavior / New Feature
**New feature**

## Actual Behavior / Motivation for New Feature
I have read [Ocelot dynamic routing](https://ocelot.readthedocs.io/en/latest/features/routing.html).
So far, I don't see any documents about passing request body from **Upstream** to **Downstream** with **POST** or **PUT** method.

### Current implementation: 

```
{
    "ReRoutes": [
        {
            "DownstreamPathTemplate": "/api/orders/{orderId}/{userId}",
            "UpstreamPathTemplate": "/api/gateway/orders/{orderId}/{userId}",
            "UpstreamHttpMethod": [
                "Get"
            ],
            "DownstreamScheme": "http",
            "DownstreamHostAndPorts": [
                {
                    "Host": "localhost",
                    "Port": 50110
                }
            ]
        }
    ]
}
```

I have to pass parameter through query string with **GET** method

## What I request
```
{
    "ReRoutes": [
        {
            "DownstreamPathTemplate": "/api/orders",
			"DownstreamRequestBody": {
				orderId: {orderId},
				userId: {userId}
			},
            "UpstreamPathTemplate": "/api/gateway/orders/{orderId}/{userId}",
			"UpstreamRequestBody": {
				orderId: {orderId},
				userId: {userId}
			}
            "UpstreamHttpMethod": [
                "Get"
            ],
            "DownstreamScheme": "http",
            "DownstreamHostAndPorts": [
                {
                    "Host": "localhost",
                    "Port": 50110
                }
            ]
        }
    ]
}
```

I would like to request something like **DownstreamRequestBody** and **UpstreamRequestBody** to help me read the request body of **Upstream** and pass them to **Downstream** in the order I want.

So far, what I have to do is:

- Write an API method to receive request from **Upstream**
- Use **HttpClient** to forward the body to **Downstream** end-point.

I would be nice if I don't have to repeat myself doing those kind of works.

## Specifications

  - Version:  13.0.0
  - Platform: Windows 10
  - Subsystem:

**Comment by redplane** [comment]
Sorry for misconfigured the ocelot.
I have tested the dynamic routing and it can help me to pass the body.

**Comment by gmedinaArkus** [comment]
Hi @redplane can I know how you made this possible using the dynamic routing? I want to pass a single field with a pre-defined value to the re route.
