### ISSUE TITLE
[Question] Support for Swagger.yml

### ISSUE THREAD

**Issue by allanchua101** [ThreeMammals/Ocelot#777]
## Expected Behavior / New Feature

Hi, this is more of a question and not a bug, does Ocelot support YAML files instead of JSON for Swagger configuration?

**Comment by raman-m** [comment]
Ask Swagger team!

**Comment by raman-m** [comment]
Officially we don't support and add Swagger to Ocelot core.
- [Not Supported | Swagger](https://ocelot.readthedocs.io/en/latest/introduction/notsupported.html#swagger)
