### ISSUE TITLE
Add URL/Request/Response rewriting to ocelot config

### ISSUE THREAD

**Issue by williamwsmith** [ThreeMammals/Ocelot#781]
## New Feature
Leverage aspnet core rewrite middle ware components to get re-writing of requests (and responses).
Both IIS and modrewrite styles are supported in aspnet core.  The internal rewrite rules
can be supported directly in the ocelot configs upstream  and downstream sections.
The actual aspnet middleware does not need to be used, just the classes responsibile for
parsing the rules languages and ability to transform http messages.
Note, inbound and outbound is truly needed.
This does lead to have some initial webAPI firewall type abilities as well the are available on 
other API gateways.

See here: https://github.com/aspnet/AspNetCore/tree/master/src/Middleware/Rewrite
In particular the tests are helpful.

**Comment by raman-m** [comment]
We are not going to integrate to IIS modules!
If you will contribute then as a team we are totally OK to add this new provider\module to our repo.
