### ISSUE TITLE
AddOcelot writes to wrong directory with IIS and InProcess hostingModel

### ISSUE THREAD

**Issue by stefankip** [ThreeMammals/Ocelot#783]
I've recently updated a ASP.NET Core project to v2.2.1 and I'm using IIS with the `hostingModel` set to `InProcess`.
The problem is with the AddOcelot method, to be precise this line:
`File.WriteAllText("ocelot.json", json);` (https://github.com/EdwinVW/Ocelot/blob/develop/src/Ocelot/DependencyInjection/ConfigurationBuilderExtensions.cs#L72)
The CurrentDirectory is set to the `inetserv` folder, instead of the application's root path.
Despite the call to `SetBasePath(hostingContext.HostingEnvironment.ContentRootPath)`.

So for now I'm setting the CurrentDirectory manually before calling AddOcelot, but it looks to me like a bigger issue?

Ocelot v13.0.0

**Comment by jmezach** [comment]
This is probably related to aspnet/AspNetCore#4206 which was fixed with ASP.NET Core 2.2.2.

**Comment by stefankip** [comment]
Yes you're right. Meanwhile I was already using v2.2.2 and I removed the manual call to set the current directory and everything's fine. Thanks!
