### ISSUE TITLE
Support for .Net Core 2.2

### ISSUE THREAD

**Issue by wrakocy** [ThreeMammals/Ocelot#784]
Hi all,

Wondering if someone could provide guidance regards to future support for .Net Core 2.2.

Cheers!

**Comment by geffzhang** [comment]
Ocelot is an net standard 2.0 library， It support .NET Core 2.2

**Comment by thiagoloureiro** [comment]
What the issue with .net core 2.2 and Ocelot? Please clarify

**Comment by wrakocy** [comment]
@thiagoloureiro, yes, fair enough. We're in the process of migrating from .Net Core 2.1 to 2.2 and have been plagued by an intractable "ANCM In-Process Handler Load Failure" on a single assembly - our Ocelot-driven gateway (which runs perfectly on 2.1). As the gateway is extremely light weight, and all other assemblies load fine within 2.2, I had attributed the problem to an Ocelot-related conflict with 2.2. Sounds like I may have spoken to soon on that....

**Comment by geffzhang** [comment]
This should be a read config problem caused by changes in the ANCM process model？ @wrakocy

**Comment by yuft** [comment]
@wrakocy , I believe it is not relevant to Ocelot.
Did you take a look at https://github.com/aspnet/AspNetCore/issues/6111#issuecomment-451294361

make sure you have modified web.config to use AspNetCoreModuleV2 and you may find useful information in windows event logs.

**Comment by wrakocy** [comment]
@yuft yes, thanks for the pointer. I had read that thread (and various others) regards to web.config changes, windows event log clues, etc. None of them have panned out. That said, I suspect the consensus on this thread is correct: this problem is not specific to Ocelot. If I find otherwise, I will update the thread. Cheers all!

**Comment by wrakocy** [comment]
just to confirm, we've sorted this out. yes, Ocelot had absolutely nothing to do with it :/ root cause was a runtime versioning issue (we had 2.2.1 installed and 2.2.2 was required to get ANCMV2 working). closing this out and thanks all!
