### ISSUE TITLE
Support for the use of Consul with Ocelot

### ISSUE THREAD

**Issue by HakanKaraoglu** [ThreeMammals/Ocelot#789]
I have a question. One Api Gateway project and two application(catalog,order) service, I have total three project. Catalog and Order services use Api Gateway . Simple a gateway project. The project is working

However, when I added a consul to this project, ApiGateway not working. Only Consul working. I want to both application run. How can I do that?

You can see project detail : https://github.com/HakanKaraoglu/OcelotApiGateway

Note: The Consul works on the Docker

## Specifications

  - Version: 13.0.0
  - Platform: Windows x64
  - Subsystem: Visual Studio Code, Docker

**Comment by nhapentor** [comment]
Not sure if your case is same as mine but by changing the Configure method in Startup.cs to not using async/await as follow works for me. 

```
        public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }
            else
            {
                app.UseHsts();
            }

            app.UseHttpsRedirection();
            app.UseMvc();
            app.UseOcelot().Wait();
        }
```
N.B. My case seems similar to https://github.com/ThreeMammals/Ocelot/issues/387 that I got 404 when send request to the API Gateway

**Comment by HakanKaraoglu** [comment]
I tried but the application gave the following error 

![image](https://user-images.githubusercontent.com/12962730/53291920-d0a6ec80-37cb-11e9-983c-698ca6cf0daa.png)

**Comment by nhapentor** [comment]
Delete these 2 lines from ocelot.json should work if you just want to use Consul to store configuration

- "ServiceName": "catalog",
- "ServiceName": "order",

**Comment by HakanKaraoglu** [comment]
does not work, gives the same error

**Comment by nhapentor** [comment]
hmmm, strange. I checked out your code and made changes as I wrote here, then it works.
