### ISSUE TITLE
Problem with forwarding body of post method over OCELOT to asp.net API

### ISSUE THREAD

**Issue by CoviloMilos** [ThreeMammals/Ocelot#792]
## Expected Behavior / New Feature
I am sending post method with body (Content-Type application/json) to asp.net Web API over Ocelot. Web API is working fine when I am testing it by sending request directly to him.

## Actual Behavior / Motivation for New Feature
My request is received by asp.net Web API but with body which is null.

## Steps to Reproduce the Problem

 1. Sending request with postman (post method, body application/json)
2. Ocelot receive method and route it to the web api
3. Web API receive null

## Specifications

  - Version: Ocelot 13.0.0
  - Platform: Windows 10
  - Subsystem:

**Comment by osovitskiy** [comment]
I encountered the same issue. This happens when other middleware triggers request buffering before Ocelot.
I created sample solution to demonstrate problem: https://github.com/osovitskiy/ocelot-sample

**Comment by forgotten-warrior** [comment]
Any update on this topic, I encountered the same issue. This happens when other middleware triggers request buffering before Ocelot.

**Comment by osovitskiy** [comment]
@serjebulavsky 
You can workaround problem by using delegating handler like this without turning off buffering
https://github.com/osovitskiy/ocelot-sample/blob/master/Gateway/MissingBodyDelegatingHandler.cs

**Comment by serjebulavsky** [comment]
Thank you @osovitskiy, will have a look

**Comment by SuricateCan** [comment]
@osovitskiy I used your workaround for some time, and it worked.
But when I needed to upload a file, it failed with `System.FormatException: The format of value 'multipart/form-data; boundary=--------------------------263426338817896429400771' is invalid.`.
I ended up rolling back and preventing Sentry to enable buffering, using this tip: https://github.com/getsentry/sentry-dotnet/issues/387#issuecomment-609849622

> Another option is to disable request buffering:
> leave `MaxRequestBodySize` as the default value which is `None`

**Comment by raman-m** [comment]
@CoviloMilos
Not accepted! Lack of description and issue artifacts!
