### ISSUE TITLE
Templating configuration

### ISSUE THREAD

**Issue by jmezach** [ThreeMammals/Ocelot#802]
## New Feature
Currently Ocelots reroutes contain all the configuration for a specific combination of upstream and downstream API's. While this provides great flexibility, it can also become fairly repetitive. It also makes configuring new upstream/downstream API combinations more difficult than it has to be IMHO.

For example, I'm currently looking into using Ocelot to create an abstraction layer for our existing API's in order to eventually implement a new authentication mechanism. So we currently see three different patterns of communication: a pass-through setup where we just pass the request as-is to the downstream API, a setup where we accept the current authentication mechanism and translate that to headers on the downstream request and finally a setup where we accept the new authentication mechanism and translate that to the same set of headers to the downstream services.

Based on our initial investigations we're fairly confident that we can implement this with Ocelot, however we're a little worried of the amount of configuration we'll eventually need to serve our existing API's and client applications.

It would be nice if we would have a way to define the 3 ways of communicating (pass-through, legacy authentication, new authentication) once in terms of the pipeline configuration needed to make that work and then reference those configurations for each combination of upstream/downstream API's. 

Do you think this is something that would be interesting to the larger Ocelot community?

**Comment by raman-m** [comment]
> Based on our initial investigations we're fairly confident that we can implement this with Ocelot, however **we're a little worried of the amount of configuration we'll eventually need to serve our existing API's and client applications.**

Please use [Service Discovery](https://ocelot.readthedocs.io/en/latest/features/servicediscovery.html) and your **ocelot.json** file will be tiny.

**Comment by raman-m** [comment]
> a pass-through setup where we just pass the request as-is to the downstream API, 

Use [Catch All](https://ocelot.readthedocs.io/en/latest/features/routing.html#id1) feature to handle all traffic/URL.

**Comment by raman-m** [comment]
> legacy authentication, new authentication

Develop your authentication policies by ASP.NET, lazy bones!

>It would be nice if we would have a way to define the 3 ways of communicating (pass-through, legacy authentication, new authentication) once in terms of the pipeline configuration needed to make that work and then reference those configurations for each combination of upstream/downstream API's.

Define 3 types of routes using [Delegating Handler](https://ocelot.readthedocs.io/en/latest/features/delegatinghandlers.html) feature and define each route as handler-typed one.

**Comment by raman-m** [comment]
Not accepted!
