### ISSUE TITLE
Allow downstream host to contain placeholders

### ISSUE THREAD

**Issue by MattMinke** [ThreeMammals/Ocelot#803]
## New Feature
Allow the Host configuration element to have placeholders that can be replaced by values from the upstream template.
```JSON
{
    "DownstreamPathTemplate": "/api/{everything}",
    "DownstreamScheme": "http",
    "DownstreamHostAndPorts": [
        {
            "Host": "{service}-{version}",
            "Port": 80
        }
    ],
    "UpstreamPathTemplate": "/{namespace}/webappgateway/{service}/{version}/{everything}",
    "UpstreamHttpMethod": [ "GET", "POST", "PUT", "DELETE" ]
}
```

To work around this limitation we need to create a series of configurations like this 

```JSON
{
    "DownstreamPathTemplate": "/api/{everything}",
    "DownstreamScheme": "http",
    "DownstreamHostAndPorts": [
        {
            "Host": "myservice-v1",
            "Port": 80
        }
    ],
    "UpstreamPathTemplate": "/{namespace}/webappgateway/myservice/v1/{everything}",
    "UpstreamHttpMethod": [ "GET", "POST", "PUT", "DELETE" ]
}, 
{
    "DownstreamPathTemplate": "/api/{everything}",
    "DownstreamScheme": "http",
    "DownstreamHostAndPorts": [
        {
            "Host": "myservice-v2",
            "Port": 80
        }
    ],
    "UpstreamPathTemplate": "/{namespace}/webappgateway/myservice/v2/{everything}",
    "UpstreamHttpMethod": [ "GET", "POST", "PUT", "DELETE" ]
},
{
    "DownstreamPathTemplate": "/api/{everything}",
    "DownstreamScheme": "http",
    "DownstreamHostAndPorts": [
        {
            "Host": "anotherservice-v10",
            "Port": 80
        }
    ],
    "UpstreamPathTemplate": "/{namespace}/webappgateway/anotherservice/v10/{everything}",
    "UpstreamHttpMethod": [ "GET", "POST", "PUT", "DELETE" ]
}
```

## Motivation for New Feature
This provides additional configurability that Ocelot currently does not have that would help in our migration efforts from our current poorly performing gateway to Ocelot as our gateways.

**Comment by NorekZ** [comment]
I would also very appreciate this feature.

**Comment by labarilem** [comment]
This would be very useful indeed.

**Comment by labarilem** [comment]
Would you guys be interested in a PR for this feature? 🤔

**Comment by raman-m** [comment]
>@MattMinke commented [Mar 9, 2019](https://github.com/ThreeMammals/Ocelot/issues/803#issue-418976902)

Why not to use [Service Discovery](https://ocelot.readthedocs.io/en/latest/features/servicediscovery.html) feature? ...instead of requesting something very specific.
In addition seems you need to develop [Custom Provider](https://ocelot.readthedocs.io/en/latest/features/servicediscovery.html#custom-providers).

**Finally,** I would say that current Placeholders logic is complex and  small refactoring can take abnormal efforts to implement your feature and stabilize current logic.
Sorry, we cannot accept this request.

**If you need this feature really, please contribute!**

**Comment by raman-m** [comment]
> @labarilem commented [on Jun 23, 2020](https://github.com/ThreeMammals/Ocelot/issues/803#issuecomment-647807267)

Hi Marco!
Yes, we would!
Have you developed a solution?
