### ISSUE TITLE
Custom Certificate validation logic

### ISSUE THREAD

**Issue by Zirias** [ThreeMammals/Ocelot#812]
We'd like to use certificates for backend services that don't match the host names of the machines they are deployed to. Still, we'd like to verify them against the name we expect and a valid chain. Right now, Ocelot only offers default validation or no validation at all. To implement a custom validation, we'd need a custom `HttpClientHandler` (or at least a way to provide an implementation for `HttpClientHandler.ServerCertificateCustomValidationCallback`).

Any chance to get this kind of flexibility? One way I could think about would be to have a callback in `OcelotPipelineConfiguration` that's called on newly created `HttpClientHandler`s, allowing to modify them before they are used to make backend calls. If this sounds like a valid solution, I could attempt to implement it myself and create a pull request ...

**Comment by raman-m** [comment]
Your solution will be [DangerousAcceptAnyServerCertificateValidator](https://ocelot.readthedocs.io/en/latest/search.html?q=DangerousAcceptAnyServerCertificateValidator)
