### ISSUE TITLE
Ocelot not forwarding request if the RouteClaimsRequirement contains multiple roles

### ISSUE THREAD

**Issue by salmaniqbal92** [ThreeMammals/Ocelot#820]
# Expected Behavior / New Feature
The request should forward to the downstream path if it contains the role in **RouteClaimsRequirement**

## Actual Behavior / Motivation for New Feature
When we send the request to the upstream path with valid roles it does not forward the request and give the response 403 Forbidden. We have one role in claims and an array of roles in **RouteClaimsRequirement**.

I receive this below warning and the Ocelot does not forward the request to the downstream path.

> warn: Ocelot.DownstreamRouteFinder.Middleware.DownstreamRouteFinderMiddleware[0]
> requestId: 0HLLCB8LIE4AA:00000003, previousRequestId: no previous request id, message: DownstreamRouteFinderMiddleware setting pipeline errors. 
> IDownstreamRouteFinder returned Error Code: UnableToFindDownstreamRouteError Message: Failed to match ReRoute configuration for upstream path: /api/user, verb: PUT.
> 
> warn: Ocelot.Responder.Middleware.ResponderMiddleware[0]
> requestId: 0HLLCB8LIE4AA:00000003, previousRequestId: no previous request id, message: Error Code: UnableToFindDownstreamRouteError Message: Failed to match ReRoute configuration for upstream path: /api/user, verb: PUT. errors found in ResponderMiddleware. Setting error response for request path:/api/user, request method: PUT

I have this Ocelot.json setting

> {
>             "DownstreamScheme": "http",
>             "UpstreamHttpMethod": [ "Put" ],
>             "UpstreamPathTemplate": "/api/user",
>             "DownstreamPathTemplate": "/api/user",
>             "DownstreamHostAndPorts": [
>                 {
>                     "Host": "localhost",
>                     "Port": 8909
>                 }
>             ],
>             "AuthenticationOptions": {
>                 "AuthenticationProviderKey": "Bearer",
>                 "AllowedScopes": []
>             },
>             "RouteClaimsRequirement": {
>                 "role": [ "admin", "superadmin" ]
>             },
>             "AddHeadersToRequest": {
>                 "id": "Claims[sub] > value > |",
>                 "email": "Claims[email] > value > |",
>                 "username": "Claims[username] > value > |",
>                 "role": "Claims[role] > value > |"
>             }
>         },

I have a valid JWT token with roles in it as an array

  

> "idp": "local",
>   "username": "superAdmin",
>   "email": "superAdmin@xyz.com",
>   "role": [
>     "superadmin",
>     "admin"
>   ],

I'm not sure where and what I'm doing wrong and why the ocelot does not forwading my request to the controller.

## Specifications

  - Version: 13.0.0
  - Platform: .Net Core

@TomPallister can you please look into and help me out if I'm missing something?

**Comment by royayan1988** [comment]
@TomPallister is this fixed?

**Comment by coleman-c** [comment]
Hitting the same issue here.  Removing the Route claims requirement make it find the route.

- Ocelot 13.5.2
- .net core 2.2

Found:
`
[40m[32minfo[39m[22m[49m: idunno.Authentication.Certificate.CertificateAuthenticationHandler[8]
      AuthenticationScheme: Certificate was successfully authenticated.
idunno.Authentication.Certificate.CertificateAuthenticationHandler:Information: AuthenticationScheme: Certificate was successfully authenticated.
Ocelot.Errors.Middleware.ExceptionHandlerMiddleware:Debug: requestId: 0HLOQG5PQAJQO:00000001, previousRequestId: no previous request id, message: ocelot pipeline started
[40m[37mdbug[39m[22m[49m: Ocelot.Errors.Middleware.ExceptionHandlerMiddleware[0]
      requestId: 0HLOQG5PQAJQO:00000001, previousRequestId: no previous request id, message: ocelot pipeline started
Ocelot.DownstreamRouteFinder.Middleware.DownstreamRouteFinderMiddleware:Debug: requestId: 0HLOQG5PQAJQO:00000001, previousRequestId: no previous request id, message: Upstream url path is /ResponseDelivery
[40m[37mdbug[39m[22m[49m: Ocelot.DownstreamRouteFinder.Middleware.DownstreamRouteFinderMiddleware[0]
      requestId: 0HLOQG5PQAJQO:00000001, previousRequestId: no previous request id, message: Upstream url path is /ResponseDelivery
[40m[37mdbug[39m[22m[49m: Ocelot.DownstreamRouteFinder.Middleware.DownstreamRouteFinderMiddleware[0]
      requestId: 0HLOQG5PQAJQO:00000001, previousRequestId: no previous request id, message: downstream templates are /api/ResponseDelivery?{everything}
Ocelot.DownstreamRouteFinder.Middleware.DownstreamRouteFinderMiddleware:Debug: requestId: 0HLOQG5PQAJQO:00000001, previousRequestId: no previous request id, message: downstream templates are /api/ResponseDelivery?{everything}
Ocelot.RateLimit.Middleware.ClientRateLimitMiddleware:Information: requestId: 0HLOQG5PQAJQO:00000001, previousRequestId: no previous request id, message: EndpointRateLimiting is not enabled for /api/ResponseDelivery?{everything}
[40m[32minfo[39m[22m[49m: Ocelot.RateLimit.Middleware.ClientRateLimitMiddleware[0]
      requestId: 0HLOQG5PQAJQO:00000001, previousRequestId: no previous request id, message: EndpointRateLimiting is not enabled for /api/ResponseDelivery?{everything}
Ocelot.Authentication.Middleware.AuthenticationMiddleware:Information: requestId: 0HLOQG5PQAJQO:00000001, previousRequestId: no previous request id, message: /ResponseDelivery is an authenticated route. AuthenticationMiddleware checking if client is authenticated
[40m[32minfo[39m[22m[49m: Ocelot.Authentication.Middleware.AuthenticationMiddleware[0]
      requestId: 0HLOQG5PQAJQO:00000001, previousRequestId: no previous request id, message: /ResponseDelivery is an authenticated route. AuthenticationMiddleware checking if client is authenticated
[40m[32minfo[39m[22m[49m: idunno.Authentication.Certificate.CertificateAuthenticationHandler[8]
      AuthenticationScheme: Certificate was successfully authenticated.
idunno.Authentication.Certificate.CertificateAuthenticationHandler:Information: AuthenticationScheme: Certificate was successfully authenticated.
Ocelot.Authentication.Middleware.AuthenticationMiddleware:Information: requestId: 0HLOQG5PQAJQO:00000001, previousRequestId: no previous request id, message: Client has been authenticated for /ResponseDelivery
[40m[32minfo[39m[22m[49m: Ocelot.Authentication.Middleware.AuthenticationMiddleware[0]
      requestId: 0HLOQG5PQAJQO:00000001, previousRequestId: no previous request id, message: Client has been authenticated for /ResponseDelivery
[40m[32minfo[39m[22m[49m: Ocelot.Authorisation.Middleware.AuthorisationMiddleware[0]
      requestId: 0HLOQG5PQAJQO:00000001, previousRequestId: no previous request id, message: route is authenticated scopes must be checked
Ocelot.Authorisation.Middleware.AuthorisationMiddleware:Information: requestId: 0HLOQG5PQAJQO:00000001, previousRequestId: no previous request id, message: route is authenticated scopes must be checked
Ocelot.Authorisation.Middleware.AuthorisationMiddleware:Information: requestId: 0HLOQG5PQAJQO:00000001, previousRequestId: no previous request id, message: user scopes is authorised calling next authorisation checks
[40m[32minfo[39m[22m[49m: Ocelot.Authorisation.Middleware.AuthorisationMiddleware[0]
      requestId: 0HLOQG5PQAJQO:00000001, previousRequestId: no previous request id, message: user scopes is authorised calling next authorisation checks
[40m[32minfo[39m[22m[49m: Ocelot.Authorisation.Middleware.AuthorisationMiddleware[0]
      requestId: 0HLOQG5PQAJQO:00000001, previousRequestId: no previous request id, message: /api/ResponseDelivery?{everything} route does not require user to be authorised
Ocelot.Authorisation.Middleware.AuthorisationMiddleware:Information: requestId: 0HLOQG5PQAJQO:00000001, previousRequestId: no previous request id, message: /api/ResponseDelivery?{everything} route does not require user to be authorised
[40m[37mdbug[39m[22m[49m: Ocelot.DownstreamUrlCreator.Middleware.DownstreamUrlCreatorMiddleware[0]
      requestId: 0HLOQG5PQAJQO:00000001, previousRequestId: no previous request id, message: Downstream url is http://server-name/api/ResponseDelivery?api-version=1.0&api-version=1.0
`

Not Found:
`
[40m[32minfo[39m[22m[49m: idunno.Authentication.Certificate.CertificateAuthenticationHandler[8]
      AuthenticationScheme: Certificate was successfully authenticated.
idunno.Authentication.Certificate.CertificateAuthenticationHandler:Information: AuthenticationScheme: Certificate was successfully authenticated.
Ocelot.Errors.Middleware.ExceptionHandlerMiddleware:Debug: requestId: 0HLOQG7DG38HN:00000001, previousRequestId: no previous request id, message: ocelot pipeline started
Ocelot.DownstreamRouteFinder.Middleware.DownstreamRouteFinderMiddleware:Debug: requestId: 0HLOQG7DG38HN:00000001, previousRequestId: no previous request id, message: Upstream url path is /ResponseDelivery
[40m[37mdbug[39m[22m[49m: Ocelot.Errors.Middleware.ExceptionHandlerMiddleware[0]
      requestId: 0HLOQG7DG38HN:00000001, previousRequestId: no previous request id, message: ocelot pipeline started
[40m[37mdbug[39m[22m[49m: Ocelot.DownstreamRouteFinder.Middleware.DownstreamRouteFinderMiddleware[0]
      requestId: 0HLOQG7DG38HN:00000001, previousRequestId: no previous request id, message: Upstream url path is /ResponseDelivery
[40m[1m[33mwarn[39m[22m[49m: Ocelot.DownstreamRouteFinder.Middleware.DownstreamRouteFinderMiddleware[0]
      requestId: 0HLOQG7DG38HN:00000001, previousRequestId: no previous request id, message: DownstreamRouteFinderMiddleware setting pipeline errors. IDownstreamRouteFinder returned Error Code: UnableToFindDownstreamRouteError Message: Failed to match ReRoute configuration for upstream path: /ResponseDelivery, verb: POST.
Ocelot.DownstreamRouteFinder.Middleware.DownstreamRouteFinderMiddleware:Warning: requestId: 0HLOQG7DG38HN:00000001, previousRequestId: no previous request id, message: DownstreamRouteFinderMiddleware setting pipeline errors. IDownstreamRouteFinder returned Error Code: UnableToFindDownstreamRouteError Message: Failed to match ReRoute configuration for upstream path: /ResponseDelivery, verb: POST.
[40m[1m[33mwarn[39m[22m[49m: Ocelot.DownstreamRouteFinder.Middleware.DownstreamRouteFinderMiddleware[0]
      requestId: 0HLOQG7DG38HN:00000001, previousRequestId: no previous request id, message: Failed to match ReRoute configuration for upstream path: /ResponseDelivery, verb: POST.
Ocelot.DownstreamRouteFinder.Middleware.DownstreamRouteFinderMiddleware:Warning: requestId: 0HLOQG7DG38HN:00000001, previousRequestId: no previous request id, message: Failed to match ReRoute configuration for upstream path: /ResponseDelivery, verb: POST.
[40m[1m[33mwarn[39m[22m[49m: Ocelot.Responder.Middleware.ResponderMiddleware[0]
      requestId: 0HLOQG7DG38HN:00000001, previousRequestId: no previous request id, message: Error Code: UnableToFindDownstreamRouteError Message: Failed to match ReRoute configuration for upstream path: /ResponseDelivery, verb: POST. errors found in ResponderMiddleware. Setting error response for request path:/ResponseDelivery, request method: POST
Ocelot.Responder.Middleware.ResponderMiddleware:Warning: requestId: 0HLOQG7DG38HN:00000001, previousRequestId: no previous request id, message: Error Code: UnableToFindDownstreamRouteError Message: Failed to match ReRoute configuration for upstream path: /ResponseDelivery, verb: POST. errors found in ResponderMiddleware. Setting error response for request path:/ResponseDelivery, request method: POST
[40m[37mdbug[39m[22m[49m: Ocelot.Errors.Middleware.ExceptionHandlerMiddleware[0]
      requestId: 0HLOQG7DG38HN:00000001, previousRequestId: no previous request id, message: ocelot pipeline finished
`

**Comment by raman-m** [comment]
@royayan1988 @salmaniqbal92
If you want a fix, please fix it, and contribute!

But I don't see any bug... I see misconfiguration issue.
