### ISSUE TITLE
Low performance even with logging disabled

### ISSUE THREAD

**Issue by Rakiah** [ThreeMammals/Ocelot#827]
Hello, I've been getting bad performance using Ocelot using bombardier as a benchmark:

I'm capping at 1194.93 req/s even though I disabled logging like so:
```c#
   services.AddLogging(logging =>
   {
      logging.ClearProviders();
      logging.SetMinimumLevel(LogLevel.None); 
   });
```
I'm actually wondering, if I am doing wrong or not? The gateway runs inside a container that is assigned 8 CPU core running at 2.4 GHz using docker stats. I see that the Gateway goes up to 280% CPU usage (2.8 cores basically) while the microservice that is receiving the request from the gateway does not go higher that 8% CPU and can handle as much as 60K req/s.

**Comment by Rakiah** [comment]
bump

**Comment by Rakiah** [comment]
Anyone had the same problem ?

**Comment by kapilepatel** [comment]
@Rakiah Please share available memory and memory usage also, it will be useful for us.

**Comment by danielearrighi** [comment]
Hello, we are having the exact same problem: point blank, usual traffic, usual requests per seconds, it started using 2 CPU.

I can only add some log from our IT management:
`procs -----------memory---------- ---swap-- -----io---- -system-- ------cpu-----
 r  b   swpd   free   buff  cache   si   so    bi    bo   in   cs us sy id wa st
 1  0      0 4572576   4172 25245588    0    0     0     0  753  864  4  0 96  0  0
 7  0      0 4572608   4172 25245596    0    0     0   112 3568 72204 23  8 69  0  0
 3  0      0 4572716   4172 25245572    0    0     0     0 4543 47964 31  6 63  0  0
 0  0      0 4572716   4172 25245572    0    0     0     0 1189 1976  8  1 92  0  0
 1  0      0 4572716   4172 25245572    0    0     0     0  796  976  5  0 95  0  0
 0  0      0 4572748   4172 25245572    0    0     0     0  640  856  3  1 96  0  0
 5  0      0 4572716   4172 25245588    0    0     0     0 3349 67675 22  7 70  0  0
 2  0      0 4572748   4172 25245588    0    0     0     0 4595 46247 29  7 64  0  0
 3  0      0 4572748   4172 25245588    0    0     0     0 1229 1464  8  1 91  0  0
 0  0      0 4572748   4172 25245588    0    0     0     0  673  794  4  0 96  0  0
 0  0      0 4572748   4172 25245588    0    0     0     0  787  938  5  0 95  0  0
 7  0      0 4572748   4172 25245596    0    0     0    28 3306 67177 25  7 68  0  0
 0  0      0 4572828   4172 25245596    0    0     0     0 4851 43691 30  7 63  0  0
 0  0      0 4572828   4172 25245596    0    0     0     0 1156 1399  7  1 93  0  0
 1  0      0 4572828   4172 25245600    0    0     0     0  775  895  4  1 95  0  0
 0  0      0 4572828   4172 25245600    0    0     0     0  896 1145  5  1 94  0  0
 0  0      0 4572860   4172 25245608    0    0     0    20 3370 72391 23  6 71  0  0
 2  0      0 4572860   4172 25245608    0    0     0     0 4507 41270 27  6 66  0  0
 0  0      0 4572860   4172 25245608    0    0     0     0 1159 1401  7  1 93  0  0
 1  0      0 4568796   4172 25245608    0    0     0     0 1675 2023  8  3 89  0  0
 0  0      0 4567964   4172 25245852    0    0     0     0 1295 1347  7  1 92  0  0
 5  0      0 4567764   4172 25245868    0    0     0     0 3644 74204 23  8 68  0  0
 1  0      0 4567968   4172 25245792    0    0     0    32 5016 42939 28  9 64  0  0
 0  0      0 4571856   4172 25245856    0    0     0    24 2500 2984 10  4 85  0  0
 0  0      0 4572300   4172 25245896    0    0     0   208 1080 1541  4  2 94  0  0
 0  0      0 4572300   4172 25245896    0    0     0     0  776 1028  4  1 95  0  0
 3  0      0 4572176   4172 25245904    0    0     0     8 3418 78537 23  7 70  0  0
 1  0      0 4572176   4172 25245904    0    0     0     0 4526 39426 29  6 65  0  0
 0  0      0 4572176   4172 25245904    0    0     0     0 1080 1379  7  1 92  0  0
 0  0      0 4572176   4172 25245904    0    0     0     0  711  952  5  0 95  0  0
 0  0      0 4572176   4172 25245904    0    0     0     0  689  785  4  0 96  0  0
 2  0      0 4572208   4172 25245916    0    0     0   276 3554 72050 24  8 68  0  0
 1  0      0 4572184   4172 25245924    0    0     0     0 4680 42825 31  7 62  0  0
 0  0      0 4572308   4172 25245924    0    0     0     0 1212 1669  8  1 92  0  0
 0  0      0 4572308   4172 25245924    0    0     0     0  822 1073  5  1 95  0  0
 0  0      0 4572308   4172 25245924    0    0     0     0  661  899  3  1 96  0  0
 2  0      0 4572308   4172 25245932    0    0     0    12 3369 69798 23  8 69  0  0
 0  0      0 4572308   4172 25245932    0    0     0     0 4702 44439 29  7 64  0  0
 0  0      0 4572308   4172 25245932    0    0     0     0 1229 1618  7  1 92  0  0
 0  0      0 4572308   4172 25245932    0    0     0     0  717  855  4  0 96  0  0
 0  0      0 4572308   4172 25245932    0    0     0     0  809  926  5  1 95  0  0
 6  0      0 4572324   4172 25245940    0    0     0    16 3619 71829 25  6 69  0  0
 1  0      0 4572604   4172 25245940    0    0     0     0 4637 43370 31  7 62  0  0`

One line = one second. As you can see, every 5 seconds (rougly) there is a CPU spike (garbage collection maybe?). Before this point, the gateway was running smoothly for 5 months. A restart of the gateway server solved the problem.

Using netcore 2.0 with Ocelot 6.0.0

**Comment by joepperkins** [comment]
I had the same problem, removing the logging.SetMinimumLevel fixed the issue. Seems to have something to do with it adding the logging filter in the extension method also seems any log level will have the same performance impact.

I ended up using AI TelemetryProcessor and filter there.

**Comment by raman-m** [comment]
Hi @ggnaegi ! FYI see prev message.
You need to check these user cases above with logging issues.

**Comment by raman-m** [comment]
Hi @Rakiah !
Are you still with Ocelot?

**Comment by ggnaegi** [comment]
@raman-m We might have two problems here: The Request Mapper, that is slow and using quite a bit of memory and the Logger - where we don't check if we should or not log the messages- . Btw, I had the same problem on Azure, we were wondering why suddenly the memory usage went up.

**Comment by raman-m** [comment]
@ggnaegi Wow! Critical problem detected!
Well... Do you recommend to return to this issue back after merging all open PR related to `RequestMapper` and Ocelot logger?
Let's preselect this bug for November release. I am going to assign High priority, but for the next release...

**Comment by ggnaegi** [comment]
> @ggnaegi Wow! Critical problem detected!
> Well... Do you recommend to return to this issue back after merging all open PR related to `RequestMapper` and Ocelot logger?
> Let's preselect this bug for November release. I am going to assign High priority, but for the next release...

Yes I would recommend bombarding ocelot in november...

**Comment by raman-m** [comment]
@ggnaegi I believe we can link this issue to current open [Nov'23](../milestone/2) PRs related to logging and request mapper, right?
Or, Is this perf problem quite different?

**Comment by raman-m** [comment]
@Rakiah Dear Beranger,
Do you still live in Ocelot world? :tiger:

**Comment by raman-m** [comment]
@ggnaegi  Could you attach this issue to your PRs please?
And, I hope performance will be improved in new version...
The author didn't provide any Steps to reproduce, that's bad. Any ideas on repro?

**Comment by raman-m** [comment]
@ggnaegi I guess this issue can be linked to #1724  where we will ensure and watch the symptoms of this bug... 🆗 ❔
