### ISSUE TITLE
Stable release for 13.x.x

### ISSUE THREAD

**Issue by emiliovmq** [ThreeMammals/Ocelot#837]
Any idea on how much it's gonna take to produce a final stable release for version 13.x.x (NuGet package)?  Let me clarify, I know there is a release (with its respective NuGet package) already available and fixing the issues I submitted a day ago, but unfortunately, in our company, there are certain rules (as UAT constraints, integration, security, and others) that make impossible for us to release our product with "non-stable" - beta, alpha, RC. - libraries (wherever they could come from).  

By the way, great work!!!

**Comment by thiagoloureiro** [comment]
I created a branch release 13.2.0 yesterday But I didn't had enough permissions to publish.
@TomPallister  I followed the requirements but the part of GitHub Release didn't worked out, and the ocelot-release was not triggered.

Can you help us with that? thanks!

**Comment by thiagoloureiro** [comment]
Edit, Didn't worked, @TomPallister  need your input please

**Comment by thiagoloureiro** [comment]
Release 13.4.1
