### ISSUE TITLE
Ocelot with IdentityServer4

### ISSUE THREAD

**Issue by WisemanIka** [ThreeMammals/Ocelot#839]
Hello,

I want to use Ocelot with IdentityServer4 to implement authentication, but I have problem with error 401 Unauthorized...

I registered ocelot as a ApiResource in IdentityServer

IdentityServer Configuration Startup.cs: 

            services.AddIdentityServer()
                .AddDeveloperSigningCredential()
                .AddInMemoryIdentityResources(IdentityServerConfigurations.GetIdentityResources())
                .AddInMemoryApiResources(IdentityServerConfigurations.GetApiResources())
                .AddInMemoryClients(IdentityServerConfigurations.GetClients())
                .AddAspNetIdentity<User>();

Config.cs

        public static IEnumerable<IdentityResource> GetIdentityResources()
        {
            return new IdentityResource[]
            {
                new IdentityResources.OpenId()
            };
        }

        public static IEnumerable<ApiResource> GetApiResources()
        {
            return new ApiResource[]
            {
                new ApiResource("basket", "Basket API Desc"),
                new ApiResource
                {
                    Name = "ocelot",
                    Description = "Ocelot Gateway",
                    //ApiSecrets = {
                    //    new Secret("secret".Sha256())
                    //}
                }
            };
        }

        public static IEnumerable<Client> GetClients()
        {
            return new Client[]
            {
                new Client
                {
                    ClientId = "Angular",
                    ClientName = "Angular SPA",
                    AllowedGrantTypes = GrantTypes.ClientCredentials,
                    ClientSecrets = {
                        new Secret("c0359956-eb75-480b-adde-2c33de5f3900".Sha256())
                    },
                    AllowedScopes = {
                        "basket"
                    }
                }
            };
        }

ocelot project Startup.cs:

      public void ConfigureServices(IServiceCollection services)
        {

            var key = "IdentityServiceApiKey";

            services.AddAuthentication("Bearer")
                .AddIdentityServerAuthentication(key, options =>
                {
                    options.Authority = "http://localhost:8080";
                    options.RequireHttpsMetadata = false;
                    options.ApiName = "ocelot";
                    //options.ApiSecret = "secret";
                });

            services.AddOcelot(Configuration);
        }

and ocelot.json file:

```
{
  "ReRoutes": [
    {
      "DownstreamHostAndPorts": [
        {
          "Host": "localhost",
          "Port": 8085
        }
      ],
      "DownstreamPathTemplate": "/api/basket",
      "UpstreamPathTemplate": "/basket",
      "UpstreamHttpMethod": [ "Get" ],
      "ReRouteIsCaseSensitive": false,
      "DownstreamScheme": "http",
      "AuthenticationOptions": {
        "AuthenticationProviderKey": "IdentityServiceApiKey",
        "ProviderRootUrl": "http://localhost:8080",
        "AllowedScopes": ["openid"]
      }
    }
  ],
  "GlobalConfiguration": {
    "RequestIdKey": "OcRequestId"
  }
}
```

If I remove **AuthenticationOptions** from ocelot configuration it works as I expect but when I put there options it gives me 401 error.

and few more questions... Ocelot acts like a Resource or Client? and what if I use ocelot as IdentityServer too...

**Comment by gilsdav** [comment]
@WisemanIka Hello, did you fix it ? If yes, can you explain how ? I got same issue

**Comment by raman-m** [comment]
@mehmetozkaya
I can prioritize if you've discussed that with the author, and have real solution, and want to contribute.

**Comment by raman-m** [comment]
Hi @WisemanIka!
We don't have any plans to research or develop Ocelot to handle the role of Identity service and management.
Based on our [Big Picture With IdentityServer](https://ocelot.readthedocs.io/en/latest/introduction/bigpicture.html#with-identityserver), the identity server should be a separate service for your tokens.
But in theory, yes, it is possible to delegate tokens creation role to Ocelot app.
Please, do your own researches.
Good luck!
