### ISSUE TITLE
Unhandled NullReferenceException at startup

### ISSUE THREAD

**Issue by sliekens** [ThreeMammals/Ocelot#841]
I encountered an unhandled NullReferenceException when trying to set up a new gateway with Ocelot. I'm sure this is my fault, but it should be made explicit.

## Expected Behavior

Throw a custom exception when the user configuration is wrong or missing.

## Actual Behavior / Motivation for New Feature

`app.UseOcelot().Wait()` blows up

```
Object reference not set to an instance of an object.
   at Ocelot.Middleware.OcelotMiddlewareExtensions.<CreateConfiguration>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ocelot.Middleware.OcelotMiddlewareExtensions.<UseOcelot>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ocelot.Middleware.OcelotMiddlewareExtensions.<UseOcelot>d__0.MoveNext()
```

## Steps to Reproduce the Problem

Program.cs
```diff
public static IWebHostBuilder CreateWebHostBuilder(string[] args)
{
    return WebHost.CreateDefaultBuilder(args)
                  .UseStartup<Startup>()
+                 .ConfigureAppConfiguration(
+                     (builderContext, config) =>
+                     {
+                         config.AddOcelot(builderContext.HostingEnvironment);
+                     });
}
```

Startup.cs
```diff
 public void Configure(IApplicationBuilder app)
 {
+    app.UseOcelot().Wait();
 }
```

## Specifications

  - Version: 13.4.1
  - Platform: Windows 10
  - Subsystem: what?

**Comment by StevenLiekens** [comment]
By the way my error was forgetting to add Ocelot to the IServiceCollection, which was easy to fix on my side, but the point is that the exception should have told me what was wrong.

**Comment by StevenLiekens** [comment]
Possible fix: replace occurrences of `ApplicationServices.GetService<T>()` with `ApplicationServices.GetRequiredService<T>()`.

**Comment by thiagoloureiro** [comment]
@StevenLiekens  I see, do you want to test it  create a PR and we close it ? Thanks!

**Comment by StevenLiekens** [comment]
Yes unfortunately I don't know which services are required... there are quite a few.

**Comment by raman-m** [comment]
Kidding...

**Comment by sliekens** [comment]
> Kidding...

What?
