### ISSUE TITLE
When I use Consul service discovery `UpstreamHost` property isn't working

### ISSUE THREAD

**Issue by wtf-boy** [ThreeMammals/Ocelot#849]
## Expected Behavior / New Feature
When I use DownstreamHostAndPorts directly it works,The following two links point to different services.
article services: [http://gateway.afuyy.com/test](url)
live service: [http://test.gateway.afuyy.com/test](url)
![image](https://user-images.githubusercontent.com/11848141/55397265-69bde580-5578-11e9-8775-73db1a3369f8.png)

when i use consul serviceDiscovery  UpstreamHost not working,Both of the following links point to the same service.
 [http://consulgateway.afuyy.com/test](url)
[http://test.consulgateway.afuyy.com/test](url)
![image](https://user-images.githubusercontent.com/11848141/55397314-8823e100-5578-11e9-9385-c4754e350d0b.png)

![image](https://user-images.githubusercontent.com/11848141/55397939-f0bf8d80-5579-11e9-9c60-0e4c64de37c4.png)
![image](https://user-images.githubusercontent.com/11848141/55397965-f917c880-5579-11e9-84ef-04d3cec36529.png)

## Specifications

  - Version: 
           ocelot version: 12.0.1
           .netcore version: 2.0
  - Platform:
  - Subsystem:

**Comment by thiagoloureiro** [comment]
Where is your consul configuration on ocelot.json ?

**Comment by thiagoloureiro** [comment]
example:

```
{
  "ReRoutes": [
    {
      "DownstreamPathTemplate": "/api/values",
      "DownstreamScheme": "http",
      "UpstreamPathTemplate": "/getvalues",
      "UpstreamHttpMethod": [ "Get" ],
      "FileCacheOptions": { "TtlSeconds": 10 },
      "AuthenticationOptions": {
        "AuthenticationProviderKey": "AuthScheme",
        "AllowedScopes": []
      },
      "ServiceName": "valueapi",
      "LoadBalancerOptions": {
        "Type": "LeastConnection"
      }
    },
    {
      "DownstreamPathTemplate": "/api/auth",
      "DownstreamScheme": "http",
      "ServiceName": "auth",
      "UpstreamPathTemplate": "/api/auth",
      "UpstreamHttpMethod": [ "Get" ]
    }
  ],
  "GlobalConfiguration": {
    "RequestIdKey": null,
    "ServiceDiscoveryProvider": {
      "Host": "localhost",
      "Port": 8500,
      "Type": "Consul"
    },
    "RateLimitOptions": {
      "ClientIdHeader": "ClientId",
      "QuotaExceededMessage": "",
      "RateLimitCounterPrefix": "",
      "DisableRateLimitHeaders": false,
      "HttpStatusCode": 428
    },
    "DownstreamScheme": "http"
  }
}
```

**Comment by wtf-boy** [comment]
on ocelot.global.json
![image](https://user-images.githubusercontent.com/11848141/56403403-c23cf480-6293-11e9-85c6-d933f1f45ffa.png)

**Comment by viveksinghnegi7** [comment]
Facing similar issue.

**Comment by 2821840032** [comment]
Same, so I came.

**Comment by 2821840032** [comment]
Use the same upstream pathtemplate
That's the problem.

**Comment by raman-m** [comment]
Hi @wtf-boy !
Yes, first scenario is correct, the second is invalid.
- usage of the same `"UpstreamPathTemplate": "/test",` is wrong but validator didn't raised the flag because of different `"UpstreamHost"` properties.
- usage of the same `"DownstreamPathTemplate": "/"` could be wrong if you've registered `live` and `article` services in Consul config in a wrong way

I guess both `article`, `live` services point to one host & port pair in Consul config.
Please, double check your Consul config!

**Comment by raman-m** [comment]
@wtf-boy 
Also, I guess maybe [Upstream Host](https://ocelot.readthedocs.io/en/latest/features/routing.html#upstream-host) feature doesn't work at all for Service discovery scenario. Then a normal matching rules select the first route.
But it should be checked... Yeap, #216 is quite simple.

It is hard to guess, and advice something, you have to provide the logs!
Now I see a misconfiguration issue.
Please, upgrade to latest version 22.0 and let us know testing results once again.

**Comment by sliekens** [comment]
This issue will be fixed as part of my PR #1944

**Comment by raman-m** [comment]
@sliekens  Steven,
I can't get it...
How is this issue related to #1496 in #1944 ?!..
Does Load Balancer key influence to finding appropriate service instance in Consul?

@ggnaegi  FYI

**Comment by sliekens** [comment]
@raman-m  Yes, it's all related to route key collisions. The route key does not currently include `UpstreamHost`, so the two routes in the this issue will have the same route key.

Given the current route key format is `UpstreamPathTemplate|UpstreamHttpMethod|DownstreamHostAndPorts`,
then both routes will have the route key: `/test|Get,Post|` (last part empty)

![image](https://github.com/ThreeMammals/Ocelot/assets/1583241/3018e23a-f5e8-471a-9816-1fcea507d993)

My PR will fix this by extending the route key format to make them unique once again.

**Comment by sliekens** [comment]
>Does Load Balancer key uniqueness (bad now) influence to finding appropriate service instance in Consul?

@raman-m no, the route key is not used when reaching out to Consul. However, the route key is used as a cache key, to prevent repeated calls to Consul for the same route. So, repeated calls will only use cached routes, and the problem occurs when route keys from different routes collide with each other, the wrong cached route will be used.

**Comment by raman-m** [comment]
Assigned to @sliekens  :wink: 
Please take care of the user scenarios of this issue in unit & acceptance tests!
You can use `Theory` xUnit attribute.
