### ISSUE TITLE
UpstreamHost different but ReRoutes has duplicate

### ISSUE THREAD

**Issue by duszekmestre** [ThreeMammals/Ocelot#863]
## Expected Behavior / New Feature
UpstreamHost must be used as key in comparing reroutes.

## Actual Behavior / Motivation for New Feature
Now - uUpstreamHost make any difference when UpstreamPathTemplate are the same.

## Steps to Reproduce the Problem

  1. Make two (or more) configurations for ReRouteslike sample:
```json
[
{
      "UpstreamHost": "dev.samedomain.com",
      "UpstreamPathTemplate": "/{url}",
      "UpstreamHttpMethod": [ ],
      "DownstreamScheme": "https",
      "DownstreamPathTemplate": "/{url}",
      "DownstreamHostAndPorts": [
        {
          "Host": "localhost",
          "Port": 443
        }
      ]
    },
{
      "UpstreamHost": "sandbox.samedomain.com",
      "UpstreamPathTemplate": "/{url}",
      "UpstreamHttpMethod": [ ],
      "DownstreamScheme": "https",
      "DownstreamPathTemplate": "/{url}",
      "DownstreamHostAndPorts": [
        {
          "Host": "sandbox",
          "Port": 443
        }
      ]
    }
]
```
  1. Try to run
  1. Unhandled Exception: System.AggregateException: One or more errors occurred. (Unable to start Ocelot, errors are: reRoute /{url} has duplicate,reRoute /{url} has duplicate,reRoute /{url} has duplicate,reRoute /{url} has duplicate,reRoute /{url} has duplicate,reRoute /{url} has duplicate) ---> System.Exception: Unable to start Ocelot, errors are: reRoute /{url} has duplicate,reRoute /{url} has duplicate,reRoute /{url} has duplicate,reRoute /{url} has duplicate,reRoute /{url} has duplicate,reRoute /{url} has duplicate

## Specifications

  - Version: 13.5.0
  - Platform: Windows 10 Pro
  - Subsystem:

**Comment by plukawski** [comment]
I totally agree - this is an important bug that prevents using the Ocelot in certain environments and should be introduced with high priority.
