### ISSUE TITLE
Get 404 with a long query

### ISSUE THREAD

**Issue by walterfranssen** [ThreeMammals/Ocelot#865]
## Expected Behavior / New Feature
Get a 200 response but i get a 404 
The url i try is: 
http://localhost:5000/clients/fda5a247-09b0-4712-8df5-27312e00dae6/timeslots?tenantId=c513fe59-17cc-45a9-aecc-2b3238e0bdf6&appointmentTypeId=215f9781-b56d-4001-93f7-6d55133881dc&selectionPeriodStartDateTimeUtc=2019-04-19&selectionPeriodEndDateTimeUtc=2019-04-25

I see in the log that Ocelot parse the url to the server, but with a 0 at the end, like 
http://localhost:5000/clients/fda5a247-09b0-4712-8df5-27312e00dae6/timeslots?tenantId=c513fe59-17cc-45a9-aecc-2b3238e0bdf6&appointmentTypeId=215f9781-b56d-4001-93f7-6d55133881dc&selectionPeriodStartDateTimeUtc=2019-04-19&selectionPeriodEndDateTimeUtc=2019-04-25 0

Is this a know issue in Ocelot?

**Comment by ks1990cn** [comment]
Hi, looks like more details are required on this. Someone can not reachout to localhost site without code (or on internal network).

**Comment by raman-m** [comment]
@walterfranssen  Hi Walter!
Thanks for your interest in Ocelot!

What will we do with your issue reporting?
Would you still like to contribute?
If Yes, you need to provide more details on your user case: exception log, config JSON etc...

**Comment by raman-m** [comment]
No communication!
