### ISSUE TITLE
etcd join

### ISSUE THREAD

**Issue by jinyuttt** [ThreeMammals/Ocelot#867]
## Expected Behavior / New Feature

Can you join the integration of etcd? At present, the Eureka license has been modified, Consul seems to me a little biased, etcd may be suitable for most projects, I hope the author can consider my proposal

## Steps to Reproduce the Problem

  1.
  1.
  1.

## Specifications

  - Version:
  - Platform:
  - Subsystem:

**Comment by catcherwong** [comment]
Here is a provider that provides Etcd integration with Ocelot.

https://github.com/BuiltCloud/Ocelot.Provider.Etcd

**Comment by jinyuttt** [comment]
OK, but etcd does not have a standard service registration discovery, so to use it is to register services in its way? Or is etcd already recognized as a service registry discovery

**Comment by jinyuttt** [comment]
The etcd I see is a bound IP and port. If etcd is a cluster deployment, will it be processed automatically? Or does Ocelot handle it? Will Ocelot use cluster query services?

**Comment by raman-m** [comment]
@jinyuttt If you need this feature, **please contribute!**
