### ISSUE TITLE
Reload merged configuration files

### ISSUE THREAD

**Issue by cybertino** [ThreeMammals/Ocelot#872]
Is there any plan to add automatic reload when configuration was combined from multiple files?
https://github.com/ThreeMammals/Ocelot/blob/develop/src/Ocelot/DependencyInjection/ConfigurationBuilderExtensions.cs#L80

**Comment by iaiken** [comment]
Same issue.

We need support for something like this:

`config.AddOcelot("/foo/bar", hostingContext.HostingEnvironment, reloadOnChange: true)`

Ideally we should be able to drop ocelot config files for different APIs into the folder during deployment and the gateway should pick them up.

**Comment by raman-m** [comment]
@cybertino 
Dosn't [Merging configuration files] feature cover your needs?

Will new #1569 extension help you in your user case? This feature says: load config from anywhere, construct config `FileConfiguration` object and call `AddOcelot`. Is this extension useful for you?

**Comment by cybertino** [comment]
This was opened more than 4 years ago. A lot changed since then and I don't use Ocelot anymore so I don't even remember what that was about 😅. 
@raman-m Feel free to close this issue if it does not make sense these days.

**Comment by raman-m** [comment]
@cybertino Next time, ask your questions in [Discussions](../discussions) please!
