### ISSUE TITLE
How to set up ocelot with azure active directory

### ISSUE THREAD

**Issue by msadikkose** [ThreeMammals/Ocelot#879]
Using ocelot with azure active directory authorisation is possible or not! 

I followed [this](https://github.com/Azure-Samples/active-directory-dotnet-native-aspnetcore-v2/tree/master/1.%20Desktop%20app%20calls%20Web%20API) tutorial and managed to use api with Azure Active Directory authentication & authorization.

However I would like to consume the api from behind the Ocelot Api Gateway. I could use ocelot with custom basic authorization but could not accomplish to use with Azure Active Directory.

I have added Ocelot api gateway url to my api redirect url list already.

How should I set ReRoutes values in config.json and Ocelot Api Gateway project StartUp.cs ?
Is it possible or not? 

Kind regards.

## Specifications

  - Version: 13.5.0

**Comment by msadikkose** [comment]
I did it. I put the solution link if anyone needs it. 
You can find it from [here](https://stackoverflow.com/questions/56004750/how-set-up-ocelot-api-gateway-with-azure-active-directory?answertab=active#tab-top).

Thanks a lot.

**Comment by NicolasREY69330** [comment]
Hi @msadikkose : I'm sorry but I'm not able to build the solution following your link.

I get the following error on launch : 

_System.AggregateException: 'One or more errors occurred. (Unable to start Ocelot, errors are: Authentication Options AuthenticationProviderKey:AzureADJwtBearer,AllowedScopes:[] is unsupported authentication provider)'_

Do you have a full tutorial which I could follow to use Ocelot with an Azure AD ?
