### ISSUE TITLE
How to pass json data in POST request

### ISSUE THREAD

**Issue by atadhani** [ThreeMammals/Ocelot#894]
## Steps to Reproduce the Problem
i would like to pass JASON data in body not as parameter in url. How can I do it?
{
     'UserId': '1',
     'Name': 'John Doe',
     'BirthDate': '02-15-2001'
}
I know there is dynamic routing but it accepts parameter with url.  I would like to pass it in a body to forward the same way in downstream as well. 
## Specifications

  - Version:
  - Platform:
  - Subsystem:

**Comment by atadhani** [comment]
I was passing with single quote. It was the issue. It is fixed now

**Comment by briansantura** [comment]
@atadhani Cool!
