### ISSUE TITLE
Website (http://threemammals.com/ocelot) down - 403

### ISSUE THREAD

**Issue by Abhith** [ThreeMammals/Ocelot#904]
## Actual Behavior / Motivation for New Feature
Error 403 - This web app is stopped.

**Comment by TomPallister** [comment]
I ran out of money in Azure, it will come back up in a few days

**Comment by Abhith** [comment]
Website is up now. 

If it is a static website, there are free hosting providers like [netlify](https://www.netlify.com/) that we can make use of.

**Comment by WeihanLi** [comment]
@Abhith  Good suggestion 👍 
Maybe the website could rewrite with angular(or react/vue etc...) and hosted by github pages @TomPallister
