### ISSUE TITLE
How to integrate 'Azure Active Directory' Authentication ?

### ISSUE THREAD

**Issue by NicolasREY69330** [ThreeMammals/Ocelot#911]
Hi,

Could someone tell me how to authenticate through Azure Ad (ie application registered in Azure AD) which will authenticate against  https://login.microsoftonline.com/ providing a client_id, client_secret and resource then giving a Bearer to each request header made to Ocelot gateway ?

I know how to do it in a classical way, not behind Ocelot gw...

Thanks for your help

**Comment by NicolasREY69330** [comment]
My mistake I followed the tutorial of @msadikkose

Here is his solution : 
https://github.com/ThreeMammals/Ocelot/issues/879
https://stackoverflow.com/questions/56004750/how-set-up-ocelot-api-gateway-with-azure-active-directory?answertab=active#tab-top

I've just missed the part relative to Microsoft.Identity.Web that is mandatory to use AddProtectWebApiWithMicrosoftIdentityPlatformV2 method.
The library is not under nuget yet, so we have to download the current project to reference it https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/tree/master/Microsoft.Identity.Web

**Comment by mylesjj** [comment]
Any idea when it will be under Nuget?  Your lkast post was over 6 months ago
