### ISSUE TITLE
request body size

### ISSUE THREAD

**Issue by RedzRedz** [ThreeMammals/Ocelot#914]
Is the ocelet has the limitation of request body size?
I have api to upload file, the file size less than 20MB, the ocelet is ok.when the file size bigger, the ocelet will reponse 404.

**Comment by ks1990cn** [comment]
Hi @RedzRedz 
~30 MB, Depends on what server you are hosting and you can customize this value.

We are fixing 404 to 413 which is correct error for large payload.

https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.server.kestrel.core.kestrelserverlimits.maxrequestbodysize?view=aspnetcore-7.0

**Comment by ks1990cn** [comment]
I raised that PR but @ggnaegi have right way to do so he discussed that he will be working on it.

So i deleted my PR.

**Comment by raman-m** [comment]
@ggnaegi  Tanmay said that you're working on this. Which PR?

**Comment by ggnaegi** [comment]
@raman-m Yes, I'm finishing it and I will push it. Maybe we should add some documentation here, as @ks1990cn pointed out, it's a server related issue:
https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.server.kestrel.core.kestrelserverlimits.maxrequestbodysize?view=aspnetcore-7.0
https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.builder.iisserveroptions.maxrequestbodysize?view=aspnetcore-7.0
From our side, we are hidding the 413 status code with the ocelot error handling.

**Comment by raman-m** [comment]
@ggnaegi we have to add docs to explain developer how to config and how to use Ocelot pipeline to avoid such ugly bugs in future.
Regarding hiding 413 status. We can provide a small bug fix with good initial approach to understand the whole picture on error handling in Ocelot. In my opinion, error handling should be redesigned. But Ocelot could provide extra status in additional header, not overriding original status code.

**Comment by ggnaegi** [comment]
@raman-m we should think about a custom Exception class and only one middleware handling the exceptions and returning a response in rfc 7807 format.

**Comment by raman-m** [comment]
A long discussion! And there is no PR...
The author created this Question-issue [on Jun 5, 2019](#issue-452405805) more that 4 years ago. And the author doesn't care about this issue anymore...
His profile is [empty](https://github.com/RedzRedz?tab=repositories)! Only a couple of forked repos...
He is ghost GitHub user. And he is not open source contributor... :thinking: 

What are we discussing here?
Seems we need to convert this issue to discussion... or close it finally.

**Comment by raman-m** [comment]
@RedzRedz 

- [KestrelServerLimits.MaxRequestBodySize](https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.server.kestrel.core.kestrelserverlimits.maxrequestbodysize) original issue by Kestrel server

But file downloading & uploading is fixed by #1724 and #1824

**Comment by alexandis** [comment]
> But file downloading & uploading is fixed by https://github.com/ThreeMammals/Ocelot/pull/1724 and https://github.com/ThreeMammals/Ocelot/pull/1824 in Ocelot

I've tried to find any information "how" is that fixed? Where should I read, what should I change in the configuration? :) Please clarify.

**Comment by raman-m** [comment]
@ggnaegi 
Someone with the user name @alexandis is [TypeScript developer](https://github.com/alexandis?tab=repositories)!!! ☝️ 
Talking to an user who has probably zero knowledges in C#, .NET, and ASP.NET has no much sense.
An I right Mr. @alexandis, and you can show us good PRs in C#, right?
