### ISSUE TITLE
Default host downstream

### ISSUE THREAD

**Issue by MoBe3** [ThreeMammals/Ocelot#918]
## My problem
Hello !

I'd like to be able to reroute everything without having to specify explicitly the host downstream.
Something like : http//:0.0.0.0:PORT. I've tried and didn't work. Using localhost works just fine, but, if the service is hosted somewhere else, I'd have to use an IP address (in the ocelot.json) and that's exactly what i'd like to avoid. I want to allow the DowstreamHost to be "anything".
So I pushed my research over the issue a little bit, and apparently service discovery might be the key (ex : Consul, Eureka). I've tried both of them, couldn't get the job done.

## So far
Using ocelot alone :
(ocelot.json / ReRoute section)

    {
    "DownstreamPathTemplate": "/api/v1/{everything}",
    "DownstreamScheme": "http",
    "DownstreamHostAndPorts": [
        {
        "Host": "0.0.0.0", // localhost works fine though
        "Port": 5501
        }
      ],
      
      "UpstreamPathTemplate": "/api/v1/{everything}",
      "UpstreamHttpMethod": [ "Get", "Put", "Post", "Delete", "Patch", "Options" ]
    }
Using Ocelot + Consul/Eureka :
&nbsp;&nbsp;&nbsp;Followed the steps in : [https://ocelot.readthedocs.io/en/latest/features/servicediscovery.html](https://ocelot.readthedocs.io/en/latest/features/servicediscovery.html)
Via Consul/Eureka, couldn't even do it with localhost, so ... there is a slight chance that I might have missed something.

Via Consul

    {
    "ReRoutes": [
    {
      "DownstreamPathTemplate": "/api/v1/{everything}",
      "DownstreamScheme": "http",
      "ServiceName": "smart",

      "UpstreamPathTemplate": "/api/v1/{everything}",
      "UpstreamHttpMethod": [ "Get", "Put", "Post", "Delete", "Patch", "Options" ]
    }
    ],
    "GlobalConfiguration": {
    "ServiceDiscoveryProvider": {
      "Host": "0.0.0.0",
      "Port": 5501,
      "Type": "Consul"
      }
     }
    }
    
Via Eureka 

    "GlobalConfiguration": {
    "ServiceDiscoveryProvider": {
      "Type": "Eureka"
    }
appsettings.json

    "spring": {
      "application": {
        "name": "someService"
      },
      "eureka": {
        "client": {
          "serviceUrl": "http://0.0.0.0:5501/eureka/",
          "shouldRegisterWithEureka": false,
          "shouldFetchRegistry": true
        }
      }	

## Specifications
I also get an exception when using Eureka : discovery client type UNKNOWN, after the statement _AddEureka()_
I used the latest version of Ocelot, the same goes for the service discovery 13.5.2

If you have any idea that might help solve the problem, i'd really appreciate it.
Thank you !

**Comment by yuft** [comment]
Here should be a perfect example for you. https://github.com/Liu-Alan/Ocelot-Consul

**Comment by MoBe3** [comment]
Thanks ! Still there's quite a lot stuff going on my head after taking a look at the example.
1) Do i need to have a whole Consul project too ? I thought the idea of using ocelot.provider.consul package is to avoid it. Because I skipped that whole part. I just went directly adding consul via ocelot in the ConfigureServices() and "overriding" the reroute in the "Global Configuration" of my json file (ocelot). 
2) I still don't understand how you manage to access a service which is not hosted on your machine/localhost, I guess that's the part where Consul does its job, but still, something is missing, i couldn't totally get it.
3) What is the point of keeping the DowntreamHostandPorts in the reroute section if the main idea is to "define them" in a general way in the Global Configuration through Consul ? Unless it produces the same final result and in this case, you could just comment those lines out, right ?

I know it's too much questions/confusions, I'm just trying to understand the mechanism too. 
Thank you again.

**Comment by yuft** [comment]
I am not sure why you require 'default host', but I guess you could take a look at https://github.com/damianh/ProxyKit which is a reverse proxy implemented with .Net core. It may fit you easily with 'default host'.

For ocelot, I suggest you to read more about big picture. https://ocelot.readthedocs.io/en/latest/introduction/bigpicture.html

**Comment by MoBe3** [comment]
Well, the services to retrieve might not be in my machine. So it would be nice to forward them to the right location without having to specify every single host responsible for a service, which means that i'd have to  specify manually all the routes leading to the services. If it were for just one or two, that'd be ok, but there are just too many, it wouldn't be convenient. Or ... maybe I'm just confused and I need to think it through again.

Yeah, i'll definitely take a look at the reverse proxy you suggested and see what it's about (ocelot big picture as well).

Thanks for your time, i'll get back to you if there are any updates, bad or good ;)

**Comment by MoBe3** [comment]
@yuft Oh my !
I was right and wrong ... but mostly wrong.
What I was trying to do was kind of impossible and thanks to you I could see it. There was no way I could have been forwarded to some url without knowing the IP address. Because either way, the services I'm trying to have access to will always be accessible from anywhere I'd like to (I hope so).
So I took the problem in the reverse way : better get the ip address of the computer and do whatever it has to be done.
Then I thought of : is there a way to configure the downstream host programatically ? And if it's the case, that would totally solve my problem.
Sooo, imma get back to it and start doing my researches again and see if i can find a way to configure that downstream host in my c# program (and not the json file).

Thank you again !

**Comment by raman-m** [comment]
:rofl:
