### ISSUE TITLE
Why not use the Consul PollConsul timing interval acquisition and only health passing = true service entry?

### ISSUE THREAD

**Issue by rocleegithub** [ThreeMammals/Ocelot#921]
> > Question: If the registered Consul node is unexpectedly down and not restarted immediately, other services should continue to find the registered service

@philiahe Why not use the Consul PollConsul timing interval acquisition and only  health passing = true service entry?

## PollConsul you need to set the following configuration:
` 
 "GlobalConfiguration": {  
    "ServiceDiscoveryProvider": {  
      "Host": "localhost",  
      "Port": 8500,  
      "Type": "PollConsul",  
      "PollingInterval": 100  
    }  
  }  
`
The polling interval is in milliseconds and tells Ocelot how often to call Consul for changes in service configuration. 
Then you can only get health passing = true  service entry. 

_Originally posted by @rocleegithub in https://github.com/ThreeMammals/Ocelot/pull/810#issuecomment-501183661_

**Comment by yuft** [comment]
I have concerns on #810 as well.
> Original question: If the registered Consul node is unexpectedly down and not restarted immediately, other services should continue to find the registered service

My answer will be:
If the registered Consul node is unexpectedly down and not restarted immediately, that means 'other services' on the same box or in the same pod are unhealthy as well, they should be restarted(re-created) with Consul client.

#810 is a breaking change, what's the point that client sending request to a known unhealthy downstream endpoint? it breaks fundamental service discovery feature. I am having a workaround at the moment.

#810 should be reverted.
