### ISSUE TITLE
Would Ocelot work with SOAP Web Services?

### ISSUE THREAD

**Issue by IvanFarkas** [ThreeMammals/Ocelot#922]
## Would Ocelot work with SOAP Web Services?

I am wondering if addition to REST API, would Ocelot work with SOAP Web Services as well?

**Comment by yuft** [comment]
In my experience, Ocelot can blindly forward SOAP request to downstream. If you need to manipulate payload such as SOAP header/body, you can have custom middleware. 

However, Ocelot is a modern microservice gateway, we would not expect it to support it.

**Comment by raman-m** [comment]
@IvanFarkas Hi Ivan!
What kind of deep SOAP protocol support you need in Ocelot and why?
Cannot you route XML body through Ocelot app instance now? Really?

Just configure your SOAP downstream app to bind to a port in your environment, open access by public/private IP or DNS host name.
Write correct [Configuration](), I mean **DownstreamHostAndPorts** options
Use `http` or `https` schemes only
And give a try to route XML data...

But, probably SOAP operates very specific headers you have to care about. If Yes, just develop custom [Delegating Handler](https://ocelot.readthedocs.io/en/latest/features/delegatinghandlers.html) module to support all SOAP headers and do other stuff.

We have closed discussion #1760 
- #1760 

If you would like to continue the discussion, I can reopen it for you?!
