### ISSUE TITLE
The status code in the response is incorrect

### ISSUE THREAD

**Issue by karinehovhannisyan** [ThreeMammals/Ocelot#926]
## Expected Behavior / New Feature
I'd love to see the Unauthorized error status code set in the Response headers instead of modifying the Request Header status Code.
## Actual Behavior / Motivation for New Feature
In case of a 401 Error, the system is modifying the Request header statusCode, even if I add an error to `context.Errors`.

## Specifications

  - Version: 13.5.0
  - Platform: Windows 10, .NET Core 2.2

**Comment by raman-m** [comment]
We know about this problem of original status code overriding by [Error Mapper](https://github.com/search?q=repo%3AThreeMammals%2FOcelot%20ErrorMapper&type=code)... :disappointed: 
In docs we have this page: [Error Status Codes](https://ocelot.readthedocs.io/en/latest/features/errorcodes.html)

This is very ugly and redundant feature which behaves strange, and it breaks a lot of downstream services.
We have to recover original status code and keep it in HTTP response.
But custom Ocelot status can be moved to a new header.

**Comment by raman-m** [comment]
### Related to
- #1621 
- #1511
- #1006

**Comment by raman-m** [comment]
### Too old!
### You have the right to reopen this issue in the future if you come with a PR ready
