### ISSUE TITLE
invalid config key log_file

### ISSUE THREAD

**Issue by jonny-xhl** [ThreeMammals/Ocelot#927]
## I use configuration files to start agent and not invalid log_file key. 
![log_file](https://user-images.githubusercontent.com/29520329/59490118-72a32f80-8eb6-11e9-9fe8-af61f45d93f3.png)
## docs
![log_file_filed](https://user-images.githubusercontent.com/29520329/59490360-0e34a000-8eb7-11e9-9834-a3f8f1074a9f.png)

**Comment by raman-m** [comment]
Not actual issue of Ocelot
