### ISSUE TITLE
Service Discovery failed use Consul for  V-13.5.2  

### ISSUE THREAD

**Issue by DevinChen1** [ThreeMammals/Ocelot#933]
## Steps to Reproduce the Problem

  1.
  1.
  1.

## Specifications

  - Version:
  - Platform:
  - Subsystem:

**Comment by WuAiDeng** [comment]
why?

**Comment by DevinChen1** [comment]
> why?

Service discovery is not available in version 13.5.2 and Consul

**Comment by WuAiDeng** [comment]
no,I can

**Comment by DevinChen1** [comment]
> no,I can
你亲试可以吗？ocelot V13.5.2

**Comment by WuAiDeng** [comment]
可以，只不过有段代码不知道为什么作者要那么些，就是作者用了consul的node节点名称作为host访问。我准备改掉这个代码，直接用address。

代码如下：new ServiceHostAndPort(serviceNode == null ? serviceEntry.Service.Address : serviceNode.Name, serviceEntry.Service.Port),

**Comment by WuAiDeng** [comment]
或者把报错信息贴出来？

**Comment by DevinChen1** [comment]
> 或者把报错信息贴出来？
部署调用时发生错误

**Comment by WuAiDeng** [comment]
你的consul node name设置的是什么？发出来看看

**Comment by WuAiDeng** [comment]
一点错误信息都没有？日志？

**Comment by DevinChen1** [comment]
加qq聊吧




------------------ 原始邮件 ------------------
发件人: "Wilson"<notifications@github.com>;
发送时间: 2019年6月19日(星期三) 下午2:24
收件人: "ThreeMammals/Ocelot"<Ocelot@noreply.github.com>;
抄送: "Code--可乐"<1750453097@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [ThreeMammals/Ocelot] Service Discovery failed use Consul for V-13.5.2   (#933)




一点错误信息都没有？日志？

**Comment by WuAiDeng** [comment]
你的QQ？

**Comment by DevinChen1** [comment]
1750453097



------------------ 原始邮件 ------------------
发件人: "Wilson"<notifications@github.com>;
发送时间: 2019年6月19日(星期三) 下午2:28
收件人: "ThreeMammals/Ocelot"<Ocelot@noreply.github.com>;
抄送: "Code--可乐"<1750453097@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [ThreeMammals/Ocelot] Service Discovery failed use Consul for V-13.5.2   (#933)




你的QQ？

**Comment by winlj** [comment]
兄弟们,解决了的话,这里回复一下奥,谢谢了,急等

**Comment by raman-m** [comment]
Boys from China are kidding here. :rofl: 

@DevinChen1 
I recommend you to upgrade to the latest version always! Current version is **22.0.1**
