### ISSUE TITLE
use ocelot in docker can't route to raw service

### ISSUE THREAD

**Issue by fuxuejun** [ThreeMammals/Ocelot#934]
## Expected Behavior / New Feature

change Ocelot.Provider.Consul.Consul Line 60:

//                new ServiceHostAndPort(serviceNode == null ? serviceEntry.Service.Address : serviceNode.Name, serviceEntry.Service.Port),
                
new ServiceHostAndPort(serviceEntry.Service.Address, serviceEntry.Service.Port),

Ocelot.DownstreamUrlCreator.Middleware.DownstreamUrlCreatorMiddleware:Debug: requestId: 0HLNKD0PKJCRA:00000002, previousRequestId: no previous request id, message: Downstream url is http://192.168.1.50:5002/common/v1/swagger.json

## Actual Behavior / Motivation for New Feature

Ocelot.DownstreamUrlCreator.Middleware.DownstreamUrlCreatorMiddleware:Debug: requestId: 0HLNKD0PKJCRA:00000002, previousRequestId: no previous request id, message: Downstream url is http://devserver:5002/common/v1/swagger.json

No Such Device or Address  Error.

## Steps to Reproduce the Problem

  1.
  1.
  1.

## Specifications

  - Version:
  - Platform:
  - Subsystem:

**Comment by WuAiDeng** [comment]
I also have this problem. But, why is it designed like this?

**Comment by Leandropintogit** [comment]
#909

**Comment by raman-m** [comment]
Fixed by #909 

Current code:
https://github.com/ThreeMammals/Ocelot/blob/f4803c24bf9e9ca3929c78ca8eb23401e3c31c23/src/Ocelot.Provider.Consul/Consul.cs#L59-L61
