### ISSUE TITLE
return 503 Service Unavailable instead on 500 Internal Server Error

### ISSUE THREAD

**Issue by TorMartin74** [ThreeMammals/Ocelot#935]
## Expected Behavior / New Feature
It would be nice if Ocelot returned 503 when Ocelot cannot connect to the downstream service, e.g. when a connection is refused.

When running in docker or other container environments, a service can be stopped temporarily due to updates or other things. In such cases 500 might be misleading.

**Comment by raman-m** [comment]
Our current errors logic: [Server error responses](https://ocelot.readthedocs.io/en/latest/features/errorcodes.html#server-error-responses)
But we have some plans to forward original status code. So, overriding status code now is very bad.
See #926 
See all knowledge domain: ["status code"](https://github.com/search?q=repo%3AThreeMammals%2FOcelot+%22status+code%22&type=issues)

But you can solve the 500 problem by [Delegating Handlers](https://ocelot.readthedocs.io/en/latest/features/delegatinghandlers.html).
Override status code for your needs in custom delegating handler.
