### ISSUE TITLE
provide offical support for zookeeper version service discovery.

### ISSUE THREAD

**Issue by wangfengjun404** [ThreeMammals/Ocelot#951]
provide offical support for zookeeper version service discovery.
thanks

**Comment by raman-m** [comment]
Hi @wangfengjun404 !
Sorry, which one?
Could you share a link to this product?

**Will you personally contribute to deliver this feature?**

**Comment by raman-m** [comment]
@ggnaegi  FYI

**Comment by raman-m** [comment]
Closing for now... because I don't think the community has any interest in these types of providers.

**Comment by ggnaegi** [comment]
@raman-m I agree priority 213124903057234587485735789
