### ISSUE TITLE
Query string parameters are not correctly removed from downstream template

### ISSUE THREAD

**Issue by webley** [ThreeMammals/Ocelot#952]
## Expected Behavior
I want to be able to map a query parameter on my gateway API to a query parameter with a different name on my downstream API.

```json
{
  "Routes": [
    {
      "DownstreamPathTemplate": "/persons?personId={userId}",
      "UpstreamPathTemplate": "/users?userId={userId}"
    } 
  ]
}
```
When calling `/users?userId=webley`, I would expect the downstream call to be `/persons?personId=webley`

## Actual Behavior
The downstream route generated is `/persons?userId=webley&personId=webley`

## Steps to Reproduce the Problem
  1. Create a re-route with query strings in both the upstream and downstream templates
  1. Call into the upstream endpoint
  1. The unwanted query parameter will remain on the downstream request

In **DownstreamUrlCreatorMiddleware.cs**, the method `RemoveQueryStringParametersThatHaveBeenUsedInTemplate(context)` seems to be called if the downstream path does not contain a query string. I have tested that this works as expected.  However, if the downstream path contains a query string, unused params from the upstream template are never removed. I think they probably should be.

## Specifications
  - Version: 13.8.0-alpha0006 (and 13.5.2)
  - Platform: Win 10

**Comment by wast** [comment]
When this gets fixed, it will be Major change because it could break apps that used this as a feature.

**Comment by raman-m** [comment]
> @wast commented [on Jan 3, 2020](#issuecomment-570561506)
When this gets fixed, it will be Major change because it could break apps that used this as a feature.

Oh, really? The feature (fix) will forward new query parameter and remove old one.
Developer must double check upstream & downstream path as an author of a route.
We can say about that in Release Notes. Sounds good?
