### ISSUE TITLE
UpstreamHeaderTransform 

### ISSUE THREAD

**Issue by WuyanLee** [ThreeMammals/Ocelot#953]
"UpstreamHeaderTransform": {
    "Host": "www.bbc.co.uk"
}

这样做不行，请问该怎么做
That's not good. What should I do?

**Comment by WuyanLee** [comment]
我发现 “Mapper.IRequestMapper” 去掉了了“Host”，但是我不明白为什么要移除
I found that "Mapper. IRequestMapper" removed "Host", but I don't understand why it should be removed.

**Comment by myesn** [comment]
你好，请问现在有解决方案吗？

**Comment by WuyanLee** [comment]
> 你好，请问现在有解决方案吗？

可以重写Mapper. IRequestMapper这个接口的类，并去掉Host实现

**Comment by myesn** [comment]
好的，谢谢你
