### ISSUE TITLE
Case sensitive AddQueriesToRequest parameters (500 error)

### ISSUE THREAD

**Issue by gfx687** [ThreeMammals/Ocelot#956]
## Premise
I configured an app to add query parameter `PID` from claims (using `AddQueriesToRequest`, and it works just fine)

## Expected Behavior / New Feature
I expected Ocelot to ignore query parameters that already configured in `AddQueriesToRequest` section without any errors no matter what case is used

## Actual Behavior / Motivation for New Feature
I tried to send a request to Ocelot with EXPLICIT `PID` query parameter and it works, but then I changed the case of EXPLICIT `PID` query parameter to `pid` (in lower case) I got 500 error.

I think it is not obvious behavior, I didn't even think at first it was because of Ocelot and not because of my app

## Steps to Reproduce the Problem

  1. Configure ocelot to add a query parameter to downstream service using AddQueriesToRequest
  2. Send a request to Ocelot explicitly specifying the same parameter but in a different case (for example, if it configured as Upper case, use Lower case)
  3. Receive 500 error from Ocelot

## Specifications

  - Version: 13.4.1

**Comment by raman-m** [comment]
Please, confirm this bug in the latest version [22.0.1](https://github.com/ThreeMammals/Ocelot/releases) and reopen.

Attach more: config JSON, startup code, exception & error logs!
