### ISSUE TITLE
Consul service discovery error 500

### ISSUE THREAD

**Issue by Leandropintogit** [ThreeMammals/Ocelot#957]
The issue #909 added a option to resolve hostname of consul node using its name, but the name of consul node is a arbitrary string and not always a valid hostname. 

I created a new node on consul called services and registred my services in this node. when ocelot query for services, it binds service to services:9091 for example and off course, this fail.

## Specifications

  - Version: 13.5.2
  - Platform: Linux 
  - Subsystem: Docker

**Comment by raman-m** [comment]
Duplicate of #954

**Comment by raman-m** [comment]
@Leandropintogit
It will be fixed with #954
