### ISSUE TITLE
Specify Scheme of ServiceProviderConfiguration

### ISSUE THREAD

**Issue by DavidLievrouw** [ThreeMammals/Ocelot#959]
## New Feature
Add ability to specify Scheme of ServiceProviderConfiguration, for use in the ConsulClientFactory.

## Actual Behavior / Motivation for New Feature
In the ConsulClientFactory class, the scheme of the Consul server address is hard-coded to "http". In our environment, Consul is not hosted over http, only over https. Currently, we are working around this issue by overriding the service composition:
```
services.AddOcelot().AddConsul();
services
  .RemoveAll<IConsulClientFactory>()
  .AddSingleton<IConsulClientFactory, SchemeSupportingConsulClientFactory>();
```
Inspired by [Steeltoe](https://github.com/SteeltoeOSS/steeltoe/blob/c623ad18ac23651ee6178fd3a2dc113af4bc0f9f/src/Discovery/src/ConsulBase/ConsulClientFactory.cs)

## Steps to Reproduce the Problem

  1. Disable Consul http endpoint, only keep https.
  1. Run your Ocelot host, with Consul service discovery enabled.
  1. When submitting a request, you get an error, stating that a http request is being sent to a https endpoint.

## Specifications

  - Version: 13.5.2
  - Platform: Windows-x64
  - Target framework: netcoreapp2.2

**Comment by TomPallister** [comment]
fixed by #1154
