### ISSUE TITLE
Add ability to register custom load balancers

### ISSUE THREAD

**Issue by DavidLievrouw** [ThreeMammals/Ocelot#961]
## New Feature
Add ability to register custom load balancers.

## Motivation for New Feature
We are using the Consul provider. We would like to add a custom load balancer that decides which service to route to, based on our custom metrics that are known in Consul.

E.g. we would like to give preference to services that have no "critical" or "warn" health checks. Or give preference to service instances that have a certain tag. Stuff like that...

This functionality is currently not possible with the built-in load balancers (CookieStickySessions, NoLoadBalancer, RoundRobin or LeastConnection). So I would like to be able to add load balancers, and specify them during DI composition.

This would require reworking the LoadBalancerFactory class, because only the built-in load balancers can be created there (switch statement).

(Possibly related to #870?)

## Specifications

  - Version: 13.5.2
  - Platform: Windows-x64
  - Target framework: netcoreapp2.2

**Comment by TomPallister** [comment]
fixed by #1155

**Comment by raman-m** [comment]
Fixed by https://github.com/ThreeMammals/Ocelot/pull/1155
