### ISSUE TITLE
DelegatingHandler

### ISSUE THREAD

**Issue by TarasKovalyk** [ThreeMammals/Ocelot#963]
Hello, 
We are using ocelot framework to handle routes to some services. And we want to implement the following behavior:
- from front end’s part we send request with some payload 
- on the router side we need to add an additional parameter to json and redirect request to other service.
As I understand we can use DelegatingHandler for that, it is necessary to define DelegatingHandler: [“SomeHandler”] within our route configuration file. And then register this handler within Startup. And then we can extend(mutate) request within SomeHandler. Is it correct? Or there are other possible solutions to achieve this.

**Comment by raman-m** [comment]
Hi Taras!

>  Is it correct? 

Yes, It is!
Use [Delegating Handlers](https://ocelot.readthedocs.io/en/latest/features/delegatinghandlers.html)

----
> Or there are other possible solutions to achieve this.

In theory you could develop custom middleware and attach to the Ocelot pipeline. But delegating handler is better approach.

Good luck!
