### ISSUE TITLE
Ocelot Configuration

### ISSUE THREAD

**Issue by romina2001** [ThreeMammals/Ocelot#965]
Hello,

I am trying to access another service fabric service from the gateway service, but I get the following error. This is happening in cloud, on a 5 node Service Fabric cluster. Locally all things run OK. Why do I get this error and what I have missconfigured?
Many thanks

19 10:53:23|WARN|requestId: 0HLOC3FF3H082:00000001, previousRequestId: no previous request id, message: DownstreamRouteFinderMiddleware setting pipeline errors. IDownstreamRouteFinder returned Error Code: UnableToFindDownstreamRouteError Message: Failed to match ReRoute configuration for upstream path: /, verb: GET. 
2019-07-19 10:53:23|WARN|requestId: 0HLOC3FF3H082:00000001, previousRequestId: no previous request id, message: Failed to match ReRoute configuration for upstream path: /, verb: GET. 
2019-07-19 10:53:23|WARN|requestId: 0HLOC3FF3H082:00000001, previousRequestId: no previous request id, message: Error Code: UnableToFindDownstreamRouteError Message: Failed to match ReRoute configuration for upstream path: /, verb: GET. errors found in ResponderMiddleware. Setting error response for request path:/, request method: GET 
2019-07-

My appsettings file

`{
  "GlobalConfiguration": {
    "RequestIdKey": "OcRequestId",
    "ServiceDiscoveryProvider": {
      "Host": "localhost",
      "Port": 19081,
      "Type": "ServiceFabric"
    }
  },
  "ReRoutes": [
    {
      "DownstreamPathTemplate": "/",
      "DownstreamScheme": "https",
      "ServiceName": "service1",
      "UpstreamHttpMethod": [
        "Get"
      ],
      "UpstreamPathTemplate": "/{url}"
    },
    {
      "DownstreamPathTemplate": "/relay/{url}",
      "DownstreamScheme": "https",
      "ServiceName": "service2",
      "UpstreamHttpMethod": [
        "Get"
      ],
      "UpstreamPathTemplate": "/relay/{url}"
    }
  ]
}`

**Comment by raman-m** [comment]
```json
   {
      "DownstreamPathTemplate": "/",
      "DownstreamScheme": "https",
      "ServiceName": "service1",
      "UpstreamHttpMethod": [
        "Get"
      ],
      "UpstreamPathTemplate": "/{url}"
    },
```

This route is invalid! You must define `{url}` placeholder in both templates!
```json
   {
      "DownstreamPathTemplate": "/{url}",
      "UpstreamPathTemplate": "/{url}"
    },
```
👆
