### ISSUE TITLE
Can't access Ocelot administration API with MVC earlier in the pipeline

### ISSUE THREAD

**Issue by ChrisSwinchatt** [ThreeMammals/Ocelot#969]
## Expected Behavior

GET /administration/{x} would reach the Ocelot administration API

## Actual Behavior

The response is 404 for all values of {x}

## Steps to Reproduce the Problem

  1. Create an MVC project
  2. Add MVC to the pipeline before Ocelot
  3. Try to access any Ocelot administration endpoint

## Specifications

  - Version: 13.5.2
  - Platform: .Net Core 2.2 on Windows 10
  - Subsystem: Ocelot.Administration

## Notes

* Adding Ocelot to the pipeline before MVC solves the issue, but means that health-checks do not work.

**Comment by ChrisSwinchatt** [comment]
Related: #915

**Comment by raman-m** [comment]
@ChrisSwinchatt 

> ## Notes
> - Adding Ocelot to the pipeline before MVC solves the issue, but means that health-checks do not work. 

Why do you need MVC pipeline in Ocelot?
Why do think it is a problem of Ocelot and you're posting it as a problem?
Why did you provide experiments & researches and then posting it as an issue?

You should understand that Ocelot is Minimal Web API ASP.NET app!!!
Ocelot need not MVC pipeline! Ocelot need not Razor/Blazor UI and any models domain and controllers at all!
Do you understand the idea of minimal API apps?

**Comment by raman-m** [comment]
> @ChrisSwinchatt commented [on Jul 24, 2019](https://github.com/ThreeMammals/Ocelot/issues/969#issuecomment-514551829)
Related: https://github.com/ThreeMammals/Ocelot/issues/915

Is it another problem / scenario or seems the same Administration feature problem?

**Comment by raman-m** [comment]
### Outdated issue :exclamation: 
### You have the right to reopen this issue in the future if you come with a PR ready
