### ISSUE TITLE
Pass through Okta Token from Client App to Web API using Ocelot Gateway

### ISSUE THREAD

**Issue by atadhani** [ThreeMammals/Ocelot#976]
## Expected Behavior / New Feature
Pass through Okta Token from Client App to Web API using Ocelot Gateway

## Actual Behavior / Motivation for New Feature
Not sure how can I simply pass Okta Token coming in header 

## Steps to Reproduce the Problem

  1. Client App configured to call API using Okta Authentication
  1. Gateway - takes request from client and passes to secure WebAPI
  1. WebAPI is created using Okta authentication 

I have appiled suggestion from this thread https://github.com/ThreeMammals/Ocelot/issues/446  I am getting " ArgumentNullException: Your Okta URL is missing. You can copy your domain from the Okta Developer Console. Follow these instructions to find it: https://bit.ly/finding-okta-domain"  Though I am using Okta-domain. 

## Specifications

  - Version: 13.5.0 (I don't think version could be an issue)
  - Platform: Windows
  - Subsystem:

**Comment by atadhani** [comment]
Getting unauthenticated error crossroad-gateway_1  |       requestId: 0HLOMJVI4GG2T:00000001, previousRequestId: no previous request id, message: Error Code: UnauthenticatedError Message: Request for authenticated route /SystemAdminServices/api/v2/Network/UnfilteredNetworkLiteList by  was unauthenticated errors found in ResponderMiddleware. Setting error response for request path:/SystemAdminServices/api/v2/Network/UnfilteredNetworkLiteList, request method: GET

**Comment by raman-m** [comment]
> Pass through Okta Token from Client App to Web API using Ocelot Gateway
> Not sure how can I simply pass Okta Token coming in header

Ocelot can forward any HTTP data including token value as:
- URL query parameter value
- **HTTP request header**
- HTTP body data

I don't see any issue with Ocelot!
If you still have the same problem, please confirm the problem in [newest](https://github.com/ThreeMammals/Ocelot/releases) Ocelot version which is [22.0.1](https://github.com/ThreeMammals/Ocelot/releases/tag/22.0.1) now!
