### ISSUE TITLE
I have asp.net core based microservices project. In this project I am implementing API Gateway using Ocelot nuget package. This project is hosted in linux based docker container in my local development environment. On testing the microservice url via the api gateway I am getting error 400 not found.

### ISSUE THREAD

**Issue by saitejaprattipati** [ThreeMammals/Ocelot#978]
My configuration file:
{
"ReRoutes": [
{
"DownstreamPathTemplate": "/api/{everything}",
"DownstreamScheme": "http",
"DownstreamHostAndPorts": [
{
"Host": "authoradmin.command.api",
"Port": 80
}
],
"UpstreamPathTemplate": "/api/ad/{everything}",
"UpstreamHttpMethod": [ "POST", "PUT", "GET" ]
}
],
"GlobalConfiguration": {
"RequestIdKey": null,
"AdministrationPath": null
}
}

my Docker file is follows:

	authoradmin.command.api:
			image: ${DOCKER_REGISTRY-}authoradmincommandapi
			build:
  			context: .
  			dockerfile: CommandStack/AuthorAdmin.Command.API/Dockerfile
			depends_on:
  				- rabbitmq
			links: 
  				- rabbitmq
docker override is as follows:

		authoradmin.command.gateway:
			environment:
  				- ASPNETCORE_ENVIRONMENT=Development
  				- IdentityUrl=http://identity.api
			ports:
  				- "50106:80"
			volumes:
  				- ./CommandStack/AuthorAdmin.Command.API:/app/configuration

**Comment by saitejaprattipati** [comment]
My configuration file:
{
"ReRoutes": [
{
"DownstreamPathTemplate": "/api/{everything}",
"DownstreamScheme": "http",
"DownstreamHostAndPorts": [
{
"Host": "authoradmin.command.api",
"Port": 80
}
],
"UpstreamPathTemplate": "/api/ad/{everything}",
"UpstreamHttpMethod": [ "POST", "PUT", "GET" ]
}
],
"GlobalConfiguration": {
"RequestIdKey": null,
"AdministrationPath": null
}
}

my Docker file is follows:

	authoradmin.command.api:
			image: ${DOCKER_REGISTRY-}authoradmincommandapi
			build:
  			context: .
  			dockerfile: CommandStack/AuthorAdmin.Command.API/Dockerfile
			depends_on:
  				- rabbitmq
			links: 
  				- rabbitmq
docker override is as follows:

		authoradmin.command.gateway:
			environment:
  				- ASPNETCORE_ENVIRONMENT=Development
  				- IdentityUrl=http://identity.api
			ports:
  				- "50106:80"
			volumes:
  				- ./CommandStack/AuthorAdmin.Command.API:/app/configuration

**Comment by raman-m** [comment]
Please, create Docker Compose configuration and environment which creates default Docker network where services communicate to each other by host names.
Refer to Docker Compose command docs!
Good luck!
