### ISSUE TITLE
Consul Proxy Configuration

### ISSUE THREAD

**Issue by garethrpratt** [ThreeMammals/Ocelot#982]
## Expected Behavior / New Feature
It would be really nice if we could change proxy settings used by Ocelot to communicate with Consul.  The `ConsulClientFactory` class currently instantiates the `ConsulClient` class, but does not use the overload which allows us to modify the HttpHandler.

In our case, I've recreated the factory to simply disable the proxy.

## Actual Behavior / Motivation for New Feature
It's only possible to change proxy behaviour by interfering with the internals of Ocelot.

## Steps to Reproduce the Problem
  1. Set up an Ocelot service that uses Consul
  1. Fire up Fiddler
  1. Run the service
  1. Make a request
  1. Observe the calls to Consul in Fiddler.

## Specifications

  - Version: 13.0.0
  - Platform: Windows
  - Subsystem:

**Comment by jamieomaguire** [comment]
This seems like a wise idea!

**Comment by raman-m** [comment]
@ggnaegi Could you help the author, please?

**Comment by raman-m** [comment]
@garethrpratt
Will you contribute to deliver this feature?
Seems not!

**Comment by garethrpratt** [comment]
> @garethrpratt Will you contribute to deliver this feature? Seems not!

Hi thanks for taking the time to look at it. This was five years ago,  and I haven't used Ocelot since 2021, happy for this to be closed
