### ISSUE TITLE
Process request and Change Configuration 

### ISSUE THREAD

**Issue by haninm** [ThreeMammals/Ocelot#987]
Hello ThreeMammals ! 
i looking for one Middleware that provide Extra Action on each Request (Action Defined by Developer who use ocelot) .
For example change Downstream Host Address depend on Query params and some data stored on DataBase.

do u want to add some thing like this ?

**Comment by raman-m** [comment]
Your scenario sounds like a custom service discovery one.
Why not to use [Service Discovery](https://ocelot.readthedocs.io/en/latest/features/servicediscovery.html) vs Consul?
So you will control your downstream services by Consul.

> For example change Downstream Host Address depend on Query params and some data stored on DataBase.

If you need query string manipulations and storing data in a DB then seems you have to develop your own SD [Custom Provider](https://ocelot.readthedocs.io/en/latest/features/servicediscovery.html#custom-providers).

-----
> i looking for one Middleware that provide Extra Action on each Request (Action Defined by Developer who use ocelot) .

Why not to choose a middleware and inject it to pipeline? :point_down: 
- [Middleware Injection](https://ocelot.readthedocs.io/en/latest/features/middlewareinjection.html)

In most cases Delegating Handler also helps to have a control on request and response.
- [Delegating Handlers](https://ocelot.readthedocs.io/en/latest/features/delegatinghandlers.html)
- [HTTP Message Handlers in ASP.NET Web API](https://learn.microsoft.com/en-us/aspnet/web-api/overview/advanced/http-message-handlers)
