### ISSUE TITLE
I'm New to Ocelot And Most of the Documentation Seems Out of Date

### ISSUE THREAD

**Issue by RobKraft** [ThreeMammals/Ocelot#988]
I could really use an API Gateway and what I read about Ocelot is very promising, but I think a recent release of Ocelot has caused most of the documentation to be irrelevant.

1) Logging - I figured out how to turn on logging.AddConsole(), but don't see how I can now use NLog for logging.

2) Authentication.  I picked Ocelot because we use Identity Server, but the IdentityServer examples in the documentation no longer compile.  I can't figure out what package or using statement to add to use a method like AddIdentityServerAuthentication.
I'll admit I am a n00b to Microsoft Middleware.  So maybe that is why it is taking me many hours to figure out how to add a working line of code to Ocelot, but before I spendt a few more days trying to get that line to work I thought I'd see if there was newer documentation somewhere, or if perhaps direct support for IdentityServer had been deprecated.  My current authorization code does not compile but I haven't figured out why.  It is very basic in Program.cs:
			   .ConfigureServices(s =>
			   {
				   s.AddOcelot();
				   s.AddAuthentication("CS");
			   })
and in ocelot.json:
			"UpstreamHttpMethod": [ "Get", "Post", "Options" ],
			"AuthenticationOptions": {
				"AuthenticationProviderKey": "CS",
				"AllowedScopes": []

**Comment by thiagoloureiro** [comment]
Hi Rob, can you share your code/repo here in GitHub? (If it’s possible) I can take a look
Thanks

**Comment by RobKraft** [comment]
Thanks for the quick response.  Here are the files.  I have changed very little from the default so far.  This is using the Nuget for Ocelot 13.5.2
[APIGateway.zip](https://github.com/ThreeMammals/Ocelot/files/3493465/APIGateway.zip)

**Comment by thiagoloureiro** [comment]
Hi @RobKraft  thanks for sharing the files.

Can you take a look in my repo? I've just updated to 13.5.2 and it's working fine.

You can use it as a start point
(remove consul stuff if you don't need it!)

Cheers mate.

**Comment by RobKraft** [comment]
Thank you sir, that is working for me after I modeled your repo.  I removed the value from my AuthenticationProviderKey, which I don't expect to need anyway: "AuthenticationProviderKey": ""

**Comment by raman-m** [comment]
Great success story!
