### ISSUE TITLE
 Ocelot.Errors.Middleware.ExceptionHandlerMiddleware

### ISSUE THREAD

**Issue by ToeToeAung** [ThreeMammals/Ocelot#995]
I am getting error in ocelot and consul api gateway. Please take a look.
 Ocelot.Errors.Middleware.ExceptionHandlerMiddleware[0]
      requestId: 0HLP7RAM3DIPM:00000002, previousRequestId: no previous request id, message: Exception caught in global error handler, exception message: No such host is known, exception stack:    at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
         at System.Threading.Tasks.ValueTask`1.get_Result()

**Comment by ToeToeAung** [comment]
1.Consul Service Discovery

![image](https://user-images.githubusercontent.com/5344377/63632097-f752bc80-c662-11e9-8d77-544700c7b036.png)

2.API

API is working well. 


![image](https://user-images.githubusercontent.com/5344377/63632102-02a5e800-c663-11e9-9746-433ad50ab263.png)

3. API Gateway

API call in postman : http://localhost:7000/api/getnerateconfigservice/GetClientID

{
    "ReRoutes": [
        {
            "DownstreamPathTemplate": "/api/{everything}",
            "DownstreamScheme": "http",
            "DownstreamPort": 7104,
            "ServiceName": "generateconfigservice",
            "UpstreamPathTemplate": "/api/{everything}",
            "UpstreamHttpMethod": [ "Get" ]
        }
    ],
    "GlobalConfiguration": {
        "ServiceDiscoveryProvider": {
            "Host": "consul",
            "Port": 8500,
            "Type": "Consul"
        }
    }
}


Error encountered

![image](https://user-images.githubusercontent.com/5344377/63632109-12253100-c663-11e9-9c12-e28e20f93a17.png)

**Comment by djrhodes** [comment]
What is ‘consul’ in the Host? Is that in you hostfile? If I’m running
consul locally i’ll point to localhost or 127.0.0.1

**Comment by ToeToeAung** [comment]
Hi @djrhodes , 

I have tried with localhost & 127.0.0.1 as well, It is still getting error.  
I am following the sample as

**Comment by ToeToeAung** [comment]
Hi @TomPallister, 

Could you take a look this. Thanks in advance.

**Comment by winlj** [comment]
ocelot version  is 13.5.2???

**Comment by ToeToeAung** [comment]
Yes. @winlj  I tried test with 13.5.2 and 13.5.0.

**Comment by winlj** [comment]
13.5.1 ok

you  try

**Comment by ToeToeAung** [comment]
Is it because of json file and client call? http://localhost:7000/generateconfigservice/apiname




{
    "ReRoutes": [
        {
            "DownstreamPathTemplate": "/api/{everything}",
            "DownstreamScheme": "http",
            "DownstreamPort": 7104,           
            "UseServiceDiscovery": true,
            "LoadBalancerOptions": { "Type": "RoundRobin" },
            "ServiceName": "generateconfigservice",
            "UpstreamPathTemplate": "/api/generateconfigservice/{everything}",
            "UpstreamHttpMethod": [  "Get" ],
            "ReRoutesCaseSensitive": false

        }
    ],
    "GlobalConfiguration": {    
        "ServiceDiscoveryProvider": {
            "Host": "localhost",
            "Port": 8500,
            "Type": "Consul",
            "PollingInterval": 100
        }
    }
}



        [HttpGet]
        [Route("api/generateconfigservice/GetClientID")]
        [Produces("application/json")]
        public string GetClientID()

**Comment by ToeToeAung** [comment]
7000 port is the for the base Url

**Comment by ToeToeAung** [comment]
Yes. Now I am trying with 13.5.1 and still getting error.

**Comment by winlj** [comment]
o my god

**Comment by ToeToeAung** [comment]
Any error found?

**Comment by ToeToeAung** [comment]
Any issue?

**Comment by djrhodes** [comment]
Hi, sorry you’re still having issues with this. A couple of things don’t seem right. Firstly, the address in your service instance config in Consul is pointing to generateconfigservice:80 (but looks like you’re running the downstream service on localhost:7104)? Though it looks healthy in consul so wouldn’t expect an error. Can you post your consul config including the healthcheck endpoint?

Secondly, as you’re using service discovery you shouldn’t need to specify DownstreamPort in the re route config. Not sure if this causes a problem, but worth taking out anyway.

John

**Comment by ToeToeAung** [comment]
Hi djrhodes,

How can we made a call service using service name?

**Comment by ToeToeAung** [comment]
http://localhost:7000/generateconfigservice/apiname. is it correct way to call?

**Comment by djrhodes** [comment]
Looking at your route config, assuming your gateway is on localhost:7000 it
would be  http://localhost:7000/api/generateconfigservice/getconfigid

**Comment by daisen** [comment]
@ToeToeAung this error is because of  new pull request(#909 ) for ssl failure which changing address to node name

**Comment by ToeToeAung** [comment]
Sorry for late reply. This issue has been solved.

**Comment by ToeToeAung** [comment]
I have fixed by using with correct service registry with specific port and call that service from ocelot api gateway.

**Comment by sumit79sahu** [comment]
hii can u please share the ocelotconfig.json file
