### ISSUE TITLE
Problem with modify request content/body

### ISSUE THREAD

**Issue by timmyyyyy** [ThreeMammals/Ocelot#999]
Hello, I'm trying to modify the request body in ocelot 'PreAuthenticationMiddleware'. Simple code example below.

```
var originalJsonContent = await ctx.DownstreamRequest.Content.ReadAsStringAsync();
var content = JsonConvert.DeserializeObject<dynamic>(originalJsonContent);

content.SomeProperty = "whatever";

string extendedJsonContent = JsonConvert.SerializeObject(content);
ctx.DownstreamRequest.Content = new StringContent(extendedJsonContent, Encoding.UTF8, "application/json");
```

It seems like ocelot is ignoring changes and passing the 'old' unmodified request to the downstream. From the logical point of view if 'DownstreamRequest.Content' has setter, there should be possibility to modify it. Is there a bug or I'm doing something wrong? I have to modify request body after ocelot match specific 'reroute', so I can't do it in 'PreErrorResponderMiddleware' with 'HttpContext.Request.Body' stream.

**Comment by richard-losande** [comment]
Is this issue resolved? encountered it today.

**Comment by raman-m** [comment]
@richard-losande  What issue, Richard? :rofl:

**Comment by raman-m** [comment]
@timmyyyyy 
>I'm trying to modify the request body in ocelot `PreAuthenticationMiddleware`

Did you try to transform content in `PreAuthenticationMiddleware`, really? :smile: :speak_no_evil: 

You must use [Delegating Handlers](https://ocelot.readthedocs.io/en/latest/features/delegatinghandlers.html) to transform content and do other useful things.
You have to read content from downstream in `HttpResponseMessage` object and create/attach new content for the object.
Sounds great?

Have you ever heard about ASP.NET message handlers? :point_down: 
- [HttpClient Message Handlers in ASP.NET Web API](https://learn.microsoft.com/en-us/aspnet/web-api/overview/advanced/httpclient-message-handlers)

------
>Is there a bug or I'm doing something wrong?

You were doing wrong, sure.
Do you still use Ocelot in your projects?
